### ISSUE TITLE
Migrate History Views

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#100]
Move to browserviews, figure out whats up with a metadata file and no image associated with it.

Files:

 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_forms/history_form.pt
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_forms/history_comparison.pt
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_images/history_compare_with_previous_inline.png.metadata

**Comment by jensens** [comment]
outdated - CMFPlone/skins/plone_forms was already removed
