### ISSUE TITLE
Implement fuzzy dates on document_byline viewlet

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1000]
Because they are cool and human readable:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9910049/76212fac-5c71-11e5-9cdf-718af125cb67.png)

**Comment by pbauer** [comment]
:+1: use ```class="pat-moment" data-pat-moment="format:relative"```

**Comment by hvelarde** [comment]
@rodfersou do you want to address this one?

**Comment by rodfersou** [comment]
I can use http://momentjs.com/ with relative time there

**Comment by rodfersou** [comment]
Ok, I'll finish one task first
