### ISSUE TITLE
Do we really need 4 versions of the toolbar?

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1001]
Besides having an horizontal and a vertical toolbars we have the expanded and collapsed versions of both. This creates a lot of overhead and complexity on maintaining the code.

Do we really have time and resources for this or do we better focus on having just enhanced versions of the horizontal and vertical ones only?

**Comment by davilima6** [comment]
My 2c: This has been discussed a couple of months ago and by now lots of effort have been put into achieving a stable and maintainable state. IMO with the "More..." solution and by solving #962 #1002 and other minor glitches we're quite there.

**Comment by jensens** [comment]
I think the question is valid, but also its now in plone 5 and would need a PLIP to change, so I close this here.
