### ISSUE TITLE
Issues when toggling from collapsed to expanded

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1002]
Start with a collapsed horizontal toolbar; expand it:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9910422/71c2bd02-5c73-11e5-923d-6ae660976202.png)

After refreshing everything runs well:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9910439/8076593a-5c73-11e5-9598-404b66ca1440.png)

**Comment by ichim-david** [comment]
@hvelarde  I have a fix for this already in my branch for this ticket
https://github.com/plone/Products.CMFPlone/issues/950 where I deal with a lot of these expand issues.
I will work on this starting from now.

**Comment by hvelarde** [comment]
awesome! thanks a lot!

**Comment by ichim-david** [comment]
Fixed in #950
