### ISSUE TITLE
Dexterity datetime field: start and end of range not stored

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1006]
Dexterity type editor -> add a datetime field and set the start and end date to some date...save the field and re-edit it ("settings"). The widgets for the start and end of range are empty. Is this intentional?

**Comment by pbauer** [comment]
I guess setting a default date for a datefield would not make a lot of sense in all use-cases I can think of at the moment (since time passes...) but it could also be a bug.

**Comment by keul** [comment]
I think is related to this very ugly bug: https://github.com/plone/mockup/issues/576

**Comment by thet** [comment]
Fixed here Plone 5.1: https://github.com/plone/mockup/pull/726 and Plone 5.0: https://github.com/plone/mockup/pull/727
