### ISSUE TITLE
Duplicated menu item on toolbars

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1007]
When you select one of the options of the menu you will see the title of the option duplicated as the first item on the list; this happens in both versions:

![selection_006](https://cloud.githubusercontent.com/assets/341393/9914620/10a229fc-5c89-11e5-9de9-03cfe6633d78.png)

![selection_007](https://cloud.githubusercontent.com/assets/341393/9914621/10a7f17a-5c89-11e5-9018-21d59e9cd055.png)

![selection_004](https://cloud.githubusercontent.com/assets/341393/9914618/1096a550-5c89-11e5-9511-bc82c6d772e6.png)

![selection_005](https://cloud.githubusercontent.com/assets/341393/9914619/10982fa6-5c89-11e5-9c97-6b19fe8e8fa4.png)

**Comment by davilima6** [comment]
+1

I think that was useful when "More options" toolbar icon brought both Portlet management and Display menu links.

**Comment by ichim-david** [comment]
@hvelarde  I am not so bothered about this. As I've mentioned in #950 you could easily hide the extra header with a css rule.

Why I still think it's useful to have is in this situation:
- You are with the top toolbar and you use the content-menus which will crop the full title.
  At least in the dropdown the title is visible

See screenshot for better understanding
![extra-header](https://cloud.githubusercontent.com/assets/152852/9915568/6ee21414-5cc0-11e5-86c4-dbe949fd9720.png)

**Comment by hvelarde** [comment]
@ichim-david I think it would be better to replace those with tooltips as @davilima6 suggested in some other issue.

**Comment by davilima6** [comment]
I see, @ichim-david. In that case I believe we'd be good with:

    .plone-toolbar-expanded .plone-toolbar-submenu-header { display: none; }

Agree?

**Comment by ichim-david** [comment]
@davilima6  yes this could be an easy fix for this problem since it's really on the expanded section that it really feels out of place because of the "duplicated" content.

Any of you could commit such a hiding if there is consent from others as well that this is really bothersome and needs to go away.

**Comment by polyester** [comment]
Give me some time to pingpong this to some screenreader users; tooltips are not always as well supported whereas hiding them with CSS could be an easier way out for those who feel bothered by it.

**Comment by polyester** [comment]
Tooltips are not well supported for a11y, and having the menu title in the submenu can also be used to have a complete menu title for languages that can only have an abbreviated version in the toolbar; this also helps those with cognitive issues. 
I would be hesitant to  remove. If your site does not require strict a11y adherence, it's a `display: none` away for your theming person to remove them, if they bother you esthetically.

**Comment by davisagli** [comment]
This didn't reach a clear conclusion and hasn't been touched in a few years. I'll close it but feel free to reopen.
