### ISSUE TITLE
Allow merging CHANGES.rst with union strategy.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1008]
Seen in bobtemplates.plone.

We can create a file `.gitattributes` in Products.CMFPlone (and other packages), with these contents:

```
CHANGES.rst merge=union
```

This then uses a different merge strategy for the CHANGES.rst file. This should give less merge conflicts and so github will not complain `This branch has conflicts that must be resolved`.  So there is less need for people to rebase their branch.  Sounds helpful to me.

Without this file, when I try merging pull request #993, it gives a conflict that you have to solve manually:

```
5.0rc3 (unreleased)
-------------------

<<<<<<< HEAD
- Add view @@hero to be included by plonetheme.barceloneta with diazo.
  [pbauer]

- Fix #991: improve contrast for pending state in tollbar.
  [pabo3000]
=======
- remove unused code to create NavTree probably left from Plone 3.0 times 
  and since a while handled by plone.app.portlets.
  [jensens]
>>>>>>> origin/jensens-remove-unused-navtree-code
```

When I add that `.gitattributes` file locally and try merging that same pull request, it works without conflict:

```
5.0rc3 (unreleased)
-------------------

- Add view @@hero to be included by plonetheme.barceloneta with diazo.
  [pbauer]

- Fix #991: improve contrast for pending state in tollbar.
  [pabo3000]
- remove unused code to create NavTree probably left from Plone 3.0 times 
  and since a while handled by plone.app.portlets.
  [jensens]

- Implement new feed syndication using `NewsML 1 <http://iptc.org/standards/newsml-1/>`_,
  an IPTC standard that provides a media-type-independent, structural framework for multi-media news.
  [frapell, jpgimenez, tcurvelo, rodfersou]

```

Small downside is that an empty line is missing between two changelog messages. But this has no effect on the resulting restructuredText, so should be fine. Can easily be fixed afterwards by the next person who actually adds a changelog entry.

Note that this is only feasible for files where the exact order does not matter. For Python files, zcml, etc, this is never a good idea.

Shall we do this?

**Comment by hvelarde** [comment]
awesome! +1

**Comment by mauritsvanrees** [comment]
Done.

Note that I do not know if github itself supports this in the UI. At the moment, in the pull request I mentioned I still see 'This branch has conflicts', so maybe not. But should help nicely for the command line.
