### ISSUE TITLE
Linkintegrity check does not cover all possible cases

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1010]
For linkintegrity in Plone I see 3 use cases:
1. Internal links in Richtext
2. Related objects (Edit a "Page" content object -> go to tab "Categorization" -> Link an object in "Related Items" -> delete referenced object)
3. Link objects (Create a "Link" content object -> reference an object in URL -> delete referenced object)

While Linkintegrity works for 1 it does not work for 2 and 3 at the moment (Plone 5.0rc2).

**Comment by pbauer** [comment]
I would like to add support for static text-portlets and link-objects that reference internal content. 

I think relations using relatedItems are resolved (=removed) automatically and without asking. I don't think it's necessary to change that behavior but I'm open to discussion.

**Comment by tomgross** [comment]
Probably we don't need to implement this all in core. All we need is a plugable solution. Possibly like here: https://bitbucket.org/gocept/gocept.linkchecker/src/80a127405ac06d2054e61dd62fcd643d864357a0/src/gocept/linkchecker/retrievers.py?at=default&fileviewer=file-view-default

**Comment by hvelarde** [comment]
what about Rich Text tiles?

**Comment by pbauer** [comment]
Yes, I forgot about Richtext tiles. 
I will not have time to work on that before november. So if someone else would want to do it, please go ahead!

**Comment by tomgross** [comment]
A more flexible solution is here: https://github.com/plone/plone.app.linkintegrity/pull/31

**Comment by jensens** [comment]
i think this is pluggable now
