### ISSUE TITLE
Plone ships a LOT of JavaScript in logged in mode

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1011]
In anonymous mode the startpage of a freshly installed Plone 5.0rc2 is 638.2 KB. It could be less but is acceptable.
In logged in mode the size of the response is **2.2 MB!** Is this really all needed?
![17-09-2015 09-08-17](https://cloud.githubusercontent.com/assets/339384/9927144/4dc4656e-5d1c-11e5-9582-ae6096e0ed75.png)

**Comment by vangheem** [comment]
Keep in mind, plone bundles ALL background images and fonts inline(for the css) so there are less HTTP requests. 

Part of the problem, as far as how the js is bundled and how requirejs works with dependency management, a lot of the javascript in the plone bundle is duplicated in the plone-logged-in bundle when it is built--not sure there is a way around that.

**Comment by jcerjak** [comment]
Would perhaps tools like [AMD Clean](https://github.com/gfranko/amdclean#why) or [Almond](https://github.com/jrburke/almond#why) help? Not sure how much we would gain and if it's possible to integrate them with the new registry though..

**Comment by davilima6** [comment]
Another part of the problem, if I'm not mistaken, is due to the fact we're distributing large frameworks such as Backbone.js (for pagination at least) and React (JSW compiler, at least, even though it seems deprecated in favor of Babel REPL...)

**Comment by vangheem** [comment]
The only framework that is getting compiled into our bundles is backbone and I think it is only included for the logged in bundle.

Modern JavaScript also compiled in chunks of html. I imagine a decent size of our bundles are html templates. 

Latest plone provides stub module settings on the bundles to prevent re-bundling the same js modules. This helps on shipped size a bit.

I'm going to close the issue unless there is something specific about an actual problem besides, "it ships with lots of JS". Feel free to re-open and yell if you disagree.
