### ISSUE TITLE
Dexterity Control Panel: No icons

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1013]
After a fresh install, there are no icons for the content types on the Dexterity control panel.

![dexterity-controlpanel_no_icons](https://cloud.githubusercontent.com/assets/170891/9929611/323ad2bc-5d2e-11e5-9e99-6d8e2d97f3b5.png)

**Comment by hvelarde** [comment]
+1

**Comment by pbauer** [comment]
The fti's if p.a.c have no property ```icon_expr``` e.g. ```<property name="icon_expr">string:${portal_url}/document_icon.png</property>```
Weird.

**Comment by pabo3000** [comment]
And the fti icon would not be displayed. But if you fix types_listing_row.pt then icons of custom dexterity would be visible. On the other hand icons in the p.a. toolbar are shown for p.a.contenttypes. But these are less style information. So: a custom dx contentype will have no icon in the toolbar.

It would be rather great if one can choose a fontello icon or provide a gif by the fti for a custom dx contenttype. And of course it should be visible in the controlpanel and the toolbar

**Comment by pabo3000** [comment]
I believe the icon should remain part of the FTI.

The FTI could be like in Plone 4:
```
<property name="icon_expr">string:${portal_url}/++resource++collective.foo/mydxct_icon.png</property>
```
or  a icon letter:
```
<property name="icon_expr">string:\e80f</property>
```
In the p.a.toolbar we add a span with \e80f and delete the style info contents.plone.less.
In p.a.contentypes we add the icons in the fti.

What do you think?

**Comment by fgrcon** [comment]
should be solved soon: see screenshots at  https://github.com/plone/Products.CMFPlone/issues/1151
