### ISSUE TITLE
Inconsistency between portal and folder

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1014]
Since the portal is based on CMFCore.PortalFolder and folders are based on plone.folders some behaviors (like WebDAV upload see https://github.com/plone/Products.CMFPlone/issues/487) are handled differently. This should be normalized.

**Comment by jensens** [comment]
I close this one. There is a PLIP now with more details to https://github.com/plone/Products.CMFPlone/issues/2454
