### ISSUE TITLE
Resourcetype settings for "contains Objects" in tinymce controlpanel are not respected for folderish custom dexterity types

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1023]
**In a tinymce textarea one can not select contents of such a folderish type**
relates to: plone 5.0rc2 / current coredev

# Steps to reproduce
* create a folderish dexterity type (eg: copy Folder to Folder1) (either ttw or by an addon product)
* add type to tinymce settings
![image](https://cloud.githubusercontent.com/assets/1640384/9957944/f1b0e1d2-5e04-11e5-9b5e-3fb52c2524fd.png)

* add an instance folder1-1 of this type to your site
* add some new items to  folder1-1 (images, pages)
* create a testpage some where on the site 
* try to insert an image via tinymce:
   **folder1-1 is not found....**
 or try to create a link ..
   **folder1-1 can not be expanded**
   
![image](https://cloud.githubusercontent.com/assets/1640384/9957874/32710af4-5e04-11e5-9427-381608c2eb77.png)

**Comment by pbauer** [comment]
The setting is correctly picked up by `plone.app.widgets.utils.get_tinymce_options` from the tinymce-controlpanel but aparently not respected in the pattern itself.
