### ISSUE TITLE
Search portlet ignores live search checkbox

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1025]
Plone 5.0rc2 /current coredev

![image](https://cloud.githubusercontent.com/assets/1640384/9958668/aa1ff0f8-5e0c-11e5-851d-b3d395f971aa.png)

but live search not working.

**Comment by hvelarde** [comment]
AFAIK, that never was implemented; +1 but we need to know if everybody agree.

@rodfersou this one involves JS :-)

**Comment by fgrcon** [comment]
I could live without live search. Either remove the option or provide live search. Just a matter of not to make users confused. :-)

**Comment by fgrcon** [comment]
fixed with https://github.com/plone/plone.app.portlets/pull/71 . Thanks @agitator !
