### ISSUE TITLE
The development mode check in Resource Registries enable the Diazo bundle browser compilation.

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#1029]
When you enable the "Development mode" in resource registries you always get the Diazo bundle of the current theme compiled in browser. If you are developing other parts you have no choice but have it and as it takes time, the development experience is horrible. I think that the compilation of the Diazo bundle should match the experience of the other bundles. 

The Diazo bundle concept itself is totally hidden from the Plone UI, and maybe it's good to show that a Diazo bundle is in place (for example by adding below the RR bundle list, as it takes effect the last), and add a button like the other bundles to compile it in browser or statically).

@vangheem @bloodbare what do you think? Is there any reason for the development mode behave this way?

**Comment by bloodbare** [comment]
If you are editing some mockup js/less and you don't want the diazo bundle to be executed on development you can disable the diazo on throw the URL! 

Adding diazo bundle on the resource registry UI to put it in development would mean some "strange" behavior when the diazo bundle is not on the configuration registry. 

At least is how I seee

**Comment by davisagli** [comment]
TTW compilation of bundles was removed in Plone 6
