### ISSUE TITLE
Use rem and em instead of px and %

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1032]
Since we have many user agents that use our page (mobile phones, tablets and desktop), px size is not always the best choice.

We should use `rem` and `em` instead, that is a size relative to the font size, and will work better on any user agent.

In Plone 5 layout, `1rem == 10px`, so we can do a fast conversion like `24px` will be `2.4rem`.

For font size, instead of using `85%` we should use `0.85em` (or `0.85rem`, which is usually more predictable)

**Comment by rodfersou** [comment]
@vangheem what do you think about it?

**Comment by thet** [comment]
Sounds like a pretty good idea, if it works out!

**Comment by davisagli** [comment]
Keep in mind browser support for `rem` is a bit limited http://caniuse.com/#feat=rem

**Comment by rodfersou** [comment]
@davisagli thank you to point that link, coping the known issues here:

1. IE 9, 10 and 11 do not support rem units when used in the "line-height" property when used on :before and :after pseudo elements (https://connect.microsoft.com/IE/feedback/details/776744).
2. Borders sized in "rem" disappear when the page is zoomed out in Chrome.
3. Reportedly does not work on Android 4.3 browser for Samsung Note II or the Samsung Galaxy Tab 2 on Android 4.2.
4. Chrome 31-34 & Chrome-based Android versions (like 4.4) have a font size bug that occurs when the root element has a percentage-based size.
5. Causes content display and scrolling issues on iPhone 4 which typically has Safari 5.1.

**Comment by rodfersou** [comment]
Anyone can point me what versions of browsers will Plone 5 support?

@esteele @polyester ?

**Comment by vangheem** [comment]
IE9+

**Comment by polyester** [comment]
phones are an important target, so we'd need to check some statistics on what older SafariMobile and Android browsers are still in large use.

**Comment by rodfersou** [comment]
@vangheem here we support the last 3 versions of every browser.. so with the release of win10 we just need to support win10+.

For example, we can use [flexbox](http://caniuse.com/#feat=flexbox) on our projects using the right [vendor prefixes and fallbacks](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_flex-box.scss)

**Comment by vangheem** [comment]
Quite a few US government agencies use plone and are on IE9 still. We made a decision quite a while ago to support IE9+ so I hope we don't change that at this point.

**Comment by polyester** [comment]
We have said IE9+, and that it should remain for 5.0. I will try to get a reasonable cross-section of mobile browser versions tested (have account on testing service) and document accordingly, but for desktop it's IE9+, Firefox 31 ESR+ (38ESR + recommended), Chrome recent version.

**Comment by rodfersou** [comment]
@polyester talking about mobile, other open CMS systems did an app to update the CMS with a cellphone, available into the cellphone market.

Maybe we can start a project for Plone App using the https://github.com/plone/plone.restapi and http://lab.ionic.io/

**Comment by jensens** [comment]
this should go into a new theme. maybe volto is the right place, i close it here
