### ISSUE TITLE
Recurrence widget is using date widgets that are not consistent with the other (nicest) date widgets in Plone

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#1033]
<img width="405" alt="screen shot 2015-09-18 at 19 19 50" src="https://cloud.githubusercontent.com/assets/486927/9966020/86e5fa46-5e3a-11e5-8850-c1dd76e416ed.png">

**Comment by davisagli** [comment]
In Plone 6 classic the browser date widget is used in both places.
