### ISSUE TITLE
Deprecation warnings re: portal_url in scripts.py and styles.py

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1034]
I see several deprecation warnings like the following in the master branch of Products.CMFPlone:

```
.../Products.CMFPlone/Products/CMFPlone/resources/browser/scripts.py:87: DeprecationWarning: Use site_url instead. ViewletBase.portal_url will be removed in Plone 4
  self.portal_url,
```

**Comment by mauritsvanrees** [comment]
@polyester this was not merged yet, so should probably stay open. It should close automatically when merged, due to the reference.

**Comment by polyester** [comment]
@mauritsvanrees thanks. Overzealous while triaging for blockers
