### ISSUE TITLE
Add a div arround JavaScript for web statistics

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1036]
To make it easier when writing a Diazo rule to copy scripts from plone configuration:

![webstatics](https://cloud.githubusercontent.com/assets/131209/9970878/871a7156-5e2e-11e5-997b-654eca9c1b48.png)

![webstatics2](https://cloud.githubusercontent.com/assets/131209/9970991/3b070788-5e2f-11e5-845c-541984f05ea7.png)

We should add a div around, like in [this example from plonegovbr](https://github.com/plonegovbr/brasil.gov.portal/commit/c9af2f6c5b7eacb51870a8b5d6956cf61b3832c6)

``` python
class AnalyticsViewlet(AnalyticsViewletBase):
    def render(self):
        """render the webstats snippet adding a div arround it
        """
        ptool = getToolByName(self.context, 'portal_properties')
        snippet = safe_unicode(ptool.site_properties.webstats_js)

        # Putting a div arround the snippets
        div = html_builder.DIV({'id': 'plone-analytics'})  # create the div
        tags = html_fromstring(snippet)  # parse the snippets from html to lxml classes
        div.extend(tags)  # insert the tags into the div
        snippet = safe_unicode(html_tostring(div))  # convert back to string the new tag
        # Putting a div arround the snippets

        return snippet
```

**Comment by hvelarde** [comment]
+1

**Comment by davisagli** [comment]
Done in https://github.com/plone/plone.app.layout/pull/220
