### ISSUE TITLE
Default format in @@markup-controlpanel is not honored

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1038]
1. Go to `@@markup-controlpanel`.
2. Tick one of the non-default formats under _Alternative formats_, e.g. `text/restructured`
3. Select the format checked in 2. as the new Default.
4. Save.

Now edit any content that has some body text, or create a new page:  you still get TinyMCE and the select field underneath is set to `text/html`.

**Comment by fulv** [comment]
This works in Plone 4.3.6.

**Comment by ale-rt** [comment]
This looks fixed to me
