### ISSUE TITLE
plone_images: clean up, dump, modernize?

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#104]
RE: https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/skins/plone_images

Some if the things in plone_images need to go to sunburst, and some need to go to... I don't know. A lot of these are from back in the day when we didn't have sprints 

When in doubt, just delete it. These icons all need modernizing and the css that does with them as well. There are ones of particular interest that we should be careful about, for example anything that kss or javascript needs to display interaction (content tree +/-, spinners, ...what else?).

I would actually be pretty happy to see someone update the entire default icon set to something modern, sprited, and all css overlaid but thats up to the expert themers in the community. Everything in this directory falls under "plone theme" EXCEPT, some tool icons (which we see in the ZMI). 

Tool icons can stay until we have no more tools. If there is a way to get those to point to actual resources then all the better.

Don't forget to delete the directory registration when its empty.

**Comment by vangheem** [comment]
Removed as many as possible.
