### ISSUE TITLE
Default ootb collections have no type criteria

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1040]
The events/aggregator and news/aggregator collections that come with a fresh Plone site seem to have empty type criteria set.  There is one line of criteria, and the first select box says "Type", but the value select box is empty.  Moreover, there are no types available to select.

However, if I add some future events to the site and publish them, the Events collection "View" shows them.  But they do not show up in the Preview list in edit mode.  Also, any private events are not shown, which indicates that there is also a workflow state criterion set in the collection, but it's not visible.

<img width="552" alt="screen shot 2015-09-18 at 6 45 31 pm" src="https://cloud.githubusercontent.com/assets/460742/9974084/4fd04754-5e36-11e5-9da1-926669ce8208.png">

**Comment by mauritsvanrees** [comment]
Problem is that we are setting the old `plone.app.querystring.operation.selection.is` instead of the new `plone.app.querystring.operation.selection.any`.

**Comment by mauritsvanrees** [comment]
I will make a few pull requests that belong together.

**Comment by mauritsvanrees** [comment]
BTW, workaround for existing sites: go to portal_setup and reapply the last plone.app.querystring upgrade steps, the ones that migrate from revision 11 to 13.

**Comment by mauritsvanrees** [comment]
This is the list of pull requests:

```
https://github.com/plone/Products.ATContentTypes/pull/27
https://github.com/plone/plone.app.contenttypes/pull/300
https://github.com/plone/mockup/pull/613
https://github.com/plone/plone.app.contentlisting/pull/12
https://github.com/plone/plone.app.discussion/pull/76
https://github.com/plone/plone.app.event/pull/207
https://github.com/plone/plone.app.querystring/pull/57
https://github.com/plone/Products.CMFPlone/pull/1259
```

Jenkins for all those together: http://jenkins.plone.org/job/pull-request-5.0/582/

**Comment by mauritsvanrees** [comment]
Jenkins is not finished yet, but let's start another one as I added migration.
http://jenkins.plone.org/job/pull-request-5.0/583/

**Comment by fulv** [comment]
:clap:

**Comment by mauritsvanrees** [comment]
Both Jenkins runs passed successfully.

**Comment by gforcada** [comment]
Merged the ones that do not have merge conflicts so far. Great job as usual!

**Comment by gforcada** [comment]
All of them merged! Great work!

**Comment by mauritsvanrees** [comment]
Thanks for merging, Gil!
