### ISSUE TITLE
eventually remove dependency on p.a.widgets for plone 5

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1049]
AFAIK, the plone.app.widgets dependency can be removed completly, after the remaining functionality is moved into plone.app.content/plone.app.vocabularies/plone.app.z3cform.
Or was there a good reason to keep plone.app.widgets in Plone 5, @vangheem ?

**Comment by vangheem** [comment]
We decided to keep it for some of its base classes and utilities. Need a
package that both archetypes and z3c form can depend on.

**Comment by thet** [comment]
OK, that makes sense.
