### ISSUE TITLE
Remove leftovers of Products.TinyMCE in Plone 5

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1051]
Products.TinyMCE was replaced by a pattern. In buildout.coredev 5.0 there is still a reference in sources.cfg and also versions.cfg references it. Translations are also still merged in 5.0. 
This will lead to confusion - and need to be cleaned up.

**Comment by jensens** [comment]
TODO: check translations

**Comment by erral** [comment]
I see that plone.app.locales' widgets.pot contains tinymce strings:

https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/widgets.pot#L736

So tinymce translation should be handled in plone.app.locales.

**Comment by vincentfretin** [comment]
right, it's in widgets.po

**Comment by saily** [comment]
There are several problems if you have a dependency for `Products.TinyMCE` in Plone 4.3 and want to upgrade. For example imports of `plone.fieldset` which is `zope.formlib` related. 
https://github.com/plone/Products.TinyMCE/blob/master/Products/TinyMCE/browser/controlpanel.py#L7

This should have been removed [within this ticket](https://github.com/plone/Products.CMFPlone/issues/537#issuecomment-107843729) and mentioned in an upgrade guide.
