### ISSUE TITLE
Fix traceback message

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1053]
Traceback message becomes ilegible:
![traceback_before](https://cloud.githubusercontent.com/assets/131209/9992642/c23d329c-6049-11e5-9669-844c4e46bbe7.png)

if add a `whitespace: pre` into this tag css it will look a lot better:

![traceback_after](https://cloud.githubusercontent.com/assets/131209/9992659/e3230bda-6049-11e5-860a-a883464edf0d.png)

**Comment by davisagli** [comment]
+1

David Glick
(mobile)
