### ISSUE TITLE
sync translations for plonefrontpage

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1057]
The i18n-domain `plonefrontpage` is not synced. Can someone from the i18n-team please sync them?

I found out since there are broken links in the generated frontpage in german (`@@skins-controlpanel` instead of `@@theming-controlpanel`).

**Comment by vincentfretin** [comment]
There is no automatic way of resyncing the plone/app/locales/locales/plonefrontpage.pot file.
You need to update plonefrontpage.pot manually and resync the po files afterwards with i18ndude.

**Comment by vincentfretin** [comment]
I fixed all the links in existing translations
https://github.com/collective/plone.app.locales/commit/065fe57f9bee7910d3dcde1c1b8ddc11e1675156
and resynced manually the plonefrontpage.pot
https://github.com/collective/plone.app.locales/commit/8c291a04810da0e05b4d5fd367a7fee6d4ea88fe

**Comment by vincentfretin** [comment]
I resynced manually all the plonefrontpage.po and didn't mark the message as fuzzy.
Translators, even if I fixed the old links, you should look at the changes https://github.com/collective/plone.app.locales/commit/8c291a04810da0e05b4d5fd367a7fee6d4ea88fe you may want to update your translation accordingly.
