### ISSUE TITLE
Not all controlpanels are moved to 

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1064]
When migrating a site from 4.3.6 to 5.0rc3 these controlpanels are still listed in the section "Plone-Configuration" instead of "General":
- filter-controlpanel
- imaging-controlpanel
- mail-controlpanel
- language-controlpanel
- discussion-settings

**Comment by tisto** [comment]
fyi: discussion-settings has been renamed to discussion-controlpanel. The old view is still available for bbb though.

**Comment by jensens** [comment]
is this still a thing?

**Comment by davisagli** [comment]
We are no longer maintaining the upgrade steps from Plone 4 -> 5
