### ISSUE TITLE
unable to save changes made in site setup  Plone 5.0rc2 (5009)

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1065]
i am exploring the Plone 5.0rc2 (5009). when i make changes into the site setup, for example the TinyMCE options or any other things it does not get saved.
i have not made any alterations yet into the out of box. i had earlier tried selecting the language selection also. basically nothing is getting saved once i make the selections.

**Comment by sudhan77** [comment]
i am using windows 7 and chrome browser on  my desktop. my site is hosted in a cloud server, ubuntu14.04. it is a standalone install

**Comment by vangheem** [comment]
Anything in the log?

**Comment by sudhan77** [comment]
vangheem, I am a lame user. you will need to guide me to check specific things. In the meanwhile i have installed rc3. will recheck the same issues in rc3 and any logs and post in a while

**Comment by sudhan77** [comment]
no errors in the log. just checked with rc2. will check with rc3 once i upgrade

**Comment by prakharjoshi** [comment]
@sudhan77  Please provide the logs when you run site in foreground mode . For running site in fg mode you have to restart the zope server using `./bin/instance fg` and check the terminal when you try to save things using tinyMCE .

**Comment by sudhan77** [comment]
ssp@mail:/opt/plone/zinstance$ sudo bin/instance fg
Traceback (most recent call last):
  File "/opt/plone/zinstance/parts/instance/bin/interpreter", line 276, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 79, in prepare
    self.setupServers()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 214, in setupServers
    % (server.servertype(),e[1]))
ZConfig.ConfigurationError: There was a problem starting a server of type "HTTPServer". This may mean that your user does not have permission to bind to the port which the server is trying to use or the port may already be in use by another application. (Address already in use)
ssp@mail:/opt/plone/zinstance$

**Comment by sudhan77** [comment]
i ran the instance in fg and then tried to make specific changes to tinyMCE in siteset up. On saving, i got the message as saved. but when i go back to the plugins page the changes are not saved. no error seen

**Comment by fulv** [comment]
Before running in fg, you must stop the running instance:

bin/instance stop

That error tells you that there is already some other process listening on
the port your instance is configured to listen on.
https://www.youtube.com/watch?v=sqcLjcSloXs

**Comment by prakharjoshi** [comment]
@fulv  Nice one  +1.  ;)

**Comment by vangheem** [comment]
I still can not reproduce.

Closing for now until more information is provided but please reopen when more information is provided and we can see if there is a problem more.

Things for you to try:

- try again following the info on running with fg mode
- create a video showing the problem
- provide your config files base.cfg and buildout.cfg
- provide contents of your event log(can be found in /opt/plone/zinstance/var/instance)

**Comment by sudhan77** [comment]
please find the files attached


i dont find any event log:
root@mail:~# cd /opt/plone/zinstance/var/instance
root@mail:/opt/plone/zinstance/var/instance# dir
import
root@mail:/opt/plone/zinstance/var/instance#


On Fri, Sep 25, 2015 at 9:02 AM, Nathan Van Gheem <notifications@github.com>
wrote:

> Closed #1065 <https://github.com/plone/Products.CMFPlone/issues/1065>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1065#event-418794727>.
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
ISSUE RESOLVED IN MY LATEST INSTALL. Thanks

On Fri, Sep 25, 2015 at 10:20 AM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> please find the files attached
>
>
> i dont find any event log:
> root@mail:~# cd /opt/plone/zinstance/var/instance
> root@mail:/opt/plone/zinstance/var/instance# dir
> import
> root@mail:/opt/plone/zinstance/var/instance#
>
>
> On Fri, Sep 25, 2015 at 9:02 AM, Nathan Van Gheem <
> notifications@github.com> wrote:
>
>> Closed #1065 <https://github.com/plone/Products.CMFPlone/issues/1065>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/plone/Products.CMFPlone/issues/1065#event-418794727>.
>>
>
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu
