### ISSUE TITLE
issues with the login popup window

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1066]
some issue with the ajax window. pls check. 5.0rc3. chrome browser. windows 7 os. the login window works fine though.

![image](https://cloud.githubusercontent.com/assets/10380993/10051060/3963466e-623d-11e5-8da8-2eb59306a880.png)

**Comment by sudhan77** [comment]
this is rc2 only. the upgrade did not take place perhaps. will update

**Comment by vangheem** [comment]
I can not reproduce this.

The bug is very odd and I have no idea how that would happen. Part of the page template is being rendered with the result document but it's still working? Very odd.

How have you installed Plone?

**Comment by vangheem** [comment]
Ahh, I see. There was debug code in that form.

Was fixed here: https://github.com/plone/Products.CMFPlone/commit/ecf239bc1cc5de5706c2ac7d7c3d335159737d5e

And I was testing latest which already had the fix.

**Comment by sudhan77** [comment]
ISSUE RESOLVED IN MY LATEST INSTALL

On Fri, Sep 25, 2015 at 9:11 AM, Nathan Van Gheem <notifications@github.com>
wrote:

> Ahh, I see. There was debug code in that form.
>
> Was fixed here: ecf239b
> <https://github.com/plone/Products.CMFPlone/commit/ecf239bc1cc5de5706c2ac7d7c3d335159737d5e>
>
> And I was testing latest which already had the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1066#issuecomment-143113471>
> .
>



-- 
Sudhanshu
