### ISSUE TITLE
upgrade from 5.0rc2 to 5.0rc3

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1069]
i have tried to upgrade to plone 5.0rc3. pls check the following to confirm if the buildout process was correct. if it was correct, why is the version in the site setup still showing plone 5.0rc2. i ran the buildout and restarted the server.

    ssp@mail:/opt/plone/zinstance$ sudo nano buildout.cfg
    ssp@mail:/opt/plone/zinstance$ sudo -u plone_buildout bin/buildout
    Uninstalling precompiler.
    Uninstalling instance.
    Installing instance.
    /opt/plone/zinstance/local/lib/python2.7/site-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
      stacklevel=1,
    Getting distribution for 'Plone==5.0rc3'.
    warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

    Got Plone 5.0rc3.
    Getting distribution for 'Products.ResourceRegistries==3.0.3'.
    warning: no files found matching '*.txt'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    Got Products.ResourceRegistries 3.0.3.
    Generated script '/opt/plone/zinstance/bin/instance'.
    Generated interpreter '/opt/plone/zinstance/parts/instance/bin/interpreter'.
    Generated script '/opt/plone/zinstance/bin/pilprint.py'.
    Generated script '/opt/plone/zinstance/bin/pilconvert.py'.
    Generated script '/opt/plone/zinstance/bin/pilfont.py'.
    Generated script '/opt/plone/zinstance/bin/pilprint.pyc'.
    Generated script '/opt/plone/zinstance/bin/pilfile.pyc'.
    Generated script '/opt/plone/zinstance/bin/pilconvert.pyc'.
    Generated script '/opt/plone/zinstance/bin/pilfile.py'.
    Generated script '/opt/plone/zinstance/bin/pilfont.pyc'.
    Generated script '/opt/plone/zinstance/bin/pildriver.pyc'.
    Generated script '/opt/plone/zinstance/bin/pildriver.py'.
    Updating repozo.
    Generated script '/opt/plone/zinstance/bin/repozo'.
    Updating backup.
    Updating zopepy.
    Generated interpreter '/opt/plone/zinstance/bin/zopepy'.
    Updating unifiedinstaller.
    Installing precompiler.
    Compiling Python files.
    Compiling locale files.
    Updating setpermissions.
    setpermissions: Running # Dummy references to force this to execute after referenced parts
    echo /opt/plone/zinstance/var/backups yes > /dev/null
    chmod 600 .installed.cfg
    # Make sure anything we've created in var is r/w by our group
    find /opt/plone/zinstance/var -type d -exec chmod 770 {} \; 2> /dev/null
    find /opt/plone/zinstance/var -type f -exec chmod 660 {} \; 2> /dev/null
    find /opt/plone/zinstance/var -type d -exec chmod 770 {} \; 2> /dev/null
    find /opt/plone/zinstance/var -type f -exec chmod 660 {} \; 2> /dev/null
    chmod 754 /opt/plone/zinstance/bin/*
    chmod: changing permissions of ‘/opt/plone/zinstance/bin/buildout’: Operation not permitted
    Versions had to be automatically picked.
    The following part definition lists the versions picked:
    [versions]
    plone.recipe.command = 1.1
    plone.recipe.precompiler = 0.6
    ssp@mail:/opt/plone/zinstance$ sudo supervisorctl stop plone5server
    plone5server: ERROR (not running)
    ssp@mail:/opt/plone/zinstance$ sudo supervisorctl start plone5server
    plone5server: started

![image](https://cloud.githubusercontent.com/assets/10380993/10052230/7bb99422-6243-11e5-9e31-10f440688417.png)

**Comment by jensens** [comment]
did you execute the upgrade for the instance? You should find information about it at http://youripadress:8090/

**Comment by vangheem** [comment]
You need to run the upgrade. Go to http://youripadress:8090/ or http://youripadress:8090/manage

**Comment by sudhan77** [comment]
the following errors were seen

Site Error

An error was encountered while publishing this resource.

*Error Type: ImportError*
*Error Value: No module named _tkinter, please install the python-tk
package*
*i installed the above then i get the following error:*

ite Error

An error was encountered while publishing this resource.

*Error Type: ImportError*
*Error Value: No module named _winreg*



On Fri, Sep 25, 2015 at 8:55 AM, Nathan Van Gheem <notifications@github.com>
wrote:

> You need to run the upgrade. Go to http://youripadress:8090/ or
> http://youripadress:8090/manage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1069#issuecomment-143112223>
> .
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
Time2015/09/25 09:30:14.527764 GMT+0530User Name (User Id)admin (admin)Request
URLhttp://128.199.230.56:8090/Control_Panel/DebugInfo/manage_mainException
TypeImportErrorException ValueNo module named _winreg

Traceback (innermost last):

   - Module ZPublisher.Publish, line 138, in publish
   - Module ZPublisher.mapply, line 77, in mapply
   - Module ZPublisher.Publish, line 48, in call_object
   - Module Shared.DC.Scripts.Bindings, line 322, in __call__
   - Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
   - Module App.special_dtml, line 185, in _exec
   - Module DocumentTemplate.DT_In, line 630, in renderwob
   - Module DocumentTemplate.DT_Util, line 210, in eval
   __traceback_info__: refcount
   - Module <string>, line 1, in <module>
   - Module App.ApplicationManager, line 167, in refcount
   - Module pip._vendor.six, line 90, in __get__
   - Module pip._vendor.six, line 113, in _resolve
   - Module pip._vendor.six, line 80, in _import_module

ImportError: No module named _winreg

On Fri, Sep 25, 2015 at 9:33 AM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> the following errors were seen
>
> Site Error
>
> An error was encountered while publishing this resource.
>
> *Error Type: ImportError*
> *Error Value: No module named _tkinter, please install the python-tk
> package*
> *i installed the above then i get the following error:*
>
> ite Error
>
> An error was encountered while publishing this resource.
>
> *Error Type: ImportError*
> *Error Value: No module named _winreg*
>
>
>
> On Fri, Sep 25, 2015 at 8:55 AM, Nathan Van Gheem <
> notifications@github.com> wrote:
>
>> You need to run the upgrade. Go to http://youripadress:8090/ or
>> http://youripadress:8090/manage
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/plone/Products.CMFPlone/issues/1069#issuecomment-143112223>
>> .
>>
>
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
repasting above:



Site Error Log Site Error Log at  /error_log
Exception traceback

 Return to log 
Time	2015/09/25 09:30:14.527764 GMT+0530
User Name (User Id)	admin (admin)
Request URL	http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main
Exception Type	ImportError
Exception Value	No module named _winreg
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module App.special_dtml, line 185, in _exec
Module DocumentTemplate.DT_In, line 630, in renderwob
Module DocumentTemplate.DT_Util, line 210, in eval
__traceback_info__: refcount
Module <string>, line 1, in <module>
Module App.ApplicationManager, line 167, in refcount
Module pip._vendor.six, line 90, in __get__
Module pip._vendor.six, line 113, in _resolve
Module pip._vendor.six, line 80, in _import_module
ImportError: No module named _winreg

Display traceback as text

 Return to log 
REQUEST

form

cookies

tree-s	'eJzTyCkw5NLIKTDiClZ3hANXW3WuAmOuRKCECUjWFEXWFyRrxpUIkjZHlnEqB8lYQGQsUWSKQTKGBkCpxEQ9AK/oHVg'
_ga	'GA1.1.1966280796.1438491867'
lazy items

SESSION	<bound method SessionDataManager.getSessionData of <SessionDataManager at /session_data_manager>>
other

AUTHENTICATION_PATH	''
TraversalRequestNameStack	[]
AUTHENTICATED_USER	<PropertiedUser 'admin'>
URL	'http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main'
a_	0
BASEPATH1	''
URL2	'http://128.199.230.56:8090/Control_Panel'
SERVER_URL	'http://128.199.230.56:8090'
traverse_subpath	[]
BASE1	'http://128.199.230.56:8090'
BASE2	'http://128.199.230.56:8090/Control_Panel'
BASE3	'http://128.199.230.56:8090/Control_Panel/DebugInfo'
BASE4	'http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main'
URL3	'http://128.199.230.56:8090'
PUBLISHED	<App.special_dtml.DTMLFile object at 0x7f5d68e17090>
URL1	'http://128.199.230.56:8090/Control_Panel/DebugInfo'
n_	1
method	'GET'
ACTUAL_URL	'http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main'
URL0	http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main
URL1	http://128.199.230.56:8090/Control_Panel/DebugInfo
URL2	http://128.199.230.56:8090/Control_Panel
URL3	http://128.199.230.56:8090
BASE0	http://128.199.230.56:8090
BASE1	http://128.199.230.56:8090
BASE2	http://128.199.230.56:8090/Control_Panel
BASE3	http://128.199.230.56:8090/Control_Panel/DebugInfo
BASE4	http://128.199.230.56:8090/Control_Panel/DebugInfo/manage_main
environ

HTTP_REFERER	'http://128.199.230.56:8090/Control_Panel/manage_main'
SERVER_SOFTWARE	'Zope/(2.13.22, python 2.7.6, linux2) ZServer/1.1'
SCRIPT_NAME	''
REQUEST_METHOD	'GET'
PATH_INFO	'/Control_Panel/DebugInfo/manage_main'
SERVER_PROTOCOL	'HTTP/1.1'
QUERY_STRING	''
channel.creation_time	1443153286
CONNECTION_TYPE	'keep-alive'
HTTP_USER_AGENT	'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36'
HTTP_COOKIE	'_ga=GA1.1.1966280796.1438491867; tree-s="eJzTyCkw5NLIKTDiClZ3hANXW3WuAmOuRKCECUjWFEXWFyRrxpUIkjZHlnEqB8lYQGQsUWSKQTKGBkCpxEQ9AK/oHVg"'
SERVER_NAME	'kousalam.com'
REMOTE_ADDR	'111.91.84.15'
PATH_TRANSLATED	'/Control_Panel/DebugInfo/manage_main'
SERVER_PORT	'8090'
plone.protect.safe_oids	[]
HTTP_HOST	'128.199.230.56:8090'
HTTP_UPGRADE_INSECURE_REQUESTS	'1'
HTTP_ACCEPT	'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
GATEWAY_INTERFACE	'CGI/1.1'
HTTP_ACCEPT_LANGUAGE	'en-US,en;q=0.8'
HTTP_ACCEPT_ENCODING	'gzip, deflate, sdch'

**Comment by sudhan77** [comment]
I am going for a fresh install instead of trying to upgrade, pls check if there is any issue in this install:

root@mail:/opt/plone/zinstance# sudo -u plone_buildout bin/buildout
Uninstalling instance.
Installing instance.
/opt/plone/zinstance/local/lib/python2.7/site-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Generated script '/opt/plone/zinstance/bin/instance'.
Generated interpreter '/opt/plone/zinstance/parts/instance/bin/interpreter'.
Generated script '/opt/plone/zinstance/bin/pilprint.py'.
Generated script '/opt/plone/zinstance/bin/pilconvert.py'.
Generated script '/opt/plone/zinstance/bin/pilfont.py'.
Generated script '/opt/plone/zinstance/bin/pilprint.pyc'.
Generated script '/opt/plone/zinstance/bin/pilfile.pyc'.
Generated script '/opt/plone/zinstance/bin/pilconvert.pyc'.
Generated script '/opt/plone/zinstance/bin/pilfile.py'.
Generated script '/opt/plone/zinstance/bin/pilfont.pyc'.
Generated script '/opt/plone/zinstance/bin/pildriver.pyc'.
Generated script '/opt/plone/zinstance/bin/pildriver.py'.
Updating repozo.
Updating backup.
Updating zopepy.
Updating unifiedinstaller.
Updating precompiler.
Compiling Python files.
Compiling locale files.
Error while compiling /opt/plone/buildout-cache/eggs/python_gettext-1.2-py2.7.egg/pythongettext/tests/test_escape.po
Error while compiling /opt/plone/buildout-cache/eggs/python_gettext-1.2-py2.7.egg/pythongettext/tests/test5.po
Updating setpermissions.
setpermissions: Running # Dummy references to force this to execute after referenced parts
echo /opt/plone/zinstance/var/backups yes > /dev/null
chmod 600 .installed.cfg
# Make sure anything we've created in var is r/w by our group
find /opt/plone/zinstance/var -type d -exec chmod 770 {} \; 2> /dev/null
find /opt/plone/zinstance/var -type f -exec chmod 660 {} \; 2> /dev/null
find /opt/plone/zinstance/var -type d -exec chmod 770 {} \; 2> /dev/null
find /opt/plone/zinstance/var -type f -exec chmod 660 {} \; 2> /dev/null
chmod 754 /opt/plone/zinstance/bin/*
chmod: changing permissions of ‘/opt/plone/zinstance/bin/buildout’: Operation not permitted
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
plone.recipe.command = 1.1
plone.recipe.precompiler = 0.6
