### ISSUE TITLE
Incorrect Lock message from plone.app.iterate - for some users

### ISSUE THREAD

**Issue by djowett** [plone/Products.CMFPlone#1075]
See the images below.  These are for the same piece of checked out content, but viewed by 2 different users.  Firstly note that the checked out user is different for each piece of content - the correct user should be "Daniel" (myself) .  Secondly note that the date does not match the last modified date.

Plone 4.3.2
plone.app.iterate 2.1.10
plone.app.contenttypes 1.0

![locked_message_for_daniel](https://cloud.githubusercontent.com/assets/1470021/10074404/a1c0143c-62c7-11e5-999d-88934978e545.png)

<img width="555" alt="locked_message_for_nick" src="https://cloud.githubusercontent.com/assets/1470021/10074276/da020068-62c6-11e5-87de-f3b947245150.png">

**Comment by djowett** [comment]
From portal_catalog:
 	Creator 	admin
  	listCreators 	('admin', 'wojtek', 'daniel')

**Comment by vangheem** [comment]
I just fixed something similar in Plone 5. From looking at the code, it should be working in Plone 4 though.

See https://github.com/plone/plone.app.iterate/commit/c95d465c372f56c62838a204e7804e6ce9981bd0

**Comment by djowett** [comment]
@vangheem Ok, the code's a bit beyond me, but that does raise the question - which version should I be using with plone.app.contenttypes on Plone 4.3?

**Comment by djowett** [comment]
This seems wrong though... (in both branches discussed)

    def created(self):
        time = self.properties.get(keys.checkout_time, DateTime())

We are just hiding a missing value by replacing it with today's date - a missing value should through up a different message...

**Comment by vangheem** [comment]
So this is where it gets a bit confusing...

You could be using ``plone.app.stagingbehavior``. Plone 5 merged ``plone.app.stagingbehavior`` into plone.app.iterate so it doesn't require a behavior to be activate.

You could try removing ``plone.app.stagingbehavior`` and upgrading plone.app.iterate but make sure to test well beforehand.

**Comment by djowett** [comment]
I am using plone.app.stagingbehavior-0.1b4, but you merged p.a.sb in around 3.0.2 so 2.1.10 *should* be Ok.  I may experiment later...

**Comment by ale-rt** [comment]
There have been no updates in the latest years.
Please feel free to reopen if this is still an issue in Plone 5.2 or Plone 6.0.
