### ISSUE TITLE
Drop `type` attribute from all `script`, `link` and `style` tags

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1078]
The `type` attribute has implicit defaults in HTML5 and and it's a best practice to omit it. Plus we get prettier and lighter output.

**Comment by vangheem** [comment]
Is there any risk here? Old style themes, non-html5 themes? Do we still want to support that?

**Comment by davilima6** [comment]
In my experience, themes usually don't downgrade the doctype. In case they do, they won't get valid markup (although not only because of `type`) but even non-HTML5 browsers [usually default to the correct type](http://stackoverflow.com/questions/3485606/will-removing-the-type-from-a-script-tag-break-in-any-browsers) when it's absent. Despite this, you're right, it might be a risk and I'd like to hear from others on the matter.

Another risk is with tests and other scripts that check for the type attribute. Likely easy fixes but we'll know better running the test suite after the removal.

And since there are so many ocurrences, maybe this should be done at once in a sprint with a large "sed" + multi-repo pushes. Other path is to focus on critical tags first, those generated by resource registries.

**Comment by hvelarde** [comment]
is not that the UA defaults to the right type, but that it is used to give the UA a hint on what MIME type the content is without having to download it and to avoid downloading non-supported types.

so, as `text/javascript` must be supported by all UA, that becomes unnecessary.

**Comment by newbazz** [comment]
I would like to work on this issue.

**Comment by hvelarde** [comment]
@newbazz then go for it: you have to know how to work with Git and branches.

**Comment by newbazz** [comment]
@hvelarde i already made a PR but dont know coz my agreement for is not yet accepted it fails tests.
