### ISSUE TITLE
Social viewlet generates invalid HTML

### ISSUE THREAD

**Issue by jladage** [plone/Products.CMFPlone#1087]
plone.app.layout's social viewlet defines ``<meta itemprop="image" ...>`` in the head tag, but it lacks a ``<span itemscope itemtype="Article"> .. </span>``

There are two ways to solve this:
1. Add itemscope itemtype="Article" as attribute to the  ``<html>`` tag
2. Add a  ``<span itemscope itemtype="Article"> .. </span>`` around the metatags with itemprop attributes 

Those are equal so please choose the one that is easiest to implement ;)

**Comment by jladage** [comment]
oke so html get filtered here :)

The meta tags with itemprop attributes miss a surrounding span with itemscope attribute.

**Comment by gforcada** [comment]
@jladage you need to wrap html-like tags with backticks

**Comment by mauritsvanrees** [comment]
When I add a span in the head, the w3c validator starts giving this error: "Stray end tag head."

So the first way is probably best. Except that `itemtype="Article"` should be a url, and WebPage is probably better: `itemtype="http://schema.org/WebPage"`.

This means that it should be changed in the main template, not in plone.app.layout.

**Comment by hvelarde** [comment]
-1 and that was one of the reasons I was against of adding this feature to Plone 5 on the first pace as discussed in https://dev.plone.org/ticket/20256

first, I don't know why we are adding schema.org markup in the header, that's not documented anywhere; second, we must be careful with this markup as it has to be very easy to override it for add-ons.

take, for instance, collective.nitf (a content type that describes a news article); we spend a lot of time [adding semantic markup to it](https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/browser/templates/view.pt) and now I think we are going to invalidate it with this change.

so IMO the solution here is to remove those tags; neither Facebook's Open Graph, nor Twitter Cards, require that.

**Comment by hvelarde** [comment]
@jensens did you read above before merging this?

**Comment by jensens** [comment]
well, no. mea culpa. reverted. this one needs discussion. plone/Products.CMFPlone#1355
since i'am not an expert on this. what about

**Comment by hvelarde** [comment]
thank you!

**Comment by mauritsvanrees** [comment]
From what I see, the Facebook `og:` tags must be in the head. I guess the Twitter tags too. See examples on https://developers.facebook.com/docs/opengraph/getting-started

The `itemScope` and `itemType` belonging to `schema.org` with their tags can be anywhere on the page.

So it would seem the solution is:
- Keep the Facebook and Twitter tags in the current viewlet in the head.
- Move all schema stuff from the head to a second viewlet above the content.

Does that sound good?

@hvelarde Is that maybe what you meant with your first comment? At the time, it sounded to me like you wanted to rip all schema stuff out, including what the viewlet in current Plone 5.0 does.

**Comment by hvelarde** [comment]
@mauritsvanrees as I mentioned, including something like Twitter Cards in Plone's core was a mistake as we don't even know if Twitter is going to collapse next month or when the current Tech bubble finally burst.

we have 2 different things here: social media markup and semantic markup; so, let's focus on the social media markup first, trying to support only open standards; semantic markup must be addressed on a different issue and then we can discuss where to implement it.

besides that, Plone must evolve to support [Linked Open Data](http://linkeddata.org/faq).

**Comment by jensens** [comment]
+1 for any PLIP (inc.implementation) that brings Linked Open Data to Plone :D

**Comment by hvelarde** [comment]
I would love to do that, unfortunately is out of my scope and I have no time/resources to do so.

I'm just proposing something that, IMO, is the way to go.
