### ISSUE TITLE
Review patches, if any can be dropped

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#109]
There are plenty of patches in https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/patches

We should review them, if any can be dropped by our dependency on Python 2.7 or by progress of Zope, etc.

**Comment by thet** [comment]
More removals:
https://github.com/plone/Products.CMFPlone/pull/688

**Comment by vangheem** [comment]
test results are scary :(

**Comment by vangheem** [comment]
I'm closing this. I couldn't successfully remove the patches without causing test failure. Both @jensens and I took a crack at it without success. Not worth the time right now.

**Comment by jensens** [comment]
indeed, this is a task on its own, it needs at least 2-3 experienced Plonistas in one room, some beer and some time. so ok to close it for now. i keep it in mind anyway.
