### ISSUE TITLE
rc3 upgrade step with iterate installed

### ISSUE THREAD

**Issue by pilz** [plone/Products.CMFPlone#1090]
If plone.app.iterate was installed once and thus the portal property checkout_workflow_policy is present, the following migration step fails because there is no IIterateSchema anymore in plone.app.interate.interfaces.

plone.app.upgrade-1.3.17-py2.7.egg/plone/app/upgrade/v50/betas.py:543
```
    if site_properties.hasProperty('checkout_workflow_policy'):
        value = site_properties.getProperty('checkout_workflow_policy')
        from plone.app.iterate.interfaces import IIterateSchema
        settings = registry.forInterface(IIterateSchema)
        settings.checkout_workflow_policy = safe_unicode(value)
        site_properties._delProperty('checkout_workflow_policy')
```

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone.app.upgrade/commit/c43cca6de61c4b14d6cf8923ff3aeeb5905b863a
