### ISSUE TITLE
album_view: still weird text position and word wrapping

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1091]
Tested with 5.0RC3

![screenshot 2015-09-26 11 42 37](https://cloud.githubusercontent.com/assets/594239/10116888/c0337602-6443-11e5-8ca5-cb8be9ca1b3b.png)

**Comment by polyester** [comment]
waiting on https://github.com/plone/plone.app.contenttypes/pull/274

**Comment by polyester** [comment]
closed via https://github.com/plone/plonetheme.barceloneta/commit/f40fb61a29f9397037014910015c995805e9c702
