### ISSUE TITLE
Sitemap: text wrapping, too many icons, orphans..

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1092]
Images and files are being displayed with their portal type icon and a mime-type related icon...way too many icons.
In addition text wrapped into the next line should be indented somehow and aligned with the text position of the first line.

In addition: 2nd column of images: there is an orphan line

![screenshot 2015-09-26 11 45 32](https://cloud.githubusercontent.com/assets/594239/10116900/2867f518-6444-11e5-9e45-2b76cadddda4.png)

**Comment by ale-rt** [comment]
I think this is solved now.
Please feel free to reopen if it is still an issue in 5.2 or 6.0
