### ISSUE TITLE
Too many icons show in navigation portlet

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1093]
![screenshot 2015-09-26 11 50 08](https://cloud.githubusercontent.com/assets/594239/10116923/c6babc46-6444-11e5-92f5-171b41b9e5b8.png)
![screenshot 2015-09-26 11 49 59](https://cloud.githubusercontent.com/assets/594239/10116924/c6bdc7e2-6444-11e5-9bee-d088eb861c59.png)

**Comment by fgrcon** [comment]
fixed  since 5.02
