### ISSUE TITLE
Horizontal Toolbar buttons have scrollbars

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1096]
Apologies if this is a duplicate - I'm in a hurry and can't find this issue in github.

  - Install RC3
  - Create a new site
  - Go to site setup - Site Settings (http://localhost:8080/Plone/@@site-controlpanel)
  - Change **Position where the toolbar is displayed** to **Top**
  - Go back to homepage

Result:  Some of the toolbar buttons have horizontal scrollbars under them (see screenshot).  They go away if I make my browser window narrower.  I'm on a 13" Retina display, default resolution (maybe 2560 x 1600, not sure).
<img width="1262" alt="screen shot 2015-09-26 at 8 43 00 pm" src="https://cloud.githubusercontent.com/assets/460742/10121071/278ff982-6490-11e5-8cad-fa95b8cd0b60.png">

**Comment by pbauer** [comment]
I cannot reproduce this on a 13''-screen without retina (ff, chrome and safari). Can someone else with a retina-display try to reproduce it?

**Comment by hvelarde** [comment]
I think this was fixed at some point.
