### ISSUE TITLE
Toolbar opens on the right side on small size display?

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1103]
The toolbar is opened by default on the right side on mobile devices (see screenshot).
Is this intentional? This appears  a bit strange from the usability point of view.
![img_0071](https://cloud.githubusercontent.com/assets/594239/10123907/6ed7f0d6-6546-11e5-9ff0-d2d404e58c38.jpg)

**Comment by davilima6** [comment]
https://github.com/plone/Products.CMFPlone/issues/482#issuecomment-121871671

**Comment by zopyx** [comment]
Well, how about left-handed people? They have no chance to chance the position to left?

But anyway...the toolbar and the edit functionalities on small display sizes are nearly impossible to use for a variety of reasons.

**Comment by davilima6** [comment]
See #803

**Comment by jensens** [comment]
dup see #803
