### ISSUE TITLE
Upgrade step for portal properties and old GS profiles.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#111]
We will need an upgrade step that takes the old portal property-based GS files and converts those settings into the new p.a.registry-based settings. This task should be started after changing the prefix of the p.a.registry entries from plone.app.controlpanel.* to plone.*.

**Comment by gforcada** [comment]
@giacomos sorry for asking more than one year later, but do you happen to remember where you did that upgrade step? I only see [one commit on p.a.upgrade from you](https://github.com/plone/plone.app.upgrade/commits?author=giacomos) and is not related to that.

**Comment by giacomos** [comment]
@gforcada I remember that we working in a team in Arnhem, so maybe I wasn't the one who actually made the commits. I remember that we worked in here: https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v50/alphas.py#L82

**Comment by gforcada** [comment]
Closing then
