### ISSUE TITLE
can't add content after adding Plone 5 site without Example content

### ISSUE THREAD

**Issue by domruf** [plone/Products.CMFPlone#1113]
I created a Plone 5 site and unchecked the box "Example content".
This caused "Content-types (plone.app.contenttypes)" to not be installed.
Only after going to portal_quickinstaller and installing it manually I was able to add content pages, folders, etc. to the site.

**Comment by sor2000** [comment]
This worked for me as well.

I couldn't find the steps on how to do this and being new to Plone doesn't help either. So here are the steps/screenshots for future lost puppies like my self.

So if you are missing "Add new..." button and cannot add content and if you are missing "Dexterity Content Types" button/panel then try this:

1. go to Admin menu and select Site Setup
2. scroll down and select Management Interface
3. scroll down and click to open portal_quickinstaller
4. check mark content-type (plone.app.contenttypes) and click install
5. Done! everything should be working now (also see screenshots for additional visual help)

![001 SOR - issue - if you are missing Add new button and cannot add content](https://user-images.githubusercontent.com/54671462/63965931-45533000-ca68-11e9-9324-2259fc0c504e.png)
![002 SOR - issue - if you are missing Dexterity Conten Types](https://user-images.githubusercontent.com/54671462/63965941-48e6b700-ca68-11e9-9545-4e4a3b88aeb4.png)
![003 SOR - solution - go to Admin menu and select Site Setup](https://user-images.githubusercontent.com/54671462/63965951-4b491100-ca68-11e9-8b95-a0a0fb6f3565.png)
![004 SOR - solution - scroll down and select Management Interface](https://user-images.githubusercontent.com/54671462/63965958-4dab6b00-ca68-11e9-8402-d01a3e873b52.png)
![005 SOR - solution - scroll down and open portal_quickinstaller](https://user-images.githubusercontent.com/54671462/63965971-5439e280-ca68-11e9-83b7-a36f7b37ac6a.png)
![006 SOR - solution - check mark content-type (plone app contenttypes) and click install ](https://user-images.githubusercontent.com/54671462/63966000-5e5be100-ca68-11e9-9943-0b44793ca64e.png)

**Comment by ale-rt** [comment]
It looks fixed to me
