### ISSUE TITLE
Folder contents: Usabilty of delete all in folder vs. current

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1123]
So I deleted the folder instead of all items in that folder. Huh, a bug? Why that. 

Going back to reconstruct it I found the check-box to select all items (left of "Title") in a folder and the the check-box folder itself (left of path-bar) very (too) near by each other. While working fast through a bunch of folders it's visually not that different. 

So not a bug, but a problem.

![screenshot from 2015-10-02 11 00 02](https://cloud.githubusercontent.com/assets/157140/10242948/10b3955c-68f5-11e5-8e45-b9108fabb24f.png)

I hope the @plone/ux-team may propose a better solution to reduce the possible error-rate of editors.

**Comment by davilima6** [comment]
I think it helps if the element has a different shade:

    .fc-breadcrumbs-container { background: #000; }
    .pat-structure .fc-breadcrumbs a { color: #fff; }

![captura de tela 2015-10-02 as 08 08 53](https://cloud.githubusercontent.com/assets/422130/10245338/ea817f24-68dc-11e5-844e-7c5724590dc0.png)

**Comment by jensens** [comment]
solved already differently
