### ISSUE TITLE
Delete action shows even when locked.

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1124]
(1) Deleting a single locked item when locked (view mode) results in a traceback.
- Editor A edits item Foo
- Editor B navigates to Foo
- Editor B chooses toolbar -> actions -> delete: results in traceback::
  
  ```
  Traceback (innermost last):
    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module z3c.form.form, line 218, in __call__
    Module z3c.form.form, line 213, in update
    Module plone.app.z3cform.csrf, line 21, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module plone.app.content.browser.actions, line 78, in handle_delete
    Module plone.dexterity.content, line 707, in manage_delObjects
    Module OFS.ObjectManager, line 536, in manage_delObjects
  ResourceLockedError: Object "custom-object-source-binder-for-z3c.forms" is locked via WebDAV
  ```

This also happens when lock when Editor A and B are the same login, i.e. navigates in separate Browser-Tab to the locked item or when a lock was not released for some other reason.

(2) Deleting while editing results in traceback
- Editor A edits item Foo
- Editor A chooses to not edit further but delete the item immediatly using the toolbar -> Actions -> delete results in same traceback as above.

Proposed solution:
- ad (1): dont show the delete action if item is locked
- ad (2): unlock before deletion if lock is owned by same person as deleter.

**Comment by mrsaicharan1** [comment]
I'd like to look into this issue. Could you point me to the file where the delete button for locked items is present?

**Comment by gp54321** [comment]
I think that a patch to plone/app/contentmenu/menu.y should give a better UI

```
--- menu.py.ori	2018-03-02 23:18:15.000000000 +0000
+++ menu.py	2018-03-22 17:50:49.219503281 +0000
@@ -74,8 +74,15 @@
             folder = utils.parent(self.context)
         return folder.absolute_url() + '/folder_contents'
 
-    @memoize
     def available(self):
+        locking_info = queryMultiAdapter((self.context, self.request),
+                                         name='plone_lock_info')
+        if locking_info and locking_info.lock_info():
+            return False
+        return self.availableEntries()
+
+    @memoize
+    def availableEntries(self):
         actions_tool = getToolByName(self.context, 'portal_actions')
         editActions = actions_tool.listActionInfos(
             object=self.context, categories=('object_buttons',), max=1)
```
rationale: it solves (a bit) the issue 'the user can't see the item is locked': if there is no action menu with delete/cut it gives an hint. If the locking user is another user, there is a warning in the UI. Now when trying to delete from content view, the lock error is caught and a nice error message is displayed.
Now if the user self locks an item and don't know how to get out of it, just waiting a bit will clear the lock. And if the user is savvy enough to try to delete with content view, he(she) will be enlightened.

**Comment by ale-rt** [comment]
In both Plone 5.2 and Plone 6.0 clicking the delete action offers to unlock the object before deleting it.
Given not much activity happened here and that the current state is IMO good enough I will close this issue.
Feel free to reopen if you disagree.
