### ISSUE TITLE
Wrong justification on "Actions in current folder" menu

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1126]
Plone 5.0 final with horizontal toolbar; inside any folder select the "Actions in current folder" button; the menu overflows the screen on left side like this:

![selection_007](https://cloud.githubusercontent.com/assets/341393/10246959/e1bf3912-68eb-11e5-8d91-1c1576b89ca0.png)

**Comment by hvelarde** [comment]
Plone 5.0.4 and this is still happening.

**Comment by davisagli** [comment]
It looks like neither this menu nor the horizontal toolbar remain in Plone 6
