### ISSUE TITLE
Toolbar switches position on screen resize

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1127]
Plone 5.0 final with horizontal toolbar:

![selection_007](https://cloud.githubusercontent.com/assets/341393/10247094/df1ce442-68ec-11e5-877e-e422e14f4100.png)

Activate responsive mode:

![selection_008](https://cloud.githubusercontent.com/assets/341393/10247093/df0175c2-68ec-11e5-8840-52759a582173.png)

Go back to normal mode; now you have a vertical toolbar:

![selection_009](https://cloud.githubusercontent.com/assets/341393/10247092/def4e35c-68ec-11e5-959e-ff2fa9511a24.png)

Reloading the page fixes the problem.

**Comment by hvelarde** [comment]
Plone 5.0.4 and this is still happening.

**Comment by alecpm** [comment]
This is fixed on 5.1 and 5.0.x
