### ISSUE TITLE
IImageScaleTraversable is provided by all types of dexterity items (I think this makes the interface useless)

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1129]
## in  plone.app.dexterity/plone/app/dexterity/configure.zcml: 
    ...class class="plone.dexterity.content.DexterityContent">
    
    implements interface="plone.namedfile.interfaces.IImageScaleTraversable" 
    /class 
Removing that  and changing plone.app.contenttypes.content.py: 
    
    ...
    +from plone.namedfile.interfaces import IImageScaleTraversable
    ...
    @implementer(IImage)
    +@implementer(IImageScaleTraversable)
    class Image(Item):
    """Convenience subclass for ``Image`` portal type
    """

... Rebuild Catalog:
Only images  and other types which explicitly implement it provide the interface

**Comment by thet** [comment]
sounds reasonable, but don't know about the reasoning behind having IImageScaleTraversable available on all content. @pbauer ?
we have to make sure, that objects with the ILeadImage behavior also provides the IImageScaleTraversable.

**Comment by fgrcon** [comment]
Agreed to that but folder/@@images/image/something does not make sense and leads to not found ...
see also https://github.com/plone/Products.CMFPlone/issues/1074

**Comment by fgrcon** [comment]
I just branched back:  this really would break Lead Image behaviour

 File "/usr/local/p5dev/buildout.coredev/eggs/Zope2-2.13.23-py2.7.egg/OFS/Traversable.py", line 300, in unrestrictedTraverse
    raise e
AttributeError: @@images

 - Expression: "context/@@images"
 - Filename:   ... ntenttypes/plone/app/contenttypes/behaviors/leadimage.pt
 - Location:   (line 3: col 28)
 - Source:     tal:define="scale_func context/@@images;
                                      ^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0) .....

**Comment by fgrcon** [comment]
found a better solution for my issue ...
