### ISSUE TITLE
plone-compile-resources breaks if you use more than one resource in your bundle

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#1131]
When i create a bundle which contains two resources, each is one less-file, then the  plone-compile-resources script will break with the following error.

```
$ ./bin/plone-compile-resources --bundle=tango-bundle
Running command: /home/maik/develop/plone/plonetheme.mytango/bin/instance run /home/maik/develop/plone/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/_scripts/_generate_gruntfile.py
Using site id: Plone
Setup npm env
Running command: npm install
Running command: /usr/local/bin/grunt --gruntfile=/home/maik/develop/plone/plonetheme.mytango/Gruntfile.js compile-tango-bundle

/home/maik/develop/plone/plonetheme.mytango/Gruntfile.js:649
"/home/maik/develop/plone/plonetheme.mytango/src/plonetheme/mytango/theme/css/
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Duplicate data property in object literal not allowed in strict mode
Warning: Task "compile-tango-bundle" not found. Use --force to continue.
```

and in the generated Gruntfile.js this is what breaks Grunt then:

```
                files: {
                    "/home/maik/develop/plone/plonetheme.mytango/src/plonetheme/mytango/theme/css/tango-compiled.css": "/home/maik/develop/plone/plonetheme.mytango/src/plonetheme/mytango/theme/css/main.less",
"/home/maik/develop/plone/plonetheme.mytango/src/plonetheme/mytango/theme/css/tango-compiled.css": "/home/maik/develop/plone/plonetheme.mytango/src/plonetheme/mytango/theme/css/custom.less"
                }
```

My registration of the bundle and resources looks like this:

```
<?xml version="1.0"?>
<registry>

    <records prefix="plone.resources/tango-custom"
              interface='Products.CMFPlone.interfaces.IResourceRegistry'>
       <value key="css">
          <element>++theme++plonetheme.mytango/css/custom.less</element>
       </value>
    </records>

    <records prefix="plone.resources/tango-main"
              interface='Products.CMFPlone.interfaces.IResourceRegistry'>
       <value key="css">
          <element>++theme++plonetheme.mytango/css/main.less</element>
       </value>
    </records>

    <!-- bundle definition -->
    <records prefix="plone.bundles/tango-bundle"
              interface='Products.CMFPlone.interfaces.IBundleRegistry'>
      <value key="resources">
        <element>tango-main</element>
        <element>tango-custom</element>
      </value>
      <value key="enabled">True</value>
      <value key="compile">True</value>
      <value key="csscompilation">++theme++plonetheme.mytango/css/tango-compiled.css</value>
      <value key="last_compilation"></value>
    </records>

</registry>
```

**Comment by MrTango** [comment]
@vangheem i thought you said that would work now. Would be nice if you can have a look at it again.
Before i was using my bundle just for one file and was including the other file with less, but if i want to use grunt watch for these files, they should belong to a bundle, i guess.

**Comment by vangheem** [comment]
I don't remember what I ever said about this. Looks like a compile script bug.

@bloodbare any ideas?

**Comment by bloodbare** [comment]
I remember that compiled bundles where designed to be used as 1 resource x bundle ( this resource as its a compiled one is a list of dependencies in requirejs and less that is going to be compiled in that bundle. The problem of having two resources as main bundle is that then dependencies where harder to fullfill without duplication and without concatenation.

**Comment by timitos** [comment]
@thet and me stumbled over this problem at the javascript training at the ploneconf 2015.

The problem is here:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/_scripts/_generate_gruntfile.py#L355

Changing less_files into a dict with the destination file as key and a list of source files as values would solve the problem. But if the bundle should contain always one resource in case of that 2 or more resources are defined an error should be raised.

If someone could decide what direction to go i would be able to provide a patch.

**Comment by davilima6** [comment]
I think can be closed, right?
