### ISSUE TITLE
Missing @@dashboard link in Personal Tools

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1132]
It seems to have been forgotten during the migration to the toolbar.

**Comment by dtordable** [comment]
There's no link to the dashboard but /@@dashboard works as usual...

**Comment by davilima6** [comment]
Strangely enough there's no reference to that action in Plone 4.3: https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/profiles/default/actions.xml#L302

I mean, would be that the only Personal Tools link inserted dynamically (via JS)?

**Comment by davilima6** [comment]
Related to https://community.plone.org/t/does-plone-5-still-have-dashboard/1235
