### ISSUE TITLE
"Build" in Resource Registries still not working properly

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1136]
Clicking on "Build" for a bundle still does not terminate (happens with latest Chrome and latest FF on Linux)

**Comment by vangheem** [comment]
Is there an error in the browser console? What bundle are you trying to build? Are there customizations?

I can't reproduce in released Plone 5.0 or in coredev buildout in Chrome or Firefox.

**Comment by zopyx** [comment]
I could reproduce the problem with a checkout of 

- git@github.com:xml-director/xmldirector.plonecore.git
- branch 'plone5'
- "make build5"

After creating a new Plone site with "XML Director Plone 5" profile I went to resources registries and added "xmldirector.plonecore" resource to the 'plone' bundle and clicked on the "build" button -> building takes forever, no JS console messages, no backend messages.

Possible some issues with my JS code but this should not lead to such a situation.

**Comment by jensens** [comment]
iirc this was fixed, at least while JS-Training at Plone conference in Bucharest it worked after using latest buildout.coredev 5 - @thet may you confirm and close this issue if so?

**Comment by jensens** [comment]
works here for me. also meanwhile the command-line variant works.
