### ISSUE TITLE
Site creation w/o example content results in no content-types at all

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1143]
While creating a new Plone 5 site, in advanced mode, i can deselect to install example content. 

In this case no content types are installed at all (not just skipping example content creation). 

Looking at ``portal_types`` its very empty (3 entries).

**Comment by davilima6** [comment]
Duplicate of #1113

**Comment by jensens** [comment]
thanks, was not aware of it

**Comment by davilima6** [comment]
np, you're welcome
