### ISSUE TITLE
Plone Hotfix 20151006 (Oct 06, 2015) using Plone4.2.1:  disables TinyMCE reference browser for images 

### ISSUE THREAD

**Issue by jmevissen** [plone/Products.CMFPlone#1145]
on Plone4.2.1 Hotfix 20151006 disables TinyMCE reference browser for adding images.
The reference modal opens, but the selection list stays empty.

uncommenting the "if(window.tinymce) { ... }" part in protect.js overrides the issue.

**Comment by pbauer** [comment]
Duplicate of https://github.com/plone/plone4.csrffixes/issues/2
