### ISSUE TITLE
After deleting a default page a 404 is rendered

### ISSUE THREAD

**Issue by jladage** [plone/Products.CMFPlone#1148]
Using the delete_confirmation overlay to delete a default page, you stay on the absolute url you just deleted. After deleting a default page delete_confirmation should redirect to the parent.

**Comment by vangheem** [comment]
I have reproduced this. It was a bug in the upgrade steps.

To fix you site in the meantime, go to /manage -> portal_actions -> object_buttons -> delete and update the modal value to be::

```
{"actionOptions": {"disableAjaxFormSubmit":true, "redirectOnResponse":true}}
```
