### ISSUE TITLE
UnifiedInstaller install failure

### ISSUE THREAD

**Issue by stefanseefeld** [plone/Products.CMFPlone#1150]
I'm trying to run the 'unified installer'. Running './install.sh' from Plone-5.0-UnifiedInstaller asks about the desired location (I specify '/usr/local/Plone'), then aborts with:

ERROR: The executable /usr/local/Plone/zinstance/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/usr/local/Plone/zinstance')
ERROR: virtualenv is not compatible with this system or executable

**Comment by idgserpro** [comment]
Thanks for reporting. Would you mind using the UnifiedInstaller repository? You can open it in https://github.com/plone/Installers-UnifiedInstaller/issues/new

**Comment by stefanseefeld** [comment]
OK, done.
