### ISSUE TITLE
Cleanup deprecated  geticon ... code

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1151]
Plone 5 renders contenttype icons with css classes (using fontello). There is a lot of sourcecode to be cleaned up. Old style icons are rendered together with fontello icons.

![double-icons](https://cloud.githubusercontent.com/assets/1640384/10416897/c482934e-702a-11e5-9904-530838962c70.jpg)

see also https://github.com/plone/Products.CMFPlone/issues/1074 and discussions in https://github.com/plone/plone.app.content/pull/57

**Comment by fgrcon** [comment]
results so far (some new or updated  prs will follow soon):
![dexterity-types](https://cloud.githubusercontent.com/assets/1640384/10481775/4ef53564-7273-11e5-9daa-d72001523478.jpg) 
![portlets kopie](https://cloud.githubusercontent.com/assets/1640384/10481779/540a5ee4-7273-11e5-9f48-920951da3c9d.jpg)
![related-items-view](https://cloud.githubusercontent.com/assets/1640384/10481783/5be969ac-7273-11e5-8598-31d54e52add0.jpg)
![reviewlist](https://cloud.githubusercontent.com/assets/1640384/10481785/5f6d891e-7273-11e5-8be3-c473a935b336.jpg)
![search](https://cloud.githubusercontent.com/assets/1640384/10481789/697fef78-7273-11e5-9493-3152b26995ac.jpg)

![sitemap](https://cloud.githubusercontent.com/assets/1640384/10481798/80f895ec-7273-11e5-9e02-72a09eca3fd6.jpg)

**Comment by fgrcon** [comment]
@vangheem, @jensens, @pbauer, @thet  ....   and all who are interested:

### this should be finished (preliminary, I hope i ditn't forget a pr), 


the prs related and to merge (if you dare  :worried: ) are:

plone/plone.app.querystring fix resultview icons,…
#55 opened 32 minutes ago by fgrcon 
 
plone/plone.app.layout fix icon rendering ...
#67 opened 2 hours ago by fgrcon 
  
plone/plone.app.dexterity fix icons in dexterity types list
#187 opened 8 hours ago by fgrcon 
 
plone/Products.CMFPlone remove deprecated icons ... pr review pr wip
#1152 opened 3 days ago by fgrcon 
 
plone/plone.app.portlets remove deprecated contenttype icons pr review pr wip
#59 opened 3 days ago by fgrcon 
 
plone/plone.app.contenttypes remove code from deprecated getIcon, reuse metadata field getIcon  pr review pr testing
#278 opened 5 days ago by fgrcon 

plone/plone.app.content - Add option tho show thumbs for images in content listing and rename… pr review
#57 opened 8 days ago by fgrcon 
 
plone/mockup Add option tho show thumbs for images in content listing and rename-p…
  pr review #592 opened 8 days ago by fgrcon 

----
* there is still a lot of legacy code to be cleaned up. I did not really dare. ...
* the bullets in some portlets should be removed - together with icons they look very ugly.
* some more minor things ...

I hope you are not to much  annoyed  by all the nuissance i caused as a plone newbie,
Franz

**Comment by jensens** [comment]
nobody is annoyed! its the opposite, thank you very much for the contribution. We are at the moment at plone conference and may find time to review and merge at the sprint. please stay tuned.

**Comment by cleder** [comment]
Thanks, Great work, and Great documentation, I love the images pointing out
what was adressed :-)

On 15 October 2015 at 10:56, Jens W. Klein <notifications@github.com> wrote:

> nobody is annoyed! its the opposite, thank you very much for the
> contribution. We are at the moment at plone conference and may find time to
> review and merge at the sprint. please stay tuned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1151#issuecomment-148338601>
> .
>



-- 
Best Regards,

Christian Ledermann

Newark-on-Trent - UK
Mobile : +44 7474997517

https://uk.linkedin.com/in/christianledermann
https://github.com/cleder/


<*)))>{

If you save the living environment, the biodiversity that we have left,
you will also automatically save the physical environment, too. But If
you only save the physical environment, you will ultimately lose both.

1) Don’t drive species to extinction

2) Don’t destroy a habitat that species rely on.

3) Don’t change the climate in ways that will result in the above.

}<(((*>

**Comment by vangheem** [comment]
So I merged a few; however, I'm not sure how this affects plone.app.contenttypes which I think is still meant to work with Plone 5.

**Comment by fgrcon** [comment]
updated search results: show thumbs for images and lead-images
![searchresults-updated](https://cloud.githubusercontent.com/assets/1640384/10563773/15b99e98-7598-11e5-86ee-69248f5369f4.jpg)

**Comment by fgrcon** [comment]
I am going to start to cleanup and rework this and related issues.
