### ISSUE TITLE
Unclickable buttons in Resource Registries

### ISSUE THREAD

**Issue by laulaz** [plone/Products.CMFPlone#1153]
When using Plone 5 in French, "Development Mode(only logged in users)" translation is too long and prevents clicking on `Add bundle`, `Add resouce`, `Save` and `Cancel` buttons.

The `<div class="checkbox development-mode>` goes over it.

See screenshot :

![screenshot](https://cloud.githubusercontent.com/assets/1101273/10422918/386c1eb0-70c1-11e5-9da7-28069bc61755.png)

This is the `<div>` area : 

![screenshot2](https://cloud.githubusercontent.com/assets/1101273/10422919/3f7b502c-70c1-11e5-8c6e-bb8feca75973.png)

**Comment by davilima6** [comment]
Relates to #1141

**Comment by Gomez** [comment]
Closed with:
https://github.com/plone/mockup/pull/610
