### ISSUE TITLE
Plone Release page reference an obsolete link to issue tracker

### ISSUE THREAD

**Issue by encolpe** [plone/Products.CMFPlone#1157]
On https://plone.org/products/plone/releases/5.0, the 'Issue Tracker' links still use https://dev.plone.org/ instead of https://github.com/plone/Products.CMFPlone/issues

**Comment by khanstark** [comment]
@encolpe same is the case with Plone 5.0.3 https://plone.org/products/plone/releases/5.0.3

**Comment by jensens** [comment]
no longer an issue
