### ISSUE TITLE
Not possible to switch to debug mode in resource registries if JS contains error

### ISSUE THREAD

**Issue by rnixx** [plone/Products.CMFPlone#1160]
After installing an Addon which I want to migrate to Plone 5 I got JS errors (as expected). Unfortunately it's not possible any more to switch to debug mode in control panel because this implies working Javascript resources.

It should be possible to switch to debug mode regardless of JS resources can be loaded successful.

**Comment by vangheem** [comment]
in the meantime, all those settings on in the configuration registry so you can modify the debug mode settings manually there.

Also, there is the FEDEV environment variable that you can set to true to have everything run un-compiled.

**Comment by davisagli** [comment]
In Plone 6 it should be harder to completely break the site this way, since there is no longer TTW compilation of bundles. So I think this is no longer relevant, but feel free to reopen if it is.
