### ISSUE TITLE
Ease inclusion of resources to bundles

### ISSUE THREAD

**Issue by frisi** [plone/Products.CMFPlone#1163]
# current state

people that want to integrate resources (eg. js and less/css of a third party library) using requireJS need to register two resources.
(see this commit on [mockup-minimalpattern](https://github.com/collective/mockup-minimalpattern/commit/0a49f9242154405a7b88423ced067c8d14fcfb46) - an example we did at the javascript training):

1) The JS for the pattern itself...

``` javascript
define([
  'pat-base',
  'jquery'
], function (Base, $) {
  'use strict';

  var Minimalpattern = Base.extend({
    name: 'minimalpattern',
    trigger: '.pat-minimalpattern',  // has to be exact like this: 'pat-' + patternname.
    parser: 'mockup',
    defaults: {
      text: 'Super Duper!'
    },
    init: function () {
      var self = this;
      self.$el.html(self.options.text);
    }
  });
  return Minimalpattern;
});
```

...is registered in the `mockup-patterns-minimalpattern` resource:

``` xml
  <records prefix="plone.resources/mockup-patterns-minimalpattern"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
      <value key="js">++plone++minimalpattern/patterns/minimalpattern/pattern.js</value>
      <value key="css">
        <element>++plone++minimalpattern/patterns/minimalpattern/pattern.minimalpattern.less</element>
      </value>
  </records>
```

2) The require statement needed to properly compile the bundle currently needs to be registered as a resource too (`mockup-bundles-minimalpattern`).

``` javascript
require([
  'jquery',  // We use jquery to search the DOM for pattern declarations.
  'pat-registry',  // We have to register
  'mockup-patterns-minimalpattern'  // Depend on the patterns, you want to support in this bundle.

], function($, Registry) {
  'use strict';

  if (window.parent === window) {
    $(document).ready(function() {
      if (!Registry.initialized) {
        Registry.init();
      }
    });
  }

});
```

``` xml
  <records prefix="plone.resources/mockup-bundles-minimalpattern"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
    <value key="js">++plone++minimalpattern/js/bundles/minimalpattern.js</value>
    <value key="css">
      <element>++plone++minimalpattern/less/minimalpattern.less</element>
    </value>
  </records>
```
# wishful thinking

the `mockup-bundles-minimalpattern` resource should not be needed

the resourceregistry should add the requireJS config information (below example for the plone bundle) on its own:

``` javascript
require([
  'jquery',  
  'pat-registry',

  // now add dependencies based on resources listed for this bundle
  'mockup-patterns-select2',
  'mockup-patterns-pickadate',
  'plone-patterns-toolbar',
  'mockup-patterns-autotoc',
  ....
  'mockup-patterns-minimalpattern'
], function($, Registry) {
  'use strict';

  if (window.parent === window) {
    $(document).ready(function() {
      if (!Registry.initialized) {
        Registry.init();
      }
    });
  }

});
```

this would require to define the resources for the plone bundle explicitly instead of pulling in the pre-compiled `plone` resource (`++resource++plone.js`).

currently:

``` xml
  <records prefix="plone.bundles/plone"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="resources">
      <element>plone</element>
    </value>
```

new

``` xml
  <records prefix="plone.bundles/plone"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="resources">
    <element>mockup-patterns-select2</element>
    <element>mockup-patterns-pickadate</element>
    <element>plone-patterns-toolbar</element>
    <element>mockup-patterns-autotoc</element>
    <element>mockup-patterns-cookietrigger</element>
    <element>mockup-patterns-formunloadalert</element>
    <element>mockup-patterns-preventdoublesubmit</element>
    <element>mockup-patterns-formautofocus</element>
    <element>mockup-patterns-markspeciallinks</element>
        ...
    </value>
```

**Comment by frisi** [comment]
we discussed this with @thet and @frapell at the JS training in bucharest and agreed that this needs to happen.
@vangheem could you please tell us what you think of this and if it's technically feasible

**Comment by vangheem** [comment]
seems too magical. RequireJS already seems hard enough for people to learn, now you add magic on top of it, I'm not sure.

You are not required to have a `define` js resource. You can define patterns inline with your `require` js file. The using `define` is convention and nice to do so you can import that js module into other modules.

A pattern without using define and then, not needing 2 files would look something like:

```
require([
  'jquery',  
  'pat-registry',
  'pat-base'
], function($, Registry, Base) {
  'use strict';

  var Minimalpattern = Base.extend({
    name: 'minimalpattern',
    trigger: '.pat-minimalpattern',  // has to be exact like this: 'pat-' + patternname.
    parser: 'mockup',
    defaults: {
      text: 'Super Duper!'
    },
    init: function () {
      var self = this;
      self.$el.html(self.options.text);
    }
  });

  if (window.parent === window) {
    $(document).ready(function() {
      if (!Registry.initialized) {
        Registry.init();
      }
    });
  }

});
```

Notice there is no return statement here and in this scenario, other modules can not import your pattern.

**Comment by frisi** [comment]
@sneridagh @ebrehault this is about your discussion at the end of the theming talk

**Comment by frisi** [comment]
thanks @vangheem  for your explanation. so there is a way to ship a pattern/addon with just one resource (downside: it can't be imported anywhere else)

i had a conversation with @bloodbare on this topic today.

* addons need to ship with pre-compiled bundles i.o. to work out of the box.
  compiling bundles automatically after quickinstalling them is currently not possible

* console build-script excludes jquery automagically, other dependencies already included in other bundles might be manually omitted too (dunno if via a config-option or a parameter)
* compiling ttw adds jquery again (bugreport has to be written for that)

* adding require statement computed out of resources as proposed here means too much magic

  A) where to store the genereated require statements
  B) which plone.resoure to store compiled js and css into  
  C) setup code might need to do more on document.ready() than just run registry.init(); so it needs to be put into the pattern as nathan outlined above - reducing re-usability)


current best practice (will update resoureregistry documentation after your ok on this ticket)

if you want to combine certain resources into plone or plone-logged-in currently
you need to

* amend them in a customized `++resource++plone-logged-in.js` and `++resource++plone.js` respectively  (copy and register via overrides.zcml)

* register a resource for your my.site package
```xml
  <records prefix="plone.resources/mysite-plone[-logged-in]"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
    <value key="js">++plone++my.site/plone.js</value>
    <value key="css">
      <element>++plone++my.site/plone.less</element>
    </value>
  </records>
```
* recompile using console script
* put compiled js and css into ++plone++my.site/plone.js/css

@bloodbare and @vangheem can this go into the registry documentation?

**Comment by vangheem** [comment]
This seems ok.

**Comment by bloodbare** [comment]
For me its ok also

**Comment by thet** [comment]
I'm not sure, if it's too much magic to automatically generate the ``require`` call for bundles. When doing the training, I had a hard time to explain why we need resources, then a resource which defines a bundle and then a bundle, which just depends on the bundle-resource.
I understand the resource registry as a RequireJS configurator. It would feel natural if it would also generate the necessary ``require`` call, making the bundle-resource obsolete.

Putting a pattern in a bundle-resource within the ``require`` statement is not ideal, because each bundle creates another request and includes all the dependencies, which we want to avoid. 
Integrators would want to add addon-resources to the plone bundle and disable the custom addon-bundles.

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity and because here has been quite some changes in the JS story lately.
Please feel free to reopen if you think this should be addressed in the next Plone versions.
