### ISSUE TITLE
registry does not compile css files

### ISSUE THREAD

**Issue by frisi** [plone/Products.CMFPlone#1164]
*.css files contained in resources do not end up in compiled bundles.

We adapted the [mockup-minimalpattern](https://github.com/collective/mockup-minimalpattern) package and renamed its *.less files to *.css and changed their registration (see below). When compiling, the bundle in `@@resourceregistry-controlpanel` it reports 0 css files.

``` xml
  <records prefix="plone.resources/mockup-patterns-minimalpattern"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
      <value key="js">++plone++minimalpattern/patterns/minimalpattern/pattern.js</value>
      <value key="css">
        <element>++plone++minimalpattern/patterns/minimalpattern/pattern.minimalpattern.css</element>
      </value>
  </records>

  <records prefix="plone.resources/mockup-bundles-minimalpattern"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
    <value key="js">++plone++minimalpattern/js/bundles/minimalpattern.js</value>
    <value key="css">
      <element>++plone++minimalpattern/less/minimalpattern.css</element>
    </value>
  </records>
```

btw: @timitos mentioned that there is a similar issue with `bin/plone-compile-resources`

**Comment by frisi** [comment]
@sgeulette might have some additional informations on this

**Comment by agitator** [comment]
... bit me too

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity and because here has been quite some changes in the JS story lately.
Please feel free to reopen if you think this should be addressed in the next Plone versions.
