### ISSUE TITLE
 bin/plone-compile-resources doesn't work on OSX without full XCode

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1166]
Could any Mac user please confirm if that's really a matter of not having full XCode, only its CLI dev tools? (which should be enough imo)

Traceback (using npm 2.14.7): http://pastebin.com/kMypw9VZ

TL;DR:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

/cc @simonedeponti @vangheem @MrTango @bloodbare

**Comment by agitator** [comment]
you don't have to install the full xcode http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/
