### ISSUE TITLE
Usability: Inform the items to be deleted in confirmation dialog

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1173]
The confirmation dialog would be more valuable to the editor if it reports the titles of the items to be deleted:

![delete_confirm](https://cloud.githubusercontent.com/assets/339384/10518199/9672305c-7360-11e5-8548-afe57653702d.png)

**Comment by davilima6** [comment]
+1. I just would like to remember that the design tradeoff when there are many items should be observed. I think it might be easy to create another UX problem with that. One solution would be having a `More details` option like when Windows Explorer copies files or while Ubuntu Software Center is running apt.

**Comment by tomgross** [comment]
This is fixed with https://github.com/plone/plone.app.linkintegrity/pull/45
