### ISSUE TITLE
Exclude from navigation in folder-contents properties

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1177]
The "exclude from navigation" setting is not correctly shown in folder-contents properties in Plone 5.0.

![exclude_from_navigation](https://cloud.githubusercontent.com/assets/339384/10540291/febfa8a0-7406-11e5-8990-039818c1fa95.png)

**Comment by vangheem** [comment]
This is on purpose. The Properties tab does not show the existing values. It's meant to allow you to change values.

- it needs to work when you select many items
- it shouldn't force you to set the value. right now, if you don't select a value, the data is not saved. Each metadata option does not have pre-filled existing values. It's only to change the value if you select one.

**Comment by tomgross** [comment]
Fair enough. I'm not completely satisfied ;-) A short teaser describing the purpose of the menu would be helpful to the user.

**Comment by davilima6** [comment]
+1 w/ @tomgross. State menu does display transitions related to current item(s) selection, so I'd expect the same behavior for Properties, and also for Tags. When multiple items are selected then those popover menus should fallback to current blank fields behavior, which most users should understand without additional explanations since this is long-established file managers' behavior.

All of this can be grabbed from catalog metadata, right? Are there any other concerns related to performance (eg: DOM)?

**Comment by vangheem** [comment]
IMO, it makes no sense to pre-fill in these values. Are we to fill in dates too? Copyright text? This is meant for bulk content editing. If you fill in the value sometimes and not others, it's inconsistent behavior. It is consistent with the way workflow and tags menus work--in bulk--not geared for single item editing.

**Comment by davilima6** [comment]
Yes, that was my suggestion: make all metadata immediately available if one single item is selected. For other cases, bulk edition.

What would be the downsides in your opinion? State menu already considers selected item's state for showing transitions so imo it'd be all about making this ui more powerful - if it doesn't overload it performance-wise.

**Comment by vangheem** [comment]
It's inconsistent. State menu is not comparable. It doesn't show existing values, it only shows possible values and does not fill in anything. Again, tags only show possible values, it doesn't pre-fill anything. What you are asking for is inconsistent and I think will confuse users in other ways.

**Comment by davilima6** [comment]
Ok, then, np!
