### ISSUE TITLE
Not enough feedback for Build button in Theme editor

### ISSUE THREAD

**Issue by mtowara** [plone/Products.CMFPlone#1181]
I created a copy of the Barceloneta Theme as instructed here:
http://training.plone.org/5/theming/ttw-advanced.html

However if I hit the build button inside of barceloneta.plone.less it will get stuck on  "Working..." until I reload (F5) the page. According to htop the build process finishes, but no output is generated.

Am I missing any prequisites or are there any log files for the build? (nothing in instance and also no output from fg process)

I got an standalone installation of Plone 5.0 on Ubuntu Server 14.04 LTS.

**Comment by davilima6** [comment]
I'd guess you might have missed something passing from the docs into your product. I followed tutorial and succeeded. Would you mind sharing your repository?

**Comment by mtowara** [comment]
Which repository? I think the copy of the theme lives in the data.fs blob somewhere, only thing I could do is download the zip.

**Comment by davilima6** [comment]
I'm sorry I thought you had your code in a repo already, the ZIP will do fine. I'm not sure about logging. If you enable Development CSS/JS buttons on your bundle, does your javascript and css changes work alright? That'd mean you probably *don't* have a syntax error breaking the build.

**Comment by mtowara** [comment]
Hi there,
I did a fresh fork of barceloneta and it's working now, however I was able to build the offending theme locally with grunt without problems. I think something with my bundles might have been messed up.

Still I think it would be nice to have more feedback from the build process in the theme editor( for example like for building the bundles in Resource Registries).

@davilima6 please note that my Issue revolves around the theme editor gui and not the resources registries as your edit of my title would suggest.

**Comment by jensens** [comment]
build button works for me
