### ISSUE TITLE
Build Builder: add Rebuild button

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1182]
After successful build completion, it'd be nice to re-enable `Build` button because it's such a common workflow. Also changing its label to `Rebuild` would help realizing it's again available.

Another UX improvement would be immediately starting build after first click, ie without the need for the second click on modal's Build button.

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity and because here has been quite some changes in the JS story lately.
Please feel free to reopen if you think this should be addressed in the next Plone versions.
