### ISSUE TITLE
overview-controlpanel: Display a default icon for controlpanels that do not register an icon

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1184]
Controlpanels for add-ons look ugly if they have no icon.

**Comment by vangheem** [comment]
We can certainly provide a default fonticon I'm sure.

**Comment by cewing** [comment]
I think this change will do it.  Although maybe it isn't the exact right approach.  @vangheem, @pbauer could you please check my work?

**Comment by vangheem** [comment]
Should be fine.
