### ISSUE TITLE
Collection views do not display lead images set on a content type

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#1185]
Create a custom dexterity type that has a lead image behavior, add one to the site. Create a collection that would display the new content item. None of the available collection views will show the lead image.

**Comment by fgrcon** [comment]
the only view right now  which shows the lead is  summary view. I am  adressing such issues right now.
I will provide small scaled images as well for list and table views.
see https://github.com/plone/Products.CMFPlone/issues/1151

**Comment by jensens** [comment]
@fgrcon I lost the overview on this complex/distributed topic (icons/images in listings) - may you give us/ point us to an current state on this?

**Comment by fgrcon** [comment]
@esteele  Can we close this with 5.01 or  is still something missing?
