### ISSUE TITLE
unlocking a locked article leeds to error but no success

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1186]
Plone 5.0 (5011)

If you edit an article in one brother and try to edit it as another user in another browser then the article is locked. But then try to unlock the article. Fails.

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.locking.browser.locking, line 31, in force_unlock
AttributeError: typesUseViewActionInListings
```

tested locally and at http://demo.plone.de/

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone.locking/commit/532a94ec445addbefa28b877ac685c962805250f
