### ISSUE TITLE
"Display traceback as text" is not found

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1188]
On an error page you have a link named "Display traceback as text". If you click on it you should see a plain text traceback but you get a not found. Btw in the ZMI in the error_log it works.

To reproduce it you could try to follow issue #1186.

tested locally and at http://demo.plone.de/

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone.locking/commit/532a94ec445addbefa28b877ac685c962805250f

**Comment by vangheem** [comment]
I just tested, works fine for me.

Are you sure you aren't running a zeoserver and it just hits the correct client randomly depending on the zeo client your load balancer chooses for you? Maybe you want to activate sticky sessions?
