### ISSUE TITLE
Replace mockup-pat-toggle with patternslib-pat-toggle

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#1192]
see #1189 for an example

**Comment by pbauer** [comment]
@MrTango what is the state on that? At the moment neither the mockup- nor the patternlib-version of pat-toggle seem to be working (tested in Plone 5.0.2.). Not even using https://github.com/plone/plone.patternslib

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity and because here has been quite some changes in the JS story lately.
Please feel free to reopen if you think this should be addressed in the next Plone versions.
