### ISSUE TITLE
Add accordion pattern to resource registries bundles and resources

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1195]
That would provide more in-screen control considering the interaction level required in this screen for some user profiles. Imo there's a bit too much information at once and being able to temporary hiding some of it would do more good than bad on this one.

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity and because here has been quite some changes in the JS story lately.
Please feel free to reopen if you think this should be addressed in the next Plone versions.
