### ISSUE TITLE
Collection result inconsistency with p.a.multilingual 

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1196]
The result in the preview and the final result are inconsistent if p.a.multilingual is turned on.
In the preview the elements outside the language folder are shown. 

![collection_edit](https://cloud.githubusercontent.com/assets/339384/10574270/3c9909dc-7655-11e5-91b2-9b1ed9430024.png)

In the view-version they are not.

![collection_view](https://cloud.githubusercontent.com/assets/339384/10574274/3f3642fe-7655-11e5-8a75-5c524c1b1091.png)

**Comment by petschki** [comment]
this should go into https://github.com/plone/plone.app.querystring

**Comment by rnixx** [comment]
Be aware that you cannot just filter out by language, see https://github.com/plone/plone.app.querystring/pull/29 for more information.

I encountered the same inconsistency with the preview, but have not thought further how to solve it properly

**Comment by jensens** [comment]
this works with collection/querystring now in coredev 5.1 at least (tested here).
