### ISSUE TITLE
Usability: Path selector for collections

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1197]
For the *Location* search term in collections

![location_query](https://cloud.githubusercontent.com/assets/339384/10574345/c1e32082-7655-11e5-9a6a-f74be9983d8f.png)

 the *Related Items* selector from mockup should be used.

![related_items](https://cloud.githubusercontent.com/assets/339384/10574348/c4e51e2a-7655-11e5-9144-bad203c208c6.png)

instead of a blank text field, which is cumbersome for the average editor.

**Comment by davilima6** [comment]
Maybe this and #1196 should be moved in the plone.app.collection repo?

**Comment by petschki** [comment]
this was actually mentioned here nearly 2 years ago https://github.com/plone/mockup/issues/226

**Comment by vangheem** [comment]
@obct537 is working on this. I think he is close.

The idea is that there are 3 modes for location selections:

- "Current folder" -- no selection, auto depth of one: "./::1"
- "Parent folder" -- no content selection, depth of one: "../::1"
- "Custom" -- show select widget along with a field to define the depth

It would hide the internal values that are used.

**Comment by rnixx** [comment]
@vangheem @obct537 please do not forget the usecase as described in https://github.com/plone/plone.app.querystring/pull/29

How do you deal with relative "../../foo" in your solution?

IMO there would be the need of four options:

* parent folder
* current folder
* child folder (like custom above)
* custom (selection and input field as already implemented)

**Comment by vangheem** [comment]
relative "../../foo" would just be using the "custom" option. Select the content.

I did forget one more mode, see my revised comment above.

**Comment by rnixx** [comment]
@vangheem thanks, looks consistent now.

**Comment by rnixx** [comment]
@davilima6 actually this things are plone.app.querystring related

**Comment by hvelarde** [comment]
please add some hints somewhere; this is one of the most frustrating issues any user has when creating a collection.

**Comment by djay** [comment]
@plone/ux-team should review this

**Comment by thet** [comment]
This is already implemented: https://github.com/plone/mockup/pull/615
