### ISSUE TITLE
RFC: Allow merging CHANGES.rst with union strategy in all core packages

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1198]
I used the word 'PLIP' first, but seems too big a word here. RFC (Request For Comment) seems be better. Anyway, this is related to two other issues of this weekend marked as plip: #1179 and #1180.

The idea is to add a file `.gitattributes` to each repo, with these contents:

```
CHANGES.rst merge=union
```

This was done for CMFPlone already, see issue #1008. My idea at time was already to do this for all packages. But might be better to get some feedback for clarity.
Did anyone encounter problems in CMFPlone or other repos that use this `.gitattributes` file?

**Comment by gforcada** [comment]
Big +1!

**Comment by thet** [comment]
+1

**Comment by hvelarde** [comment]
+1

**Comment by jensens** [comment]
+1

**Comment by saily** [comment]
I'm not sure if it's possible but @gforcada i'd suggest we add an optional check in `plone.recipe.codeanalysis` for this

**Comment by gforcada** [comment]
@saily why not? Just look at where the package root is located and check that the file and contents are there :-)

**Comment by hvelarde** [comment]
just remember that, per convention, the changelog entry should be on top of the current development changes block; if the automatic merge put the line in the middle we still have to move it manually.

**Comment by mauritsvanrees** [comment]
I have started adding `.gitattributes` to repos.

I am adding `[ci skip]` to the commit message, which *should* prevent Jenkins from activating, but this does not work. I do have the correct message, right? I think it worked before.

**Comment by mauritsvanrees** [comment]
I have done this for all packages in coredev 5.0. Well, I have skipped the ones that are in the zopefoundation repo. And the ones that have no CHANGES.rst.  I may rename CHANGES.txt to CHANGES.rst and do it for those packages too. And on the coredev 4.3 branch.  But no need to keep this issue open, I will close it.

**Comment by mauritsvanrees** [comment]
If you use the `check-manifest` command (which extends zest.releaser), you may get a complaint that `.gitattributes` is missing from the source dist.  This is being handled in https://github.com/mgedmin/check-manifest/pull/50
