### ISSUE TITLE
content_status_modify will show confirm button

### ISSUE THREAD

**Issue by saily** [plone/Products.CMFPlone#1203]
If you use Plone 4.3.7 with `plone.protect 3.x` you will experience *Confirm action* button because `content_status_modify` is called using a GET request in workflow menu without token.

**Comment by gforcada** [comment]
Quite a lot of other things break if you add plone.protect 3.x actually all of this: http://jenkins.plone.org/job/pull-request-4.3/137

I already fixed and sent a few pull requests for a few packages, but at least for all the AT related packages I've done nothing as I'm already using Dexterity.

**Comment by saily** [comment]
For my tests i've added a new keyword as a quick fix, maybe this helps:

    Click confirm action button if authenticator token is missing
        ${error code}  ${error msg}  Run Keyword And Ignore Error
        ...     Click Element  css=.formControls input[name="form.button.confirm"]
        Log  ${error msg}  WARN

**Comment by gforcada** [comment]
I don't remember which package provides this (plone.app.content/layout/??) but there is already a fix for it, you can try to bump that version and see if it works already. I have quite a few versions forked/patched to make 4.3 work for us at der Freitag with plone.protect > 3.x

**Comment by jensens** [comment]
is this still an issue using https://pypi.python.org/pypi/plone4.csrffixes and pinning the versions as recommended in the Instllation section?

**Comment by saily** [comment]
This seems to be fixed with latest `plone4.csrffixes`. Good Job
