### ISSUE TITLE
z3c.form issue with defaultFactory on dexterity

### ISSUE THREAD

**Issue by loechel** [plone/Products.CMFPlone#1206]
The Issue described in https://github.com/zopefoundation/z3c.form/issues/32 will produce side effects on views if you use defaultFactories that always result in the same default Value for the creator but not other users.

**Comment by ale-rt** [comment]
I think this was fixed in https://github.com/plone/plone.dexterity/blob/master/CHANGES.rst#251-2017-02-27, please feel free to reopen if I am wrong.
