### ISSUE TITLE
PLIP: add checkbox to enable Gitter sidecar to plone/public chat room 

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1214]
see https://sidecar.gitter.im/?ref=producthunt at http://gitter.im/plone/public 

It adds a green "Open Chat" at bottom right corner of the site and clicking on it takes you to the configured Gitter room 

@plone/framework-team 

![screen shot 2015-10-29 at 7 06 05 pm](https://cloud.githubusercontent.com/assets/815418/10835419/35034674-7e70-11e5-974b-b1fce2710df3.jpg)
![screen shot 2015-10-29 at 7 06 10 pm](https://cloud.githubusercontent.com/assets/815418/10835420/39adacf0-7e70-11e5-8906-54bc63c77c7e.jpg)

**Comment by vangheem** [comment]
What is this a plip for? I'm going to remove the plip label. Please close if this is not valid. This doesn't seem to me like a plip for plone core.

**Comment by tkimnguyen** [comment]
This was based on discussion elsewhere (in Gitter!)... I blame @jensens :)
