### ISSUE TITLE
Protect all master and maintenance branches on github from forced pushes.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1216]
Today I saw that someone mistakenly did a forced push to the master branch of plone.app.querystring. See my remarks on this commit (though it may have been a different commit where this happened):
https://github.com/plone/plone.app.querystring/commit/37b93d4c4a7cae9a1272fa88b97dd07078194da2

I have resolved it there, and there is no need to point fingers, as that is not the point. But we should make it impossible to do forced pushes.

You can disable forces pushes per branch:
https://github.com/blog/2051-protected-branches-and-required-status-checks
I have now done that for plone.app.querystring. Earlier I already did this for a few other packages, like CMFPlone and buildout.coredev.

We should do this for all master branches and for the maintenance branches, say for the branches used in Plone 4.3.

This is a lot of clicking. Does anyone know ways of automating this? I have no experience with automating github stuff.

**Comment by davisagli** [comment]
robotframework? :)

**Comment by gforcada** [comment]
I've been wondering about that for some time and mr.roboto should be a good fit. It already handles github interaction, so adding more functionality on it wouldn't be that difficult...

**Comment by jensens** [comment]
in github UI branches can be protected

**Comment by jensens** [comment]
After I did not find anything related in the docs, so I used twitter to ask:
https://twitter.com/yenzenz/status/661677717671276544
At the moment there is no API call to protect the branches.

**Comment by jensens** [comment]
meanwhile most are protected
