### ISSUE TITLE
plone 5 - login screen

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1217]
i have noticed that in some mobile handsets the login screen does not adapt to the screen size. the login button is only 20% visible. this issue is only in vertical mode. in horizontal mode there is no issue. there was no problem in plone 4.3.6. pls check

**Comment by mrsaicharan1** [comment]
Could you point me to the exact file in the repo? I'd like to help fixing this.

**Comment by gforcada** [comment]
@mrsaicharan1 the template might be https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_login/login_form.cpt as for the CSS that styles it, that's another matter. If you get a buildout from [buildout.coredev](https://github.com/plone/buildout.coredev) running you can grep on the `parts/packages` for it.

**Comment by ale-rt** [comment]
I am closing this because of the long inactivity
Please feel free to reopen if this is still an issue in Plone 5.2 or Plone 6.
