### ISSUE TITLE
Resource Registries: broken JS bundle delivery in Diazo?

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1220]
I've been having trouble working with uncompiled vs compiled bundles. Basically in some cases I'm getting my theme's CSS and JS delivered twice when Diazo is enabled, so it seems Development Mode and Dev{CSS,JS} switches don't act as expected. Here are my files:

* Registry.xml: http://pastebin.com/p0B4phNn
* Manifest.cfg: http://pastebin.com/yMfCRkSD
* Rules.xml: http://pastebin.com/w6ZJi6xa

When Diazo is enabled and Development mode is off, there's a `data-bundle="diazo"` which delivers a copy of `mybundle-compiled.css` and also `data-bundle="mybundle"` which delivers `mybundle-compiled.css?version=XXX`. When Diazo is enabled and Devmode is ON, `data-bundle="diazo"` delivers `mytheme-main.less` while `data-bundle="mybundle"` still delivers `mybundle-compiled.css?version=XXX`. So I get duplicated code.

**UPDATE:** Besides (but that should probably be another issue), I couldn't set `registry.xml`'s `jscompilation` value to anything besides theme's root because doing that and also setting an empty value in `manifest.cfg`'s `{development,production}-js` entries seem to be the only way to workaround duplicated JS for now.

Finally, I have empty values for manifest.cfg's `enabled-bundles` and `disabled-bundles` entries. I just copied that from Barceloneta and think it should remain that way, shouldn't it?

I did a lot of trial and error and summarized my findings below:

<table align="center">
    <tr>
        <th colspan="7">
            <p>Theme's custom JS load analysis</p>
        </th>
    </tr>
    <tr>
        <th rowspan="2">
            <p>Registry.xml</p>
        </th>
        <th colspan="2">
            <p>Manifest.cfg</p>
        </th>
        <th rowspan="2">
            <p>Diazo</p>
        </th>
        <th rowspan="2">
            <p>
                <span>Develop. mode: OFF</span>
            </p>
        </th>
        <th rowspan="2">
            <p>
                <span>Develop. mode: ON</span>
            </p>
        </th>
        <th rowspan="2">
            <p>Develop JS: ON</p>
        </th>
    </tr>
    <tr>
        <th>
            <p>develop-<br>ment-js</p>
        </th>
        <th>
            <p>produc-<br>tion-js</p>
        </th>
    </tr>
    <tr>
        <td rowspan="7" align="center">
            <p>{css,js}compilation =<br>theme's root</p>
            <p>
                <span>
                    <br/>
                </span>
                <em>++theme++<br>mytheme/<br>mybundle-<br>compiled.js</em>
            </p>
        </td>
        <td colspan="2" align="center">
            <p>Same as registry.xml</p>
        </td>
        <td>
            <p>On</p>
        </td>
        <td align="center">
            <p><b><i>Compiled 2x (!)</i></b></p>
        </td>
        <td align="center">
            <p><b><i>Compiled,<br>Original (!)</i></b></p>
        </td>
        <td align="center">
            <p><b><i>Original 2x (!)</i></b></p>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center">
            <p>Same as registry.xml</p>
        </td>
        <td>
            <p>Off</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center">
            <p><b>Empty</b><br><i>(the only usable/ predictable option)</i></p>
        </td>
        <td>
            <p>Both</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td rowspan="2" align="center">
            <p>Same</p>
        </td>
        <td rowspan="2" align="center">
            <p>Empty</p>
        </td>
        <td>
            <p>On</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td align="center">
            <p><b><i>Compiled,<br>Original (!)</i></b></p>
        </td>
        <td align="center">
            <p><b><i>Original 2x (!)</i></b></p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Off</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td rowspan="2" align="center">
            <p>Empty</p>
        </td>
        <td rowspan="2" align="center">
            <p>Same</p>
        </td>
        <td>
            <p>On</p>
        </td>
        <td align="center">
            <p><b><i>Compiled 2x (!)</i></b></p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Off</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td rowspan="4" align="center">
            <p>{css,js}compilation =<br>/less, /js</p>
            <p>
                <span/>
            </p>
            <p>
                <em>++theme++<br>mytheme/js/<br>mybundle-<br>compiled.js</em>
            </p>
        </td>
        <td colspan="2" rowspan="2" align="center">
            <p>Same as registry.xml on both</p>
        </td>
        <td>
            <p>On</p>
        </td>
        <td align="center">
            <p><b><i>Compiled 2x (!)</i></b></p>
        </td>
        <td align="center">
            <p><b><i>Compiled, Original (!)</i></b></p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Off</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" rowspan="2" align="center">
            <p>Empty on both</p>
        </td>
        <td>
            <p>On</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Off</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Compiled</p>
        </td>
        <td>
            <p>Original</p>
        </td>
    </tr>
</table>

/cc @bloodbare @albertcasado

**Comment by davilima6** [comment]
As hinted by @fulv, if I define empty values also for `{development,production}-css`, then I stop the Diazo duplications. It works but doesn't make sense, though, since Barceloneta does define those entries and doesn't get duplicate CSS resources.

**Comment by davilima6** [comment]
Finally I get it, this is a feature, not a bug. I thought I had to register my js and less files in two places instead of one but actually I only ever need to touch the new manifest.cfg entries when distributing ZIP-based Diazo-only themes.

For some reason I'm unaware of, even though Barceloneta is distributed as a package it doesn't register its less as resources in what I think should be the canonical way, ie registry.xml. It does so using the new Diazo bundle scheme, which [according to documentation](docs.plone.org/adapt-and-extend/theming/resourceregistry.html#diazo-bundles) was created for standalone static themes. Should we change that in Barceloneta so less confusion is spread, I mean, so we better straighten Plone's communication of the canonical way to do it?

I'm closing this one.

**Comment by davilima6** [comment]
After watching @albertcasado's PloneConf talk I understood that even though it's not distributed as a standalone ZIP, Barceloneta is meant to be an example of the new canonical Diazo-only way of theming.

Problem is I'm not sure that should also mean we should register its resources in Diazo-only bundles, because that's not the canonical way for Resource Registries, is it? Regardless of this changing or not, I'll open a PR adding a comment to its manifest.cfg.

**Comment by sneridagh** [comment]
@davilima6 Have you seen my (updated) talk on theming from this year's Plone Conference? I'm aware that the theming documentation should be revised and finished. You are right, the Diazo bundle was thought keeping in mind the original Diazo purpose.

You can of course, add more resources if required, by using RR or other means. The point is that you have to provide the means by your resources get compiled (via grunt/gulp/webpack). If you have some JS to add to your them you can do it via the theme itself or by using the new manifest.cfg options, develop and production. Same for CSS (LESS resources). However, note that the final production version should be compiled on your side not on Plone's. Albert and I will work on make a series of default Plone 5 themes with all the possible combinations. It's not a promise, but I hope we could deliver.

The reason for all this is not being more opinionated than we already did, leaving to the developer to use whatever tools and compilation of resources like the most and let it use. Not everybody loves LESS and not everybody uses require.js. Plone just puts in place a way to do it, not forced way of doing things.

David Bain ( @pigeonflight ) is also organizing a sprint on theming documentation in January.

**Comment by davilima6** [comment]
@sneridagh How can I know if it was updated? What's the difference? :)

What do you think of plone/plonetheme.barceloneta#58? Could you please merge it?

January is so far away... but I shall participate!
