### ISSUE TITLE
error viewing @@tinymce-controlpanel 

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1221]
This is on the coredev buildout at http://dev.brianledwell.com:8081/Plone/@@tinymce-controlpanel (use admin/admin). That site was created maybe 3-4 weeks ago. Currently on Plone 5.0.1.dev0 (5012). It doesn't show any upgrades as being necessary. Trying to go to the TinyMCE control panel gives this error.  It does not occur in a newly created site.

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 128, in updateWidgets
  Module plone.app.registry.browser.controlpanel, line 48, in getContent
  Module plone.registry.registry, line 74, in forInterface
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.ITinyMCESchema` defines a field `other_settings`, for which there is no record.'
```

**Comment by hvelarde** [comment]
seems to me there's a missing upgrade step for updating the registry.

**Comment by tkimnguyen** [comment]
@vangheem had mentioned to me a while back that coredev buildouts can have this issue since it's only for released versions that people get around to creating upgrade steps

**Comment by vangheem** [comment]
create a new plone site or manually re-run the registry install. This isn't a bug though. This is because you are using master.
