### ISSUE TITLE
Remove Products.ResourceRegistry

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1225]
Don't forget to add deprecation warnings in Plone 4.

**Comment by thet** [comment]
Plone 5 still uses Products.ResourceRegistry. It's used for migrating old-style cssregistry.xml or jsregistry.xml resources over to registry.xml.

However, I think we should find a way to remove Products.ResourceRegistry for Plone 5.1.

I thought it's a setup.py dependency of plone.app.upgrade, but it isn't. Nor it's one of Products.CMFPlone or Plone. I'm wondering, which package depends on it.

**Comment by gforcada** [comment]
@thet maybe you find the answer here: http://jenkins.plone.org/view/Dependencies/job/plone-package-dependencies/lastSuccessfulBuild/artifact/package-dependencies.txt/*view*/

**Comment by hvelarde** [comment]
@thet how do you migrate? where is that documented?

**Comment by jensens** [comment]
done by @ksuess for 5.2
