### ISSUE TITLE
Cleanup and rework: contenttype-icons and showing thumbnails for images/leadimages in listings ...

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1226]
Replaces https://github.com/plone/Products.CMFPlone/issues/1151, https://github.com/plone/Products.CMFPlone/issues/1074  and adresses  https://github.com/plone/Products.CMFPlone/issues/1185 and may be some more.
**Detailed documentation: https://github.com/fgrcon/Products.CMFPlone/blob/documented/docs/icons_in_plone5.rst

I will reopen pull requests when finished (almost done) and tested (as far as I can).
**PRs are interdependend**

@jensens:
you suggested:
nterdependent pull request are not directly possible by now, this was discussed here plone/jenkins.plone.org#126 . But you can make a branch and PR (which is only for testing, not for merge) in buildout.coredev with adjusted sources.cfg - this can then be tested with the PR>mechanism. Its a workaround , but well...

**I created a branch in coredev (see above) but how to start Jenkins with that? I  created  https://github.com/plone/buildout.coredev/pull/140 -> http://jenkins.plone.org/job/pull-request-5.0/529/ which obviously did not fetch sources from fgrcon....**

**Comment by gforcada** [comment]
@fgrcon interdependent pull requests can be tested now: just put all of them (one per line) on the jenkins job for either 5.0 or 4.3.

Have fun!

**Comment by fgrcon** [comment]
@gforcada  Great! thanks...
http://jenkins.plone.org/job/pull-request-5.0/530/

**Comment by hvelarde** [comment]
@fgrcon IMO, is a bad idea to include different issues on the scope of one PR; this could lead easily to errors and could delay the merging of it.

**Comment by fgrcon** [comment]
@hvelarde   you are absolutely right on that, but this really was not my own  decision. I just wanted to contribute  a small feature,  but i found a  lot of  dependend  issues  .... and if you think you can handle  this better: i will suport you as much  as i can,  No need to merge  my proposals - but  just replace it with other ones ...

**Comment by fgrcon** [comment]
sorry  i dn't close this intentionally,(one click to much ?)

**Comment by hvelarde** [comment]
sorry, I have no time, neither knowledge to do what you're doing; I'm just giving my opinion.

something is rotten in the state of Plone if the contribution of a small feature turned into a nightmare of dependent issues; take some fresh air and think about it again...

**Comment by jensens** [comment]
@hvelarde yes, this is indeed one little thing distributed all over the place. I'am not sure if this states that Plone is rotten. Its in the nature of things, that icons are used at several places. The only thing to criticise is, that the original change from v4 to v5 on how icons are used was not implemented completly. Here our quality assurance failed massively.

And I am really happy that @fgrcon took the time and energy to fix this. Thank you @fgrcon! 

I'll try to look at the PR today and merge if possible.

**Comment by fgrcon** [comment]
http://jenkins.plone.org/job/pull-request-5.0/532/ (with all prs)
@jensens @hvelarde  @vangheem  ....
I dont think that plone is such a mess (a long history leeds to some traces, compared to what i have seen since plone 3 the whole process and plone itself have improved dramatically. But of course there always is room for further improvement.)

yes this is quite a time consuming and enervating job and still not finished yet.:
* passing all the tests
* still a fix needed in mockup ( replace portal_type.toLowerCase() with a js implementation of normalizeString ..
* an upgradestep ( reindexing of get_icon) ?? (i am not familiar with upgrade steps yet)
* maybe some fixes in barceloneta as well (contenttype-icons dont show up in related items browser dropdowns, to many ugly bullets in some portlet views ..)

But i think it would be great to get the major things into core **with your help**  asap. (I am getting a little bit tired of rebasing and have a lot of other things in mind with plone)
see  https://github.com/fgrcon/Products.CMFPlone/blob/master/docs/icons_in_plone5.rst . I am just adding some more overview info there.

**Comment by hvelarde** [comment]
don't take my words too seriously, guys; it's obvious that I don't have all the details but... yes, we have a problem with features distributed among dependencies and that's something we have to fix.

**Comment by fgrcon** [comment]
http://jenkins.plone.org/job/pull-request-5.0/536 (with all 8 prs)
**needed to comment out some  tests in mockup/tests/pattern-relateditems-test.js in order to get the build done. These testcases seem to need rework and as far as I can see by a number of manual tests they show false results or i dont understand them.**

**Comment by gforcada** [comment]
@fgrcon down to only one error in p.a.event! You are almost there!

**Comment by fgrcon** [comment]
@gforcada  yes live can be hard and cruel ;-)
http://jenkins.plone.org/job/pull-request-5.0/539

**Comment by vangheem** [comment]
test passed, everything merged. @fgrcon can you make sure I didn't miss anything?

Thanks for your work on this.

**Comment by fgrcon** [comment]
@vangheem only two more left:  https://github.com/plone/Products.CMFPlone/pull/1227 
and https://github.com/plone/plone.app.event/pull/205 

btw: the metadatafield get_icon requires an index rebuild. How can this be done (ipgrade-step?)

**Comment by hvelarde** [comment]
great job, indeed!

**Comment by jensens** [comment]
:fireworks: well done!

**Comment by jensens** [comment]
The upgrade step should go into plone.app.upgrade. I think there are some examples in there, i.e. this one https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v43/alphas.py#L14
It goes a bit deep into catalog internals, but does it in an efficient way.
