### ISSUE TITLE
Static portlet broken when try to insert image or link (Plone 5)

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1231]
* Manage portets > add static portlet
* edit text (tinymce)
* insert link or image  > select image or document 
* click insert:
 you don't get back to the editor but get stuck ....

**Comment by pbauer** [comment]
Clicking save when insertign a link or image closes not only the modal where you add the link/image but also the modal behind that where you edit the portlet. I guess it is a issue with the modal-pattern.

**Comment by fgrcon** [comment]
seems to be fixed with https://github.com/plone/mockup/commit/c9695d6301dccbec78a90df079481108de5195da
