### ISSUE TITLE
Convert test_rendering into view

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1234]
Moved from  plone/plonetheme.barceloneta#59.

There are multiple ideas to enhance test_rendering:
- [ ] Render portlet managers in context
- [ ] Include custom TinyMCE styles
- [ ] A way to specify what the example HTML should be

**Comment by ale-rt** [comment]
It is a view as of now:

- https://github.com/plone/Products.CMFPlone/blob/0725a67f58f48edc6d43f67996ece1d0af2f78b3/Products/CMFPlone/browser/test_rendering.py

Feel free to open specific issues with ideas to improve it :)
