### ISSUE TITLE
New i18n team page on plone.org

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#1235]
The current https://plone.org/community/teams/i18nTeam page is very old.
The most up to date i18n team is in this file:
https://github.com/collective/plone.app.locales/blob/master/docs/TRANSLATORS.html
Not very readable isn't it. (click on Raw, save it and reopen it with your browser)
How the new plone.org handle the different teams? Is this the good tracker or do you have a specific repository for that?

**Comment by jensens** [comment]
you may want to move this question over to https://github.com/plone/ploneorg.core/issues

**Comment by vincentfretin** [comment]
Thanks. https://github.com/plone/ploneorg.core/issues/94
