### ISSUE TITLE
Webdav file upload content type issue in Plone 5

### ISSUE THREAD

**Issue by jswinner** [plone/Products.CMFPlone#1237]
I have a test instance of Plone 5 and when uploading files, like pdf, doc other application mime types, they end up as plain text, not application/pdf. I see in the documentation that this is controlled in zope.filerepresentation. The docs refer to this:

In Dexterity, the PUT() method is overridden to adapt self to
zope.filerepresentation.IRawWriteFile, and call its write() method one
or more times, writing the contents of the request body, before calling
close(). The mimeType and encoding properties will also be set
based on the value of the Content-Type header, if available.

I am using cadaver 0.23.3. Uploading files to my existing plone 3.3.5 site, the files are treated correctly out of the box.

**Comment by hvelarde** [comment]
probably related with this: http://thread.gmane.org/gmane.comp.web.zope.plone.devel/31799
