### ISSUE TITLE
Display LeadImages within Portlets

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1238]
Since we have the leadimage behavior is available in Plone 5, I would like to be able to display that image within the portlets.

I think it would make sense to be able to configure the visibilty per portlet - default off.
Default placement above the item title, big enough to give the image reason to be shown (icon size doesn't make much sense for me)

there is also a pr in that direction https://github.com/plone/plone.app.event/pull/205/

@plone/ux-team

**Comment by jensens** [comment]
@fgrcon ping, since you worked on this, whats the state here?

**Comment by fgrcon** [comment]
yes, thats fully covered already (and merged) see https://github.com/plone/Products.CMFPlone/issues/1226, https://github.com/plone/plone.app.portlets/pull/61,https://github.com/plone/plone.portlet.collection/pull/10, ....
**see summary and screenshots in https://github.com/fgrcon/Products.CMFPlone/blob/documented/docs/icons_in_plone5.rst** but also the discussion in https://github.com/plone/plone.app.event/issues/205

**Comment by fgrcon** [comment]
float thumbs right ...:
https://github.com/plone/plonetheme.barceloneta/pull/60

**Comment by jensens** [comment]
1. after merging plone/plone.app.event#205 - are there any portlets left to cover? like CollectionPortlet?
2. open task: make it configureable if thumbs are shown or not.

**Comment by fgrcon** [comment]
@jensens:
* ad 1: all portlets covered and merged as far as know (p.a.potlets, p.portlet.collection,...)
 there are still some layouts in CMFPlone but wait with merging them, I want to check again (learned a lot in the meantime) -  will do later today)

*. ad 2: see last change in barceloneta: all image tags are rendered  with class image-icon or image-tile
  as mentioned before i would like to add an option to site control panel to globaly enable /disable   the thumbs  like the option for icons -but dont really know how this works. (help appreciated)

* I think we should close CMFPlone#1226 then
  There might be some smaller issues left. I would prefer to create new issues for these accordingly.

**Comment by jensens** [comment]
+1 for closing and creating smaller issues to have separate the scopes.

ad controlpanel: 
- uses plone registry for storing data
- code in https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/controlpanel
- interfaces in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py
- I would add it beside icon visibility here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L1109
- upgrade step needed (plone.app.upgrade) which re-applies the registry to store an initial value, see

**Comment by fgrcon** [comment]
@jensens @thet @vangheem  see prs in  https://github.com/plone/Products.CMFPlone/issues/1241. 
more or less finished (will start a last jenkins ...)

three minor styling issues left:
* leadimages: seems to be an older issue, 
* thumbs in listings when thumbs-on but anonymous: need some spacing)
* foldercontents: ugly positioning of thumbs

I will try to fix them them subsequently

**Comment by jensens** [comment]
@fgrcon thanks for your work, now if i didnt miss something, only the css issues mentioned above are open, right? wow :)

**Comment by fgrcon** [comment]
afaik yes, css issues see: https://github.com/plone/plonetheme.barceloneta/issues/62
thanks for your help

btw: I need new prs  -  i am down to 0 ! :-)

**Comment by gforcada** [comment]
@fgrcon if you need prs then the documentation team and @plone/marketing-communications will most probably like to have a few paragraphs describing the changes, why, what, how, etc etc ;-)

**Comment by fgrcon** [comment]
@gforcada obviously you missed the smily? But anyway documentation is on my plans of course ...
