### ISSUE TITLE
Refactor Archetypes/ATContentTypes related portal tools into AT/ATContentTypes.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#124]
Archetypes / ATContentTypes related tools:

- portal_atct (move into ATContentTypes)
- portal_factory (move into ATContentTypes)
- portal_form_controller (move into ATContentTypes)
- portal_metadata (move into Archetypes)

**Comment by vangheem** [comment]
Closing. This is stale. Update and reopen if necessary.
