### ISSUE TITLE
New option to show/hide thumbs in listings and portlets (site-controlpanel)

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1241]
(Work in proress)
tasks:

* plone.app.layout: new  thumb_visibilty
* CMFPlone: plone.less  , interfaces/controlpanel
* plone.app.upgrades inital registry setting
* extend plone documentation
* plone.po

**Comment by fgrcon** [comment]
http://jenkins.plone.org/job/pull-request-5.0/548/

**Comment by jensens** [comment]
all merged afaict
