### ISSUE TITLE
Language options not visible when default display page is changed - plone 5.0

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1242]
In my plone 5.0 site i have selected 5-6 languages in which the site should be available. While the language options are available in the default welcome page. Since i have made the default display page to be one of the content pages. the language options are not available.

![image](https://cloud.githubusercontent.com/assets/10380993/11164060/e2d41768-8b0b-11e5-9308-d8965d49e80b.png)

The language options are available in the default welcome page. but it is private for me currently.

![image](https://cloud.githubusercontent.com/assets/10380993/11164063/008e9512-8b0c-11e5-9554-cd200af9041e.png)

**Comment by ale-rt** [comment]
It is fine to me.
