### ISSUE TITLE
Need link to return to folder view after managing porlets

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1243]
Need a way to go back to view the folder you were working on after making changes in "Manage Portlets." 

1. The toolbar is empty
2. Clicking the browser (Firefox) back button takes you back to the folder view but does not save changes
3. Clicking on parent folder 1) does not save changes and 2) adds unnecessary navigation steps

![screen shot 2015-11-14 at 12 56 20 pm](https://cloud.githubusercontent.com/assets/7101218/11164993/71c7394c-8acf-11e5-8df6-ea098127b62a.png)

**Comment by davilima6** [comment]
:+1:

**Comment by hvelarde** [comment]
changes are saved via AJAX but there's no feedback on that so the user can get confused.

**Comment by davilima6** [comment]
Actually there's the spinner but I agree it's not enough feedback, it doesn't confirm success, only disappears briefly.

**Comment by davilima6** [comment]
Added in plone/plone.app.portlets#70
