### ISSUE TITLE
Collections: navigation path removed when collection is edited

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1244]
Created a collection and added criteria, saved it. When "edit" for collection is clicked, "Location" criteria is automatically removed. In the screenshot below, prior to editing the collecting, the navigation path was "/new-news-folder" but it is now empty. I have to re-add it every time I edit (this) collection.

![screen shot 2015-11-14 at 1 05 35 pm](https://cloud.githubusercontent.com/assets/7101218/11165032/f84ca514-8ad0-11e5-9ffe-a4c4898758ab.png)

**Comment by jensens** [comment]
just tried this in Plone 5.1b2: after save and edit the value is still there
