### ISSUE TITLE
Content disappear for non-manager when planned into the future

### ISSUE THREAD

**Issue by Gagaro** [plone/Products.CMFPlone#1247]
Only people with the `AccessInactivePortalContent` permission on the `portal_catalog` itself can see the content planned into the future.

The relevent part in the code is https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L380-L382

Is this the intended behaviour or is this a bug?

**Comment by davisagli** [comment]
That's as intended.

**Comment by Gagaro** [comment]
My question maybe wasn't accurate enough. The isssue I have is that the owner of the content can't actually see it after he changed the planned date into the future. How can he find it back without having to go to the direct URL?

**Comment by petschki** [comment]
you can try to give the `Access future portal content` permission to the `Owner` and `Site Administrator` role (rolemap.xml in your profile) and reindex the catalog ... should do the work. but OOTB only Manager can access future content ... maybe this could be a default for CMFPlone rolemap.xml ?

**Comment by petschki** [comment]
btw. `Access inactive portal content` is allowed to the Owner ... see here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/default/rolemap.xml#L20

**Comment by Gagaro** [comment]
The thing is that the permission check is made on the portal_catalog itself (https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L380-L382).

So it is an all or nothing permission, not a by content one.

**Comment by petschki** [comment]
So `rolemap.xml` intends to give the `Owner` access, but the permission check on the portal_catalog denies it ... but why is there a permission check anyway ... this should be done with the `allowedRolesAndUsers` index, shouldn't it?

**Comment by Gagaro** [comment]
`allowedRolesAndUsers` would be `Anonymous` for a published content with an effective date in the future.

**Comment by petschki** [comment]
of course, you're absolutely right ... so you're not able to check this per content ... but you should see it as `Owner` as `rolemap.xml` promises

**Comment by jensens** [comment]
dup of #189
