### ISSUE TITLE
create /recently_modified portal_action/site_actions

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1248]
The built in /recently_modified view is really useful. Could we include it in the site_actions, between Accessibility and Contact? e.g.

![screen shot 2015-11-18 at nov 18 9 36 43 am](https://cloud.githubusercontent.com/assets/815418/11245359/f679e508-8dd7-11e5-946f-485576e7eb3a.jpg)

@plone/ux-team

**Comment by ale-rt** [comment]
I love that view but I am -1 on exposing it to user and bots.
It usually takes time to call that view.
If it goes there please add a rel="nofollow" to the link.

**Comment by tkimnguyen** [comment]
It's like so many of Plone's "best kept secrets". If we don't show it, no one (except weird people) knows it's even a feature.

**Comment by jensens** [comment]
stalled

**Comment by tkimnguyen** [comment]
@jensens you're closing this because it stalled or because it's a bad idea?

**Comment by jensens** [comment]
feel free to revive it. Its just about process. Dropping ideas here as plip formally not one that are stalled just makes things  complex to manage. We may need a label "type: idea".

**Comment by thet** [comment]
+1 on the idea. It's really useful.

@ale-rt this should only exposed to logged in users, so bots wont be able to access it. That would solve your concerns?

It would also be nice to have a filter for all modifications and own modifications. But that expands the scope of this issue.

**Comment by jensens** [comment]
For logged in users this should go into the personal menu or in toolbar.

**Comment by ale-rt** [comment]
fine for me @thet!

**Comment by jensens** [comment]
Someone (tm) should reopen this one and turn it in to a real Plip.....  Just saying.
