### ISSUE TITLE
Creators field should constrain to users vocabulary

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#1250]
shouldn't it? 
right now you can enter any text and save it. (btw. this may cause an evil `UnicodeEncodeError` if you type a non existing user with non-ASCII characters and save it... see https://github.com/plone/plone.app.widgets/issues/120)

**Comment by hvelarde** [comment]
-1 the Creators field could be used to list the name of the person that created some content even if that person does not have an account on the site.

**Comment by petschki** [comment]
I'm ok with that. i'll close this. The Unicode error is tracked in p.a.widgets
