### ISSUE TITLE
plone.namedfile scales do not support webdav

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1251]
In https://github.com/plone/plone.app.imaging/pull/22 I fixed a problem with getting scales using webdav in plone.app.imaging. plone.namedfile has the same problem. I tried doing the same change, but this did not help.

Both scaling implementations return an `ImageScale`.

For plone.app.imaging this is a class inheriting from the Archetypes Image field:
https://github.com/plone/plone.app.imaging/blob/2.0.0/src/plone/app/imaging/scale.py#L6
Due to inheritance, this `ImageScale` has a method `manage_DAVget`. Via `webdav.Resource` this ends up at `manage_FTPget` of `OFS/Image.py`:
https://github.com/zopefoundation/Zope/blob/2.13.23/src/OFS/Image.py#L630

In plone.namedfile, the `ImageScale` is a browser view. This does not have the `manage_DAVget` method:
https://github.com/plone/plone.namedfile/blob/3.0.4/plone/namedfile/scaling.py#L25

Both eventually end up in this line in the ZPublisher, checking it the `ImageScale` instance has an attribute `manage_DAVget`:
https://github.com/zopefoundation/Zope/blob/2.13.23/src/ZPublisher/BaseRequest.py#L111
For `plone.app.imaging` this works, for `plone.namedfile` it fails.

Well, we can add the method to the ImageScale browser view. That seems to work. I'll make a pull request.

**Comment by mauritsvanrees** [comment]
Oops, that should have been a pull request, not a commit directly on branch 2.0.x... Well, should be okay. Let's see if Jenkins complains. And feel free to complain yourself or have other feedback. :-)

**Comment by jensens** [comment]
@mauritsvanrees looks like this is fixed  - so I close this, please reopen if I'am wrong.
