### ISSUE TITLE
control panel for creation/editing/management of portal_actions

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1253]
...either add to an existing one like Navigation or create a new panel that lets people add/edit/delete/reorder portal_tabs etc.

Discussion initially was at https://community.plone.org/t/determining-if-a-new-page-or-folder-shows-in-plone-5-nav/1151/29

**Comment by tkimnguyen** [comment]
@plone/ux-team

**Comment by hvelarde** [comment]
+1

**Comment by bloodbare** [comment]
Could we write a PLIP for it ?

**Comment by tkimnguyen** [comment]
Sure, I'll do that - is there a description of how to write PLIPs now?

**Comment by bloodbare** [comment]
@tkimnguyen https://github.com/plone/buildout.coredev/blob/5.0/docs/plips.rst#how-to-submit-a-plip

**Comment by bloodbare** [comment]
@tkimnguyen I think that we decided recently that PLIPS are on plone/CMFPlone issues repo at github

**Comment by tkimnguyen** [comment]
@bloodbare that page points to dev.plone.org - I thought that was being decommissioned?

**Comment by vangheem** [comment]
plip created here: https://github.com/plone/Products.CMFPlone/issues/1342
