### ISSUE TITLE
Update Site Setup link in control panels

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1255]
I have identified and replaced all `plone_control_panel` ocurrences by `@@overview-controlpanel` in the following packages:

* p.a.caching
* p.a.contentrules
* p.a.discussion
* p.a.multilingual
* p.a.registry
* p.a.theming
* p.a.users
* P.ATContentTypes
* P.CMFPlone
* P.CMFPlacefulWorkflow

I will launch an interdependent pull requests Jenkin job here once I push them all.

**Comment by davilima6** [comment]
Here it is: http://jenkins.plone.org/job/pull-request-5.0/574/

**Comment by jensens** [comment]
the PR test failed - looks because of some CI/Test problem. May you retry?

**Comment by davilima6** [comment]
Here we go: http://jenkins.plone.org/job/pull-request-5.0/577/

**Comment by davilima6** [comment]
It failed in the same manner:

* http://jenkins.plone.org/job/pull-request-5.0/574/console
* http://jenkins.plone.org/job/pull-request-5.0/577/console

```
Traceback (most recent call last):
  File "/tmp/hudson1832578917567346283.py", line 21, in <module>
    response = urllib2.urlopen(github_api_call)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
Build step 'Execute Python script' marked build as failure
Xvfb stopping
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

Am I doing sth wrong?

**Comment by davilima6** [comment]
Green light!

**Comment by davilima6** [comment]
Hi, @vangheem. Why didn't you merge the other PRs? Any problems?
