### ISSUE TITLE
How do I view *all* items of a folder in folder contents?

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1265]
For reordering purposes it is usefull to have all items of a folder on one page. In Plone 4.3 there was such an option but I could not find it in PLone 5.0.
I would expect it at most right option of the batch sizes [ 5 ] [ 10 ] [ 20 ] [ all ].

**Comment by davilima6** [comment]
There's already an issue for this: plone/Products.CMFPlone#735
