### ISSUE TITLE
manage portlets in plone 5: a usability regression?

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1266]
I found ContentWellPortlets a very useful addon and it is also recommended in Plone 5 Documentation (http://docs.plone.org/develop/plone/functionality/portlets.html?highlight=contentwellportlets).
What I get after adding such an addon is something like:
![manageportlets](https://cloud.githubusercontent.com/assets/1640384/11456924/f792bcec-9699-11e5-9613-ba84c28c0a78.jpg)

**When you select the toolbar to be on the side you dont get the portletmanager-dropdown at all**
Then I imported some content (already with some portlets assigned). Now its a very funny (confusing and time consuming) game to guess the correct manager for a portlet ...
The old portletmanager links and views offered much better overview.

Of course i can still work with @@manage-portlets ... but then I often get some js errors like

```
Uncaught Error: Mismatched anonymous define() module: function ($, Base, Registry, utils, Modal, _t, logger) {
  'use strict';

  var log = logger.getLogger('pat-manage-portlets');

  var ManagePortlets = Base.extend({
    name: 'manage-portlets',
  ....
```

**Comment by keul** [comment]
There's also another usability issue I found here: when you are in the manage portlet view (after you catch the right one) there's no "back link", no way to close the page and go back to Plone.

![schermata 2015-12-01 alle 09 37 40](https://cloud.githubusercontent.com/assets/284924/11495935/3659a938-980f-11e5-8ce1-8673681b11ba.png)

**Comment by davilima6** [comment]
There's already an issue for this: plone/Products.CMFPlone#1243

**Comment by fgrcon** [comment]
@keul:  related: https://github.com/plone/Products.CMFPlone/issues/1243

**Comment by keul** [comment]
@fgrcon @davilima6 thanks

**Comment by witekdev** [comment]
Another manifestation of this when the toolbar is set to side position:
https://github.com/collective/Products.ContentWellPortlets/issues/6

**Comment by fgrcon** [comment]
seems to work fine now in 5.1: thanks !
