### ISSUE TITLE
Impossible to export News Item FTI profile from /dexterity-types 

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1267]
Plone 5.0
1. Go to /dexterity-types
2. Select all checkboxes, or a subset containing _News Item_
3. Click the _Export Type Profiles_ button

The resulting zip file does not contain the `News_Item.xml` file.
I'm guessing this is because of the space in the CT name.

**Comment by jensens** [comment]
checked: its fixed in 5.2
