### ISSUE TITLE
change version specification like suggested by pep 8 and pip

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1275]
PEP 8 and other sources recommend to define a ``__version__`` attribute in the module's ``__init__.py`` file and single source it by reading the ``__init__.py`` in ``setup.py`` and parse the version specifier there.

this is maybe the best example on how to do it: https://github.com/mitsuhiko/click/blob/master/setup.py

```
import re
import ast

_version_re = re.compile(r'__version__\s+=\s+(.*)')

with open('click/__init__.py', 'rb') as f:
    version = str(ast.literal_eval(_version_re.search(
        f.read().decode('utf-8')).group(1)))
```

here is a list of other options on how to single-source the version specifier: https://packaging.python.org/en/latest/single_source_version/#single-sourcing-the-version
here is the pep 8 recommendation: https://www.python.org/dev/peps/pep-0008/#version-bookkeeping
zest releaser can still be used with a little extra configuration in setup.cfg: http://zestreleaser.readthedocs.org/en/latest/versions.html#where-does-the-version-come-from

```
[zest.releaser]
python-file-with-version = mypackage/__init__.py
```

some other discussion on that: http://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by thet** [comment]
there was a pull request in icalendar, where this was addressed: https://github.com/collective/icalendar/pull/172

**Comment by hvelarde** [comment]
-1 on this; @thet I think you are misunderstanding the scope as this is not related with the version of the package. PEP 8 specs talks about having a `__version__` attribute on every source file.

that used to be a pattern in the old subversion times, but I haven't seen that for a while.

**Comment by miohtama** [comment]
-1, @thet - this is deprecated practice. Package metadata is the authoritative source for the version number and everybody can read it nowadays. `__version__` is relic from the time Python did not have packaging.

**Comment by thet** [comment]
not that i'd be happy with changing each of our ~200 packages to support what i suggested above, and getting the source code more complicated.

however, I'm not sure about ``__version__`` being deprecated. looks like a lot of packages declare their versions like this - some mention it as a quasi-standard. and it's nice to be able to do ``package.__version__`` instead of having to use the setuptools' ``import pkg_resources; pkg_resources.get_distribution("package").version``. but it reminds me where we had a version.txt file in each Zope "Product" and ugly code to parse it in setup.py if it was already a package.

i think i'm -1 too...

**Comment by jensens** [comment]
thanks :D 
version information is metadata that does not have to reside in code (same with author, license, ...). today we have much better ways to deal with metadata thanks to advanced packaging which was not available some years in past.

**Comment by miohtama** [comment]
@thet: If packages still stick with __version__ it's just because code and people change slower than best practices :)

otherwiseWeWouldNotLookLikeZopeCamelCase() ;)
