### ISSUE TITLE
let bin/instance accept a PORT argument

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1276]
add a ``--port`` option to bin/instance which lets you to overload the http set in zope.conf.
this this lets you to start up another zope instance while others are also running.
add options for other ports too...

most likely something to work at https://github.com/plone/plone.recipe.zope2instance

**Comment by davisagli** [comment]
Yes, please. This would also make it possible to build a single instance in buildout rather than multiple instances which defer only in their port, which would in turn let production buildouts run faster. (Though, we'd probably also need to be able to specify an instance name as a parameter, to avoid colliding on things like the pidfile and log files.)

**Comment by thet** [comment]
Yes, and then - on production environments - you can even start new instances on the fly when you have to increase the number of instances for peformance reasons. If you have a zeoserver running.

**Comment by hvelarde** [comment]
+1

**Comment by jensens** [comment]
but also location of var-directory should be configured then - and much more.

**Comment by thet** [comment]
Anything which is configurable via zconfig. I think we'd need a configuration syntax to support the nested structures which are used in zconfig.

I peeked a bit around in various involved packages. It's not like a quick fix. Although the hardest part would be to fix something in Zope2 or related packages, just because of the process.

**Comment by tomgross** [comment]
You can always point to an alternate zope.conf file in a custom script like this:

```
if __name__ == '__main__':
    sys.exit(plone.recipe.zope2instance.ctl.main(
        ['-C', '/home/tom/buildout.coredev/parts/instance/etc/zope.conf']
        + sys.argv[1:]))
```
I don't think this is worth the extra effort. To put some effort in the WSGI story is much more sustainable I think.

**Comment by jensens** [comment]
ping @do3cc - didnt you told me latest (zope2/zope3?) can use environment variables to overrule zconfig parameters? if so this one is no longer needed.

**Comment by do3cc** [comment]
Yes

https://github.com/zopefoundation/ZConfig/blob/master/CHANGES.txt#L11

With ZConfig 3.10

**Comment by do3cc** [comment]
I wonder if it makes sense to provide a way that zope2instance provides an easy way to set some sensible variables automatically. So that the problems @davisagli mentioned get handled automatically

**Comment by datakurre** [comment]
@thet @davisagli @hvelarde Because this has been stalled for a while, would you accept env variable support in ZConfig 3.10 to be good enough for this?

**Comment by davisagli** [comment]
Looks like I can probably achieve what I was hoping for with that. Thanks for pointing it out.

**Comment by jensens** [comment]
Indeed using environment variables is a good way to solve this issue.
