### ISSUE TITLE
Use CSScomb on core CSS

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1281]
[CSScomb](http://csscomb.com/) is a coding style formatter for CSS; it could be interesting to start using it on Plone.

HT @rodfersou

**Comment by gforcada** [comment]
My approach would be:
- first get it into p.r.codeanalysis
- then write some lines about it on plone.api
- after the above to pull requests merged we can turn that on on core CSS (actually LESS but I guess it will work as well)

**Comment by rodfersou** [comment]
The last version of csscomb is csscom.js https://github.com/csscomb/csscomb.js and there is one grunt task that support it https://github.com/csscomb/grunt-csscomb

**Comment by rodfersou** [comment]
there is a lint option (to integrate with p.r.codeanalysis)
```
$ csscomb --help

  Usage: csscomb [options] <file ...>

  Options:

    -h, --help           output usage information
    -V, --version        output the version number
    -v, --verbose        verbose mode
    -c, --config [path]  configuration file path
    -d, --detect         detect mode (would return detected options)
    -l, --lint           in case some fixes needed returns an error
```

**Comment by rodfersou** [comment]
I didn't find a gulp task for csscomb that explicity says that suport the last version, need some test on that if needed.

**Comment by jensens** [comment]
moved to p.r.codeanalysis

**Comment by rodfersou** [comment]
@jensens I can't find the issue in p.r.codeanalysis

**Comment by jensens** [comment]
@rodfersou #181 - see back referenced issue above above

**Comment by rodfersou** [comment]
@jensens thank you
