### ISSUE TITLE
"Creators" select2 lookup takes very long for many users

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1282]
If you have many users in your site (say, 4000) and you search for one in the "Creators" (or other userbase related fields), it takes really long until the result is returned.
Tried with plone.app.widgets 1.8, Plone 4.3 and plone.app.users 1.2.2.

**Comment by davisagli** [comment]
Are you using standard Plone users or some other user PAS plugin?

**Comment by thet** [comment]
These are standard Plone users...

**Comment by hvelarde** [comment]
we found a related issue some time ago with LDAP users; probably a memoizer can help solve the problems associated with it:

https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/browser/__init__.py#L84:L126

now I think a catalog counter would be a better key.

**Comment by thet** [comment]
i think the problem is, that the query key cannot be used for a catalog filter, as there is no catalog queried.
i guess all users are retrieved and then a filter is applied.
i guess, there are even better query possibilities for ldap, using LDAP API capabilities.

**Comment by davisagli** [comment]
The users vocabulary does a searchUsers by fullname, so a property sheet has to be constructed for each user. I'm surprised it's really slow though since everything should be in the mutable_properties storage in an OOTB site. I'd suggest profiling this.

**Comment by thet** [comment]
will do the profiling...

**Comment by thet** [comment]
Let's close this.
