### ISSUE TITLE
p.a.theming is required before upgrading to 5 from an old version

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1284]
(see http://stackoverflow.com/questions/34113043/upgrading-4-0-10-to-plone-5-missing-iregistry)

If you upgrade to 5 from an old version of Plone and [do not pass Go](https://en.wikipedia.org/wiki/Do_not_pass_Go._Do_not_collect_$200.), er... and forget to install `plone.app.theming` you will see tracebacks like the one at the bottom.

My suggestions:
1. Document that any pre-Diazo version of Plone must be upgraded to an intermediate version (e.g. 4.3.x) before the final upgrade step to 5.  During the intermediate step, install `plone.app.theming`.
2. Would it be possible to somehow trap this error condition, and give a helpful message?

The problem with 2. is that this error will be produced pretty much anywhere - not only during the upgrade, but also just when loading the ZMI.

```
    2015-12-05 17:19:24 ERROR Zope.SiteErrorLog 1449364764.10.146181213601 http://localhost:8080/mysite
    Traceback (innermost last):
      Module ZPublisher.Publish, line 127, in publish
      Module ZPublisher.BaseRequest, line 444, in traverse
      Module ZPublisher.BeforeTraverse, line 97, in __call__
      Module Products.CMFCore.PortalObject, line 75, in __before_publishing_traverse__
      Module zope.event, line 31, in notify
      Module zope.component.event, line 24, in dispatch
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module zope.component.event, line 32, in objectEventNotify
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module plone.app.theming.plugins.hooks, line 33, in onRequest
      Module plone.app.theming.policy, line 91, in isThemeEnabled
    AttributeError: 'NoneType' object has no attribute 'enabled'
```

**Comment by jensens** [comment]
this is primary a doc-task.

cc @plone/documentation-team

**Comment by mauritsvanrees** [comment]
In https://github.com/plone/plone.app.upgrade/issues/98 I include code to install plone.app.theming in 5.0 alpha.
Even without this, I did not see any tracebacks like above when I tried an upgrade today. But your situation may be different.

**Comment by gforcada** [comment]
Fixed with https://github.com/plone/plone.app.upgrade/pull/98
