### ISSUE TITLE
Actions/navigation portlet not updated on contents change folder

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#1285]
# user problem
1. add a footer portlet for actions object_buttons.
2. click contents. change folder
3. the actions will still have urls that point to original folder where contents was activated
# options
1. Have an event on hashchange that reloads any actions portlet.
   - con: reloads the whole page in the background for every click.
2. on hashchange, substitute urls for any link with data-context-sensitive-url="True" on it.
   - con: doesn't handle changes in action conditions
3. Change action portlet actions to adjust their urls on click. 
   - con: doesn't handle changes in action conditions

**Comment by djay** [comment]
Here is my quick and dirty hack to implement solution (1).

```
    (function(history){
    var pushState = history.pushState;
    history.pushState = function(state) {
        // ... whatever else you want to do
        // maybe call onhashchange e.handler
        var res = pushState.apply(history, arguments);
        if (typeof history.onpushstate == "function") {
            history.onpushstate({state: state});
        }
        return res;
    }
})(window.history);

    
window.history.onpushstate = function(e){
    $.ajax({
            url : window.location.href,
            type: 'GET',
    
            success: function(data){
                $(data).find(".portletWrapper").each(function(i, val){
                    var id = val.id;
                    $("#"+id).replaceWith(val);
                })
            }
        
    });
    
};
```
but I'd like feedback on the best way to solve this

**Comment by jensens** [comment]
portlets are not shown in folder contents. menu is reloaded. seems to be no issue any more
