### ISSUE TITLE
fix links to dev.plone.org and PLIP process on plone.org

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1286]
dev.plone.org is going to be shut down, and we have to replace all links to it on plone.org. Also, some process docs are outdated. At least this is the case with core contributor/PLIP docs. To avoid having multiple versions of these documents (they also exist in buildout.coredev repository), I propose to just link to their canonical location (which is docs.plone.org, but I reference only the github locations here because there is another issue proposing a structural change: https://github.com/plone/documentation/issues/470 )

These are the issues I've found so far:

- [x] Replace https://plone.org/community/processes/plips with a link to https://github.com/plone/buildout.coredev/blob/5.0/docs/plips.rst (resp. the version on docs.plone.org)
- [x] Replace the link to http://dev.plone.org/plone/wiki/PLIP with one to this https://plone.org/community/processes/plips with a link to https://github.com/plone/buildout.coredev/blob/5.0/docs/plips.rst in https://plone.org/documentation/glossary/plip
- [x] Fix the links in https://plone.org/community/processes/features
- [x] Replace the https://plone.org/foundation/contributors-agreement/contributors-agreement-explained with a link to the version in this https://plone.org/community/processes/plips with a link to https://github.com/plone/buildout.coredev/blob/5.0/docs/ folder.
- [x] Fix links in https://plone.org/community/teams/aiteam
- [x] Fix links in https://plone.org/community/teams/installers-team/installers-team

Obsolete:
- [ ] This one is out of date and might not be fixed: https://plone.org/news/newsixmonthreleasecycle

Please note, the plips.rst file in buildout.coredev is in the process of being updated: https://github.com/plone/buildout.coredev/pull/149

**Comment by thet** [comment]
@plone/documentation-team 
@3dogMcNeill

**Comment by jensens** [comment]
corrected
