### ISSUE TITLE
New Plone 5 site: can't register new image format using Generic Setup

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#1288]
If you create a new Plone site, then you try to install an add-on with a `registry.xml` GS step like this:

```
  <record name="plone.allowed_sizes" interface="Products.CMFPlone.interfaces.controlpanel.IImagingSchema" field="allowed_sizes">
    <value purge="false">
      <element>hero 1600:500</element>
    </value>
  </record>
```

...the add-on will fail the installation will this traceback.

```
...
2015-12-10 13:06:54 ERROR Zope.SiteErrorLog 1449749214.120.140957074973 
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 478, in _validate
WrongContainedType: ([WrongType('large 768:768', <type 'unicode'>, ''), WrongType('preview 400:400', <type 'unicode'>, ''), WrongType('mini 200:200', <type 'unicode'>, ''), WrongType('thumb 128:128', <type 'unicode'>, ''), WrongType('tile 64:64', <type 'unicode'>, ''), WrongType('icon 32:32', <type 'unicode'>, ''), WrongType('listing 16:16', <type 'unicode'>, '')], 'value')
```

Seems that the issue is a concurrence of the "purge" keyword and some wrong unicode encoding (not debugged deeply).

If you change the registry step removing the purge (then defining from scratch all of the default image formats) the add-on installation will run.
_Then_ you can go back to the purge version: reinstalling will never raise errors again.

It seems like the registry contains some incompatible/corrupted types by default.

**Comment by jensens** [comment]
works meanwhile (I use this in several projects).
