### ISSUE TITLE
useractions popup sometimes opens at top of page

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1295]
1. Create a Plone 5 site.
2. As admin go to the home page.
3. In the bottom of the toolbar click on your user name.

Expected: popup (or submenu) opens next to the user name.
Got: popup opens at the top of the window.

I got this in the current coredev buildout.This worked fine in the 5.0 release.

Errr... what? It only happens in Firefox. Safari and Chrome are fine. It gets stranger. When I login as admin on http://localhost:8080/Plone I get the described wrong behaviour. But when I login as admin on http://mauritsbook.local:8080/Plone (local name of my laptop) it goes fine. This is in both cases without basic authentication.

I threw my var and parts directory away and reran buildout to be sure, but this made no difference. So only on Firefox and only on localhost I get this behaviour. Weird! OS version: Mac OSX El Capitan 10.11.2.
Can anyone confirm this?

Screen shot:
<img width="286" alt="screen shot 2015-12-22 at 11 08 35" src="https://cloud.githubusercontent.com/assets/210587/11953004/f7860622-a89c-11e5-930f-25db769e9eb5.png">

**Comment by fulv** [comment]
I have seen this behavior in Plone 5.0.  I can't remember what I did to fix it, but I will post if I do.

**Comment by allcaps** [comment]
I've seen this happening in Chrome. Refreshing the page 'fixed' it for me.

**Comment by khanstark** [comment]
I think it happens when ul element's `<li id="portal-personaltools" class="plone-toolbar-separator">` gets interfered with enlargement ratio of the browser. Try decreasing zoom level  by 1(`Ctrl + '-'`), you might get just the right alignment.

**Comment by jensens** [comment]
probably fixed in 5.2 or earlier, never saw this again in recent releases.

**Comment by mauritsvanrees** [comment]
I haven't seen this recently either.
