### ISSUE TITLE
TinyMCE looks for en.js and en_EN.js and 404

### ISSUE THREAD

**Issue by allcaps** [plone/Products.CMFPlone#1297]
Reproduce: Create an English Plone site and add a page. In the add page there are the following errors in the console:

    GET http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/en.js 404 (Not Found)  
    GET http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/en_EN.js 404 (Not Found)

English is the default language of TinyMCE therefore Plone doesn't need to request the translation file.

When I create Dutch there are no 404s since `nl.js` is served correctly.

**Comment by frisi** [comment]
see also https://github.com/plone/plone.app.widgets/issues/106

**Comment by hvelarde** [comment]
duplicated with #949
