### ISSUE TITLE
Upgrade to Zope 2.13.24

### ISSUE THREAD

**Issue by loechel** [plone/Products.CMFPlone#1299]
A new Zope 2 Version has been published, upgrade if possible.

**Comment by thet** [comment]
Looks like, it's not released yet?
Here, it's still mentioned as unreleased: https://github.com/zopefoundation/Zope/blob/2.13/doc/CHANGES.rst
And it's not on pypi.

**Comment by jensens** [comment]
Lets skip this and force the Zope 4 Plip #1351
