### ISSUE TITLE
Move/rethink the purpose of the CSS/LESS "Add" button

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1309]
My first time experimenting with theming in Plone 5. This is my experience when trying to create new theme based off of Barceloneta. 

Site Setup > Registry > Add Resource

Went to add a new resource but couldn't add file path because there was no input field next to CSS/LESS label. Because there a large gap between the CSS/LESS label and the button (see image), I thought the input field was missing and that the purpose of the button is type something into the input field and add it by clicking the "Add" button. 

![cssless](https://cloud.githubusercontent.com/assets/7101218/12147931/9d1b630c-b469-11e5-9f8b-cf8a6c99aa6b.png)

However, with @cdw9's help, I realized that I had to click the "Add" button to make the input field appear. 

End state: due to the "Add" button's distance and placement from the CSS/LESS label, its function is not clear. 

Suggestion: place/design the button so it's visually clear that its function is to call a input box

**Comment by mauritsvanrees** [comment]
I close this: in Plone 6 the resource registry is completely different.
