### ISSUE TITLE
PLIP: A direct link from a group name on Sharing tab to that group's member list

### ISSUE THREAD

**Issue by rioksane** [plone/Products.CMFPlone#1310]
## Abstract
As an admin I would like to have a direct link from a group name on Sharing tab to group member list under Portal Settings. 

Use case: as a site admin I often need to check and add permissions on a certain page/folder. The Sharing tab shows groups and user names and their permissions. If I want to add permissions to a user, and there already is a suitable group, I want to check if the person is in the group, and if not, add him/her to the group.  

Right now if I want to do that, I have to do this: 
1. Click my name
2. go to Portal Settings
3. go to Users and groups
4. go to Groups
5. Select the group and see if the user is there

More useful way would be just to 
1. Click the group name on sharing tab -> link takes me to the group member list. 

If I want, I can cmd+click the link to open it to a new tab.

## Motivation
This will make the life on every site admin easier when dealing with groups, users and permissions.

## Assumptions
Lots of unnecessary pointing and clicking.

## Risks
This should be a low risk implementation. We already show the group name on the Sharing tab. The direct url to the group then must be added as an  <a> element. This should not be too complicated to implement. 

There are some automatic groups like Logged-in users, which don't need the link at all. The link should be only on internal Plone groups to make it as simple as possible. The link could be added to LDAP-groups and others, if that's easy to implement. 

Note! The link should be only visible if a user has permissions to see Plone Group settings -> Only for administrator/manager/site admin -roles. This means that users with view, add, edit, review cannot see the link at all on Sharing tab. 

When it come to user experience, the change is so minor, that it shouldn't vex old Plone users. If someone as an admin-role accidentally clicks the link, he/she can easily come back.

## Participants
Asko Soukka..?

**Comment by rioksane** [comment]
This is where the link should be.
<img width="893" alt="link-to-group-members" src="https://cloud.githubusercontent.com/assets/5127672/12195744/17a520ce-b602-11e5-9c53-3b434bca999e.png">

**Comment by ebrehault** [comment]
+1

**Comment by fgrcon** [comment]
+1

**Comment by hvelarde** [comment]
+1

**Comment by frisi** [comment]
+1
instead of showing the linke for managers and site-admins i'd rather go for the permission "Plone Site Setup: Users and Groups"

**Comment by ebrehault** [comment]
@rioksane, your PLIP has been approved by the Framework team, and I am the one in charge of review your PR once it will be ready.
Feel free to contact me for any question.

**Comment by rioksane** [comment]
Great :)

**Comment by ebrehault** [comment]
@rioksane Hi Rikupekka, did you start implementing this PLIP? If you need any help or support of any kind, let me know.

**Comment by datakurre** [comment]
@ebrehault Requesting review. I needed to define more variables in template than I'd liked to. https://github.com/plone/plone.app.workflow/pull/7/files

**Comment by ebrehault** [comment]
Review by Eric Bréhault (ebrehault@gmail.com, barbichu@irc.freenode.net)

The PLIP was reviewed on Ubuntu 15.10 using python 2.7.6 and Chromium 49.0.2623.108.

April 3rd, 2016

# Review steps

- Set up the buildout:
Use `buildout.coredev` on branch 5.1 and add `plone.app.workflow` to auto-checkout and test eggs.
Checkout branch datakurre-plip1310.

- Ran tests for the PLIP's auto-checkout packages::
```
  $ bin/test -s plone.app.workflow
```
- Reviewed code

- Manual testing TTW

# Notes and observations

## Automated testing

- Tests for plone.app.worflow:
No error (same on Jenkins)

- Tests for Products.CMFPlone:
Ran successfully by Jenkins: http://jenkins.plone.org/job/pull-request-5.0/1093/

- Missing tests:
The 2 new tests added to `plone/app/workflow/tests/test_sharing_view.py` are sufficient.

- Test coverage:
100% coverage.

## Manual testing

Logged as admin:
- create a new group GroupA,
- add this group as editor in News folder,
- I see a link on the group label and this link open the group page,
- I can also see a similar link on Authenticated users.

Logged as regular user having editor access on the News folder:
- there is no link on group labels

# Code review

The code is very simple (only few extra lines in `plone/app/workflow/browser/sharing.pt`).
As indicated by @datakurre, several variables have been necessary, but I do not think it is a problem (and it probably canot be avoided anyway). 

# Conclusion
The feature and the implementation are good.
The only problem I have noticed is the link on the Authenticated Users group (which was not supposed to be linked as specified in the PLIP).
It must be fixed before we can merge the PR.

**Comment by datakurre** [comment]
@ebrehault Thanks for the review.

Link for Authenticated Users -groups is now removed as in
https://github.com/plone/plone.app.workflow/pull/7/commits/8ba2e69117d051b42545bf2d984545b1408c7120

FWIW, AuthenticatedUsers is linked on control panel groups management view.

**Comment by ebrehault** [comment]
https://github.com/plone/plone.app.workflow/pull/7 is merged
