### ISSUE TITLE
plone.namedfile 3.0.6 requirement

### ISSUE THREAD

**Issue by papachoco** [plone/Products.CMFPlone#1311]
Is there any reason why plone.namedfile 3.0.6 requires plone.protect. It seems to be a minor upgrade to introduce a hard dependency on a Plone product. We are currently running w/ a minimum set of deps for plone.namedfile (3.0.5)  - (zope and ZODB). Is there any way we could have a release without the plone.protect hard requirement?

Thanks a lot

Carlos

**Comment by thet** [comment]
Not really a big reason, except that no one came across your use case to use plone.namedfile without the Plone stack. You do? Great!

Here is the fix: https://github.com/plone/plone.namedfile/pull/18

Next plone.namedfile release could contain it.
