### ISSUE TITLE
TinyMCE image dialog don't use settings from controlpanel

### ISSUE THREAD

**Issue by marwoe** [plone/Products.CMFPlone#1314]
In a new Plone 5 Site the TinymCE image dialog don't use the settings for allowed sizes from the Image Handling controlpanel (Products.CMFPlone.interfaces.controlpanel.IImagingSchema).

Tested with Plone 5.0 and 5.0.2

![issue-allowed_sizes](https://cloud.githubusercontent.com/assets/16717620/12351268/ad3252f4-bb7c-11e5-8f24-090b537c22c9.jpg)

**Comment by hvelarde** [comment]
I can confirm the same happens in Plone 4.3.

**Comment by agitator** [comment]
@vangheem do you have an idea where tinymce get's the default sizes from?

**Comment by thet** [comment]
Duplicate of: https://github.com/plone/Products.CMFPlone/issues/1717
