### ISSUE TITLE
Theme editor broken with 5.0.2

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#1316]
Seems this was broken and no one noticed.

We need robot tests for the theme editor so we know when this part of the UI because broken.

@obct537 can you add at least a few basic robot tests for the theme editor? Please put them in the CMFPlone package's robot tests.

**Comment by ebrehault** [comment]
Looks like it is just a bundle issue, because it looks good on 5.0 branch.

+1 for robot tests

**Comment by ebrehault** [comment]
Oh, that's ok on master because you fixed it :)

Maybe we could make a new p.a.theming release on Pypi so people who are using 5.0.2 on prod can pin the version manually.

**Comment by acsr** [comment]
pinning plone.app.theming by adding the following line

> plone.app.theming = 1.2.18

to my buildout fixes this for me. Thank you!
