### ISSUE TITLE
Dexterity Control Panel is missing if site is created without default/example content

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1318]
Plone 5.0.2

**Comment by agitator** [comment]
still the case in coredev 5.1

**Comment by hvelarde** [comment]
I can confirm this issue; I think the problem is plone.app.contenttypes is not being installed and Dexterity was installed by it.

**Comment by sor2000** [comment]
I can confirm this issue as well with Plone 5.2.0 (5207) running on Ubuntu 18.04 and both Python 3.6.8 & Python 3.7.3.

**Comment by sor2000** [comment]
I got this working with the Help of #1113 and there I entered step by step for other people like my self on how to deal with this as I was having trouble finding steps.

**Comment by ericof** [comment]
PR merged for Plone 5.2.x branch
