### ISSUE TITLE
Folder content does not respect workflow permissions

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1319]
One of the strengths of Plone is the fine grained workflow / permission model. With the new folder contents of Plone 5.x it is not possible to use this model to full capacity.

Because of
https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/workflow.py#L39
changing state in a workflow is limited to the _"Modify portal content"_-permission.
This is not consistent if a more fain grained permission (and/or a workflow controled permission) is defined in a workflow.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
