### ISSUE TITLE
Deprecate and document migration of Calendar tool

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1320]
Plone 5 completely removed the Calendar tool without warnings on Plone 4; it's important to fix that and to document the new location of the tool (if I understood correctly, it is now embedded in plone.app.event).

**Comment by arunkiddo** [comment]
Can I Work in this issue

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 4.3 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
