### ISSUE TITLE
Thumbs visibility: shown in too much listings

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1322]
There is a new setting in Site Setup, "Thumbs visibility" - defaults to "always". This settings shows image thumbnails in listings (e.g. listing_view and tabular_view), which is mostly great!
But it also shows the thumbs in the navigation portlet and possibly other portlets too. That's IMO too much.

I propose to add an option to show thumbs in portlets to each of the portlets schematas, where thumbs can be shown. The options can be the same as in Site Settings: `false``,``enabled``and``authenticated``.

To illustrate my problem, the following listing doesn't look nice for me:

![plone-thumbs-in-listings-and-portlets](https://cloud.githubusercontent.com/assets/170891/12436924/a56c8bb6-bf19-11e5-83f4-5ad66e195e1e.png)

/cc @fgrcon

**Comment by zopyx** [comment]
Still broken in 5.0.5

**Comment by hvelarde** [comment]
this is not an enhancement but clearly a regression from the original behavior in Plone 4.

**Comment by fgrcon** [comment]
@hvelarde: just switch off the _regression_ in the control panel :-) (  Set Show Thumbs to Never). 
@thet: you are right, more fine granular control of this would be desirable / untill that solved default should be set to NEVER ?

Im thinking about thinking about submitting  a new PLIP to clean up the whole stuff:
* add controls to standard portlets and listing layouts (checkbox show yes /no, additional: dropdown: select thumbsize)
   (overriding the settings in registry)

* see also : https://github.com/plone/plone.app.contenttypes/issues/296 (@petschki)
* rename  meta data field getIcon  to hasImage (to make thinghs clear!)
* better documentation  (still many people seem  to be quite confused about document-type icons, mime type icons, thumbs  ... )

btw:  the icon story needs some cleanup as well  (document type icons vs mimetype icons ,  attachment icon vs pdf, doc, xls ........ )

further related:
pr: https://github.com/plone/mockup/commit/f068f8430a15f0622fe75e5b54e18bd9193c4a84  (@thet where should this option be set ?  right now it seems to be hardcoded in https://github.com/plone/mockup/blame/f068f8430a15f0622fe75e5b54e18bd9193c4a84/mockup/patterns/structure/pattern.js line 51 - which does not make any difference)

https://github.com/plone/plone.app.portlets/issues/69
https://github.com/plone/Products.CMFPlone/issues/1364

**Comment by espenmn** [comment]
Even with thumb visibility off, the thumbs still show if you add a navigation portlet to the footer.

**Comment by thet** [comment]
in plone 6 the listing does look nicer. see: 

![Screenshot from 2022-08-24 17-07-59](https://user-images.githubusercontent.com/170891/186454534-ff93fa81-2173-4824-a176-c45f34c36ea4.png)


I'm closing this, as there is also some fine grained control possible:
- disabling pictures to be part of the navigation
- disabling thumbs altogether.
