### ISSUE TITLE
Remove SiteLogo view

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1326]
we can access the widget view instead:

http://localhost:8080/Plone/@@site-controlpanel/++widget++form.widgets.site_logo/@@download

**Comment by hvelarde** [comment]
@rodfersou is the widget view available to anonymous users?

**Comment by jensens** [comment]
iirc the idea behind the specific view was possibility of cistomization. well. i'am nit sure at all if this makes sense. @thet may know more about this

**Comment by rodfersou** [comment]
@hvelarde yes, it is

**Comment by thet** [comment]
I tend to not jump on this idea.

Pro:
- No need to implement another view. But the view is just a derivation of the @@download view from plone.namedfile anyways.

Cons:
- Exposes details about the @@site-controlpanel location to anonymous users.
- Depends on availability of this widget and it's weak permissions.
- Doesn't feel very right to me.

I'd leave it as it is.

If there other good arguments, please state them here and reopen this ticket.

**Comment by rodfersou** [comment]
@thet thank you for your feedback
