### ISSUE TITLE
Issue with Collection after migration from 5.0 to 5.0.2

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1328]
I had a collection which was working fine. After migration, I edited the same by adding another key word in the tag. The search preview comes up but it does not save the results. Image 1, while i am adding the tags. image 2 after I save.

![image](https://cloud.githubusercontent.com/assets/10380993/12528730/a06991f4-c1c6-11e5-976b-aca4a8908834.png)

![image](https://cloud.githubusercontent.com/assets/10380993/12528733/b45f1e4a-c1c6-11e5-96c9-a63dc44275a3.png)

**Comment by vangheem** [comment]
I have confirmed this. @obct537 can you look at this?

**Comment by vangheem** [comment]
https://github.com/plone/mockup/pull/619 fixes this.

**Comment by fulv** [comment]
@vangheem When is the next release containing the fix for this going to be cut?
