### ISSUE TITLE
assimilate collective.indexing

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#1331]
Move all functionality upstream (Products.ZCatalog) and apply all monkey patches directly to to packages they belong like Products.CMFCore or Products.Archetypes.CatalogMultiplex.

**Comment by gforcada** [comment]
PLIP file for it: https://github.com/plone/buildout.coredev/blob/5.0/plips/merge-collective-indexing.cfg

**Comment by gforcada** [comment]
And a jenkins job is also there: http://jenkins.plone.org/view/PLIPs/job/plip-collective-indexing

**Comment by hvelarde** [comment]
+1

**Comment by tomgross** [comment]
+1
Héctor Velarde <notifications@github.com> schrieb am Mo., 25. Jan. 2016 um
13:18:

**Comment by gforcada** [comment]
There's a PLIP for it already: #1343
