### ISSUE TITLE
Error when running upgrade step "Reinstall plone.app.iterate (all → 121)"

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1345]
I upgraded a Plone 5.0 site to 5.0.2.  After that, I went to portal_setup/upgrades, to see if there were any upgrade steps still left to do.  Under plone.app.iterate there is **Reinstall plone.app.iterate
(all → 121)**.  I'm not sure if it's necessary, but when I run it, I get this traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 954, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module plone.app.iterate.util, line 39, in upgrade_by_reinstall
  Module <string>, line 6, in reinstallProducts
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 770, in reinstallProducts
  Module <string>, line 4, in uninstallProducts
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 742, in uninstallProducts
AttributeError: plone.app.iterate
```

**Comment by mauritsvanrees** [comment]
`portal_setup/upgrades` lists all profiles that have upgrades defined. This includes profiles that have never been applied/installed. I expect that you see this text when you select the plone.app.iterate profile: 'The profile "plone.app.iterate:plone.app.iterate" is currently upgraded to version unknown.' This means it was never installed. So you should not run the upgrade step.
Note that the add-ons control panel in the Plone UI has a special section for upgrades, which does check if profiles/products have actually been installed.

**Comment by thet** [comment]
@mauritsvanrees so, plone.app.iterate was incorrectly listed in upgrade steps? I also stumbled over this error. In your maurits-zmi branch of P.GS, this upgrade profile isn't shown anymore.

**Comment by mauritsvanrees** [comment]
Correct. Current GenericSetup versions simply list all profiles that have upgrade steps defined their zcml.
My branch helps there yes.
