### ISSUE TITLE
The description field is misleading

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#1352]
The description field is a textarea so users think they can enter newlines in their text, but newline characters are not rendered and not preserved.
We should use either:

1. use a text field,
2. or preserve and render newlines.
3. shrink textarea height to only one row and auto expand, when writing longer descriptions.
4. keep a textarea (as it is bigger) but automatically remove newline as the user types it.

**Comment by thet** [comment]
The description has still to comply with the Dublin Core Metadata specification:

http://dublincore.org/documents/usageguide/elements.shtml

> Descriptive information can be copied or automatically extracted from the item if there is no abstract or other structured description available. Although the source of the description may be a web page or other structured text with presentation tags, it is generally not good practice to include HTML or other structural tags within the Description element. Applications vary considerably in their ability to interpret such tags, and their inclusion may negatively affect the interoperability of the metadata.

+1 for option 2), actually. But any structural content has to be stripped out - so the transform, which changes newlines into ``<br/>`` tags must not be applied for the html/head section. Maybe even line breaks has to be replaced with a space...

**Comment by hvelarde** [comment]
+1 on 1 as this is something we've been asked for in the past; +1 also on running a transform for the DC metadata.

**Comment by ebrehault** [comment]
I have added a 4th option, the input will look as a textarea (which encourages the user to enter a longer description if he wants to), but the user will immediately understand newlines are not allowed.

**Comment by fulv** [comment]
We could just strip out structural elements when rendering the description
in the html/head metadata.  Users care less about that than about how it
displays in their content.

**Comment by ebrehault** [comment]
If we decide to keep newlines, I think it is wiser to store the description as it is supposed to be (according DublinCore), and transform it into HTML (by replacing newlines with `<br/>` for instance) rather than the contrary.
If we don't, we will have problem at some point (for instance RSS would break).

Storing newlines should not cause problem (the only thing we need to make sure is to remove them in the `metadata` header tag, as it will be an HTML attribute, so newlines are not allowed).

**Comment by jensens** [comment]
What about store as is, on output transform using text/-x-web-intelligent?

**Comment by ebrehault** [comment]
If you mean to use x-web-intelligent transform to turn the text value into HTML, +1.

**Comment by jensens** [comment]
thats the idea

**Comment by djay** [comment]
I forget which CMS is was but they don't have a description field at all. You select the description from the text using tinymce style or else it picks the first sentance.

**Comment by jensens** [comment]
@djay idea is good, as long it is an option one can override with custom text. any taker for such a javascript/tinymce plugin?

**Comment by hvelarde** [comment]
-1 on that: keep things simple; that's work for an add-on, not for the Plone core.

**Comment by ebrehault** [comment]
> I forget which CMS is was but they don't have a description field at all. You select the description from the text using tinymce style or else it picks the first sentance.

SWe would still need a description field for images, files, etc., so that's probably better to keep it consistant and have a description everywhere.

**Comment by jensens** [comment]
Due to usage of HTML and other metadata of the description it has to be w/o linebreaks. So there is an accessor in plone.app.dexterity.behaviors.metadata defined to strip out ``/r`` and ``/n``. I fixed this to replace them with a space in plone/plone.app.dexterity#217 - I dont think we can do more about it unless we make a real difference between "description - the metadata" and between "description - the text to display in listings". Latter would result in a PLIP. So I close it here.
