### ISSUE TITLE
upgrading to Plone 5 leaves old ZMI configlet name

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1357]
Upgrading a site from Plone 4 to 5 leaves the "Zope Management Interface" configlet name showing up in the right portlet list of configlets, e.g. if you visit /@@dexterity-types what should be named "Management Interface" as per https://github.com/plone/Products.CMFPlone/blob/985bc9107bc60ed79bdbf26170839116be280f25/Products/CMFPlone/profiles/default/controlpanel.xml#L101 is left with its old name.

**Comment by mrsaicharan1** [comment]
I would like to take up this issue. What would be a possible approach to this hurdle?

**Comment by mrsaicharan1** [comment]
What is the expected behaviour in Plone 5?

**Comment by tkimnguyen** [comment]
It should be named "Management Interface"

**Comment by davisagli** [comment]
Current versions of Plone no longer include upgrade steps from such old starting points. And it's arguably a feature to keep existing labels which may have been customized by a site admin. So I'll close this, but I don't feel strongly if someone cares about it enough to add the missing upgrade step.
