### ISSUE TITLE
Problem with Plone5 toolbar "More..." sub menu

### ISSUE THREAD

**Issue by luca-bellenghi** [plone/Products.CMFPlone#1359]
We are detecting a strange behaviour with Plone 5.0.2 and the toolbar.
When the toolbar contains too much elements a "More..." drop down menu appear, and sometimes this menu doesn't work. As far as we can see the sub elements are in the DOM, (with display:none), but the toggle doesn't work properly: the arrow icon changes accordingly to the close/open action, but the sub menu doesn't appear.

We can reproduce this issue going to the folder_contents and browsing the site with the folder contents bredcrumbs. This action reload only the core part of the body (the div with 'order-support' class). After this reload the "More..." menu doesn't works anymore.
We are able to reproduce this problem with with different browser: chrome, firefox and safari.

**Comment by hvelarde** [comment]
could you please include a screenshot?

**Comment by luca-bellenghi** [comment]
I have attached a screencast, so you can see what i mean.


[moremenu.avi.zip](https://github.com/plone/Products.CMFPlone/files/114181/moremenu.avi.zip)

**Comment by jensens** [comment]
is this still an issue in 5.2?

**Comment by ale-rt** [comment]
I tested it https://demo.plone.org/en/demo/a-folder/folder_contents and I was not able to reproduce it.
On Plone 6 the tolbar goes to the side when the viewport width is narrowed.
