### ISSUE TITLE
Add an "email" field type to zope.schema

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1365]
I propose introducing an additional, `TextLine`-based field to zope.schema, called `Email`.  This way, people wouldn't have to add their own custom validators to `TextLine` fields in every project.  A field to capture an email address is one of the most frequent use cases.  We already have a `URI` type, this would be similar.

**Comment by gforcada** [comment]
:+1:

**Comment by hvelarde** [comment]
+1

**Comment by davisagli** [comment]
This already exists in the `plone.schema` package which is included in Plone 5.

**Comment by fulv** [comment]
I *thought* I had seen that somewhere!  Thanks David.
