### ISSUE TITLE
you can no longer create user accounts with no mail account set

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#1367]
# User problem
1. create a new site
2. create a user specifying email address
3. see an error

**Comment by ebrehault** [comment]
I don't get it: you enter an email address or you don't?

**Comment by jensens** [comment]
wild guess (from the title): the mail server settings were not set.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
