### ISSUE TITLE
Clear up Archetypes and ATContentTypes status on Plone 5

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1369]
I have not thought this completely through yet, but I have some notes which are better left here.

Some facts:
- In Plone 4.3, ATContentTypes had no profile at all, and no Extensions/install.py either: installation of types and any other installation was done in CMFPlone.
- In the add-ons control panel, Plone 5 offers install of 'Archetypes Content Types for Plone' (Products.ATContentTypes).
- This installs the ATContentTypes:base profile, since this is alphabetically the first profile.
- In plip #1340 I am changing this logic to always use the default profile if it is available. This is why I am looking at this: suddenly you would be installing the old content types, instead of only the basic stuff.
- PloneFormGen on Plone 5 depends on the ATCT base profile. I guess it should depend on the Archetypes:Archetypes profile instead, but maybe the ATCT:base does a bit more that is required.
- Well, yes: the base profile installs portal_atct, portal_factory, portal_metadata, and some permissions and skins. It depends on profiles Products.Archetypes:Archetypes and Products.CMFFormController:CMFFormController. (But CMFPlone depends on this last one already.)
- CMFPlone sets Products.Archetypes as non installable product.
- Some related issues are https://github.com/plone/Products.CMFPlone/issues/382 and https://github.com/plone/Products.ATContentTypes/pull/22
- In Plone 5 we do not want to support installing the old ATCT content types. The ATCT:default profile is there in case someone really wants it, but you cannot install it in the Plone UI.
- In Plone 5 we *do* want to support installing Archetypes, because we want to support existing add-ons (like PloneFormGen) that are still based on Archetypes. And ATCT:base has some extras on top of Archetypes that such add-ons really need.

Thinking this through, it mostly seems okay, except that plip #1340 threatens to install the ATCT:default profile, which would more or less uninstall plone.app.contenttypes, which is not what we want.

There are several options.

1 Before writing that list down, I thought we might want to switch Archetypes and ATCT around: allow installing Archetypes, but not ATCT. We can keep the existing profiles. In that case, we get this todo list:

- Remove Archetypes from INonInstallable products.
- Add ATCT to INonInstallable products.
- Add uninstall profile for Archetypes.

2 Alternatively, we keep the INonInstallable as it is, but then I would want the following:

- [X] Make ATCT:default an INonInstallable *profile* (not product).
- [X] Adjust the quickinstaller browser view to not prefer the default profile if it is marked as INonInstallable (may need to be part of #1340 anyway).
- [X] Add uninstall profile for ATCT. (working on it)

3 Alternatively, allow installing both Archetypes and the full ATCT separately in the Plone add-ons panel (but then you lose the ability to install Archetypes plus the ATCT base without the types):

- Create ATCT/Extensions/install.py that installs the default profile instead of the base profile.  This is for forward compatibility. (Has no effect if ATCT is not an installable product.)
- Possibly some migration is needed: if ATCT is marked as installed, it currently means the base profile is installed, but the code may start thinking that the default profile is installed. Or upgrade steps may not be found because the code looks for upgrade steps of the default profile and it should look for the base profile instead, or the other way around. I'm not sure if we have a problem here, just something to check.
- Reinstall plone.app.contenttypes when uninstalling ATCT.

Other notes in all cases:

- [X] ATCT:base should not register the Archetypes skin: Archetypes does that itself.

Number 2 seems the way to go to me. That is the least invasive as well.
Thoughts?

**Comment by jensens** [comment]
Complex. Well, even if I may not get all implications:
I'am for option # 2. 
# 3 is too complex and if it needs migrations there are chances to fall in a deep hole.
# 1 is not enough I'd say. It needs ATCT features often.

**Comment by gforcada** [comment]
Just a side note (maybe): given all the incompatible changes that are being worked on (zope 4, python 3, drop legacy code, test isolation) Plone 6 is closer than we would normally expect (IMHO), and support for Archetypes/ATCT on Plone 6 should be dropped already, so I would go for the lowest effort possible.

Working (still unfinished) on #1343 has been proving way more work due to supporting/fixing Archetypes.

**Comment by mauritsvanrees** [comment]
I'll go for number two. Probably as part of PLIP #1340, but maybe this is something that can be done separately.

**Comment by witekdev** [comment]
Just want to link to this issue I just created, in case it is somehow related: https://github.com/plone/Products.CMFPlone/issues/1519

**Comment by mauritsvanrees** [comment]
This is handled in https://github.com/plone/Products.ATContentTypes/pull/32 which cannot be merged yet: we can only do that as part of plip https://github.com/plone/Products.CMFPlone/issues/1340.
