### ISSUE TITLE
Creator filter is lost in search view, if other filters are active

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1391]
Happens with Plone 5.0.2
Steps to reproduce:
1. Go to authors page: https://localhost:8080/Plone/author/jsmith
2. Click link below "Find all articles of ..." -> search view opens with "Creator" as GET parameter Creator=jsmith
3. Filter the search (for example portal type) with the facet. -> "Creator" is reset.

Solution could be:
expose creator via hidden or visible form field in (advanced)search

**Comment by jensens** [comment]
works in 5.2
