### ISSUE TITLE
Can not click develop js/css of currently selected bundle

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1392]
See 

http://public.zopyx.com/ct.mp4
http://public.zopyx.com/ct2.mp4

It is still impossible to properly enable/disable development mode for JS/CSS.

Tested with Plone 5.0.2 and a simple policy package using jsregistry.xml + cssregistry.xml with almost empty styles and JS code, no errors on the console

**Comment by ebrehault** [comment]
@zopyx I do not read German, but I see those videos, I have the feeling you do not click on the Save button (must be "Speichem" button), so it makes sense that nothing happen.

**Comment by zopyx** [comment]
Toggling the "Develop JS/CSS" buttons is clearly not working (the buttons should change their color to orange or something like that).

**Comment by ebrehault** [comment]
You need to click "Develop JS/CSS" and then to click on "Save".

**Comment by zopyx** [comment]
Nope, see

http://public.zopyx.com/ct3.mp4

*not* clicking on the "plone-legacy" allows me to toggle the Develop CSS/JS buttons correctly (they change their color).

Clicking on the "plone-legacy" link as seen in the first two videos cause a broken behavior of the buttons.

Even clicking "Save" allows me to enable one of the "Develop..:" buttons but I can no enable the second one and I can not re-toggle it:

http://public.zopyx.com/ct4.mp4

The UI is broken because only certain click paths are safe while others cause a dysfunctional UI.

**Comment by ebrehault** [comment]
Oh ok I got it this time (and I can reproduce it).
Thank you for detailing the procedure, I did not catch it at the first time.

**Comment by vangheem** [comment]
PR: https://github.com/plone/Products.CMFPlone/pull/1395

**Comment by jensens** [comment]
PR was merged
