### ISSUE TITLE
Browser layer not removed using GenericSetup

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1401]
See: http://stackoverflow.com/q/35490049/644075

CC @mauritsvanrees

**Comment by thet** [comment]
Are you sure, your browser layer name matches the one, under which the layer is registered? Only the name counts - the interface is ignored for unregistering. You could pdb into https://github.com/plone/plone.browserlayer/blob/master/plone/browserlayer/exportimport.py#L64 and see, what happens.

**Comment by hvelarde** [comment]
yes, I'm sure; I checked with a `pdb` and it goes inside the `unregister_layer` and do what is supposed to do but the layer remains there, so this seems not to be related with GS.

this is working in Plone 4.2 and 4.3; and, as you can see in the SO question, Mathias is experiencing the same issue.

**Comment by hvelarde** [comment]
I found the issue... my fault: I'll document it in SO.
