### ISSUE TITLE
Should I be concerned about Errors on initial buildout run on Ubuntu 15.10

### ISSUE THREAD

**Issue by abadger1406** [plone/Products.CMFPlone#1403]
I'm still tryijng to get my Plone 4.2.1.1 upgraded to Plone 5, and want to be sure the two errors show below can be ignored. This is a 'fresh' Plone 5.0.2 install, with buildout run on this fresh install.

Thanks Dave

```
 sudo -u plone_buildout bin/buildout
Updating zeoserver.
Updating client1.
Updating backup.
Updating zopepy.
Updating unifiedinstaller.
Updating precompiler.
Compiling Python files.
Compiling locale files.
Error while compiling /home/Plone5/buildout-cache/eggs/python_gettext-1.2-py2.7.egg/pythongettext/tests/test_escape.po
Error while compiling /home/Plone5/buildout-cache/eggs/python_gettext-1.2-py2.7.egg/pythongettext/tests/test5.po
Updating setpermissions.
setpermissions: Running # Dummy references to force this to execute after referenced parts
echo /home/Plone5/zeocluster/var/backups yes > /dev/null
chmod 600 .installed.cfg
# Make sure anything we've created in var is r/w by our group
find /home/Plone5/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /home/Plone5/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
find /home/Plone5/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /home/Plone5/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
chmod 754 /home/Plone5/zeocluster/bin/*
chmod: changing permissions of ‘/home/Plone5/zeocluster/bin/buildout’: Operation not permitted
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
plone.recipe.command = 1.1
plone.recipe.precompiler = 0.6
```

**Comment by gforcada** [comment]
No idea what those errors are, but first of all they are not in a Plone core package, but instead on python_gettext (so concerning translations) and on top of that the two files that cause the error are on the tests folder, so my assumption is that it would only matter if you were running tests.

So I would say that it's safe to ignore them.

**Comment by mauritsvanrees** [comment]
I agree that this is safe to ignore.

**Comment by ermancio** [comment]
I have the same errors. But Plone doesn't start after buildout.

**Comment by gforcada** [comment]
@ermancio so after running ``bin/buildout`` you try to run ``bin/instance fg`` and Plone does not start? Can you share the stacktrace please?

**Comment by ermancio** [comment]
I started buildout (sudo -u plone_buildout bin(buildout) without editing buildout.cfg and everything is alright.
I want to add an egg editing the buildout.cfg (Ubuntu 15).
Using "sudo -s", I edit buildout.cfg. Then I start buildout and download my egg (first question: where do i find my installed products? Second question: Is it right to edit buildout.cfg with "sudo -s"?).
Anyway when I try to start plone (sudo -u plone_daemon /opt/plone/zinstance/bin/plonectl start),

**Comment by mauritsvanrees** [comment]
@ermancio Is there an error when you start plone on the foreground, so like this?

```
sudo -u plone_daemon /opt/plone/zinstance/bin/plonectl fg
```

I think there might be permission issues, but that is hard to say.
I don't use sudo myself when running buildout or `plonectl` or for editing files, but I guess there can be reasons. Maybe http://docs.plone.org/4/en/manage/deploying/production/ubuntu_production.html has information that helps you setup Plone.

**Comment by ermancio** [comment]
No error when i start Plone.
Anyway I agree with you it's a question of permission.
I'll try to edit buildout.cfg with "sudo vi" double checking that the file doesn't change ownership.

**Comment by jensens** [comment]
``python_gettext`` is not part of Plone. So if this is a problem it should be reported upstream anyway. But I doubt it is a problem for us, just annoying.
