### ISSUE TITLE
cannot download files with spaces

### ISSUE THREAD

**Issue by umlaeute** [plone/Products.CMFPlone#1404]
uploading a file with spaces works fine and replaces all spaces with dashes:
- e.g. upload the file `test file.pdf`
- results in a file `https://example.com/test-file.pdf`

unfortunately downloading becomes problematic, mostly because of the spaces in the target filename:
- `https://example.com/test-file.pdf/view` points to a download link:
- `https://example.com/test-file.pdf/@@download/file/test%20file.pdf`

downloading the latter with _firefox_ gives me

> 400 Bad request
> Your browser sent an invalid request. 

it seems to work with wget and chrome (but @thet suggested it is fixable on the plone-side).

setup:
-   Plone 5.0 (5011)
-    CMF 2.2.10
-    Zope 2.13.23
-    Python 2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
-    PIL 2.7.0 (Pillow)

system:
- Debian 8.3 (jessie) amd64
- haproxy-1.5.8-3+deb8u2
- varnish-4.0.2-1
- nginx-1.6.2-5+deb8u1

**Comment by jensens** [comment]
just tried this in Plone 5.1 works here.
