### ISSUE TITLE
Click on folder takes directs to home page

### ISSUE THREAD

**Issue by abadger1406** [plone/Products.CMFPlone#1405]
After upgrade to Plone 5 some of my directories are no longer accessible through the normal click on folder router....it just takes you directly to the home page.

Interestingly, there are contents in this folder, because if you do a site search, and click on a link for a file within this folder it will show the file.

Suspect some permission issue ...

**Comment by abadger1406** [comment]
events.log does not show anything different...just this same error I get for all folders...

```
------
2016-02-23T18:24:19 ERROR Zope.SiteErrorLog 1456251859.110.909178374638 https://www.gp-mycollaborator.com/MyCollaborator/++plone++static/++unique++2014-08-14%2000%3A00%3A00.000003/contenttypes-sprite.png
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 508, in traverse
  Module ZPublisher.BaseRequest, line 344, in traverseName
  Module plone.resource.directory, line 224, in publishTraverse
NotFound
```

**Comment by abadger1406** [comment]
# tail -f ./zeocluster/var/client1/Z2.log .. slightly edited version

```
127.0.0.1 - Anonymous [23/Feb/2016:18:28:04 +0100] "GET /VirtualHostBase/https/borator.com/borator/choice-programme-engagement-and-communications/360-degree-tour-matthew-evans HTTP/1.0" 200 39711 "https://www.gp-mycollaborator.com/MyCollaborator/choice-programme-engagement-and-communications" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
127.0.0.1 - Anonymous [23/Feb/2016:18:28:04 +0100] "GET /VirtualHostBase/https/borator.com/borator/config.js HTTP/1.0" 200 17059 "https://borator.com/borator/choice-programme-engagement-and-communications/360-degree-tour-matthew-evans" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
127.0.0.1 - Anonymous [23/Feb/2016:18:28:04 +0100] "GET /VirtualHostBase/https/borator.com/borator/++plone++static/++unique++2014-08-14 00:00:00.000003/contenttypes-sprite.png HTTP/1.0" 404 18090 "https://borator.com/borator/++plone++static/++unique++2014-08-14%2000%3A00%3A00.000003/plone-legacy-compiled.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"

```

**Comment by abadger1406** [comment]
Perhaps this is related to the three duplicate users I had to remove prior to the upgrade ?

**Comment by abadger1406** [comment]
I can get to content if I click on content then the little box with arrow...i.e by adding 'view' at end of URL it works, remove the 'view' from URL and you go straight to home page. Also see following error in side menu...

error while rendering plone.contentviews

I

**Comment by vangheem** [comment]
By going straight to the home page, do you mean you get an unauthorized error and it wants you to login?

**Comment by abadger1406** [comment]
I have already logged in as an admin, and no I don't see any authorisation error.

**Comment by abadger1406** [comment]
You can access these folders by either adding view or folder_contents to end of url, but if you remove this you get taken to the home directory

E.G these will work:- (slightly edited url's)

https://borator.com/borator/choice-programme-engagement-and-communications/saturday-sunday/folder_contents

https://wborator.com/borator/choice-programme-engagement-and-communications/saturday-sunday/view

And this will take you to home page:-

https://borator.com/borator/choice-programme-engagement-and-communications/saturday-sunday/

Both the views that work have the following error displayed in side panel:-

error while rendering plone.contentviews

**Comment by abadger1406** [comment]
One other thing...there were errors concerning encrypted documents during the migration, and some of these folders did contain these sort of documents .. could that be the issue ?

**Comment by abadger1406** [comment]
If the contents are deleted from a folder that we currently cannot access then the folder becomes accessible in the normal way!

Shure this how issue is related to this error I see when I add /view to the url - so don't get taken directly to home page and actually see folders contents, but with this error in left hand frame...

![screenshot from 2016-02-26 07-46-06](https://cloud.githubusercontent.com/assets/634924/13346307/357426b4-dc5d-11e5-9d81-3e71990eb450.png)

**Comment by davilima6** [comment]
@abadger1406 Maybe that's some catalog issue? Did you try cleaning & rebuilding it?

**Comment by jensens** [comment]
probably not a bug, but a migration/policy problem
