### ISSUE TITLE
PLIP: Add support for conditionally import registry records

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1406]
## Abstract
Registering resources in Plone 5 is done via GenericSetup using a `registry.xml` file. Implementing conditional imports, similar to what is available in ZCML using the `zcml:condition` directive, could avoid a lot of complexity associated with the way we have to deal with this in different versions of Plone.

## Motivation
To speed up development and make it easier to get add-ons compatible with both Plone 4 and Plone 5.

## Proposal & Implementation
Implement support for something like this:

```xml
<records
    condition="have plone-5" 
    prefix="plone.bundles/collective.lazysizes"
    interface='Products.CMFPlone.interfaces.IBundleRegistry'>
  ...
</records>
```

Compare the complexity associated with the [current proposed solution for a single add on](https://github.com/collective/example.p4p5/tree/master/src/example/p4p5/profiles), that includes 6 profiles, with a standard version that uses only the usual `default` and `uninstall`.

## Deliverables
New versions of plone.app.registry for both branches.

## Risks
I don't see any risks on this.

## Participants
@mauritsvanrees?

**Comment by ebrehault** [comment]
@hvelarde I think it is a good idea. Put my name as seconder.

**Comment by mauritsvanrees** [comment]
Sounds good.

I am not volunteering as participant currently. I have got other stuff on my plate. But some of it is related, so I'll keep an eye on this plip.

**Comment by ebrehault** [comment]
This PLIP is approved for Plone 5.1, see https://community.plone.org/t/framework-team-meeting-minutes-2016-03-01/1663

**Comment by hvelarde** [comment]
awesome!

**Comment by tisto** [comment]
+1

**Comment by idgserpro** [comment]
@hvelarde The link for https://github.com/collective/collective.lazysizes/tree/hvelarde-plone5/src/collective/lazysizes/profiles is broken, is it because now this implementation is on `master`?

**Comment by hvelarde** [comment]
@idgserpro I removed the reference as now seems to me irrelevant.

**Comment by datakurre** [comment]
@hvelarde I accidentally half of this (installed/not-installed) in https://github.com/plone/plone.app.registry/pull/23

I made it as enhancement, because it did not have any side effects for any old registry imports.

I could not do have/have-not, because that information is available only during configuration is parsed and re-reading all ZCML during registry import seemed overkill. Yet installed allows to test if required interface module exists (can be imported) before import.

**Comment by datakurre** [comment]
Well, now I recall that maybe with Zope2 the configuration state is stored globally in memory. Need to check that. If that's the case, I could trivially add support for have/not-have.

**Comment by datakurre** [comment]
Half of this has been implemented in plone.app.registry 1.4 (before I was aware of this PLIP) and the rest is waiting for review in https://github.com/plone/plone.app.registry/pull/24

**Comment by hvelarde** [comment]
a new release with this feature has been made: https://pypi.python.org/pypi/plone.app.registry/1.5
