### ISSUE TITLE
Content browser for link content type

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1408]
The edit widget link object supports internal and external links. An enhancement would be to support content browsing for internal links.

**Comment by thet** [comment]
+1
that would be great.

**Comment by tomgross** [comment]
Implementation is here: https://github.com/plone/plone.app.contenttypes/pull/367

**Comment by agitator** [comment]
fixed with https://github.com/plone/plone.app.contenttypes/pull/367 and https://github.com/plone/mockup/issues/725
