### ISSUE TITLE
One can not change the navigation root name

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#1413]
If you install Plone in German you get a "Startseite" as the root element on your navigation, if it's in Catalan "Inici", and so on.

But you are not able to change that on a per instance basis.

It would be really useful to be able to change that, maybe in the navigation control panel for example?

**Comment by gforcada** [comment]
Actually one can change that via ``portal_actions/portal_tabs/index_html``. So maybe is something that could be made more clear once portal actions PLIP https://github.com/plone/Products.CMFPlone/issues/1342 is merged.

**Comment by jensens** [comment]
This is more about documentation than a bug or missing feature, right?
