### ISSUE TITLE
"Save" button not accessible with a big schema in babel view

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1415]
With a big schema the "Save" button is not visible/accessible in babel view.
# My Setup

Plone 5.0.2 with p.a.multilangual
# Steps to reproduce
- Create a multilangual site
- Add some standard fields to the schema of a content type
- Translate the content
# Workaround

Switch to a fieldset with fewer fields and the "Save" button is accessible

**Comment by jensens** [comment]
fixed by merge of plone/plone.app.multilingual#266
