### ISSUE TITLE
contenttypes-sprite.png missing in fresh Plone 5 site

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1420]
In coredev Plone 5, create a new site. Go to the home page. Open the network tab of your browser. You will see a 404 for contenttypes-sprite.png. Specifically in my case:
http://localhost:8080/Plone5test/++plone++production/++unique++2016-02-26T22:27:38.919407/contenttypes-sprite.png

In Plone 4, this file was in Products/CMFPlone/skins/plone_images/contenttypes-sprite.png
Simply copying the file over from 4 to 5 does not help.
It might not be needed anymore.

**Comment by jensens** [comment]
iirc we replaced this by a partial fontella icon font

**Comment by davidjb** [comment]
Directly relates to #1446; pretty sure the CSS definition for `contenttype-collection` in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/plone-legacy-compiled.css is the only reference and can be removed.

**Comment by jensens** [comment]
probably fixed in 5.2
