### ISSUE TITLE
Plone 5.0.2 not linked in homepage

### ISSUE THREAD

**Issue by canepan** [plone/Products.CMFPlone#1423]
Hello.
Link in homepage of plone.org still links to 5.0, not to the latest one.

Nicola

**Comment by jensens** [comment]
@esteele this should be fixed with 5.0.3 release

**Comment by jensens** [comment]
I tried to fix this, but the route https://plone.org/download/ seems to be an webserver redirect and not  content (Link Type). 

@plone/ai-team may you have a look at this? Best remove the webserver side redirect (or whatever it is) and create a link object at plone.org root?

**Comment by esteele** [comment]
Fixed. 

For what it's worth, the link target is a property of https://plone.org/products/edit
