### ISSUE TITLE
Fix html validation

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1430]
When validation the homepage of a fresh Plone 5 site, there are several errors and warnings. Let's fix them. This is from the validator at https://validator.w3.org:

- Error: Bad value menu for attribute role on element section.
- Warning: Element main does not need a role attribute.
- Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.
- Warning: The banner role is unnecessary for element header.
- Warning: The contentinfo role is unnecessary for element footer.

Some are there multiple times. There can be others, for example when you change the portal_actions footer to show a portlet title (which is ugly by the way, but that is why it is switched off by default).

I have fixed these and will create pull requests and link them here.  There will still be failures on other pages, but this is a nice start.

The most controversial may be the warning 'section lacks heading'. We have various `section` elements with a `header` element in it, but that is not the same as a heading. Headings are `h1`, `h2`, etcetera. And in a lot of these cases it does not make sense to add a heading. My solution in most cases was to simply change the `section` into a `div`. Seems like that is fine for our current css. There were no glaring javascript errors due to this change either. Let's see what Jenkins has to say about that in a while.

Anyway, since it is only a warning, we could ignore it: adding a heading in a section is only a recommendation, not a requirement.

I have added https://github.com/plone/buildout.coredev/blob/5.0/plips/maurits-fix-html-validation.cfg with checkouts and source branches so you can try it out. I'll create the individual pull requests now and feed them to Jenkins in one go.

Pull requests:

~~https://github.com/plone/plone.app.contenttypes/pull/329~~ merged for 5.0 and 5.1
~~https://github.com/plone/plone.app.layout/pull/81~~ merged for 5.0 and 5.1
~~https://github.com/plone/plone.app.portlets/pull/64~~ merged for 5.1 only
~~https://github.com/plone/plone.app.theming/pull/98~~ merged for 5.0 and 5.1
~~https://github.com/plone/plonetheme.barceloneta/pull/90~~ merged for 5.0 and 5.1
~~https://github.com/plone/Products.CMFPlone/pull/1431~~ merged for 5.1 only

For easy copy-pasting in Jenkins:
```
https://github.com/plone/plone.app.contenttypes/pull/329
https://github.com/plone/plone.app.layout/pull/81
https://github.com/plone/plone.app.portlets/pull/64
https://github.com/plone/plone.app.theming/pull/98
https://github.com/plone/plonetheme.barceloneta/pull/90
https://github.com/plone/Products.CMFPlone/pull/1431
```

**Comment by mauritsvanrees** [comment]
Testing all five pull requests together at http://jenkins.plone.org/job/pull-request-5.0/1012/

**Comment by mauritsvanrees** [comment]
Related is this separate pull request which handles a validation error in the social viewlet:
https://github.com/plone/plone.app.layout/pull/78
In the other pull requests, I was testing with the social support switched off.

**Comment by mauritsvanrees** [comment]
This leads to some robot test failures in plone.app.contenttypes like this:

```
Element 'xpath=//section[@id='content-core']' did not appear in 30 seconds
```

Let's see if this path expression works:

```
xpath=//*[@id='content-core']
```

Works locally, when I update to selenium 2.52.0 (otherwise no robot test will work for me), except that there is a random test failure. Random in this case means: it always fails, but not always for the same reason.

In scenario: 'Test Relative Location Criterion' I either do not get enough items back in a collection:

```
AssertionError: Xpath //*[@id='content-core']//*[@class='entry']//a[contains(text(),
 'Document within Folder')] should have matched 1 times but matched 0 times
```

or I get back too many:

```
Element 'id=content' should not contain text 'Document outside Folder' but it did.
```

The failures fit the screenshots I see.

Well, let's try it out on Jenkins, adding a branch of p.a.contenttypes.

**Comment by mauritsvanrees** [comment]
Started new job:
http://jenkins.plone.org/job/pull-request-5.0/1013/

**Comment by gforcada** [comment]
Nice work!

**Comment by gforcada** [comment]
Some time ago I was looking for a way to automate this, ie, start a test and run an HTML analyzer on it to report about this kind of problems.

Unfortunately I didn't find anything, but maybe things have changed since then. Does somebody knows about any software that can do this?

**Comment by mauritsvanrees** [comment]
You are smelling another flake8 plugin. :-)

**Comment by gforcada** [comment]
That could be a robotframework plugin rather than a flake8 one, but indeed I want to write yet another flake8 plugin, to warn about using ``object`` and such other names as variables :-)

**Comment by mauritsvanrees** [comment]
Tests pass at http://jenkins.plone.org/job/pull-request-5.0/1013/
Ready for review.

**Comment by mauritsvanrees** [comment]
Started a new run after changing divs to asides in plone.app.portlets:
http://jenkins.plone.org/job/pull-request-5.0/1017/

**Comment by mauritsvanrees** [comment]
Still green.

**Comment by jensens** [comment]
I would say this one targets Plone 5.1

**Comment by mauritsvanrees** [comment]
Yeah, 5.1 might be better for the parts that change tags.
The parts that remove unnecessary or illegal roles can be merged before that, I think. I can do that manually.

**Comment by gforcada** [comment]
@mauritsvanrees @jensens pinging you as I didn't go through all the pull requests one by one: there is a test failure on 5.1 robot framework tests:
http://jenkins.plone.org/job/plone-5.1-python-2.7-robot/31/console

I see that there are two pull requests still to merge, maybe that fixes it? Let's try it:
http://jenkins.plone.org/job/pull-request-5.1/28/console

Was there any reason not to merge **all** branches together (as that was shown to work, at least on the 5.0 pull request job?).

**Comment by jensens** [comment]
hmm, lets see if both are needed. for some reason while merging this i thought it could be done one by one, but reading again it's more both at once.

**Comment by thet** [comment]
All merged!
