### ISSUE TITLE
resourceregistry: https proxying and js errors

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1433]
We have a deployment, where we have a https-only nginx in front of varnish-pound-zope.
Nginx serves only https and redirects to http into the varnish-pound-zope chain.

we have seen these errors in the browser console:

```
default.js:1924 Mixed Content: The page at 'https://DOMAIN/PATH/folder_contents?_authenticator=84d2a78c88364ed0f0c1d306a2c7e8f206d0497d' was loaded over HTTPS, but requested an insecure script 'http://localhost:8000/PATH/TO_ROOT/++plone++static/components/patternslib/src/core/base.js'. This request has been blocked; the content must be served over HTTPS.
default.js:147 Uncaught Error: Script error for: pat-base
http://requirejs.org/docs/errors.html#scripterror
default.js:1924 Mixed Content: The page at 'https://DOMAIN/PATH/folder_contents?_authenticator=84d2a78c88364ed0f0c1d306a2c7e8f206d0497d' was loaded over HTTPS, but requested an insecure script 'http://localhost:8000/PATH/TO_ROOT/++resource++mockup/moment/pattern.js'. This request has been blocked; the content must be served over HTTPS.
default.js:147 Uncaught Error: Script error for: mockup-patterns-moment
http://requirejs.org/docs/errors.html#scripterror
```

not sure about the cause yet...

/cc @umlaeute

**Comment by umlaeute** [comment]
it seems that the system has a few js (and css) resources (*not* all of them), that are delivered via a hardcoded base-uri of `http://localhost:8000/` (though nothing is listening on port `8000`; iirc the zeo-server *used to* listen on this port but does not longer).

btw, i don't think that the proxy/loadbalancing chain is important in this case (the browser might block the non-https content, but this is just a side-effect leading to the actual problem):
if i bypass the entire nginx-varnish-hyproxy chain and connect directly to the zope-instance, i still see these js/css ressources referred to via `http://localhost:8000/...`

**Comment by thet** [comment]
Probably fixed. If not, reopen.
