### ISSUE TITLE
Improve the "feel" of the Site Setup (@@overview-controlpanel) by removing underlines on hover

### ISSUE THREAD

**Issue by pigeonflight** [plone/Products.CMFPlone#1435]
The Site Setup (ie. @@overview-controlpanel) is more aethetically pleasing when the underlines associated with the hover are removed. 

## Current Site Setup look:

A button on hover: 
![image](https://cloud.githubusercontent.com/assets/31827/13522233/4c8b0872-e1bc-11e5-95d5-6e642c900de5.png)

![icky-controlpanel](https://cloud.githubusercontent.com/assets/31827/13522059/1de7c54c-e1bb-11e5-8fd4-fab664e1c726.gif)

## Proposed new look:
The new look removes the underline, keeps the text the same colour rather than making it blue and adds a little bit of inner shadow on hover to give it a slightly more tactile "feel".

A button on hover: 
![image](https://cloud.githubusercontent.com/assets/31827/13522192/1bdff9bc-e1bc-11e5-8204-0f8f010b5f24.png)

![without-underlines](https://cloud.githubusercontent.com/assets/31827/13521981/9a9e78d4-e1ba-11e5-9f65-25ed015f2d9c.gif)

## Additional Background
It is unusual for buttons in modern interfaces to have underlined text on hover and just "feels" wrong.
For comparison you can look at how button like items are done in bootstrap out of the box.

![bootstrap-no-underline-but-clickable](https://cloud.githubusercontent.com/assets/31827/13521668/4ccae82e-e1b8-11e5-98db-690f58abbc81.gif)

**Comment by pigeonflight** [comment]
To fix this, css/less changes will need to be made in the following file: https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/controlpanels.plone.less

**Comment by davilima6** [comment]
+1

**Comment by pigeonflight** [comment]
See pull request that fixes this:https://github.com/plone/plonetheme.barceloneta/pull/91

**Comment by gforcada** [comment]
Merged
