### ISSUE TITLE
Versioning Files causes "AttributeError: Schema"

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1437]
Was set to "automatic"

Would be nice to version files but if there are reasons against this, don't make versioning an option under 
Content Settings/Version Policy in Site Setup

**Comment by davilima6** [comment]
I couldn't reproduce. Can you check if that still happens in latest stable release (5.0.5)?

**Comment by 3dogMcNeill** [comment]
confirmed fixed in v5.0.5
