### ISSUE TITLE
Use lxml cleaner for safehtml transforms

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1441]
moved from https://dev.plone.org/ticket/14929

**Proposer: Tom Gross**
**Seconder:**
# Abstract

Use the HTML cleaner shipped with lxml to provide the safe_html transform of Plone found in Products.Portaltransforms.
# Motivation

The lxml cleaner class is shipped already with Plone. Some homebacked code relying on CMFDefault, regex and the obsolete SGMLParser can be removed and be replaced with a cleaner and faster implementation of HTML code cleaning.
# Proposal & Implementation

Replace the SGMLParser / regex solution with the HTML cleaner shipped with lxml, which is a Plone dependency already.
# Deliverables

A branch of Products.Portaltransforms with the new implementation of the safe_html-transform.
# Risks
- The output of HTML might change in a subtile way and break many tests of Plone or third parties, which rely on this output. 
- Needs a security audit?
- Might need additonal tests with broken HTML 
# Participants

@tomgross @prakharjoshi @tisto 
# Progress

Most of the code is done as part of GSoC2015 and can be found here https://github.com/collective/experimental.safe_html_transform . We have a transform script that have been developed using lxml and we have added the control panel for the add-on with the deregistration of safe_html from portal_transform on installing of this new safe_html transform and we have also created a uninstall profile for the add-on. Also the TinyMCE integration of the script is almost done. Now the thing that is left is the integration of control panel with the script so that user can modify the transform to work according to their needs. 
# Products affected
- [x] https://github.com/plone/plone.app.discussion/pull/97
- [x] https://github.com/plone/plone.outputfilters/pull/20
- [ ] https://github.com/plone/Products.PortalTransforms/pull/14
- [x] https://github.com/plone/Products.ATContentTypes/pull/35
- [ ] Products.CMFPlone

**Comment by prakharjoshi** [comment]
The tests need to be taken care as this script gives result quite different from old script so tests that are dependent on script output will definitely gonna break so it will be great if we remove those test cases and add the test cases from experimental.safe_html_transform as most of the tests in experiment safe_html_transform are for script output only. This is the one way I can see right now, there may be other ways to integrate this :)

**Comment by gforcada** [comment]
:+1: !

**Comment by jensens** [comment]
Thanks!
