### ISSUE TITLE
pat-toggle does not work

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1442]
Tested in Plone 5.0.2: the toggle-pattern of mockup (https://plone.github.io/mockup/dev/#pattern/toggle) seems to be not enabled. After adding the following html to a page (can be done in TinyMCE) a click shoud toggle the class `documentFirstHeading` but does not. 

``` html
<h1 class="pat-toggle"
    data-pat-toggle="value:documentFirstHeading;">This header should get a underline upon click</h1>
```

How can I enable pat-toggle?

**Comment by khanstark** [comment]
@pbauer It seems that u have some pattern dependency issues. I am also using 5.0.2 and I tested the toggle pattern separately, it seems to be working good. Do you have this problem with other patterns also or they work fine?

**Comment by pbauer** [comment]
@khanstark I added the html mentioned above to http://demo.plone.de/de/demo/eine-seite and it does not do anything.

**Comment by sneridagh** [comment]
@pbauer @khanstark Any follow up on this?

**Comment by pbauer** [comment]
@sneridagh This still does not work in 5.1b2-pending.

**Comment by sneridagh** [comment]
I took a quick look and it seems that we are not including it by default in the Plone bundle...

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/plone.js#L25

... adding the resource manually to a view works fine.

Question is, should we add to the bundle some JS that we are not using in default Plone, but is potentially useful and easy to add while building sites?

We are already advertising it on https://plone.github.io/mockup but we are not enabling it by default... I wonder if that's the only case or there are others similar in default JS.

**Comment by pbauer** [comment]
I don't see a reason why we make it hard to actually use patterns. One big point of patterns is that people can do fancy stuff without writing javascript. When you have to not only write javascript but also create a custom bundle to make use of patterns it defeats this purpose. So: +1 on including it.

**Comment by pbauer** [comment]
This works in Plone 6. Example:
```html
<p><button class="btn btn-primary pat-toggle" type="button" data-pat-toggle="value:btn-lg;">
This button goes bigger/smaller!
</button></p>
```
