### ISSUE TITLE
The navigation on the calendar widget

### ISSUE THREAD

**Issue by pigeonflight** [plone/Products.CMFPlone#1445]
Current navigaton on calendar widget:
![image](https://cloud.githubusercontent.com/assets/31827/13592042/5e589080-e4bc-11e5-9ac0-33fc57c81c92.png)
The blue feels out of place.

Proposed navigation on calendar widget:
![image](https://cloud.githubusercontent.com/assets/31827/13592109/1a9fa706-e4bd-11e5-81c7-6b3f707721ad.png)

Changing the colour from blue to grey is a simple fix which makes it feel more "complete" and unified.

**Comment by thet** [comment]
+1.
IMO, this should match our general link highlight strategy - if there is one. Other 2nd level link elements should also be grey like that.

**Comment by davilima6** [comment]
+1 @pigeonflight

**Comment by janga1997** [comment]
Can someone please guide me as to how to download the widget to debug it? I tried using ./bin/buildout co plone.formwidget.datetime, but I couldn't find any CSS files to edit.
What am I doing wrong?
