### ISSUE TITLE
Chinese characters displayed in menu on IE11

### ISSUE THREAD

**Issue by abadger1406** [plone/Products.CMFPlone#1448]
![image](https://cloud.githubusercontent.com/assets/634924/13602887/4bac21ac-e531-11e5-9e6e-2fda973ae9e6.png)

**Comment by abadger1406** [comment]
The menu looks fine in latest Firefox and Chrome browsers....this is a system that came from a big upgrade from Plone 4 to Plone 5.

**Comment by gforcada** [comment]
Did you check the browser's developer tools/console to see if there's any error there? These Chinese characters are supposed to be replaced by a custom font that plone should provide, but seems it does not on your case.

If that's a migration, can you check if a newly created site already on Plone 5 has the same issue? So we can discard a general error but just an upgrade one.

**Comment by abadger1406** [comment]
![image001](https://cloud.githubusercontent.com/assets/634924/14283181/1c1547e2-fb3a-11e5-9f21-1f3c47f36541.png)

**Comment by abadger1406** [comment]
What do I need to upload to fix this issue ?

**Comment by gforcada** [comment]
You seem to have a problem with the resources provided by the theme, usually these chinese characters are replaced with icons, some CSS and/or JS is not being loaded, can you check your browser console and see if there is any error?

**Comment by abadger1406** [comment]
There are no errors but these warnings are given in the Console:
 
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: @@overview-controlpanel
Usage of the mockup-patterns-base pattern is deprecated and it will eventually be removed.Instead, use pat-base and explicitly set parser to 'mockup' when calling extend.
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
patterns.Patternslib Base: This pattern without a name attribute will not be registered!
Usage of the mockup-patterns-base pattern is deprecated and it will eventually be removed.Instead, use pat-base and explicitly set parser to 'mockup' when calling extend.
 
Screen shot to confirm……

![image](https://cloud.githubusercontent.com/assets/634924/14291491/b9527d9c-fb5b-11e5-8a21-4202205ba214.png)

**Comment by jensens** [comment]
looks like a migration/specific problem to the site when fonts are not loaded are similar.
