### ISSUE TITLE
p.a.controlpanel migration doesn't copy p.a.multilingual settings yet

### ISSUE THREAD

**Issue by fredvd** [plone/Products.CMFPlone#145]
The upgrade code copying settings from the different portal tools to plone.app.registry is for the Language Schema for now only copying some basic fields and not honoring the extended list of properties on portal_languages when you use multingual. A full list is in a schema in plone.app.i18n .

We should probably first close this plip and afterwards improve the migration to take multilingual into consideration

**Comment by jensens** [comment]
if this is still the case i consider this as a bug/ unfinished feature.

**Comment by vangheem** [comment]
Is this still an issue? This doesn't seem like a plip. Closing for now. Please re-open if this is still a problem.
