### ISSUE TITLE
Impossible to insert an internal image (Plone 5.0.3-pending) for non-English site

### ISSUE THREAD

**Issue by serge73** [plone/Products.CMFPlone#1450]
Plone 5.0.3 after upgrade 5.0.2:

Impossible to insert an internal image when the document is edited.
Can find, but can't insert.

**Comment by serge73** [comment]
solution: downgrade plone.app.content to version 3.0.17

Add new issue: https://github.com/plone/plone.app.content/issues/77#issue-140782426

**Comment by serge73** [comment]
The problem appears when using Russian, Polish, African and probably any other non-English

**Comment by davilima6** [comment]
Duplicate of plone/plone.app.content#77
