### ISSUE TITLE
plone.app.iterate - Cancel Check-out error

### ISSUE THREAD

**Issue by agnogueira** [plone/Products.CMFPlone#1452]
When you try to cancel the check-out of a page from the original page, Plone deletes the original page instead of the working copy.

![iterate-checkout](https://cloud.githubusercontent.com/assets/1030139/13647927/13a5a6c2-e615-11e5-874a-9faf2f9cb139.png)
![iterate-checkout2](https://cloud.githubusercontent.com/assets/1030139/13647935/1947d19a-e615-11e5-8b78-33bc827d6300.png)
![iterate-checkout3](https://cloud.githubusercontent.com/assets/1030139/13647941/1f56e9c2-e615-11e5-9544-1eb7f673725e.png)
![iterate-checkout4](https://cloud.githubusercontent.com/assets/1030139/13648115/e45ed0cc-e615-11e5-95f7-c1ad065586ec.png)

How to reproduce:
1. Create a new plone site and install plone.app.iterate;
2. On the frontpage, click Action / Checkout;
3. Go back to the home page;
4. Click Action / Cancel Checkout.

Plone will delete the original content. 
The copy remains alive but will show a error message in toolbar and in message area.

Expected behavior:
Delete the copy

**Comment by rodfersou** [comment]
Another Expected behavior:
Don't delete the original content.

**Comment by davisagli** [comment]
Could not reproduce in Plone 6. The original page was locked by the creation of the working copy, and "Cancel checkout" was not available on the actions menu.
