### ISSUE TITLE
more than two criterion in the collection 

### ISSUE THREAD

**Issue by serge73** [plone/Products.CMFPlone#1455]
Test 1. Plone 5.0.2 fresh instance
Test 2 , Plone 5.0.2,  mockup 2.1.3, plone.app.collection 1.1.6

identical result:

**1. Add new collection**

![img1](https://cloud.githubusercontent.com/assets/13430305/13681118/8253fb7e-e71d-11e5-85db-af02312fad3d.JPG)

**2. Result**

![img2](https://cloud.githubusercontent.com/assets/13430305/13681124/89265c8a-e71d-11e5-8773-4783ae22d878.JPG)

**3. Edited again**

![img3](https://cloud.githubusercontent.com/assets/13430305/13681126/8de454ac-e71d-11e5-93e2-91ab20746b9a.JPG)

**4. Object is locked**

![img4](https://cloud.githubusercontent.com/assets/13430305/13681134/9603c4f6-e71d-11e5-8051-dde3d79b124c.JPG)

Test3 Plone 5.0.3

No Problem

What is the difference?

**Comment by fulv** [comment]
See https://github.com/plone/mockup/pull/619 and other issues referenced
therein.

**Comment by serge73** [comment]
https://github.com/plone/Products.CMFPlone/issues/1328
issues is CLOSSED. why?

![img5](https://cloud.githubusercontent.com/assets/13430305/13684571/27102362-e72e-11e5-95fc-537bae6e0b59.JPG)
![img6](https://cloud.githubusercontent.com/assets/13430305/13684578/3081f308-e72e-11e5-884d-ae1f88546dec.JPG)

**Comment by serge73** [comment]
I resolve this problem only by switching to Plon 5. 0. 3 and updating the filesystem
What I do:
1. Update all products in versions.cfg (5.0.2)  to  versions.cfg (5.0.3),
exception:
- Plone;
- Products.CMFPlone;
- plone.app.discussion (2.4.10 not working with 5.0.2);
2. Test issue - failure;
3. Update exception from paragraph 1 and  upgrade Plone.
4. Test issue - passed

Who knows other solutions?

**Comment by serge73** [comment]
There is no problem in version 5.0.3 Plone.
Issue closed.
