### ISSUE TITLE
Handle SVG image

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#1460]
Users often try to put an SVG image in an Image content.
It is not supported (because the Image content expects the fiel to be a bitmap in order to generate the different scales versions).

It could be nice to support SVG (I guess we just need to disable the resizing and replace it with a super-simple `<img width="THE-WIDTH" src="my.svg" />` when the mimetype is SVG but I haven't looked into it)

**Comment by hvelarde** [comment]
+1

**Comment by thet** [comment]
That's worth a PLIP, no?

Some of my clients often try to upload PDF files as images. Which also doesn't work. I'd love to see the File and Image types combined. Images are files, but with additional scales.

Slightly related: https://github.com/blog/2112-delivering-octicons-with-svg and https://speakerdeck.com/ninjanails/death-to-icon-fonts
Maybe I should open up a separate issue proposing replacing icon fonts with inline svg.

**Comment by tomgross** [comment]
Fixed with plone/plone.namedfile#39

**Comment by jensens** [comment]
merged plone/plone.namedfile#39
