### ISSUE TITLE
Allow to build CSS for file system based themes

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#1468]
When we create a theme addon which inherits from Barceloneta, we cannot use (easily) our own toolchain to compile our LESS files, because things like:
```
@import "++theme++barceloneta/less/barceloneta.plone.less";
```
won't be supported.
And we cannot use `plone-compile-resources` to compile Diazo resources.

Fortunately, we can go to the Plone theming editor, and use the "Build CSS" button.
Unfortunately, it fails (because we are not allowed to write in a FilesystemResourceDirectory).

We should return the generated CSS to the browser so we can copy/paste it in our add-on.

**Comment by ebrehault** [comment]
I have implemented it: https://github.com/plone/mockup/pull/648 + https://github.com/plone/plone.resourceeditor/pull/17

@vangheem, @datakurre, do you think it is a good idea?

**Comment by vangheem** [comment]
Looks good to me.

**Comment by datakurre** [comment]
@ebrehault Nice! Next step would be to figure out nice UX for version control actions, becuse FSResourceDirectory could easily be a repository. Another use-case for that would be me finishing my gitresource-plugin (maps git repo as resourcedirectory using dulwich) :)
