### ISSUE TITLE
Plone 5 - the addons control panel no longer shows the addon version number

### ISSUE THREAD

**Issue by witekdev** [plone/Products.CMFPlone#1472]

**Comment by hvelarde** [comment]
here is a screenshot:

![selection_013](https://cloud.githubusercontent.com/assets/341393/13792758/43c9be44-ead2-11e5-9204-bd6ee09c24a2.png)

**Comment by jensens** [comment]
This is still an issue.

**Comment by hvelarde** [comment]
I don't know how this information was obtained before, but I think this was lost at some point when we decide to get rid of the `portal_quickinstaller` tool.

as long as I see, profiles don't include version information:

```python
(Pdb) pp [p for p in profiles if p['title'] == 'collective.lazysizes']
[{'description': u' Integration of lazysizes, a lightweight lazy loader, into Plone.',
  'for': None,
  'id': u'collective.lazysizes:default',
  'path': u'/home/hvelarde/collective/lazysizes/src/collective/lazysizes/profiles/default',
  'post_handler': None,
  'pre_handler': None,
  'product': 'collective.lazysizes',
  'title': u'collective.lazysizes',
  'type': 2,
  'version': u'7'}]
```

probably we need to hack `portal_setup.listProfileInfo()` to include the information; any ideas @mauritsvanrees?

**Comment by witekdev** [comment]
@hvelarde thanks for following up on this.

**Comment by mauritsvanrees** [comment]
For the record, this has nothing to do with the PLIP for getting rid of the `portal_quickinstaller`, which is new in 5.1. The versions are already gone in 5.0.  4.3 still shows them.

Anyway, it seems good to show them, and your pull request does that.

Maybe good to do that on 5.0 too?

**Comment by hvelarde** [comment]
fixed all over the place!
