### ISSUE TITLE
Wrong user roles with Plone Active Directory

### ISSUE THREAD

**Issue by davidemoro** [plone/Products.CMFPlone#1474]
I've migrated an old Plone site to 4.3.7 with `Plone Active Directory` PAS plugin and the catalog no more returns brains of private object for authenticated users (even managers).
Tested with:
- Plone 4.3.7
- Products.PloneLDAP 1.2
- Products.LDAPUserFolder 2.27
- Products.LDAPMultiPlugins 1.14

If a third party user implementation returns a list of roles plus the `Anonymous` one, your users won't be able to search for private contents through the catalog even if you are a manager.
See  https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L311

I think it would be fine changing that if statement with a more restrictive condition like `'Anonymous' in result and len(result) == 1`

**Comment by davidjb** [comment]
+1 for a fix to this issue.  I've been patching around this for a while, since 4.1 -- see the original bug report at https://dev.plone.org/ticket/12094.

My patch from 4.x (working at least until 4.3.7) is at http://pastie.org/2603659

**Comment by jensens** [comment]
PloneLDAP is not core, report there.
