### ISSUE TITLE
Inconsistent behavior of plone.multilingual.manager.TranslationsManager:get_translations()

### ISSUE THREAD

**Issue by do3cc** [plone/Products.CMFPlone#1477]
Currently, the code does an unrestricted Search, then does a getObject on each object.
Unfortunately, this is does a restrictedTraverse.
This means that currently, if code executed is by a user who does not have access to all objects, the method throws an exception.
It should either return all objects without any permission check or only the objects the user is allowed to access. This should also be explained in the docs.
I'd love to put this bug report in plone.multilingual, but it does not have a bugtracker yet.
cc @saily

**Comment by pbauer** [comment]
Here you go: https://github.com/plone/plone.multilingual/issues

**Comment by do3cc** [comment]
Thanks!
