### ISSUE TITLE
plone.namedfile with plone.app.caching has stale content problems

### ISSUE THREAD

**Issue by do3cc** [plone/Products.CMFPlone#1479]
Caching is hard.
When I use the proper way to generate image tags for a page, the URL will contain an UUID.
If I modify the image, the UUID Url will become invalidated.

Both Pages and Folders use weak caching, an ETAG header is set.
Even if the image is in a folder, the folder does not get his modified field updated. So with most configurations the ETAG header stays the same, the browser will happily use the old url.

I can configure plone.app.caching to make the catalogCounter part of the etag. This means that after any change that gets catalogued, all weak cached things are invalidated.

Unfortunately if I update the image, only changing the image file, the catalog is clever enough to realize that no indexed value got changed and the catalogCounter does not get incremented.

the traverser of plone.namedfile could try to improve the situation by keeping the information a while longer and triggering something that will change the etag header of all pages that link to the resource.

cc @saily

**Comment by mauritsvanrees** [comment]
This doesn't have anything to do with caching. It happens without caching too.

Tested on current Plone coredev 4.3. The image can be either the standard ATContentTypes Image or an own dexterity image.
Also tested on current Plone coredev 5.1, with only Dexterity.

Scenario 1:

- Create an image.
- Create a Page that shows the mini scale for this image.
- Modify the image: upload a new one (or transform the image in case of ATContentTypes)
- The page still shows the old scale.
- Restart Plone.
- The page shows the new scale.

Scenario 2:

- Create an image.
- Create Page 1 that shows the mini scale for this image.
- Create Page 2 that shows the mini scale for this image.
- Modify the image.
- Edit Page 1. Don't change anything, just save.
- Page 1 shows the new scale.
- Page 2 tries to show the old scale, but it has been removed, so you get a 404 for the image, and no image is visible on the page.
- Edit Page 2 or restart Plone and all is well again.

Scenario 3:

- Create an image.
- Create a Page that shows the mini scale for this image.
- Modify the image.
- The page still shows the old scale.
- Edit the page. This shows the new scale. Now cancel without saving.
- The page tries to show the old scale, but it has been removed, so you get a 404 for the image, and no image is visible on the page.
- Edit and save the page or restart Plone and all is well again.

I was working on plone.scale when I saw this. Prime suspect was https://github.com/plone/plone.scale/blob/1.4.1/plone/scale/storage.py#L158 but this line is innocent: commenting it out changes nothing in these two scenarios.

So it's happening in plone.namedfile (for dexterity) or plone.app.imaging (for Archetypes) or perhaps in `ATContentTypes/lib/imagetransform.py` (if you use the image transform tab for the standard AT image).

Possibly plone.outputfilters caches the generated html.

Note that plone.scale actually tries to keep old scales around [for a while longer](https://github.com/plone/plone.scale/blob/1.4.1/plone/scale/storage.py#L185). plone.namedfile and plone.app.imaging could do something similar perhaps.

Note that when you keep outdated scales around, there is a danger that they mask newer scales in https://github.com/plone/plone.scale/blob/1.4.1/plone/scale/storage.py#L148

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
