### ISSUE TITLE
Russian web-sites are outdated or domains are down

### ISSUE THREAD

**Issue by vasily-v-ryabov** [plone/Products.CMFPlone#1481]
Page [Plone in Russian](https://plone.org/countries/ru) contains broken links to Russian sites (1). The domains ploner.ru and plone.org.ru look not paid and someone has registered them for sale. So the links should be updated or removed.

**Comment by serge73** [comment]
Russian community actually died.
These links should be removed.
Live subscription only plone-ru@googlegroups.com but there is silence.

**Comment by jensens** [comment]
the russian page does not exist any more under the given url
