### ISSUE TITLE
PLIP(WIP): new modal implementation

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#1487]
## Abstract

Implement a new modal pattern named `plone-modal2` and deprecate the use of `plone-modal`. The new modal will provide new, sane configuration options and _not_ attempt to shoe-horn regular pages into modal forms. Pages that are meant to be rendered in a modal should provide a way to just render modal content instead of the modal attempting to fake out validation, rendering and redirection.

This PLIP depends on https://github.com/plone/Products.CMFPlone/issues/1485 being approved.
## Motivation

Managing the complexity of the current modal implementation is very difficult and the configuration options are very confusing. The rendering model is difficult to integrate with and it's trying to do too much.
## Proposal & Implementation
- implement new modal pattern with react
- be able to sub-class the react component or use the pattern to configure and render the modal
- less configuration options, if you need something more complex, sub-class and override instead of trying to do everything with configuration
- class names prefixed
- follow general modal implementation like bootstrap modal implementation(what current one does as well)
## Deliverables
- new modal pattern
- example migration of existing modals to new
- migrate use of modals in tinymce, resource registry and other patterns to new modal
- documentation in mockup
- deprecation warning for `plone-modal`
## Risks
- yet another modal implementation
- pissed off, annoyed users

**Comment by thet** [comment]
Not sure, if I would like the move to React. I don't have much experience with it, code I've seen isn't easy to understand and I have heard/read controversial things about it.
Have you heard about vue.js? Looks like it's an lightweight but still flexible and more performant alternative to what is hyped otherwhere at the moment.
Here is an interesting read about comparison with other frameworks, e.g. React: http://vuejs.org/guide/comparison.html#React

**Comment by thet** [comment]
Can't the change be done transparently, so that we don't need to add a new pattern name?
Or does your proposal include real changes to the rendered templates and doesn't work with the simple ``ajax_load=1`` request parameter? Which changes are these then?

I'm in a need of some modal options, which are currently unavailable, like ``fullscreen=true``. I was thinking about adding pattern variants under a different name, like ``pat-modal-fullscreen`` instead of having to configure it like so: ``class="pat-modal" data-pat-modal='{"fullscreen": true}'``.
What do you think of the pattern variants idea? Maybe it can be done within the scope of this PLIP.

I'm not sure about adding React, see my comment on #1485 . Also, why do you need React for the modal pattern? Is it related to jquery-form and follow-up links within the pattern?

**Comment by vangheem** [comment]
Look at the current pattern implementation. That's what you get if you don't use something like React to manage state and complexity.

I'm not sure it can be done transparently. Review current modal pattern and see all the crazy options available. It's pretty insane and that pattern is extremely difficult to know how to extend/customize.

**Comment by vangheem** [comment]
In my own projects, I already have my own react-based modal and don't bother with the horrible `plone-modal` pattern.

**Comment by thet** [comment]
I suspect that no one is customizing the modal or using much of its options. 

On March 24, 2016 4:08:43 PM GMT+01:00, Nathan Van Gheem <notifications@github.com> wrote:
>In my own projects, I already have my own react-based modal and don't
>bother with the horrible `plone-modal` pattern.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/plone/Products.CMFPlone/issues/1487#issuecomment-200878420

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hvelarde** [comment]
@vangheem isn't it better to fix the "horrible" pattern (you look like me know) instead of adding a new one?

**Comment by vangheem** [comment]
Fixing it would be removing a ton of options and things it tries to do. This would be more risky as people who do not upgrade to the new way of using it, would have a broken modal.

I'm okay with that but then it'd be a breaking change. There isn't so much of fixing it as of completely redoing it and rethinking how we do modals.

**Comment by vangheem** [comment]
We're trying to make old style pages and forms work with modals and it's very difficult to get right, error-prone and complex.

**Comment by hvelarde** [comment]
I would agree with @thet even without making a poll: probably no one is using those options.

**Comment by thet** [comment]
I'm +1 on the PLIP, but -1 on having two modal implementations - I'd prefer a backwards incompatible change if there is a forward migration path AND the new one can be used as a drop in replacement for the old one when no special options were used.

I would like to see your current React based modal implementation to better understand this PLIP.
Also, a list of requirements would be awesome.

Thinking naively, a modal only needs to display something in an overlay. But then ajax loading is needed. Together with that form handling. And handling links within the modal. That's all covered with the current implementation. Anything else?

**Comment by thet** [comment]
By the way, I'd like to second this (If we start disagreeing during this discussion).

I want to add modal requirements to the PLIP proposal, but start a list here. Please add/modify items:

- Simple and flexible implementation.
- Needs to support AJAX content as well as static content.
- Needs to support AJAX forms.
- Needs a way to handle links within the modal - wether redirecting to new site or opening within the modal.
- Needs to support good UX patterns:
  - Following Bootstrap modal UX patterns.
  - (Optional/default) darken background on opening.
  - Close on click outside if no data has changed. If data has changed within a modal form, ask for confirmation.
  - Support full screen modals (like this: http://tympanus.net/Development/FullscreenOverlayStyles/index3.html or this: http://tympanus.net/Development/FullscreenOverlayStyles/index7.html )

**Comment by vangheem** [comment]
@thet thanks, let's talk more about this and work on it. I've made this PLIP a WIP

**Comment by thet** [comment]
@vangheem I'm about to create some pull requests to improve the current modal pattern (being able to add ``ajax_load`` parameter, making sure, a new modal uses the highest z-index + 1, ...).
I'm not sure if it's worth the effort, if this pattern is going to re-implemented.
Is there any chance to see your new implementation and to build upon that?

**Comment by thet** [comment]
I have an alternative modal implementation, based on mockup's old modal but largely simplified.
It isn't based on react, though.

I use it in a current project as a drop in replacement for plone-modal, even for the TinyMCE insert image/link overlays.

For the visual part, it supports full-screen modals only (which I favor anyways for UX reasons). The visual part is based on:
Demo: http://tympanus.net/Development/FullscreenOverlayStyles/
Article: http://tympanus.net/codrops/2014/02/06/fullscreen-overlay-effects/

Here it is: https://github.com/thet/pat-fancyoverlay

**Comment by ale-rt** [comment]
I am closing this because it is very old, stalled since quite some time and is probably obsolete.

Feel free to reopen/comment.

CC @plone/framework-team
