### ISSUE TITLE
PLIP: New image widget

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#1488]
## Abstract

I propose an advanced image widget that allows users to crop and resize the image before they upload.

## Motivation

Give user ability to crop, resize before they upload to the server. Also, give user inline preview of image they are uploading.

## Proposal & Implementation

 - new z3c.form widget in plone.app.z3cform
 - new image widget pattern using http://dev.vizuina.com/cropper/

## Deliverables

- documentation on the new pattern
- implementation of new widget
- (I already have most of the code done in another project)

## Risks

- only works with modern browsers

**Comment by hvelarde** [comment]
sounds interesting +1

**Comment by pigeonflight** [comment]
+200

**Comment by jensens** [comment]
I'am not sure if i want to be able to resize/crop at upload in general. I'm -1 to have this by default. Fine as addon.

IMO much important would be an async upload, which survives form validation errors.

Btw.: I'm just at an overhaul of p.a.imagecropping: https://github.com/collective/plone.app.imagecropping/pull/74

This shows also a bit the complexity of the whole cropping story which I fear can not be handled good before upload in a general and generic way.

**Comment by thet** [comment]
sorry for the close/reopen

**Comment by gforcada** [comment]
If it's a *new image widget* then one could still select either this one or the current plain old one? In general I'm in favor of having this one in core, but at the same time it could be a good idea to also keep the plain upload, as one could want to upload icons or other kind of imagery that do not need resize/cropping and/or have been already been done by professionals beforehand.

**Comment by jensens** [comment]
yes, it can be in core, i.e. provided as an alternative behavior one can swap with the default one. But please do not use it as default.

**Comment by thet** [comment]
@vangheem this PLIP was rejected. Amon the reasons were: Cropping on upload is the wrong place (better on uploaded images) and this should better live as an add on.
If you feel this needs a re-evaluation, please provide more context and use cases and discuss it with us!

**Comment by ebrehault** [comment]
The PLIP has been rejected. See https://community.plone.org/t/framework-team-meeting-minutes-2016-04-12/1943

**Comment by datakurre** [comment]
@jensens As a solution for "async upload, which survives validation errors", plone.app.drafts (bundled with Mosaic) could be fixed to work. It saves a draft on every ajax-validation, but currently only when validation passes. But it could be fixed to always save uploads.

**Comment by espenmn** [comment]
Slightly related (or at least interesting if too big images are a problem): 
https://pypi.python.org/pypi/collective.autoscaling/1.0
