### ISSUE TITLE
Can't select Image on TinyMCE Image browser

### ISSUE THREAD

**Issue by terapyon** [plone/Products.CMFPlone#1493]
Related to #1398

I found to mistook my PR code. It is for translating on folder_contents. But the function using another place.
TinyMCE is also using `@@getVocabulary` . The returned `portal_type="Image"`,  but I got `portal_type="画像"` by Japanese.

I'll soon make a new PR. Please let me know status of another language.

**Comment by davilima6** [comment]
Duplicate of plone/plone.app.content#77
