### ISSUE TITLE
Search on *partial* email address in "Members" standard search page always gives "invalid" error message.

### ISSUE THREAD

**Issue by ronchi** [plone/Products.CMFPlone#1499]
In a stock Plone setup, there is a Members tab that has a search page "Search for users".  The second option is to search email addresses under the heading "E-mail Find useres whose email addresses contain." (which suggests that a partial email address (e.g., gmail.com) would be a valid search term).  Unfortunately, when you search for a partial email address, you get an "invalid email address" error.  The only "valid" search term is a complete email address.

I'm sure the easy fix would be to rephrase the search term (e.g., "Find user whose email address is." ) However, it would be really handy to search for members having an email address with a particular domain so, for example, you could find all the users from a particular company via their domain name.  

As an aside, the term "Name" should be for Full Name, and "Username" should be for the "Name".  Most people who aren't developers would associate "Name" with a person's real name, not their username.

Incidentally, I'm using Plone 5.0.2 on Linux.

**Comment by khanstark** [comment]
its been resolved in above PR.
