### ISSUE TITLE
Page alignment issues post migration to 5.0.3-pending

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1501]
I moved my site from 5.0.2 to 5.0.3-pending. the alignment of the pages seems to have moved to extreme left. please suggest any solutions. It was a server migration before the upgrade.

www.kousalam.com

![blob](https://cloud.githubusercontent.com/assets/10380993/14187222/9cca7964-f79f-11e5-9194-d747dcfe30f4.png)
![blob 1](https://cloud.githubusercontent.com/assets/10380993/14187261/c3f5717e-f79f-11e5-83bb-f6ef31631944.png)

**Comment by jensens** [comment]
probably a special case and not a common problem
