### ISSUE TITLE
resourceregistry: "develop" mode loads less files, even if "Develop CSS" isn't active

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1505]
Putting the resource registry in "develop" mode loads all LESS files.
This should only be done, if "Develop CSS" is active.
Otherwise it takes unnecessary much time if you only want to get the newest compiled versions or develop JavaScript only.

**Comment by jensens** [comment]
Actually it loads all less of barcelonetta. Inside resourceregistry it works as expected and only loads less from bundles in development mode. So it seems barcelonetta/plone.app.theming/...(?) reads the debug value too and interprets it more broadly.

**Comment by VerSooSet** [comment]
Hi! I'm reproduce at in barcelonetta Resource Register:
- 'Development mode' checked at the checkbox.
- 'resourceregistry' -label.
- 'Develop.css' -button and 'Build' for BundleBuilder.
- unputting -button and 'Build' for BundleBuilder. 
Seens no difference and LESS files are not loaded. [result to me at screens](https://drive.google.com/drive/folders/0B2052kKMN8_Wa29hMVpncFRldnc?usp=sharing)

Could you describe to me in more details? I would like a issue to fix.

**Comment by VerSooSet** [comment]
Made a firstview about app.theming works with LESS. There is a sketch -
IResourceRegistry --- ? ----Layer/Adapter ?---- themapper.js (getting *.less files) ----themapper.less

barcelonetta are used as default on Site Setup so I should to see how works debug mode at barcelonetta documentation, not addon as essence. I will do it.

**Comment by thet** [comment]
Still an issue? I'm not sure, closing....
