### ISSUE TITLE
Resources from third party add-ons are not being included in compiled plone-legacy bundle

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1511]
Seems JS resources registered in Plone 5 using old approach (`jsregistry.xml`) are not included in the final compilation: I installed an add-on and, even as I can see the JS resources listed in `default.js`, the source code is not present.

If I enable development mode, then I can see the source code included in `plone-legacy-compiled.js` and it's executed normally.

**Comment by hvelarde** [comment]
@ebrehault this is just applied to Plone 5.1 branch; as Plone 5.0.4 has no final release yet, maybe we can add the fix to the other branch also; @esteele comments?

**Comment by esteele** [comment]
@hvelarde As I said yesterday, 5.0.4 has been finalized, so this will have to wait for 5.0.5. I can cut that ASAP, once it's merged and tests have passed.

**Comment by hvelarde** [comment]
ah, ok… thanks, @esteele !

@ebrehault I will try to port the fix to the 5.0.x branch then.
