### ISSUE TITLE
Wrong portal_url used for TinyMCE in multilingual site

### ISSUE THREAD

**Issue by kcleong** [plone/Products.CMFPlone#1513]
When adding an image in the TinyMCE editor in a multilingual site the wrong navigation root is used. If a file is uploaded in the visual editor, and the content item is located at `/nl/agenda/lokroep-zonder-handen/edit` the `@@fileUpload` view is called on `/agenda/lokroep-zonder-handen/@@fileUpload`. The correct path for the file upload view would be  `/nl/agenda/lokroep-zonder-handen/@@fileUpload`, witht the language code included.

See this screenshot in the browser for the 404:

<img width="1199" alt="screen shot 2016-04-07 at 10 00 35" src="https://cloud.githubusercontent.com/assets/201650/14344504/5568105a-fca8-11e5-9fae-ea74733dc046.png">

The portal_url attribute in [TinyMCESettingsGenerator.portal_url](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patterns/__init__.py#L29) is pointing to the Plone site instead of the language specific folder. 

I think the fix is easy, use `self.context` when calling `get_portal_url` instead of using `self.portal`. When I try this in a pdb I get this result:

```
(Pdb) get_portal_url(self.portal)
'http://localhost:8100/avk'
(Pdb) get_portal_url(self.context)
'http://localhost:8100/avk/nl'
```

I can provide the fix, but I cannot see any tests related to the `TinyMCESettingsGenerator`.

**Comment by kcleong** [comment]
This is happening in Plone 5.0.3 with plone.app.multilingual installed.

**Comment by thet** [comment]
This is related, please have a look at it: https://github.com/plone/plone.app.widgets/pull/138
Tests would be awesome of course too...

@jensens do you have some comments about that?

There is related code in https://github.com/plone/plone.app.widgets/blob/master/plone/app/widgets/utils.py and https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/widget.py - again spread over 3 packages :(

**Comment by jensens** [comment]
We have a similar problem in our lineage based project.

Unrelated, but I always wonder how many ``get_portal_url`` implementations Plone has... The whole implementation hurts my eyes.

Anyway: This ``get_portal_url`` is meant to be called with the real context as parameter, so your proposal is overall fine.

BUT: I started looking at it and this resulted in #1513
