### ISSUE TITLE
A collection of News items - issues with tabular view 

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1532]
Please check if this is a bug. Emerged out of no where. I have a couple of news items. In my home folder i create a collection News-1. The collection is given in Fig 1. In fig 2 i give the tabular view. Things were alright as long as there were 5 news items. On adding the 6th item it shows the view as in fig 2. There is bullet points and numbers before and after the table view of news items. Pls ignore if not a bug. Note that I had selected " no. of items to be selected in one batch = 5" in this case. When I change this to 10 the issue goes away as there are only 6 total news items currently. (Plone 5.0.3)

![image](https://cloud.githubusercontent.com/assets/10380993/14564342/c29369b2-0343-11e6-8938-01100efddd1a.png)

![image](https://cloud.githubusercontent.com/assets/10380993/14564412/17b8cb76-0344-11e6-8a01-98e2280df163.png)

**Comment by jensens** [comment]
I'd say this is a bug.

**Comment by ale-rt** [comment]
It looks fine to me now, please feel free to reopen if not :)
