### ISSUE TITLE
Toolbar: Add New-->Collection seems to be misaligned 

### ISSUE THREAD

**Issue by khanstark** [plone/Products.CMFPlone#1536]
![issue](https://cloud.githubusercontent.com/assets/17498833/14641540/611be29e-0664-11e6-9792-ff7b8d8c031c.png)

the image and text for collection seems to be merged.[Plone 3]

**Comment by hvelarde** [comment]
IIRC, this was already reported and fixed.

**Comment by khanstark** [comment]
its Plone 5.0.3.1

**Comment by zopyx** [comment]
The bug is still present in 5.0.4.

**Comment by davilima6** [comment]
Reported in #1446 and should have been fixed by #1491 but somehow the commit 671c3811ffe9059e70661b54b5cbc3044e43d254 seems to have been lost after merge.

**Comment by khanstark** [comment]
that fix is not good enough, i see in Plone 5.0.1 there is no issue with alignment of `Collection`....
and the code(which is changed in that fix) remains same as that in 5.0.3

**Comment by jensens** [comment]
Works in Plone 5.1
