### ISSUE TITLE
Visual issue in Plone toolbar

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1540]
With xmldirector.plonecore I see a visual artifact in the Plone toolbar. The string "Collection" is badly placed.

![screenshot-dev zopyx com 12020 2016-04-20 15-28-28](https://cloud.githubusercontent.com/assets/594239/14676192/b5388244-070c-11e6-93e7-362ab7a60018.png)

**Comment by hvelarde** [comment]
duplicated with #1536
