### ISSUE TITLE
Do we need to implement Subresource Integrity?

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1543]
In order to avoid JavaScript DDoS we must implement [Subresource Integrity](https://www.w3.org/TR/SRI/), if needed.

More information: https://blog.cloudflare.com/an-introduction-to-javascript-based-ddos/

We should document this recommendation also for developers.

HT @cleberjsantos

**Comment by cleberjsantos** [comment]
@hvelarde I think it we'll need to implement directly as attribute of the portal_(javascript|css).

**Comment by jensens** [comment]
This was implemented in Plone 6
