### ISSUE TITLE
Incomplete french url normalizer

### ISSUE THREAD

**Issue by yleclanche** [plone/Products.CMFPlone#1544]
Hello,

When you create a document in french, with a title like "béret français baguètte", it will generate an url with missing character : 
bret-franais-bagutte

I think the french normalizer (plone.i18n.normalizer.fr) is incomplete.
Currently, the mapping is : 

```
mapping = {
    339: 'oe'
}
```

I think it should be : 

```
mapping = {
    192: u'A',
    200: u'E', 201: u'E', 202: u'E',
    207: u'I',
    212: u'O',
    217: u'U',
    199: u'C',
    224: u'a', 225: u'a',
    232: u'e', 233: u'e', 234: u'e',
    239: u'i',
    244: u'o',
    249: u'u',
    231: u'c',
    339: 'oe'
}
```

This normalizer is used for other things. I have tested this only on urls for the moment.

**Comment by ale-rt** [comment]
Nowadays it is generated with id: `beret-francais-baguette`.
Tested on https://demo.plone.org/.
