### ISSUE TITLE
Viewlet not rendering after migration from Plone 3 to Plone 4 

### ISSUE THREAD

**Issue by Farha14** [plone/Products.CMFPlone#1545]
Hi Team,

We migrated our Plone site from Plone 3.3.5 to Plone 4. and we are facing issue while rendering only one viewlet rest all are working fine.

We are facing 'TypeError: **call**() takes at least 2 arguments (1 given)'issue while rendering the viewlet. Kindly rfer to the attached file for detailed log [viewlet_rendering_Error.txt](https://github.com/plone/Products.CMFPlone/files/230005/viewlet_rendering_Error.txt)

Please let us know if we can provide you more information around this.

Regards,
Farha

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
