### ISSUE TITLE
viewlets.footer - help needed

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1548]
In plone 5.0.3, i include a mailchimp portlet in plone.footer portlet. please note the plone.footer viewlet it has the site actions and colophone coming from no where. where is it coming from? I checked the zope.interface.interface-plone.footer  and it does not have any way i can stop this.

![image](https://cloud.githubusercontent.com/assets/10380993/14766287/f337cc78-0a20-11e6-9183-de3eb67fa620.png)

**Comment by frisi** [comment]
have you read the documentation on viewlets? 
http://docs.plone.org/develop/plone/views/viewlets.html

this will help you understand where the colophon and site-actions are coming from.

please post questions like this to https://community.plone.org/ or stackoverflow (tagged with plone) in the future. the issue tracker is only for bug reports and feature-requests
