### ISSUE TITLE
on Event edit page, the default button is incorrect

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1549]
If you are editing an Event and press Enter or Return key while in (say) the title field, you expect to save the event, ie. the default button should be Save, but it is the Add button for the recurrence. Plone 5.0

**Comment by ArhantJain** [comment]
Hii, @tkimnguyen @jensens @MrTango 
   I want to work on this issue, please guide me the way to proceed.

Also, I have made my own site using Plone 4.3, thus I have Experienced hands on it.

**Comment by ale-rt** [comment]
Tested on https://demo.plone.org/ is still an issue.
It is not an issue anymore in https://6-classic.demo.plone.org/

**Comment by jensens** [comment]
Fixed in Plone 6
