### ISSUE TITLE
the content_status_modify.cpy script does not handle Validator failures when editing the object before changing the workflow.

### ISSUE THREAD

**Issue by do3cc** [plone/Products.CMFPlone#1552]
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_form_scripts/content_status_modify.cpy#L46-L49

A page might have an invariant defined and then here would be the right place to catch it.
See also #1551 which is the issue that the methods there don't actually check for invariants

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
