### ISSUE TITLE
Status message on folder content options not cleared

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1559]
Do some action in the folder content view and a status message is shown:

![selection_066](https://cloud.githubusercontent.com/assets/341393/14906915/9af21968-0d97-11e6-8803-8e8f551ae485.png)

First, the style used makes hard to an untrained user to understand that is a status message.

Then, if you traverse over the site, the status message will travel with you all over the place:

![selection_067](https://cloud.githubusercontent.com/assets/341393/14906932/d23a7b86-0d97-11e6-8dd1-b640ed843430.png)

**Comment by davilima6** [comment]
Also happens when you filter something and then clears the filter but the status message remains: `Can not order items while querying`.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
