### ISSUE TITLE
Usage of Title column is inconsistent in folder contents

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1561]
The Title column seems always visible in the folder contents view (structure pattern). Still there is a checkbox "Title" in the columns selector:
![columns_fc](https://cloud.githubusercontent.com/assets/339384/14913811/e4f36dfa-0e05-11e6-9cc8-aed1435d702c.png)
It is disabled by default. If you enable the "Title" it is duplicated in the listing.

I think the best solution would be to check the "Title" column in the columns view and disable it. Like this:
![columns_fc_title_disabled](https://cloud.githubusercontent.com/assets/339384/14913867/623166c8-0e06-11e6-8816-c5b7877e953f.png)

**Comment by tomgross** [comment]
Seen on Plone 5.0.4

**Comment by davilima6** [comment]
For some reason I don't see `Title` in the `Columns` popover. However if we do leave it disabled by default it'd be best to put it as first item (just before `Last modified`).

**Comment by vincentfretin** [comment]
I don't see the Title checkbox in Plone 5.2.2rc1. So I'm closing it.
