### ISSUE TITLE
Plone 4 and 5: sitemap does not show all the links of the site

### ISSUE THREAD

**Issue by ivanteoh** [plone/Products.CMFPlone#1564]
# Problem
Recently one of our 4.x plone sites was audited for WCAG 2.0 AA. The report came back and mentioned that sitemap need to show all the links of the site due to https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/G126.html. Currently sitemap only show links up to level 3 in Plone 4 and 5.

<img width="1424" alt="sitemap_plone4" src="https://cloud.githubusercontent.com/assets/900434/14945832/308b7160-105c-11e6-8ba1-bd864ff3cfbb.png">

<img width="1413" alt="sitemap_plone5" src="https://cloud.githubusercontent.com/assets/900434/14945833/3b6ce8fc-105c-11e6-88ca-0d8ecbfeddac.png">

# Options

[ ] Provide option in sitemap for show all the links of the site.

**Comment by davisagli** [comment]
In Plone 4 you can configure this using the `sitemapDepth` property in `portal_properties/navtree_properties`, and in Plone 5 you can configure it using the `plone.sitemap_depth` key in the `portal_registry`. Set it to `-1` for no depth limit.

**Comment by davisagli** [comment]
Also, it seems like a misinterpretation of the guideline you linked to say that it requires linking to every page in the site. The description of the guideline explicitly says "This technique is only effective for small sets of Web pages; if the list of links is longer than the rest of the content in the Web page, it may make the Web page more difficult for users to understand and use." Also G63 (https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/G63.html), which is more specifically about a site map, appears to only require that each page be reachable via links starting from the sitemap, not that the sitemap link to each page directly.

**Comment by ivanteoh** [comment]
We feedback same comment back to auditor and waiting for a reply. If she still insist us to fix it, at least we got the solution. Thanks @davisagli

**Comment by davilima6** [comment]
Sitemap depth can be configured TTW from Plone 5 on, have a look at @@navigation-controlpanel
