### ISSUE TITLE
Problem with relative date criteria in Plone 5.0.4

### ISSUE THREAD

**Issue by cekk** [plone/Products.CMFPlone#1571]
Hi,
i've opened an issue on [plone.app.querystring](https://github.com/plone/plone.app.querystring/issues/61) for a problem with relative date criterias in collections.
I have these problems with "today" or "within last" criteria (for start event date) for example.

I opened also an issue here because i don't know what's the best place for this bug.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
