### ISSUE TITLE
ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, '') after upgrading from Plone 4 to Plone 5

### ISSUE THREAD

**Issue by Farha14** [plone/Products.CMFPlone#1573]
Hi Team,

We are in process of Upgrading our Plone 4 to Plone 5. We are done with all the code modifications and successfully ran the build out. We initially got the message 'Info: Zope Ready to handle request'.
After that when we hit the URL in browser we are getting 'ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, '') '. Kindkly refer to the attached logs.
[Plone_ upgrade_Error_logs.txt](https://github.com/plone/Products.CMFPlone/files/250183/Plone_.upgrade_Error_logs.txt)

Also when we try to hit the ZMI, we are getting Attribute Error(Portal registry) :

AttributeError('portal_registry',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: (<InterfaceClass plone.registry.interfaces.IRegistry>, ''))

Our actual motive is to upgrade the Plone  4 to Plone 5. 

Please let us know if we can provide you more information.

Thanks & 

Regards,
Farha

**Comment by hvelarde** [comment]
what Plone 4 version exactly?

**Comment by Farha14** [comment]
Its Plone 4.0

**Comment by hvelarde** [comment]
Plone 4.0 does not include plone.app.registry by default; you will probably have to install it manually at some point.

**Comment by sanjaykapoorsaini** [comment]
plone.app.registry is already installed as plone.app.registry-1.3.5-py2.7.egg in buildout-cache.
we added plone.app.registry in eggs+=  as well as in zcml += in buildout.cfg and rerun the bin/buildout command but there is no impact on result, we are facing same issue.

**Comment by hvelarde** [comment]
I mean installed in Plone, no present in the buildout.

**Comment by petri** [comment]
For what it's worth, I get the same exception when trying to rename a Plone 4.3 site I just upgraded to 4.3.15. In my case, the rename triggers indexing in Plone, which in turn calls some third-party code that attempts to get the registry. Really weird that the component lookup fails this way.

**Comment by pbauer** [comment]
Another possible reason is that you uninstalled a addon that had the registry as a dependency.
Addons that have the registry as a dependency in metadata.xml (`<dependency>profile-plone.app.registry:default</dependency>`) will unregister the registry during uninstalling. An example is collective.imagetags.

You can safely remove it by omiting `utilities` from the the uninstall-cascade like this:

```python
cascade = ['types', 'skins', 'actions', 'portalobjects', 'workflows', 'slots', 'registrypredicates', 'adapters']
quickinstaller.uninstallProducts(['collective.imagetags'], cascade=cascade)
```

**Comment by petri** [comment]
@pbauer huh? Thanks for pointing that out. Defaulting to cascading uninstalls seems to me a recipe for disaster, though...

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
