### ISSUE TITLE
Search portlet not responsive

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1578]
Plone 5.0.4; add a Search portlet to the left column and use a smaller screen resolution:

![screen shot 2016-05-05 at 14 32 58](https://cloud.githubusercontent.com/assets/341393/15051353/83845318-12ce-11e6-9d26-81af5ea5cab0.png)

**Comment by vincentfretin** [comment]
This seems fine with Plone 5.2.2. I'm closing.
![Capture d’écran de 2020-07-01 11-41-37](https://user-images.githubusercontent.com/112249/86229405-f6968b00-bb8f-11ea-8022-c551dcae2c05.png)
