### ISSUE TITLE
Edit view is not responsive

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1579]
Plone 5.0.4; the Edit view is not responsive and some fields are inaccessible for Editors using small screen devices:

![screen shot 2016-05-05 at 14 41 57](https://cloud.githubusercontent.com/assets/341393/15051603/de09c9de-12cf-11e6-8803-cc762ecf6164.png)

**Comment by datakurre** [comment]
Related to "Allow multiline tabs" https://github.com/plone/Products.CMFPlone/issues/1674

**Comment by vincentfretin** [comment]
Still an issue one Plone 5.2.2.

**Comment by jensens** [comment]
fixed (swipe works) in 5.2.10 and 6.0 Classic UI.
