### ISSUE TITLE
Tab "Default" not translatable

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1580]
It is missing in ``plone.po`` files. 

it is defined in class ``plone.dexterity.browser.base.DexterityExtensibleForm``,

/cc @chrimba

**Comment by jensens** [comment]
found it in plone.z3cform, fix soon.

**Comment by chrimba** [comment]
nennen es Standardeinstellung oder Standardeingabe
Am 06.05.2016 19:37 schrieb "Jens W. Klein" <notifications@github.com>:

**Comment by jensens** [comment]
@chrimba I though just short "Standard" is fine?

**Comment by chrimba** [comment]
das kann aber alles und auch nichts heißen
Am 06.05.2016 19:39 schrieb "Jens W. Klein" <notifications@github.com>:

**Comment by jensens** [comment]
@chrimba, *Standardeingabe* sagt aber auch nicht mehr, dann eher *Hauptformular* oder sowas.

Sind andere Deutschsprachige hier, die hierzu eine Meinung haben und mitlesen?

**Comment by loechel** [comment]
Bezüglich der Form, klingt Hauptformula passender, Standard, klingt mehr nach Vorgaben.

**Comment by jensens** [comment]
Ich lasse jetzt mal "Standard" und schaue wie das bei der Schulung nächste Woche ankommt.

**Comment by hvelarde** [comment]
Sylvia wagt quick den Jux bei Pforzheim.
