### ISSUE TITLE
versioning blob-content

### ISSUE THREAD

**Issue by iham** [plone/Products.CMFPlone#1585]
Setting Dexterity File and Image to be versioned causes errors on creation.

even thou versioning blob-content is not that common, this should work when selected to be versioned.

after fixing some problems in plone/Products.CMFEditions#36 CMFPlone fails to allow creation of blob content, because locking support is missing. locking support is heavily tied to the versioning behaviour and must be applied too if its not there, when enabling versioning on a dexterity type.

**Comment by iham** [comment]
this also relates to:
https://github.com/plone/Products.CMFPlone/issues/1437
https://github.com/plone/Products.CMFPlone/issues/964

**Comment by mauritsvanrees** [comment]
It looks like all your fixes got merged a few years ago. :-)
Works fine in Plone 5.2 (I tried Python 2.7 only). At least: reverting brings back an earlier version of the blob, also when I have packaged the database in between.
