### ISSUE TITLE
Toolbar items with submenu not displaying correctly.

### ISSUE THREAD

**Issue by didrix** [plone/Products.CMFPlone#1588]
The toolbar breaks after building the the 'plone' css/js bundle in coredev.

affected: coredev 5.1 branch

![schermafbeelding 2016-05-17 om 13 43 53](https://cloud.githubusercontent.com/assets/3892707/15321391/70470522-1c36-11e6-9ae6-3a8be77eac32.png)

**Comment by jensens** [comment]
just build it locally and now it works an buildout.coredev(5.1)/Products.CMFPlone(master)
