### ISSUE TITLE
Don't display "external link" icon on hero section

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#1592]
From current coredev: 

![screen shot 2016-05-19 at 7 38 09 pm](https://cloud.githubusercontent.com/assets/483999/15403463/56fd31a8-1df9-11e6-8c58-72f7c29dad16.png)

**Comment by jensens** [comment]
IIRC its the same in footer links to Plone,

**Comment by jensens** [comment]
outdated, AFAIK this was fixed in 5.2 and is no longer valid for Plone 6
