### ISSUE TITLE
PLIP: Easily change default search order

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1600]
## Abstract
Provide an option to easily change the default search order of @@search view

## Motivation
In some of our biggest Plone sites we need to make this customization in the portal, and from time to time our customers request the same change.

Of course we can elect other interesting options to add into this PLIP to improve the @@search view.

## Assumptions
This change should be done into both Plone 4.3.x and 5.x

## Proposal & Implementation
We should add a new option into @@search-controlpanel to select the default search order, and it affect the @@search view.

## Deliverables
A combo-box into @@search-controlpanel to select the default search order of the Plone site.

## Risks
The actual order should be the default value of this option.

## Participants
Rodrigo Ferreira de Souza @rodfersou

**Comment by hvelarde** [comment]
CC @plone/framework-team

**Comment by jensens** [comment]
Just yesterday I run into this problem. Shared Minds! 

Some thoughts:

- If you order by date, which date to take? I added an own index "general_date" to solve this problem. Its a DateRecurringIndex similar to start with an indexer first looking for a start date, if not found fallback to a effective date and if that wasnt found it takes the creation date, which should be available for all content. @thet suggested to use start itself for this fallbacks, but said it would need some research for side effects. Usually Events are detected either by portal_type or interface. But this is out of scope for this PLIP.

- Order by relevance in a default Plone just ... sucks. We need something better here. I also know, thats not a trival problem. Out of PLIP-scope too.

**Comment by rodfersou** [comment]
In our case we add the ``sort_on == Date`` and ``sort_order == reverse``, I think this way there is no need to look for fallbacks.. but I could not understand [how this index handle this](https://github.com/zopefoundation/Products.ZCatalog/blob/master/src/Products/PluginIndexes/DateIndex/DateIndex.py#L123) to know what date to take.

**Comment by hvelarde** [comment]
@jensens we have been implementing this using this approach: http://stackoverflow.com/q/15823413/644075

you can see it working here for instance: http://www.oabsp.org.br/@@search?SearchableText=impeachment

**Comment by jensens** [comment]
FYI: we - the frameworkteam - looked at the plip and it now goes in the voting process. Overall opinion is very positive. 
Regarding adding features to Plone 4 - this need to be decided by the release team if we want to do this. This one would have low-impact w/o any BBB problems to be expected, so I would be fine with it.

**Comment by rodfersou** [comment]
Pull requests for Plone 4.3.x:

* https://github.com/plone/plone.app.vocabularies/pull/32/files
* https://github.com/plone/plone.app.search/pull/17/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/plone.app.controlpanel/pull/63/files
* https://github.com/plone/Products.CMFPlone/pull/1616/files

Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/290/console

**Comment by hvelarde** [comment]
Plone 5 implementation will follow maybe on Friday.

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/291/console

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/292/console

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/293/console

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/294/console

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/295/console

**Comment by rodfersou** [comment]
Finally green!

**Comment by jensens** [comment]
@rodfersou great! FYI: Next FWT meeting is at 2016-06-14 if you provide all the implementation before I can do a review before FWT meeting. If we get enough votes we can merge it afterwards. 

We need also decision by the @plone/release-team if we want this in 4.3: On one hand its a feature, on the other it has no impact nor does it need upgrades, right? @rodfersou please talk to the release team if they accept features like this for 4.3.

On the other hand if we introduce it in 4.3 you need to add an upgrade step (conditional) in 5.1 checking if the property is there and moving it to the registry. That is not a problem, but additional work to do.

**Comment by mauritsvanrees** [comment]
The changes seem small and restricted enough for me.

**Comment by esteele** [comment]
I'm ok with this going into 4.3.

**Comment by jensens** [comment]
@rodfersu @hvelarde any update here? FWT has not enough votes, but already 2 positive votes.

**Comment by hvelarde** [comment]
sorry, we're busy this week; please wait until Friday to see if we have some spare time.

**Comment by rodfersou** [comment]
I did the suggested code reviews in the branches, and fixed one bug to [select the default option](https://github.com/plone/plone.app.search/blob/0d96434fe70393de2af25e01dff0dddd9f9c2177/plone/app/search/browser.py#L144-L147) if no option is selected.

New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/309/console

**Comment by rodfersou** [comment]
Green!

**Comment by rodfersou** [comment]
Review translations on ``plone.app.vocabulary`` package.

New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/311/console

**Comment by rodfersou** [comment]
Green!

**Comment by ebrehault** [comment]
@rodfersou the PLIP has been approved by the Framework Team.

**Comment by rodfersou** [comment]
@plone/framework-team New Pull requests for Plone 4.3.x:

* https://github.com/plone/plone.app.search/pull/17/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/plone.app.controlpanel/pull/63/files
* https://github.com/plone/Products.CMFPlone/pull/1616/files

Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/351/console

Already Green

**Comment by rodfersou** [comment]
New Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/352/console

**Comment by rodfersou** [comment]
New Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/353/console

**Comment by ebrehault** [comment]
Review by Eric Bréhault (ebrehault@gmail.com, barbichu@irc.freenode.net)

The PLIP was reviewed on Ubuntu 16.04 using python 2.7.6 and Chromium 51.0.2704.79.

August 30, 2016

# Review steps

- Set up the buildout using the PLIP's config (plone/buildout.coredev branch 4.3):
```
  $ ./bin/buildout -c plips/plip-1600.cfg
```
Note: I have created this buildout to ease the testing, I guess it is ok, but feel free to update it if anything is wrong.

- Ran tests for the PLIP's auto-checkout packages::
```
  $ bin/test -s plone.app.search
  $ bin/test -s plone.app.controlpanel
  $ bin/test -s Products.CMFPlone
```

- Reviewed code

- Manual testing TTW

# Notes and observations

## Automated testing

Tests are green, but there is no test about the feature itself (we only test the control panel).

## Manual testing

The feature is working fine in the search page, but the livesearch ignores the search order setting, I think it might be confusing for the users.

# Code review

The implementation is good. 

# Conclusion

It seems quite good, as soon as livesearch is fixed and we have one test demonstrating the feature, I guess we can merge it in 4.3.

Any progress on the Plone 5 implementation?

**Comment by jensens** [comment]
I'd like to see this simultaneously merge this in 4.3 + 5.1. Otherwise we may end up with a feature in 4.3 that is not in latest 5.

**Comment by rodfersou** [comment]
@plone/framework-team

New Pull requests for **Plone 4.3.x**:

* https://github.com/plone/plone.app.search/pull/18/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/plone.app.controlpanel/pull/63/files
* https://github.com/plone/Products.CMFPlone/pull/1616/files

Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/426/console

New Pull requests for **Plone 5.1.x**:

* https://github.com/plone/mockup/pull/713/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/Products.CMFPlone/pull/1783/files

Jenkins job: http://jenkins.plone.org/job/pull-request-5.1/657/console

**Comment by rodfersou** [comment]
There is an error in robotframework test for Plone 5.1.x that AFAIK is not related with this pull request.  Can someone help me with that?

**Comment by jensens** [comment]
@rodfersou is it sticky or random (try re-run)?

**Comment by rodfersou** [comment]
@jensens this is the second time I run the Jenkins job, and the error is there

**Comment by rodfersou** [comment]
maybe I misunderstand the log and that was a broken test allowed to fail.. let's wait Jenkins finish the job.

**Comment by rodfersou** [comment]
and now we have 2 robotframework erros instead of one.. http://jenkins.plone.org/job/pull-request-5.1/663/

**Comment by rodfersou** [comment]
but at the branches the message is that the tests passed https://github.com/plone/Products.CMFPlone/pull/1783

I don't know if it is good or bad :)

**Comment by mauritsvanrees** [comment]
In the Robot Test Summary on http://jenkins.plone.org/job/pull-request-5.1/663/ you can see that out of 113 **critical** tests there were zero failures. That is the important number.
Out of all 119 robot tests there were 2 failures, but they are not critical.
We should still fix those, but it has nothing to do with this pull request and should not hold it up.
See https://github.com/plone/Products.CMFPlone/issues/1656

**Comment by rodfersou** [comment]
@mauritsvanrees thank you

**Comment by rodfersou** [comment]
@jensens I think it is ready

**Comment by hvelarde** [comment]
the 4.3 version looks good to me; not sure about the 5.1 version.

**Comment by rodfersou** [comment]
@plone/framework-team

Pull requests for **Plone 4.3.x**:

* https://github.com/plone/plone.app.search/pull/18/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/plone.app.controlpanel/pull/63/files
* https://github.com/plone/Products.CMFPlone/pull/1616/files

Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/430/console

Pull requests for **Plone 5.1.x**:

* https://github.com/plone/mockup/pull/713/files
* https://github.com/plone/plone.app.upgrade/pull/77/files
* https://github.com/plone/Products.CMFPlone/pull/1783/files

Jenkins job: http://jenkins.plone.org/job/pull-request-5.1/676/console

Both buildouts has a **plips/plip-1600.cfg** file to do manual test in the right branches.

**Comment by rodfersou** [comment]
@jensens I did a rebase of all branches and run again Jenkins.

**Comment by jensens** [comment]
I talked with @agitator and he will review this PLIP at least for 5.1, as the feature would come in handy for one of his projects.

**Comment by rodfersou** [comment]
@jensens green \o/

**Comment by agitator** [comment]
My review https://github.com/plone/buildout.coredev/blob/5.1/plips/reviews/plip1600-review-agitator.rst

Conclusion
-----------

- I think the upgrade step should work on existing sites (running coredev) too
- All other things work as expected

**Comment by rodfersou** [comment]
@agitator the control panel entry is into other upgrade step https://github.com/plone/plone.app.upgrade/blob/27d85d45d2732093912f03b1cc839ce7fe99f3f5/plone/app/upgrade/v51/configure.zcml#L45-L52

https://github.com/plone/plone.app.upgrade/pull/77/files#diff-57782ddfce30e5baec92736149c84c68R17

**Comment by agitator** [comment]
after selecting both steps, all things work as expected

**Comment by rodfersou** [comment]
@agitator thank you

**Comment by jensens** [comment]
Note from FWT meeting. Read for for merge in Plone 5, needs short review for Plone 4 (lie search?)

**Comment by ebrehault** [comment]
I have reviewed the Plone 4 implementation, it is fine now.
Ready to merge.

**Comment by rodfersou** [comment]
any plans to merge a commit?

**Comment by jensens** [comment]
This week impossible for me if I look at my workload. Next week is better.

**Comment by agitator** [comment]
PLIP is merged
