### ISSUE TITLE
INonInstallable interface duplication

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1621]
The INonInstallable interface, which is used for hidding products in quickinstaller is originally defined in CMFQuickInstallerTool:
https://github.com/plone/Products.CMFQuickInstallerTool/blob/master/Products/CMFQuickInstallerTool/interfaces/installable.py
It contains a method _**getNonInstallableProducts**_ which is used here:
https://github.com/plone/Products.CMFQuickInstallerTool/blob/master/Products/CMFQuickInstallerTool/QuickInstallerTool.py#L185

In CMFPlone there is also defined a interface _INonInstallable_ here:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/installable.py
It has a method _**getNonInstallableProfiles**_ which is used in the controlpanel  and some addons.

This can be confusing. I propose to merge this interfaces into one.

**Comment by hvelarde** [comment]
those marker interfaces are different and their use scope is also different: one defines that a **product** is non-installable, so it will not be shown in QuickInstaller configlet; the other defines that a **profile** is non-installable, so it will not be shown in QuickInstaller configlet neither.

**Comment by mauritsvanrees** [comment]
I am actually working on this in plip #1340. The plan there is to gradually get rid of the QI, which also means getting rid of its INonInstallable interface. The two interfaces will be merged into one, with two methods, one for profiles and one for products.

This file explains it:
https://github.com/plone/Products.CMFPlone/blob/get-rid-of-qi/Products/CMFPlone/GET_RID_OF_QI.rst#inoninstallable

For the moment (certainly Plone 5.1) we will still check the QI INonInstallable interface as well for backwards compatibility:
https://github.com/plone/Products.CMFPlone/blob/get-rid-of-qi/Products/CMFPlone/controlpanel/browser/quickinstaller.py#L205

Note that the plip is not ready yet, but it is getting closer. It needs some more smoothing, and either less or more backwards compatibility code.
