### ISSUE TITLE
New theme upload does not show in Theming Panel (also no manifest.cfg created)

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1622]
Plone 5.0.4

at Site Setup > Theming > "Upload Zip File"
while following directions to [Upload An Existing Theme](http://docs.plone.org/external/plone.app.theming/docs/index.html#uploading-an-existing-theme)

Pop up to browse for .zip (correctly compressed with single top directory with home file named index.html); file selected (doesn't matter whether options are checked or not), click to upload, when popup disappears, new theme does not show at /theming-controlpanel

manifest.cfg is not created

If I add new file, "manifest.cfg," and these two lines:

```
[theme]
title = MyNewTheme
```

then MyNewTheme shows up at /theming-controlpanel. According to the docs, all I should have to do is upload my zip file and it should just work.

Lastly, no errors are generated (in Errors panel or during fg mode)

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
