### ISSUE TITLE
Image upload doesn't work properly if plone.app.multilingual is activated.

### ISSUE THREAD

**Issue by karalics** [plone/Products.CMFPlone#1630]
Testet with latest minimalplone5
Products.CMFPlone-5.0.4-py2.7.egg

Upload Images looks like it has failed and the uploaded image is gone.
Console log:  GET http://localhost:8080/Plone/de/@@images/image/thumb 404 (Not Found)

I tried it here:
http://localhost:8080/Plone/**de**/++add++Document
Later I realized that the failed images were just uploaded to a different place. To the Plone root:
http://localhost:8080/Plone/  (without the language suffix/path)

It happens also if I select a specific Folder as upload target.

reproduction steps: 
- Installation of minimalplone5
- Activate add-on plone.app.multilingual. 
- Select at least two different languages. 
- Add a new Page, try to upload an Image within TinyMCE

**Comment by tomgross** [comment]
This works on coredev 5.1 branch. Any chance for a backport and a 5.0.5 release?

**Comment by tomgross** [comment]
Same as: https://github.com/plone/Products.CMFPlone/issues/1513
