### ISSUE TITLE
form_tabbing.js doesn't regard hashes in URL

### ISSUE THREAD

**Issue by ida** [plone/Products.CMFPlone#1640]
Calling an edit-form with an URL containing a hash, like `front-page/edit#fieldset-dates` one still lands on the default-tab open, not the dates-tab. The fix is to change the line:

`var targetPane = item.find('.enableFormTabbing input[name="fieldset"]').val() || window.location.hash;`

To:

`var targetPane = window.location.hash || item.find('.enableFormTabbing input[name="fieldset"]').val();`

So a hash-URL preceeds the default-selected tab.

Adding this as an issue instead of a PR, because I'm not sure how the procedure is for Plone-4.3 fixes.

**Comment by davilima6** [comment]
Hi, @ida. Thanks for reporting! I think there's no special procedure for 4.3, you can just make the PR and we can merge. Would you have any specific doubt?

**Comment by ida** [comment]
Hi @davilima6, thanks for your response, ok I'll go with forking the 4.3.x branch then. It's just the script has been removed lately, see: https://github.com/ida/Products.CMFPlone/commit/e7788f54c6f6adfa2d18da4d14fc2f579340d1a0#diff-dcdfbb5459c5869c9df2ee14a3ae72d7
I asked bloodbare there, if it can be restored.

Not sure, if I understand fully what you write about the edit-URL, but I'm calling it directly of a custom template, in order to land right away in a certain tab.

**Comment by davilima6** [comment]
What I meant is that if you right-click the tabs and Copy the link address you'll see that's currently wrong. And I think this is how most users will get a hold of that URL.

Re: the file removal, notice that the link you posted refers to the 5.0.2 branch. You can still see it there if you go to https://github.com/ida/Products.CMFPlone/tree/4.3.x/Products/CMFPlone/skins/plone_ecmascript

**Comment by ida** [comment]
@davilima6 Ah ok, thanks for claryfying! I see how far I can get, with squashing the further points you brought up and report back.

**Comment by jensens** [comment]
fixed with merge of #1643
