### ISSUE TITLE
LESS variable plone-toolbar-submenu-width is missing non-registry default value

### ISSUE THREAD

**Issue by datakurre** [plone/Products.CMFPlone#1646]
It's good practice that LESS files could be built without variables from Plone registry.

https://github.com/plone/Products.CMFPlone/commit/4850cf72825b4078189854a26fcd8e41f9a70092

/cc @jensens

**Comment by thet** [comment]
@datakurre I fixed this here (together with other toolbar compilation issues): https://github.com/plone/Products.CMFPlone/pull/1644/commits/41777374fcaf6ab4c82ee39312634414f01e28c9#diff-381ba97af7b18152b3dc651029f833a2

This is part of https://github.com/plone/Products.CMFPlone/pull/1644

There is still a problem with a failing robot test - may you can have a look at it? I ran out of ideas on how to fix it. See: https://github.com/plone/Products.CMFPlone/pull/1644#issuecomment-227841308

**Comment by datakurre** [comment]
@thet By reading the test report and looking (for some reason the HTML reports are broken at Jenkins...) it looks like a timing issue: At first the Insert button (for adding image) is clicked and then Save button is clicked, but because overlay is still open, the Save button is hidden by the overlay. I believe, it needs a keyword to wait that overlay is no longer visible?

**Comment by thet** [comment]
@datakurre tnx for the feedback! That sounds probable. I'll try this out right after trying to squash some commits.

**Comment by jensens** [comment]
merged #1644
