### ISSUE TITLE
Hide querystring upgrade profiles on add-site package listing

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#1649]
On a new 4.3.10 site.

<img width="747" alt="screen shot 2016-06-24 at 11 02 53 pm" src="https://cloud.githubusercontent.com/assets/483999/16354385/3200ff64-3a60-11e6-93bd-67eac1c1ef47.png">

**Comment by mauritsvanrees** [comment]
This was already done in plone.app.querystring:
https://github.com/plone/plone.app.querystring/commit/b6f79910973d106920c8cadaa66a5a2d5f5e9c78
But it was not in the `checkouts.cfg`. I have added it now.

**Comment by mauritsvanrees** [comment]
I have released plone.app.querystring 1.2.10 with that fix.
