### ISSUE TITLE
Logo Customization on control panel

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#165]

**Comment by gforcada** [comment]
@thet I would go for the second: create an image named ``logo`` and that's it. We could handle that indirectly from the control panel itself, to find it easier.

The AT vs DX can be solved with a try/except right?

Also for documentation that's just simple, clear and to the point: do you want to change the logo? Just use the control panel or directly create/modify what's in mysite.com/logo

**Comment by thet** [comment]
i already startet implementing the logo stored encoded in the registry. prerequisite is this branch, which allows the NamedImageWidget to be used on a zope.schema.Dict field, which can be stored in the registry: https://github.com/plone/plone.formwidget.namedfile/tree/thet-dictfieldconverter

i have the feeling that it's a bit hairy to depend on specific content structures. my solution is also easy. you just have the plone.formwidget.namedfile image widget in the site control panel to set the logo. unless there is a strong disagreement with that, i'll continue what i started.

**Comment by djay** [comment]
Why wouldn't you store it in the current diazo theme?
The caching rules are such that in most cases content images don't have strong caching. A logo really has to have strong caching since it's used on every page and is unlikely to change. =

**Comment by thet** [comment]
do you mean, storing a fileupload from the site controlpanel in the current diazo theme? hmhm... but that would be removed when installing an updated version of the theme, no?

i'd rather make sure, that the logo is strongly cached.


sidenote about one of my usecases: conent editors are creating lineage subsites. i want them to be able to customize the logo for the subsite without much hassle. with lineage.registry in place and a site controlpanel, wich isn't only bound to the plone site root, one can just do it via the upload widget in the controlpanel.

**Comment by djay** [comment]
I think you are optimizing for a case that doesn't or shouldn't happen.
Sites don't want updated themes. They want to update plone and have it look
exactly the same. A theme is not like a plugin that unknown third parties
improve. Its you own site look and feel and you should control that.
It doesn't feel right taking something which is the very essence of your
site theme and brand and taking out of the theming control.
If you are worried about theme upgrades perhaps its better to tackle that
problem directly instead?

**Comment by davisagli** [comment]
It's an entirely reasonable use case to want to give a user control over the logo but not over the entire theme. Maybe it's a user who is new to Plone and you want to reassure them that it will give them control without diving into the deep end of teaching Diazo theming immediately. Maybe it's someone responsible for a subsite in an organization that only wants a few people to have full control over the theme.

Also, storing it this way in the registry doesn't prevent someone with theming privileges from putting their logo in the theme if they want, so it seems noninvasive. +1

**Comment by djay** [comment]
If they are new to plone them a control panel or documentation that
modified a logo.jpg in the theme seems reasonable. No need to learn diazo.
Single image, no rules.
Then there is no later question of "now I've learnt  theming, where the
heck is my logo I uploaded? Why isn't it in my theme??"

Lineage themes where users control logo and not the theme is a very special
case. If you are making a theme like that then there is likely other
aspects you want certain users to control too. There are plenty of ways to
support this like special portlets. Doesn't seem like a good reason to make
a special new exception to how we do theming. CSS is in the theme. Js is in
the theme. Logo is in the theme... Except if it isn't.

**Comment by thet** [comment]
related pull request on plone.formwidget.namedfile:
https://github.com/plone/plone.formwidget.namedfile/pull/15

**Comment by thet** [comment]
all done and merged, and works like a charm:
- https://github.com/plone/plone.formwidget.namedfile/pull/15
- https://github.com/plone/Products.CMFPlone/pull/355
- https://github.com/plone/plone.app.layout/pull/38

**Comment by pbauer** [comment]
:beer:

**Comment by gforcada** [comment]
:+1:
