### ISSUE TITLE
PLIP: Remove plone.app.openid from core

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1659]
## Abstract
plone.app.openid is an old OpenID implementation for Plone used by very few users.

## Motivation
It is rarely used and should live as an addon. Also nowadays there are better and more flexible implementations for OpenID supporting many other protocols, like the more widespread  OAuth2: ``pas.plugins.authomatic``. We do not want to maintain it any more. It reduces the number of packages in Plone. Also we get rid of a warning while start-up.

## Assumptions
Nothing needs to happen before this PLIP.

## Proposal & Implementation
Remove from sources.cfg, versions.cfg  (including its dependencies) and as dependency in setup.py.

## Deliverables
Since we remove, there are just some PR's.

## Risks
Installations using this package need to explicitly specify plone.app.openid. It will not go away. This need a line in the upgrade guide.

## Participants
Jens Klein
Johannes Raggam

see also plone/Products.CMFPlone#1554

**Comment by tisto** [comment]
+1

Von meinem iPhone gesendet

**Comment by jensens** [comment]
@tisto: please vote also on the PLIP worksheet

**Comment by tisto** [comment]
Done

Am 05.07.16 um 21:33 schrieb Jens W. Klein:

**Comment by jensens** [comment]
PLIP "implemented" ... ready for review :D

**Comment by gforcada** [comment]
Merged!

**Comment by jensens** [comment]
@gforcada :D intend was to let it go through the plip process, but since we have 6 of 7 votes positive and one abstention (non voted): I will not revert it. If anyone of @plone/framework-team feels different please do revert so we can stick to the full process.

**Comment by gforcada** [comment]
@jensens @thet buildout.coredev was not cleaned up, see https://github.com/plone/buildout.coredev/issues/353
