### ISSUE TITLE
Contact form / sitemap redesign

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#167]
related #92

**Comment by vangheem** [comment]
No action on this in a while. Closing this until someone wants to work on it and writes a proper plip for it. Feel free to reopen.

**Comment by tkimnguyen** [comment]
At the board meeting today we discussed Plone 5.1 release planning. According to our notes this is one of the changes in Plone 5.1... but it seems it's not. I personally am in the middle of making changes to https://docs.plone.org/develop/plone/functionality/contactform.html so would love to know where I can find the new changes to the contact form for 5.1.
