### ISSUE TITLE
PLIP: Auto-Rotation for Images

### ISSUE THREAD

**Issue by loechel** [plone/Products.CMFPlone#1673]
**Proposer:** Alexander Loechel
**Seconder:** @hvelarde
# Abstract

Plone has a dedicated Contenttype for Images, which should offer an enhanced handler for different Image formats. 
Several Image Formats Specifications (JEPG, TIFF) contain a metadata set (Exif), which also contains information about image orientation. Plone should use them to auto-rotate the images. 
# Motivation

The Image specification for photos (RAW, JPEG, TIFF) contains metadata (Exif) on the image, which includes image orientation. Modern picture viewer and operating systems do show the image on the desktop rotated corresponding to the image orientation. For an editor in Plone it is not always clear that if they upload an image to Plone that contains Image Orientation, that this is ignored and Plone shows the original rotation. 

Since Dexterity and plone.app.contenttypes the shortcut image manipulation tab with rotation and mirroring has gone. So there is no easy online way to make an image using the correct orientation. 

There are several possibilities to read the Exif data and rotate the image on upload.
# Assumptions

no assumptions necessary
# Proposal & Implementation

The package plone.namedfile has to be modified so that on storage of an image the exif information of raw, jpeg and tiff images get read and do a image transformation (based on PIL/Pillow functions).
# Deliverables

new version of plone.namedfile
# Risks
- Old uploaded images don't get rotated as the meta-data has been dropped on store, so we could not rotate them on a upgrade step
- we include an additional external library for reading and writing Exif data
# Participants
# References
- https://github.com/plone/plone.namedfile/tree/plip-1673-automatic-image-rotation-based-on-exif-data (Current Development Branch)
- https://github.com/plone/plone.namedfile/pull/36 (corresponding Pull Request)

**Older approaches:**
- https://github.com/plone/plone.namedfile/pull/14 
- https://github.com/plone/plone.namedfile/pull/13
- https://github.com/plone/plone.namedfile/pull/12

**Comment by hvelarde** [comment]
this is related with #804

**Comment by ebrehault** [comment]
@loechel this PLIP has been approved by the @plone/framework-team

**Comment by loechel** [comment]
@svx could you mentor or appoint a doc mentor for this PLIP to help updating the corresonding documentation?

**Comment by pigeonflight** [comment]
I'm interested in helping out on this. Maybe a sprint task at the upcoming ploneconf sprint?

**Comment by loechel** [comment]
@pigeonflight yes documentation could be a good help or sprint topic.

**Comment by loechel** [comment]
@pigeonflight yes documentation could be a good help or sprint topic.

**Comment by jensens** [comment]
This PLIP is under review. 

Are this 

- code review 
- documentation

the open tasks before merge?

**Comment by loechel** [comment]
@jensens yes, it should have a code review. @pysailor did already did a first code review as it was still on the old branch, he might could contribute.

The Documentation for Plone 5.1, for which this PLIP aims should have be updated, so that the user knows that the image will be rotated on update after upload it they contain exif informations, @svx might know where in the docs that should go.

**Comment by jensens** [comment]
merged
