### ISSUE TITLE
Pointless error message from resource registry while manually adding resources and bundles and then building the bundle.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1678]
Clean Plone 5.0.5 installation. 

I added manually a bundle and then tried to register a resource with a JS and CSS file...possibly

Resource name: xmldirector
URL: ++resource++xmldirector.plonecore
JS: ag-grid/dist/ag-grid.js

Clicking on "Build" gives me this error with any reasonable error context about what the problem could be

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.resourceregistry, line 176, in **call**
  Module Products.CMFPlone.controlpanel.browser.resourceregistry, line 298, in js_build_config
TypeError: 'NoneType' object is not iterable

**Comment by jensens** [comment]
outdated
