### ISSUE TITLE
Version mismatch of plone.app.content in Plone 5.0.5 / 5.1a2

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1682]
The version of plone.app.content in Plone 5.1a2 is lower (3.0.20) as in Plone 5.0.5 (3.1.1).
See http://dist.plone.org/release/5.1a2-pending/versions.cfg and http://dist.plone.org/release/5.0.5/versions.cfg

**Comment by mauritsvanrees** [comment]
http://dist.plone.org/release/5.1a2-pending/versions.cfg is from 21 June. coredev branch 5.1 has the correct version: https://github.com/plone/buildout.coredev/blob/5.1/versions.cfg
