### ISSUE TITLE
Plone legacy bundle not re-created automatically after add-on installation/update

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1683]
https://github.com/zopyx/zopyx.plone.persistentlogger uses cssregistry.xml under Plone 5.0.5.

I updated some CSS styles in the packages, created a new package version and updated it within my buildout. 

After restarting the Plone site the new styles are not picked unless rebuilding the legacy bundle manually.

Of course we can not blame Plone here for not detected changed CSS files.
Not sure how to handle this better? What would be the right way to trigger and automatic build of the legacy bundle?

**Comment by mauritsvanrees** [comment]
I think it should work if you add an upgrade step that runs the `cssregistry` step of your profile. That should force an automatic compile.

**Comment by zopyx** [comment]
Possibly the best solution however not very nice. So you would end up with
a dedicated upgrade step for even the smallest css changes.
Perhaps a  magic "Rebuild all" button or view might be helpful here in
order to minimize multiple manual step in the resource registry...just for
the sake of simplicity.

2016-07-15 20:32 GMT+02:00 Maurits van Rees <notifications@github.com>:

**Comment by ebrehault** [comment]
There is a kind of "Rebuild all" button for that: just go to Resources registriy control panel, do and undo something (like go to plone bundle, enter a blank at the end of its name and remove the blank), so the Save button is enabled, and click Save.
It will regenerate the bundle aggregates.

Note: and there is a "Bundle combination" GS step that does the same.

**Comment by thet** [comment]
I always activate the development mode - save - deactivate development mode - save.

But @jensens and I were discussing that the resources actually should automatically be build when one of it's source file modification time is changed. The resources have to be touched anyways, no?

**Comment by zopyx** [comment]
Manual interactions with the resource registry are not acceptable for standard Plone Users. Builout and Plone restart are the two things must be enough inorder to make it work.

Regards
Andreas Jung
-----
Sorry for being brief - sent from a mobile device.

**Comment by fgrcon** [comment]
thelepatic interactions would be preferable sometimes ;-)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
