### ISSUE TITLE
Broken link inside the add ons activation form

### ISSUE THREAD

**Issue by oz123** [plone/Products.CMFPlone#1690]
I followed training.plone.org, trying to add a plugin to my plone, I saw the link to e Installing a third party add-on inside the form. Upon clicking on it, I received a 404 page.
![screenshot at 2016-07-22 12-40-06](https://cloud.githubusercontent.com/assets/1083045/17054925/062e58c2-500a-11e6-81b3-0c7c33830327.png)

The correct link would probably be http://docs.plone.org/manage/installing/installing_addons.html.
I guess this is an easy fix.

**Comment by pbauer** [comment]
Thanks for reporting. Additionally to fixing this in Plone itself we should add a redirect from http://plone.org/documentation/kb/installing-add-ons-quick-how-to to http://docs.plone.org/manage/installing/installing_addons.html. I created a issue for this: https://github.com/plone/ploneorg.core/issues/195
