### ISSUE TITLE
Icons are not shown properly

### ISSUE THREAD

**Issue by danielhz** [plone/Products.CMFPlone#1691]
I updated Plone from 5.0.3 to 5.0.5. Then, icons in the menu below the "Add page" title are not shown properly. See the image below.

![screen shot 2016-07-23 at 17 21 29](https://cloud.githubusercontent.com/assets/173787/17080324/b6dca018-50f8-11e6-8c4a-b3363cc9b448.png)

**Comment by keul** [comment]
See also https://github.com/plone/mockup/issues/707

**Comment by vincentfretin** [comment]
duplicate of https://github.com/plone/plonetheme.barceloneta/issues/147
