### ISSUE TITLE
Long words break in resource registry control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1692]
Plone 5.0.5

![screen](https://cloud.githubusercontent.com/assets/341393/17102703/39a5f6da-5251-11e6-8229-998d1bcb6545.png)

There are various other place with the same problem - in particular labels in plone.app.toolbar

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
