### ISSUE TITLE
Resource registries: 0 CSS files build although one CSS file configured

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1693]
I configured a resource (with one CSS file) and created a new bundle using this particular resource. Building the bundle gives me a message "0 CSS files build"...why?

http://public.zopyx.com/RR-builder.mp4

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
