### ISSUE TITLE
Installation of a Plone 5.0 add-on through the add-on installer of Plone does not install its resource bundle

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1698]
My add-on xmldirector.dropbox  installs without problems when I create a new Plone site and choose the related extension profile during installation.

Creating a new Plone 5.0.5 site and installing the add-on inside Plone does not install the resource registry resources. The resource bundle

https://github.com/xml-director/xmldirector.dropbox/blob/master/xmldirector/dropbox/profiles/plone-5/registry.xml

does NOT show up in the resource registries.

**Comment by jensens** [comment]
Works meanwhile, I use install it always this way
