### ISSUE TITLE
Can't add "Change Note" to File

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1700]
Plone 5.0.4

Adding a comment in "Change Note" when editing, such as to replace an existing file with a new one, throws "AttributeError: Schema" 

Seems closely related to #1437

**Comment by davilima6** [comment]
Could you please confirm if this bug is still present in latest version (5.0.5)? I couldn't reproduce it in the sites below:

* http://demo.plone.de/
* https://www.plone-demo.info/

**Comment by 3dogMcNeill** [comment]
Confirmed that the bug is not present in v5.0.5.
