### ISSUE TITLE
Adding "charset=windows-1252" as text will break encoding

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1704]
When I add the following as the content of a textfield (in Plone 4 with Archetypes, not yet tested with Dexterity): 

``` html
<p> </p>
<p>"charset=windows-1252"</p>
```

The rendered html will be 

``` html
<p>Â </p>
<p>"charset=windows-1252"</p>
```

The same does not happen in Plone5. This is bad since it's ok to write something like the above in some IT-documentation.

**Comment by pbauer** [comment]
This is true for Plone 4 **and** 5 when using Archetypes but never with Dexterity.

**Comment by pbauer** [comment]
It does not happen when disabling javascript, so it might have something to to with TinyMCE. 
I can confirm it still happens in 4.3.14 and 5.0.8 (still only with Archetypes).

**Comment by davisagli** [comment]
Closing since this is quite old and Archetypes is no longer supported.
