### ISSUE TITLE
Plone 5 Cannot change Publication Date in folder_contents

### ISSUE THREAD

**Issue by dready** [plone/Products.CMFPlone#1714]
In the folder_contents view in plone 5 you can mark an item and then on the properties Button. A window appears where you can set the Publication Date.. but it does not work in any way.

It does not matter if the item is already public or not, it just ignores the setting. There is also no error message on the log file.

Plone 5.0.5

**Comment by jensens** [comment]
Checked with 5.1 coredev and meanwhile it works.
