### ISSUE TITLE
TinyMCE does not use imagescales from imaging-controlpanel

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1717]
When I configure scales in /@@imaging-controlpanel TinyMCE still shows the default since they are only hard-coded in the pattern (`mockup/patterns/tinymce/pattern.js`) and not overwritten by `Products.CMFPlone.patterns.PloneSettingsAdapter.tinymce`

**Comment by agitator** [comment]
connected to https://github.com/plone/Products.CMFPlone/issues/1314
a controlpanel setting to allow to choose which scale should appear would also be nice

there are some more tinymce settings that don't work...
