### ISSUE TITLE
Plone configuration registry overlap issue/not responsive.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1719]
![screenshot-dev zopyx com 8080 2016-08-16 14-27-02](https://cloud.githubusercontent.com/assets/594239/17698823/8e0421a2-63bd-11e6-876a-6284efc280ad.png)

**Comment by zopyx** [comment]
![screenshot-dev zopyx com 8080 2016-08-16 14-31-35](https://cloud.githubusercontent.com/assets/594239/17698943/37562ade-63be-11e6-9972-32a7be2ddf1b.png)

**Comment by davisagli** [comment]
Looks good in Plone 6
