### ISSUE TITLE
Resource Registry - remove the js/css that some core components add into a default Plone site.

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#172]
This includes:

CSS
++resource++plone.app.jquerytools.overlays.css
++resource++plone.app.jquerytools.dateinput.css
++resource++plone.formwidget.recurrence/jquery.recurrenceinput.css
++resource++plone.formwidget.recurrence/integration.css
++resource++plone.app.event/event.css
++resource++plone.app.discussion.stylesheets/discussion.css
++resource++collection.css

JS
...

**Comment by vangheem** [comment]
I think we're going to leave what's left in for plone 5. I'm going to close the issue. These are still some legacy resources--it's okay.
