### ISSUE TITLE
Bad placement of "clear filter" button

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1721]
The "Clear filter" button should be place on the same line as the input field since they belong together.

**Comment by zopyx** [comment]
https://nimbus.everhelper.me/client/notes/share/549519/1w762z8wfi507i3kn052

**Comment by vincentfretin** [comment]
Your screenshot appears broken.
Here did you mean the Clear button in folder contents Plone 5.2.2?
![Capture d’écran de 2020-07-08 13-25-17](https://user-images.githubusercontent.com/112249/86913210-974ff200-c11e-11ea-9ee4-c853b0194a13.png)

**Comment by mauritsvanrees** [comment]
On Plone 6.0 it looks okay. Not on the same line, but the line is pretty full anyway, so it seems better this way.

![Screenshot 2022-08-24 at 13 09 20](https://user-images.githubusercontent.com/210587/186404067-7c13a5b9-1f10-402e-9f31-1e632623484d.png)

I doubt anyone wants to fix this UI issue in 5.2 still. I close this.
