### ISSUE TITLE
Impossible to edit content rule email 

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1722]
Create a content rule to email you f. e. in case somebady added an article.
Then click on Edit of the Send Email.
Edit subject, message, and /or email recipient.
Save the changes
Click on edit again.
You can see that no changes have been saved.

**Comment by esteele** [comment]
This appears to be working in 5.0.x (pre-5.0.9 coredev buildout) and 5.1b4. Feel free to reopen if you discover otherwise.
