### ISSUE TITLE
Using comment related substitutions in content rules email message leads to error

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1723]
Create a content rule to email you f. e. in case somebady added an article.
Then click on Edit of the Send Email.
Edit the message of the mail and use all comments related substitutions

Comments    ${comment_id}   Comment id
Comments    ${comment_text} Comment text
Comments    ${comment_user_email}   Comment author email
Comments    ${comment_user_fullname}    Comment author full name
Comments    ${comment_user_id}  Comment author user name

Safe and add an article.

Ok there is no comment, but the error should not occur.

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 130, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 105, in handleAdd
  Module z3c.form.form, line 265, in createAndAdd
  Module plone.dexterity.browser.add, line 80, in add
  Module plone.dexterity.utils, line 182, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 461, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.contentrules.handlers, line 181, in added
  Module plone.app.contentrules.handlers, line 130, in execute
  Module plone.contentrules.engine.executor, line 38, in __call__
  Module plone.contentrules.rule.rule, line 49, in __call__
  Module plone.app.contentrules.actions.mail, line 138, in __call__
  Module plone.stringinterp.dollarReplace, line 58, in __call__
  Module string, line 207, in safe_substitute
  Module string, line 198, in convert
  Module plone.stringinterp.dollarReplace, line 36, in __getitem__
  Module plone.stringinterp.adapters, line 44, in __call__
  Module plone.app.discussion.contentrules, line 59, in safe_call
  Module plone.app.discussion.contentrules, line 47, in comment
AttributeError: 'NoneType' object has no attribute 'comment'
```

**Comment by pabo3000** [comment]
Plone 5.0.5
plone.app.locales-5.0.10-py2.7.egg

**Comment by pabo3000** [comment]
There are even more substitutions which leads to an error.
Here an error which seems to be related to the review_state

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 130, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 105, in handleAdd
  Module z3c.form.form, line 265, in createAndAdd
  Module plone.dexterity.browser.add, line 80, in add
  Module plone.dexterity.utils, line 182, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 461, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.contentrules.handlers, line 181, in added
  Module plone.app.contentrules.handlers, line 130, in execute
  Module plone.contentrules.engine.executor, line 38, in __call__
  Module plone.contentrules.rule.rule, line 49, in __call__
  Module plone.app.contentrules.actions.mail, line 138, in __call__
  Module plone.stringinterp.dollarReplace, line 58, in __call__
  Module string, line 207, in safe_substitute
  Module string, line 198, in convert
  Module plone.stringinterp.dollarReplace, line 36, in __getitem__
  Module plone.stringinterp.adapters, line 44, in __call__
  Module plone.stringinterp.adapters, line 295, in safe_call
  Module Products.CMFCore.WorkflowTool, line 263, in getInfoFor
WorkflowException: No workflow provides '${name}' information.

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 5.0 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
