### ISSUE TITLE
Replace "Add comment" with translation

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1724]
Switch to german language.
Enable the commenting feature.
Add an article.
The headline of the commenting feature at the lower end of the article should be 

> Kommentar hinzufügen

but it is not translated.

**Comment by gforcada** [comment]
@pabo3000 thanks for all the bug reports, would you mind providing the exact Plone version you are using and how you installed it? That will be quite helpful.

**Comment by pabo3000** [comment]
Plone 5.0.5 (5015)
plone.app.locales-5.0.10-py2.7.egg

**Comment by Shriyanshagro** [comment]
I would like to work on this issue. Can someone suggest me the package for this issue, as I see this is not associated with plone.app.locales.

**Comment by cewing** [comment]
Hello, @Shriyanshagro!  I believe the problem here is located in the commenting feature itself.  That is [`plone.app.discussion`](https://github.com/plone/plone.app.discussion)

**Comment by Shriyanshagro** [comment]
Hey @cewing , I'm new to Plone and currently setting up the discussion forum, but I'm not able to enable the commenting feature. Though I have already choosen the "Allow Comments" under Types Control Panel of that particular type.
Also I believe for this issue, we need to make changes under this file and add required translations
https://github.com/plone/plone.app.discussion/blob/master/plone/app/discussion/i18n/plone-de.po

**Comment by mikkohu** [comment]
This problem seems to be fixed in 5.0.11 version of locales. Apparently it was just a missing msgstr from the .po file.

**Comment by Shriyanshagro** [comment]
Exactly @mikkohu , that's what I have figured out too and mentioned the file .po in my last comment too. 
@cewing I think this issue can be closed now??

**Comment by Rostislav2017** [comment]
TranslatorsAuction is the translation exchange with a free selection of the best performer for the Auction principle.
It provides the unique opportunity to conduct the ruled auction: preliminary testing, cross assessment by potential authors the works of the other applicants, ranging the results of the tests according to the points gained by "blind" assessment. The conditions allow the customer to choose the option, which is the most suitable for his requirements in compliance with the ratio suggested price – points of the general rating. 
There are three options for placing orders: 
- with the selection of translators without testing, by personal preference or the current rating;
- with the test task for applicants, which is not providing payment for performance;
- with payment for a test task to the translator, who will be chosen by the customer, for the attraction of significant number of authors and quick data acquisition for the choice of the applicant.
For the translators, offering their services at the exchange, the performance of the competitive translations can be a key to obtaining good orders or one of the ways of increasing rating.
[ https://translatorsauction.com](url)
