### ISSUE TITLE
No form unload protection in Plone 5

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1729]
Plone 5 doesn't have a form unload protection. We have a "formunloadalert" pattern, which is triggered by the ``.pat-formunloadalert`` class, but Plone 5 doesn't use it.

**Comment by thet** [comment]
I'm about to fix this. We still use the class ``enableUnloadProtection`` instead ``pat-formunloadalert``, which would trigger the mockup pattern.

I see three ways, all will work:

1) change the Mockup ``formunloadalert`` pattern trigger class from ``.pat-formunloadalert`` to ``.enableUnloadProtection``.
Pros:
- No templates need to be changed. Works by only updating mockup branches for Plone 5.1 and 5.0 (if possible - Maybe we need Mockup > 2.0 with it's patternslib based parser for it?) and including them.
Cons:
- It differs from Mockup pattern trigger conventions and thus It's not obvious that this functionality is implemented as a Mockup pattern.
- It might break other peoples code, if they rely on the ``.pat-formunloadalert`` trigger class. I guess, this will not affect much people.

2) Updating templates and change ``enableUnloadProtection`` to ``pat-formunloadalert``.
This is the list of occurences of ``enableUnloadProtection``. All of these are Plone 5.x specific, so this will not break code in Plone 4:

```
plone.app.theming/src/plone/app/theming/browser/controlpanel.pt:335:            class="enableUnloadProtection"
plone.app.theming/src/plone/app/theming/browser/controlpanel.pt:705:            class="enableUnloadProtection"
plone.app.z3cform/plone/app/z3cform/templates/macros.pt:53:                      class="rowlike enableUnloadProtection" action="." method="post"
plone.app.z3cform/plone/app/z3cform/templates/macros.pt:60:                                  unload_protection python:enable_unload_protection and 'enableUnloadProtection';
Products.CMFPlone/Products/CMFPlone/skins/plone_prefs/password_form.pt:26:              class="pat-formautofocus enableUnloadProtection"
Products.CMFPlone/Products/CMFPlone/skins/plone_prefs/prefs_error_log_form.pt:130:              class="enableUnloadProtection">
Products.CMFPlone/Products/CMFPlone/controlpanel/browser/usergroups_groupdetails.pt:83:                class="enableUnloadProtection pat-formautofocus"
Products.CMFPlone/Products/CMFPlone/controlpanel/browser/emaillogin.pt:48:          class="enableUnloadProtection pat-formautofocus">
Products.CMFPlone/docs/HISTORY.txt:8684:  class="enableUnloadProtection" are checked.
plone.app.caching/plone/app/caching/browser/import.pt:62:                    class="enableUnloadProtection"
plone.app.caching/plone/app/caching/browser/purge.pt:74:                    class="enableUnloadProtection"
plone.app.caching/plone/app/caching/browser/controlpanel.pt:94:                    class="enableFormTabbing enableUnloadProtection pat-autotoc"
plone.app.caching/plone/app/caching/browser/ramcache.pt:61:                    class="enableUnloadProtection"
Products.Archetypes/Products/Archetypes/skins/archetypes/base_metadata.cpt:62:            class="enableUnloadProtection"
Products.Archetypes/Products/Archetypes/skins/archetypes/edit_macros.pt:83:            class="enableUnloadProtection enableAutoFocus atBaseEditForm"
Products.Archetypes/Products/Archetypes/skins/archetypes/edit_macros.pt:88:                            class python:test(path('allow_tabbing|nothing'), 'enableUnloadProtection enableAutoFocus enableFormTabbing pat-autotoc enableUnlockProtection', 'enableUnloadProtection enableAutoFocus enableUnlockProtection');">
```

Pros:
- Cleaner code, does not break Mockup conventions
Cons:
- Might break others code, where custom forms use ``enableUnloadProtection`` (although those wouldn't work with the pattern anyways)
- Might break CSS customizations (probably not the case with ``enableUnloadProtection``)
- Needs to be clearly documented (Incompatibilities section in Changelog, Plone upgrade guide)

3) Like 2) but instead of replacing the class just adding ``.pat-formunloadalert``. This is already done with ``enableFormTabbing``. Eliminates Cons of 2) but adds possibly unnecessary boulerplate.

Safest options are 1) and 3), but I personally prefer 2).

Any opinions? /cc @vangheem @@jensens

**Comment by jensens** [comment]
since it does not work now anyway, I'd go for (2)

**Comment by mauritsvanrees** [comment]
2 sounds okay to me.
