### ISSUE TITLE
Menu buttons available on all context

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#173]
The following menu buttons are available on all context and no only in the context of folderish content types:

- [ ] Contents
- [ ] View
- [ ] Sharing
- [ ] Content info

**Comment by hvelarde** [comment]
no, it should be available only in the context of folderish content type intances.

here you have the user preferences page displaying some actions:

![selection_001](https://cloud.githubusercontent.com/assets/341393/7802074/39a5155e-0305-11e5-85c8-466afb695fa4.png)

**Comment by vangheem** [comment]
IMO, it should be available on any context. Folder contents is the major place where "Content Management" takes place--it should be accessible from everywhere.

**Comment by bloodbare** [comment]
I really can't remember why I wrote that issue and I can see that it was in a rush, sorry guys!

I think that my point is that this four buttons does not make so sense on contexts like control panel, search results where the context idea is not related with the view you are seeing, but its quite a UX problem.

**Comment by agitator** [comment]
No reason to display it on a controlpanel.

Different story for content, it's the one "tool" in the content area that allows the (confused) user to see what's already there.
