### ISSUE TITLE
MemberDataTool uses deprecated Python syntax for raising exception

### ISSUE THREAD

**Issue by cewing** [plone/Products.CMFPlone#1743]
[This post](https://community.plone.org/t/plone-role-manager-throwing-error/2618) in community.plone.org led me to discover a bit of code in the MemberDataTool in Products.CMFCore that appears to use a Python syntax that is no longer valid in modern Python.  

The code in question is [in the `getUser` method](https://github.com/plone/Products.CMFCore/blob/2.2/Products/CMFCore/MemberDataTool.py#L255-L266):

``` python
    security.declarePublic('getUser')
    def getUser(self):
        # The user object is our context, but it's possible for
        # restricted code to strip context while retaining
        # containment.  Therefore we need a simple security check.
        parent = aq_parent(self)
        bcontext = aq_base(parent)
        bcontainer = aq_base(aq_parent(aq_inner(self)))
        if bcontext is bcontainer or not hasattr(bcontext, 'getUserName'):
            raise 'MemberDataError', "Can't find user data"
        # Return the user object, which is our context.
        return parent
```

the problem is in the line where we are raising an exception indicating we can't find user data.  

Unless I'm mistaken, we are using the ancient Python syntax where you could raise a "custom exception" that was just a string.  The second argument to the raise statement was the message, and an exception object would be generated with that message.

I've been poking around trying to figure out when this became illegal, and it appears to have been quite some time ago.  As early as Python 2.0 the documentation de-emphasizes using this approach in favor of creating Exception classes.  

I think the right thing to do would be to declare a `MemberDataError` Exception subclass and raise it instead, but I'm not entirely clear on what the implications might be in terms of where this exception is handled.  There is no other reference to `MemberDataError` I can find in core Plone code anywhere.

Any thoughts on the right approach to solving this?

**Comment by mauritsvanrees** [comment]
Ouch. :-(

When I try `raise 'foo'`:

- in Python 2.4 it works (so Plone 3 and lower)
- in Python 2.5 it works but also gives a warning (no Plone version supports 2.5)
- in Python 2.6 it raises a TypeError (so Plone 4 and higher)

I would say, simply do this:

```
raise ValueError("Can't find user data")
```

It should be fixed in Products.CMFCore. I don't see activity there, though that is also because Plone people are not doing anything. So maybe create a patch in Products.CMFPlone. We already have `patches/csrf.py` which does a bit of patching there.

**Comment by cewing** [comment]
It seems like fixing it in Products.CMFCore is the better place to handle the problem.  There is a copy of that in the Plone github organization, though I am not clear if we've followed through on taking over those packages.  Anyone else have some input on this one?

**Comment by gforcada** [comment]
@cewing I see that @esteele has pypi permissions on [Products.CMFCore](https://pypi.python.org/pypi/Products.CMFCore), so maybe it is safer to send pull requests there.

@polyester and @esteele usually know the exact state of the forks

**Comment by gforcada** [comment]
@cewing now I see that @mauritsvanrees is sending pull requests to the zope foundation repo, so maybe we should still do that?

**Comment by mauritsvanrees** [comment]
Yeah, I'll make some pull requests in the zopefoundation repo.

**Comment by mauritsvanrees** [comment]
A few rabbit holes later...

On CMFCore master (2.3) the old exception is not used, except in a test, which I fixed.

For CMFCore 2.2 I made a pull request: https://github.com/zopefoundation/Products.CMFCore/pull/5

**Comment by cewing** [comment]
Thanks so much @mauritsvanrees
