### ISSUE TITLE
Products.PloneHotfix* should not log errors for hotfixes not meant for a plone version

### ISSUE THREAD

**Issue by frisi** [plone/Products.CMFPlone#1744]
PloneHotfix20160830 lead to warnings in instance.log when installed on a plone4.x site.
see analysis and  discussion in https://community.plone.org/t/plonehotfix20160830-and-could-not-apply-user-warning-on-plone-4

future hotfixes should check for imports or package versions of the packages they are patching.
unfortunately i don't have any idea (except a checklist, or a hotfix template with some boilerplate for import/version checks) how to make sure that future hotfixes take this into account.

in addition, it would be great to print the stacktrace to the log so admins/integrators have a better idea what is going on:

``` python
for hotfix in hotfixes:
    try:
        __import__('Products.PloneHotfix20160830.%s' % hotfix)
        logger.info('Applied %s patch' % hotfix)
    except Exception, e:
        logger.warn('Could not apply %s' % hotfix)
        logger.warn(str(e))
```

is there a base-template for hotfixes this improvement could be contributed to?

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
