### ISSUE TITLE
add link to login form in pwreset_finish.pt?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1748]
When Plone sends out a password reset email, after a user successfully resets their password they are shown the pwreset_finish.pt with the message "Your password has been set successfully. You may now log in with your new password.". Is there a reason why "log in" shouldn't be a link to the "login_form"?

**Comment by tomgross** [comment]
Added here: afe8759364d193fda78b9e8aa6c15a17ed0b2107
It's available after #1799 is merged.

**Comment by tiberiuichim** [comment]
There's a bug with the current implementation, Plone 5.1b3.dev0: when clicking on the "login" link in the pwreset_finish page, the "came from" is the password reset page, with the reset code in the URL. After logging in, we're redirected to the same page, with the reset code, this time we're getting a message:

> ##Error setting password
> Sorry, this appears to be an invalid request. Please make sure you copied the URL exactly as it appears in your email and that you entered your email address correctly.

**Comment by jensens** [comment]
this was fixed AFAIK.
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
