### ISSUE TITLE
resourceDirectory ZML registration can't use layer if resources are used by resource registry

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#1749]
I commonly protect all of my `resouceDirectory` registration with the proper add-on's browser layer, but I found this is not possible if the resource folder contains a resource used by new the resource registry.
More correctly: we can't have both the `browserlayer.xml` and `registry.xml` in the same add-on.

The error you'll get it something like:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
   - __traceback_info__: ('my.addon',)
  Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
   - __traceback_info__: profile-my.addon:default
  Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
   - __traceback_info__: combine-bundles
  Module Products.CMFPlone.resources.exportimport.bundles, line 28, in combine
  Module Products.CMFPlone.resources.browser.combine, line 119, in combine_bundles
  Module Products.CMFPlone.resources.browser.combine, line 74, in write_js
  Module Products.CMFPlone.resources.browser.combine, line 41, in get_resource
  Module OFS.Traversable, line 300, in unrestrictedTraverse
   - __traceback_info__: (['my.js'], '++resource++my.addon')
```

The `registry.xml` is something like this:

```
<?xml version="1.0"?>
<registry>
    <records prefix="plone.bundles/my-addon"
              interface='Products.CMFPlone.interfaces.IBundleRegistry'>
      <value key="csscompilation">++resource++my-addon/styles.css</value>
      <value key="jscompilation">++resource++my-addon/article.js</value>
      <value key="enabled">True</value>
      <value key="compile">False</value>
      <value key="depends">plone</value>
      <value key="merge_with">default</value>
    </records>
</registry>
```

I think this is happening because until the registration ends we don't have the layer really registered so the traversing to files inside the resource directory, done by the resource registry, is not working.

The workaround is simple: just don't use `layer` protection, but I find this a little hacky and unclean.

**Comment by seanupton** [comment]
@keul @agitator Can you verify that you still have this chicken-vs-egg problem on import of your respective add-ons?

For some reason, I am not having this problem with my add-ons, but do have (unrelated) browser layer issues I am [fixing in gruntfile generation](https://github.com/plone/Products.CMFPlone/issues/2080).

**Comment by keul** [comment]
Hi @seanupton, on which Plone version you don't have the issue?

**Comment by keul** [comment]
On Plone 5.0.7 and 5.0.8 I still have the issue.

**Comment by thet** [comment]
On latest Plone too.
While updating collective.lazysizes for Plone 5 I ran into the same issue. IIRC while installing the problem was that the ++resource++ directory paths coulnd't be found, so I left out the browser layer it worked again ( https://github.com/collective/collective.lazysizes/commit/58c4322331dbf3d65ec5966d43e5c79a049a6f95#diff-1e3819934a65fe2eae8c25b9e90dda01L27 )
I think not using the browser layer is totally OK as a workaround and maybe should be the standard.
Without browser layer you can use resource directories from other packages, which is totally fine. With browser layer you could only use them when the browser layer is installed and all the other stuff too, which you might not want.

**Comment by keul** [comment]
@thet let's say is a feature, not a bug 😄 

Is a perfectly legit workaround I'm my opinion too, having name clashing with resources is really uncommon... but still is a bit hacky. We protected resources with browser layers for years and it was OK.

**Comment by davisagli** [comment]
The real fix is probably to declare that the registry import step depends on the browserlayer import step.

David Glick
(mobile)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
