### ISSUE TITLE
Live search view

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#176]

**Comment by vangheem** [comment]
bah, I just implement this and I didn't know that @ale-rt did all the of the work already... Sigh.

@ale-rt would you might looking at my implementation and seeing if you have any additional improvements? https://github.com/plone/mockup/commit/3004bca21646fe64a8a03bb791f7f9923cec800b

This is now integrated into plone core live search.

**Comment by ale-rt** [comment]
Well done @vangheem!
I really prefer your version, mine was basically moving the old Plone code to a pattern.
Your approach is really preferable :)

Thanks a lot for closing this!
