### ISSUE TITLE
Search results RSS feed isn't displayed in the UI (no icon or link)

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1762]
When the related setting (`search_rss_enabled`) in `@@syndication-controlpanel` is turned on, the RSS link is rendered in the markup but no RSS link or icon is displayed in the UI.

Moreover, the RSS link is rendered regardless if the setting is turned off. When trying to access the feed URL you get a 404, though.

Tested in Plone 4.3.4 and 5.0.5.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
