### ISSUE TITLE
Idea: check dependency before uninstalling

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1773]
This is an idea that surfaced when working on PLIP #1340.

Before uninstalling, check if the default profile is a dependency of another profile that is currently installed.  In that case we could prevent uninstall, or warn.

But: someone might want to uninstall a package and install it immediately after, to solve some problem.

**Comment by hvelarde** [comment]
just warn, people must be responsible for their acts.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
