### ISSUE TITLE
Idea: unmark default profile in event when applying uninstall profile

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1774]
This is an idea that surfaced when working on PLIP #1340.

In the `uninstall_product` method we apply the uninstall profile and unmark the default profile.  We could do this in an event handler instead, much like the old event handler in `Products.CMFQuickInstallerTool`, so that the default profile is also unmarked when someone manually applies the uninstall profile.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Comment by mauritsvanrees** [comment]
We could still do this, it is still relevant also for Plone 6.  But if someone manually applies the uninstall profile, they can manually unmark the default profile as well.  No one has stepped up to implement the idea to automate this, including me, so indeed fine to close.
