### ISSUE TITLE
main_template.pt body tag  tal:attributes  error

### ISSUE THREAD

**Issue by adam139** [plone/Products.CMFPlone#1776]
`tal:attributes="class body_class;
                        dir python:isRTL and 'rtl' or 'ltr';
                        python:plone_view.patterns_settings()"`

**Comment by gforcada** [comment]
@adam139 thanks for reporting the issue, would you mind explaining it a bit further? what's the actual error you see? which version of Plone are you using?

**Comment by davisagli** [comment]
This works fine with Chameleon; the `python:plone_view.patterns_settings()` part returns a dict and the items in the dict are added as attributes. Feel free to reopen and explain what's not working.
