### ISSUE TITLE
moment.js only load required/configured locales

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1779]
trying to slim down the Plone default.js which has grown to whooping 1.5mb in my project

I found that for example moment-with-locales.min.js is already 172kb because all locales are included.
Do we have a way to only include the locales needed for the configured languages of a Plone site?

**Comment by davilima6** [comment]
Fixed in:
*  https://github.com/plone/mockup/pull/887/files
* https://github.com/plone/plone.staticresources/pull/10/files

Now we're at 55kb (3x drop) o// Thanks for the suggestion!
