### ISSUE TITLE
Improper URL rendered for NamedBlobImage fields in DX 'view'

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1788]
Running Plone 4.1 with plone.app.dexerity 2.1.1.

A DX type contains

```
    image = NamedBlobImage(
        title=_(u"Image"),
        required=False,
    )

```

An uploaded image appears properly as preview in edit mode of the content however the default 'view' only shows a broken image.

The generated URL is (where 'x' is the Plone site and 'seminar' the related content object):

http://foo.de:10080/x/seminar/view/++widget++form.widgets.image/@@download/Screenshot+2016-10-04+13.40.01.png

````
  '/home/ajung/sandboxes/dynamore/eggs/plone.namedfile-3.0.7-py2.7.egg',
  '/home/ajung/sandboxes/dynamore/eggs/plone.formwidget.namedfile-2.0.2-py2.7.egg',
```

**Comment by hvelarde** [comment]
you're not supposed to used Dexterity 2.0 with Plone 4.1; you have to use Dexterity 1.x with a KGS like this one:

http://good-py.appspot.com/release/dexterity/1.2.1?plone=4.1.6

**Comment by zopyx** [comment]
Well, I do it and it is perfectly working except for this particular error...anyway..I wrote my own view for this content type...
