### ISSUE TITLE
Links in folder_content not working under Chrome

### ISSUE THREAD

**Issue by Martronic-SA** [plone/Products.CMFPlone#1789]
I don't know if it has been already mentionned somwhere but it seems that under Chrome in folder_contents view, it's not possible to click on a link in the content list. It behaves like reordering.
It's working fine on firefox.
Plone v. 5.0.6
Thanks!

**Comment by davilima6** [comment]
I confirm it in 5.0.6 and coredev.

**Comment by wohnlice** [comment]
This appears to still be an issue in Plone 5.1. Works fine in Firefox and IE.

**Comment by abosio** [comment]
Still running into this occasionally. Have not been able to reduce issue. It might only be Chrome on Windows. It seems like the drag interferes with the click.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
