### ISSUE TITLE
Title and breadcrumbs don't get updated in folder_contents

### ISSUE THREAD

**Issue by mr-rob** [plone/Products.CMFPlone#1796]
Plone 5.0.6, plone.app.content 3.2

Title and breadcrumbs don't get updated while navigating through folders via folder_contents.
Steps to reproduce:
 - Create a folder and one or two subfolders
 - Start in the root-folder and click on the subfolders
The sidebar, breadcrumbs of pat-structure and the address-bar of the browser show the current folder. 
However the Title (documentFirstHeading) and portal-breadcrumbs don't show the current folder which confuses some of our editors.

![folder3](https://cloud.githubusercontent.com/assets/5370769/19520965/52e8ce24-9612-11e6-8d93-aaced66ac500.png)

**Comment by hvelarde** [comment]
duplicated with #1379
