### ISSUE TITLE
Replace cssmin for something else

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#1800]
It is no longer maintained and it is no python 3 compatible.

A quick search on pypi shows https://pypi.python.org/pypi/rcssmin/1.0.6 as python 2 and 3 compatible... any other solution?

**Comment by tomgross** [comment]
https://pypi.python.org/pypi/cssutils/1.0.1 is another one.

**Comment by loechel** [comment]
I have already tried it, it is actually Python 34-3.6 compatible or needed just a few minutes to fix it, I think I still have it on my notebook. But it is also so old that it has never been flagt as such. but we should replace it totaly, it does not make any sense anymore, if we switch to extrenal JavaScript tools like webpack.

If we want to keep JS and CSS minifing in Plone, then a SASS element would be much better, we might should look if https://pypi.python.org/pypi/pyramid_scss could be integerated

**Comment by gforcada** [comment]
@loechel I would be more than happy if we first to a minimal cssmin to *something* replacement and later on decide if we drop it all together, as that would involve a much more longer and, possibly, heated community discussion.

*Let's keep it simple as we have so much to do* 🙂

**Comment by loechel** [comment]
Ok, I will make a fork in the plone org and make a Python 3 compatible version tomorrow, we might need to look for a new name or release rights.

**Comment by loechel** [comment]
I have also tested to directly replace it by PyScss which works very smooth, but yes one step after each other.

**Comment by gforcada** [comment]
@loechel does it make sense to fork an unmaintained project? Physiologists will call this "Plone syndrome" 😆 keep unmaintained projects alive and kicking 😄 

I would rather just replace it by a maintained *and* python 3 compatible right away. As long as we don't move to python 3, cssmin is still usable and works, so if we want to change something there, let's do it future proof ™️

**Comment by loechel** [comment]
then I would suggest to move to PyScss which could do that easily and some additional things.

**Comment by gforcada** [comment]
Ptscss would not do the trickas our current CSS is on LESS, or does it support LESS as well? On the pypi page it does not say anything

**Comment by loechel** [comment]
@gforcada first of all, PyScss should be the replacement for cssmin, which it would do perfectly, see https://gist.github.com/loechel/a8d037908d0158f14b1841e1bb3d72a8 
But also SCSS is a superset of CSS, SASS and LESS, it could handle our less files. We don't use the edge cases where the compatibility is low.

PyScss support an uptodate version of SCSS and therefor we could benefit from that.

And also perfect examples for the usage of this module is in Pyramid and the OneGov Theme (https://github.com/OneGov/plonetheme.onegov) for Plone 4 

I could do a pull request and replace the useage of cssmin against the usage of PyScss. And we could use it in other places two.

**Comment by gforcada** [comment]
Oh I see, cool then, if you don't mind doing the pull request, go ahead!

**Comment by loechel** [comment]
@gforcada see https://github.com/plone/Products.CMFPlone/pull/2107

**Comment by loechel** [comment]
@gforcada can we close this issue now?

**Comment by gforcada** [comment]
Yup! Thanks for your work on this!!
