### ISSUE TITLE
RESPONSE content-type - application/javascript when installing some add-ons

### ISSUE THREAD

**Issue by avoinea** [plone/Products.CMFPlone#1806]
When you enable EEA Faceted Navigation Add-on on Plone 5 it gets installed and you're redirected to Plone site, but this page has RESPONSE.headers = application/json thus it looks like it's broken.

The problem seems to be in [`Products.CMFPlone.resources.browser.cook.cookWhenChangingSettings`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/cook.py#L25)
[`ConfigJsView`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/configjs.py#L85) get's called and its `Content-Type` header leaks onto the main request's response.

The following code in `cook.py` will fix the issue but I think the real fix needs to be done in `plone.subrequest` as it doesn't seem right for subrequest headers to end up on the main request.

``` python
def keep_response_headers(headers):
    def _decorator(func):
        def _func(context, bundle=None):
            keep = {}
            response = getRequest().RESPONSE

            for header in headers:
                keep[header] = response.getHeader(header)

            result = func(context, bundle)

            for header, value in keep.items():
                response.setHeader(header, value)

            return result
        return _func
    return _decorator


@keep_response_headers(['Content-Type'])
def cookWhenChangingSettings(context, bundle=None):
...

```

**Comment by avoinea** [comment]
See also plone/Products.CMFPlone#1436

**Comment by jensens** [comment]
this was fixed by https://github.com/plone/Products.CMFPlone/commit/20a46bcca5ce095d88d2fe6ebccda0bcf9939d50
