### ISSUE TITLE
Move non-archetypes-specific code out of plone.app.folder in CMFPlone

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#1817]
I was looking at removing ZopeTestCase from plone.app.folder and got to a point where a test needs to create Folder but after changing it from ZopeTestCase to plone.app.testing the folder no longer existed.

Long story short: I started to notice that plone.app.folder is full of Products.Archetypes imports, so I'm not sure if it has anything that's not Archetypes specific and thus makes sense to port it to both plone.app.testing _and_ dexterity or if it will be one of the packages that with the removal of Archetypes at some point will be removed as well.

Anyone has a bit more insight than me?

**UPDATE**
Given @davisagli comment (see below), if we move the fake `GopipIndex` out of plone.app.folder we can put plone.app.folder on the Archetypes specific packages which are meant to not long last anymore (in terms of Plone 6 and future), thus making it easier to not spend time nor resources in keeping them up-to-date and fixing their test isolation problems (their tests will run on the AT specific jenkins job).

**Comment by davisagli** [comment]
Looks like plone.app.folder basically has two things in it:
1. The folder base class used by Archetypes.
2. The `GopipIndex` which is used for the fake `getObjPositionInParent` index to look up the position in the actual folder.

If we move the GopipIndex elsewhere (probably to CMFPlone) then plone.app.folder will only have Archetypes-related code.

**Comment by gforcada** [comment]
@pbauer @jensens is this still relevant or should it be closed? I remember reading something about it some weeks/months ago.

**Comment by pbauer** [comment]
This is being worked on in https://github.com/plone/Products.CMFPlone/issues/2422

**Comment by jensens** [comment]
Probably not relevant anymore. Reopen if I am wrong
