### ISSUE TITLE
Legacy bundle does no honor TAL expressions

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1821]
We have a package that [registers some JS code](https://github.com/collective/collective.glossary/blob/master/src/collective/glossary/profiles/default/jsregistry.xml) and displays it using a TAL expression like this:

```xml
<?xml version="1.0"?>
<object name="portal_javascripts">
  <javascript id="++resource++collective.glossary/main.js"
              expression="context/@@glossary_state"
              insert-after="*" />
</object>
```

The `glossary_state` view checks some constrains to validate if the JS code must be loaded or not:

```python
class GlossaryStateView(BrowserView):
    ...
    def __call__(self):
        return self.tooltip_is_enabled and self.content_type_is_enabled and self.is_view_action
```

So, in Plone 4 the code is not loaded in the` @@edit` view, but in Plone 5 this is not honored and the code is loaded always leading to some unintended consequences like losing the content on the body text field.

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 5.0 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
