### ISSUE TITLE
"cut" and "copy" actions fail silently when _cp cookie becomes too large

### ISSUE THREAD

**Issue by tmog** [plone/Products.CMFPlone#1841]
When a large number of content (100+) items are selected and copied/cut, the UI claims items were copied/cut but no _cp is not updated.

As far as I know, this was always an issue in Plone. 
But it seems to me to be a bigger issue after the introduction of the structure pattern. Especially since it easily facilitates selecting everything in a folder.

I'm unsure of the correct solution. Can this be fixed without storing a session server side?

**Comment by tmog** [comment]
I'm setting this to high since the impression users are getting is that Plone fails at the most basic computing task.

**Comment by vincentfretin** [comment]
duplicate of https://github.com/plone/plone.app.content/issues/200
