### ISSUE TITLE
Plone5: Login success page references the user dropdown previously sitting in the top right corner of Plone 4

### ISSUE THREAD

**Issue by neilferreira** [plone/Products.CMFPlone#1842]
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_login/login_success.pt#L29

```
Notice that the top right bar has changed. It now contains several personalized items. Use these items           o control your settings and your personal area. They will remain as long as you are logged in.
```

Top right bar is now sitting at the bottom left

**Comment by gforcada** [comment]
Well actually is configurable, so better not to say where it is, but rather specify what is about so they can find it :-)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
Meanwhile, the login process changed significantly. 
If you think this is wrong please reopen the issue and assign a matching milestone.
