### ISSUE TITLE
Compatibility with ZODB 4 and 5

### ISSUE THREAD

**Issue by davisagli** [plone/Products.CMFPlone#1845]
Tasks identified so far:
- [ ] Pin to ZODB3 3.11.0 which is an empty distribution that requires the new package name, `ZODB`.
- [ ] Update core packages to require `ZODB` instead of `ZODB3`.
- [ ] Use Products.ZCatalog >=3.1.2
- [ ] Use BTrees 4.4.0
- [x] Fix improper `_p_serial` in plone.app.caching tests. Merged: https://github.com/plone/plone.app.caching/pull/31
- [x] Fix doctest in plone.app.redirector. Merged: https://github.com/plone/plone.app.redirector/pull/6
- [ ] ZODB 5 now requires unicode transaction notes (see also https://github.com/zopefoundation/Zope/issues/79)

**Comment by gforcada** [comment]
@davisagli if we can update all BTrees and all the logic to not add ``None``s **before** migrating to BTrees 4.x then it would be much easier then to move to ZODB 4 and 5, right? I'm starting to get used at work to use cleanup upgrades before actually upgrading to newer versions of Plone and it feels much more cleaner, it's a two steps process, but you don't have to keep all the deprecated stuff around when you are on the new version.

If we could run that script you are working on before updating the ZODB it would be easier.

**Comment by davisagli** [comment]
@gforcada true, though I suspect it's easier to make BTrees handle this than to retrain the entire community to do upgrades differently.

**Comment by davisagli** [comment]
Jim released BTrees 4.4.0 which restores support for using `None` as a key in BTrees!

**Comment by pbauer** [comment]
The PLIP #1351 now runs on ZODB 5 and ZCatalog 4
