### ISSUE TITLE
lead image looks wonky when clicked on

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1847]
The lead image behaviour lets you click on a content item's lead image, displaying it in a JavaScript popup with a white background, but the white background doesn't necessarily fit the image, and the popup's title is not helpful ("Image").

e.g. click on the lead image in https://plone.org/events/plone-open-garden-in-sorrento-italy-2017 and you see

![screen shot 2016-11-22 at 7 34 01 pm](https://cloud.githubusercontent.com/assets/815418/20548614/a5ef3da4-b0ea-11e6-85eb-8c2620357439.jpg)

**Comment by hvelarde** [comment]
which Plone version? which plone.app.contentypes version?

**Comment by tkimnguyen** [comment]
Sorry, Plone 5.1a1, plone.app.contenttypes 1.2.11.

**Comment by A7xSV** [comment]
Can I try fixing this ?
I do have an idea.

**Comment by gforcada** [comment]
@A7xSV go for it! Do you need pointers? On the IRC there will be probably quite some people around to help you

**Comment by A7xSV** [comment]
Alright !
I've fixed both the pop-up title and fit the image properly, I did that by adding a class and other edits in the html file of https://plone.org/events/plone-open-garden-in-sorrento-italy-2017 in Chrome developer tools.
How do I implement these changes as I can't find the html file in the repository ? I am supposed to fork, change and submit the pull request right ?

**Comment by Dnouv** [comment]
Hello @tkimnguyen 
Is this issue still available to work? If it is, please let me know, I would like to work on this.
Thank you!

**Comment by jensens** [comment]
In Plone 6 this is handled different and works.
I close the issue.
If you think this is wrong please reopen the issue and assign a matching milestone.
