### ISSUE TITLE
Password reset link is instantly invalid

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1849]
Even after manually running the upgrade step from https://github.com/plone/Products.CMFPlone/commit/fbbc911e9e8566e33d7bc17ef1a0b4bb6e6a4aad the password reset link says (This link is valid for 0 hours)

Something missing with the upgrade step?
@tomgross got an idea?

**Comment by tomgross** [comment]
The storage changed from DateTime to datetime. Old links might not work after upgrade.

**Comment by agitator** [comment]
Old links? Using only fresh password reset mails ;-)
