### ISSUE TITLE
fix lingering links to plone.org/upgrade ?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1853]
In Gitter @mjschuh reported running into an upgrade error and found a link (perhaps on the upgrade page or in our code docs) to https://plone.org/upgrade, which until now was giving a 404 since we had not moved that page from old.plone.org. 

```
I tried going to https://plone.org/upgrade and the page does not exist.
This was linked to at the top of the 8080/Main/@@plone-upgrade page.
```

I've created a Link in plone.org so that https://plone.org/upgrade now points to http://docs.plone.org/manage/upgrading/index.html.

It could be that that Link is good enough and will give us flexibility to change the final destination page in future as needed.

Otherwise we should go through the code and change plone.org/upgrade links

**Comment by gforcada** [comment]
I asked for that some months ago: https://github.com/plone/ploneorg.core/issues/199 I guess we can close both  this and that one now :-)
