### ISSUE TITLE
Badly placed arrows in In-Out-Widget

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1855]
See screenshot

with Plone 5.1b2...I think this had been reported and fixed a while ago for Plone 5.0 (but I can not find the related
ticket anymore).

**Comment by zopyx** [comment]
![screenshot-localhost 8086-2016-11-28-11-13-25](https://cloud.githubusercontent.com/assets/594239/20664508/d9342c68-b55b-11e6-8e7f-5decbc6fcdb2.png)

**Comment by ale-rt** [comment]
@zopyx You may want to pin barceloneta to 1.6.22.

The PR that fixes the issue should be plonetheme.barceloneta#115. Let me know if it does not.

**Comment by zopyx** [comment]
Fixed in 1.6.22
