### ISSUE TITLE
User creation aborted on SMTPAuthenticationError

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1856]
Plone 4.3.11 with zope.sendmail 3.7.5; when you are trying to create an error and the email configuration is invalid, the following exeption is rose and user creation is aborted in the middle:

```python
2016-11-29T17:10:04 ERROR MailDataManager (535, '5.7.8 Error: authentication failed: authentication failure')
Traceback (most recent call last):
  File "/home/example/eggs/Products.CMFPlone-4.3.11-py2.7.egg/Products/CMFPlone/patches/sendmail.py", line 12, in _catch
    return func(*args, **kwargs)
  File "/home/example/eggs/zope.sendmail-3.7.5-py2.7.egg/zope/sendmail/mailer.py", line 72, in send
    connection.login(username, password)
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Error: authentication failed: authentication failure')
```

should we upgrade to newer zope.sendmail 4.1.0 in Plone?

**Comment by davisagli** [comment]
What's the bug here? It seems right to me that the transaction is aborted when there's an error. You should fix your email configuration.

**Comment by hvelarde** [comment]
what I was expecting is the user being created successfully and a status message telling me the email configuration was incorrect and the password was not emailed to the user.

the bug is that the process is interrupted, the user is half-created and is not usable, and I'm not being able of change the password by hand.

**Comment by mauritsvanrees** [comment]
If we don't do this, this leads to two bad things:

1. Hackers can fill in random, non existing email addresses and create accounts for them. Useless and annoying.
2. Innocent users fill in their valid email address but with a typo and can never get into their account.

There should *not* be half-created users though. Are you sure about that? How do you see that? Are they maybe visible in `acl_users` but not in the Plone UI?
If that is the case, then we may need to do an explicit `transaction.abort()`.

**Comment by hvelarde** [comment]
I was able to see the user in the control panel configlet, but I was not able to remove it or assign it to any group; I was neither able to recover the password as the form was telling me that the user didn't exist; it was very weird.

I'm not able to test again as we have fixed the configuration of the production server; I think this can be simulated on a test.

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 4.3 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
