### ISSUE TITLE
Improper URLs generated in Plone 5.1a2 containing ++plone++production/++unique++2016-12-04T18:31:03.170090/++plone++static

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1862]
My CSS file in my registry.xml 

https://github.com/xml-director/xmldirector.demo/blob/master/xmldirector/demo/profiles/default/registry.xml

is referenced as 

https://demo.xml-director.info/xml-director/++plone++production/++unique++2016-12-04T18:31:03.170090/++plone++static/++resource++xmldirector.demo/xmldirector.png

which leads to a 404 error with Plone 5.1a2)

Related (and seen earlier with Plone 5.0):

https://community.plone.org/t/improper-resource-urls-generated-in-plone-5-0-5/2426

**Comment by djay** [comment]
Isn't this the same as https://github.com/plone/Products.CMFPlone/issues/1663 ?
