### ISSUE TITLE
Removing any standard entries from the site registration form crashes the site.

### ISSUE THREAD

**Issue by rileydog** [plone/Products.CMFPlone#1864]
in the registration form, removing any of the standard entries crashes the site. 

ould be mitigated with simple admonition, not to remove the greyed out boxes. Best solution, don't allow them to be deleted.

**Comment by jensens** [comment]
Works in Plone 6 
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
