### ISSUE TITLE
TTW compile of resources is broken

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1867]
Tried out https://training.plone.org/5/ttw/basic.html#customize-css-less-variables with a customer...

- activate dev mode of resource registry
- develop css on plone bundle
- changing linkcolor within less variables
- looks "good"
- build plone bundle ttw
- deactivate dev mode
- no change visible
- icon font is not working anymore

**Comment by jensens** [comment]
does this overlap with #1862 and #1863?

**Comment by agitator** [comment]
sorry was 5.1a2

**Comment by djay** [comment]
Actually I think its the same as https://github.com/plone/Products.CMFPlone/issues/1663
