### ISSUE TITLE
Cut/Copy and Paste from contents: ordering isn't preserved

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1875]
When cutting or copying contents and pasting them somewhere, the original ordering from their originating container isn't preserved. They are inserted into the new container in arbitrary ordering.

**Comment by rnixx** [comment]
On Zope level, copying and pasting is just an export/import to a temp file. The order of items is stored in getObjPosInParent index IIRC. The index data of the source folder(s) needs to be transferred somehow then. This also raises the question if exporting/importing as ZEXP via ZMI also loses ordering

**Comment by jensens** [comment]
Maybe we can recreate the order by using a subscriber before and after paste. Before read order, annotate to request, after reorder pasted items.

**Comment by thet** [comment]
That was actually a problem in plone.app.content, where selected items are retrieved by a catalog call, which is passed a list of UUIDs. The order is then not preserved. I fixed that for copying items.

The order is kept for items in folder when the folder itself is copied. That is because the sort order is actually defined as annotation on the folder itself.
