### ISSUE TITLE
'LeadImage' object has no attribute 'image'

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1877]
For Plone 5.0.6, the RSS feed invokes the code in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/syndication/adapters.py#L287 where the expression 'lead.image' causes the error "'LeadImage' object has no attribute 'image'"

Should that be wrapped in a try block?

https://sentry.io/share/issue/3132333138332e313935313137303333/

**Comment by hvelarde** [comment]
nop, that seems another issue; the code looks fine.

**Comment by tkimnguyen** [comment]
@hvelarde I haven't seen the issue come up again (thanks, Sentry!) but don't you think any reading or setting of a bare attribute should be protected/checked?

**Comment by hvelarde** [comment]
in this specific case, I don't think so as the lead image behaviour should have an image attribute.

**Comment by tkimnguyen** [comment]
ok thx!
