### ISSUE TITLE
Invalid breadcrumbs URL if folderish content is in types_use_view_action_in_listings

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#1878]
Reproduced on 5.0.6. Breadcrumbs viewlet do not support folderish item to be in `plone.types_use_view_action_in_listings` property. Issue is not in viewlet itself but came from `@@breadcrumbs_view` view.

How to reproduce:

* add `Folder` (or another folderish content type) in the plone.types_use_view_action_in_listings
* create this folderish type in the site root (*/Plone/level-1*)
* create another folderish inside it (*/Plone/level-1/level-2*)
* note that breadcrums link to `level-1` is `http://.../level-1/view` (it's ok)
* create another content inside `level-2` (*/Plone/level-1/level-2/document*)
* **error**: breadcrums link to `level-2` is `http://.../level-1/view/level-2...`

In brief: the logic that adds `/view` suffix to an item should be applied only in the last item of the set.

See https://github.com/plone/Products.CMFPlone/blob/c6be5d373ee0508741dc04a6a1fa7db17d23bbcb/Products/CMFPlone/browser/navigation.py#L48

**Comment by keul** [comment]
CC @gforcada

**Comment by hvelarde** [comment]
which Plone version?

**Comment by keul** [comment]
@hvelarde tested on 5.0.6

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
