### ISSUE TITLE
ContactForm class is not extensible.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#1879]
The ContactForm class does not inherit from AutoExtensibleForm, this makes it impossible to extend the form (e.g. with a recaptcha field for https://github.com/collective/collective.recaptchacontactform).

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/contact_info.py#L21

We should go through all forms in Plone and make sure they are extensible. It would be nice if we could write some docs on how to extend those forms.

**Comment by tkimnguyen** [comment]
@tisto I'm looking over release notes for Plone 5.1 and am wondering if it's documented anywhere how to extend the new contact form

**Comment by davisagli** [comment]
Forms can be extended without touching the built-in form class using a feature of plone.z3cform called "form extenders": https://pypi.python.org/pypi/plone.z3cform#fieldsets-and-form-extenders

The docs for plone.app.discussion show how this can be used to add CAPTCHA to the comment form; adding it to the contact form would be similar. https://pythonhosted.org/plone.app.discussion/captcha.html
