### ISSUE TITLE
unittest2

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1882]
We're using ``unittest2`` in many packages:

1) we do not need it in packages targetting python 2.7 or 3 only.
2) we do not declare it in several setup.py's as test dependency if Python 2.6 is target.

Action needed! Remove or Declare in:

- [x] archetypes.multilingual
- [x] five.pt
- [x] plone.app.caching
- [x] plone.app.collection
- [x] plone.app.content
- [x] plone.app.contentlisting
- [x] plone.app.contenttypes
- [x] plone.app.debugtoolbar
- [x] plone.app.discussion
- [x] plone.app.intid
- [x] plone.app.iterate
- [x] plone.app.linkintegrity
- [x] plone.app.multilingual
- [x] plone.app.openid
- [x] plone.app.portlets
- [x] plone.app.querystring
- [x] plone.app.redirector
- [x] plone.app.registry
- [x] plone.app.relationfield
- [x] plone.app.testing
- [x] plone.app.theming
- [x] plone.app.uuid
- [x] plone.app.vocabularies
- [x] plone.autoform
- [x] plone.openid See https://github.com/plone/plone.openid/pull/8
- [x] plone.outputfilters
- [x] plone.portlet.collection
- [x] plone.portlet.static
- [x] plone.protect
- [x] plone.resource (declared)
- [x] plone.resourceeditor
- [x] plone.subrequest
- [x] plone.theme
- [x] plone.transformchain
- [x] Products.CMFPlone (removed)

**Comment by hvelarde** [comment]
do you have information on which packages are still being used in Python 2.6? are we properly using trove classifiers?

**Comment by jensens** [comment]
I would double check. Iirc @mauritsvanrees did a great job of adding classifiers, I am just not sure if it's been complete. 

So I would check the sources.cfg of buildout.coredev 4.3 branch as well.

**Comment by mauritsvanrees** [comment]
I have added the trove classifiers a while ago. It could be that some have gotten out of sync. Best place to check is indeed [coredev 4.3 sources.cfg](https://github.com/plone/buildout.coredev/blob/4.3/sources.cfg).

**Comment by mauritsvanrees** [comment]
For reference, these are the extra functions in `unittest2` and in the `unittest` of Python 2.7 that are not in Python 2.6 (ignoring some underscore methods):

```
addCleanup
addTypeEqualityFunc
assertDictContainsSubset
assertDictEqual
assertGreater
assertGreaterEqual
assertIn
assertIs
assertIsInstance
assertIsNone
assertIsNot
assertIsNotNone
assertItemsEqual
assertLess
assertLessEqual
assertListEqual
assertMultiLineEqual
assertNotIn
assertNotIsInstance
assertNotRegexpMatches
assertRaisesRegexp
assertRegexpMatches
assertSequenceEqual
assertSetEqual
assertTupleEqual
doCleanups
longMessage
maxDiff
setUpClass
skipTest
tearDownClass
```

So if a package is not using any of those, we can remove the `unittest2` dependency.
And if the `master` branch of a package is not used on Plone 4.3, we can remove the dependency as well.

**Comment by tomgross** [comment]
Some packages include the dependency only for Python 2.6 (like diazo -> https://github.com/plone/diazo/blob/master/setup.py). I guess this is a good aproach for shared packages Plone 4.3 and 5.0

**Comment by gforcada** [comment]
@tomgross that's quite handy indeed, I would rather use this approach on all other packages as well, so we are sure that we are not pulling unittest2 from 2.7 onwards.

Still low hanging fruit, perfect for newcomers or when you have some hours to kill :-)

**Comment by kakshay21** [comment]
Can I do this? @gforcada @jensens

**Comment by jensens** [comment]
@kakshay21 sure, this would be great! Do you need any directions?

**Comment by gforcada** [comment]
@kakshay21 yes please! Let us know if you have problems, either here or on community.plone.org. Go go go!

**Comment by kakshay21** [comment]
Can i go little slowly on this one??
Actually, I'm in the middle of my semester end exams. But I really want to do this.
@jensens @gforcada

**Comment by gforcada** [comment]
@kakshay21 you can go as fast or as slow as you wish, one pull request at a time is the best thing to do 👍

**Comment by jensens** [comment]
So many already are done! A big thanks @kakshay21

**Comment by kakshay21** [comment]
Appreciate your help @jensens @gforcada

**Comment by kakshay21** [comment]
I'm not able to find any repository with name "plone.portlet" neither mr.developer
```mr.developer: The package 'plone.portlet' from auto-checkout has no source information.```
@jensens @gforcada

**Comment by mauritsvanrees** [comment]
We do have `plone.portlets`, but that does not use `unittest2` at all.
Ah, I see that `plone.portlet.collection` and `plone.portlet.static` use `unittest2`. I have updated the original list with them.

**Comment by kakshay21** [comment]
thanks! @mauritsvanrees

**Comment by kakshay21** [comment]
is there something wrong with naming ```plone.theme.tests``` ?
I'm not able to find this repo

**Comment by kakshay21** [comment]
Seems like Plone is free from unittest2

**Comment by mauritsvanrees** [comment]
`plone.theme.tests` would be the `plone.theme` package. I indeed see unittest2 in there.

**Comment by kakshay21** [comment]
Do we have to fix these too? 
https://github.com/search?q=org%3Aplone+unittest2&type=Code

**Comment by jensens** [comment]
I think, yeah! Now it is unittest2 free! 

Last task: remove trace/dependencies of unittest2 from buildout.coredev *.cfg files!

**Comment by mauritsvanrees** [comment]
Great work!
I see plone.formwidget.contenttree and plone.formwidget.datetime that still require unittest2 unconditionally. Well, they are not in the `sources.cfg` of Plone 5.1, so that may be fine.

Apart from those, when I grep through the 5.1 code, I still see real use of unittest2 in:
- plone.app.contentlisting
- plone.app.debugtoolbar
- plone.openid
- plone.resource

Of these, `plone.app.debugtoolbar` was missing from the original list. The other three are in there and have a checkbox claiming they have been fixed. I have updated the list to reflect the current situation.

**Comment by kakshay21** [comment]
unittest2 is only mentioned in this file.
https://github.com/plone/buildout.coredev/blob/5.1/tests.cfg
there is no master branch so do i have to make only in changes in 5.0 and 5.1 branches? 
or all of them?

**Comment by jensens** [comment]
only in 5.1 
at https://github.com/plone/buildout.coredev/blob/5.1/tests.cfg#L200-L213 there are also versions comments giving hints which packages need to get removed from version pins as well.

**Comment by gforcada** [comment]
@kakshay21 on plone.openid there is still an import for it, but as it is no longer part of plone core (not used in 5.1 nor in 5.2) it can be safely ignored. On the others you are right, there were some pull requests a few weeks/months ago that cleaned them up.

**Comment by jensens** [comment]
Great work! Thanks our get-rid-of-unittest2-hero @kakshay21 and all others who helped to make it happen!
