### ISSUE TITLE
Contact form in overlay does not show info message after successful submit

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#1886]
Steps to reproduce:

1) Create vanilla Plone 5.0.6 site
2) Set up basic mail settings
3) Click on "Contact" on any page
4) Fill out contact form in overlay
=> Overlay closes without showing the user any feedback at all.

Contact form works fine without the overlay. Therefore this might be a general issues with overlays.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
