### ISSUE TITLE
AccessInactivePortalContent for local assigned roles doesn't work

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#189]
the CatalogTool.searchResults method checks AccessInactivePortalContent on "self" ... this is only true for global/site wide user roles and not locally assigned ones, so a local editor cannot see his own outdated/future articles ... see also https://dev.plone.org/ticket/8353

**Comment by jensens** [comment]
This would be difficult to fix. 

One would need to check for each path-location of an result brain if the current user has permission to AccessInactivePortalContent there. 

I dont think we want to fix this.

**Comment by jensens** [comment]
fixed with #1952
