### ISSUE TITLE
PLIP Issuetemplate service not available

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1891]
For our PLIP issues, we relied on the issuetemplate.com service. Apparently, this service was taken offline. We still reference it here: http://docs.plone.org/develop/coredev/docs/plips.html#how-submit-plip

Github now offers issue template itself: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

We have to create a new issue template for PLIP submissions.

@plone/framework-team

**Comment by thet** [comment]
That might be a good example for restoring all necessary fields: https://github.com/plone/Products.CMFPlone/issues/1343

**Comment by jensens** [comment]
Proposal  for an issue/plip template at #1893
