### ISSUE TITLE
Cannot select all items when managing group-membership

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#1892]
In Plone 5 two templates that manage group-membership still use the removed js-method `toggleSelect` that used to select all items. Now it does nothing and throws `toggleSelect is not defined`.

See http://demo.plone.de/@@usergroup-groupmembership?groupname=Reviewers and http://demo.plone.de/@@usergroup-usermembership?userid=editorinchief 
It is also in http://demo.plone.de/de/test_rendering

**Comment by marncz** [comment]
I'd like to work on this issue

**Comment by envy7** [comment]
This seems can I work on this, I will check in all the template files and remove the onclick listener calling toggleSelect.

**Comment by envy7** [comment]
found it in three files test_rendering.pt, usergroups_groupmembership.pt and usergroups_usermembership.pt

**Comment by cewing** [comment]
@envy7, it sounds like you've found the right places.  Do you have any questions on how to proceed from here?

**Comment by envy7** [comment]
@cewing So, Do I just remove the onclick listeners, or do we need to replace it with a newly written method, cause after deleting it, the checkbox that selects all items will be quite useless.

**Comment by cewing** [comment]
@envy7 I would replace it with something else.  I am not familiar with the javascript layer we have available at this time.  Perhaps @pbauer, or @vangheem or @datakurre or another person with more familiarity might be able to weigh in on the new approach to this.  In the absence of additional help, you can also take a look at the folder contents view, which has a `select-all` checkbox.  Perhaps there is a globally available javascript handler there you can make use of?

**Comment by envy7** [comment]
@cewing okay I'll check the code thanks for the info

**Comment by envy7** [comment]
I checked the code, the selectAll function in plone-logged-in-complied.min.js is responsible for it, and the the checkbox has a class of .select-all and when there is a change in the checkbox the selectAll function is called, but I think this function is defined for a table template, but I really don't know how to use this function in test_rendering.pt, usergroups_groupmembership.pt and usergroups_usermembership.pt

**Comment by envy7** [comment]
@pbauer @vangheem @datakurre could you help me with this?

**Comment by tulikavijay** [comment]
I would like to work on this if no one is.

**Comment by tulikavijay** [comment]
@cewing @pbauer  @vangheem  @datakurre  In plone-logged-in-complied.min.js theres the function -
`toggleSelectAll` and `selectAll`. And according to this guide, how should i proceed : 
[JavaScript styleguide - Custom events](https://docs.plone.org/develop/styleguide/javascript.html#custom-events)

**Comment by pbauer** [comment]
This is still not working in Plone 6

**Comment by davisagli** [comment]
Fixed for Plone 6 in #3746
