### ISSUE TITLE
Image is lost on DX add form, if validation error occurs

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1895]
### What I did:

- Create a content type with an image field and any other required field.
- Create a content object with the new type
- Add an image but leave the required field blank
- Submit the form
-> The form will show up with validaton errors but no image
- fill the required fields
- submit the form
-> The image is lost

### What I expect to happen:

An image should be taken over in the DX add form, if validation errors occur.

### What actually happened:

The image is lost

### What version of Plone/ Addons I am using:

- 5.0.6
- buildout.coredev (5.1a2)

**Comment by tomgross** [comment]
First issue with new template 🎉 . Good work!

**Comment by hvelarde** [comment]
maybe related with https://github.com/plone/plone.namedfile/issues/38

**Comment by thet** [comment]
If so, this should be fixed via:
https://github.com/plone/plone.namedfile/pull/41
and
https://github.com/plone/plone.namedfile/pull/45
