### ISSUE TITLE
"(" Breaks collections

### ISSUE THREAD

**Issue by mr-rob** [plone/Products.CMFPlone#1900]
### What I did:
- Click Add new... -> Collection
- Search terms: "Title" "Contains" "sites (test)"
- Click Save

### What I expect to happen:
- Get a working collection

### What actually happened:
- Traceback `ParseError: Token 'EOF' required, u'(' found`

### What version of Plone/ Addons I am using:
- Plone 5.0.6 (minimalplone5)
- buildout.coredev (branch 5.1)

Full Traceback: https://gist.github.com/mr-rob/a0e0e0cdaf1cecc54674978cef664508

**Comment by hvelarde** [comment]
duplicated with #1537; follow https://github.com/zopefoundation/Products.ZCTextIndex/issues/2 instead.
