### ISSUE TITLE
Navigation portlet indentation level is fixed after 1st nesting level

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1906]
### What I did:

1. Create at least two folders, one inside the other, and a leaf item in the innermost folder, e.g.: `/Members/jblow12345/2017/q1/1st-q-2017-statement-12345.pdf`
2. Navigate to the leaf item (the file `1st-q-2017-statement-12345.pdf`, in my example)

### What I expect to happen:

The navigation portlet should indent each successive level of nesting further to the right, or otherwise indicate the nesting structure, perhaps with successively smaller fonts (just an example).

### What actually happened:

After the first level of nesting, all further levels have the exact same indentation, and look like they are all elements of the first level folder.

### What version of Plone/ Addons I am using:

Plone 5.0.6

### Screenshot

The following screenshot shows the navigation portlet when I'm on `/Members/jblow12345/2017/q1/1st-q-2017-statement-12345.pdf/view`:

![1st q 2017 statement 12345 pdf](https://cloud.githubusercontent.com/assets/460742/21918523/5d6c8c9c-d90f-11e6-9a97-766ac79dba81.png)

**Comment by MrTango** [comment]
This is still the case in current 5.1.3 release.

![plone-nested-folders-indention-bug](https://user-images.githubusercontent.com/1113628/42449429-f5d41ab4-8380-11e8-83a8-0b98a8121665.png)

**Comment by petschki** [comment]
anybody willing to review my fix here https://github.com/plone/plonetheme.barceloneta/pull/156 ?
