### ISSUE TITLE
Inline validation problems

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1914]
### What I did:

- Created an event: http://localhost:8080/Plone/++add++Event

- Deleted start time:

![image001](https://cloud.githubusercontent.com/assets/170891/22126855/af36d9a8-de99-11e6-84c3-91d1825fa7e4.png)

 -  Changed the start date:

![image002](https://cloud.githubusercontent.com/assets/170891/22126866/c1ce3214-de99-11e6-967e-0b9269ebf6c0.png)

### What I expect to happen:

- Since in current buildout.coredev 5.1 and 5.0, the start time is automatically set when a start date is set and the time was empty.

-  No validation error should have happened.

### What actually happened:

- A validation error happenend: "Required input is missing."

### What version of Plone/ Addons I am using:

- buildout.coredev 5.1 from 2017-01-19

### More detailed investigation of the problem

- The pickadate pattern hides the original HTML input field (having the class "pat-pickadate" applied) and replaces it with two HTML inputs - one for date and one for time.

- The inline validation is also a pattern and is set on the field wrapper div with the CSS class "pat-inlinevalidation".

- Inside this class, there are now 3 HTML inputs, one of them being hidden.

- The inlinevalidation pattern listens on ``blur`` events for any input within it's scope, so all 3 HTML inputs.

- When the date on the date input is set, the inline validation is already doing it's job - but there is a good chance, that the input is incomplete (no time set or time was cleared) - this leads to false positives when validating the input.

### Proposal for a better solution

- pat-inlinevalidation should be set on the original input field directly.

- Any value updates have to be written to this input field anyways, otherwise form submission won't work.

- pat-inlinevalidation should listen to the ``changed`` event on the original input widget.

- On the ``submit`` event of the form, a inline validation step should be done. The submit action should be canceled, if the inline validation fails.

### Risks

- When visiting a required, but empty field and leaving it again without changing a value, no inline validation error will occur - as the changed event isn't thrown. But this is actually a win, as I personally felt the inline validation when jumping through fields in the form a bit annoying.

### References

- Inline validation pattern and registering a callback for the ``blur`` event on input fields: https://github.com/plone/mockup/blob/master/mockup/patterns/inlinevalidation/pattern.js#L118

- Where ``pat-inlinevalidation`` is set on the wrapper-div. One out of some templates: https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/templates/widget.pt#L12

- Where the plone.app.z3cform base widget calls the render method of the plone.app.widget base widget: https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/widget.py#L106

- Where the ``pat-inlinevalidation`` CSS class could possibly set to be directly on the original input field: https://github.com/plone/plone.app.widgets/blob/master/plone/app/widgets/base.py#L94

/cc @tomgross @plone/framework-team

**Comment by jensens** [comment]
I agree to change it as proposed in order to fix the bug!

**Comment by hvelarde** [comment]
here's good reading on [Date-Input Form Fields: UX Design Guidelines](https://www.nngroup.com/articles/date-input/).

**Comment by thet** [comment]
Not applicable for Plone 6. We're using pat-validation from Patternslib and browser's native date/time input fields. If there is still a problem it's a different one.
