### ISSUE TITLE
Remove icon label column, in ZMI

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#1926]
after the icons in the ZMI are removed, we still have the label column there, which doesn't make sense.
http://localhost:8080/Plone/manage_main
We should remove this column too.

**Comment by mrsaicharan1** [comment]
I'd like to look into this issue. BTW, are you referring to the **NAME** column present at that url when the site is up and running? If I'm wrong, which is the expected column to be removed?

**Comment by jensens** [comment]
Still an issue with the new bootstrap based ZMI?

**Comment by pbauer** [comment]
This issue is obsolete with the new ZMI. See http://demo-latest-py3.plone.de/manage
