### ISSUE TITLE
Alternative for removed Undo-Tab in ZMI?

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#1927]
Since the Undo-Tab in ZMI was removed, we should have an alternative to use undo in Plone, at least for managers.

**Comment by mauritsvanrees** [comment]
Apparently it has moved to the root Zope control panel at http://localhost:8080/Control_Panel/Database/main/manage_UndoForm

**Comment by MrTango** [comment]
I thing we need one as a controlpanel for manager.

**Comment by NicolasGoeddel** [comment]
Oh, it would be really nice if the undo form would be available somewhere in @@overview-controlpanel

**Comment by icemac** [comment]
The Undo-Tab has been restored in newer Zope versions.

**Comment by jensens** [comment]
This is done and can be closed, right? 
If you disagree please reopen and go on.
