### ISSUE TITLE
Excluding an user takes too long

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1942]
I have a site with hundreds of users belonging to a group and I want to exclude one; I'm using an intermediate proxy (Cloudflare).

### What I did:

I accessed https://www.example.com/@@usergroup-userprefs, looked for the user and tried to exclude it.

### What I expect to happen:

The user must be excluded.

### What actually happened:

A timeout screen was shown in the intermediate proxy and the user was not excluded.

### What version of Plone/ Addons I am using:

Plone 4.3.11.

**Comment by mauritsvanrees** [comment]
Just checking if I understand it correctly. With 'excluding' a user you mean removing him or her from the group?

So you are saying that going to the group and removing a user there takes far longer than going to a user and removing the group?

Obligatory question: is this site using LDAP?

**Comment by hvelarde** [comment]
my mistake, @mauritsvanrees; in fact you're right and I was just removing the user from the group and not the user from Plone; more information:

* we have around 1100 users in this site and we're not using LDAP at all
* retrieving the whole list of users in this group takes around 14 seconds
* removing the user from Plone takes around 340 seconds
* site is already configured as having too much users

**Comment by hvelarde** [comment]
more information: IIRC, the only different thing from a vanilla Plone is we have an adapter that adds a new field to all users.

**Comment by mauritsvanrees** [comment]
- Getting the list of users for that group should not take 14 seconds. That surprises me.
- Removing a user from Plone: ah, that is a different story. Yes, this can take a very long time: Plone goes through the entire site to remove any local roles for this user. If you have a big site, this can take very long.

**Comment by hvelarde** [comment]
those users don't have any local roles; is there any way to speed up the process?

**Comment by mauritsvanrees** [comment]
I knew I had answered roughly the same question a while ago somewhere. So I searched and came up with this [community post by you](https://community.plone.org/t/alternate-way-do-delete-users/3009). :-)

**Comment by hvelarde** [comment]
holy cow! I'm getting old ;-)
