### ISSUE TITLE
Footer not stick on bottom in Large screens

### ISSUE THREAD

**Issue by itaditya** [plone/Products.CMFPlone#1943]
### What I did:
Go to [Plone Login](http://demo.plone.de/acl_users/credentials_cookie_auth/require_login?came_from=http%3A//demo.plone.de/%40%40usergroup-groupmembership%3Fgroupname%3DReviewers) . Then go Fullscreen .

### What I expect to happen:
The footer should have stuck to the bottom
### What actually happened:
The footer didn't stuck at the bottom
![plone](https://cloud.githubusercontent.com/assets/15871340/22683402/ca46b30a-ed3d-11e6-8238-f3204dce04fe.png)

### What version of Plone/ Addons I am using:
The latest version

**Comment by hvelarde** [comment]
please specify clearly which Plone version you're using; if your issue sits too long we'll not know what was "latest version" at the time you opened it.

**Comment by imjog** [comment]
this is not an issue now. please close it. thanks
