### ISSUE TITLE
User Search in Site Setup breaks

### ISSUE THREAD

**Issue by pe82** [plone/Products.CMFPlone#1946]
## BUG/PROBLEM REPORT
Searching for user in @@usergroup-userprefs throws an error while searching for the same user in @@sharing proceeds fine.

### What I did:

Went to @@usergroup-userprefs to search for a user, entered the username in User Search and clicked on Search.

### What I expect to happen:
Expected to get a user in grid and permissions

### What actually happened:
Threw an error:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.usergroups_usersoverview, line 44, in __call__
  Module Products.CMFPlone.controlpanel.browser.usergroups_usersoverview, line 77, in doSearch
TypeError: 'NoneType' object is not iterable

### What version of Plone/ Addons I am using:
Plone 5.0.6 (5016)
CMF 2.2.10
Zope 2.13.24
Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
PIL 3.3.0 (Pillow)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
