### ISSUE TITLE
DateTimeWidget new buttons wrong aligned

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1953]
![screenshot from 2017-02-24 16 54 52](https://cloud.githubusercontent.com/assets/157140/23310204/01abc26e-fab2-11e6-83a1-88752b5c7ca3.png)

**Comment by nikandroff** [comment]
Is it still an open issue? Or was it fixed by @jensens at https://github.com/plone/mockup/pull/744

**Comment by jensens** [comment]
@nikandroff indeed this was fixed by merging of this PR.
