### ISSUE TITLE
Links outside the content area are marked with icons

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1966]
### What I did:

I installed sc.social.like, and add-on that displays a viewlet with social widgets under Plone 5.1; the viewlet is registered in the `IBelowContentTitle` viewlet manager.

### What I expect to happen:

Normal behavior as in Plone 4.3.

### What actually happened:

An icon showing a secure link (a lock) is now shown in some of the widgets:

![selection_017](https://cloud.githubusercontent.com/assets/341393/23769958/ed200966-04ef-11e7-96f6-5debf193d2d4.png)

My guess is the `pat-markspeciallinks` is being applied outside the content area, which is a mistake, IMO.

### What version of Plone/ Addons I am using:

* Plone 5.1a2
* sc.social.like from master branch

**Comment by jensens** [comment]
probably the same as plone/mockup#707

**Comment by hvelarde** [comment]
not the same, but clearly related.

**Comment by mrsaicharan1** [comment]
I'd like to look into this issue. Where can I find pat-markspeciallinks?

**Comment by gforcada** [comment]
@mrsaicharan1 is on the mockup project: https://github.com/plone/mockup/tree/master/mockup/patterns/markspeciallinks

**Comment by vincentfretin** [comment]
see https://github.com/plone/plonetheme.barceloneta/issues/147 too

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
