### ISSUE TITLE
Toolbar menus missing checkmark on some browsers

### ISSUE THREAD

**Issue by michaeldunstan** [plone/Products.CMFPlone#1972]
The toolbar menus are missing checkmarks for selected items when running Plone 5.1b2-pending in Chrome (v56). The menus are also missing the bullet point markers. Here is a screenshot showing the problem with the display menu in Chrome:

![display_menu_in_chrome](https://cloud.githubusercontent.com/assets/360401/24096511/d3399938-0dc6-11e7-8bd5-dcac1b5354dd.png)

And here is a screenshot showing the menu rendering okay in Safari (v10):

![display_menu_in_safari](https://cloud.githubusercontent.com/assets/360401/24096587/1fc67906-0dc7-11e7-899e-60e3081dfb96.png)

My guess is that the problem was introduced in 646b534cbcb13225c861a038f9fcdb5bc9f08f39 where the negation pseudo-class was extended to have two selectors:

`&:not(.plone-toolbar-submenu-header, .plonetoolbar-display-view.actionSeparator)`

As that is not yet widely supported by browsers. See http://stackoverflow.com/questions/35993727/not-selector-not-behaving-the-same-between-safari-and-chrome-firefox

**Comment by gforcada** [comment]
@michaeldunstan hi! It seems you already nailed problem, would you mind providing a pull request to fix it?

**Comment by michaeldunstan** [comment]
Hi @gforcada. I have had a bit of a look at how to resolve this but could do with some guidance.

Would it be okay if the content menu was updated so that it could have more than one `plone-toolbar-submenu-header` entry? (Or should there be strictly one such entry per menu?)

There is a case when the display menu makes use of second level header and separators. That is  when a content item is used as the default view and that content item has several different view options. The goal is to get styling of these separators excluded from the styling or regular menu entries. 

Here is a screen shot of that from Safari which does work with the combined selectors in the negation pseudo-class:

![collection_ _toolbar](https://cloud.githubusercontent.com/assets/360401/24591157/bddf03a6-184e-11e7-9651-15050962e96f.png)

For what I can see the easiest way to get wider browser support for this is to go back to using a simple selector in the CSS like:

`&:not(.plone-toolbar-submenu-header)`

and updating plone.app.contentmenu to add the class `plone-toolbar-submenu-header` to those second level headings. So for that example in the screenshot the display menu would have three elements with the class `plone-toolbar-submenu-header`:

- Display
- Folder display
- Item display

@alecpm as the author of 646b534cbcb13225c861a038f9fcdb5bc9f08f39 do have any thoughts on this?

**Comment by vincentfretin** [comment]
That's true in Plone 5.2.2rc1, it works only on Safari (iPad iOS 13.5.1), it doesn't work on Firefox 78 and Chrome 83 on Ubuntu 18.04.

**Comment by vincentfretin** [comment]
https://github.com/plone/mockup/pull/1003 fixes the issue.
