### ISSUE TITLE
Improving the theme editor experience

### ISSUE THREAD

**Issue by pigeonflight** [plone/Products.CMFPlone#1973]
## Proposal & Implementation
The overall goal is to make it possible for editors of themes to feel comfortable working directly in the theme editor. Specifically, I propose that the following be made possible:

- users should be able to search for files within the theme
    - find in files - they should be able to find a file based on text in the file
    - search by name - they should be able to find a file based on the name of the file

- users should be able to drag and drop files into folders in the theme editor
- users should be able to drag and drop files between folders in the theme
- manifest settings should be configurable from a menu
- help should be displayed in context and not load off site (it may need to be rewritten to be more Plone specific rather than linking to the diazo.org site)

## Deliverables

- new features identified above working
- documentation on how to use the new features
- clean upgrade from the old theme editor to the new theme editor

## Risks

Very little I believe, this is a JS focused improvement.

## Participants

pigeonflight

**Comment by shivamluthra** [comment]
@pigeonflight I would like to see for this issue. Please guide me the files to start with. Thanks

**Comment by pigeonflight** [comment]
@shivamluthra the best place to start is to look at the plone.app.theming package https://github.com/plone/plone.app.theming 
The js resources are provided by the thememapper pattern from mockup/patternslib

see: https://github.com/plone/plone.app.theming/tree/master/src/plone/app/theming/browser/resources
and https://github.com/Patternslib/Patterns
