### ISSUE TITLE
Interal link browser should start from current folder and/or should be customizable

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1974]
### What I did:

1. Edit a page nested in a folder structure
2. Open dialog to insert internal link

### What I expect to happen:

Search / Browsing starts at the folder the current page is located

### What actually happened:

Search / Browsing starts at Root (next NavRoot)
In Plone 4.3 there were two options: Current Folder, Root and it was even custom extendable.

### What version of Plone/ Addons I am using:

5.1b2-pending

**Comment by hvelarde** [comment]
@tomgross an issue can be a **bug** or a **regression**, but not both.

**Comment by hvelarde** [comment]
I just tested and this is a regression from the behavior in Plone 4.3.

**Comment by fgrcon** [comment]
sorry, but  a recurring  **bug**  is a ** regression**  so it could be both :-) ?

**Comment by fgrcon** [comment]
a bug which comes back is still a bug but also a   regression (what makes it worse) , or i am totally wrong ? :-)

**Comment by fulv** [comment]
A regression is a specific class of bug.

**Comment by hvelarde** [comment]
a regression is a bug or a different behavior introduced (or reintroduced) due to a refactor like in this case; it's something that should not happen if we have test for a specific use case.

**Comment by paskyorg** [comment]
I get the same behaviour with Plone 5.0.4. Anyone know if there is a plan to correct it?

**Comment by thet** [comment]
These issue is among others addressed here:


https://github.com/plone/Products.CMFPlone/pull/2055
https://github.com/plone/mockup/pull/765
https://github.com/plone/plone.app.widgets/pull/159
