### ISSUE TITLE
No validation is made on Twitter username

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1981]
### What I did:

I added a `@` char to the Twitter user name in the Social Media configlet.

### What I expect to happen:

An validation error should be shown.

### What actually happened:

I was able to save the invalid user name.

![screen shot 2017-03-28 at 13 41 17](https://cloud.githubusercontent.com/assets/341393/24416789/4ffc193c-13bc-11e7-932b-0ea15d87246b.png)

### What version of Plone/ Addons I am using:

Plone 5.1b2

**Comment by tkimnguyen** [comment]
I think I already added code to strip out extra '@' in those

**Comment by tkimnguyen** [comment]
Hm, maybe it was a dream...

**Comment by tkimnguyen** [comment]
needs to strip extra @ here: https://github.com/plone/plone.app.layout/blob/b34a4366e2308e3882d3238206c85d54d01e3334/plone/app/layout/viewlets/social.py#L55 unless you want to write an upgrade step that checks for them and removes them too

**Comment by hvelarde** [comment]
I think is fine; I'm only adding this because is what the description of the field says.
