### ISSUE TITLE
Inline validation fails on Plone 4.3.12 due to bad base tag

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1982]
### What I did:

- Plone coredev 4.3 or a plain 4.3.12 (or 4.3.13 pending) instance.
- Create a Plone Site.
- Edit the front page.
- Move the cursor out of the title field.

### What I expect to happen:

- Inline validation kicks in, but does not complain.

### What actually happened:

- Inline validation makes the Title field red, but does not show an error.

Alternatively, if you make the Title field empty and move the cursor out of the field, the field also turns red, but does not show an error.

### Analysis

It goes wrong because [`inline_validation.js`](https://github.com/plone/Products.CMFPlone/blob/4.3.12/Products/CMFPlone/skins/plone_ecmascript/inline_validation.js#L45) calls `<base tag url>/at_validate_field`. Since Plone 4.3.12 this means `http://localhost:8080/Plone/front-page/edit/at_validate_field` instead of `http://localhost:8080/Plone/front-page/at_validate_field`. So we actually get the html of the edit page back via ajax, instead of a json response with a possible validation error.

### Options

- Revert the `base` tag fixes from https://github.com/plone/plone.app.layout/pull/87. But that seems a bad idea and will reintroduce other problems. cc @rodfersou who made this change.
- Fix `inline_validation.js` to not use the `base` tag. Or probably: use it, but strip `/edit` from it. Probably: find the right most slash and remove it and anything after it. I worry that there may be corner cases where we should *not* strip anything.

**Comment by rodfersou** [comment]
Something like this would work: https://github.com/collective/collective.liveblog/blob/master/src/collective/liveblog/browser/templates/update.pt#L136-L140

**Comment by mauritsvanrees** [comment]
Pull request made: https://github.com/plone/Products.CMFPlone/pull/1984

**Comment by rodfersou** [comment]
@mauritsvanrees @gforcada we can close this issue?

**Comment by mauritsvanrees** [comment]
Ah, yes we can.
