### ISSUE TITLE
folder_contens: Creator shows uuid when plone.use_uuid_as_userid ist set to True

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1988]
When adding setting ``plone.use_uuid_as_userid`` (via registry or ``@@security-controlpanel``) "Creator" shows the uuid instead a user name / login name.

This is technically correct, but not very informative for users.

Instead, folder contents should show the login name.

In  a current project, I solved it like so:

- new metadata column in ``catalog.xml`` profile: ``<column value="creator_name" />``
- new ``creator_name`` indexer:

```
from plone.dexterity.interfaces import IDexterityContent
from Products.CMFPlone.utils import safe_unicode
import plone.api

@indexer(IDexterityContent)
def default_creator_name_indexer(obj, **kw):
    user = plone.api.user.get(userid=obj.Creator())
    return safe_unicode(user.getUserName())
```

- registered it in ``configure.zcml``:
```
  <adapter
      factory=".content.default_creator_name_indexer"
      name="creator_name"
  />
```

The new ``creator_name`` metadata column can be selected in folder contents columns selection.

I wonder, if we want to get this into core.

/cc @plone/framework-team

**Comment by gforcada** [comment]
IMHO, rather than adding another column, I would add, no matter the ``plone.use_uuid_as_userid``, the username to the Creator column, it does not make much sense to store the UUID there anyway...

**Comment by mauritsvanrees** [comment]
The login name can be changed, where the user id is stable, so I think the `Creator` field of the object and in the catalog should always contain the user id.  You need to be able to for example search for all content created by user, in the UI or in code.

Using the `pas_member` view from `Products.PlonePAS` to show the fullname (or rather `name_or_id`) would be nice, but could be tricky to integrate into the folder contents.

**Comment by thet** [comment]
Stale issue.
