### ISSUE TITLE
Double Shared maxage for Strong caching options for Ruleset: File and image resources

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1989]
### What I did:

- Go to the caching control panel.
- On the Import Settings tab import the 'With caching proxy' settings.
- Go to the 'Detailed settings' tab.
- Locate the 'File and image resources'
- Click ' View/edit/clear per-ruleset parameters '

### What I expect to happen:

- I expect a field for maximum age and a field for Shared maximum age.

### What actually happened:

- I see two fields for Shared maximum age. At least, the title and description for the two fields are the same. See screen shot.  When I check the html, the first one is for maxage and the second one for s-maxage.

![screen shot 2017-03-31 at 16 28 14](https://cloud.githubusercontent.com/assets/210587/24555140/4e47c994-1630-11e7-9cfe-d783b6b8fd0f.png)

### What version of Plone/ Addons I am using:

This is in Plone 4.3, 5.0, 5.1 with `plone.app.caching`.

### Analysis

In the configuration registry, the `plone.app.caching.strongCaching.plone.resource.maxage` has the wrong title and description:

![screen shot 2017-03-31 at 16 26 57](https://cloud.githubusercontent.com/assets/210587/24555180/7b1f95fa-1630-11e7-82f3-0823321068ba.png)

The error is in these lines in the [`with-caching-proxy` profile](https://github.com/plone/plone.app.caching/blob/1.2.16/plone/app/caching/profiles/with-caching-proxy/registry.xml#L83-L87). This has been in there since six years, version 1.0b2.

The code works fine, it just shows a wrong title and description, which is confusing.

### Solution

- [x] Fix the profile. We just need to remove one character. :-)
- [ ] See if we can fix existing installs. `plone.app.caching.strongCaching.plone.resource.maxage` is not always there, so we cannot just add a `registry.xml` in `plone.app.upgrade`. But should be doable.

I will have a go at this.

cc @jladage

**Comment by pgrunewald** [comment]
In the changelog of Plone 4.3.15 says, that this ticket has been fixed. But apparently it's not the case when looking at the status of this ticket. Any reasons why it is that?

**Comment by mauritsvanrees** [comment]
Forgot to close it I guess.
Let me check to be sure.
Core problem fixed in plone.app.caching 1.1.12 (Plone 4.3.15 and higher) 1.2.17 (Plone 5.0.8 and higher, Plone 5.1).
Upgrade step for fixing existing installations done in plone.app.upgrade 1.4.2 (Plone 4.3.15 and higher) and 2.0.3 (Plone 5.0.8 and higher, Plone 5.1).
So yes, it is fixed in Plone 4.3.15.
I will close the issue now.
