### ISSUE TITLE
xhtml_compress in plone memoize is useless as slimmer is not installed

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1990]
`xhtml_compress` is used in portlet rendering since immemorial times.

I reviewed the code of it and arrived to the conclusion that is currently useless as none of the current versions of Plone have a dependency on [slimmer](https://pypi.python.org/pypi/slimmer):

https://github.com/plone/plone.memoize/blob/1.2.0/plone/memoize/compress.py#L9-L29

We need to decide how to proceed, but before removing this feature I have to say that compressing XHTML code after minification results in a much smaller code that compressing it without minification (for more information, see: http://stackoverflow.com/q/807119).

We have 2 options then:

1. deprecate `xhtml_compress` in Plone 4.3 and Plone 5.0 and remove its code from Plone 5.1
1. implement an alternative XHTML minifier that gets rid not only of whitespaces, but also of comments.

I prefer option 2.

### What version of Plone/ Addons I am using:

Tested under Plone 4.3, 5.0 and 5.1.

**Comment by jensens** [comment]
this was fixed years ago
