### ISSUE TITLE
Add metadata item mime_type to catalog

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#1995]
When ever mime-type information for a content-item is needed (quite often!),  you have to get the object, which is very resource consuming -  especially  when processing lists of  content-items.
 
In  order to speed up all this we need  a metadata column MimeType,  for affected contenttypes File and Image (dexterity as well as Archetypes),  implementing  indexers  for MimeType and an upgrade step.

cc @jensens 

I hope we do not need  we need a Plip for this ?

**Comment by fgrcon** [comment]
implemented  & tested:
ok : http://jenkins.plone.org/job/pull-request-5.1/1476/

**Comment by jensens** [comment]
I would call it all lowercase ``mimetype``.

**Comment by fgrcon** [comment]
@jensens  thanks for reviews, done  http://jenkins.plone.org/job/pull-request-5.1/1487 

to merge: 

- [ ] https://github.com/plone/Products.CMFPlone/pull/2000
- [ ] https://github.com/plone/plone.app.contenttypes/pull/393
- [ ] https://github.com/plone/plone.app.upgrade/pull/111
- [ ] https://github.com/plone/documentation/pull/817

**Comment by fgrcon** [comment]
new try (fixed aquisition bug):  http://jenkins.plone.org/job/pull-request-5.1/1493/console

**Comment by fgrcon** [comment]
@jensens :  is it possible to merge this.? All review comments have been respected by now. This would really help to get  the little monster https://github.com/plone/Products.CMFPlone/issues/1734 finished!

**Comment by fgrcon** [comment]
review comments dealt with / rebased / rebased ... : http://jenkins.plone.org/job/pull-request-5.1/1527/

**Comment by gforcada** [comment]
@fgrcon I reviewed the code and fixed some cosmetics (trailing spaces, too much empty lines) and merged all commits into a single one on each pull request.

I'm re-running Jenkins to be extra sure: http://jenkins.plone.org/job/pull-request-5.1/1529/

Once it finishes, and continues green, I will merge.

**Comment by hvelarde** [comment]
@gforcada is not always a good idea to squash all commits before merging; sometimes it make sense to keep things separated to make it easier to understand the changes.

**Comment by gforcada** [comment]
@hvelarde yes, and I myself do *a lot* of small commits, this time, I did merge them because they were iterating over the same files on the same lines, i.e. fixing things on the previous commits, that's my main reason to merge 2 commits together usually

**Comment by jensens** [comment]
all green and merged. this was really missing.
