### ISSUE TITLE
Autorotation bug observed in Plone 5.1b2 and Plone 5.1 coredev master - Some jpgs do not successfully autorotate

### ISSUE THREAD

**Issue by pigeonflight** [plone/Products.CMFPlone#2008]
I've found that some JPGs do not successfully autorotate 

Issue observed on both Plone 5.1b2 and Plone 5.1 coredev master  (https://github.com/plone/buildout.coredev/commit/a7626c42cb34e5e9bfdf2638620941cb97ae89be)

Both depend on plone.namedfile 4.2.0

JPG A  (landscape that should be portrait) - Does not work
-------------------------------------------------------------------------------------
This is the original JPG  (note that github issues does not autorotate it)
![faulty](https://cloud.githubusercontent.com/assets/31827/24933754/97ca8f92-1edd-11e7-848e-2567c567d236.jpg)

When I attempt to upload it as an image I get the following output

```
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 63, in __call__
Module plone.z3cform.layout, line 47, in update
Module plone.dexterity.browser.add, line 134, in update
Module plone.z3cform.fieldsets.extensible, line 65, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 145, in update
Module plone.app.z3cform.csrf, line 22, in execute
Module z3c.form.action, line 98, in execute
Module z3c.form.button, line 315, in __call__
Module z3c.form.button, line 170, in __call__
Module plone.dexterity.browser.add, line 105, in handleAdd
Module z3c.form.group, line 98, in extractData
Module z3c.form.form, line 148, in extractData
Module z3c.form.field, line 303, in extract
Module plone.formwidget.namedfile.converter, line 43, in toFieldValue
Module plone.namedfile.file, line 391, in __init__
Module plone.namedfile.utils, line 228, in rotate_image
KeyError: 283
```

JPG B (mirror image) - Does work
--------------------------------------------------------
This JPG uploads without error to Plone and is properly rotated. (note that github issues does not autorotate it)
![thisoneworks](https://cloud.githubusercontent.com/assets/31827/24933755/97ca9866-1edd-11e7-875b-6b7fc0197416.jpeg)

As expected it displays correctly:
Here's a screenshot

![screenshot 2017-04-11 at 5 53 38 pm](https://cloud.githubusercontent.com/assets/31827/24934431/24f9b3e0-1ee1-11e7-8c42-e9d42e2f1e59.png)

**Comment by pigeonflight** [comment]
It may be worth getting some sample images with the various exif orientation flags:
there are some available here: https://github.com/recurser/exif-orientation-examples

**Comment by jensens** [comment]
Cc @loechel

**Comment by loechel** [comment]
Ok, I have analyzed what goes wrong and fixed it for images like that on https://github.com/plone/plone.namedfile/pull/44

The Problem is that this image did have a very reduced exif set which did not include the documented access method for width and hight in ImageIFD.XResolution and ImageIFD.YResolution.

As Soon as a new release of plone.namedfile is released this should not happen anymore.

**Comment by loechel** [comment]
@pigeonflight I have a huge set of test images mentioned on the plip / docs for autorotation, we might need some test implemented for those.

**Comment by loechel** [comment]
fixed by https://github.com/plone/plone.namedfile/pull/44#event-1043780117
