### ISSUE TITLE
Too many features in meta.zcml?

### ISSUE THREAD

**Issue by cekk** [plone/Products.CMFPlone#2016]
Hi,
in the list of meta:feature [here](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/meta.zcml) there are both Plone 4 and Plone 5 versions.

Is it ok?
I think that here we should have only plone 5 features, otherwise a zcml:condition only for Plone 4 can't work..or i'm missing something?

**Comment by ale-rt** [comment]
you can use zcml:condition="not-have plone-5" to load Plone 4 specific configuration

**Comment by cekk** [comment]
Yes, it's a solution ;)
mine was philosophical question about keeping or not plone 4 features in meta.zcml file

**Comment by jensens** [comment]
keep them, otherwise addons with ``have plone4`` stop working in plone 5
