### ISSUE TITLE
can not add Hebrew to and right to left to Plone 5

### ISSUE THREAD

**Issue by tmunati** [plone/Products.CMFPlone#2019]
can not add Hebrew to and right to left to Plone 5

### What I did:
Trying to change the main plone5 to Hebrew and right to left

### What I expect to happen:
when going to Plone languages options there is not option to add Hebrew - HE from the languages menu

### What actually happened:
No Hebrew option
### What version of Plone/ Addons I am using:
plone 5

**Comment by gforcada** [comment]
@tmunati there are translations https://github.com/collective/plone.app.locales/tree/master/plone/app/locales/locales/he/LC_MESSAGES but I did check on http://demo.plone.de and you are right, Hebrew is not on the dropdown...

**Comment by tmunati** [comment]
I am sure Hebrew is not the only translation which is missing.

also please know that when i tested in hebrew it also making problems with right to left.
what work is needed in order to add the Hebrew?

**Comment by loechel** [comment]
@tmunati there is the central development buildout (https://github.com/plone/buildout.coredev) check it out, Branch 5.1 is master, but translations could be easly backported to 5.0,

in experimental is a i18n.cfg that does load all translation tools

Translation in Plone Interface are done via GNU gettext (https://www.gnu.org/software/gettext/manual/gettext.html) menchanism. Some instructions how to maintain the translations are on: https://github.com/plone/Products.CMFPlone/issues/983

**Comment by loechel** [comment]
I have tried to reproduce it on a fresh Plone 5.0.7 and Hebrew is avaliable to select on PloneSite creation and on the control panel in @@language-controlpanel 

But yes I could confirm that the Hebrew translation is extremly limited, at the moment, so needs updates on the translation files and a new release of plone.app.locals.

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 5.0 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
