### ISSUE TITLE
Review captioned image markup

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#2020]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

It looks like we need to define a new markup for captioned images.  We suggest [this one](http://w3c.github.io/html/single-page.html#example-1b4e51d7).  And the fix would be as simple as change [this template](https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/browser/captioned_image.pt).

Is it possible to have this fixed on both Plone 4.3.x and Plone 5.x ?

### What I did:

* Enable captioned image option at TinyMCE configlet.
* Create a News Item with image inside

### What I expect to happen:

Have something like:

```html
<div>
  <p>
    <dl>
      ... image markup ...
    </dl>
    Other text
  </p>
</div>
```

### What actually happened:

The `<p>` content is kicked out because `<dl>` tag can't be inserted into the paragraph:

```html
<div>
  <p></p>
  <dl>
    ... image markup ...
  </dl>
  Other text
</div>
```

This looks that `lxml` library has some code that try to fix our markup:

```python
ipdb> lxml.html.tostring(lxml.html.fromstring('<p></p>'))
'<p></p>'
ipdb> lxml.html.tostring(lxml.html.fromstring('<p><dl></dl></p>'))
'<div><p></p><dl></dl></div>'
```

### What version of Plone/ Addons I am using:
This bug happen on all Plone versions

**Comment by hvelarde** [comment]
captioned images should be inserted using the `<figure>` and `<figcaption>` tags; the problem is that, different from `<img>`, `<figure>` can't be placed inside a `<p>` tag.

the TinyMCE plugin that inserts the caption should move out of a paragraph any `<img>` tag before inserting it as a captioned image.

so, for instance:

```xml
<p>foo <img src="bar">.</p>
```

becomes:

```xml
<p>foo.</p>
<figure>
  <img src="bar" alt="bar">
  <figcaption>bar</figcaption>
</figure> 
```

or:

```xml
<figure>
  <img src="bar" alt="bar">
  <figcaption>bar</figcaption>
</figure> 
<p>foo.</p>
```

**Comment by rodfersou** [comment]
@hvelarde it looks like we need a special css to put the image in the [middle of the paragraph](http://stackoverflow.com/a/5163443)

**Comment by hvelarde** [comment]
keep it simple: captioned images can not be used inside a paragraph; problem solved.

**Comment by rodfersou** [comment]
at Plone 4.3 we have: a [configlet option](https://github.com/plone/Products.TinyMCE/blob/1.3.x/Products/TinyMCE/interfaces/utility.py#L393-L396) linked to [an utility](https://github.com/plone/Products.TinyMCE/blob/1.3.x/Products/TinyMCE/utility.py#L1000-L1008) to [flag outputfilters](https://github.com/plone/plone.outputfilters/blob/1.x/plone/outputfilters/filters/resolveuid_and_caption.py#L92-L97) to [transform img tag](https://github.com/plone/plone.outputfilters/blob/1.x/plone/outputfilters/filters/resolveuid_and_caption.py#L360-L364)

Also tinymce image plugin adds `captioned` class into the image (when the flag is turned on)

**Comment by rodfersou** [comment]
ag Plone 5.1 we miss the `configlet option`, miss `the utility`, then outputfilters [don't find the utility and assume false](https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/filters/resolveuid_and_caption.py#L88-L93) and [never transform the img tag](https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/filters/resolveuid_and_caption.py#L363-L371)

Also new image plugin don't have the option to add `captioned` class into image

**Comment by rodfersou** [comment]
Still about Plone 5.1 from `buildout.coredev`, even if I add by hand the missing class at `<img>` tag and force the `outputfilters flag` to always return True the image is never show to `News Item` content type.

The image is never show with or without the `outputfilters transform`.  It looks like it is took out of the generated HTML at other step of the save process.

**Comment by rodfersou** [comment]
If html filtering is disabled the image tag start showing at Plone 5.1.

This is a new bug since `<img>` tag is not listed to be filtered out.

**Comment by hvelarde** [comment]
@plone/framework-team can someone help here?

**Comment by rodfersou** [comment]
@hvelarde I think the level of this issue is not easy anymore

**Comment by MrTango** [comment]
Just run ito this on Midsummer sprint while fixing tests.
But the good news is, that the transforms (safe_html) will work way better soon and also be in sync with TinyMCE. But the captions story seems to be broken too.
It's probably a good idea to create the new markup and find a way to either build the right markup in TinyMCE or refacture the caption transform in outputfilter to do it right.
But we disable the style attribute by default now, so we should use it here.
I think it should be doable without these specific styles.

**Comment by thet** [comment]
See: https://github.com/plone/mockup/pull/911

**Comment by skleinfeldt** [comment]
Keep in mind a11y ticket #2836 - hopefully not making it difficult to eventually implement that. W3C's [Techniques for providing useful text alternatives](https://dev.w3.org/html5/alt-techniques/developer.html) page has lots of markup examples.
