### ISSUE TITLE
3 translation errors in german contact-info

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#2030]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

![contact-info](https://cloud.githubusercontent.com/assets/918640/25331148/45bc3552-28e2-11e7-9868-a76704e3c4d1.png)

### What I did:

Clean install of Plone 5.0.7 and Plone 5.1b4

I checked 

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/interfaces.py#L320
https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/de/LC_MESSAGES/plone.po#L10862

Both seems to be ok.

**Comment by vincentfretin** [comment]
I checked on Plone 5.2 German, this is fixed.
