### ISSUE TITLE
Error 404 loading fontello font while upgrading to 5.1b3

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#2032]
### What I did:
While upgrading from 5.1a1 tp 5.1b3 I've found the issue that the compiled resources saved on production mode in the ZODB (those ++plone++production) were outdated and they were trying to pull the icon font from a deprecated /fonts/ directory on ++plone++static. It seems that the font now is being bundled (I guess via grunt) embedded in the CSS. As the saved resources were still pointing it to the old way of calling the font, it was unable to load the font, throwing a 404.

In order to overcome this, I had to remove manually the static and production folders from the portal_resources. Then, I had to force a recompilation by going to the resource registry and set/unset the development mode.

### What I expect to happen:
It might be required to write an upgrade step to reset the ZODB saved compiled resources and force a fresh cook of them.

### What actually happened:
The font load was broken, throwing a 404.

### What version of Plone/ Addons I am using:
Vainilla Plone 5.1b3 in production (non-fg) mode using ++plone++production resources.

**Comment by mlechner** [comment]
seems to be, that this can happen while upgrading from 5.0.6 to 5.0.8 as well - this is critical, because it affects stable plone

**Comment by sunew** [comment]
Can there be saved resources in portal_resources we do not want to remove - with customisations?

**Comment by sunew** [comment]
Same issue as https://github.com/plone/Products.CMFPlone/issues/1862
and https://github.com/plone/Products.CMFPlone/issues/1663

**Comment by jensens** [comment]
probably not an issue any more (also it was alpha/beta)
