### ISSUE TITLE
When a page is locked and someone tries to delete it - it leads to an error.

### ISSUE THREAD

**Issue by andreesg** [plone/Products.CMFPlone#2038]
**What I did:**
Tried to delete a locked item. 

**What I expect to happen:**
A warning message should appear to warn the user that the item is locked. Maybe explain that it will automatically be unlocked after 15min or contact the administrator to unlock it. 

**What actually happened:**
An error message is shown. Please check the screenshot.
![error-locked-page](https://cloud.githubusercontent.com/assets/810322/25536978/f86c4c0c-2c3c-11e7-9641-2323405759ec.png)

**What version of Plone/ Addons I am using:**
Plone == 5.0.6

It is really useful that on Plone 5 we can see on the menu that an item is locked (and for how long). It would be great to give a nice warning in case the user tries to delete or edit a locked item instead of an error message.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
