### ISSUE TITLE
WebDAV is converting files into DexterityItems.

### ISSUE THREAD

**Issue by robinsjm2** [plone/Products.CMFPlone#2040]
### What I did:

Installed cadaver on remote host. 
From terminal, connect to cadaver.  `cadaver https://<my-site>/<my-collection>`
Upload the file at the dav: prompt. `put my-file.txt`

### What I expect to happen:

I expect the file to be uploaded as a "File" within Zope.  I believe this is the one provided by plone.app.blob.

### What actually happened:

The file was uploaded as a "DexterityItem" within Zope.

### What version of Plone/ Addons I am using:

Plone 5.0.6
CMF 2.2.10
Zope 2.13.24
Python 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
PIL 3.3.0 (Pillow)

Products.CMFPlone = 5.0.6

**Comment by hvelarde** [comment]
we need to check if this was working in Plone 4.3 to determine if it's a bug or a regression.

**Comment by Rudd-O** [comment]
Files are uploaded as Dexterity Files indeed, when the `PUT` targets a Dexterity container.  See https://github.com/plone/plone.dexterity/blob/master/docs/WebDAV.txt to get how it works.

I think this is not a bug, though it could use more documentation.

**Comment by mauritsvanrees** [comment]
For me it seems logical. You upload a File and this uses the File content type from Plone. I expect this has always been the case, also in Plone 4 and with Archetypes.

**Comment by Rudd-O** [comment]
How do I configure Plone to receive files via WebDAV and give me back the same files _unchanged_?  This was the case for many, many years with Plone, and this behavior is "new" (the past couple years).

**Comment by Rudd-O** [comment]
Filed: https://github.com/plone/Products.CMFPlone/issues/3622
