### ISSUE TITLE
Document Python 3 buildout

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2041]
Document how to create a buildout that can test plone-packages against Python 3

**Comment by pbauer** [comment]
To be able to run test of plone-packages with python 3 locally you need to create a coredev-buildout along this example. 

https://github.com/plone/jenkins.plone.org/blob/master/scripts/pkg-py3.sh:

```bash
#!/bin/bash
git clone git@github.com:plone/buildout.coredev.git coredev-py3
cd coredev-py3
python3 -m venv .
source bin/activate
pip install -U setuptools zc.buildout
./bin/buildout -c experimental/py3x-test.cfg
```

Run the tests with ``./bin/test``
Add packages that are ported to Python 3 to ``experimental/py3x-test.cfg``.

**Comment by gforcada** [comment]
That's quite a nice writeup 😆 thanks for documenting it!

**Comment by loechel** [comment]
@pbauer could this go into the standard documentation and maybe the buildout.coredev documentation please

**Comment by tomgross** [comment]
I created a gist with the updated version of the script: https://gist.github.com/tomgross/94109bdef51547f07a2a0cc3be2dac0e

**Comment by rodfersou** [comment]
wow! UnicodeError never more!

**Comment by pbauer** [comment]
In https://github.com/plone/Products.CMFPlone/issues/2184#issuecomment-359445243 I also now documented how to run the whole of Plone (without AT) in python3. I copy it here for completeness sake.

# Running Plone on Python 3

The config `py3.cfg` (https://github.com/plone/buildout.coredev/blob/5.2/py3.cfg) can 
be used to build and run Plone on Python3. It removes the Arcetypes-dependecies that will not be
ported to python3. In your own projects you could add a similar effect by depending only on `Products.CMFPlone` instead of `Plone`.

The config depends on `wsgi.cfg` for wsgi-support and adds checkouts and
branches with python3 compatability that is work-in progress.

It also removes a lot of parts that either break at the moment or are not
necessary before startup works.

Clone coredev and use branch 5.2::

    $ git clone git@github.com:plone/buildout.coredev.git coredev_py3
    $ cd coredev_py3
    $ git checkout 5.2

Create py3 virtualenv::

    $ python3.6 -m venv .

Install buildout::

    $ ./bin/pip install -r requirements.txt

Run buildout::

    $ ./bin/buildout -c py3.cfg

Start Plone::

    $ ./bin/wsgi.py

Startup will most likely fail since a lot of code is not python3-compatible yet.

Once startup works you need a wsgi-server. This example uses waitress::

     $ ./bin/pip install waitress
     $ ./bin/waitress-serve --listen=0.0.0.0:8080 wsgi:application

**Comment by pbauer** [comment]
Since python 3 support was merged in Plone 5.2 the above documentation is outdated. 

Here is how you do that now:

# Running Plone 5.2 on Python 3

The configuration-file `buildout-py3.cfg` (https://github.com/plone/buildout.coredev/blob/5.2/buildout-py3.cfg) can be used to build Plone on Python 3. It no longer has any Archetypes-dependecies. 

Clone coredev and use branch 5.2:

    $ git clone git@github.com:plone/buildout.coredev.git coredev_py3
    $ cd coredev_py3
    $ git checkout 5.2

Create a py3 virtualenv with either Python 3.6 or 3.7 (they are very similar):

    $ python3.7 -m venv .

Install buildout:

    $ ./bin/pip install -r requirements.txt

Run buildout:

    $ ./bin/buildout -c core.cfg

Start Plone:

     $ ./bin/wsgi

By default Plone it will then run on port 6543 using the wsgi-server `waitress`: http://localhost:6543

You can easily extend that buildout by for example adding your own file `local.cfg` which then specifies a addon you want to migrate/test in Plone on Python 3. 

The following example would add `plone.tiles` and `collective.easyform` to the buildout:

    [buildout]
    extends = buildout-py3.cfg

    always-checkout = true

    custom-eggs +=
        collective.easyform
        plone.tiles

    test-eggs +=
        collective.easyform [test]
        plone.tiles [test]

    auto-checkout +=
        collective.easyform
        plone.tiles

    [sources]
    collective.easyform = git git@github.com:collective/collective.easyform.git branch=python3
    plone.tiles = git git@github.com:plone/plone.tiles.git branch=python3

You can build this configuration now using `./bin/buildout -c local.cfg`

To run Plone like usual on Python 2.7 you should use `buildout-py2.cfg`, start Plone with `./bin/instance fg` and it will run on port 8080: http://localhost:8080

If you also want Archetypes you need to run the same buildout but run the Plone with `./bin/instance-archetypes fg`.

**Comment by staeff** [comment]
> Start Plone:
> 
> ```
>  $ ./bin/wsgi
> ```

@pbauer I was curious to try it out after your talk. The command to run an instance with python3 is back to `$ ./bin/instance fg`, right?

**Comment by pbauer** [comment]
yes
