### ISSUE TITLE
4 test errors on CMFEditions on 5.0 jenkins jobs

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2042]
With the last commits done on [buildout.coredev 5.0 branch](https://github.com/plone/buildout.coredev/commits/5.0) 4 tests started failing on Products.CMFEditions: http://jenkins.plone.org/job/plone-5.0-python-2.7-at/41

Anyone has any idea what that could lead to those errors or has time to debug and fix them?

The @plone/release-team is about to cut a 5.0.8. This test failures are going to block it until they are fixed 😞

**Comment by mauritsvanrees** [comment]
Locally, the CMFEditions tests pass when I revert to commit ee8beae46a6b2acbbefe4995756eb0f20b1c8d93 from Monday. So somewhere in between that and now (9f531134f96d89442640840c76853f054ae290d3) it started failing.

1d8b45de0771b1b0136a177acc73c6a0f29873a3 is still good too.
I wil try a few more.

**Comment by mauritsvanrees** [comment]
It goes wrong in https://github.com/plone/buildout.coredev/commit/ca44a70e87ace3ae6a88359c03d274e62a2c176e, where `Products.CMFCore` is increased from 2.2.10 to 2.2.11.

Ho, in that release collective.indexing is merged. I am pretty sure we do not want this in 5.0.

**Comment by mauritsvanrees** [comment]
I have opened a [pull request](https://github.com/plone/buildout.coredev/pull/333) on coredev 5.0, reverting the version update.

Note that coredev 4.3 uses the 2.2 branch as well, though we are pinning an even older version, 2.2.9. We can probably update that one to 2.2.10. I will open a pull request to see if that breaks anything.

**Comment by esteele** [comment]
Nice catch, Maurits. Thank you!

**Comment by gforcada** [comment]
Fixed!
