### ISSUE TITLE
Update to zope.component latest

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2043]
After zope.interface is now latest and we are going forward to Python 3, I tried to update zope.component also to latest. This leads to some problems introduced with the removal of layers on zope.component.zcml.[view|resources]. After some discussion at Zope 4 Sprint in Halle, we figured out, that those implementations are not supposed to be used as base but the 'real' implementations in zope.browserpage and zope.browserresource (still having layers).

In the best case, this is just a task to find the right combinations of versions. It could also be a problem in some plone package itself. This needs some investigation.

**Comment by gforcada** [comment]
I wouldn't that as a high priority given that python 3 has still a long way to go 😄

**Comment by MrTango** [comment]
solved with PR #335
