### ISSUE TITLE
Portal tabs highlighting wrong for nested folders

### ISSUE THREAD

**Issue by mjmare** [plone/Products.CMFPlone#2047]
### What I expect to happen:
I have some folders, say:

/A
/A/B
/A/B/C

I have manually created portal actions in the ZMI with the corresponding URLs:
string:${globals_view/navigationRootUrl}/A

### What actually happened:

The tabs work but only one is highlighted. It seems that whatever tab is selected the longest path is matched (at least, that is what I gather from the source GlobalSectionsViewlet)

### What version of Plone/ Addons I am using:

5.0.7

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
