### ISSUE TITLE
clarify wording of "dry run" upgrade

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#2048]
as per discussion in https://community.plone.org/t/plone-4-3-13-soft-released/3873/30 it may not be clear what "dry run" means, so we could 

- explain better in the page template what this means
- include a message at the end of a dry run that clarifies that even if it was successful, no changes were made to the site and the user should do it again without "dry run" checked

cc @mauritsvanrees

**Comment by jensens** [comment]
We  have "Run the upgrade and show the result without actually writing anything to the database."
Sufficient, I close this here.
