### ISSUE TITLE
Circular dependency between CMFPlone and plone.i18n

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2049]
Since https://github.com/plone/plone.i18n/pull/18 was merged, ``plone.i18n`` [now depends](https://github.com/plone/plone.i18n/blob/0e49ae551e91de3a7190c253ffe7986879cc19e5/setup.py#L33) on ``Products.CMFPlone``, just like ``Products.CMFPlone`` [depends on plone.i18n](https://github.com/plone/Products.CMFPlone/blob/049c4a6cbc41f45a675cd65f5f25919a32446cf0/setup.py#L108). 🎉 surprise, surprise, a new circular dependency is born (or rather, an implicit one is made explicit).

On plone.i18n there is really only one place where CMFPlone is imported: https://github.com/plone/plone.i18n/blob/69c712da9ea01dd1922d27c3268dd55d7989caae/plone/i18n/utility.py#L11 the purpose there is to get language related registry settings.

Should this dependency be broken from plone.i18n side and not rely on the interface but rather use a string for the key?

Should this dependency be broken from CMFPlone side and move the interface to plone.i18n and update all imports?

**Comment by sallner** [comment]
> Should this dependency be broken from CMFPlone side and move the interface to plone.i18n and update all imports?

@gforcada I would like to vote for this option, although we could also just use a BBB import in `CMFPlone.interfaces.py` as this is the collection of the API anyway. I would be happy to prepare a PR for this here and in [plone/plone.i18n](https://github.com/plone/plone.i18n). What do you think?

We use `plone.i18n` in a project without the plone stack for normalization, so depending not on Plone is an important point.

**Comment by gforcada** [comment]
@sallner I'm :+1: on it, go go go :wink:
