### ISSUE TITLE
add data-base-url attribute to HTML body tag in Plone 4

### ISSUE THREAD

**Issue by petri** [plone/Products.CMFPlone#2051]
Since plone 4.3.12, the `<base href` attribute in HTML generated by Plone no longer always points to the context URL as it used to prior to the change. This change broke Plone and some add-ons. More breakage may still surface. Fixes have varied because no alternative was provided when the change was made.

For a lengthy background, see the [discussion](https://community.plone.org/t/how-to-get-context-url-in-js-on-plone-4-3-12/4031). 

Rather than rolling back the change which was done to support some other things and would require reverting them, I suggest providing a future-proof alternative (thanks @rodfersou for suggesting using a new attribute):

Plone 5 has removed `<base href` completely. Instead Plone 5 has added a `data-base-url` attribute to the HTML `body` tag. Which points to the context URL.

So, I suggest same be done for Plone 4. That way, anything in Plone core and/or add-ons needing context URL in Javascript have a future-proof way of getting it from here on.

**Comment by rodfersou** [comment]
I did some pull requests to fix this and other issues related:

https://github.com/plone/Products.CMFPlone/pull/2101/files
https://github.com/zopefoundation/Products.CMFDefault/pull/1/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.classic/pull/6/files

**Comment by rodfersou** [comment]
Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/22/console

**Comment by rodfersou** [comment]
Applied code review suggestions at all pull requests.

New Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/26/console

**Comment by rodfersou** [comment]
To test you can use a custom buildout configuration like this:

```ini
[buildout]
extends =
    buildout.cfg

auto-checkout +=
    Products.CMFPlone
    Products.CMFDefault
    plonetheme.sunburst
    plonetheme.classic

[sources]
Products.CMFPlone = git ${remotes:plone}/Products.CMFPlone.git pushurl=${remotes:plone_push}/Products.CMFPlone.git branch=issue_2051
Products.CMFDefault = git git://github.com/rodfersou/Products.CMFDefault.git pushurl=${remotes:zope_push}/Products.CMFDefault.git branch=issue_2051
plonetheme.sunburst = git ${remotes:plone}/plonetheme.sunburst.git pushurl=${remotes:plone_push}/plonetheme.sunburst.git branch=issue_2051
plonetheme.classic = git ${remotes:plone}/plonetheme.classic.git pushurl=${remotes:plone_push}/plonetheme.classic.git branch=issue_2051
```

and run buildout like this:
```bash
$ ./bin/buildout -c custom.cfg
```

**Comment by rodfersou** [comment]
Fix tests.

New Jenkins Job: http://jenkins.plone.org/job/pull-request-4.3/27/console

**Comment by rodfersou** [comment]
green \o/

**Comment by rodfersou** [comment]
Wait.. there is a better way to write the fallback without guess the context url, I'll refactor now

**Comment by rodfersou** [comment]
Didn't work my idea.. I tried to add a new variable in jsvariables point into context url, but at time @@jsvariables is executed, the context is the Plone site object, no luck here.

**Comment by rodfersou** [comment]
@plone/framework-team can someone help me please with this last idea?

**Comment by rodfersou** [comment]
@pgrunewald @mauritsvanrees do you have any idea on a way to fix the context of `@@jsvariables` view to point to the current object? currently it points to the root object.

If this works I can add a new javascript variable with the context, avoiding the need to guess the context url.

**Comment by rodfersou** [comment]
Is it safe to use `HTTP_REFERER` `request.environ` variable?

I'll use it now.. need someone to validate it for me (please)

**Comment by rodfersou** [comment]
New Jenkinks Job: http://jenkins.plone.org/job/pull-request-4.3/29/console

**Comment by rodfersou** [comment]
@petri all merged \o/
