### ISSUE TITLE
@@sharing is broken on Page objects in Plone 4.3.12 and 4.3.14

### ISSUE THREAD

**Issue by dpc22** [plone/Products.CMFPlone#2053]
### What I did:

1. Create vanilla Plone 4.3.14 site.
2. Add private Page with title Test at the top of the site
3. Navigate to sharing tab for that page
4. Type some characters into the Search box
5. Kaboom: exception

### What I expect to happen:

List of potential users as search results

### What actually happened:

Large python back trace because the search form AJAX accessed:

  http://localhost:8080/Plone2/test/@@sharing/@@updateSharingInfo

rather than the following used by Plone 4.3.11:

  http://localhost:8080/Plone2/test/@@updateSharingInfo
 
The root cause appears to be:

https://pypi.python.org/pypi/plone.app.layout/2.3.17

  2.3.15 (2016-06-28)
   Fixes:
   _Fix base tag differs from actual URL (fixes [86](https://github.com/plone/plone.app.layout/issues/86)). [rodfersou]_

which was actually made **after** plone.app.layout 2.3.15 was released, (December 2016): that comment is placed incorrectly in the README file. I'm happy to make a bug report there as well.

### What version of Plone/ Addons I am using:

Vanilla Plone 4.3.14, which uses  plone.app.layout 2.3.17. So does Plone 4.3.12, and I see exactly the same problem there.

(NB: Pinning plone.app.layout 2.3.15 in Plone 4.3.14 resolves the problem).

Update: appears to be the same issue discussed in: https://github.com/plone/Products.CMFPlone/issues/2051

**Comment by rodfersou** [comment]
@dpc22 the problem with changelog happen that the code review take too much time to merge the pull request, and one release was done in the middle time.

Of course I didn't realize it when I rebase the branch.. my mistake.

This change was merged at version `2.3.16`, not `2.3.15` and I'll fix the changelog in the sequence.

**Comment by rodfersou** [comment]
Jenkins job http://jenkins.plone.org/job/pull-request-4.3/13/console

**Comment by rodfersou** [comment]
Did some changes thinking better on how URL is formed.

New jenkins job http://jenkins.plone.org/job/pull-request-4.3/14/console

**Comment by rodfersou** [comment]
@hvelarde green \o/

**Comment by rodfersou** [comment]
This one can be closed after the merge

**Comment by rodfersou** [comment]
I did some pull requests to fix this and other issues related:

https://github.com/plone/Products.CMFPlone/pull/2101/files
https://github.com/zopefoundation/Products.CMFDefault/pull/1/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.classic/pull/6/files

**Comment by rodfersou** [comment]
Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/22/console

**Comment by davidjb** [comment]
For anyone trying to solve this problem, the solution is to upgrade to Plone 4.3.15. 

I found the problem persisted with the same exception shown at https://github.com/plone/plone.app.workflow/issues/14 after the upgrade, but what had happened was the `?_authenticator=...` token was *still* in my URL in the window open to `/@@sharing`.  Removing the query string saw the Sharing page search start working again.

Throwing an exception like that on an invalid authenticator token is probably something else that needs fixing, mind you.
