### ISSUE TITLE
@@plone_lock_operations called for wrong URL

### ISSUE THREAD

**Issue by pgrunewald** [plone/Products.CMFPlone#2061]
### What I did:

1. Create or edit a Document (or any other type).
2. Wait 5 minutes till the AJAX request @@plone_lock_operations/refreshlock occurs.

### What I expect to happen:

The result of the AJAX request refreshes the lock.

### What actually happened:

The result of the AJAX request is the view of the Document.

### What version of Plone/ Addons I am using:

Plone version 4.3.14.

--

The main problem is, that url from the base-tag is being used which now points to the actual url instead of the context's url. I guess it can be easily fixed by applying the proposal from #2051 and rewriting [this line](https://github.com/plone/Products.CMFPlone/blob/4.3.14/Products/CMFPlone/skins/plone_ecmascript/unlockOnFormUnload.js#L48).

**Comment by hvelarde** [comment]
@rodfersou this is also related with #1710.

**Comment by ale-rt** [comment]
I also had annoyances with plone locking redirecting top the view of the object recently, so I added an optional parameter `redirect=True` (to keep the previous behavior unchanged):

- https://github.com/plone/plone.locking/commit/ef0ed707b46ee74ed3e8a021b925b0425cdfa814

If the `redirect` is "falsish" the view method will return `None`. I do not like a view to return None but this is also coherent with the implementation I found in the `force_unlock` method.

I left the default behavior as it was. 
Can you check if calling `@@plone_lock_operations/refreshlock?redirect:int=0` will fix the issue?

**Comment by rodfersou** [comment]
I did some pull requests to fix this and other issues related:

https://github.com/plone/Products.CMFPlone/pull/2101/files
https://github.com/zopefoundation/Products.CMFDefault/pull/1/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.sunburst/pull/17/files
https://github.com/plone/plonetheme.classic/pull/6/files

**Comment by rodfersou** [comment]
Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/22/console

**Comment by jensens** [comment]
fixed long time ago
