### ISSUE TITLE
Can’t insert link on image (Plone 5.0.6+)

### ISSUE THREAD

**Issue by silviomarino** [plone/Products.CMFPlone#2062]
I have some sites on production server developed on 5.0.0 that have link over image. I noticed since I updated to Plone 5.0.6 it isn't possible to insert a link on image.

I will describe the steps to reproduce the problem:
create a new Plone site
upload a new image
edit default front-page and insert the image
click to insert a new link (Internal or External) on image. Nothing happens when I try to click on insert button.

I updated to Plone 5.0.7 but the problem still happens. The same problem happens on a new fresh 5.0.7 installation. Is there anyone working on this problem?

Thanks

**Comment by dpc22** [comment]
I'm pretty sure that this is:

   https://github.com/tinymce/tinymce/issues/3611

as I see the same Javascript exception listed on that page:

` Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.`

(We are running Plone 4.3.14, so it looks like all versions of Plone are affected).

**Comment by cdw9** [comment]
tinymce.js has two places with this bit of code:
`self.getSel().setBaseAndExtent(node, 0, node, 1);`
If the `1` is changed to a `0`:
`self.getSel().setBaseAndExtent(node, 0, node, 0);` then the image and link panels work in Chrome and Firefox

I don't know the best way to go about fixing this in core Plone.

**Comment by davisagli** [comment]
One way to fix it is to upgrade to a version of tinymce that has fixed the problem. That already happened on `mockup` master, but Plone 5.0 uses an older version of mockup and Plone 4.3 uses Products.TinyMCE (unless plone.app.widgets is installed, in which case it uses mockup). For these it may be simplest to try the workaround mentioned in this comment to avoid a tinymce upgrade which would have other side effects: https://github.com/tinymce/tinymce/issues/3611#issuecomment-304384844

**Comment by esteele** [comment]
Do we have any hope of backporting that fix for 5.0.x and 4.3.x?

**Comment by hvelarde** [comment]
@rodfersou can you help here?

**Comment by gp54321** [comment]
For the record this is fixed in 5.1

**Comment by ale-rt** [comment]
This works in Plone 5.2 and Plone 6
