### ISSUE TITLE
Rich text indexing issues again

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2066]
There is code in [plone.app.contenttypes/indexers.py](https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/indexers.py) that is getting changed back and forth. The code gets rich text for the SearchableText index like this:

```
textvalue = richtext.text
text = transforms.convertTo('text/plain',
    safe_unicode(textvalue.out).encode('utf8'),
    mimetype=textvalue.mimeType)
```

Let's simplify this to make it easier to talk about:

```
convert(text, mimetype)
```

It is not clear what `text` and `mimetype` need to be.
It started out like this:

```
convert(textvalue.output, textvalue.mimeType)
```

Then @petri filed https://github.com/plone/plone.app.contenttypes/issues/357.
There he argued that the current code was using the output in combination with the original mimetype, which indeed sounds strange, although he did not give an example of an actual bug caused by this.
His idea was that it should be one of these:

```
# 1: use output and output mimetype
convert(textvalue.output, textvalue.outputMimeType)
# 2: use original text and original mimetype
convert(textvalue.raw, textvalue.mimeType)
```

Both seem okay.

So he made pull requests choosing the first solution: output and output mimetype. This was included in 1.1.2 and 1.2.18.

Then @agitator noticed problems with this in https://github.com/plone/Products.CMFPlone/issues/1844.
Basically, the `outputMimeType` was `text/x-safe-html`, and there was no transform from this to `text/plain`, so the SearchableText contained nothing (except title and description).
This got fixed by reverting to the original:

```
convert(textvalue.output, textvalue.mimeType)
```

This was released in 1.2.19 (branch 1.2.x and master). It was not yet backported to branch 1.1.x, but it should be: I notice the same problem there.

So:

- [x] @petri: What problems did you encounter? Do they come back when you use 1.2.19?
- [x] The fix from @agitator needs to be backported to 1.1.x. I can do that.
- [x] Most importantly: Should we instead use the second method on all branches? So `convert(textvalue.raw, textvalue.mimeType)`. It seems to work fine then.
- [x] Once we have the correct code, an upgrade step to reindex the SearchableText index for Collections, Documents and News Items would be good. I have such code in https://github.com/plone/plone.app.contenttypes/pull/407 for Collections already.

**Comment by petri** [comment]
It's been a while...  I don't remember of any particular problems in Plone that I would have encountered.

After re-reading the sources and #1844 discussion, it seems to me that for indexing, we should use the raw RichText value for plaintext conversion, not the output value, because:

- the `.output` property triggers what seems a unnecessary second portal transform run, before plaintext conversion
- I cannot imagine how that extra conversion would add any value for indexing purposes

Because of that  it seems to me the suggestion by @mauritsvanrees is what we should do:

>  Most importantly: Should we instead use the second method on all branches? So convert(textvalue.raw, textvalue.mimeType). It seems to work fine then.

If I understand correctly, this is what @thet implied as well, in the #1844 discussion.

**Comment by pbauer** [comment]
Yes on all points.

**Comment by jensens** [comment]
any reason to keep this one open?

**Comment by mauritsvanrees** [comment]
Nope, everything has been fixed as far as I know.
