### ISSUE TITLE
Datepicker / Timezone inconsistencies

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2074]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

There are several datepicker / timezone inconsistencies in Plone 5.1b3 (espacially in folder_contents)

1. - [ ] The datetime localization is not respected in the folder contents version of the datepicker. It IS respected on the edit page.
![grafik](https://user-images.githubusercontent.com/339384/27171668-9a25c6e6-51b2-11e7-9e1e-04d95f4f7a06.png)

2. - [ ] Timezone offset is not handled, if browser TZ is not UTC and date is changed in folder_contents. It is correctly handled on edit page.

As a fix for 2. I trieds etting a custom timezone. I set a custom timezone in the resource registry `{"date": {"selectYears": 200}, "time": {"interval": 5 },
"timezone": {"data": [{"id":"Europe/Berlin","text":"Europe/Berlin"}]}}` like documented in the mockup build.

This fixed the timezone issue in folder_contents BUT lead to following even more severe issue:

3. - [ ] Datepicker is no longer displayed if timezone is set in datepicker options and it is impossible to change the date.

![grafik](https://user-images.githubusercontent.com/339384/27180117-166a0b62-51d2-11e7-9712-dc6eb610ac50.png)

The JavaScript console shows an ugly traceback:

![grafik](https://user-images.githubusercontent.com/339384/27182824-dfcac2ee-51dc-11e7-99b5-59b4ad38c0cc.png)

### What I did:

For 2.
 - Check if you system is not set to UTC timezone.
 - Change the effective date to any value.
 - Time should be the same is set but shown and saved with offset to UTC.

For 3.
 - Configure timezone in @@resource-registy datepicker pattern options
 - Change effective date of a page in folder contents
 - Try to edit effective date in edit mode of a page.

### What I expect to happen:

- Consistent handling of timezones in folder_contents, edit and view pages and listings
- Ability to set custom timezones and keep the consistent handling of timezones.

### What actually happened:

 - Timezone handling is inconsistent and setting a custom timezone does not work.

### What version of Plone/ Addons I am using:

Plone 5.1b3 (minimalplone5)

**Comment by jensens** [comment]
still applies in RC1 (coredev of today)

**Comment by jensens** [comment]
see also #1298

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
