### ISSUE TITLE
Specific Dexterity behaviors are shown on all content types

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#2087]
### What I did:

I registered a Dexterity behavior like this:

```xml
  <plone:behavior
      title="Library"
      description="Adds extra fields for file classification."
      provides="my.package.behaviors.ILibrary"
      for="plone.app.contenttypes.interfaces.IFile"
      i18n:attributes="title; description"
      />
```

### What I expect to happen:

as the behavior is declared explicitly for `IFile` I expect is shown only on File content type.

### What actually happened:

the behavior is available for all Dexterity content types.

### What version of Plone/ Addons I am using:

Plone 4.3.14 (this may happen in Plone 5 also) and plone.app.contenttypes 1.1.1.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
