### ISSUE TITLE
images in body do not appear in view mode

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#2088]
On plone.org if I create a news item (or a page) in which I insert images in the body, they appear fine in Edit view. Once I save, the images do not appear, and the img tags are entirely missing. If I go back to Edit view, everything is there correctly. 

@sneridagh suspects it has to do with transforms. This other issue seems similar: https://github.com/plone/Products.CMFPlone/issues/1567

plone.org uses 5.1b3, along with a few other add-ons. For a while we ran 5.1a2 then in April we upgraded to 5.1b3. 

https://github.com/plone/ansible-playbook/blob/plone-org/local-configure.yml#L41

  - ploneorg.core
  - authomatic
  - pas.plugins.authomatic
  - collective.workspace
  - collective.isotope
  - Products.PloneFormGen
  - collective.recaptcha
  - simplejson
  - plone.app.mosaic
  - plone.formwidget.autocomplete

plone_sources:
  - "ploneorg.core = git https://github.com/plone/ploneorg.core.git"
  - "ploneorg.theme = git https://github.com/plone/ploneorg.theme.git pushurl=git@github.com:plone/ploneorg.theme.git"
  - "Py-StackExchange = git https://github.com/lucjon/Py-StackExchange.git"
  - "plone.app.vulnerabilities = git https://github.com/plone/plone.app.vulnerabilities.git pushurl=git@github.com:plone/plone.app.vulnerabilities.git"
  - "collective.workspace = git https://github.com/collective/collective.workspace.git pushurl=git@github.com:collective/collective.workspace.git branch=plone5"
  - "collective.roster = git https://github.com/collective/collective.roster.git pushurl=git@github.com:collective/collective.roster.git"
  - "collective.badge = git https://github.com/collective/collective.badge.git pushurl=git@github.com:collective/collective.badge.git"
  - "pas.plugins.authomatic = git https://github.com/collective/pas.plugins.authomatic.git pushurl=git@github.com:collective/pas.plugins.authomatic.git"
  - "collective.isotope = git git://github.com/collective/collective.isotope.git pushurl=git@github.com:collective/collective.isotope.git"
  - "collective.recaptcha = git git://github.com/collective/collective.recaptcha.git"

plone_additional_versions:
  - "check-manifest = 0.25"
  - "collective.jsonmigrator = 0.2"
  - "corneti.recipes.codeintel = 0.3"
  - "flake8 = 2.4.1"
  - "MarkupSafe = 0.23"
  - "mccabe = 0.3.1"
  - "plone.app.transmogrifier = 1.3"
  - "plone.recipe.codeanalysis = 2.1"
  - "pycountry = 1.17"
  - "pyflakes = 0.8.1"
  - "PyGithub = 1.25.2"
  - "requests = 2.8.1"
  - "setuptools = "
  - "transmogrify.dexterity = 1.6.1"
  - "twitter = 1.17.1"
  - "z3c.jbot = 0.7.2"
  - "zc.buildout = "
  - "Authomatic = 0.1.0.post1"
  - "Products.PloneHotfix20160419 = 1.0"
  - "collective.themefragments = 1.0.1"
  - "Products.PloneFormGen = 1.8.0"
  - "Products.PythonField = 1.1.3"
  - "Products.TemplateFields = 1.2.5"
  - "Products.TALESField = 1.1.3"
  - "wadllib = 1.3.2"
  - "launchpadlib = 1.10.3"
  - "testresources = 2.0.0"
  - "lazr.restfulclient = 0.13.1"
  - "keyring = 9.0"
  - "httplib2 = 0.9.2"
  - "pbr = 1.9.1"
  - "wsgi-intercept = 1.2.2"
  - "oauth = 1.0.1"
  - "lazr.uri = 1.0.3"
  - "lazr.authentication = 0.1.3"
  - "Products.PloneHotfix20160830 = 1.0"
  - "Products.PloneHotfix20161129 = 1.2"
  - "Products.PloneHotfix20170117 = 1.0"
  - "collective.recaptcha = 2.0.0"
  - "norecaptcha = 0.3.0"
  - "plone.app.mosaic = 2.0.0rc4"
  - "plone.tiles = 1.8.1"
  - "plone.subrequest = 1.8"
  - "plone.app.tiles = 3.0.1"
  - "plone.app.standardtiles = 2.0.0"
  - "plone.app.blocks = 4.0.0"
  - "plone.app.drafts = 1.1.1"
  - "plone.formwidget.multifile = 2.0"
  - "plone.jsonserializer = 0.9.2"

**Comment by tkimnguyen** [comment]
@ebrehault Victor wondered if you could have a look at this...

**Comment by tkimnguyen** [comment]
One puzzling bit that might be connected: in TinyMCE the view code shows a full HTML document:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>some text some text</p>
<p> </p>
<p> </p>
</body>
</html>
```

**Comment by datakurre** [comment]
I've seen that full HTML code issue. I try to recall, which was the cause and fix for me.

**Comment by datakurre** [comment]
@tkimnguyen Now I remember. We had accidentally enabled fullpage plugin in TinyMCE settings, and it resulted in full HTML documents in TinyMCE.

**Comment by sneridagh** [comment]
@ebrehault in fact I was meant to say @esteele because of his mighty control of the changelog. ;)

**Comment by pbauer** [comment]
I had the same issue after migrating a page from 4.3.15 to 5.1b4. The culprit was safe_html. After I reloaded the transform in /portal_transforms/safe_html/manage_main the issue was gone. 

I did not investigate further since @MrTango did https://github.com/plone/Products.PortalTransforms/pull/20 after I had the issue. Next week I can check if the issue is still there, since I plan to rerun migration then.

**Comment by sneridagh** [comment]
Please it would be great, since the issue still present in plone.org. :(
Couldn't figure out why yet.

**Comment by pbauer** [comment]
Did you try reloading the transform? You need to restart the site to see the results.

**Comment by sneridagh** [comment]
Nope, but it's not supposed to be happening on each site reboot? I have a
local instance, I will try there.

**Comment by sneridagh** [comment]
Just tried it out as you suggested, no luck... :( 5.1b4 too, migrated from
alpha1.

**Comment by pbauer** [comment]
Ok. I'll do a test-migration of that project tomorrow. Disabling the transform should work though if you don't think that would be a security-issue.

**Comment by pbauer** [comment]
The issue was still there after the migration today but we figured out that the tag img was not in the new place for the settings (/@@filter-controlpanel, which controls registry['plone.valid_tags']). The controlpanel in the ZMI has no effet (see https://github.com/plone/Products.CMFPlone/issues/2130).
After adding img to the tags

**Comment by tkimnguyen** [comment]
I'm trying to test this on plone.org live :) Where on @@filter-controlpanel should I be manually re-adding the img tag?

**Comment by tkimnguyen** [comment]
OK I added img to the "Custom tags", edited a test news item that had an image that wasn't showing up, saved it, and now the image shows up. :) :) :)

**Comment by pbauer** [comment]
"Custom tags"? There is only "Custom attributes". `img` should be in "Valid tags"

**Comment by sneridagh** [comment]
WAT? Really? How could that be?

**Comment by pbauer** [comment]
I now encountered a third site that was missing the images in Plone 5.1 after being migrated from 4.3. The upgrade-step that switches from the settings in the Transform safe_html to the settings in the registry (@@filter-controlpanel) has a bug. 

It does:

```python
valid_tags = [tag.decode() for tag, enabled in raw_valid_tags.items() if enabled]
```

Here `enabled` is either 0 or 1 and those with a 0 are dropped. But in the old safe_html that was actually something completely different! Here is what the UI in portal_transforms/safe_html/manage_main said: 

**List of valid html-tags, value is 1 if they have a closing part (e.g. `<p>...</p>`) and 0 for empty tags (like `<br />`). Be carefull!**

Since we moved from our old homgrown cleaner to the on in lxml this feature is gone. I'll make a PR to remove that condition.

**Comment by tkimnguyen** [comment]
@pbauer plone.org no longer has a "Valid Tags" setting on the https://plone.org/@@filter-controlpanel page. See below.

![plone org- filter-controlpanel](https://user-images.githubusercontent.com/815418/29884564-84ea8bd8-8d79-11e7-9a56-03d87955c96c.png)

**Comment by pbauer** [comment]
I guess that changed with the work in https://github.com/plone/Products.PortalTransforms/pull/20 by @MrTango.

**Comment by MrTango** [comment]
@tkimnguyen @sneridagh the upgrade step is not loaded, maybe because you where already on some 5.1 version. @pbauer could that be your change (moving the upgrade of safe_html to an earlier state) ?
I'm online tomorrow I can help then.
