### ISSUE TITLE
Upgrade step required for jqtree-contextmenu to be available in pre-existing sites

### ISSUE THREAD

**Issue by b4oshany** [plone/Products.CMFPlone#2091]
### What I did:

After adding the cs-jqtree-contextmenu to the resource registry, I added it as a dependency package in plone.mockup for it to be used on the theme editor for a pre-existing Plone 5 package.

### What I expect to happen:

On the theme editor for pre-existing and new Plone 5 sites, users should be able to select a contextual menu item after right click on files in the file tree.

### What actually happened:

It worked as is supposed to with new Plone 5 sites. However, for pre-existing sites, the theme editor page was breaking. Looking at the developer console, the cs-jqtree-contextmenu library wasn't loading. It was returning a 404 error.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
