### ISSUE TITLE
ACE editor is not loaded for easyform

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2095]
### What I did:

- Install easyform in a fresh Plone 5.1b4 site
- Edit fields
- Enter XML model editor

### What I expect to happen:

- Editing and saving XML works

### What actually happened:

- ACE editor is not loaded and editing is disabled

![grafik](https://user-images.githubusercontent.com/339384/27859239-5ddeb5fa-6178-11e7-88d1-061c8f00da8a.png)

The ACE editor is accessible and useable for a Dexterity schema. On a migrated site it is not accessible (see #2093 )

### What version of Plone/ Addons I am using:

- Plone 5.1b4
- collective.easyform 2.0.0b1

It worked with the same setup on Plone 5.1b3.

**Comment by agitator** [comment]
Tested with the same site as https://github.com/plone/Products.CMFPlone/issues/2093

I also have the missing .../Plone/++resource++plone.resourceeditor/ace/ace.js

**Comment by thet** [comment]
I cannot reproduce the problem.
I installed a fresh 5.1 site, all is working - with resource registry in dev mode and production mode.
Then I re-run all upgrade steps from 5.0 to 5.1 (to maybe reproduce any upgrade issues) - still working.
I also tried to use a VHM mapping, to reproduce any url-mapping problems.

@tomgross what was the Plone version from which you migrated your site?

Besides, the correct path is: ``++plone++static/components/ace-builds/src/ace.js``

**Comment by tomgross** [comment]
@thet It happens on a fresh minimalplone too. This is my buildout:

```
[buildout]
parts = instance
extends =
    https://dist.plone.org/release/5.1b4-pending/versions.cfg
versions = versions

[instance]
recipe = plone.recipe.zope2instance
eggs =
    Plone
    Pillow
    collective.easyform==2.0.0b1
```

**Comment by agitator** [comment]
After a restart of the instance the ace.js is found at the correct location ++plone++static/components/ace-builds/src/ace.js

But the editor still doesn't work, also in a newly created site ... the schema content is not laoded and plone specific styles for the editor are imho missing

<img width="744" alt="screen shot 2017-07-07 at 09 49 02" src="https://user-images.githubusercontent.com/365761/27946300-c5c85f18-62f9-11e7-8536-0ab4d90f1499.png">

**Comment by thet** [comment]
@tomgross fixed: https://github.com/collective/collective.easyform/commit/d1495d46ee5510f4803e7d434b5ff5f373bd4f48

@agitator I can reproduce the problem with the schema editor in Dexterity control panel too.
Not sure, why that happens.
IMO, that's a different issue.

**Comment by tomgross** [comment]
Thanks @thet for fixing. Why needs the ACE editor be loaded for easyform separately? Isn't it included in the bundle in Plone 5. collective.easyform >= 2 is for Plone 5.1 anyways.

**Comment by thet** [comment]
The ACE editor is loaded for easyform like it's done with the model editor in plone.app.dexterity (see: https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/browser/modeleditor.pt#L66 ).
The ACE editor is not part of the plone or plone-logged-in bundle. It is an dependency of the texteditor pattern, which itself is a dependency of the filemanager pattern which is bundled for the thememapper (plone.app.theming) bundle.
But for the schema model editor, it's included via a script tag directly.

IMO, that's fine enough as long we do not run into any weird dependency issues.

**Comment by tomgross** [comment]
OK. @thet Thanks for the clarification.
