### ISSUE TITLE
Purge on scales of Images does not work (caching)

### ISSUE THREAD

**Issue by karalics** [plone/Products.CMFPlone#2097]
### What I did:
Upload a new image to a Document (NamedBlobImage)
### What I expect to happen:
After saving the document, all scales of the new image are purged.
e.g.: needed purge requests: 
```
myexample.com/mydocument/@@images/myimgvar
myexample.com/mydocument/@@images/myimgvar/thumb
myexample.com/mydocument/@@images/myimgvar/large
myexample.com/mydocument/@@images/myimgvar/preview
```
... etc
### What actually happened:
Purge requests on scales have not  triggered.
Adding the a scale path to /@@caching-controlpanel-purge (manually purge) works fine.
There are no errors or warnings in the log.
### What version of Plone/ Addons I am using:
5.1b3

**Comment by tomgross** [comment]
The solution is here: https://gist.github.com/tomgross/bb6d741c032207b22bcbf1e936ae18ee
We try to do a PR soon. Where would that live? `plone.cachepurging`?

**Comment by pbauer** [comment]
Not sure. Maybe plone.app.caching there are some other such methonds in plone.app.caching.purge already.

**Comment by jensens** [comment]
best practice is to not use the URLs as above, but use generated URLs with unique keys. After modification a new unique key is used and no purging at all is needed.

**Comment by mamico** [comment]
Probably https://pypi.python.org/pypi/collective.purgebyid could help to solve this type of issue using a different way (disclaimer: I am the author)

**Comment by karalics** [comment]
Possible solution: 
https://github.com/plone/plone.app.caching/pull/39
( additional class for plone.app.caching.purge )

**Comment by jensens** [comment]
https://github.com/plone/plone.app.caching/pull/39 was merged, so this issue was solved. thanks @karalics !
