### ISSUE TITLE
Dexterity schema editor not working

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2099]
As reported by @agitator in https://github.com/plone/Products.CMFPlone/issues/2095, the Dexterity schema editor is not working properly.

I cite:

> After a restart of the instance the ace.js is found at the correct location ++plone++static/components/ace-builds/src/ace.js
> 
> But the editor still doesn't work, also in a newly created site ... the schema content is not laoded and plone specific styles for the editor are imho missing
> 
> <img width="744" alt="screen shot 2017-07-07 at 09 49 02" src="https://user-images.githubusercontent.com/365761/27946300-c5c85f18-62f9-11e7-8536-0ab4d90f1499.png">
>

**Comment by pbauer** [comment]
I cannot reproduce this in 5.1 coredev, it seems to be working fine. Can we close the issue?

![ace](https://user-images.githubusercontent.com/453208/29242078-6ce6e0f0-7f86-11e7-8423-05595a4ff344.png)

**Comment by thet** [comment]
cannot reproduce either - it works even with collective easyform - i'm closing this.
@agitator @tomgross if it's still an issue, please reopen with the steps to reproduce the problem.
