### ISSUE TITLE
Move filter control panel to z3c.form.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#211]

**Comment by thet** [comment]
maybe this is helpful: i have some code, where portal_transforms settings are get/set:
https://github.com/collective/collective.setuphandlertools/blob/master/collective/setuphandlertools/setuphandlertools.py#L258
https://github.com/collective/collective.setuphandlertools/blob/master/collective/setuphandlertools/setuphandlertools.py#L283

IMO Products.PortalTransforms should be changed to use plone.app.registry instead of it's own obscure storage.

**Comment by tisto** [comment]
I think for Plone 5 we should re-write the filter control panel with plone.autoform. That should be pretty straight forward. Here is an example of the editing control panel that I wrote with plone.autoform in the z3cform branch:

https://github.com/plone/plone.app.controlpanel/commit/91d0c2f93c12c424f458d5d4515ba63a957b6eb0

The filter control panel should also be moved to Products.CMFPlone.

@MRTango @khink Is that something that you guys would want to work on?

**Comment by khink** [comment]
Starting work on this now.

**Comment by khink** [comment]
There's plip10359-filter-controlpanel of CMFPlone and controlpanel.

**Comment by khink** [comment]
The stripped_combinations give me an "AttributeError: adapter", commented that out

**Comment by khink** [comment]
Going with thet's suggestion and making Products.Portaltransforms use p.a.registry storage.

**Comment by khink** [comment]
Current status:
* Form works and stores in registry, except ``stripped_combinations`` which gives ``AttributeError: adapter`` (so i commented that out)
* Form edit also stores ``disable_filtering`` and ``nasty_tags`` on the ``portal_transforms`` tool
* But we're going to replace that storage with ``Products.PortalTransforms`` reading its settings from the registry
* For this, we need to include p.a.registry in the PortalTransforms tests somehow. Currently this gives me ``ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/zope', u'includeDependencies')``

Branches:
https://github.com/plone/Products.PortalTransforms/tree/plip10359-filter-controlpanel
https://github.com/plone/Products.CMFPlone/tree/plip10359-filter-controlpanel
https://github.com/plone/plone.app.controlpanel/tree/plip10359-filter-controlpanel

**Comment by khink** [comment]
The last bullet from the list above is solved, all tests in the PortalTransforms branch pass. Now we can start querying the registry.

**Comment by tisto** [comment]
I'm a bit confused. The plone.app.registry-based filter control panel already was ready for merge: 

https://github.com/plone/Products.CMFPlone/tree/plip10359-filter-controlpanel-timo

How does my branch differ from the one you created? The main problem is making P.PortalTransform read those settings. I did a quick PortalTransforms code review and my feeling was that it beyond the scope of the initial PLIP to rewrite it as well.

@thet's code just gets/sets the (old) portal transforms settings, so I don't see how that would help us. If we would use that code we would end up with storing the settings in two locations. This is why I recommended to go with plone.autoform and do the plone.app.registry setting at a later point.

**Comment by khink** [comment]
Branches are quite the same indeed. I wanted to replay it to understand what's going on.

PortalTransforms changes will help filter settings take effect. It was either that, or write to the tool's obscure storage on each change (and have no GS update). The current approach is a more complete solution.

If you look at the code, you'll see i didn't do much with thet's code examples, so i agree with you there as well.

**Comment by tisto** [comment]
I created a Jenkins job for the plip: http://jenkins.plone.org/view/PLIPs/job/plip-10359-filter-controlpanel

**Comment by tisto** [comment]
@khink with the branches you mentioned above:

https://github.com/plone/buildout.coredev/blob/04c29edbea67aaa05bbff4bd3042b2097b49f484/plips/plip10359-filter-controlpanel.cfg

**Comment by tisto** [comment]
All tests pass:

http://jenkins.plone.org/job/plip-10359-filter-controlpanel-autoform/20

Ready to merge.

**Comment by tisto** [comment]
Pull requests:

https://github.com/plone/Products.CMFPlone/pull/404
https://github.com/plone/plone.app.controlpanel/pull/47

**Comment by tisto** [comment]
Merged. All Jenkins build green.

**Comment by thet** [comment]
@khink @tisto just want to know: the settings are still stored in portal_transforms tool and not in the registry, or not?

**Comment by tisto** [comment]
Still stored in portal_transforms.
