### ISSUE TITLE
Cannot set Website name in control panel

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#2117]
As far as I remember @@site-controlpanel is the place to set the website title aka title meta suffix for Plone.

Changing that title shows no effect on the actual site title.
(It's only reflected for the title of @@site-controlpanel not on other pages)

It still shows the title that is visible under manageProperties within the zmi - right now the only place to change that.

Did I miss something?

Plone 5.1 master

**Comment by gforcada** [comment]
I can see the same on demo.plone.de as well, so seems a regression

**Comment by pbauer** [comment]
I think I fixed it in https://github.com/plone/plone.app.layout/pull/131. MIght need a couple of tests since they did not fail.

**Comment by pbauer** [comment]
I added a couple of tests.
