### ISSUE TITLE
TinyMce - Impossible to hide a format group (for example block)

### ISSUE THREAD

**Issue by cekk** [plone/Products.CMFPlone#2120]
On last Plone version (5.1b5.dev0 built with buildout.coredev)

### What I did:

I wanted to hide one voice from Formats menu, for example "Block".
I removed all values from its field and saved.

### What I expect to happen:

- block_styles field empty after save
- Block menu item disappear from Formats menu

### What actually happened:
- block_styles and other style fields are required, so i can't leave them empty. A workaround is to save them with a space character, to bypass requirements. A possible solution could be to let these field not required, but we also need to remove default values.

- If i set one of these fields empty, the menu item is always present..without sub-items

### Proposal
I have two ideas:

1) remove requirements from these fields. Remove also the defaults (because otherwise at every form load, empty fields will be filled with default values) and save defaults values in the registry on site creation and with an upgrade-step. Customize the method `get_all_style_formats` in _patterns/tinymce.py_ to return only filled fields

2) leave the fields required, but add also a new field for set which formats show in the menu, like "menubar" or "toolbar".

I could make a branch and improve one of these solutions, but i don't know exactly how to add an upgrade-step for CMFPlone (that's not a simple plugin)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
