### ISSUE TITLE
Remove all references to "Retina" in our source code due to trademark issues

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#2123]
PLIP #1483 introduced a series of changes to allow scale images in plone.scale such that they will look good on devices with pixel ratios higher than 1.

The following is [from the Wikipedia](https://en.wikipedia.org/wiki/Retina_Display):

> Retina Display is a brand name used by Apple for its series of IPS panel displays that have a higher pixel density than other displays. Apple has applied to register the term "Retina" as a trademark in regard to computers and mobile devices with the United States Patent and Trademark Office, Canadian Intellectual Property Office, and in Jamaica. On November 27, 2012 the US Patent and Trademark office approved Apple's application and "Retina" is now a registered trademark for computer equipment.

I suggest to remove all references to "**Retina image scales**" and replace it with "**High DPI image scales**" (or something similar) in our source code to avoid any future trademark issues:

https://github.com/plone/Products.CMFPlone/search?utf8=%E2%9C%93&q=retina

An upgrade step will be necessary.

**Comment by tkimnguyen** [comment]
"high pixel density" seems good

**Comment by tkimnguyen** [comment]
- adding deprecation warning to getRetinaScales in Products.CMFCore.utils (replacing with getHighPixelDensityScales), in plone.namedfile, plone.formwidget
- many .po file changes (to the msgids that included the word) but left the plone.po files alone where the msgstr contained the word

Next up:

- Should I change .rst files like ~/PloneBuilds/buildout.coredev/plips/reviews/plip1483-retina-image-scales-review-jensens.rst 
- Should I change the occurrences I've found in .map files? e.g. Products/CMFPlone/static/plone-compiled.css.map, Products/CMFPlone/static/plone-compiled.js.map, Products/CMFPlone/static/plone-compiled.min.js, Products/CMFPlone/static/plone-compiled.min.js.map, Products/CMFPlone/static/plone-logged-in-compiled.css.map, Products/CMFPlone/static/resourceregistry-compiled.css.map, etc.
- How to update files like .min.js? (just edit directly?)

**Comment by hvelarde** [comment]
thanks for taking care of this! I have no idea how to proceed with the rest of the stuff.

**Comment by tkimnguyen** [comment]
I have it in this branch and will make a similar one for plone.namedfile and plone.formwidget.namedfile then will make a WIP PR

**Comment by tkimnguyen** [comment]
OK I think I'm done... mind you I guess I should test this... just run the test cases and try it manually to see if I broke anything?

- https://github.com/plone/plone.namedfile/tree/tkimnguyen-no-retina
- https://github.com/plone/plone.formwidget.namedfile/tree/tkimnguyen-no-retina
- https://github.com/collective/plone.app.locales/tree/tkimnguyen-no-retina

**Comment by tkimnguyen** [comment]
- I left the .rst files in the plips/reviews folder unchanged
- I manually changed the .map and .min.js files

**Comment by tkimnguyen** [comment]
OK I *think* I initiated the Jenkins build ok for https://github.com/plone/Products.CMFPlone/pull/2133...

**Comment by jensens** [comment]
Jenkins is running with this at http://jenkins.plone.org/job/pull-request-5.1/497/

**Comment by pbauer** [comment]
@tkimnguyen you to change some tests. I fixed them and started a jenkins-build: http://jenkins.plone.org/job/pull-request-5.1/546/
I might need to rebase the branches first though...

**Comment by pbauer** [comment]
@tkimnguyen: Tests are now green. Please rebase your branch of Products.CMFPlone and we can merge the whole thing.

**Comment by jensens** [comment]
I rebased (and recompiled the plone and plone-logged-in resources) and started the tests for all 4 PRs.

**Comment by tkimnguyen** [comment]
I never got around to making the PR for namedfile packages...

**Comment by jensens** [comment]
I merged them all.

**Comment by hvelarde** [comment]
seems we can close this now the PR are merged.

thanks to all the involved!
