### ISSUE TITLE
Mockup Issues to be fixed before Plone 5.1 release

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2124]
A collection of mockup issues which should be considered to be fixed before a final Plone 5.1 release:

- [ ] https://github.com/plone/plone.app.widgets/issues/115
- [ ] https://github.com/plone/mockup/issues/795
- [x] https://github.com/plone/mockup/issues/716

**Comment by MrTango** [comment]
Maybe @thet can have a look at this during the sprint?

**Comment by seanupton** [comment]
I left a [post](https://community.plone.org/t/seeking-input-on-relateditems-widget-bug-for-non-site-navroots/4793) re: plone/mockup#795 on community.plone.org, trying to get some discussion and/or ideas.  I would like to work on fixing that.  Unfortunately, I think that means both a change to mockup pattern and (at least) plone.app.widgets.utils.get_relateditems_options...

I hope to work on this in the next 2 days.

**Comment by thet** [comment]
@seanupton hi, sorry to not answering questions on communtiy.plone.org

If there is something I can help with, let me know!

**Comment by tomgross** [comment]
Plone 5.1 was released so this is obsolete.
