### ISSUE TITLE
improve editing of the footer

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#2128]
In Plone 5.0.7 editing the footer requires a convoluted use of the ZMI. See https://community.plone.org/t/change-the-footer/4776/2 

We should

a) document this better
b) improve it so the footer can be edited through the normal UI

**Comment by djay** [comment]
Is the best option here to switch to tiles and layouts? @tkimnguyen

**Comment by tkimnguyen** [comment]
You're just trying to start a flame war ... again ;)

**Comment by tkimnguyen** [comment]
Assuming that Plone does go to tiles and layouts ("designs" in castlecms.io parlance) eventually, in the short term then we need to document how to edit the footer.

**Comment by fgrcon** [comment]
For now, I think one ( maybe more ) simple static portlets would do fine - no need for confusing classic ...

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
