### ISSUE TITLE
Default page not marked with star in folder listing (Plone 5.1b4)

### ISSUE THREAD

**Issue by krissik** [plone/Products.CMFPlone#2131]
I have installed Plone 5.1b4. If I have a folder with a default page this page is not marked with a little star in folder listing anymore. Is it a bug? In 5.1b3 there was a star in front of the icon.

![default-page-not-marked-with-red-star](https://user-images.githubusercontent.com/5301889/29864942-75c42628-8d74-11e7-91ab-594aa02c1abd.png)

**Comment by jensens** [comment]
@thet I fear this is because of our major polishings to colder_contents... Any idea what has caused it?

**Comment by thet** [comment]
@krissik tnx for the bug report!
