### ISSUE TITLE
Move mail control panel to z3c.form.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#214]
This has been already done in the z3c.form branch of plone.app.contenttypes:

https://github.com/plone/plone.app.controlpanel/blob/plip10359-z3cform/plone/app/controlpanel/browser/mail.py

**Comment by khink** [comment]
So we can close this.

**Comment by tisto** [comment]
@khink We still need to make sure that all Plone core packages use the new mail settings lookup.

**Comment by tisto** [comment]
And I guess we should write a robot test for the mail control panel similar to https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_controlpanel_site.robot

**Comment by khink** [comment]
> We still need to make sure that all Plone core packages use the new mail settings lookup

Thanks, good point. Looking at the list i compiled above (https://github.com/plone/Products.CMFPlone/issues/214#issuecomment-61404374), we have these left:
[?] Products/CMFCore
[?] Products/CMFDefault
[?] ZConfig

But ZConfig is not Plone core code. I'll start with CMFCore and CMFDefault.

**Comment by tisto** [comment]
@khink I'm online on irc #sprint. Feel free to ping me any time... :)

**Comment by khink** [comment]
I find only these files:

parts/omelette/Products/CMFDefault/skins/zpt_generic/logged_in.py
parts/omelette/Products/CMFDefault/skins/zpt_generic/password_email.py
parts/omelette/Products/CMFDefault/skins/zpt_generic/reconfig_form.py
parts/omelette/Products/CMFDefault/skins/zpt_generic/registered_email.py
parts/omelette/Products/CMFDefault/tests/RegistrationTool.txt
parts/omelette/Products/CMFDefault/tests/test_PropertiesTool.py
parts/omelette/Products/CMFCore/exportimport/tests/test_mailhost.py

I think we should ignore them and move on to writing a test.

**Comment by MrTango** [comment]
So, we have already browser test in test_controlpanel_browser_mail.py which covers saving the settings.
I think we don't need a additional robot test by now.

**Comment by tisto** [comment]
I agree that there is an overlapping between our functional test (zope.testbrowser) and our acceptance tests (robot). Though, the functional zope.testbrowser tests do not test if the control panel settings are applied correctly. This is what the other robot tests do. The robot tests are also the documentation how the control panels work and what kind of options the user has. Therefore I think we should write those robot tests.

**Comment by tisto** [comment]
There is a regression in Plone 5.0b1. The mailhost settings (host, port, etc.) are not picked up from the registry. They are still being picked up from the MailHost object. I fixed the regression with a monkey patch:

https://github.com/plone/Products.CMFPlone/commit/9ee500d7e01e2866bea9d0a3a340298095eded92

Though, we have to write robot tests to make sure things like this don't happen in the future. In addition we should properly refactor the MailHost in the next Plone release (something we can not do right now because that would require an API change in a beta release).
