### ISSUE TITLE
Plone 5.0.7/8 user interface black toolbar in Hebrew site has incomplete/cut descriptions 

### ISSUE THREAD

**Issue by MichaelPN** [plone/Products.CMFPlone#2140]
### BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

**After creating a new site in Hebrew or changing to Hebrew and loging-in, the black toolbar on the left is BARELY USABLE if you don`t know the icon meanings, because the descriptions that are mixed in English and Hebrew are CUT-OFF, so are incomplete.**

Additionally,
someone intuitively would probably expect that **toolbar to be on the right** side for RTL languages.
The same and even MORE IMPORTANT goes for  content objects that appear in the horizontal Navigation Menu of the site .
Any page/object that you add to the site menu, **adds from left to right** on **any theme** installed. And the menu itself is on the left. It is counter-intuitive for RTL designs especially while all other objects and page descriptions are displayed right to left. 
Here is the screenshot from demo.plone.de  with all the problems visible :
https://www.dropbox.com/s/5wrmcv5wgzd5i2k/Screenshot_incomplete_descriptions.jpeg?dl=0

**Comment by MichaelPN** [comment]
This issue is also related to #2139

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
