### ISSUE TITLE
Permission plone.app.controlpanel.Imaging is unknown to imaging-controlpanel

### ISSUE THREAD

**Issue by zmijunkie** [plone/Products.CMFPlone#2145]
Hi !

Here is my workaround:

```
 pwd
/Applications/Plone51/buildout-cache/eggs/Products.CMFPlone-5.1b4-py2.7.egg/Products/CMFPlone/controlpanel/browser
[spinatgurke:CMFPlone/controlpanel/browser] alex% diff -uN configure.zcml-dist configure.zcml
--- configure.zcml-dist	2017-09-13 10:04:48.000000000 +0200
+++ configure.zcml	2017-09-13 10:42:17.000000000 +0200
@@ -264,7 +264,7 @@
       name="imaging-controlpanel"
       for="Products.CMFPlone.interfaces.IPloneSiteRoot"
       class=".imaging.ImagingControlPanel"
-      permission="plone.app.controlpanel.Imaging"
+      permission="cmf.ManagePortal"
       />
 
   <!-- Portal actions -->
```

**Comment by jensens** [comment]
it is defined in ``plone.app.imaging/src/plone/app/imaging/configure.zcml:31``. I suppose you have an Archetypes free setup, so ``plone.app.imaging`` is no longer included? I agree to replace the permission. IMO we have way too many permissions added for the control panel.

**Comment by jensens** [comment]
@zmijunkie may you provide a pull request, please?

**Comment by zmijunkie** [comment]
>I suppose you have an Archetypes free setup
I am not so sure - I have got Products.Archetypes/archetypes.referencebrowserwidget/archetypes.multilingual and archetypes.schemaextender but  maybe the order might play a role:

Products.Archetypes is pulled in line 26
Products.CMFPlone in line 28
plone.app.imaging in line 278

I will try to change the order and report in the next few days

**Comment by davisagli** [comment]
IIRC I added all these control panel permissions in the PLIP that implemented the Site Administrator role, because people wanted finer control over who can access which control panels.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
