### ISSUE TITLE
After Upgrading to Plone 5.1rc1 toolbar not visible for logged-in user without manager role

### ISSUE THREAD

**Issue by vincero** [plone/Products.CMFPlone#2146]
## BUG/PROBLEM REPORT

![screenshot-v5 1rc1-logged-in](https://user-images.githubusercontent.com/1233101/30502055-05810752-9a65-11e7-8db2-56319d1e38d3.png)

### What I did:

Generate a vanilla Plone 5.1b4 instance. Upgrade this instance to  Plone 5.1rc1. Generate in this instance a new user who has all permissions, except manager (zope manager). Login as this user.

### What I expect to happen:

The toolbar should show up at the left side of the screen.

### What actually happened:

No toolbar showing up. 
Instead of that showing up of portal-membertools link in the header section next to the search box.

(see screenshot)

### What version of Plone/ Addons I am using:

 Plone 5.1rc1 with vanilla ZODB upgraded from  Plone 5.1b4.

**Comment by pbauer** [comment]
The profile to_rc1 was not run before. Fixed with https://github.com/plone/plone.app.upgrade/pull/137
