### ISSUE TITLE
Error uninstalling archetypes.multilingual

### ISSUE THREAD

**Issue by edemir206** [plone/Products.CMFPlone#2147]
Hi,

I installed the module called archetypes.multilingual on Plone 5.0.8, I discovery I don't need to use this, but now when uninstalling it gives the error on log: ERROR root Could not uninstall archetypes.multilingual: Empty module name

What is the problem?

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
