### ISSUE TITLE
main menu is not working after changing the language to Hebrew

### ISSUE THREAD

**Issue by tmunati** [plone/Products.CMFPlone#2159]
after I change the main language to Hebrew the left main menu is not showing.

### What I did:
after I change the main language to Hebrew the left main menu is not showing.

**Comment by hvelarde** [comment]
what version of Plone? please fill the bug report properly.

**Comment by tmunati** [comment]
Plone version: 5.0.8 
I used it here
http://demo.plone.de
as admin

**Comment by hvelarde** [comment]
related with #2139

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
