### ISSUE TITLE
Move security control panel to z3c.form.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#216]
This has been already done in the z3c.form branch of plone.app.contenttypes:

https://github.com/plone/plone.app.controlpanel/blob/plip10359-z3cform/plone/app/controlpanel/browser/security.py

**Comment by tisto** [comment]
@jcerjak Any updates? We would like to close this issue if possible. If there is still work to do maybe you can give us an heads up so people at the sprint can work on that.

**Comment by jcerjak** [comment]
I've updated the list of things to fix, see: https://github.com/plone/Products.CMFPlone/issues/216#issuecomment-66923833

I'll start with the last two items on that list, I'd appreciate feedback on things that block other items.

**Comment by jcerjak** [comment]
I did some progress on this on the Alpine City Sprint, I hope to wrap it up today/tomorrow.

**Comment by jcerjak** [comment]
Pull request opened: https://github.com/plone/Products.CMFPlone/pull/362

**Comment by tisto** [comment]
Hey @jcerjak, I plan to work on this today. I just merged master into all repos. Though, I see quite a few test failures in CMFPlone now. Do you have time for a quick chat on IRC?

**Comment by tisto** [comment]
I created a Jenkins job, see console output for test failures: http://jenkins.plone.org/job/PLIP-10359/3/console

**Comment by tisto** [comment]
@jcerjak is it possible that all tests pass now?

http://jenkins.plone.org/view/PLIPs/job/PLIP-10359/8/console

After I set up the Jenkins job on the new machine all tests seem to pass. Will check on my local machine...

**Comment by jcerjak** [comment]
@tisto, if it sounds too good to be true, it probably is :)

I did:
* git pull
* bin/buildout -c plips/plip10359-security-controlpanel.cfg
* bin/test

and I get a bunch of errors. Am I missing something?

**Comment by tisto** [comment]
There must be something wrong with the Jenkins job. I get errors when I run the tests locally. BTW: running "bin/test" without any params will not work in buildout.coredev. You always have to run "bin/alltests" and "bin/alltests-at".

**Comment by tisto** [comment]
Ok, this is a configuration problem. I will investigate it further...

**Comment by jcerjak** [comment]
Ok, thanks!

**Comment by tisto** [comment]
All pull requests merged.
