### ISSUE TITLE
[Plone 5.1] Warning This product cannot be uninstalled!

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2167]
What is the current criteria in Plone 5.1 for a product not being uninstallable?
The existence of an uninstall profile?

Former versions of Plone were not that picky and allowed the deinstallation of an add-on - perhaps with some remaining data cruft. Not sure why this changed? For the sake of a dedicated uninstallation? An existing uninstallation profile does not give the guarantee for a complete uninstall without remaining cruft.

<img width="865" alt="bildschirmfoto 2017-10-05 um 20 43 33" src="https://user-images.githubusercontent.com/594239/31246564-0d114c08-aa0e-11e7-9ed7-c78bd9f18141.png">

**Comment by hvelarde** [comment]
that was discussed last year in #1340.
