### ISSUE TITLE
TinyMCE URL transformation errornous with folderish types

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2169]
Create a new folderish content type:

![Screenshot from 2022-08-24 18-23-14](https://user-images.githubusercontent.com/170891/186472513-53fa1b6a-ada6-49d4-b1bc-d855f1e2efe0.png)

![Screenshot from 2022-08-24 18-23-42](https://user-images.githubusercontent.com/170891/186472552-30a4dddf-a49d-40b9-a4f4-4477f9a440d3.png)

Add this type to a nested structure - here the path is ``/a/b``. Add a link pointing to something outside this nested structure, like ``/Members``:

![Screenshot from 2022-08-24 18-29-27](https://user-images.githubusercontent.com/170891/186472740-913647e7-2add-413c-a8cd-16b85370bfe7.png)

It will link to ``/a/Members``:

![Screenshot from 2022-08-24 18-26-00](https://user-images.githubusercontent.com/170891/186472783-03b83bf0-c10d-4e4f-be82-d6aeb24a9b45.png)

This is the html source:

![Screenshot from 2022-08-24 18-26-19](https://user-images.githubusercontent.com/170891/186472817-8e0f73af-d854-4110-9632-24f246eb9bf6.png)

Original description from 2017-10-06:

I've just got an error from a customer - without further investigation I do submit it here... I have to look into that later...

When creating a link in TinyMCE and using the "External URL" input for that, TinyMCE or whoever creates a relative URL is it's in the same domain. But in our case the relative target was wrong.

That is probably a side effect of the case that the content type is a folderish content type.

This is from where we link (a folderish document):
https://mydomain.com/bauen-in-tirol/neues-bauen-in-tirol/auszeichnung-des-landes-tirol-fuer-neues-bauen-2014

This is the target URL:
https://mydomain.com/bauen-in-tirol/architektour-tirol?atour_inc=tour&atour_id=180

And this is how TinyMCE - or whoever - rewrites it:
../../architektour-tirol?atour_inc=tour&amp;atour_id=180

Leading to:
https://mydomain.com/architektour-tirol?atour_inc=tour&atour_id=180

My quick fix was to use the internal link input and manually add the request parameters to the URL:
../../../resolveuid/00f405b285a04c6fbc0d59975e69d3f4?atour_inc=tour&amp;atour_id=180

Of course, this has to be fixed with a real fix.

Note: it's not about mydomain.com ;)

**Comment by fgrcon** [comment]
I Just crashed into the same issue but **not with a folderish type** : its just a pdf.file 

I tried to insert an external link:
https://<server>/dev/ebooks/nginx-1-web-server-implementation-cookbook-ebook.pdf/view (using document viewer) but this is also converted to 
https://<server>/ebooks/nginx-1-web-server-implementation-cookbook-ebook.pdf/view ("/dev" is eaten up  tinmce or what ever....)

How can I switch of this faulty URL conversion?  @thet any idea that could help?
(5.1.1 ...)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
