### ISSUE TITLE
manage_UndoForm broken on Plone 5.1.rc1

### ISSUE THREAD

**Issue by datakurre** [plone/Products.CMFPlone#2175]
I upgraded a site from Plone 5.0 to 5.1rc1 and noticed ```manage_UndoForm``` being broken. Is it just me or a known issue?

```
Plone 5.1rc1 (5108)
CMF 2.2.12
Zope 2.13.26
Python 2.7.13 (default, Feb 8 2017, 06:57:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
PIL 4.2.1 (Pillow)
```

```
ZEO-5.1.0
ZODB-5.3.0
```

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module App.special_dtml, line 185, in _exec
  Module App.Undo, line 112, in undoable_transactions
  Module ZODB.DB, line 951, in undoInfo
  Module ZEO.ClientStorage, line 930, in undoInfo
  Module ZEO.asyncio.client, line 764, in call
  Module ZEO.asyncio.client, line 748, in call
  Module ZEO.asyncio.client, line 756, in wait_for_result
  Module concurrent.futures._base, line 429, in result
  Module concurrent.futures._base, line 381, in __get_result
ClientDisconnected: connection lost
```

**Comment by jensens** [comment]
I am on simplest a non-ZEO local installation here and the ``Undo`` tab tells me always: 

> There are no transactions that can be undone. 


So this is indeed a problem.

**Comment by mamico** [comment]
@datakurre @jensens  try with ZopeUndo 4.3 and https://github.com/zopefoundation/ZEO/pull/96 
With those that works in my experience

**Comment by jensens** [comment]
With plone/buildout.coredev#376 (no ZEO) all works fine again.

**Comment by jensens** [comment]
@mamico do I understand correctly the ZEO problem isn't solved without the ZEO PR?

**Comment by mamico** [comment]
@jensens absolutely yes (... I think that we don't want monkey patching ZEO or ZopeUndo, right?)

**Comment by jensens** [comment]
Ok, so we have to wait for merge and release. 

@esteele - do you have the power to push things a bit forward over there? (zopefoundation/ZEO#96)

**Comment by pbauer** [comment]
@esteele The PR is merged. Now we need a release of ZEO and we can finally release Plone 5.1.

**Comment by zmijunkie** [comment]
:+1:

**Comment by esteele** [comment]
Requested a new Zeo release.

**Comment by mauritsvanrees** [comment]
This seems to have been solved five years ago.
