### ISSUE TITLE
CSS Issue in Plone 5.1RC1 on plone-demo.info

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2179]
See

https://www.plone-demo.info/images/image-1/view

or 
<img width="1414" alt="bildschirmfoto 2017-10-18 um 15 05 12" src="https://user-images.githubusercontent.com/594239/31720067-d196d582-b415-11e7-8cb6-f42e2ce841f8.png">

The image should not spread into the right portlet.

**Comment by jensens** [comment]
nice issue, but bad bug report. You should know better. How can one reproduce this in a fresh install? May you please describe all steps briefly?

**Comment by zopyx** [comment]
https://github.com/zopyx/pappnasen-plone5

`bin/instance run setup-plone.py`

**Comment by jensens** [comment]
@fgrcon btw, do you have an idea whats going on here?

**Comment by pbauer** [comment]
Thaty is a old issue and you can see it here as well: http://demo.plone.de/de/demo/a-image.jpg/view
To reproduce: Upload a image content-type and enable a right portlet.

**Comment by jensens** [comment]
@pbauer - do I get it right: old == but still an issue?

**Comment by zopyx** [comment]
The error is in all Plone 5.X versions.

**Comment by pbauer** [comment]
Yes, it is still an issue.

**Comment by MrTango** [comment]
Looks like an issue in bareloneta styles.
Should be easy to fix ;).

**Comment by fgrcon** [comment]
There are several ocurrences of this flaw:

- for plone.app.contenttypes/plone/app/contenttypes/browser/templates/image.pt :
  adding 
```
.image-product img {
    width: 100%;
    height: 100%;
}
```
![before](https://user-images.githubusercontent.com/1640384/34340623-e2672504-e987-11e7-9668-12e4755a2af0.jpg)
-->
![after](https://user-images.githubusercontent.com/1640384/34340625-e6a8b97a-e987-11e7-9df0-093086461af2.jpg)

to plonetheme.barceloneta/plonetheme/barceloneta/theme/less/image.plone.less should do the job.

- Not  sure how to handle the issue within tinymce blocks: I think the author of the page could be made responsible for correct sizing her/himself??

for #content-core  I would anyway set overflow:hidden  to avoid overlapping with portlets etc...
