### ISSUE TITLE
Best practices for making code compatible with Python2 and Python3

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2184]
Yesterday we have been discussing (see #2181) if using six is a good option for us and there seems there is consensus about it.

We are investigating ways to automate the code porting and we found out the tool [sixer](https://github.com/haypo/sixer).

We now want to write a script to automatically run sixer on our packages.

Anybody who has suggestions (or is aware of some reasons to not use this approach) is invited to discuss on this issue.

**Comment by gforcada** [comment]
My personal opinion: using sixer sound a really good idea 👍 👍 👍 👍 run it automatically on all our packages a really bad one 👎 👎 👎 

Although I guess, I have barely tried six before, that six is mostly safe, our test matrix is quite complex enough to give it one commit on each package and then have fun trying to figure out which one is responsible of the breakage.

I love this talk from this year's pycon: https://www.youtube.com/watch?v=66XoCk79kjM what relates this talk to this issue is: *"one commit one specific change"*, i.e. don't fix 300 different little changes on a single commit, because even if 300 little changes one on their own are really small and innocent, 300 at the same time are an easy way to slip simple mistakes that go unseen, because, who reviews a boring pull request doing only 300 small cleanups that spans 90 files with a diff of +1000 lines? If that same diff is split into 300 chunks is far more easier to spot where the mistake has been made (if any).

**Comment by pbauer** [comment]
I started to document to process. Feel free to update as needed.

Porting Plone packages to Python 3
==================================

Principles:
- We support Python 2 and 3 with the same codebase
- We support Python 2.7, Python 3.4, Python 3.5 and Python 3.6
- We use six and sixer to do the first steps towards python 3.
- We do the work for all packages used by the coredev branch 5.2

**Github Project**: https://github.com/plone/Products.CMFPlone/projects/4

**Meta-Ticket for porting all packages**: https://github.com/plone/Products.CMFPlone/issues/2217


Migrate a package using sixer
-----------------------------

Install sixer (https://pypi.python.org/pypi/sixer) in a fresh python3 virtualenv. sixer does not run in python 2.7

    $ python3 -m venv py3
    $ cd py3
    $ ./bin/pip install sixer
    $ source bin/activate

Pick a package to work on. Add it to https://github.com/plone/Products.CMFPlone/issues/2217 with your name.

Run sixer for a complete package in coredev to get an idea how much will need to be changed:

    $ sixer all src/plone.app.robotframework

Create a new branch for the package you are working on:

    $ cd coredev/src/plone.app.robotframework
    $ git checkout -b python3

Make all changes in-place: 

    $ sixer all -w src/plone.app.robotframework

Now you need to:

- Check if all the changes sixer made really make sense
- Add a changelog-entry: "Python 2 / 3 compatible imports. [yourname]"
- Commit 
- Make a pull-request  (e.g. https://github.com/plone/Products.CMFPlone/pull/2181)
- Run the jenkins-job for Plone 5.2: http://jenkins.plone.org/job/pull-request-5.2/build
- If the job is green
- Merge if green

**Comment by gforcada** [comment]
@pbauer thanks for putting some documentation!! ❤️ , shouldn't we put that on buildout.coredev docs folder?

May I ask one question? According to [wikipedia](https://en.wikipedia.org/wiki/CPython#Version_history) by 2020, only Python 3.6 will still be supported (ok, 3.5 as well, but only until September).

Does it make sense to support 3.4 at all? Given that our testing setup is complex enough, having to run all the tests against 2.7 and 3.6 will be already a lot of time to wait to merge pull requests,  the more python versions we try to support the longer the whole process it will be...

**Comment by pbauer** [comment]
@gforcada good question. I simply thought we would support the same version as Zope. But it makes sense to only support 3.5. and 3.6 since 3.4 reaches end of live in march next year. 
The ticket is WIP. I'll move the final text to buildout.coredev docs after the sprint in Insbruck this week.

**Comment by gforcada** [comment]
Cool 👍 have fun there!! ⛷

**Comment by pbauer** [comment]
sixer is not picking up doctests automatically. Files not ending with *.py need to be specified explicitly:

```
sixer all -w  src/plone.testing/src/plone/testing/*.rst
```

**Comment by mauritsvanrees** [comment]
Some things that sixer does not pick up:

- Python 3 has no `cmp` function anymore. For sorting it is always better to use a key instead.
- `zope.interface.implements` should become a decorator `@implementer`.  But Gil already fixed a lot of this last year.

**Comment by jnns** [comment]
As an addendum to @pbauer 's instructions to get coredev-py3 running: 

I ran into problems running `./bin/buildout -c py3.cfg` when it tried to install `zope.security`: 

> ValueError: not enough values to unpack (expected 1, got 0)

Installing it manually via `./bin/pip install zope.security` yields:

> src/zope/proxy/_zope_proxy_proxy.c:27:10: fatal error: Python.h: File or directory not found

This means that I had to install the Python3 development package (which on my system is done with `sudo apt install python3-dev`).  

Maybe this helps someone.

**Comment by gp54321** [comment]
I think that unicode could have a full blown article in your porting code guidelines.

I tried Plone Python 3 and searching for news, one of the first thing I tried, is crashing.
```
ERROR:portlets:Error while determining renderer availability of portlet ('context' '/Plone' 'news'): a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/gp/coredev_py3/eggs/plone.portlets-2.3-py3.6.egg/plone/portlets/manager.py", line 117, in _lazyLoadPortlets
    isAvailable = renderer.available
  File "/home/gp/coredev_py3/src/plone.app.portlets/plone/app/portlets/portlets/news.py", line 91, in available
    return self.data.count > 0 and len(self._data())
  File "/home/gp/coredev_py3/eggs/plone.memoize-1.2.2-py3.6.egg/plone/memoize/instance.py", line 53, in memogetter
    val = func(*args, **kwargs)
  File "/home/gp/coredev_py3/src/plone.app.portlets/plone/app/portlets/portlets/news.py", line 119, in _data
    sort_limit=limit)[:limit]
  File "/home/gp/coredev_py3/src/Products.CMFPlone/Products/CMFPlone/CatalogTool.py", line 458, in searchResults
    if not show_inactive and not self.allow_inactive(kw):
  File "/home/gp/coredev_py3/src/Products.CMFPlone/Products/CMFPlone/CatalogTool.py", line 419, in allow_inactive
    parts = path[len(site_path) + 1:].split('/')
TypeError: a bytes-like object is required, not 'str'
```
The Python error message is difficult to understand, path[len(site_path) + 1:] *is* a bytes object, that's the whole problem, if it was a str it would work.

the code:
```
        if isinstance(paths, six.string_types):
            paths = [paths]

        objs = []
        site = getSite()
        for path in list(paths):
            path = path.encode('utf-8')  # paths must not be unicode
            try:
                site_path = '/'.join(site.getPhysicalPath())
                parts = path[len(site_path) + 1:].split('/')
                parent = site.unrestrictedTraverse('/'.join(parts[:-1]))
                objs.append(parent.restrictedTraverse(parts[-1]))
```
Removing  the
          path = path.encode('utf-8')  # paths must not be unicode
line makes it work (not that it is a good fix of course)

I grepped the python code of the git-cloned coredev for encode('utf-8') and got about 250 hits.
I have tried without success to search in Github for the plone and collective organisations, I am not sure there is a way.

Not that all these hundred of hits will  be bad of course. But they could. And it may not even be especially obvious. So a guideline on Unicode and porting Plone to Python 3 could be good to have, also for add-on writers who could write not compatible code - even right now

**Comment by ale-rt** [comment]
Try:
```
path[len(site_path) + 1:].split(b'/')
```

Note the *b*. Prepending a b should work on both Py2 and Py3.

**Comment by gp54321** [comment]
@ale-rt : yes it seems to work on both Plone for Python 3 and Python 5.1.2.
My main point was that it's a specific task that could be documented in guidelines, with the patterns to search, how to fix...It can't be the one place in the code where unicode will be a problem.

**Comment by pbauer** [comment]
The docs above mostly apply to porting Plone itself. For addons this is documented in https://github.com/plone/documentation/blob/5.2/manage/upgrading/version_specific_migration/upgrade_to_python3.rst
