### ISSUE TITLE
Failing Plone 5.2 test_cooking_missing test due to subrequest handling

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2187]
This is currently the [last failing test](http://jenkins.plone.org/job/plone-5.2-python-2.7/lastBuild/testReport/Products.CMFPlone.tests.testResourceRegistries/TestResourceRegistries/test_cooking_missing/) on Jenkins for the main Plone 5.2 job. This fails:

```
  File ".../Products/CMFPlone/tests/testResourceRegistries.py", line 174, in test_cooking_missing
    self.assertTrue('Could not find resource' in resp.getBody())
```

So that is [this line](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/testResourceRegistries.py#L174) in the test. It expects that cooking a non existing resource leads to a response with 'Could not find resource' in the body.

It fails because of some [code in cook.py](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/cook.py#L110-L113). That code uses `subrequest` to get this non existing resource `'++plone++static/foobar.js'`. The result of that subrequest is a response with status 200 and a body `{"error_type": "NotFound"}`.

What apparently *used* to happen is that the response had a different status code (presumably 404) and then you end up in the [part of the code](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/cook.py#L130) that adds the expected 'Could not find resource' in the response.

Quick workaround would be to change the test to expect 'NotFound' in the body text. But the question remains: has something changed in `subrequest` or `Zope` or elsewhere to no longer give a 404 here? For our use case here it seems not so bad, but other code using subrequests may be tripped up when they get a 200 status for a javascript file that is not found.

**Comment by jensens** [comment]
A subrequest has to return sane status codes. Mosaic will get problems too if this happens. So, we need to find the source of the changed behavior.

**Comment by pbauer** [comment]
I'm pretty sure @davisagli knows where this change originates since he already dealt with many issues regarding the changed error-handling in Zope 4.

**Comment by mauritsvanrees** [comment]
When I switch to `plone.subrequest` 1.7.0 it works (though probably some other tests fail). 1.8 works too.  1.8.4 is the first version that fails.  The difference is in [these lines](https://github.com/plone/plone.subrequest/blob/master/plone/subrequest/__init__.py#L166-L171). In previous versions, `response.exception` would be called and that would set an error status.  Now an exception view is looked up, and no status is set there.

The exception view in our case is [CMFPlone/browser/exceptions.py](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/exceptions.py) and I do not see a status getting set there.

@davisagli made a change there three days ago, commit 3abf5f822eeeffc1963b874366607aa37a842ddb, but going back to the commit before that does not fix the test.

@davisagli Does it make sense to set the status in the CMFPlone exception view? Or would this need a change elsewhere?

**Comment by mauritsvanrees** [comment]
Well, seems to make sense anyway. I have pushed a branch with this and will make a pull request.

**Comment by mauritsvanrees** [comment]
Yes! That fixes the failure and introduces no other test errors.

**Comment by mauritsvanrees** [comment]
Strange, after merge, Jenkins 5.2 Python reports zero test failures, but the build is *not* marked as successful. When I check the [console log](http://jenkins.plone.org/job/plone-5.2-python-2.7/55/console) I do see an error in test teardown:

```
Running plone.app.testing.bbb.PloneTestCase:Functional tests:
  Tear down plone.app.relationfield.testing.plone.app.relationfield:Functional in 0.000 seconds.
  Tear down plone.app.relationfield.testing.PloneAppRelationfieldFixture in 0.004 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.240 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.003 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 1.163 seconds.
  Set up plone.app.testing.bbb.PloneTestCase:Functional in 0.000 seconds.
/home/jenkins/workspace/plone-5.2-python-2.7/src/Products.CMFCore/Products/CMFCore/DirectoryView.py:424: UserWarning: DirectoryView classic_ecmascript refers to a non-existing path 'plonetheme.classic:skins/classic_ecmascript'
  (self.id, reg_key), UserWarning)
Traceback (most recent call last):
  File "/home/jenkins/workspace/plone-5.2-python-2.7/bin/test", line 428, in <module>
    '--test-path', '/home/jenkins/.buildout/eggs/zope.globalrequest-1.4-py2.7.egg',
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 73, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 160, in run
    self.run_tests()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 242, in run_tests
    self.skipped, self.import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 411, in run_layer
    import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 331, in run_tests
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 370, in run
    result.stopTest(self)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 839, in stopTest
    self.testTearDown()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 764, in testTearDown
    layer.testTearDown()
  File "/home/jenkins/workspace/plone-5.2-python-2.7/src/plone.app.testing/plone/app/testing/layers.py", line 279, in testTearDown
    self.tearDownEnvironment(self['portal'])
  File "/home/jenkins/workspace/plone-5.2-python-2.7/src/plone.app.testing/plone/app/testing/layers.py", line 316, in tearDownEnvironment
    cache = queryUtility(IRAMCache)
  File "/home/jenkins/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 172, in queryUtility
    return getSiteManager(context).queryUtility(interface, name, default)
  File "/home/jenkins/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 281, in queryUtility
    return self.utilities.lookup((), provided, name, default)
AttributeError: 'PersistentAdapterRegistry' object has no attribute 'lookup'
#### Finished tests for group plone_app_testing ####
```

I guess it makes sense that a failure during teardown gives a broken build, even though all tests have passed.
I have restarted the build to see if this is just a temporary problem. If it fails again, then this is a different issue.

**Comment by mauritsvanrees** [comment]
The teardown is not a temporary problem. [New issue opened.](https://github.com/plone/Products.CMFPlone/issues/2192)
