### ISSUE TITLE
Translations in  folder_contents are incomplete

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2188]
Partly this looks like a regression to 5.1b4. The translation coverage was better there. 

### What I did:

- Install Plone 5.1rc1 and set a language different to English.
- Go to folder_contents of the site or a folder.

### What I expect to happen:

 * All actions are translated to the selected language.

### What actually happened:

 * NOT all actions are translated to the selected language.

![grafik](https://user-images.githubusercontent.com/339384/31934935-c32acfc0-b8ad-11e7-8172-b05d6160e88a.png)

### What version of Plone/ Addons I am using:

 * Plone 5.1rc1

**Comment by mauritsvanrees** [comment]
When I search for 'Move to top of folder' I only find this in `mockup/patterns/structure/js/actionmenu.js`. So it has something to do with Javascript translations.
@thet Does this ring a bell for you?

**Comment by terapyon** [comment]
I want to fix it.

**Comment by vincentfretin** [comment]
The issue with those actions Copy, Move to top of folder, Move to bottom of folder, Set as default page still exists.

There is an issue about two messages in the properties dialog too #2313

Still an issue:
- review states are not translated
- tooltip on action "Open" not translated
- in the filter dialog, "No sorting" not translated

**Comment by vincentfretin** [comment]
There is an issue with the "last modified" line #2953 too.

**Comment by vincentfretin** [comment]
Does anyone has the knowledge how to debug this? Like how do we modify the files of mockup and see the changes in a buildout.coredev 5.2?
Maybe someone who did the latest mockup / plone.staticresources bundle recently can tell us? @thet maybe?

**Comment by vincentfretin** [comment]
I only know how to create widgets.pot from the https://github.com/plone/mockup/ repository with `yarn && make i18n-dump` and copy it in plone.app.locales/plone/app/locales/locales/widgets.pot and then run `bin/i18n widgets` from buildout.coredev 5.2.
What I don't know is how to modify the mockup javascripts files and see the changes in Plone.

**Comment by vincentfretin** [comment]
@thet @davisagli @adam139 @parruc @frapell Do you know how to modify mockup files and see the changes in Plone? I see what I need to change to fix #3120 but I don't know how to test it.

**Comment by frapell** [comment]
@vincentfretin You need to go to the site setup, and then to the "Resource registries". In there you should see a checkbox that will enable "Dev mode" for resources. Next, you can enable dev mode for JS or CSS resources (I believe in your case you will only want to enable JS) I think the bundle you are looking for is "plone-logged-in" but it could be some other, I don't remember at this time.

**Comment by vincentfretin** [comment]
Thanks you @frapell ! Now we're talking.
So from buildout.coredev, if you change something in src/mockup/mockup/patterns/structure/js/actionmenu.js
and want to see the change:
Go to Site Setup->Resource Registries, click on "Development Mode(only logged in users)" checkbox, then on "Develop Javascript" button for the plone-editor-tools bundle and then click the "Save" button.

**Comment by vincentfretin** [comment]
OMG how does this stuff works? I started to write documentation of what I know there https://github.com/plone/Products.CMFPlone/issues/2188
How do you make changes to the translations and see the changes? Does the translation needs to be converted in json or something? How does it works?

**Comment by vincentfretin** [comment]
I found out. The translations are handled by mockup/js/i18n.js that calls the plonejsi18n view in plone.app.content apparently to generate a live json from the mo file. The view is called one time for a given domain and language and the result is cached in localStorage for 24 hours. The only way to test the new translations is to restart the instance to update the mo file from the po file, and then to purge the localStorage to trigger a new download of the translations.

**Comment by frapell** [comment]
@vincentfretin I don't know much about the translations, and I didn't know they were cached for 24 hours in localstorage, isn't there a way to avoid that in development? I can imagine being a total pain when adding new translations

**Comment by frapell** [comment]
@vincentfretin Maybe @thet knows?

**Comment by vincentfretin** [comment]
@frapell There is no way no, look at the code 
https://github.com/plone/mockup/blob/0f4e1d014f305723bdbc7bd8826218ac69168d62/mockup/js/i18n.js#L75-L79
There is no develop flag or anything.

**Comment by vincentfretin** [comment]
I'm not going to work on it myself. So anybody feel free to continue from here.
I documented how to live debug this in https://github.com/plone/mockup/pull/985
I'm sure some of the issues I listed in https://github.com/plone/Products.CMFPlone/issues/2188#issuecomment-646535054
can be fixed similarly to other fixes that have already been done like https://github.com/plone/Products.CMFPlone/issues/3120 @djowett-ftw if you want to try.

**Comment by vincentfretin** [comment]
@pbauer is one of a few that did know the caching issue in localStorage in 2015 :-)
https://github.com/plone/mockup/issues/537#issuecomment-124117941

**Comment by vincentfretin** [comment]
There is actually a dedicated issue for the review state column: https://github.com/plone/Products.CMFPlone/issues/2419

**Comment by vincentfretin** [comment]
@erral started a branch in mockup https://github.com/plone/mockup/pull/992 to fix some of the issues of the list https://github.com/plone/Products.CMFPlone/issues/2188#issuecomment-646535054
Thanks you!
If anyone else wants to contribute, please do! :-)

**Comment by erral** [comment]
I will create specific issues for some of the items described above, because some of them are hard to track down.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
