### ISSUE TITLE
traversal fails with portal from getPortalObject()

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2194]
In Plone 5.2 with CMF 2.4 traversal with a portal returned by `url_tool.getPortalObject()` fails since it can not acquire the request. `unrestrictedTraverse` needs that though. Found when debugging `test ./bin/test -t testIconLookupForUnknownMimeType`

```
>>> from zope.component import getUtility
>>> from Products.CMFCore.interfaces import IURLTool
>>> portal_url = getUtility(IURLTool)
>>> portal = portal.getPortalObject()
>>> portal.aq_chain
[<PloneSite at /Plone>, <Application at >]

>>> portal.unrestrictedTraverse('foo')
*** AttributeError: REQUEST

>>> from plone import api
>>> portal = api.portal.get()
>>> portal.aq_chain
[<PloneSite at /Plone>, <Application at >, <ZPublisher.BaseRequest.RequestContainer object at 0x10acc66d0>]

>>> portal.unrestrictedTraverse('foo')
*** KeyError: 'foo'
```

**Comment by davisagli** [comment]
You have to get portal_url using getToolByName in order for it to include the request in the acquisition chain. five.localsitemanager removes the request for utility lookups so that it doesn't get cached by the ZCA

David Glick
(mobile)

**Comment by pbauer** [comment]
Yes, but the lookup happens in `DynamicType` which is in CMF when doing `portal['some_file'].getIcon()` as done in the test `testIconLookupForUnknownMimeType`.

**Comment by davisagli** [comment]
Okay. Then I think my `getPortalObject` which I added to CMFPlone's URLTool is not correct. We should go back to the CMFCore version, but I'll need to follow up with a small fix to that for one of the other failures.

**Comment by pbauer** [comment]
@davisagli any idea when you might get around to doing that?

**Comment by davisagli** [comment]
I'll try to take a look tomorrow.

**Comment by davisagli** [comment]
I took a look but haven't been able to get it right yet.

**Comment by perrinjerome** [comment]
I was debugging the same issue using `Products.CMFCore` without plone and I was thinking of fixing it with the same approach that was used in #2205 . Is it OK to "steal" this patch in CMFCore ? ( I made https://github.com/zopefoundation/Products.CMFCore/pull/126 for that )
