### ISSUE TITLE
5.1RC1: mixture of IDs and texts in folder_contents view

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2201]
See screenshots..the dropdown shows several IDs instead of the related texts.

<img width="1298" alt="bildschirmfoto 2017-10-30 um 17 23 16" src="https://user-images.githubusercontent.com/594239/32182540-3fc1d798-bd97-11e7-891f-d48510014489.png">

**Comment by zopyx** [comment]
The report is also true for buildout.coredev as of today

**Comment by Jigar3** [comment]
I would like to work on this issue. Can you guide me on how to solve this

**Comment by ale-rt** [comment]
@Jigar3 This is the file where the magic happens: https://github.com/plone/plone.app.content/blob/3401b8470188cb83cfcffec6a13cf4f8926d0a96/plone/app/content/browser/contents/__init__.py#L242
I would say that many of those indexes should not even be there.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
