### ISSUE TITLE
Can't save static text portlet if mime type changed

### ISSUE THREAD

**Issue by sgmentzer** [plone/Products.CMFPlone#2210]
On a fresh install of 5.1rc1, changing the mime type (editor) when adding a static text portlet hangs with a spinner upon saving, and the JS error below appears in the browser console.

Also happens if you just change the mime type, then change it back so TinyMCE re-appears.

    TypeError: a.tiny is undefined  plone-logged-in-compiled.js:73963:12
      init/</< plone-logged-in-compiled.js:73963:12
      dispatch http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:8497
      b.dispatch plone-compiled.js:8023:8
      add/r.handle http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:5235
      trigger http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:7648
      trigger/< http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:15509
      each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:2973
      each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:833
      trigger http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:15488
      handleFormAction plone-compiled.js:16698:8
      form/</</< plone-compiled.js:16651:16
      dispatch http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:8497
      b.dispatch plone-compiled.js:8023:8
      add/r.handle http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:5235
      trigger http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:7648
      trigger/< http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:15509
      each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:2973
      each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:833
      trigger http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:15488
      render/</< plone-compiled.js:16886:14
      dispatch http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:8497
      b.dispatch plone-compiled.js:8023:8
      add/r.handle http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:5235
  
**Versions:**

* Plone 5.1rc1 (5108)
* CMF 2.2.12
* Zope 2.13.26
* Python 2.7.9 (default, Oct 18 2017, 02:13:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
* PIL 4.2.1 (Pillow)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
