### ISSUE TITLE
Navigation tree depth level zero doesn't show all levels

### ISSUE THREAD

**Issue by ivanteoh** [plone/Products.CMFPlone#2220]
### What I did:

I created multi level of folders and pages and then I clicked on a page on level 3. Navigation portlet configuration is default, which is 'start level' 1 and  'Navigation tree depth' 0.

### What I expect to happen:

Side navigation shows all the levels till level 3.

### What actually happened:

Side navigation shows the first level.

### What version of Plone/ Addons I am using:

Plone 5.0.10.dev0 and commit 'aeadee9e59a59af' of CMFPlone.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
