### ISSUE TITLE
PLIP: bring back JS and CSS head slots

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#2221]
## Abstract

It's another step backwards [having to create a bundle](https://docs.plone.org/manage/upgrading/version_specific_migration/p4x_to_p5x_upgrade.html#conditional-resources) to add a couple of lines of JS or CSS on a single template.

## Motivation

Make the life of developers and integrators easier.

In the past I was able to easily add JS or CSS by using this on a template:

```xml
<metal:slot fill-slot="javascript_head_slot">
...
</metal:slot>
<metal:slot fill-slot="css_slot">
...
</metal:slot>
```

**Comment by agitator** [comment]
isn't https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#controlling-resource-and-bundle-rendering doing what you're looking for?

examples: https://docs.plone.org/manage/upgrading/version_specific_migration/p4x_to_p5x_upgrade.html
https://training.plone.org/5/javascript/exercises/2.html#load-your-javascript-resource

**Comment by jensens** [comment]
@hvelarde Peters suggestion is exact the solution you're looking for.: Adding a single css/js for a specific view. 

So yes, you have to register a bundle, which is imo ok (can be a non-compiling one). But you don't need to apply it globally or via condition, you can just add it in your view.

**Comment by hvelarde** [comment]
guys, I know that can be done that way, but, why complicate even more the life of the developers/integrators for free? why this was removed on the first place? what problem the removal sovles? IMO, this is not solving anything and creates more burden for free.

my package has no static resources registration, I just want to put a form button side by side of an input, and I only want a `Reset` button.

**Comment by jensens** [comment]
cc @thet - do you have an idea how to solve the it's-just-a-tiny-javascript-snippet problem in an easier/ better way?

**Comment by ebrehault** [comment]
@hvelarde it is an interesting PLIP as it is a small change and can help with compatibility of old packages. Could you finish up the PLIP description so the Framework team can vote?

**Comment by ale-rt** [comment]
It looks like the slots are still there:

- https://github.com/plone/Products.CMFPlone/blob/243c913b0af73d168aca1af61d7d63bbc5572751/Products/CMFPlone/browser/templates/main_template.pt#L35

And they are used in the core:

- https://github.com/plone/plone.app.viewletmanager/blob/master/plone/app/viewletmanager/manage-viewlets.pt#L9

I think this is just a misinterpretation of the documentation.

**Comment by hvelarde** [comment]
yes, the slots are there, but there are not working as expected: the CSS is not included (probably because the name is wrong) and the JS is inserted inside the body.

I need to test again.

**Comment by hvelarde** [comment]
with our new approach we don't need this anymore.
