### ISSUE TITLE
pattern.relatedItems.less style sheet could not be loaded

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#2222]
### What I did:

Install brand new Plone site and it displays the following error on the console:

![selection_023](https://user-images.githubusercontent.com/341393/33156596-68764b58-cfe2-11e7-89a2-2f80b9b18b2b.png)

### What version of Plone/ Addons I am using:

Plone 5.1rc1 with collective.fingerpointing installed from [branch feature-17](https://github.com/collective/collective.fingerpointing/tree/feature-17) (it doesn't register any static resources).

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
