### ISSUE TITLE
CSS navigation tree issues in Plone 5.1RC1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2225]
Create a Folder and add two news items with lead image:
![navi](https://user-images.githubusercontent.com/594239/33266741-20681f1a-d377-11e7-8c93-f0eb5621ecd9.png)

1) the line break and the rendering of the 2nd item looks weird and broken
2) The positioning of the right arrow in the navigation is supposed to be where? Aligned with the top or the bottom?
3) lead image and arrow right overlap ...looks ugly and unprofessional.
![navi2](https://user-images.githubusercontent.com/594239/33266888-922062a2-d377-11e7-8e00-70f323649aef.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
