### ISSUE TITLE
Unhandled error in folder_factories when submitting the form without selection

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2230]
Plone 5.1

Submitting the folder_factories form without a selection gives an error

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.app.content.browser.folderfactories, line 32, in __call__
    Module Products.CMFPlone.URLTool, line 35, in isURLInPortal
    Module re, line 155, in sub

TypeError: expected string or buffer```

**Comment by zopyx** [comment]
<img width="1073" alt="bildschirmfoto 2017-11-30 um 15 14 25" src="https://user-images.githubusercontent.com/594239/33435066-7c13377a-d5e1-11e7-8b27-16d4af562263.png">

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
