### ISSUE TITLE
Copying a default page copies the parent with all it's children

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2237]
Moment ... there is something else going on here.
Got the same result with the default page being deactivated.

Maybe it has something to do with the following error, when i tried to rename the id from ``index`` to ``index-bak``

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 233, in __call__
  Module z3c.form.form, line 228, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.content.browser.actions, line 168, in handle_rename
  Module OFS.CopySupport, line 334, in manage_renameObjects
  Module Products.CMFPlone.PloneFolder, line 88, in manage_renameObject
  Module OFS.CopySupport, line 355, in manage_renameObject
ResourceLockedError: Object "index" is locked via WebDAV
```

### What I did:

In folder_contents I copied the default page on the start site and pasted it somewhere.

### What I expect to happen:

The page should have been pasted in no time.

### What actually happened:

The spinner was spinning, the /tmp directory on the filesystem was growing until no space was left (100GB site, 1.7GB /tmp), the action did not complete successfully althouth the ``folder_contents`` portal message told me: "Successfully copied items" folder contents message but also "Error performing action" popup.

I suspect, when copying a default page not the default page but the whole site is copied.

### What version of Plone/ Addons I am using:

5.1rc2-pending

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
