### ISSUE TITLE
TinyMCE: "Insert Media" of internal audio file fails 

### ISSUE THREAD

**Issue by ksuess** [plone/Products.CMFPlone#2240]
### What I did:
Used "insert media" with an internal audio file address like 
http://bluechurch.example.com/marketplace/06-grace-kelly.mp3/view

### What I expect to happen:
Generation of a node like
`<audio controls="controls">
    <source src="http://bluechurch.example.com/marketplace/06-grace-kelly.mp3/@@download/file/06 Grace Kelly.mp3" type="audio/mpeg">
  </audio>`
or
`<audio controls="controls">
    <source src="/marketplace/06-grace-kelly.mp3" type="audio/mpeg">
  </audio>`

### What actually happened:

A video node is created instead of an audio node.
![cd_release_susi_ _blue_church](https://user-images.githubusercontent.com/1144737/33542654-46f3b592-d8d4-11e7-9f1d-a1e71d9fc6c9.jpg)
![cd_release_susi_ _blue_church](https://user-images.githubusercontent.com/1144737/33542729-90a0f02e-d8d4-11e7-878d-903973f2a923.jpg)

Also the use of the address without "/view" in "insert media" fails with
`<audio controls="controls">
    <source src="../06-grace-kelly.mp3" type="audio/mpeg">
  </audio>`
That seems to be correct, but doesn't play the audio. 

### What version of Plone/ Addons I am using:
5.1rc1 (5.1-latest)

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
