### ISSUE TITLE
RelatedItemsFieldWidget fails

### ISSUE THREAD

**Issue by ksuess** [plone/Products.CMFPlone#2241]
### What I did:
Used RelatedItemsFieldWidget for a field of a custom Dexterity type.

    eventlocation = RelationChoice(
        title=_(u"Location"),
        required=True,
        vocabulary='plone.app.vocabularies.Catalog',
        )
    widget(
        'eventlocation',
        RelatedItemsFieldWidget,
        pattern_options={
            'selectableTypes': ['bluechurchlocation',],
            'basePath': get_locations_base_path,
            }
        )
Its not the only field with RelatedItemsFieldWidget.

### What I expect to happen:
Field where user can select an object to relate to.
![sardana_mit_xavi_pidgi_ _blue_church](https://user-images.githubusercontent.com/1144737/33546841-66b9d998-d8e2-11e7-9f02-791818fa4456.jpg)

### What actually happened:
The uid of the former selected and saved related object is displayed
![sardana_mit_xavi_pidgi_ _blue_church_and_new_issue_ _plone_products_cmfplone](https://user-images.githubusercontent.com/1144737/33546504-76c1dc38-d8e1-11e7-844d-c0a96b17db68.jpg)

or even worse the uid is not shown:
![sardana_mit_xavi_pidgi_ _blue_church 2](https://user-images.githubusercontent.com/1144737/33547349-1dbd59f2-d8e4-11e7-9979-2f8486dab8ac.jpg)

### What version of Plone/ Addons I am using:
5.1rc1 (5.1-latest)

## Assumptions

select2.js fails in updateSelection  https://github.com/plone/Products.CMFPlone/blob/85475602e9e6d0f0861137bdea7b485ae2406e7b/Products/CMFPlone/static/components/select2/select2.js#L3156

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

Also, I think this was fixed long time ago.
