### ISSUE TITLE
Can we have a automatic run of our tests after a commit to Zope?

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2244]
https://github.com/zopefoundation/Zope/commit/e2f83e6c26204477fc860cbf66e5b766e5e663f7 broke the 5.2-AT build at http://jenkins.plone.org/job/plone-5.2-python-2.7-at/. 

I only found out after testing all the commits in Zope since the last passing build since mr.roboto (or whoever) does not trigger an automatic build even though Zope is in the checkouts for the 5.2-coredev.

**Comment by gforcada** [comment]
If I get access to the zopefoundation organization, yes, we could make mr.roboto also trigger Jenkins jobs.  Who should I ping for getting that access?

Meanwhile we can run them on an hourly basis as well...

**Comment by davisagli** [comment]
@gforcada if you've signed the Zope contributor agreement then @hannosch or @tseaver can do that. If not and it's a matter of adding a webhook I have access to do that.

**Comment by pbauer** [comment]
I fixed the issue and the build is green again. I started it by hand.

**Comment by gforcada** [comment]
@pbauer are we tracking released eggs or git checkouts from zope packages? If we want to have just the same like in Plone, that for every package listed in sources.cfg a build is triggered, we should make mr.roboto be able to talk and get info from zopefoundation github org.

If the build twice a day is enough for now, we can go with that as well.

**Comment by pbauer** [comment]
Anything is better than nothing, so I'd say enable two builds a day and then enable builds for commits to checkouts from github.com/zopefoundation. We not only checkout Zope but also Products.CMFCore, AccessControl and probably some more. It might even be good to be able to integrate pull-request-jobs like we do for plone packages.

**Comment by gforcada** [comment]
@pbauer then we do really need full access for mr.roboto to Zope and me admin access as well.

@davisagli where's that contributor agreement that I need to sign? 🙂

**Comment by tseaver** [comment]
[ZopeFoundation_Committer_Agreement-2013.pdf](https://github.com/plone/Products.CMFPlone/files/1552832/ZopeFoundation_Committer_Agreement-2013.pdf)

**Comment by gforcada** [comment]
I can never get around to get a grip on cronjob scheduling, but finally I made it: 5.2 jobs are already scheduled to run twice a day.

**Comment by gforcada** [comment]
I guess that this is already too late now, or there is still need for it? :thinking: Reopen if so!
