### ISSUE TITLE
Is not possible to disable TinyMCE menu items

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#2245]
Customer ask for removing the "Align" menu item at all (and other menus too).

I tried to empty it by providing an emtpy registry collection, but the menu entry is still displayed.

An easy fix can be to not put menu entries in case there's not items, like there:

https://github.com/plone/Products.CMFPlone/blob/6dd64f562576ecf47e067d0ed4a8564ab7e1c653/Products/CMFPlone/patterns/tinymce.py#L102

**Comment by ale-rt** [comment]
This should be fixed by #2335, am I right?
