### ISSUE TITLE
plone 5.2 / 5.1  confusing versions .....

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#2251]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)
branch **master** ( referred in sources.cfg for **5.2**)  currently   version = '**5.1rc2.dev0**'
branch 5.1x (referred in sources.cfg for 5.1)  currently   version = '5.1rc3.dev0' .... 
5.1.1. .....

**Comment by fgrcon** [comment]
@jensens @esteele ????

**Comment by jensens** [comment]
There's work in 5.2 done already, so yes there's a branch. But what's the problem? Why is it so confusing?

**Comment by fgrcon** [comment]
Maybe I'm just  to stupid to understand the Plone  versioning scheme?

coredev Plone5.2 > sources.cfg:  Products.CMFPlone = master   -> setup.py : 5.1rc2.dev0
 I supposed this should rather be something like 5.2.dev0 ????

**Comment by jensens** [comment]
I think you're right about that, seems like we missed an increase here.
