### ISSUE TITLE
PLIP: Use Web Components instead of Patterns for Mockup.

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2253]
## Abstract

Web Components is a developing W3C standard for reusable widgets and components for websites.
The goal is similar to Mockup and it's underlying framework Patterns, with the big difference that web components are added to the HTML and DOM specifications and that Web Components implementations are available which have with widespread industry support.

Also web components plays well with other frameworks and concepts like ReactJS and Redux.

The most popular implementation of Web Components is Google's Polymer.
Polymer is even used for Sites like YouTube, Google Earth, Google Music and others.

## Motivation

Provide a future proof framework for Plone's JavaScript. Mockup is only used by Plone and Patterns isn't widely used either. The developer community is relative small, the underlying technology not anymore state of the art (heavy usage of jQuery).

To let Plone be part of top of modern web frameworks we have to reconsider and change our JavaScript frameworks.

I believe Web Components and specifically the Polymer implementation to be our best fit to adress this problem. It's simple to use for integrators and designers and exactly solves the problem we adress with Mockup.

## Assumptions

- A working group doing the development work can be established and developer time shared among some companies.
- Optimally, the work on this matter can be funded.
- TTW compilation of JS and LESS is going to be removed.
- Browser support below IE 11 isn't necessary at the time Plone 6 is released (which is likely).

## Proposal & Implementation

- Use plone.restapi as a unified API/data endpoints to Plone (which is a precondition for any new generation of Mockup, whatever the technological basis will be).
- Use existing and well maintained components for as many Mockup patterns as possible.
- Re-Implement missing Plone specific Patterns as Web Components.
- Distribute these Patterns under the Mockup umbrella.
- Unify plone.app.z3cform and plone.app.widgets into one package and support web components there.
- Necessary changes to Products.CMFPlone.patterns
- Resource Registry simplifications: Drop TTW support for compilation of JS and LESS, drop RequireJS and use ES6 imports and the current JavaScript build system (Webpack) instead. Still use a simplified version of the resource registry for delivering JavaScript and CSS resources.

## Deliverables

- Because of a number of major changes and much effort to put into, this PLIP targets Plone 6 at earliest.
- Framework Team decision on that topic.
- Nominating a team leader for this PLIP.
- Installation of a working group for this PLIP.
- Developing implementations of web components for Plone.
- Changes to:
  - plone.app.z3cform,
  - plone.app.patterns,
  - Products.CMFPlone.patterns
  - Products.CMFPlone.resources
  - Mockup
  - ...

## Risks

ReactJS is a competitor to Plone's next JS framework because of it's componnentized nature.
ReactJS is currently much more popular than Polymer. However, no one knows how things will develop but Web Components have some advantages: being an official - yet developed - W3C standard, being in production by sites like YouTube and playing nice together with other frameworks like ReactJS.

## Related PLIPs

- PLIP: Resource registry improvements https://github.com/plone/Products.CMFPlone/issues/1955
- PLIP: Restructure CMFPlone static resources https://github.com/plone/Products.CMFPlone/issues/1653

## Resources

- https://en.wikipedia.org/wiki/Web_Components
- https://www.w3.org/standards/techs/components
- https://www.webcomponents.org/
- https://en.wikipedia.org/wiki/Polymer_(library)
- https://www.polymer-project.org/
- https://github.com/Polymer/polymer
- Polyfill: https://github.com/webcomponents/webcomponentsjs

## Participants

- Johannes Raggam
- If you can/want to help out, drop me a note.

**Comment by thet** [comment]
Please comment here, if there is something unclear or wrong in this PLIP.

**Comment by gforcada** [comment]
@thet can this be done in parallel and/or could an estimate of work involvement be made? i.e. with polymer we can drop x/y/z mockup patterns, and only a/b/c need to be reimplemented.

By using a specific implementation, polymer as you are suggesting, do we loose anything important that we are used to with mockup? Translations come to mind for example, I'm expecting that lots of gains (usability, accessibility, maintainability...)

Is polymer *stable*? As in: do they have release policies, development is completely open source, etc etc?

If pastanga is going to be the new UI for Plone 6, not sure if that decision is made, but at least I've heard a few times, how does that clash with it? Can they work together or are completely different targets?

**Comment by ebrehault** [comment]
This PLIP does not state clearly if we are talking about a frontend-oriented approach (similar to Plone React or Plone Angular but based on Polymer) or about a backend-oriented approach (like the current Plone 5 UI implementation mixing .pt and Mockup components).

As you named the PLIP "Use Web Components instead of Patterns for Mockup ", I guess you are considering the second option.

We already started to implement Pastanaga in both React and Angular using the frontend approach, and I really think that's where we should put our efforts.

Why do you think the backend approach is better?

**Comment by thet** [comment]
I do not think a backend based approach is better, also I did not consider the ongoing efforts with React/Angular SDKs.
I have to rethink this again. It's a WIP.
But I think web components can help to not have to implement every "widget" for every frontend framework seperately.

**Comment by tisto** [comment]
@thet do you still plan to work on this? I will remove the Plone 6 label if that's ok with you.

**Comment by thet** [comment]
I think I'll even close it. I think Volto and ask the other plone.restapi client frameworks make this PLIP obsolete.
