### ISSUE TITLE
add formatting or enable/disable option for moment.js relative datetimes

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#2254]
moment.js was all the rage and in casual circumstances presents datetimes in a useful way, but other situations require knowing the exact datetime, e.g. when you are looking at version history or workflow state change history. @jensens 

It would be useful to be able to either:

- 1: disable relative datetimes (and show absolute ones e.g. "December 26, 2017 2:36 PM" instead of "1 day ago") 

- or 2: to be able to control the format used by moment.js when displaying datetimes, e.g. from the current "format:relative" to "format:LLL" which shows localized absolute datetimes

Option 2 essentially allows you to do the equivalent of Option 1, and more.

This would require one or more settings in a control panel. We could have just one setting that applies to all views on the site, or we could have multiple settings (one for each view that uses moment.js).

It would require that the following templates be modified to look up the setting:

- plone.app.layout/plone/app/layout/viewlets/menu.pt
- plone.app.layout/plone/app/layout/viewlets/document_byline.pt
- plone.app.layout/plone/app/layout/viewlets/content_history.pt

In addition, there is a `structure` pattern option registry entry for controlling the datetimes display format in folder contents view (as described at https://community.plone.org/t/showing-dates-in-folder-contents-in-absolute-format-instead-of-relative/1839 you would set it to `{"momentFormat": "LLL"}`) so the following JavaScript files would need to be modified to look up the new setting:

- mockup/mockup/patterns/structure/js/views/table.js
- mockup/mockup/patterns/structure/pattern.js

(and these three generated JS files)
- Products.CMFPlone/Products/CMFPlone/static/plone-logged-in-compiled.js
- Products.CMFPlone/Products/CMFPlone/static/plone-logged-in-compiled.min.js
- Products.CMFPlone/Products/CMFPlone/static/plone-logged-in-compiled.min.js.map

And for good measure, we should not leave these settings buried as an obscure registry setting but instead we should expose them in a control panel.

**Comment by jensens** [comment]
moment JS is no longer used.
