### ISSUE TITLE
make Members folder private by default

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#2259]
In years of deploying Plone sites, I have never needed the Members folder to be public, and have in fact had to retract it on every site... when I remembered to. 

We should make that folder private by default.

**Comment by tkimnguyen** [comment]
by removing this line: https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/setuphandlers.py#L310

**Comment by mrsaicharan1** [comment]
Hello! I would like to look into this issue. Can I take this up?

**Comment by mrsaicharan1** [comment]
I've made the relevant change by removing public functionality of the 'members' folder. I've taken care of this issue. Thank you for the guidance!

**Comment by mauritsvanrees** [comment]
Fix by PR https://github.com/plone/plone.app.contenttypes/pull/452. Thanks!
