### ISSUE TITLE
Error using Users vocabulary with SelectFieldWidget

### ISSUE THREAD

**Issue by wohnlice** [plone/Products.CMFPlone#2261]
This crosses over both the plone.app.vocabularies and plone.app.z3cform packages, and it's not clear to me that one of them is at fault. My issue comes from a form that uses the plone.app.vocabularies.Users vocabulary on a Choice field, with the plone.app.z3cform.widget.SelectFieldWidget widget when one of the users has a special character in their full name.

### What I did:

I have a form that looks like this:

```
 from plone.supermodel import model
 from zope import schema
 from plone.autoform import directives

 class IAddUserSchema(model.Schema):
   directives.widget(
        'user',
        SelectFieldWidget,
        vocabulary='plone.app.vocabularies.Users',
   )
   user = schema.Choice(title=_(u"Connect user"),
                         description=_(
                             u"Select a user"),
                         required=False,
                         missing_value='',
                         vocabulary='plone.app.vocabularies.Users'
                         )
```

### What I expect to happen:

This works fine with no special characters in the full name, or if using AjaxSelectFieldWidget, but not SelectFieldWidget. I looked at the Plone base code and it seems this vocabulary is only being used with AjaxSelectFieldWidget for multi value fields. But in my opinion the non-ajax version really should work.

### What actually happened:

I get an HTML rendering error:

> Traceback (innermost last):
> 
>     Module ZPublisher.Publish, line 138, in publish
>     Module ZPublisher.mapply, line 77, in mapply
>     Module ZPublisher.Publish, line 48, in call_object
>     Module z3c.form.form, line 238, in __call__
>     Module z3c.form.form, line 162, in render
>     Module Products.Five.browser.pagetemplatefile, line 125, in __call__
>     Module Products.Five.browser.pagetemplatefile, line 59, in __call__
>     Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>     Module five.pt.engine, line 98, in __call__
>     Module z3c.pt.pagetemplate, line 163, in render
>     Module chameleon.zpt.template, line 261, in render
>     Module chameleon.template, line 171, in render
>     Module 5ad820c16b7611a4957d3cab911517d5.py, line 906, in render
>     Module df2651a8c2804a7490ba312b09314d44.py, line 1227, in render_master
>     Module 5ad820c16b7611a4957d3cab911517d5.py, line 868, in __fill_content
>     Module cad02139b0a8ee8d4e105df2692189bf.py, line 451, in render_fields
>     Module cad02139b0a8ee8d4e105df2692189bf.py, line 126, in render_widget_rendering
>     Module cad02139b0a8ee8d4e105df2692189bf.py, line 1069, in render_field
>     Module five.pt.expressions, line 161, in __call__
>     Module Products.Five.browser.metaconfigure, line 485, in __call__
>     Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
>     Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>     Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>     Module five.pt.engine, line 98, in __call__
>     Module z3c.pt.pagetemplate, line 163, in render
>     Module chameleon.zpt.template, line 261, in render
>     Module chameleon.template, line 191, in render
>     Module chameleon.template, line 171, in render
>     Module 6ce45fa4ac433bf981736334cb2f3fd3.py, line 591, in render
>     Module 6ce45fa4ac433bf981736334cb2f3fd3.py, line 466, in render_widget_wrapper
>     Module five.pt.expressions, line 161, in __call__
>     Module plone.app.z3cform.widget, line 90, in render
>     Module plone.app.widgets.base, line 178, in __init__
>     Module plone.app.widgets.base, line 205, in _set_items
>     Module lxml.etree, line 1031, in lxml.etree._Element.text.__set__ (src\lxml\lxml.etree.c:55347)
>     Module lxml.etree, line 711, in lxml.etree._setNodeText (src\lxml\lxml.etree.c:24667)
>     Module lxml.etree, line 699, in lxml.etree._createTextNode (src\lxml\lxml.etree.c:24516)
>     Module lxml.etree, line 1439, in lxml.etree._utf8 (src\lxml\lxml.etree.c:32441)
> 
> ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
> 
> - Expression: "widget/@@ploneform-render-widget"
> - Filename: ... rm-1.2.1-py2.7.egg\plone\app\z3cform\templates\macros.pt
> - Location: (line 98: col 81)
> - Source: ... place="structure widget/@@ploneform-render-widget"/> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> - Expression: "widget/render"
> - Filename: ... rm-1.2.1-py2.7.egg\plone\app\z3cform\templates/widget.pt - Location: (line 38: col 46)
> - Source: ... xt" tal:replace="structure widget/render"

### What version of Plone/ Addons I am using:

Plone 5.0.5.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
