### ISSUE TITLE
Plone 5.1rc2 buildout fails with "UnknownExtra: plone.namedfile 4.2.4 has no such extra feature 'blobs'"

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#2266]
I ran into this multiple times so I report it here. I have to pin plone.namedfile and plone.app.event to make my Plone 5.1rc2 buildout pass:

```
[buildout]
extends = http://dist.plone.org/release/5.1rc2/versions.cfg

[versions]
plone.namedfile = 4.2.3
plone.app.event = 3.0.6
```

Example: plone.restapi:

https://github.com/plone/plone.restapi/blob/master/plone-5.1.x.cfg

@thet any idea?

**Comment by tisto** [comment]
FYI: @sneridagh is not able to reproduce that problem on OS X. I saw the problem on Travis though. Could be that this is a Linux/Ubuntu only issue...

**Comment by tisto** [comment]
This problem is still present on Plone 5.1 final. I just created a new project from the scratch with bobtemplates.kitconcept (fork of bobtemplates.plone 2.x). I tried to check why this does not occur on bobtemplates.plone but the test setup goes over my head...

As said, I run into this in all my Plone projects (on Ubuntu) and it is hard to believe that I am the only one. cc @plone/release-team

**Comment by hvelarde** [comment]
the `[blobs]` extra had no dependencies back in 4.3 and was just present for backwards compatibility only; that extra mus have been removed at some point and now you have to find which package is still depending on that extra and just remove it.

**Comment by mauritsvanrees** [comment]
I created a new project with `bobtemplates.plone` 3 about two weeks ago, and I did not see this. This is on Mac.

**Comment by gforcada** [comment]
I could not reproduce it on Fedora 27 in a completely fresh new laptop with the following buildout:

```
[buildout]
extends = https://dist.plone.org/release/5.1/versions.cfg

parts = instance

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs = Products.CMFPlone
```
