### ISSUE TITLE
better template for pagination (nextprevious and collection pagination)

### ISSUE THREAD

**Issue by iham** [plone/Products.CMFPlone#2276]
### What I did:

while theming less/css/pt i wanted to hide the labels (eg 'next item') and change the arrows.
also the "next items" arrow is way smaller then the "previous".
<img width="431" alt="screen shot 2018-01-27 at 15 35 58" src="https://user-images.githubusercontent.com/36721/35473723-48c12e6a-0384-11e8-95cc-ce5cd9b68797.png">

### What I expect to happen:
that it will be easy by using only some less. (hide labels & :before content to change the icon)

### What actually happened:
i had to override 2 templates and the less code...
... which is more work then i thougt.

### What version of Plone/ Addons I am using:
plone 5.1

## SOLUTION
i want to change the templates a little to achieve:
 - add the arrows using css :before and content: 'unicode'
 - change the arrows to &lt/&gt as they are rendered correctly (the double arrows are actually quotes.)
 - change the less to keep the layout as is.

... because this looks pretty nice too ...
<img width="424" alt="screen shot 2018-01-27 at 17 16 54" src="https://user-images.githubusercontent.com/36721/35473850-15d79ee2-0386-11e8-8520-5ebb5a532f36.png">
<img width="293" alt="screen shot 2018-01-27 at 17 15 45" src="https://user-images.githubusercontent.com/36721/35473852-188a4bf8-0386-11e8-8d9a-09a0c301f0e5.png">
... and is customisable using css only ;)

### files touched:
plone.app.layout.nextprevious.nextprevious.pt
plone.batching.batchnavigation.pt
plonetheme.barceloneta/plonetheme/barceloneta/theme/less/pagination.plone.less

**Comment by mrsaicharan1** [comment]
Can you emphasise on what you meant by &lt/&gt?

**Comment by jensens** [comment]
this was improved a lot in Plone 6 ClassicUI and is even better in Volto.
