### ISSUE TITLE
Various alignment issues in Plone 5.1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2291]
See plone-demo.info and screenshot

* "Log in " completely unaligned
* Navigation portlet: unwanted indent, image not aligned
* portal tabs: not aligned with left border

![screenshot-www plone-demo info-2018 02 04-15-00-11](https://user-images.githubusercontent.com/594239/35778290-927f00f2-09bc-11e8-8053-5dc58d9e3a2f.png)

**Comment by ajayns** [comment]
For the login, I've thought of the following fix:

Made a few UI tweaks for it to look like a button and also aligned it.

![image](https://user-images.githubusercontent.com/20743219/36069732-0b70f63e-0f15-11e8-9fe1-30891924b5f4.png)

I feel this looks way better than what we have currently. @zopyx

**Comment by ajayns** [comment]
About the navigation alignment issue relative to the Plone logo, I don't think it's an issue cause each one of them are styled to look like buttons and have padding, which aligns them to the center of the container. This is what makes them look unaligned. But when we're at the Home, you can see its actually aligned:

![image](https://user-images.githubusercontent.com/20743219/36070150-c5d041b0-0f1a-11e8-9fe2-6453b93d1b17.png)

**Comment by ajayns** [comment]
For some reason, in the styling when I checked it out, it seems that the following is specified.
```
.portletNavigationTree .portletContent > ul > li > a::before {
    content: "";
}
```
Once that is removed it seems to be showing the icons, and looks fine:
![image](https://user-images.githubusercontent.com/20743219/36070189-cca6e5ba-0f1b-11e8-824f-13786e004891.png)

**Comment by jensens** [comment]
@ajayns is there a pull request related to your changes?

**Comment by ajayns** [comment]
Actually, I haven't been able to figure out where to find the code for this to work on. If you could guide me on where Plone stores its styling I'd love to make PRs! @jensens

**Comment by jensens** [comment]
LESS-Files are in plonetheme.barceloneta. Take a buildout.coredev branch 5.1 as a start and add plonetheme.barceloneta to the checkouts.cfg and run buildout. You will need to compile the less file. There will be a script bin/plone-compile-resources that helps you to do so. In case of any questions come back here or to https://community.plone.org for a broader audience. Make sure to read the Plone Core-Development section of https://docs.plone.org as well.

**Comment by ajayns** [comment]
@jensens Okay thanks, let me check it out!

**Comment by jensens** [comment]
Navigation alignment issue: 
I just needed it in a customization: the portal-tabs are in need of a negative left margin of 30px (2x the normal margin of 15px - iirc thats a variable and needs to be calculated in less).
my simplified customization looks like so:

```
@media (min-width: 768px) {
  #portal-globalnav {
    margin-left: -30px;
  }
}
```

Looks much cleaner now!

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
