### ISSUE TITLE
Link reset text not translated in password reset mails.

### ISSUE THREAD

**Issue by allusa** [plone/Products.CMFPlone#2293]
The text "The following link will take you to a page where you can reset your password for site_name site:" isn't translated. 

When moving from PasswordResetTool some fields were cleaned. However there is still remaining a `
i18n:domain="passwordresettool"` in
https://github.com/plone/Products.CMFPlone/blob/1db95d954fa395eaa5479a93d376b9a55030f4cc/Products/CMFPlone/browser/templates/mail_password_template.pt#L19

Should it also be cleaned @tomgross ?

**Comment by vincentfretin** [comment]
You need to remove this i18n:domain so it uses the plone domain. I will resync the translations after that.

**Comment by vincentfretin** [comment]
If you can search for any i18n:domain="passwordresettool" in other templates and remove them or use i18n:domain="plone" if there isn't one defined in a parent tag, it would be great.

**Comment by allusa** [comment]
I have only found this one.

**Comment by allusa** [comment]
Now it is in the plone domain. You may resync locales whenever possible.

**Comment by vincentfretin** [comment]
You need the fix in the 5.1.x branch as well if you want I resync the translations for Plone 5.1.

**Comment by vincentfretin** [comment]
@allusa Thanks for the PRs. I resynced the translations and even put back the translations we had in Plone 5.0.

**Comment by vincentfretin** [comment]
I released plone.app.locales 5.1.5 with the translations.

**Comment by allusa** [comment]
Many thanks @vincentfretin.

> and even put back the translations

This is very good news.
