### ISSUE TITLE
Login link looks out of place

### ISSUE THREAD

**Issue by ajayns** [plone/Products.CMFPlone#2300]
### What I did:
I was browsing Plone and the header caught my eye. The login button seemed out of alignment, as if it was randomly placed.

### What I expect to happen:
I've made a few UI tweaks for it to look like a button and also aligned it.

![image](https://user-images.githubusercontent.com/20743219/36069732-0b70f63e-0f15-11e8-9fe1-30891924b5f4.png)

### What actually happened:
This is what it currently looks like.

![image](https://user-images.githubusercontent.com/20743219/36069735-26a5925c-0f15-11e8-9718-8e489458316f.png)

### What version of Plone/ Addons I am using:
I'm using Plone 5.1

**Comment by ajayns** [comment]
#2291 Seems to already have noted this.

**Comment by kakshay21** [comment]
Good work @ajayns! 
Let's not duplicate the issue. I'm closing it.
