### ISSUE TITLE
Footer appears in center of page if no content

### ISSUE THREAD

**Issue by ajayns** [plone/Products.CMFPlone#2301]
### What I did:
In a basic Plone site I'm working on, folders such as News and Events hardly have any content and so this seems to place the footer right below the content, which is somewhat at the center of the page.

### What I expect to happen:
The footer should attach to the bottom of the viewport if less content and when more content comes, it should be at the end of the scroll. 

![image](https://user-images.githubusercontent.com/20743219/36069819-5bb1d69e-0f16-11e8-9b6c-ec1634edd746.png)

### What actually happened:
Footer appears right below the content.

![image](https://user-images.githubusercontent.com/20743219/36069823-6256fd9e-0f16-11e8-833a-46aff9dd5199.png)

### What version of Plone/ Addons I am using:
Plone 5.1

**Comment by djay** [comment]
I don't think that is a bug. The theme is designed so the content area expands or shrinks to fit the content. You have no content then it is zero height. If you want it different then customise the theme to set a minimum height.
