### ISSUE TITLE
Various UI detail problems in folder_contents  in Plone 5.1RC2

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2306]
See screenshot
![fc](https://user-images.githubusercontent.com/594239/36416288-f1745b84-1628-11e8-8efa-54e30e60684c.png)

**Comment by ajayns** [comment]
@jensens I'd like to work on this!

**Comment by jensens** [comment]
Great! Code is in mockup, structure pattern and LESS-files in plonetheme.barceloneta (afaict).

**Comment by arunkiddo** [comment]
Could I Work on this

**Comment by ajayns** [comment]
@arunkiddo I won't be available to code for a few days owing to college. So you can take it up! Do ask for any guidance.

@jensens Has provided a basic of where to look at for the code.
This [discussion](https://community.plone.org/t/setting-up-a-local-development-env-for-working-on-the-theme/5874/5) in the community could help setup your local dev env.

**Comment by vincentfretin** [comment]
For mime_type translation I fixed it in Plone 5.2.2.

**Comment by Dnouv** [comment]
Hello @zopyx and/or @vincentfretin 
Is this issue still available to work? If it is, please let me know, I would like to work on this.
Thank you!

**Comment by jensens** [comment]
@Dnouv I need to pass this question over to @thet and @MrTango.  I think this evolved with Plone 6 and ES6 upgrade a lot.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
