### ISSUE TITLE
z-index issues in folder_contents in 5.1RC2

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2307]
Seen screenshot
![zindex](https://user-images.githubusercontent.com/594239/36416514-781d3a02-1629-11e8-998d-4760ce7e515a.png)

**Comment by sunew** [comment]
Also in plone 5.1 final

![selection_547](https://user-images.githubusercontent.com/893142/37521680-de431148-2921-11e8-8b81-d74aea0646e8.png)

**Comment by vincentfretin** [comment]
Actually this one was fixed on Plone 5.2.1 but I did a regression trying to fix https://github.com/plone/Products.CMFPlone/issues/3124 for Plone 5.2.2 (not released yet)
See https://github.com/plone/mockup/pull/1002 for more details.
