### ISSUE TITLE
folder_contents 5.1RC2 - visual issue

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2310]
There should be more space between the checkboxes and the labels.
![space](https://user-images.githubusercontent.com/594239/36417091-4209df5e-162b-11e8-8c60-7fc06471cbda.png)

**Comment by ashraysinha6069** [comment]
i'm intrested in solving this issue.
can you guide me further about where can i find the  files.

**Comment by ashutoshsenger** [comment]
Hey, my self ashutosh senger and i want to fix this bug.Pls instruct me about t he resources to find the corresponding issue's code

**Comment by vincentfretin** [comment]
This is how it look likes in Plone 5.2.2:
![Capture d’écran de 2020-07-02 10-12-03](https://user-images.githubusercontent.com/112249/86333703-8bf75500-bc4c-11ea-8ea1-92ee13441dea.png)
