### ISSUE TITLE
folder_contents 5.1Rc2 - actions column

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2311]
See screenshot

* untranslated menu items (DE)
* action icons broken into two lines
![actions2](https://user-images.githubusercontent.com/594239/36419228-98511f48-1631-11e8-826b-7987e88944c1.png)

**Comment by espenmn** [comment]
Where is the screenshot ?=

**Comment by zopyx** [comment]
<img width="1411" alt="screenshot 2018-08-08 19 42 01" src="https://user-images.githubusercontent.com/594239/43854476-46c28ff8-9b43-11e8-9560-aabb2a1ad20a.png">

The markup of the `div` used for the action icons is in particular smelly. It uses `&nbsp;` that don't have any effect.

The expected result is that the icons should be display in one line.

**Comment by tmassman** [comment]
This bug is coming from a customer add-on used in the site and will be fixed there.
