### ISSUE TITLE
folder_contents 5.1RC2 partly untranslated (DE)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2312]
See screenshot
![upload](https://user-images.githubusercontent.com/594239/36417272-be55967a-162b-11e8-95fb-9a8ab97ec12d.png)

**Comment by mauritsvanrees** [comment]
This is simply not translated into German yet. You can fix it in this file: 
https://github.com/collective/plone.app.locales/blob/5.1.6/plone/app/locales/locales/de/LC_MESSAGES/widgets.po#L271-L273

**Comment by zopyx** [comment]
The overall problem is the lack of completeness and the lack of control over the state of translations before the final release. Several parts of the control panels are untranslated.

**Comment by malikrohit16** [comment]
I would like to fox this.

**Comment by mauritsvanrees** [comment]
@malikrohit16 For this you would need to be able to write German. Then it is a matter of adding changes to https://github.com/collective/plone.app.locales/blob/5.1.6/plone/app/locales/locales/de/LC_MESSAGES/widgets.po and the other German translation files.

**Comment by malikrohit16** [comment]
thanks @mauritsvanrees  I have created a PR please check it out.

**Comment by mauritsvanrees** [comment]
Ah, I indeed see you made https://github.com/collective/plone.app.locales/pull/183. I will leave it to German speakers to check that one out. :-)

**Comment by malikrohit16** [comment]
Thanks @mauritsvanrees for the help. It got merged :+1:

**Comment by vincentfretin** [comment]
This one is fixed.
![Capture d’écran de 2020-06-19 11-18-39](https://user-images.githubusercontent.com/112249/85117134-abd75380-b21e-11ea-8034-1e59f4c76e83.png)
