### ISSUE TITLE
Actions: control panel in 5.1RC2 irregular button sizes/missing translations

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2314]
See screenshot
![actions](https://user-images.githubusercontent.com/594239/36417426-3803b52e-162c-11e8-991d-9fb4e45d18a9.png)

**Comment by ShushantSood** [comment]
I want to work on this issue . how can i begin.

**Comment by malikrohit16** [comment]
hello @zopyx I would like to fix this issue. Can you tell me where to find the respective file?

**Comment by vincentfretin** [comment]
This is translated in Plone 5.2.2
![Capture d’écran de 2020-07-02 10-10-53](https://user-images.githubusercontent.com/112249/86333577-61a59780-bc4c-11ea-9409-18da6e98ee57.png)
