### ISSUE TITLE
Toolbar in 5.1RC1: clipping of text 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2315]
See photos (german UI, Chrome 64 Linux). 

Texts would be "Bearbeiten" and "Hinzufügen"...so at least one character missing.

![img_1301](https://user-images.githubusercontent.com/594239/36419923-9cdc3a32-1633-11e8-9648-a8a045ddebac.jpg)
![img_1302](https://user-images.githubusercontent.com/594239/36419925-9d0a08fe-1633-11e8-95d0-a31dc7e6a57d.jpg)

**Comment by iamar7** [comment]
@zopyx I want to work on this issue. can you tell me where i can find the required code to proceed.

**Comment by iamar7** [comment]
You can correct this by following this-:
   Toolbar -> Admin -> Site setup -> Go to control panel
   In the control panel -> Go to Resource Registry
   Enable Development mode
   In the "plone" bundle below click on develop CSS
   Go to Less variables tab
   Find the variable plone-left-toolbar-expanded and set it to 300 px or according to your use
   Hit the save button and reload the page 
   go back to Registry tab and hit the Build button for the plone module
   Now check your issue should have been solved.

![corrected](https://user-images.githubusercontent.com/20831630/37863908-4736e7dc-2f5e-11e8-9bd4-300b09b8ae8e.png)

**Comment by tmassman** [comment]
Same as #723 and fixed with hyphenation support added.
