### ISSUE TITLE
5.1-pending theme editor does not compile less theme

### ISSUE THREAD

**Issue by fredvd** [plone/Products.CMFPlone#2319]
I have installed Plone 5.1-pending from source, using our internal Plone 5.x scaffolding. Plain Plone 5.1, no other add'ons, nothing else activated in the site. 

I'm following the Plone 5 theming training on https://training.plone.org/5/theming/ttw-advanced-2.html and I'm creating a new them that inherits from Barcelona.

I've followed the guide, copied the manifest.cfg from the training page, copied index.html from barceloneta and I've created a new styles.less file with just one line: 

@import "++theme++barceloneta/less/barceloneta.plone.less";

So I'm inhering Barceloneta, but not doing any other less customisations. 
when I try to build the the file in the theming editor using the "build CSS" button, I get the following message at the top of the small popup screen: 

"Error: directive options not recognised".

When I create a copy of barceloneta theme and got to less/barceloneta.plone.less the same happens

**Comment by vincentfretin** [comment]
Oh man, I encountered this error today on Plone 5.1 for a customer that needed a simple color change in their theme. I really don't have time to debug this...
I successfully rebuilt the styles.css file with lessc command like this.

Add the following import to styles.less before the `@import "++theme++barceloneta/less/barceloneta.plone.less";` line:

    @import "++plone++static/patterns/toolbar/src/css/toolbar.plone.less";

then run the following commands

    cd ~/workspace/Project/develop/project.theme/project/theme/theme/project
    npm install less
    ln -s ~/workspace/Project/parts/omelette/plonetheme/barceloneta/theme/ '++theme++barceloneta'
    ln -s ~/workspace/Project/parts/omelette/Products/CMFPlone/static/ '++plone++static'
    ./node_modules/.bin/lessc styles.less > styles.css
    sed -i "s@url.'roboto@url('++theme++barceloneta/less/roboto@g" styles.css

**Comment by LFPSGS** [comment]
Hey guys! Tried to do just the same but can't find those directories to build the css.

The closest I found was:

/etc/plone/buildout-cache/eggs/plonetheme.barceloneta-1.8-py2.7.egg/plonetheme/barceloneta/theme

I tried to find my styles.less using linux search and nothing

Could you guys give me a hand?

Best regards,

**Comment by vincentfretin** [comment]
@LFPSGS You need to export your theme and create a package on the file system for this. Or just export the content of your styles.less in a directory on the file system, do my instructions, and reupload styles.css I guess.

**Comment by LFPSGS** [comment]
Hi @vincentfretin! I've done the following steps:

1.At the plone installation folder (just 'cos it's easier to keep it all together), I've created a folder named workspace (/etc/plone/zinstance/workspace/theme_name)
2.Downloaded my files from Plone via webUI (index.html, manifest.cfg, styles.less and rules.xml) and copied to the previously created folder.
3.Then run npm install less
4.Then run: ln -s /etc/plone/buildout-cache/eggs/Products.CMFPlone-5.1.0.1-py2.7.egg/Products/CMFPlone/static/ '++plone++static'
5.Then: ln -s /etc/plone/buildout-cache/eggs/plonetheme.barceloneta-1.8-py2.7.egg/plonetheme/barceloneta/theme '++theme++barceloneta'
6.Run: ./node_modules/.bin/lessc styles.less > styles.css
Here I had an warning: "extend ' .clearfix' has no matches" but still, the styles.css was created
7.Run: sed -i "s@url.'roboto@url('++theme++barceloneta/less/roboto@g" styles.css
8. Copied styles.css and upload it to the Plone theme folder again via webUI
9. Activated the theme and....nothing --everything is broken and had to go back to the original theme.

Any ideas where I mistake?

**Comment by LFPSGS** [comment]
Hi @vincentfretin just found what I was missing (to READ!). When I was following the example made at the Plone Training, they ask you to copy the manifest.cfg:

```
[theme]
title = Custom
description = A custom theme
doctype = <!DOCTYPE html>
development-css = ++theme++custom/styles.less
production-css = ++theme++custom/styles.css
```

But my theme was called ACME so, plone couldn't find the files, when I altered to:

```
[theme]
title = Custom
description = A custom theme
doctype = <!DOCTYPE html>
development-css = **++theme++acme**/styles.less
production-css = **++theme++acme**/styles.css
```
Every change I made started to work!

**Comment by vincentfretin** [comment]
I'm glad my instructions was helpful to you.

**Comment by tmassman** [comment]
The problem was the missing colons in `variables.plone.less`, which was fixed in https://github.com/plone/plonetheme.barceloneta/commit/28d164738a21113d15eed7bb2b8ddb4a54a2862f. This commit is included in `plonetheme.barceloneta` 1.8.1 which was released on 2018-04-08.
