### ISSUE TITLE
BUG REPORT: Some nested `section id="edit-bar"` tag in folder_contents page

### ISSUE THREAD

**Issue by terapyon** [plone/Products.CMFPlone#2322]
### What I did:

- Click any `fc-breadcrumbs` on folder_contents page
- And Re-Click the `fc-breadcrumbs`

### What I expect to happen:

I think `section id="edit-bar"` tag will not be shown  in dynamic html.

### What actually happened:

`section id="edit-bar"` tag will be made too.

**Comment by thet** [comment]
The issue is still open.
But I have a fix for it...
