### ISSUE TITLE
Language-selector broken in mobile view for 5.0 and 5.1

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2332]
When p.a.multilingual is installed the language-switcher is not useable because the search-form has a padding that overlaps it. Also it does not look very nice. 

Here is a screenshot made with 5.1 but it looks the same in 5.0:

![language switcher](https://user-images.githubusercontent.com/453208/37155980-04b0a9c8-22e5-11e8-80b0-e11a4e1ac633.png)

**Comment by ashraysinha6069** [comment]
@pbauer 
i'm intrested in solving this issue.
i've added plone.app.multilingual in eggs buildout
can you tell me where i can find the required code to proceed.

**Comment by pbauer** [comment]
@ashraysinha6069 the styles are part of of the barceloneta theme (https://github.com/plone/plonetheme.barceloneta) in the file `header.plone.less` (https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/header.plone.less). 

I'm not really good at theming so I do not know how to develop barceloneta but https://github.com/plone/plonetheme.barceloneta/blob/master/HOWTO_DEVELOP.rst might help you.

barceloneta has quite some issues that need fixing 😉

**Comment by ashraysinha6069** [comment]
@pbauer, in header.plone.less i just increased top margin for seach box in mobile view. it brings the search box in the blue nav-bar
![screenshot from 2018-03-09 17-41-25](https://user-images.githubusercontent.com/34709632/37207133-94cf561c-23c1-11e8-9a02-d544a99855bc.png)

or by changing the positioning of search-box
![screenshot from 2018-03-09 17-42-13](https://user-images.githubusercontent.com/34709632/37207670-0231ee20-23c4-11e8-9c23-4677585c2ff5.png)

**Comment by pbauer** [comment]
@sneridagh: Can someone from the Frontend-Team chip in here?

**Comment by pbauer** [comment]
@sneridagh ping!

**Comment by sneridagh** [comment]
@pbauer Sorry! I didn't see it! I'm on it!

**Comment by agitator** [comment]
I think I prefer the current order of elements, Logo/Language/Search or even move Language to the first

**Comment by Dnouv** [comment]
Hello @pbauer 
Is this issue still available to work? If it is, please let me know, I would like to work on this.
Thank you!

**Comment by ale-rt** [comment]
This is not an issue anymore.
Checked on:
- https://demo.plone.org/en (Plone 5.2.6)
- https://6-classic.demo.plone.org/ (Plone 6 alpha)
