### ISSUE TITLE
Toolbar broken in 5.1 mobile view

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2333]
The submenus do not open in 5.1 and have no arrow indicating that there are submenus:
![toolbar](https://user-images.githubusercontent.com/453208/37156281-ede0382a-22e5-11e8-858a-46b55e0cba6c.png)

In 5.0.8 it works:
![toolbar 5 0](https://user-images.githubusercontent.com/453208/37156328-156e09a8-22e6-11e8-8fa3-026043a3181a.png)

**Comment by nzambello** [comment]
I'm currently trying to resolve this issue.
@pbauer Any update in the meanwhile?

**Comment by nzambello** [comment]
@pbauer Is this solved? Could we close this?

**Comment by jensens** [comment]
I lost a bit track here. Is it solved? Is (and if, how) #2349 related or something different?

**Comment by nzambello** [comment]
In my opinion and during my tests, I consider this solved.
#2349 should be solved: it's the same stuff.

**Comment by MrTango** [comment]
Is fixed now for Plone 5.1 and 5.2

**Comment by thet** [comment]
Closing with : #2561
