### ISSUE TITLE
CSS issue with lock icons on plone-demo.info

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2339]
Portal tabs on plone-demo.info look weird.

This is plain Plone 5.1.0.

![45776436-d67e-40d2-b34b-9cb633e50a77](https://user-images.githubusercontent.com/594239/37405245-6e95ba3c-2794-11e8-8486-e66d0e6a70ba.jpeg)

**Comment by jensens** [comment]
afaik meanwhile fixed. didnt see it anymore anywhere.
