### ISSUE TITLE
Drag and drop inside folder_contents on iPad complete unusable

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2345]
Resorting content using drag and drop inside the folder contents view on Plone 5.1 only works as expected on a desktop browser.

Dragging items on iPad conflicts with the iOS system behavior, gestures etc. making DnD basically unusable on iPad.

**Comment by nehsus** [comment]
Hey, I'd like to work on this issue. I'll have a pull request up in a bit

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
