### ISSUE TITLE
plone.app.upgrade time machine problem blocks pull requests

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2346]
At the moment Pull Requests for 5.1 are broken, because of some problems with the profile version. See https://github.com/plone/Products.CMFPlone/pull/2324 and https://github.com/plone/Products.CMFPlone/pull/2342.

Involved test are: 
- Products.CMFPlone/Products/CMFPlone/tests/testMigrationTool.py", line 60
- plone/app/upgrade/tests/test_upgrade.py", line 62
- plone/app/upgrade/v50/tests.py", line 107

All above tests are checking after migration steps are executed if the current profile reached the end of the queue, so are the same as the latest available profile.
For some reason it find as latest version ``5111`` but it reached version ``5112``. So kind of a time machine here?

Fun part: The problem only occurs with PRs, not when running the tests on coredev.

I have no idea why this happens. Probably I missed something.

@mauritsvanrees b/c you digged a lot through the GS code, do you have any idea/hint?
@plone/testing-team Also: Any idea/hint?

**Comment by mauritsvanrees** [comment]
The tests will pass when the destination of the last upgrade step in plone.app.upgrade matches the profile version in Products.CMFPlone.

Current coredev 5.1 has no checkouts of these two packages, so it uses the latest releases, and the tests pass there.

Both packages already have a change in their source to handle a new version: CMFPlone has a new profile version and plone.app.upgrade has that version as destination in an upgrade step. So if you check out both packages, the tests will pass.

In the PRs you point to, only CMFPlone has changes. The PR job will checkout CMFPlone, so it will also have the profile version. Result: the tests fail.

Solution: add both packages to the checkouts of 5.1. I have done so just now in https://github.com/plone/buildout.coredev/commit/6b872af0ec691949837e88e532bfbb6579cf0872

**Comment by esteele** [comment]
Thanks, Maurits. I forgot to add those back after releasing them. Maybe the Products.CMFPlone, plone.app.upgrade, and Plone eggs should be exempted from the removal-after-release.
