### ISSUE TITLE
Collection location-criteria widget behavior differs on add and edit form

### ISSUE THREAD

**Issue by sunew** [plone/Products.CMFPlone#2348]
### What I did:

Install plone 5.1
Add a new plone site.
Add a folder.
Add some content in the folder.
Add a collection in the same folder.

On the collection add form - add a Location criteria.
Choose "Current (./)" as the value.

The content objects in the folder are shown in the preview.

Save the collection.

Nothing is shown in the view.

Edit the collection.
Preview is now empty.

Now choose "Parent (../)" as the value of the location criteria.

Now the items in the folder are shown in the preview again.
Save the collection.
The items shows up in the collection view.

Clearly 'current' on the add view is refering to the folder, while on the edit view (and the when rendering the view) it refers to the collection object itself.

### What I expect to happen:

Should "Current (./)" refer to the current folder of the collection, not the collection object itself ?

At least the behavior should be consistent.

### What version of Plone/ Addons I am using:

Plone 5.1 with no addons.

Add form:
![selection_553](https://user-images.githubusercontent.com/893142/37523953-b567d48c-2928-11e8-915e-16816ed0629d.png)

Edit form with 'current':
![selection_554](https://user-images.githubusercontent.com/893142/37523971-cac99a36-2928-11e8-8ba2-7cdc4a590170.png)

Edit form with 'parent':
![selection_555](https://user-images.githubusercontent.com/893142/37523990-d9fe61c6-2928-11e8-9dc1-b8fa88bc805b.png)

**Comment by hvelarde** [comment]
I think this happens also in Plone 4.3; I have never understood how to use the location field.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
