### ISSUE TITLE
plone-toolbar-logo 5.1 - 'toolbar_width' of undefined

### ISSUE THREAD

**Issue by Frankkyl** [plone/Products.CMFPlone#2349]
pls refe the screenshot below:
Error:
Uncaught TypeError: Cannot read property 'toolbar_width' of undefined.

![image](https://user-images.githubusercontent.com/14010337/37730484-10b9336c-2cfd-11e8-96cb-1909d72a4cbe.png)

**Comment by pigeonflight** [comment]
Can you say which version of Plone?

**Comment by petschki** [comment]
Mayer related to lately fixed mobile Toolbar? #2333

**Comment by nzambello** [comment]
This shoud be resolved by #2477, isn't it?
