### ISSUE TITLE
Why are PLIPs rocket science?

### ISSUE THREAD

**Issue by volkerjaenisch** [plone/Products.CMFPlone#2350]
Adding a PLIP is not straight forward. Let us improve this.

**Comment by volkerjaenisch** [comment]
I added an issue but where to place the :

03 type: feature (plip)

I am lost

**Comment by thet** [comment]
You can state your ideas about how to improve the PLIP process here.

Regarding the "03 type: feature (plip)" - I don't understand the question here. If it is how to add the label, you can do it on the right side under "labels".
