### ISSUE TITLE
content_status_history does not honor effectiveDate and expirationDate field's guards

### ISSUE THREAD

**Issue by sauzher** [plone/Products.CMFPlone#2352]
## BUG/PROBLEM REPORT
content_status_history renders an edit form for two quite standard ATFields: `expirationDate` and `effectiveDate`. These fields may have custom read and write permissions in custom archetype schema to match specific use cases. The cpt does not check these permissions (i.e. write_permission) before rendering related edit input widget.

### What I did:
Suppose to create a custom AT width 
```
from Products.ATContentTypes.content import schemata
CustomSchema = schemata.ATContentTypeSchema.copy()

```
and to set a write_permission on effective/expire date fields

```
from Products.CMFCore import permissions
CustomSchema['effectiveDate'].write_permission = permissions.ReviewPortalContent
CustomSchema['expirationDate'].write_permission = permissions.ReviewPortalContent

```

Now add your custom AT  and do access on it with a user with no ReviewPortalContent permission. Go to 
object_url/conten_status_history (workflow menu -> Advanced...)

### What I expect to happen:

The 'Dates' schema section actually disappears from standard edit view (right!)
I expect same beaviour in content_status_history view

### What actually happened:
I'm able to see, and successfully edit, both expiration and effective date fields.

### What version of Plone/ Addons I am using:
Plone 4.x

## Proposal & Implementation
It seems to me it is quite straighforward do add two tal:condition on content_status_history.cpt

https://github.com/plone/Products.CMFPlone/blob/32fcebc9cb48d6a4ea932845c9279b51cad555d0/Products/CMFPlone/skins/plone_forms/content_status_history.cpt#L219

```
<div class="field"
    tal:define="error errors/effective_date | nothing;
                field python:context.Schema()['effectiveDate'];
                visCondition python:field.checkPermission('w', context)"
    tal:condition="visCondition">
```
and

https://github.com/plone/Products.CMFPlone/blob/32fcebc9cb48d6a4ea932845c9279b51cad555d0/Products/CMFPlone/skins/plone_forms/content_status_history.cpt#L242
```
<div class="field"
    tal:define="error errors/expiration_date | nothing;
                field python:context.Schema()['expirationDate'];
                visCondition python:field.checkPermission('w', context)"
    tal:condition="visCondition">
```

## Risks
Actually that a developer remove from a custom AT the expirationDate or effectiveDate field. But in that case, he should take rid of a lot of other plone standard views... so almost no risks from my point of view.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
