### ISSUE TITLE
ZEO in Plone 5.1 does not store properly database index

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2354]
Just a warning:

The ZEO server of Plone 5.1 does not properly persistent the database index file.
I discovered that my migration instance re-creates the index with each ZEO restart ("Ignoring index for ...." message.

Reporting this to the ZODB tracker as well

**Comment by zopyx** [comment]
https://github.com/zopefoundation/ZODB/issues/195

**Comment by MrTango** [comment]
Hm, i had the feeling recently that there is something wrong. After adding content and couln'd find it in search results in sopme widgets like the related items. Good catch

**Comment by zopyx** [comment]
This looks then like a different problem. A data persistence problem is different from from recreating the in-memory index every time you start your instance.

**Comment by davisagli** [comment]
Is this still an issue more recently?

**Comment by zopyx** [comment]
No idea 🤷🏻‍♂️

**Comment by davisagli** [comment]
Okay, closing since it's also filed in the ZODB repo
