### ISSUE TITLE
CSS issue with lead images in navigation

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2356]
Plone 5.1.0:

![screenshot-localhost-5080-2018 03 27-08-52-41](https://user-images.githubusercontent.com/594239/37951326-53d066f4-319c-11e8-97c6-f0bb2f1b8942.png)

**Comment by fgrcon** [comment]
**I have introduced more detailed control for showing of preview images  aka thumbs and  document type icons for lists, tables (e.g.: content view)  and portlets :**

Set globally in site settings:

![global-thum-settings](https://user-images.githubusercontent.com/1640384/37964217-02f6f73c-31c1-11e8-8c20-b7f8db702aaa.jpg)

In your special case (works for all standard portlet types ...) you can override in portlet settings:
![detail-portlet-thumb-settings](https://user-images.githubusercontent.com/1640384/37964336-657467b4-31c1-11e8-825f-e3cbfaa80953.jpg)

Hope, that helps - if so: please close issue ... (Maybe I ll provide some more documentation ...)

**Comment by zopyx** [comment]
The default CSS  should give a better user experience. Right now it is possible to mess up the UI in so many ways....the defaults must be more conservative or more explicit.

**Comment by MrTango** [comment]
definitely turning them off the right choice.
I can't thing of a situation where I want thumbnails in the navigation, but for sure not by default in barceloneta.
@fgrcon could please make a sane default for this and disable thumbs for the navigation.

**Comment by jensens** [comment]
This was fixed.
