### ISSUE TITLE
CSS issues in resource registries control panel 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2357]
Plone 5.1.0
![screenshot-localhost-5080-2018 03 27-09-29-22](https://user-images.githubusercontent.com/594239/37952853-7b19aa40-31a1-11e8-9fd5-b561f6934a71.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
