### ISSUE TITLE
URL redirection no longer works for images in Plone 5

### ISSUE THREAD

**Issue by davisagli** [plone/Products.CMFPlone#2372]
In Plone 4, if you move an image then try to access its old URL, you get redirected to the new URL. In Plone 5 this works when accessing the old URL directly, but not when loading the old URL via an `img` tag (at least not in Firefox).

This is because of this code:
https://github.com/plone/Products.CMFPlone/blob/5.1.x/Products/CMFPlone/skins/plone_templates/standard_error_message.py#L30 (Plone 5.1)
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/exceptions.py#L29 (Plone 5.2)

When loading an image the browser sends `Accept: */*`, so this code returns a JSON-formatted error and never renders the standard error message template, which is where URL redirection is normally processed.

We should probably move the redirection lookup into the exception view before returning any response.

**Comment by ale-rt** [comment]
I cannot reproduce this on Plone 5.2, can you confirm this @davisagli

**Comment by davisagli** [comment]
Working in Plone 6
