### ISSUE TITLE
Navigation portlet edit screen showing portlet resource name as navigation root

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2388]
See screenshot.

As a user I expect the name/path of the current context object but displaying a resource path here makes no sense.

Plone 5.1.1
![screenshot-test dynaexamples com-2018 04 23-17-23-46](https://user-images.githubusercontent.com/594239/39136369-58a750c2-471b-11e8-904f-8ab555bc9385.png)

**Comment by jensens** [comment]
This was fixed.
