### ISSUE TITLE
Navigation portlet issue with nested folders

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2389]
See screenshot
![screenshot-test dynaexamples com-2018 04 23-18-10-44](https://user-images.githubusercontent.com/594239/39139340-eed9f080-4721-11e8-91c3-816eaa4e473d.png)

The screenshot shows a navigation portlet with a three level deep folder structure. The items on the third level which belong to "Wave..." can not be distinguished from the following items on the 2nd level.
This is totally confusing and unhelpful.

In this case the 3rd level navigation items need an extra indentation.

Navigation items on different levels must never have the same identation.

**Comment by zopyx** [comment]
The expected output is something like this here
<img width="324" alt="screenshot 2018-04-23 18 28 18" src="https://user-images.githubusercontent.com/594239/39140195-26c0e3bc-4724-11e8-9289-cd7ebe94ee2b.png">

**Comment by petschki** [comment]
should be fixed here https://github.com/plone/plonetheme.barceloneta/pull/156 (plonetheme.barceloneta >= 1.8.2)

**Comment by davisagli** [comment]
Looks okay in Plone 6
<img width="328" alt="Screen Shot 2022-08-24 at 7 05 52 PM" src="https://user-images.githubusercontent.com/49014/186557673-7f349215-272e-45c6-ad3e-821676b865a8.png">
