### ISSUE TITLE
log a message when catalog rebuilt

### ISSUE THREAD

**Issue by djowett** [plone/Products.CMFPlone#239]
"Clear and Rebuild" often takes so long browser to time out before it's complete, can we log a message to the console / log file when it's done, so we know for sure?

Probably at the end of  Products.CatalogTool.clearFindAndRebuild at a guess

**Comment by vangheem** [comment]
Fixed with https://github.com/plone/Products.CMFPlone/commit/71eb5a7d2fb0afbb0eb967b43ad988c10115ab98
