### ISSUE TITLE
Deprecate Archetypes

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2390]
According to #2368 Archetypes will not be ported to Python 3.
These are the relevant packages:

* Products.Archetypes
* Products.ATContentTypes
* plone.app.blob
* plone.app.collection
* plone.app.imaging
* plone.app.folder
* archetypes.referencebrowserwidget
* archetypes.schemaextender
* archetypes.multilingual
* Archetypes-related parts of Products.contentmigration

We need to:
* [x] deprecate the AT-packages used in the coredev
* [x] where we use it in tests it should only be a dependency when running python 2
* [x] move GopipIndex from plone.app.folder somewhere else

**Comment by hvelarde** [comment]
IIRC, plone.app.imaging is used in Dexterity-based content types also.

**Comment by davisagli** [comment]
@hvelarde plone.app.imaging isn't used for Dexterity types. They use the scaling view in plone.namedfile. The only thing I'm aware of that Dexterity used to depend on in plone.app.imaging was the setting for scale sizes, but that got moved to the registry for Plone 5.

**Comment by hvelarde** [comment]
you mean this one? https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py#L38

that's completely transparent, right? I still use the same `@@images` helper view?

**Comment by davisagli** [comment]
There are 2 different views, both named `images`. The one in plone.app.imaging adapts Archetypes content and the one in plone.namedfile adapts Dexterity content. They aim to implement the same interface; I don't know if there are bugs. ;-)
