### ISSUE TITLE
Plone 5.1 file icons referenced with absolute path 

### ISSUE THREAD

**Issue by mamoep** [plone/Products.CMFPlone#2391]
### What I did:
1. Install Plone 5.1 on RHEL7
`install.sh --target=/test/plone5 --build-python zeo`
2. Create new Plone Site with default settings
3. Add files like pdf, doc, xls
4. Configure Apache 2.4 as reverse proxy
`RewriteRule ^/News($|/.*) http://localhost:9090/VirtualHostBase/https/%{SERVER_NAME}/Plone/VirtualHostRoot/_vh_News$1 [L,P]`

### What I expect to happen:
list view & table view of the Plone folder containing the files should show the file type icon

### What actually happened:
Icons are broken. Apache Rewrite Rule doesn't work, because the icon is referenced with an absolute path, starting with /Plone
![1ac9f9fae4179d4ca292c80bed281d85f8bff3ff](https://user-images.githubusercontent.com/26142342/39171318-9fd454ee-479e-11e8-827a-c17a1e6f3e84.png)

When I open the file, the icon is shown, as it is referenced relative there. Screenshot:
![plone51_mimetype_icon_2](https://user-images.githubusercontent.com/26142342/41411596-b6785c92-6fdd-11e8-82b2-7a1427e9a6f7.png)

Mimetype registry looks ok, example:
![4237e0d907f0630f7a797b37780621b50ae3fc04](https://user-images.githubusercontent.com/26142342/39171200-5474a3be-479e-11e8-9df8-7e4083a86a5a.png)

### What version of Plone/ Addons I am using:
Plone 5.1
pas.plugins.ldap

**Comment by mamoep** [comment]
I tried to follow the code to find out more about this issue. plone.app.contenttypes uses `tal:attributes="src item/MimeTypeIcon">` in the template showing the list. MimeTypeIcon function comes from [plone.app.contentlisting](https://github.com/plone/plone.app.contentlisting/blob/c82cf3059fcf04b707d078e7afeb7ac70e393dfa/plone/app/contentlisting/contentlisting.py#L154). This function uses [getNavigationRoot from plone.app.layout ](https://github.com/plone/plone.app.layout/blob/d53e3b64119eeb431343ae22b1580c800a8a0bc1/plone/app/layout/navigation/root.py#L11) to create the path to the Mime Icon.

**Comment by maethu** [comment]
I just stumbled over this after upgrading from Plone 4.3 to 5.1.6. 


If fixed it by running: 

```python
        from Products.MimetypesRegistry.MimeTypeItem import PREFIX


        mimes_tool = api.portal.get_tool('mimetypes_registry')
        for mimetype in mimes_tool.mimetypes():
            first_mime = mimetype.mimetypes[0]
            attrs = {
                'name': first_mime,
                'new_name': first_mime,
                'mimetypes': mimetype.mimetypes,
                'extensions': mimetype.extensions,
                'icon_path': PREFIX + mimetype.icon_path,
                'binary': mimetype.binary,
                'globs': mimetype.globs,
            }

            mimes_tool.manage_editMimeType(**attrs)
```

**Comment by wkbkhard** [comment]
Probably resolved by commit https://github.com/plone/plone.app.contentlisting/pull/46, tests are ongoing
