### ISSUE TITLE
Uploaded images cannot be opened in the edit form

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2402]
When I upload an image as part of creating a News Item and then open the @@edit view, the image has a link but cannot be opened:

![image-upload-preview](https://user-images.githubusercontent.com/170891/39703328-0db6aaf2-5208-11e8-9072-147088173858.png)

Trying to open the link produces the error:
```
2018-05-07 14:57:34 ERROR Zope.SiteErrorLog 1525697854.620.512516707795 http://localhost:8080/Plone/ok7-1/@@edit/++widget++form.widgets.ILeadImage.image/@@download/Bildschirmfoto+2018-02-27+um+17.14.54.png
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.formwidget.namedfile.widget, line 376, in __call__
  Module plone.formwidget.namedfile.widget, line 69, in _make_namedfile
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by gp54321** [comment]
I can't reproduce this problem neither with 5.1.0 nor 5.1.2 pending. What's baffling is that in your trace line 69 seems included in _make_namedfile routine while it's not in all Plone version that I have on my disk, be it 5.1.0, 5.1.2, 5.0.8 or even Plone 4.3 or 5.2). Usually _make_namefile ends before line 60. And file widget.py in plone.formwidget.namedfile has about 310-320 lines, so it's unclear for me from where is coming the line 376.
So it would be interesting to add the precise Plone version to your report.

**Comment by thet** [comment]
cannot reproduce either. closing.
