### ISSUE TITLE
Plone 5.2: Remove occurences of ZODB3 in all eggs

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2404]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Currently (Plone 5.1 and 5.2) ships with both ZODB 3 AND ZODB 5. Only the newer one is used. Version 3 is pulled in via dependencies in setup.py. Since we always depend on Zope it is probably safe to assume we are using the version (pin) of the applicaton server. The following eggs need changes:

- [ ] ./plone.app.discussion/setup.py:    'ZODB3',
- [ ] ./plone.dexterity/setup.py:        'ZODB3',
- [ ] ./Products.PortalTransforms/setup.py:          'ZODB3',
- [ ] ./plone.app.viewletmanager/setup.py:    'ZODB3',
- [ ] ./plone.locking/setup.py:        'ZODB3',
- [ ] ./plone.recipe.zope2instance/setup.py:        'ZODB3 >= 3.9',
- [ ] ./Products.ResourceRegistries/setup.py:        'ZODB3',
- [ ] ./plone.testing/setup.py:    'ZODB3',
- [ ] ./plone.testing/setup.py:        'zodb': ['ZODB3'],
- [ ] ./Products.Archetypes/setup.py:          'ZODB3',
- [ ] ./plone.app.portlets/setup.py:        'ZODB3',
- [ ] ./Products.ATContentTypes/setup.py:          'ZODB3',
- [ ] ./plone.app.textfield/setup.py:        'ZODB3 >= 3.8.1',
- [ ] ./Products.CMFPlone/setup.py:        'ZODB3',

Here are examples of how this can be done:
- https://github.com/plone/Products.MimetypesRegistry/pull/14
- https://github.com/plone/plone.app.users/pull/72

**Comment by davisagli** [comment]
Note that the release of ZODB3 that is pulled in is an empty shim that simply requires ZODB, so this is pretty low priority. But sure, it would be nice to clean up.

**Comment by gforcada** [comment]
Perfect material for GSOC students to warm their skills in providing patches :wink:

**Comment by jensens** [comment]
I close the issue, because I think we fixed all of those. If not the current architecture work with pipdeptree/pipforester will find leftovers.

**Comment by gforcada** [comment]
a quick grep over the source checkouts found a few of them and I created PRs for all. I don't think we need to keep this one open 🍀
