### ISSUE TITLE
UniversalInstaller buildout fails

### ISSUE THREAD

**Issue by natea** [plone/Products.CMFPlone#2405]
### What I did:

Tried to run the UniversalInstaller, and buildout failed when it could find one of the Zope packages.

### What I expect to happen:
Buildout to finish successfully.
### What actually happened:
Buildout failed trying to install a Zope package.
### What version of Plone/ Addons I am using:
5.1.1

The fix is to add this line to the buildout.cfg file:
```
# If you change your Plone version, you'll also need to update
# the repository link below.
index=https://pypi.python.org/simple/
find-links +=
    http://dist.plone.org/release/5.1.1
```

Add the line `index=https://pypi.python.org/simple/`

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
