### ISSUE TITLE
Missing icons after building plone-logged-in ttw

### ISSUE THREAD

**Issue by krissik** [plone/Products.CMFPlone#2407]
### What I did:

I installed Plone 5.1.2 (using minimalplone5 buildout). After creating a new site I can see tinymce icons while editing front-page. Then I build plone-logged-in in resource registry and save resource registry. 

### What I expect to happen:

That there are still icons in tinymce and the toolbar.

### What actually happened:

The icons are gone.

![fehlende_icons](https://user-images.githubusercontent.com/5301889/39915655-c09843f8-5508-11e8-97e5-2a4e540a07a1.png)

### What version of Plone/ Addons I am using:

5.1.2

### What I found out

Before building plone-logged-in there is no tinymce font download. Like @gp54321 pointed out at https://community.plone.org/t/plone-5-1-1-soft-released/6159/2
the font seems to be inlined. After building plone-logged-in the browser tries to download fonts but the urls are wrong, e.g.

http://localhost:8080/Plone4/++plone++production/++unique++2018-05-11T10:39:52.874051/++plone++static/components/tinymce-builded/js/tinymce/skins/lightgray/fonts/tinymce.ttf

is not correct - it should be

http://localhost:8080/Plone4/++plone++static/components/tinymce-builded/js/tinymce/skins/lightgray/fonts/tinymce.ttf

**Comment by gp54321** [comment]
The Plone system fonts are in plone-compiled.css (that's default.css in production mode). This is definitely broken in TTW rebuilding, plone-fontello is missing completely. You can use plone-compile-resources instead. After that you have to delete the (broken) 'personalizations' created in the 'static' Zodb directory under portal_resources/resource_overrides leaving only the legacy entries, then in the resource registry control panel disable and enable the dev mode, reload by Ctrl F5 and you should be good. Works for me.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
