### ISSUE TITLE
Review state should be translatable on folder_contents page

### ISSUE THREAD

**Issue by terapyon** [plone/Products.CMFPlone#2419]
## BUG REPORT

Review state should be translatable on folder_contents page

<img width="1083" alt="2018-05-16 19 37 18" src="https://user-images.githubusercontent.com/485372/40112538-396f10fe-5941-11e8-9444-c76c892f4d57.png">

### What I expect to happen:

`@@getVocabulary` should return new property `review_state_title` and this property should be used on the page. Because `review_state` property already be used view class as `state-private`, it means `review_state` could not be translatable.

### What actually happened:

`@@getVocabulary`

```
review_state: "private"
```

### What version of Plone

Plone 5.1.2

**Comment by erral** [comment]
If we just add `_t('')` to address this, we will have to translate review state names **also** in mockup. Perhaps it's a first step, but I think we should take the translations from `plone` domain. Although achieving that from mockup is like science-fiction for me :smile:

**Comment by vincentfretin** [comment]
This issue is a hard one. You need to get the title that is defined for the workflow state, not try to translate the id. There may be a change to do in plone.app.content?

**Comment by vincentfretin** [comment]
![Capture d’écran de 2020-07-03 10-00-05](https://user-images.githubusercontent.com/112249/86446282-06d77300-bd14-11ea-8c0d-8f0ce88d44b5.png)
The javascript call a view getVocabulary to retrieve the data for each item.

Btw @tisto I didn't test volto recently, but do you have the review state correctly translated in folder contents in volto? Maybe you can shed some light on this issue? How do you do it properly in volto?

**Comment by erral** [comment]
If I am not wrong we translate all workflow and content-type names in plone.restapi endpoints. I was working on in a Sprint some time ago, indeed :smile:

**Comment by vincentfretin** [comment]
I guess you still need the review_state as id for the filters, so we should add the review_state_label (already translated with `translate(workflow_label, context=self.request)` in the returned json?

**Comment by erral** [comment]
Yeah, something like that. See what we did with transitions, for instance: https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/workflow/info.py#L54

**Comment by vincentfretin** [comment]
Ah ah, so you know there is a change do be made in the python code that create this json and then a change in mockup to use the new key in the json to show the workflow state.

**Comment by erral** [comment]
I had to make 2 changes to achieve this:

- Expose an additional 'translated_review_state' attribute in the vocabulary: https://github.com/plone/plone.app.content/commit/0d74f6954553722d10e050939d0cb82ea3c595d7
- Configure the folder_contents view to use that 'translated_review_state' as the rendered value: https://github.com/plone/mockup/commit/16f9973a5fb7b7a19f411371867fc78f17d22e87

A similar strategy can be used for portal types. I find the vocabulary changes a bit hacky, but I think that there is no other way to achieve this.

I didn't just exchange the value of the review_state with its translated version because the original review_state value could be useful for other purposes, not just for rendering it in folder_contents view.

Any comment?

**Comment by vincentfretin** [comment]
You're right about not changing the value for review_state, otherwise it would be a breaking change.
I left a comment on each commit.

**Comment by vincentfretin** [comment]
@erral You can create a PR as draft for your branch so we have more visibility you are working on it.

**Comment by erral** [comment]
I thought I already did this, sorry. I created https://github.com/plone/plone.app.content/pull/207 and https://github.com/plone/mockup/pull/1001

**Comment by jensens** [comment]
So, just checked, here it translates the state: 6.0.2 classicui
