### ISSUE TITLE
Specified source-checkout not used in py3 buildout

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2421]
When running buildout sometimes the released egg of Chameleon is used, not the source-checkout as specified.

This was observed for local buildouts, on jenkins and ay leasty in one case for a custom package (aside from Chameleon). I am not sure but strongly suspect that it only happens in python 3. If it is a issue in mr.developer, zc.buildout or a recipe is still unclear.

It is not possible to predictably reproduce the issue so we're currently starting the job https://jenkins.plone.org/view/PLIPs/job/plip-py3/ as often as it takes to get it right. 

Here is a example of the py3-build started on the same jenkins node with the same configuration only seconds apart with different results. I log the script `bin/test` so see you can see which version of Chameleon is used:

Good: https://jenkins.plone.org/view/PLIPs/job/plip-py3/95/

```
'/home/jenkins/workspace/plip-py3@3/src/Chameleon/src',
```

Bad: https://jenkins.plone.org/view/PLIPs/job/plip-py3/93/

```
'/home/jenkins/.buildout/eggs/Chameleon-3.2-py3.5.egg',
```

**Comment by davisagli** [comment]
Last week I had trouble with it until I started using lowercase `chameleon` as the name of the mr.developer checkout. I'm not sure if that was the real fix or if it's intermittent for some other reason and I just got lucky when I changed the checkout to lowercase.

**Comment by ale-rt** [comment]
Once I had a similar problem with eggs containing a `_` in their name: https://github.com/fschulze/mr.developer/pull/150

Maybe this is something related.

Setting:
```
[versions]
...
Chameleon (or chameleon) =
...
```
might help to have a consistent result.

**Comment by pbauer** [comment]
It used to be lowercase and switched to uppercase in https://github.com/plone/buildout.coredev/commit/f4dabae7fb828e2c55179bb6a1d6af965893dca6 hoping that would fix it. It changed nothing.

**Comment by ale-rt** [comment]
I still did not verify it but I guess the problem might be here:

- https://github.com/ale-rt/mr.developer/blob/0cb7515902d1f358d28ef59d553c800532f7c17c/src/mr/developer/extension.py#L206

mr.developer tries to remove from the `[versions]` section `safe_name(name)`.
I think in this case we have `Chameleon` in versions and `safe_name('Chameleon')` is `'chameleon'`.

Will check this tonite.

**Comment by ale-rt** [comment]
Closed by https://github.com/plone/buildout.coredev/commit/3d4e05b75d886a18c8e674ccfa58e0798952a3f4
