### ISSUE TITLE
Adapt tests to Zope 4.0b5

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2427]
After bumping buildout.coredev branch 5.2 to use Zope 4.0b5 tests are running but there are only two failures here in CMFPlone:
```
Products.CMFPlone.tests.testCheckId.TestCheckId.testBadId
Products.CMFPlone.tests.testCheckId.TestCheckId.testDecodeId
```
Which is kind of expected as one of the main changes in beta 5 is to allow unicode ids: https://github.com/zopefoundation/Zope/pull/181

**Comment by davisagli** [comment]
Looks like these are passing with Zope master.
