### ISSUE TITLE
support reindexObjectSecurity on Solr and other non-ZCatalog backends

### ISSUE THREAD

**Issue by gyst** [plone/Products.CMFPlone#2428]
In #1343 collective.indexing was assimilated. 
Todo: also assimilate https://github.com/plone/collective.indexing/pull/17

The monkey patches ported there fix `reindexObject` but not `reindexObjectSecurity`.

https://github.com/plone/collective.indexing/pull/17 adds support for `reindexObjectSecurity` to collective.indexing. This fix should be forward-ported here, to properly support non-ZCatalog backends like Solr.

With that monkey in place, `reindexObjectSecurity` properly works in Solr.

**Comment by jensens** [comment]
can we close this? @gyst @ale-rt ?

**Comment by gyst** [comment]
Thanks for following up on this 5 year old issue Jens! I'm not current with this code, let's see what Ale says.

**Comment by ale-rt** [comment]
That's fixed by https://github.com/zopefoundation/Products.CMFCore/pull/61
