### ISSUE TITLE
Products.MimetypesRegistry need overhault for python 3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2434]
The tests and code to classify data in Products.MimetypesRegistry is hard to port to Python 3.

For example, we are maintaining a huge list of mimetypes in `Products/MimetypesRegistry/mime_types/`. Would it be better to add https://pypi.org/project/filemagic as a dependency and rely on that to be able to correctly identify files and data?

Similarly can we use https://pypi.org/project/chardet/ to guess the encoding and drop `Products/MimetypesRegistry/encoding.py`?

**Comment by gforcada** [comment]
Is Products.MimetypesRegistry a hard dependency? :thinking: while waiting for the overhaul, one could *"simply"* create dummy replacements for the methods that are needed (with ``six``) as to not block other work.

**Comment by pbauer** [comment]
Yes, both are hard dependencies. Plone on py3 works even with this in the current state but some features that require guessing amd converting data do not work correctly.  With https://github.com/plone/Products.MimetypesRegistry/pull/15/commits/2991e7431a81ff0c0bdb35984765e2c2d80d1ae6 i moved the tests away from `bbb.PloneTestCase`. 

Integrating filemagic and chadet is some more work. Since it means adding two new external dependencies it would probably require consent from the Framework-Team. 

@ebrehault: Can you comment?

**Comment by tomgross** [comment]
How about https://github.com/zopefoundation/zope.mimetype? Does it do the same thing? It's in the ZTK, it's ported to Python 3 already, has a good test coverage and probably included already implicitly.

**Comment by rnixx** [comment]
``Products.MimetypesRegistry`` is ported as is now here https://github.com/plone/Products.MimetypesRegistry/pull/15
