### ISSUE TITLE
Search updated url becomes unreadable

### ISSUE THREAD

**Issue by andreesg** [plone/Products.CMFPlone#2435]
Plone has amazing human readable urls. A lot of people share search results in emails. This is the only url in Plone that looks very long and unreadable. Also it shouldn't be necessary to have all the empty variables.

**Example:**
* https://plone.org/@@search?sort_on=&sort_order=&SearchableText=Plone&advanced_search=False&pt_toggle=%23&portal_type%3Alist=Document&portal_type%3Alist=File&portal_type%3Alist=FormFolder&portal_type%3Alist=homepage&portal_type%3Alist=Image&portal_type%3Alist=vulnerability&portal_type%3Alist=hotfix&portal_type%3Alist=Collection&portal_type%3Alist=Event&portal_type%3Alist=plonerelease&portal_type%3Alist=Link&portal_type%3Alist=sponsor&portal_type%3Alist=FoundationSponsor&portal_type%3Alist=Folder&portal_type%3Alist=News+Item&portal_type%3Alist=Badge&portal_type%3Alist=site_link&portal_type%3Alist=FoundationMember&created.query%3Arecord%3Alist%3Adate=1970-01-02&created.range%3Arecord=min

Could this minor issue be a possible enhancement for a next release? It would be great to have a clear and human readable url when the search is updated.

**Comment by jensens** [comment]
wont fix.
