### ISSUE TITLE
Unable to export a particular configuration registry schema.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2449]
The Plone configuration registry only support an export of all configuration records.

In GenericSetup you were to export a particular aspect of the Plone configuration e.g. the mailhost configuration (that configured someone TTW).

The same should be possible with the configuration registry. One must be able to export for example all records for IMailSchema in order to include these particular mail settings into the registry.xml of a site customization profile. Finding and extracting the related records from the complete registry dump is error-prone and complex.

**Comment by jensens** [comment]
Ah, I already created a PR here some time ago https://github.com/plone/plone.app.registry/pull/26

**Comment by zopyx** [comment]
For now I have the gist code running and working. I can not do more at the moment (heading out for a two week trip).

**Comment by jensens** [comment]
ok, have fun!
