### ISSUE TITLE
PLIP: Using Dexterity for Plone Site

### ISSUE THREAD

**Issue by jaroel** [plone/Products.CMFPlone#2454]
## Abstract

Replace the CMFPlone Portal class with a Dexterity implementation.

## Motivation

Moving from a CMF item to a Dexterity container will allow us to edit the site root directly using the DX framework including support for behaviors.

This makes it possible to add the rich text behavior to the site root. This way we don’t need to use extra documents to select as default views. This is the last step we need to be able to go with a full folderish objects site and get rid of the “select item as default view” which is a huge usability improvement

## Proposal & Implementation

Replace the base class for Products.CMFPlone.Portal.PloneSite with a DX container.
Development is initially done on the latest stable (5.1) branch of Products.CMFPlone. We'll move to unstable (5.2) when this is done or if 5.2 is released, whichever is earlier.

## Deliverables

PLIP buildout config can be found here: https://github.com/plone/buildout.coredev/blob/6.0/plips/plip-2454-dx-siteroot.cfg

Jenkins job: https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/

Change Products.CMFPlone.Portal.PloneSite from CMF to DX. #2612 
Various supportive changes in -at least- https://github.com/plone/plone.app.contenttypes/pull/475 and https://github.com/plone/plone.dexterity/pull/85.

## Risks

Currently unknown.

## Participants

Roel Bruggink
Alessandro Pisa

**Comment by jensens** [comment]
How do you plan to migrate the Site Root?

**Comment by jaroel** [comment]
I haven't given it too much thought atm.
I copied over an existing Plone 5.1 Data.fs into my development stuff and at least it loaded the state correctly from the ZODB, had the correct mro for the Plone Site root and rendered the site just fine.

Something like this should do using a view/script on the zope root for each Plone site:

```python
for site in root.objectValues('Plone Site'):

    # Initialise the btree.
    if '_tree' not in site.__dict__:
        site._initBTrees()

    # Migrate existing portal content.
    for obj_meta in site._objects:
        obj_id = obj_meta['id']
        # Load the content item, tool, or whatever
        obj = getattr(site, obj_id)
        # insert it into the btree.
        # Use _setOb so we don't reindex stuff. the paths stay the same.
        site._setOb(obj)
        # Drop the attribute
        del site.__dict__[obj_id]

    # Drop no-longer needed bookkeeping
    del site.__dict__['_objects']
    site._p_changed = True
```

I do need to check what bookkeeping can be dropped.
Note: I haven't tested this yet.

**Comment by jaroel** [comment]
We'll need to add the `Plone Site` FTI and fix the `edit` method alias.

**Comment by ebrehault** [comment]
@jaroel The FWT is very positive about this PLIP.

It would be useful to get more information about the motivations (what could be the benefits? What kind of behaviors could be usefully used on the Plone Site object) as it would help to communicate about this important improvement.

Note: we will vote on the PLIP during our next meeting.

**Comment by sunew** [comment]
for one, selectablecontrainstypes behavior would be super useful:)

**Comment by robgietema** [comment]
This makes it possible to add the rich text behavior to the site root. This way we don’t need to use extra documents to select as default views. This is the last step we need to be able to go with a full folderish objects site and get rid of the “select item as default view” which is a huge usability improvement. I can second this proposal.

**Comment by ebrehault** [comment]
@jaroel, the @plone/framework-team approved this PLIP

**Comment by jaroel** [comment]
@ebrehault that's great news, thanks!

**Comment by tkimnguyen** [comment]
How does this work? "This is the last step we need to be able to go with a full folderish objects site and get rid of the 'select item as default view'" In CastleCMS we got rid of default items by using Mosaic and including a rich text tile on the Folder content type default layout

**Comment by tisto** [comment]
@jaroel would you mind giving us an update on the current status? What is missing before we can review your code? Do you plan to integrate this in Plone 5.2 or later?

**Comment by pbauer** [comment]
@tkimnguyen see https://github.com/plone/plone-react/blob/master/api/buildout.cfg#L24

**Comment by jaroel** [comment]
@tisto In practice it seems to work just fine. I'm resolving the test failures when I have time.
See https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot/ for the current state.

You can check the changes done so far using the PLIP buildout config https://github.com/plone/buildout.coredev/blob/5.1/plips/plip-2454-dx-siteroot.cfg .

I wouldn't see this as a blocker for 5.2. I'd not even consider this for 5.2, unless people have used this in production somewhere.

**Comment by jaroel** [comment]
@gforcada or @tisto  I'm getting timeout accessing the ftp server on jenkins (https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot/12/testReport/plone.app/testing/layers_rst/)
Any idea what could be going on there?

**Comment by jaroel** [comment]
FYI I'm back on this. Primary goal is to make this work for 5.2+, as that seems stable enough now.

**Comment by tisto** [comment]
@jaroel we do not plan to do a 5.3 release so this would be Plone 6 then. I added the label...

**Comment by jaroel** [comment]
@jensens FYI:
1. So far bin/instance starts and I have a functional Plone site root.
2. The tests failures from https://github.com/plone/plone.supermodel/commit/c1822bb822270b323558bfd3cd49229c50b04140 are back
3. https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/ has some failures
4. The ZMI (/manage) doesn't reflect the normal interface for the site root
5. The Products.CMFEditions failures make me sad.

**Comment by esteele** [comment]
What's the current status of this? It looks like tests are currently green.

**Comment by jaroel** [comment]
I've just updated the branches in the repos I needed.
The "upgrade script" https://github.com/plone/Products.CMFPlone/issues/2454#issuecomment-400022190 should be added somewhere. This could be in `Products.CMFPlone.Portal.__getstate__` or as a normal upgrade step.
The FWT should review what has been done, and people *must test it with actual production data*.

To be honest I don't really have time nor incentive currently to work on this except for once in a blue moon. I'm fairly certain it would be more effective if someone like @ale-rt would champion this PLIP.

**Comment by ale-rt** [comment]
I will work on this at the Not-an-Alpine-City-Sprint

**Comment by jaroel** [comment]
@ale-rt I'm sure this is in very capable hands, thank you very much Alessandro!
I'm more than happy to answer questions.

**Comment by esteele** [comment]
@ale-rt I see you've taken care of the upgrade step. Is this ready for FWT review? If not, are there additional tasks I (or others) can help out with?

**Comment by ale-rt** [comment]
Hi @esteele! I am planning to recheck this on the 23rd of April (there is a Zope sprint scheduled).
I am not using this on production yet but so far I did not spot any issue.
Hi really would like somebody from the @plone/framework-team to pick this up and review it.

**Comment by ale-rt** [comment]
And of course testing by anybody: if anyone can check that their DB run fine after this switch it would be super cool.

**Comment by pbauer** [comment]
I tested it against a Plone 6 (master) database with p.a.multilingual and that failed initially with expected tracebacks and I could not open the portal in the ZMI. 

After accessing http://localhost:8080/Plone/portal_setup/manage_upgrades I managed to run the two upgrade-steps "Be sure that the Plone Site FTI is a dexterity one" and "Make the Plone Site a dexterity container". Then the site seemed to work fine only the FTI of `Plone Site` has lost the `default_view` property `language-switcher` and was reset to `listing_view`. 

What freaks me out is that some test failed in unexpected ways: The content of `[i for i in portal._tree]` was not the same as `portal.keys()` and `portal.contentValues()` failed with:

```
>>> m.contentValues()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/pbauer/workspace/dynajet_relaunch/src-mrd/Products.CMFCore/src/Products/CMFCore/PortalFolder.py", line 202, in contentValues
    return [item[1] for item in self.contentItems(filter)]
  File "/Users/pbauer/workspace/dynajet_relaunch/src-mrd/Products.CMFCore/src/Products/CMFCore/PortalFolder.py", line 188, in contentItems
    return self._filteredItems(ids, filter)
  File "/Users/pbauer/workspace/dynajet_relaunch/src-mrd/Products.CMFCore/src/Products/CMFCore/PortalFolder.py", line 174, in _filteredItems
    obj = get(id)
  File "/Users/pbauer/.cache/buildout/eggs/plone.folder-3.0.3-py3.8.egg/plone/folder/ordered.py", line 73, in _getOb
    raise AttributeError(e)
AttributeError: 'de'
```

**Comment by ale-rt** [comment]
Thanks @pbauer for reporting this back.
About the upgrade, were you able to run the http://localhost:8120/Plone/@@plone-upgrade or that was not helpful because you were already using Plone 6?
I will take care of copying the `default_view` and maybe some other properties during the upgrade.

**Comment by pbauer** [comment]
I already used Pone 6 master for that test but I'll test another project which still runs on Plone 5.2

**Comment by pbauer** [comment]
I just tried the upgrade using `@@plone-upgrade ` with a project that ran 5.2.4 before and it worked like a charm. I updated the plip-branches locally to the current master of Plone 6. The project has no plone.app.multilingual.

**Comment by tisto** [comment]
@ale-rt we did not discuss this PLIP at our last FWT meeting. @mauritsvanrees would like to start doing a first (internal) release of Plone 6. Can you give us a heads up about the status here,? If needed, we could schedule a @plone/framework-team meeting on short notice to push this further in order to get this into the first release.

**Comment by mauritsvanrees** [comment]
I upgraded a Plone 6 site to dx site root and it seemed fine.
After the upgrade, the front-page content item is still there and is used as default page. I wondered if its text would be taken over, and maybe even the front-page itself removed, but this is not the case. Current state is probably best.
Creating a new site worked fine as well.

Two minor things:

1. Currently the homepage shows the text field plus the contents of the root (news, events, Members). If you only want to show the text field and no contents, there is currently no way.
2. The `plone.excludefromnavigation` behavior is enabled, but when you check this field in the edit form, it has no effect. We should probably just remove this behavior.

For the first one, we could make a copy of document_view and make this available in the view methods. Or is there some basic view which I am not aware of that renders all defined fields?
Probably a simple `siteroot_view.pt` would be fine. That also gives a nice way for integrators to override this with `z3c.jbot`.
For me, it is fine to do this after things get merged.

The excludefromnavigation behavior is probably best removed now, unless someone sees a need for this anyway.

**Comment by mauritsvanrees** [comment]
We could add the versioning behavior, though I don't see this having an effect when I try it, so this might need changes elsewhere.

We could add the constraintypes behavior. This seems to work well when I try it.

Both could be done later, or we leave this as an option for the user.

**Comment by mauritsvanrees** [comment]
I created two PRs that were missing. Related PRs are now:

- [ ] https://github.com/plone/Products.CMFPlone/pull/2612
- [ ] https://github.com/plone/plone.app.contenttypes/pull/475
- [ ] https://github.com/plone/plone.app.upgrade/pull/256
- [ ] https://github.com/plone/plone.restapi/pull/1200 (needs rebase/merge)

Plus the following PRs which can maybe be merged separately because they seem fine for current Plone as well:
- [ ] https://github.com/plone/plone.app.multilingual/pull/336 
- [ ] https://github.com/plone/plone.app.testing/pull/60
- [ ] https://github.com/plone/plone.dexterity/pull/85 (needs rebase/merge)

If we merge the PRs which can be done separately, it makes the rest of the PLIP smaller.

**Comment by mauritsvanrees** [comment]
I have updated the PLIP config to only test the three remaining packages with branches.
I have started the three PLIP jobs on Jenkins, on 3.7, 3.8 and [3.9](https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.9/).
I have deleted the 3.6 PLIP project, because Plone 6 no longer supports it.

**Comment by mauritsvanrees** [comment]
The three jobs all have five the same failures in the robot tests. So this may need some work.  Locally the failing ones pass though.
The 3.7 job even has 34 robot failures, I have restarted this one.

See the [3.9 job](https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.9/4/robot/).
Four are in the user schema editor, where for a checkbox we get:

    is not clickable at point (1771, 2208).
    Other element would receive the click: <div class="plone-toolbar-container">

See the [screenshot](https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.9/4/robot/report/robot_test_edit_user_schema_Scenario_As_a_manager_I_can_add_a_field_to_the_registration_form_selenium-screenshot-1.png), which looks very wrong: the toolbar is visible inside a popup/overlay. When I try it locally, it looks fine though.

The fifth is for the scenario "A page is opened to edit in TinyMCE" where we get:

    Button with locator 'css=.pattern-relateditems-container button.favorites' not found.

See [screenshot](https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.9/4/robot/report/robot_test_tinymce_Scenario_A_page_is_opened_to_edit_in_TinyMCE_selenium-screenshot-1.png)

**Comment by mauritsvanrees** [comment]
I have restarted the 3.7 job and it again had the same 34 robot failures.
I have restarted the 3.8 job and it again had the same 5 robot failures.
Jenkins did not do much at the time.
So there are no random failures, but real ones.

**Comment by mauritsvanrees** [comment]
Sorry, I lost sight of the `plone.supermodel` PR. I added it to the [list above](#issuecomment-901082515) now. Can be merged separately. @ale-rt has [re-added it to the plip config file](https://github.com/plone/plone.supermodel/pull/27#discussion_r695615977) and this should fix the PLIP build.

**Comment by ale-rt** [comment]
Yes, all the branches are green right now:
- https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.7/
- https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/
- https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.9/

**Comment by ale-rt** [comment]
> @ale-rt we did not discuss this PLIP at our last FWT meeting. @mauritsvanrees would like to start doing a first (internal) release of Plone 6. Can you give us a heads up about the status here?

@tisto this PLIP gets periodically green. 

For me it is even good to be merged now, but nobody did a formal review of the 4 branches:
- https://github.com/plone/Products.CMFPlone/pull/2612
- https://github.com/plone/plone.app.upgrade/pull/256
- https://github.com/plone/plone.supermodel/pull/27
- https://github.com/plone/plone.app.contenttypes/pull/475/

I never used this code on production, but using this plip branch I could easily migrate and run simple Plone 5.2 websites.
If you ask me I would merge all the PRs right now (this will target the first alpha version...).
I would also like to hear other people opinions.

> If needed, we could schedule a @plone/framework-team meeting on short notice to push this further in order to get this into the first release.

Unluckily I think some FWT people are now on vacation, that is why we agreed to meet next time the 7th of September (see https://community.plone.org/t/fwt-meeting-minutes-2021-07-20/14110).
Anyway if other @plone/framework-team people want to organize a meeting on a short notice I will be fine with that :)

**Comment by ale-rt** [comment]
Congratulation @jaroel! 
As agreed with the @plone/framework-team in the last meeting this PLIP can be merged.
This requires merging:
- https://github.com/plone/Products.CMFPlone/pull/2612
- https://github.com/plone/plone.app.contenttypes/pull/475
- https://github.com/plone/plone.app.upgrade/pull/256

I currently cannot do that myself because the merge button is disabled for me in https://github.com/plone/Products.CMFPlone/pull/2612.
I think the reason is the failing Python 3.6 build, which should actually be ignored.
CC @mauritsvanrees

**Comment by jaroel** [comment]
Thank you @ale-rt  for your help in landing this PLIP!
Does this mean **I** need to press 'merge' or what's the next step?

**Comment by ale-rt** [comment]
![Screenshot_20210911_201801](https://user-images.githubusercontent.com/1300763/132957434-b327f357-f769-40a4-ac30-5f0fd5a4b810.png)

I have no power to merge https://github.com/plone/Products.CMFPlone/pull/2612 while a test is still failing, even if it is outdated.
I bet someone has the power to do it :)

**Comment by mauritsvanrees** [comment]
I have merged all three remaining PRs.

Great job, Roel! Thanks for taking over, Alessandro! Thanks to all others who helped, reviewed, tested!

**Comment by jensens** [comment]
For information on how to upgrade existing Plone 6 sites. please read https://community.plone.org/t/upgrade-plone-6-sites-dx-site-root/14303
