### ISSUE TITLE
Editing images after inserted in TinyMCE breaks content

### ISSUE THREAD

**Issue by Netroxen** [plone/Products.CMFPlone#2465]
#### Scenario 1

1. Open image dialog in TinyMCE editor
  * Default ( Large 768x768 )
2. Go to "Upload" tab
  * Select an image from the local disk
  * Click "Insert" or "Upload" and then "Insert"
3. Navigate to the image and "Settings" tab
  * Select "Exclude from navigation"
4. Navigate back to parent item ( Content-Type the image was inserted on )
  * The image is no longer shown, only the filename...
5. Go into edit mode and click "Save" again
  * The image is now visible and also excluded from the navigation...

#### Scenario 2

1. Open image dialog in TinyMCE editor
  * Select ( Preview 400x400 )
2. Go to "Upload" tab
  * Select an image from the local disk
  * Click "Insert" or "Upload" and then "Insert"
3. Navigate to the image and "Settings" tab
  * Select "Exclude from navigation"
4. Navigate back to parent item ( Content-Type the image was inserted on )
  * This time the image is still shown...

### Example

![plone51-2018-07-04 10-48](https://user-images.githubusercontent.com/7691449/42267017-32f168dc-7f78-11e8-890e-761c2491fff0.gif)

### Expected

When inserting an image in the TinyMCE editor, I often want to exclude it from the navigation. However doing this in the current state causes the image to disappear from the content.

1. Open image dialog in TinyMCE editor
  * Select any image scale or default
2. Go to "Upload" tab
  * Select an image from the local disk
  * Click "Insert" or "Upload" and then "Insert"
3. Navigate to the image and "Settings" tab
  * Select "Exclude from navigation"
4. Navigate back to parent item ( Content-Type the image was inserted on )
  * The image should still be shown...

### Versions

```
Plone 5.1.2.1 (5112)
CMF 2.2.12
Zope 2.13.27
Python 2.7.14 (default, Oct 9 2017, 22:27:46) [GCC 4.8.4]
PIL 4.3.0 (Pillow)
```

**Comment by petschki** [comment]
NOTE: this happens every time you edit the image. This is likely due to scale recreation on ObjectEdited event but somehow portal_transform doesn't get the updated scales for the image object? 

/cc @davisagli maybe you've got some idea where to fix this?

**Comment by petschki** [comment]
fixed by https://github.com/plone/plone.app.textfield/pull/30
