### ISSUE TITLE
Subobjects are indexing attributes of parent

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2469]
### What I did:

- Created a custom container type with an behavior attribute ``bpm``. 
- Items inside this container do not have this behavior and attribute.
- ``bpm`` is registered as catalog index.

### What I expect to happen:

Looking at portal_catalog -> indexes -> bpm -> browse, values should show up results for the container, but not the contained items.

### What actually happened:

Looking at portal_catalog -> indexes -> bpm -> browse, values show up results for the container AND all contained items.

### What version of Plone/ Addons I am using:

Vanilla Plone 5.1.2 and 4.3.17  plus custom test behavior.

**Comment by alecpm** [comment]
I have to say it's shocking to me that this change made it into a bug fix release on stable versions of Plone. Implicit acquisition of attribute values has long been a "feature" of Zope and Plone, including during catalog indexing. This change has certainly silently broken existing sites by changing long established and well known behavior. Implicit acquisition can be annoying, but this does not seem to have been the right time or place to "fix" it.
