### ISSUE TITLE
PLIP: drop Python 2.6 support for Plone 4.3.x series

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2475]
## Abstract
Plone 4.3 was released around April 2013, 6 months later there Python 2.6 reached its end of life.

As that release was dually supported by the release team, it was decided at that time, that we would only drop Python 2.6 support on a new major release (what was supposed to be 4.4 that turned out to be 5.0 at the end).

New releases of Plone 4.3.x are still being made, some months ago there was 4.3.17 and in a few weeks there will be 4.3.18, as Plone 4.3.x series was turned into a Plone LTS (Long Term Release).

We are in 2018, 5 years later of the first release of 4.3.x series and also 5 years later of Python 2.6 EOL.

## Motivation

Plone, and python, communities are shifting their focus, not only on making code Python 2/3 compatible, but even drop completely support on Python 2.7 as its final EOL is approaching us (sometime around 2020).

Keeping jenkins builds of Plone 4.3.x series test suite running on both Python 2.7 and Python 2.6 is proving more and more challenging: virtualenv, SSL support, setuptools, just trying to install it on newer linux distributions, just to name a few, are hindering Plone Jenkins CI maintenance time, that could be otherwise be spent on adding support for CI pipelines, adding Python 3.7, ensuring packages migrated to Python 3 do not regress...

The @plone/release-team has had a few discussions about it and are supportive of this decision, but in order to add transparency and give the wider Plone community a chance to raise their voice, we are proposing this PLIP to be sanctioned by the @plone/framework-team with input from the whole Plone community.

## Assumptions
As stated above:
- Python 2.6 support reached its EOL in 2013
- Python 2.7 itself is bound to reach its EOL in 2020
- the Plone community has agreed to focus its energy in Python 3
- keeping Jenkins CI builds on Python 2.6 is getting more and more time consuming as the whole infrastructure chain (linux distributions, building python itself, setuptools, lack of virtualenv...) proves it more and more difficult as time goes

## Proposal & Implementation
Mark and announce that the next Plone 4.3.x series release will **soft drop** Python 2.6 support.

There will be no active work on *removing* Python 2.6 support on any package, it will be simply not being tested anymore.

After 5 years of keeping it support, the installations that still relay on Plone 4.3 on Python 2.6 should start their plan to move to Plone 4.3 on Python 2.7, which should be a low effort project.

## Deliverables
Announcing, after this PLIP gets approved, that the next Plone 4.3.x series release is the last one that is officially supported on Python 2.6.

## Risks
Using Python 2.6 in itself is a risk :smile:

On a more serious note, the risk is that, as of a few weeks already, the Jenkins job for Python 2.6 is already broken.

Countless hours have been used to try to keep it running on the, for a few months, upgraded Jenkins nodes infrastructure without success.

That's why Node 4 is not being used at all right now, again, hindering other Plone efforts like the Python 3 migration or other tasks.

## Participants
@plone/release-team

**Comment by tisto** [comment]
@gforcada the framework team approved this PLIP.

@esteele would you mind announcing that we drop Python 2.6 for the next 4.3 / 5.1 releases?

**Comment by gforcada** [comment]
And.... the jenkins job is finally removed (it had been disabled for months already though :sweat_smile: )
