### ISSUE TITLE
folder_contents: rename page with quotation marks

### ISSUE THREAD

**Issue by krissik** [plone/Products.CMFPlone#2476]
### What I did:

I try to rename a page that has quotations marks in its title. I am using rename function in folder_contents.

### What I expect to happen:

I expect full title in rename dialog.

### What actually happened:

Just the part before the quotation mark is shown.

![rename-bug](https://user-images.githubusercontent.com/5301889/42763488-7bd77ec0-8913-11e8-9cd1-b8cfaed22bab.jpg)

### What version of Plone/ Addons I am using:

Plone 5.1.2.1 (5112)
It can be reproduced at http://demo.plone.de

**Comment by jensens** [comment]
this was fixed - just tried in 6.0.2
