### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode on Statusmessage

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#2478]
On http://dist.plone.org/release/5.1.3-pending/ while saving a standard document.
```
  Module plone.dexterity.browser.add, line 114, in handleAdd
  Module Products.statusmessages.adapter, line 43, in add
  Module Products.statusmessages.adapter, line 89, in _encodeCookieValue
  Module Products.statusmessages.message, line 89, in encode
TypeError: Struct() argument 1 must be string, not unicode
```

Not sure what combination produces this error but it seems the fixes from https://github.com/plone/Products.statusmessages/commit/efb21fa5db0a76c25a12544e9a27fbe802150841 are being nullified by some of the latest py3 compatibility fixes...

I think the 'b' should be back in https://github.com/plone/Products.statusmessages/blob/master/Products/statusmessages/message.py#L86 

@pbauer any other idea?

**Comment by jensens** [comment]
yes, looks like this should be  a bytes. OTHO the Plone 3 docs claim this to be a string: https://docs.python.org/3.6/library/struct.html#struct.pack
