### ISSUE TITLE
Overlay with Toolbar from Top and NavBar

### ISSUE THREAD

**Issue by l34marr** [plone/Products.CMFPlone#2490]
### What I did:

Site Setup -> Site Settings -> Toolbar Position -> on the Top

### What I expect to happen:

Add new... Dropdown Menu should overlay on top of NavBar

### What actually happened:

![toolbar-top](https://user-images.githubusercontent.com/56113/43717949-b781b0cc-99bb-11e8-9816-192b3c2b8aab.png)

### What version of Plone I am using:

Plone 5.1.1

For the record: with Browser Inspector, unchecking z-index for the NavBar CSS Settings, this seems to fix the overlay issue.
![z-index](https://user-images.githubusercontent.com/56113/43718060-1027be24-99bc-11e8-9372-c13b4a3f4770.png)

**Comment by l34marr** [comment]
For the record, this issue also happens while Toolbar Position on the Side

![overlay-issue](https://user-images.githubusercontent.com/56113/46035768-6f082680-c136-11e8-9e53-657ad72cc08d.png)

**Comment by fulv** [comment]
This is still an issue in 5.2.
