### ISSUE TITLE
Improper action URL in actions control panel not reported

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2491]
Plone 5.1.2:

If you enter an improper path expression like in the screenshot (`string:` missing) then you are unable to save the form because of the validation error however now error message is show for the error.

![screenshot-dynasupport zopyx com-2018 08 06-15-36-54](https://user-images.githubusercontent.com/594239/43719687-a92a209a-998e-11e8-8e4d-5234f586e0b2.png)

**Comment by jensens** [comment]
error shows in Plone 6.0.2
