### ISSUE TITLE
Folder contents error when a user a add content with "widget" id

### ISSUE THREAD

**Issue by claytonc** [plone/Products.CMFPlone#2500]
### What I did:

1- Add content with  **widget** id.
2 - Access  **folder_contents**

### What I expect to happen: 
Check if reserved name and rename.
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_scripts/check_id.py#L68

### What actually happened:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.foldercontents, line 53, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
   - Warning: Macro expansion failed
   - Warning: <type 'exceptions.TypeError'>: __call__() takes exactly 1 argument (3 given)
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 867, in do_useMacro
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/plone/desenv/brasil.gov.tiles/eggs/plone.app.content-2.1.7-py2.7.egg/plone/app/content/browser/folder_contents.pt
   - Line 29, Column 18
   - Expression: <PythonExpr (here.widget('title', mode='view'))>
   - Names:
      {'args': (),
       'container': <PloneSite at /plone>,
       'context': <PloneSite at /plone>,
       'default': <object object at 0xb7d0c9e8>,
       'here': <PloneSite at /plone>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xb17f57ac>,
       'request': <HTTPRequest, URL=http://localhost:8080/plone/folder_contents>,
       'root': <Application at >,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0xb24cfb8c>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>,
       'view': <Products.Five.metaclass.SimpleViewClass from /home/plone/desenv/brasil.gov.tiles/eggs/plone.app.content-2.1.7-py2.7.egg/plone/app/content/browser/folder_contents.pt object at 0xaf937f6c>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0xaf95beac>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (here.widget('title', mode='view'))
  Module <string>, line 1, in <module>
TypeError: __call__() takes exactly 1 argument (3 given)

### What version of Plone/ Addons I am using:
Plone 4.3.17

**Comment by mauritsvanrees** [comment]
Plone 4.3 is not supported anymore. I cannot reproduce in Plone 5.2 or 6.0.
