### ISSUE TITLE
Combine bundles import step not running with registry directories

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2502]
Plone 5.1.
The `combine-bundles` [import step](https://github.com/plone/Products.CMFPlone/blob/5.1.3/Products/CMFPlone/resources/exportimport/bundles.py) looks for a file `registry.xml`, looks for the string `IBundleRegistry` in the body of this file, and then combines bundles. Working fine.

But `plone.app.registry` since Plone 5.1 can handle a [directory `registry`](https://github.com/plone/plone.app.registry/blob/1.7.2/plone/app/registry/exportimport/handler.py#L69-L72) with files in it. The `combine-bundles` import step ignores this directory, so no bundles are combined.

So: the import step should look in the directory too. If one of the files matches, it should combine the bundles.

**Comment by sunew** [comment]
@mauritsvanrees I guess this can be closed? Is merged.
