### ISSUE TITLE
Remove dependency on Products.CMFTestCase

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#252]
I just ran bin/buildout on buildout.coredev branch 5.0 and I noticed that it picked ``Products.CMFTestCase``.

A quick grep on src folder revealed that 3 distributions depend on it:

    grep 'Products.CMFTestCase' */setup.py
    Products.Archetypes
    Products.CMFQuickInstallerTool
    Products.PortalTransforms

At least for the last one, maybe the only one we do really care (don't think so for Archetypes but not so sure for CMFQuickInstallerTool) I already removed as it was not being used anywhere.

**Comment by tomgross** [comment]
all ocurences removed

**Comment by pbauer** [comment]
:beers:

**Comment by thet** [comment]
:beers: also from me!
