### ISSUE TITLE
TinyMCE replace a wrong relative url referred to the same domain if multilingual support is installed on the web site

### ISSUE THREAD

**Issue by robbuh** [plone/Products.CMFPlone#2520]
When an External URL related to the same domain (an internal page) is added via TinyMCE editor, TinyMCE replace absolute url with a relative url.

But If plone.app.multiligual support is installed and active in the web site the folder related to the language (eg. /en) is included and added in the relative path, so link leads to a not existing page.

a "../" too much is added on the relative path.

http://www.mydomain.eu/en/page/subpage address will be replaced with "../../../subpage" relative path if it's placed in a third level page of the same domain for example.

Plone 5.1.2

![tinymce-inserlink](https://user-images.githubusercontent.com/2462533/45827638-2811cf80-bcf7-11e8-8f8b-a5b1063b3a0e.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
