### ISSUE TITLE
Build all js / css bundles before every release

### ISSUE THREAD

**Issue by sunew** [plone/Products.CMFPlone#2521]
On 5.1.x master, resourceregistry and thememapper havent been compiled for quite a while:

![selection_665](https://user-images.githubusercontent.com/893142/45827986-d61d7980-bcf7-11e8-8e98-3b6faf1e901a.png)

This could explain this:
https://github.com/plone/Products.CMFPlone/pull/2518
The test are failing locally with a freshly buildt thememapper bundle.

In general, changes to mockup or other frontend resources could have effects on all bundles.

I suggest making a rebuilding part of the cmfplone release proces (if it is not already).
Could be integrated in plone.releaser?

**Comment by mauritsvanrees** [comment]
In the past, I have seen PRs on CMFPlone where someone had done the bundle build work already. Ah, like you did [two days ago](https://github.com/plone/Products.CMFPlone/pull/2522).
I have never done the building myself, and don't know how to do that.

I guess fresh bundles make sense after a mockup release, not after every little change in mockup. Right?

I have made mockup releases, but have never done anything special during release time.
I don't do the CMFPlone releases though, that is left to @esteele.
See the current [Plone release process](https://docs.plone.org/develop/coredev/docs/release.html).

**Comment by vincentfretin** [comment]
@mauritsvanrees Can you update the https://docs.plone.org/develop/coredev/docs/release.html document with the checkboxes you have in https://github.com/plone/Products.CMFPlone/issues/3119 mainly the "If unsure, ask if mockup and plone.staticresources are in sync and can be released." checkbox, and close this issue?

**Comment by mauritsvanrees** [comment]
Done: https://github.com/plone/buildout.coredev/commit/20d144dcbdd903c7ba472709f684b149c81ce219
