### ISSUE TITLE
Default page popup/overlay should omit the document descriptions for saving space

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2528]
See screenshot.

I many case we have something like 40-100 documents with often longer descriptions in one folder.
Picking up the right default page is a pain when the UI is cluttered with irrelevant document descriptions.
Either hide the document descriptions at all or display only one or two lines. In general: the description is not really helpful for content authors here. It's the title that matters.

Tested with Plone 5.1

![screenshot-dev zopyx de-5080-2018 09 28-07-45-33](https://user-images.githubusercontent.com/594239/46190145-a0c5ec80-c2f2-11e8-9fbe-d76d23c1670d.png)

**Comment by hvelarde** [comment]
same happens in Plone 4.3.

![screenshot_2018-09-28 home](https://user-images.githubusercontent.com/341393/46208626-ae36a300-c301-11e8-8fa0-c573ec0d7843.png)

**Comment by jensens** [comment]
This is still the case in Plone 6.0.2 and I must admit, if the description is short it adds value. 
I do not think we will change this in ClassicUI. In Volto there is no default page any more, so this is solved.
I close this issue. If you disagree and plan to work on making it optional, i.e. through some registry setting, please reopen.
