### ISSUE TITLE
Toolbar -> manage portlets applies to default page instead of current content object

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2529]
- blank Plone site
- add some page and assigned it as default page to the Plone root
- click on the Plone logo for getting into the context of the Plone root
- click on manage portlets 
- Plone will redirect to ../plone-site/default-page/@@manage-portlets

This is usually not what you want because you expect to manage the portlets of the Plone site  and not only the portlets of the default page. The correct URL would ../plone-site/@@manage-portlets

Tested with Plone 5.1.2

**Comment by hvelarde** [comment]
that has been the default behavior for eons as you can see in this Plone 4.3 screenshot:

![screenshot_2018-09-28 home secretaria de teste de migracao](https://user-images.githubusercontent.com/341393/46208738-0bcaef80-c302-11e8-867e-c845aa786371.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
