### ISSUE TITLE
CSS issus in "insert Image"

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2533]
See screenshoot (overlap of filename with icon)

Plone 5.1.2, plone-demo.info
![screenshot-www plone-demo info-2018 09 28-16-08-43](https://user-images.githubusercontent.com/594239/46213469-edccb180-c338-11e8-852d-8709b6bf4528.png)

**Comment by jensens** [comment]
still an issue in 5.2

**Comment by zopyx** [comment]
yes, tested on plone-demo.info

**Comment by vincentfretin** [comment]
Still an issue in Plone 5.2.2rc1:
![Capture d’écran de 2020-07-07 16-29-43](https://user-images.githubusercontent.com/112249/86796674-1f76be80-c06f-11ea-8557-e5d24bbab5c9.png)
With my PR https://github.com/plone/mockup/pull/1000
This is now:
![Capture d’écran de 2020-07-07 16-28-56](https://user-images.githubusercontent.com/112249/86796777-3ae1c980-c06f-11ea-9998-66c8b319316f.png)
