### ISSUE TITLE
TinyMCE default styles incompatible with HTML filtering

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2535]
Usability bug in Plone 5.1.2:

- create a new document, add some text and select "strikethrough" as character format -> text show as strikethrough inside TinyMCE
- "Save" -> text display as normal text

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

And: probably solved already.
