### ISSUE TITLE
Provide a replacement for WebDAV and FTP

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2537]
WebDAV and FTP are part of ZServer which is removed when running on Python 3. We might need a replacement if the uses-cases that we use it for are still valid nowadays.

@thet wrote in https://github.com/plone/Products.CMFPlone/issues/2368: 
> Regarding
> 
>  WebDAV and WSGI - there is a WSGI middleware for WebDAV (which also includes a standalone WebDAV server):
> 
> https://github.com/mar10/wsgidav
> https://wsgidav.readthedocs.io/en/latest/reference_guide_architecture.html
> 
> This project looks quite promising:
> 
>     It has a good software architecture - everything is implemented against interface specifications.
>     It comes with default DAVProvider, PropertyManager and LockManager implementations and allows for providing more specific ones.
>     It's tested against a lot of WebDAV clients: Windows File Explorer and drive mapping, MS Office, Ubuntu, Mac OS X, …
> 
> This could help us a lot providing WebDAV on WSGI for Plone/Zope.

**Comment by thet** [comment]
Plone 5.2.2 brings back WSGI, jipee!
https://community.plone.org/t/failed-to-be-enable-webdav-in-plone-5-2-1/12451/10
