### ISSUE TITLE
Use towncrier for all or most Plone packages

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2548]
Towncrier is a tool for putting the changes in news fragments instead of a single CHANGES.rst that will get merge errors.

See also #2524. Busy on this during the Saltlabs Sprint in Halle.
This should be helpful for those wanted to assist: https://github.com/plone/plone.releaser/blob/master/ADD-A-NEWS-ITEM.rst

For a package, all branches used in 4.3-5.2 should be initialized to use towncrier. Partially this can be [automated](https://gist.github.com/mauritsvanrees/92c40bc16ceaf3c375d81c995b4552c4) and partially you will need to edit the `CHANGES.rst` and move the unreleased changes to files in the `news` directory.

We may not need to do this for *all* packages. Also, it might be okay to do it for only a part of the packages at first, and see if it actually works in practice.  But should be fine, and has been in use for a while.

List of packages:

- [x] Plone -> no towncrier
- [x] Products.ATContentTypes
- [x] Products.Archetypes
- [x] Products.CMFDynamicViewFTI
- [x] Products.CMFEditions
- [x] Products.CMFFormController
- [x] Products.CMFPlacefulWorkflow
- [x] Products.CMFPlone
- [x] Products.CMFQuickInstallerTool
- [x] Products.ExtendedPathIndex
- [x] Products.Marshall
- [x] Products.MimetypesRegistry
- [x] Products.PlacelessTranslationService
- [x] Products.PloneLanguageTool
- [x] Products.PlonePAS
- [x] Products.PortalTransforms
- [x] Products.ResourceRegistries
- [x] Products.contentmigration
- [x] Products.statusmessages
- [x] Products.validation
- [x] archetypes.multilingual
- [x] archetypes.referencebrowserwidget
- [x] archetypes.schemaextender
- [x] borg.localrole
- [x] collective.monkeypatcher
- [x] collective.xmltestreport
- [x] diazo
- [x] mockup
- [x] plone.alterego
- [x] plone.api
- [x] plone.app.blob
- [x] plone.app.caching
- [x] plone.app.collection
- [x] plone.app.content
- [x] plone.app.contentlisting
- [x] plone.app.contentmenu
- [x] plone.app.contentrules
- [x] plone.app.contenttypes
- [x] plone.app.controlpanel
- [x] plone.app.customerize
- [x] plone.app.debugtoolbar
- [x] plone.app.dexterity
- [x] plone.app.discussion
- [x] plone.app.event
- [ ] plone.app.folder
- [x] plone.app.i18n
- [ ] plone.app.imaging
- [x] plone.app.intid
- [x] plone.app.iterate
- [x] plone.app.layout
- [x] plone.app.linkintegrity
- [ ] plone.app.locales
- [x] plone.app.lockingbehavior
- [x] plone.app.multilingual
- [x] plone.app.portlets
- [x] plone.app.querystring
- [x] plone.app.redirector
- [ ] plone.app.referenceablebehavior
- [x] plone.app.registry
- [x] plone.app.relationfield
- [x] plone.app.robotframework
- [x] plone.app.testing
- [x] plone.app.textfield
- [x] plone.app.theming
- [x] plone.app.upgrade
- [x] plone.app.users
- [x] plone.app.uuid
- [ ] plone.app.versioningbehavior
- [x] plone.app.viewletmanager
- [x] plone.app.vocabularies
- [x] plone.app.widgets
- [x] plone.app.workflow
- [x] plone.app.z3cform
- [x] plone.autoform
- [x] plone.batching
- [ ] plone.behavior
- [ ] plone.browserlayer
- [x] plone.cachepurging
- [x] plone.caching
- [x] plone.contentrules
- [x] plone.dexterity
- [ ] plone.event
- [x] plone.folder
- [x] plone.formwidget.namedfile
- [ ] plone.formwidget.recurrence
- [x] plone.i18n
- [x] plone.indexer
- [x] plone.intelligenttext
- [x] plone.keyring
- [x] plone.locking
- [x] plone.memoize
- [x] plone.namedfile
- [ ] plone.outputfilters
- [ ] plone.portlet.collection
- [ ] plone.portlet.static
- [x] plone.portlets
- [x] plone.protect
- [ ] plone.recipe.alltests
- [x] plone.recipe.zeoserver
- [x] plone.recipe.zope2instance
- [x] plone.registry
- [x] plone.releaser
- [ ] plone.reload
- [x] plone.resource
- [x] plone.resourceeditor
- [x] plone.rest
- [x] plone.restapi
- [x] plone.rfc822
- [x] plone.scale
- [x] plone.schema
- [x] plone.schemaeditor
- [x] plone.session
- [x] plone.stringinterp
- [x] plone.subrequest
- [x] plone.supermodel
- [x] plone.synchronize
- [x] plone.testing
- [x] plone.theme
- [ ] plone.themepreview
- [x] plone.tiles
- [x] plone.transformchain
- [x] plone.uuid
- [ ] plone.versioncheck
- [ ] plone.z3cform
- [x] plonetheme.barceloneta
- [ ] plonetheme.sunburst

**Comment by gforcada** [comment]
Should we update Mr.roboto to warn if the towmcrier config is there but changes.rst is modified? 🤔

**Comment by mauritsvanrees** [comment]
It could help.
But it should already be hard to modify `CHANGES.rst`, because there is no header for the next version. Well, one could easily add an entry to the previous header...
I guess a check could easily lead to false positives, where a contributor edits the `CHANGES.rst` file directly to fix a typo.

**Comment by mauritsvanrees** [comment]
Note that in some cases, you may need to add a dummy issue, so you have a unique identifier for towncrier. See https://github.com/plone/Products.CMFFormController/issues/17.

**Comment by gforcada** [comment]
I added a bunch of them while making releases today :cake: :sparkles: 

One issue that I noticed while making company package releases is that if you create a `news/123.my-fancy-suffix` it is silently ignored by towncrier :disappointed: 

I already filed a ticket on https://github.com/hawkowl/towncrier/issues/137 to add a lint mode, so one can verify the news snippets before releasing, to ensure no snippet is left behind.

**Comment by ale-rt** [comment]
Just for the record, my usual workflow, with the current tools available, when releasing is to:
- run bin/prerelease
- then I check fancy news files and the produced changelog
- run bin/release
- run bin/postrelease

Having a linter might be a nice addition but many times amending the produced changelog is something you want to do (especially when you have lot of changes).

**Comment by gforcada** [comment]
I think this can be closed, if any repository is still not initialized, with `plone/meta` it should 😄
