### ISSUE TITLE
Linkintegrity is broken in Plone 5

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#255]
plone.app.linkintegrity reads the setting from the new registry: 

https://github.com/plone/plone.app.linkintegrity/commit/e4656fae41e5d71e28e757c561df276d167ec0d0

Though, it seems this setting has no effect at all.

There is a robot test that would currently fail and is therefore commented out:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_controlpanel_editing.robot#L30

Once the issue has been solved, this test should pass.

**Comment by pbauer** [comment]
There is PLIP and quite a lot of work was done already: See https://github.com/plone/Products.CMFPlone/issues/698
It would be great to get the input of people like @martior who looked into that already.
