### ISSUE TITLE
Toolbar: "Display" has various issues

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2565]
1) Why does the popup with the available views contain the string "Display"...confusing and duplicates "Display" within the toolbar. Using a heading in the popups of the toolbar is a common pattern, It works for "Add new" because the addable entries haven icon. It does not work for toolbar popups without icons. In particular the visual contrast between the heading of a popup toolbar and its entries is very poor - almost the same font size and color.
2) the currently active view is not highlighted. Obviously the first view is always the active one but is not detectable if you don't know it. 
3) The right arrow icon of the "Manage portlets" conflicts here...people may think that this icon belongs to the "Display" popup pointing to a particular entry.

![screenshot-dynalook zopyx com-2018 10 04-13-19-30](https://user-images.githubusercontent.com/594239/46470839-5227bf00-c7d8-11e8-80a9-b6a9de2f7202.png)

**Comment by hvelarde** [comment]
this was already reported eons ago in #1007.
