### ISSUE TITLE
Provide a Python 3 upgrade form/view

### ISSUE THREAD

**Issue by frisi** [plone/Products.CMFPlone#2575]
Before being able to run Plone 5.2 on Python 3 the database needs to be migrated.
(see https://github.com/plone/Products.CMFPlone/issues/2525 for more information and a collection of related documentation and tickets)

Before using https://github.com/zopefoundation/zodbupdate to migrate the database to python 3 we need to differentiate which Python 2 strings should be converted to Python 3 binary and which to string(unicode) on application level.
For example, there are `str` values in a `BTree` that will need to be converted to `binary` rather than (unicode)`str` in Python 3. Eg. this is the case for hashed passwords stored in acl_users

The idea we discussed at the sprint in Halle (@pbauer) was to provide a view/form that

* [ ] explains what it does (prepare data for python3 migration)
* [ ] that you should do a backup first
* [ ] links to the relevant documentation (https://github.com/plone/documentation/pull/1022)
* [ ] runs one or several upgrade scripts
* [ ] we might optionally provide a way to register upgrade scripts for addons (eg specialized indexes)
  so they are run here too

Known migration tasks:
* [ ] acl_users password hashes (https://github.com/plone/Products.CMFPlone/issues/2576)

**Comment by jensens** [comment]
I do not think this is possible. One can not start Zope w/o manual migration before.
