### ISSUE TITLE
Prepare Userfolders for Python 3 migration

### ISSUE THREAD

**Issue by frisi** [plone/Products.CMFPlone#2576]
we need a script that is called by the python3 migration view (see #2575 for details) that marks password hashes located in userfolders as `zodbpickle.binary` so they do not get mangled when `ZODB.serialize` unpickles the Btree running Python 3 or when using `zodbupdate` to migrate the database to python 3.

## Procedure:

I tried out with test setup described in https://github.com/frisi/coredev52multipy/blob/zodbupdate/README.rst

A) Converted str hashes to zodbpickle.binary running `py2/bin/instance debug`

```
from zodbpickle import binary
import transaction

zodb_usermanagers = [
    app.restrictedTraverse('acl_users/users')._user_passwords,
    app.Plone.restrictedTraverse('acl_users/source_users')._user_passwords,
]
for zodb_usermanager in zodb_usermanagers:
    for user_id, pwd in zodb_usermanager.iteritems():
        zodb_usermanager[user_id] = binary(pwd)

transaction.commit()
```

B) copy db to py3 instance and run upgrade 

```
cp py2/var/filestorage/Data.fs py3/var/filestorage/Data.fs
py2/bin/zodbupdate --pack --convert-py3 --file py3/var/filestorage/Data.fs
```

C) startup py3 instance `py3/bin/wsgi` and try to login http://0.0.0.0:6543/Plone/login

D) if you can't login, create a new manager user

To get a valid manager user to login again call `py3$ bin/wsgidebug`

```python
>>> import transaction
>>> result = app.acl_users._doAddUser('admin2', 'admin2', ['Manager'], [])
>>> transaction.commit()
```

## Current state

Marking hashes as zodbpickle.binary seems not to be sufficient

before migration py2 database contains zodbpickle.binary:
```python
    (Pdb++) uf._user_passwords.get('admin')
    '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='
    (Pdb++) type(uf._user_passwords.get('admin'))
    <class 'zodbpickle.binary'>
```

but after migration py3 database still uses string:
```python
    >>> app.acl_users.users._user_passwords
    <BTrees.OOBTree.OOBTree object at 0x7f79329671e0>
    >>> app.acl_users.users._user_passwords.get('admin')
    '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='
    >>> type(app.acl_users.users._user_passwords.get('admin'))
    <class 'str'>
```

new user passwords are encoded as bytes
```python
    >>> app.acl_users._doAddUser('admin2', 'admin2', ['Manager'], [])
    <PropertiedUser 'admin2'>
    >>> app.acl_users.users._user_passwords.get('admin2')
    b'{SSHA}lR7R4mZygLfKj4cO7dvlOelRDKMBnBSV/p8p'
```
so convert for existing one
```python
    >>> pwd=app.acl_users.users._user_passwords.get('admin')
    >>> pwd
    '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='
    >>> bytes(pwd, 'ascii')
    b'{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='
    >>> app.acl_users.users._user_passwords['admin']=bytes(pwd,'ascii')
    >>> import transaction; transaction.commit()
    # login works now
```

## TODO

passwords in the btree should be bytes after migration (or when unpickled under py3) automatically
since we converted them to zodbpickle.binary in the py2 database already.

we need to find out if zodbmigrate mixes that up (changes the optcode/datatype in the pickle) , or if it simply does not work as expected:

i'd expect the pickle in the python2 ZODB record to use something that "sounds" like it is storing bytes:

```
>>> import pickle
>>> import pickletools
>>> pickletools.dis(pickle.dumps(di))
       ....
       18: X        BINUNICODE 'str'
       26: q        BINPUT     2
       28: C        SHORT_BINBYTES '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='
```
and that unpickling it under python 3 results in `b'{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc='`

the tricky part is to find out the oid of the zodbrecord holding Btree for (i'd try a pdb in `zodbmigrate.serialize.Renamer.rename` for `class_meta == BTree`) to be able to set a pdb in `zodbupdate.update.Updater.__call__` before/after processing the record with this oid

**Comment by davisagli** [comment]
I updated AuthEncoding to handle either strings or bytes as input, so this is no longer necessary.
