### ISSUE TITLE
CSS in robot tests on py3 is broken

### ISSUE THREAD

**Issue by jaroel** [plone/Products.CMFPlone#2579]
When running robot tests I noticed that the editbar isn't styled.
This works correctly when using `bin/wsgi`.

![screen shot 2018-10-05 at 17 09 06](https://user-images.githubusercontent.com/70700/46543593-8b882980-c8c1-11e8-8faa-3adc8b279d8d.jpg)

A diff between some CSS shows that urls contains '' <0x01> characters. This prevents the CSS from being applied, which breaks robot tests 💯 

[bin_wsgi.css.txt](https://github.com/plone/Products.CMFPlone/files/2450868/bin_wsgi.css.txt)
[bin_test.css.txt](https://github.com/plone/Products.CMFPlone/files/2450870/bin_test.css.txt)
[meh.diff.txt](https://github.com/plone/Products.CMFPlone/files/2450869/meh.diff.txt)

**Comment by jaroel** [comment]
I see the following using `bin/wsgi` using pdb in PloneBundlesTraverser:

(Pdb++) persistentDirectory
<PersistentResourceDirectory object at portal_resources>
(Pdb++) the_resource
<File at /Plone/portal_resources/resource_overrides/production/logged-in.css>
(Pdb++) the_resource.data
<OFS.Image.Pdata object at 0x10e6becf8>
(Pdb++) type(the_resource.data.data)
<class 'bytes'>
(Pdb++) the_data = the_resource.data.data
**(Pdb++) 0x01 in the_data
True**
(Pdb++) 0x02 in the_data
False
(Pdb++) 0x00 in the_data
False
(Pdb++)

**Comment by pbauer** [comment]
The problem seems not only in robot-tests. Robot-tests use `logged-in.css`. 

When running `./bin/wsgi` the content of http://0.0.0.0:6543/Plone/++plone++production/++unique++2018-10-10T09:38:39.378199/logged-in.css
contains:

```
div.overlaybg div.close,
div.overlay div.close {
    background-image: ++plone++static/pb_close.png);
    position: absolute;
    left: -14px;
    top: -14px;
    cursor: pointer;
    height: 30px;
    width: 30px;
}
```
Where ```` is ``<0x01>`` and should be `url(`, so that `url(++plone++static/pb_close.png)` works.

What is more: The same in python2 (using `py3_on_py2.cfg`) returns the same broken css.

Only when running the normal coredev of 5.2 in py2 the result is correct: `url(++plone++static/pb_close.png)`. Thus the issue must be in one of the unmerged branches only used for py3.

**Comment by pbauer** [comment]
The issue is in `Products.CMFPlone.resources.browser.combine.write_css`:

```
css = re.sub(
    b"""(url\(['"]?(?!['"]?([a-z]+:|\/)))""",
    b'\1%s/' % path,
    css)
```

The regex is broken:

```
(Pdb++) import re
(Pdb++) path = b'++plone++static'
(Pdb++) css = b'url(pb_close.png)'
(Pdb++) re.sub(b"""(url\(['"]?(?!['"]?([a-z]+:|\/)))""", b'\1%s/' % path, css)
b'\x01++plone++static/pb_close.png)'
```

**Comment by pbauer** [comment]
The fix that seems to work is to use raw bytes in the regex to make the `\` work as a escape-character. Do regex-nerds think that is ok or is there a better fix?

**Comment by jaroel** [comment]
@pbauer That's ok!

Normally raw string are used, but this got mixed up in https://github.com/plone/Products.CMFPlone/commit/f4c99c98567b028da2aae3a321b7d109bde405c2 

I've checked this locally and it works like a charm! Thank you!
