### ISSUE TITLE
Startup of Plone fails in Zope 4.0b6 on py3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2591]
Due to https://github.com/zopefoundation/zope.schema/commit/c5da21d27354430abec3d965011c96f47c626b2e values like `plone.app.registry` and `3-4alpha1` or `import-intid-util` are no longer valid names of import-steps. They seem to be validated as PythonIdentifier using the regex `r'[a-zA-Z_]+\w*'`. 

```
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/zope.configuration-4.3.0-py3.7.egg/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/pbauer/workspace/plip/src/zope.schema/src/zope/schema/_field.py", line 544, in fromUnicode
    self.validate(v)
  File "/Users/pbauer/workspace/plip/src/zope.schema/src/zope/schema/_bootstrapfields.py", line 291, in validate
    self._validate(value)
  File "/Users/pbauer/.cache/buildout/eggs/zope.configuration-4.3.0-py3.7.egg/zope/configuration/fields.py", line 89, in _validate
    super(PythonIdentifier, self)._validate(value)
  File "/Users/pbauer/workspace/plip/src/zope.schema/src/zope/schema/_field.py", line 625, in _validate
    _is_identifier(value)
zope.schema._bootstrapinterfaces.InvalidValue: plone.app.registry
```

**Comment by davisagli** [comment]
Well, they aren't valid Python identifiers. We should probably switch the schema in Products.GenericSetup to use ASCIILine, maybe with our own constraint.

I can't figure out why this worked before the change 🤔

**Comment by pbauer** [comment]
Changing to ASCIILine until startup works requires changes in: 
* Products.GenericSetup: (IRegisterProfileDirective, IExportStepDirective, IImportStepDirective, IImportStepDependsDirective)
* plone.resource (IResourceDirectoryDirective)
* z3c.caching (IRuleset)

Should we do that?

**Comment by davisagli** [comment]
See the discussion on https://github.com/zopefoundation/Products.GenericSetup/pull/72

**Comment by pbauer** [comment]
@davisagli should we switch to `TextLine` or `ASCIILine` in `plone.resource` and `z3c.caching`?

**Comment by davisagli** [comment]
@pbauer sorry, I'm not sure and don't have time to take a closer look tonight.

**Comment by davisagli** [comment]
But given the discussion on the GenericSetup issue I would guess TextLine

**Comment by pbauer** [comment]
I did the same in https://github.com/zopefoundation/z3c.caching/pull/6 and https://github.com/plone/plone.resource/pull/28
