### ISSUE TITLE
Reconfigure coredev for Plone 5.2a1

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2593]
It should work in py2 and py3 with py2 still being the default and py3 working when extending from a py3.cfg

Tasks/Questions:

* Since py2 is the default, ZServer should be in the default config. 
* We should probably move the whole Archetypes-stack to a separate file since it is being deprecated with 5.2.
* We should add a py3.cfg that removes the incompatible packages (ZServer/AT) similar to what the current py3.cfg does. It should not hold any extra-checkouts, branches or version but could remove parts.
* Should we add wsgi.cfg to the default setup since it works the same in py2 and py3? If yes it should be extend by core.cfg like the others.
* We can remove alltests and relates parts from test.cfg

**Comment by thet** [comment]
All sounds good. There is already a wsgi.cfg which extends core.cfg, so that should be fine.

**Comment by jensens** [comment]
FTR, besides the reconfiguration, here other findings while analysing our buildout and resulting TODOs:

- we still have a Sphinx setup in buildout.coredev while the actual build happens at a different place @svx @polyester - can we drop it here?

- we still have references to Grok in our ecosystem.cfg and versions and in . Lets drop it. We anyway can not  guarantee that it is working.

**Comment by svx** [comment]
@jensens IMHO, yes !
