### ISSUE TITLE
Update and translate Plone default frontpage

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2594]
The text of the frontpage might need to be updated/reviewed. Also the translations (at least german) are not up to date. 
Template: Products/CMFPlone/browser/templates/plone-frontpage.pt, 
Translations: e.g. plone/app/locales/locales/de/LC_MESSAGES/plonefrontpage.po)

**Comment by vincentfretin** [comment]
@polyester did some updates in plone/app/locales/locales/plonefrontpage.pot in https://github.com/collective/plone.app.locales/commit/d5990d59de2e36fd6fe1c2a731a2c8da83f06c19

If you change Products/CMFPlone/browser/templates/plone-frontpage.pt you need to keep it synchronized with plone/app/locales/locales/plonefrontpage.pot manually I think.
