### ISSUE TITLE
review list portlet does not work with plone.app.multilingual

### ISSUE THREAD

**Issue by iham** [plone/Products.CMFPlone#2595]
### What I did:
1. create a vanilla plone site; install it with multilingual support
2. configure at least two languages (i used German and English)
3. on portal_root add the review list portlet
4. create a contentobject and submit it for publication

### What I expect to happen:
the review list portlet should show the pending object.

### What actually happened:
the review list portlet is not shown

### What version of Plone/ Addons I am using:
plone 5.x

### What i found so far:
according to this documentation:
https://docs.plone.org/develop/plone/searching_and_indexing/query.html#bypassing-language-check
> plone.app.multilingual 2.x and later (part of Plone 5.x) creates Root Language Folders for each of your site’s languages. It keeps (“jails”) content within the appropriate folders. Each Root Language Folder is also a NavigationRoot, so the portal_catalog is already effectively limited to searches in the users current language.

... this lines of code can't work
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/WorkflowTool.py#L234
as there is no obvious way to set languages via workflowlist, there will never be a "Language" set for the query. as p.a.m. does not use "all"  for bypassing languages, the result is empty.

i hope for some solution on that.

**Comment by iham** [comment]
i did some more research ...
plone.app.multilingual way above 2.x is pinned by at least all versions of plone 5.1. according the docs it is used by all plone 5.x versions.

why is that language bypass for linguaplone still part of cmfplone?
is there any case in which cmfplone 5.x is used by plone4?

if not: we could just remove that language bypass.
a neat feature would be, to make the bypass an option of the review portlet.

@hvelarde
for my better understanding: why is this not considered a bug?
so i don't file this wrong the next time again. thx

**Comment by hvelarde** [comment]
@iham a regression is a special kind of bug; marking a regression as a bug is redundant.

**Comment by 2silver** [comment]
same as #1969
