### ISSUE TITLE
Collection edit screen inconsistent naming of table columns

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2597]
See screenshot.

The "table columns" items are not properly named or localized. The naming should be consistent e.g. with the "Columns" items 

![screenshot_20181022_105321](https://user-images.githubusercontent.com/594239/47284823-0acb6c00-d5e9-11e8-999d-f9e305a99fe2.png)

**Comment by hvelarde** [comment]
do you mind to replace the screenshot?

**Comment by vincentfretin** [comment]
A recent screenshot with Plone 5.2.2rc1
![Capture d’écran de 2020-06-28 10-57-41](https://user-images.githubusercontent.com/112249/85943133-53930680-b92e-11ea-8104-431a8af8ca8e.png)

**Comment by vincentfretin** [comment]
See https://github.com/plone/plone.app.contenttypes/issues/93

**Comment by vincentfretin** [comment]
See https://github.com/plone/plone.app.collection/issues/52
In collection tabular view, ModificationDate is the id, not the title, this is related to the same issue with the vocabulary using the ids.
![Capture d’écran de 2020-06-28 11-18-26](https://user-images.githubusercontent.com/112249/85943568-2136d880-b931-11ea-9c7d-4c365625c10b.png)

**Comment by vincentfretin** [comment]
See https://github.com/plone/Products.CMFPlone/issues/1183 to sort alphabetically the columns in this vocabulary.

**Comment by vincentfretin** [comment]
See https://github.com/plone/plone.app.contenttypes/issues/211 and my explanation on https://github.com/collective/plone.app.locales/issues/231#issuecomment-392074930

**Comment by vincentfretin** [comment]
PR https://github.com/plone/plone.app.contenttypes/pull/559
folder tabular view
![Capture d’écran de 2020-06-29 17-05-14](https://user-images.githubusercontent.com/112249/86022626-eadd8400-ba2a-11ea-9ab2-8dfdf2d8e331.png)
collection tabular view
![Capture d’écran de 2020-06-29 17-05-24](https://user-images.githubusercontent.com/112249/86022637-ef09a180-ba2a-11ea-8565-e0dc9337b1cf.png)
collection edit
![Capture d’écran de 2020-06-29 17-05-38](https://user-images.githubusercontent.com/112249/86022645-f3ce5580-ba2a-11ea-80cc-f3887295f237.png)

**Comment by vincentfretin** [comment]
This will be fixed in the following releases maybe for Plone 5.2.2 :
- plone.app.contenttypes 2.1.8
- plone.app.content 3.8.4
- plone.app.vocabularies 4.1.3
