### ISSUE TITLE
Collection portlet lacks configuration for # items to display

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2604]
We created a collection for showing the "recent changes" of all content across the site.
The collection display options are perfectly fine for controlling #items, #items per batch etc.
You want to reuse the collection with a collection portlet and display the latest N items. There is no to control the number of items being displayed inside the portlet unless you reconfigure the collection's display options which then influence the collection display.

**Comment by davisagli** [comment]
There's a `limit` option for the collection portlet; is it not working? https://github.com/plone/plone.portlet.collection/blob/master/plone/portlet/collection/collection.py#L66

**Comment by zopyx** [comment]
My bad...sorry for being blind.

**Comment by davisagli** [comment]
@zopyx I think I found your problem: 
![screen shot 2018-10-30 at 9 38 49 am](https://user-images.githubusercontent.com/49014/47721958-abdca700-dc27-11e8-8c96-e93f64721076.png)

**Comment by zopyx** [comment]
#fake-news
