### ISSUE TITLE
Resource filter in /@@resourceregistry-controlpanel not working Plone 5.1.4

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2609]
/@@resourceregistry-controlpanel provide an input field for filtering the resources.

This functionality is not working (tested on plone-demo.info, Plone 5.1)

**Comment by uwaiszaki** [comment]
@zopyx . Can u tell me where are the files related to the search option?

**Comment by davisagli** [comment]
In Plone 6 the resource registry no longer has a filterable list of resources, only a list of bundles.
