### ISSUE TITLE
Error adding a new user with an uppercase e-mail and use_email_as_login enabled

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#261]
When adding a new user using the ``@@new-user`` or the ``@@register`` view from ``plone.app.users``, there is an issue if ``use_email_as_login`` security setting is enabled.

Normally, when ``use_email_as_login`` is enabled, user id is generated from full name. If full name is not supplied, user id is generated from the e-mail. If e-mail contains uppercase characters (e.g. 'John@Doe.com'), we get an error:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 218, in __call__
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.users.browser.register, line 712, in action_join
  Module plone.app.users.browser.register, line 484, in handle_join_success
  Module Products.PluggableAuthService.PluggableAuthService, line 1284, in updateLoginName
  Module Products.PluggableAuthService.PluggableAuthService, line 1331, in _updateLoginName
ValueError: Cannot update login name of user 'John@Doe.com' to 'john@doe.com'. Possibly duplicate.
```

The most obvious solution would be to use pas.applyTranform on the email when generating a user id [2], so that uppercase email is transformed to lowercase. Are there any downsides to this?

Alternatively, since using email as a user id has some problems, as outlined in the generate_user_id docstring[1], we might want to consider alternative solutions:

* Use uuid as user id
* Make full name field required
* Show the user name field even when the ``use_email_as_login`` is enabled

Using uuid seems the best option, though we'd have to change the templates to show the user's email instead of the 'ugly' uuid.

[1] https://github.com/plone/plone.app.users/blob/master/plone/app/users/browser/register.py#L154
[2] https://github.com/plone/plone.app.users/blob/master/plone/app/users/browser/register.py#L218

**Comment by pbauer** [comment]
Fixed.
