### ISSUE TITLE
CSRF protection screen apperas when custom site logo was uploaded in @@site-controlpanel

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#2628]
_### What I did:_

- install fresh Plone
- Upload a custom Site Logo in @@site-controlpanel 
- go back to configuration overview
- click again on @@site-controlpanel

_### What I expect to happen:_

The @@site-controlpanel form appears

_### What actually happened:_

The @@confirm-action screen of plone.protect appears

_### What version of Plone/ Addons I am using:_

Plone 5.1.5, 5.2b1

_### possible explanation:_

wild guess: the scaled preview of the logo triggers a write on read event? should be handled by plone.scale?

**Comment by pbauer** [comment]
I think this is related to https://github.com/plone/Products.CMFPlone/issues/2709

**Comment by petschki** [comment]
I can confirm, that with the fix from @mauritsvanrees https://github.com/plone/plone.formwidget.namedfile/pull/38 this issue is solved.
