### ISSUE TITLE
Plone 5 Shows Error When Saving Default Values for Dexterity Fields

### ISSUE THREAD

**Issue by CorySanin** [plone/Products.CMFPlone#2629]
### What version of Plone/ Addons I am using: 5.0.8

The bug occurs because it tries to also save defaults for behaviors. But afaik behaviors can't have defaults set, or at least not in the same way as regular fields. plone.schemaeditor 2.0.20 fixes this bug. Plone 5.0.8 is using plone.schemaeditor 2.0.17.

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
