### ISSUE TITLE
TinyMCE based content can overflow to the right

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2631]
Plone 5.1.4

The content (migrated from a Plone 4.3 site) overflow the right border. This must never happen.
Content managed through TinyMCE must always fit into the given grid.
![screenshot-dev zopyx de-5080-2018 11 20-13-20-57](https://user-images.githubusercontent.com/594239/48773340-66137b80-ecc7-11e8-851f-48d5ac87fb0f.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
