### ISSUE TITLE
Inconsistent borders out of the box with Plone 5.1.4

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2636]
See screenshot showing the plone.app.multilingual edit interface on a Plone 5.1.4 site:

- inconsistent  left/right borders of the dark blue header
- why can't the theme allocate 100% of the browsers windows width...a major wasting of space for giving the editor the space that it needs here for editing and translating content

![screenshot-dev zopyx de-5080-2018 11 27-16-05-49](https://user-images.githubusercontent.com/594239/49090662-721ab280-f25e-11e8-9585-238fb97b7ac9.png)

**Comment by davisagli** [comment]
Isn't that extra space on the left meant to be for the toolbar? Where's the toolbar?

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
