### ISSUE TITLE
Position of "change notes" field in edit dialog of Document/Page (move it down above the Save button)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2640]
The input field for "change notes" inside the standard documen/page edit view should be below the text field. First you edit your content and then you add a change note before saving the document but not in between.

![screenshot-dev zopyx de-5080-2018 11 29-12-35-24](https://user-images.githubusercontent.com/594239/49219424-8207d300-f3d3-11e8-891d-cdc72bcbffdf.png)

**Comment by gforcada** [comment]
@zopyx I think, untested, that with this small change is enough, would you mind trying it? https://github.com/plone/plone.app.versioningbehavior/pull/44

**Comment by zopyx** [comment]
Seems to work
