### ISSUE TITLE
In-Out widget overflow

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2650]
Plone 5.1.4, see screenshot
![screenshot-dev zopyx de-5080-2018 12 06-07-44-43](https://user-images.githubusercontent.com/594239/49566503-1bcb0500-f92b-11e8-93f2-5f0f59a5b967.png)

**Comment by virendrarajpurohit** [comment]
can i solve this issue if its not assigned to any one. also please tell me that it is located in which file so that i can make changes in it?

**Comment by davisagli** [comment]
Working in Plone 6

<img width="860" alt="Screen Shot 2022-08-24 at 5 00 57 PM" src="https://user-images.githubusercontent.com/49014/186544670-cdb52d73-8b85-4ac6-9037-7fe2637abd8c.png">
