### ISSUE TITLE
Widget for RelationChoice showing up with duplicate path information

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2653]
Plone 5.1.4:

![screenshot-dev zopyx de-5080-2018 12 07-08-40-35](https://user-images.githubusercontent.com/594239/49634084-f9ed8300-f9fb-11e8-9d25-032103e70a64.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
