### ISSUE TITLE
UI issues in fields editor

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2658]
See screenshot (Plone 5.1.4):

- overlap of field label with form ID
- field label should be left aligned
- the 'x' link for removing the current field should perhaps be placed top-right
- the "settings" link should be place right-aligned below the 'x' link

![screenshot-dev zopyx de-5080-2018 12 10-08-30-45](https://user-images.githubusercontent.com/594239/49717055-0e2cbc80-fc56-11e8-8c15-b0cd6659393c.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
