### ISSUE TITLE
UI issues XML model editor

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2659]
See screenshot (Plone 5.1.4)
![screenshot-dev zopyx de-5080-2018 12 10-08-42-58](https://user-images.githubusercontent.com/594239/49717622-f6563800-fc57-11e8-851b-95cd89fb9dc0.png)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
