### ISSUE TITLE
plone.app.event 3.2

### ISSUE THREAD

**Issue by angelawong** [plone/Products.CMFPlone#2660]

**Comment by tkimnguyen** [comment]
Probably best to ask this in the forum https://community.plone.org

**Comment by tkimnguyen** [comment]
I see you did post in https://community.plone.org/t/add-folder-fields-are-missing/7641/2 so am closing this for now.

**Comment by angelawong** [comment]
Thanks. I posted it here because I was not sure if it were a bug.
