### ISSUE TITLE
Multiple UI issues on navigation portlet

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2661]
See screenshot (Plone 5.2a1)

- broken alignment of icons and text
- icons shown on left and right hand side ..their is no consistency

![screenshot-dev zopyx de-8080-2018 12 11-16-26-39](https://user-images.githubusercontent.com/594239/49810503-a6fc2e80-fd61-11e8-8f16-a90cc692bfee.png)

**Comment by vincentfretin** [comment]
This seems fine in Plone 5.2.2. I'm closing it.
![Capture d’écran de 2020-07-01 13-04-57](https://user-images.githubusercontent.com/112249/86237143-87269880-bb9b-11ea-9696-0023fbb16fba.png)
