### ISSUE TITLE
Display folder content do not show the 21. element in content area

### ISSUE THREAD

**Issue by filith** [plone/Products.CMFPlone#2662]
### What I did: 
I created a folder named FAQs and added 21 pages  with differnt subjects. 
I set the view mode of this folder to "All content"

### What I expect to happen:
I exepted to see all content of all pages in this folder in the content area. With a breakdown  to different pages at a defined number of entries

### What actually happened:
If the folder contains exactly 21 entries the subnavigation indeed shows all content elements of the folder. But in the content area only 20 entries displayed. And only one page is avaliable.
If a add a 22th page in the folder the second page with two items is avaliable . 

### What version of Plone/ Addons I am using:

5.1.4 (5114)

**Comment by rafaelbco** [comment]
I think this is probably related to this one: https://github.com/plone/plone.batching/issues/9
