### ISSUE TITLE
Javascript error in `jquery-ext.js` from patternslib

### ISSUE THREAD

**Issue by kcleong** [plone/Products.CMFPlone#2674]
### What I did:

Call `startsWith` javascript function with a special char (such as `?`) on any plone site:

```javascript
var example = 'spam bacon eggs spam';
console.log(example.startsWith('?'));
```
On plone.org in the Chrome developer toolbar:

<img width="758" alt="screenshot 2018-12-21 at 12 28 10" src="https://user-images.githubusercontent.com/201650/50340598-ebcf5480-051b-11e9-8b22-491d9f87c23f.png">

When  I click 'default.js' in above screenshot, I see:

<img width="756" alt="screenshot 2018-12-21 at 12 29 11" src="https://user-images.githubusercontent.com/201650/50340637-19b49900-051c-11e9-95c7-541014a85bce.png">

### What I expect to happen:

The `startsWith` function should not return an error. See this codepen where I reproduced the error: https://codepen.io/anon/pen/oJZBqz

### What actually happened:

The `startswith` and `endswith` functions are overridden using prototype in:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/components/patternslib/src/core/jquery-ext.js#L226-L227

A PR (see https://github.com/plone/plone.patternslib/pull/26) was merged in `plone.patternslib` to only override these methods if they are not present. Most modern browsers (if not all) have support for those methods. 

What would be a good solution to fix this in `Products.CMFPlone/static/components/patternslib/src/core/jquery-ext.js`? I am not that familiar with these static resources, I think the easiest would be to replace the two offending lines with the fix from PR 26 in `plone.patternslib`. If I look at the commit history (see https://github.com/plone/plone.patternslib/commits/master/src/plone/patternslib/static/components/patternslib/src/core/jquery-ext.js) of `jquery-ext.js`, I see only two commits. There are not other changes in this file, expect for the first commit and the fix from the PR.

### What version of Plone/ Addons I am using:

Plone 5.1.4

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
