### ISSUE TITLE
Manually update Italian TinyMCE translations

### ISSUE THREAD

**Issue by cekk** [plone/Products.CMFPlone#2679]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

I've found some typos in the builded TinyMCE [translations](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/components/tinymce-builded/js/tinymce/langs/it.js).

I've already opened an issue in TinyMCE's repo, but i don't know when and in which version they will fix them.
Can i manually fix them here, or it's not a good practice?

**Comment by gforcada** [comment]
I would say yes, notice though that they might get overriden by a tinymce update.

**Comment by cekk** [comment]
Yes, i know :(
But i don't know when tiny will may fix these typos in a public release.

**Comment by vincentfretin** [comment]
@cekk Did you update the translations in Products.CMFPlone? Can we close this issue?

**Comment by vincentfretin** [comment]
Did we have a new release since then @cekk?

**Comment by cekk** [comment]
Unluckily not yet..I totally forgot about this issue

**Comment by vincentfretin** [comment]
In mockup master for Plone 5.2.2 we use tinymce-builded 4.7.13
https://github.com/plone/mockup/blob/9bb1ce1aa2ffe5963dfe7aa6cbba88800b2377ee/package.json#L53
with latest commit dating from Sep 13, 2018 so indeed before you created this issue.
I see there is a 4.8.3 release there that was made by @erral the 14 Sep 2018 or 5.0.1 release by @frapell the 28 Feb 2019
Actually I just saw @fredvd and @erral comments about that here
https://community.plone.org/t/list-of-tinymce-defects-in-plone-5-2-call-for-fixing-issues-and-participation/12257/13
and here
https://community.plone.org/t/list-of-tinymce-defects-in-plone-5-2-call-for-fixing-issues-and-participation/12257/14

There is PR from @frapell to update mockup to use TinyMCE 5.0.1 there https://github.com/plone/mockup/pull/901

**Comment by erral** [comment]
FWIW TinyMCE translations are handled in TinyMCE's transifex: https://www.transifex.com/projects/p/tinymce/

**Comment by jensens** [comment]
upstream problem
