### ISSUE TITLE
POST to @@actions-form ignores validation error

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2689]
The edit for for actions ignores validation errors upon saving/applying.

I used an URL like `https://some.com` as `ACTION URL`.

The backend raises

```
2019-01-07 15:02:26,589 ERROR [Zope.SiteErrorLog:250][waitress] 1546873346.5875420.1529143591444001 https://python3.plone-demo.info/portal_actions/site_actions/XXXXX/@@action-form
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module z3c.form.form, line 233, in __call__
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module z3c.form.form, line 312, in handleApply
  Module z3c.form.group, line 114, in applyChanges
  Module z3c.form.form, line 51, in applyChanges
  Module z3c.form.datamanager, line 91, in set
  Module Products.CMFPlone.controlpanel.browser.actions, line 121, in set_url_expr
  Module Products.CMFCore.ActionInformation, line 127, in _setPropValue
  Module Products.CMFCore.Expression, line 43, in __init__
  Module zope.tales.tales, line 640, in compile
zope.tales.tales.CompilerError: Unrecognized expression type "https".
```

The JS call receives a 500 response but does not report the failure on the UI...

Verified for Plone 5.2a2, unverified for Plone 5.1.X

**Comment by uwaiszaki** [comment]
@zopyx . it is mentioned in description to use string:${globals_view/navigationRootUrl}/page .
We can add a url by adding string:https://www.google.com instead of https://www.google.com.
Should i add this in description? If yes , i would like to work on this.

**Comment by ale-rt** [comment]
@uwaiszaki I already started adding some validation to that form. You are welcome to review, live test and add test coverage to my PR #2715.

**Comment by uwaiszaki** [comment]
@ale-rt  what is the need to add string: in front of url ?

**Comment by ale-rt** [comment]
That field contains a so called expression: https://docs.plone.org/develop/plone/functionality/expressions.html

**Comment by uwaiszaki** [comment]
@ale-rt . Is this adding validation in url_expr ? I can't find any constraint on url_expr

**Comment by ale-rt** [comment]
Validation is added here: https://github.com/plone/Products.CMFPlone/pull/2715/files#diff-fa6b670554e72078393552c295dc150dR1733
