### ISSUE TITLE
Unwanted word break in @@overview-controlpanel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2691]
See screenshot (Plone 5.1, 5.2).

Either avoid word breaking completely or add `hyphenate: auto` to CSS (as it was added to the CSS of the toolbar for similar issues).

![screenshot-dev zopyx de-20080-2019 01 08-09-17-33](https://user-images.githubusercontent.com/594239/50818150-78ed1880-1326-11e9-90d0-8146ad408d4f.png)

**Comment by vinay72** [comment]
Can you please provide me the link of the file in which I have to make changes as I'm finding difficult to search a file to work in this issue?

**Comment by agitator** [comment]
@vinay72 https://github.com/plone/plonetheme.barceloneta

**Comment by jensens** [comment]
Looks good in 5.2.10 and 6.0.2
