### ISSUE TITLE
Effective/Expires date UI (date picker) broken/crazyness

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#270]
This is a problem with the IPublication behaviour, but I suspect its moreover the datepicker.
- if a value in effective was selected nothing is filled in the field and it jumps immediatly to expires field (I would expect to jump to time field).
- if in expires a value is selected its stored in expires. 
- if I then click somewhere a date appears in effective and so on.
seems kind of random. A similar oddness happens on time selection (also time different from the selected is shown in UI).

Problem occurs on todays coredev branch 5.0 buildout.

**Comment by vangheem** [comment]
This still a problem? Seems to be working for me. Please close if it's no longer valid.

**Comment by jensens** [comment]
IIRC @thet fixed this already?

**Comment by thet** [comment]
can't remember. i'll look at this issue later today.

**Comment by thet** [comment]
looks like fixed. i think this was a side effect of some javascript mess.
however, i'm closing this.
