### ISSUE TITLE
CMFEditions 3.2.1 breaks archetypes support

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#2701]
## BUG

CMFEditions 3.2.1 which is part of 5.1.3 breaks the archetypes support, due to a missing upgrade step in plone.app.upgrades.

We need to add the upgrade step into plone.app.upgrades, which I'm duing soon.
This is more for people who have the problem that Archetypes based content types in migrated sites are no longer able to save data.

You can fix it, by releading the CMFEditions profile in portal_setup manually.

**Comment by mauritsvanrees** [comment]
Fix is in plone.app.upgrade 2.0.21 from February 2019.
