### ISSUE TITLE
5.2 coredev is not building some parts

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2711]
The following parts from `[buildout]` are not build when running buildout in Python 2:

```
    zopepy
    packages
    releaser
    z3c_checkversions
    dependencies
```

They are defined with `parts +=` in `[buildout]`. My guess is that the way conditional parts work does not extend values defined in the unconditional part but overwrites them.

This is the conditional part that loses these parts: 
```
[buildout:python27]
parts +=
    instance
    instance-archetypes
    ploneversioncheck

extensions +=
    plone.versioncheck
```
This means they also need to be defined in `[instance:python27]`.

**Comment by mauritsvanrees** [comment]
Reminds me of a problem with extensions a few months ago, fixed with this [PR](https://github.com/plone/buildout.coredev/pull/558).
