### ISSUE TITLE
./bin/instance fg does not set debug mode on

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2719]
### What I did:

Pulled buildout.coredev master and added plone.reload in my local.cfg

### What I expect to happen:

When I start the instance in foreground and browsed to http://localhost:8080/reload?action=code the code I modified reloads.

### What actually happened:

I got a message that code cannot be reloaded because the instance is in foreground mode

### What version of Plone/ Addons I am using:

Plone 5.2 corededev buildout + plone.reload 3.0.0

**Comment by ale-rt** [comment]
Workaround add `debug-mode = on` in the `[instance]` section of the buildout file, e.g.:
```
[instance]
debug-mode = on
```

Thanks @pbauer for the suggestion!

**Comment by tschorr** [comment]
Fixed with https://github.com/plone/plone.recipe.zope2instance/pull/69

**Comment by ale-rt** [comment]
It works perfectly! Thank you :)
