### ISSUE TITLE
bin/instance fg: display deprecation warnings

### ISSUE THREAD

**Issue by tschorr** [plone/Products.CMFPlone#2724]
DeprecationWarnings currently don't show up at all when running bin/instance fg on Plone 5.2/WSGI.

Expected behavior:

- bin/instance fg should honor PYTHONWARNINGS environment settings 
- if PYTHONWARNINGS is unset, bin/instance fg should log all warnings
- other modes of execution of bin/instance should not log warnings

**Comment by ale-rt** [comment]
I can confirm this works now:
```
[ale@emily buildout.coredev.alpine]$ ./bin/instance fg
/home/ale/Code/plone/buildout.coredev.alpine/lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
/home/ale/.buildout/eggs/Zope-4.0b8-py3.7.egg/Zope2/Startup/serve.py:270: DeprecationWarning: 'U' mode is deprecated
/home/ale/.buildout/eggs/Products.PythonScripts-4.2-py3.7.egg/Products/PythonScripts/PythonScript.py:53: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp  # NOQA
...
```

**Comment by icemac** [comment]
@ale-rt 
At least this one is funny:
`/home/ale/.buildout/eggs/Zope-4.0b8-py3.7.egg/Zope2/Startup/serve.py:270: DeprecationWarning: 'U' mode is deprecated`
[Zope2/Startup/serve.py](https://github.com/zopefoundation/Zope/blob/4.0b8/src/Zope2/Startup/serve.py) only has 219 lines.

**Comment by ale-rt** [comment]
Well, I can confirm the fancyness:
```
[ale@emily buildout.coredev.alpine]$ wc -l /home/ale/.buildout/eggs/Zope-4.0b8-py3.7.egg/Zope2/Startup/serve.py
219 /home/ale/.buildout/eggs/Zope-4.0b8-py3.7.egg/Zope2/Startup/serve.py
[ale@emily buildout.coredev.alpine]$ ./bin/instance fg
/home/ale/Code/plone/buildout.coredev.alpine/lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
/home/ale/.buildout/eggs/Zope-4.0b8-py3.7.egg/Zope2/Startup/serve.py:273: DeprecationWarning: 'U' mode is deprecated
...
```

BTW today is 273

**Comment by ale-rt** [comment]
See also https://github.com/zopefoundation/Zope/issues/415
