### ISSUE TITLE
SIGUSR1 and SIGUSR2 are not handled correctly in Plone 5.2

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2729]
When running Plone 5.1, you can send some signals to the instance from the command line.  I know two that are supported:

```
$ kill -SIGUSR2 $(cat var/instance.pid)  # reopen log files
$ kill -SIGUSR1 $(cat var/instance.pid)  # thread dump
```

Result, when run in the foreground:

```
2019-02-06 18:56:52 INFO SignalHandler Caught signal SIGUSR2
2019-02-06 18:56:52 INFO Z2 Log files reopened successfully
2019-02-06 18:57:00 INFO SignalHandler Caught signal SIGUSR1
Threads traceback dump at 2019-02-06 18:57:00

End of dump
```

In 5.2, both with Python 2.7 and 3.6, this simply kills the instance. We don't have a `var/instance.pid` anymore, so we have to look up the correct process id.

```
$ ps aux | grep python
...
maurits          35095   0.0  1.2  4563840 205456 s001  S+    7:01pm   0:12.40 /Users/maurits/community/plone-coredev/5.2/bin/python2.7 /Users/maurits/community/plone-coredev/5.2/parts/instance/bin/interpreter /Users/maurits/shared-eggs/cp27m/Zope-4.0b8-py2.7.egg/Zope2/Startup/serve.py /Users/maurits/community/plone-coredev/5.2/parts/instance/etc/wsgi.ini -d debug-mode=on
maurits          35088   0.0  0.3  4395964  54916 s001  S+    7:01pm   0:04.36 /Users/maurits/community/plone-coredev/5.2/bin/python2.7 bin/instance fg
```

When I `kill -SIGUSR1 35095` (the first one) both processes die.  There is no message. There is no `var/log/instance.log`.

When I try again, restart (`bin/instance fg`) and kill the second one, only the second one dies. This time with a message:

```
User defined signal 1: 30
```

Here the containing script is killed, and the instance keeps running: I can access port 8080 just fine.

This may be an error in Zope or in plone.recipe.zope2instance.

**Comment by mauritsvanrees** [comment]
I just talked with @icemac and he said this was part of `ZServer`. Plone 5.2 is using a WSGI server now, and this is something that would need to be handled by this server. It is questionable whether this is possible.

**Comment by icemac** [comment]
See [ZServer/Signals/Signals.py](https://github.com/zopefoundation/ZServer/blob/968d86cc9f125d4a72e89caff0204256066e9500/src/Signals/Signals.py#L82-L108) for the relevant code.

**Comment by davisagli** [comment]
Note: you can use https://github.com/benfred/py-spy as a different way to get stack traces.

**Comment by jensens** [comment]
I think we can close this.
