### ISSUE TITLE
SMTP authentication is broken

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2732]
In Plone 5.2 using Python 3 you cannot use an SMTP that requires authentication.

The original issue comes from https://github.com/zopefoundation/zope.sendmail/pull/16 and it is solved by https://github.com/zopefoundation/zope.sendmail/pull/20.

We need to wait for a zope.sendmail release and we need to update our pins to use it.

Note the pin comes from Zope:
```
[ale@emily buildout.coredev]$ ./bin/buildout annotate|grep sendma -A 1
zope.sendmail= 4.2
    https://raw.githubusercontent.com/zopefoundation/Zope/4.0b8/versions-prod.cfg
```

**Comment by agitator** [comment]
zope.sendmail 4.2.1 is released

**Comment by jensens** [comment]
its part of Zope 4.0b9 https://raw.githubusercontent.com/zopefoundation/Zope/4.0b9/versions-prod.cfg
so we need to get https://github.com/plone/buildout.coredev/pull/564 merged.
