### ISSUE TITLE
Release Plone 5.0.10

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#2735]
Creating an issue so that I can create a changelog entry. Whee!

**Comment by gforcada** [comment]
@plone/release-team would it make sense to create issues for each release where we have checkboxes to keep control on the process steps that lead to a new release? :thinking: 

It will not only give us more insight on the process, but also it will be a point of transparency on how the release is going, and if efforts are needed, or blockers happened, where they can be reported as well.

**Comment by mauritsvanrees** [comment]
This could help, yes. Informally this is of course what the 'Plone X is pending' message on community.plone.org is for, but an issue can be the more formal way.

The main issue text could be a copy of the checklist from somewhere in docs.plone.org, or a redacted version thereof. Appended could be a list of issues that come up during testing and that we consider blockers.
At the current point with 5.0.10, all checkboxes would have been marked, except possibly the creation of the Installer.

Some communication could or should probably still happen on the release team e-mail, but a central ticket can help a lot for everyone to get a clearer idea of how far along a release is, and what the holdup is and where they can help.

We can give it a try next time and see if it works.

**Comment by gforcada** [comment]
We can create a github issue template for that
