### ISSUE TITLE
Cannot compile barceloneta

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2738]
### What I did:

1. I checked out plonetheme.barceloneta
2. I ran `npm i`
3. I ran `grunt less`

### What I expect to happen:

A new ccs compilation should be produced

### What actually happened:

I had this error:
```
[ale@emily plonetheme.barceloneta]$ grunt less
Running "less:dist" (less) task
>> plonetheme/barceloneta/theme/less/barceloneta.plone.local.less: [L1:C0] resource 'https://raw.githubusercontent.com/plone/Products.CMFPlone/master/Products/CMFPlone/static/patterns/toolbar/src/css/variables.less' was not found
Warning: Error compiling plonetheme/barceloneta/theme/less/barceloneta.plone.local.less Use --force to continue.

Aborted due to warnings.
```

### What version of Plone/ Addons I am using:

buildout.coredev 5.2

**Comment by ale-rt** [comment]
Apparently this file location changed: https://raw.githubusercontent.com/plone/Products.CMFPlone/5.1.4/Products/CMFPlone/static/patterns/toolbar/src/css/variables.less

**Comment by ale-rt** [comment]
This was removed in 94bdfbf368a9d820d5a5a55f0c8601cbf1d493f0:
```
[ale@emily patterns]$ git show 94bdfbf368a9d820d5a5a55f0c8601cbf1d493f0 --name-status |grep variables.less
D       Products/CMFPlone/static/components/bootstrap/less/variables.less
D       Products/CMFPlone/static/patterns/toolbar/src/css/variables.less
```

**Comment by thet** [comment]
OK - so also Barceloneta has to get some fixes to support plone.staticresources.
Can do that in the next days..

**Comment by ale-rt** [comment]
For the moment I have this workaroud in place:
https://github.com/plone/plonetheme.barceloneta/commit/5bf69e11ef02a7ccfbed887eae4877101e674d0a

**Comment by vincentfretin** [comment]
Ah! For https://github.com/plone/plonetheme.barceloneta/pull/205
I didn't know how to rebuild the theme, I searched for documentation but didn't find any. It never occurred to me to look at grunt.
I rebuilt the theme with `npx lessc`, I added the command in the README.
