### ISSUE TITLE
Provide an IEditView that works like IViewView

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#274]
*(filling it here as plone.app.layout has the issue tracker disabled).*

Currently plone.app.layout provides an ``IViewView`` which you can use to register, let's say viewlets to it. This way you make sure that a viewlet is only shown on the view of an object but not on the add or edit form.

We are using that quite heavily on https://www.freitag.de and now we have a use case where we want to do the same for the edit view. Will provide a pull request in some days, just opening this issue here so that discussion about it can happen before the pull request.

Would be a change like that on plone.app.layout welcome?

**Comment by vangheem** [comment]
Closing this until we get more info about the status.
