### ISSUE TITLE
New Navigation does not highlight current item if it is file or image

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2744]
E.g. http://demo-latest-py3.plone.org/de/demo/a-image.jpg/view
Related to #2730

**Comment by ale-rt** [comment]
Probably related: https://github.com/plone/plonetheme.barceloneta/pull/177

**Comment by pbauer** [comment]
I think it requires a change in the pattern `navigationmarker`. Ping @agitator

**Comment by agitator** [comment]
I'll look into it

**Comment by agitator** [comment]
fixed with https://github.com/plone/plone.staticresources/pull/18
