### ISSUE TITLE
verbose-security is ignored in object_paste and folder_paste 

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#276]
Since `object_paste` and `folder_paste` handle Unauthorized-Exceptions in a try-except block the log-messages of verbose-security (a setting in plone.recipe.zope2instance that helps debugging these problems) are swallowed. This applies to Plone 4 (where object_paste is a python-script) and Plone 5 (where it is a browser-view).

**Comment by jensens** [comment]
probably outdated
