### ISSUE TITLE
Toolbar completely dysfunctional on iPad with Plone 5.1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2761]
See screenshot.

Toolbar on mobile (iPad here) open on the right side. The submenus don't show up when you click at them.

Seems to work on Plone 5.2 where the toolbar opens on the left side.
![img_1058](https://user-images.githubusercontent.com/594239/53031230-b936cf00-346c-11e9-8808-c5cb432a5497.png)

**Comment by vincentfretin** [comment]
I tested Plone 5.2.2rc1 on Safari iPad 2018 6th gen, the toolbar opens on the left, I don't reproduce the issue.
