### ISSUE TITLE
Main content jumping to the left when opening a toolbar submenu on mobile

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2762]
Plone 5.2/iPad

Click on a submenu and the underlaying main content screen of Plone suddenly jumps to the left...unacceptable, unexpected, bad user experience

![img_1062](https://user-images.githubusercontent.com/594239/53039442-864a0680-347f-11e9-9eb1-3e4909afa23d.png)

![img_1063](https://user-images.githubusercontent.com/594239/53039446-8944f700-347f-11e9-8ffd-57fcdafa50e8.png)

**Comment by vincentfretin** [comment]
Still true with Plone 5.2.2rc1 on iPad Safari iOS 13.5.1

**Comment by jensens** [comment]
can not reproduce on 5.2.10 https://52.demo.plone.org/de
