### ISSUE TITLE
List of display columns in folder contents view should be stored globally and not per folder 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2764]
It seems that the list of visible colums of the folder contents view is stored per folder individually.
So when you enter a new folder you will not see the list of columns that you configured earlier.
This is a usability foul. As user I want to login configured my columns in order work on a particular probleme (e.g. setting "exclude from navigation" for a bunch of items in a bunch of folder. So right now I need to enable this column every time on each folder..this is annoying from the users prospective and should be considered as an error. Such a configuration should be global across all folders and remembered at least for the lifetime of the session.

**Comment by davisagli** [comment]
In Plone 6 it seems to be persisting across folders.
