### ISSUE TITLE
Stop calling initializeTFC over and over

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2765]
## BUG/PROBLEM REPORT

At production we use Products.LongRequestLogger and since we upgraded to 5.1.5 (yeah, sorry late at the party :sweat_smile: although the problematic code is still there on CMFPlone master ) we noticed that there is a huge amount of traces to this function: ``initializeTFC``:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/PloneBaseTool.py#L23-L35

The problem is that as we don't have ATCT available, the function is called over and over on every single request.

The global ``TempFolderClass`` is never assigned anything, so it always tries to import ATCT, failing at it, and giving up (the ``pass``).

I guess that just changing the pass to a ``TempFolderClass = False`` would be enough. The function would still be called anyway, but the *expensive* ``pkg_resources.get_distribution`` would be called only once.

**Comment by gforcada** [comment]
@ale-rt thanks for the merges!

**Comment by davisagli** [comment]
Nice catch!
