### ISSUE TITLE
Enable dropdown navigation by default

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2772]
When playing around with http://demo-latest-py3.plone.org I get the feeling that having dropdown-navigation enabled by default would be great since it enhances usability a lot. 

But: When upgrading existing sites to 5.2 that would probably be very irritating and ruin layouts. 

So I propose to:

* Set `plone.navigation_depth` to a default of 3 (which is the setting on http://demo-latest-py3.plone.org) for new sites.
* Disable it (set `plone.navigation_depth` to a level of 0) during a upgrade to 5.2

Side-note: It is a little irritating that 0 and 1 result in the same navigation.

**Comment by ale-rt** [comment]
Be aware that the time needed to render the navigation grows exponentially with plone.navigation_depth.
Setting 3 as a default seems too much to me.

Maybe it would be cool to add a warning about potential speed issues in the description of the field in the control panel?

**Comment by pbauer** [comment]
We discussed the suggestion to add a warning and thought that it is probably self-evident that a high level in sites with a lot of content can slow down the site. Since it is still only one catalog-query it should be reasonably fast for most use-websites.
