### ISSUE TITLE
PLIP: Archetypes End of Life

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#2775]
## Abstract

Dexterity has been around forever and we already supported Archetypes way longer than anyone could expect. It is time to say goodbye and be 100% clear about this.

## Motivation

Costs for supporting Archetypes with Python 3 would be huge and there is little to gain.

## Assumptions

People had more than enough time to prepare for this.

## Proposal & Implementation

None.

## Deliverables

None.

## Risks

None.

## Participants

- Philip Bauer
- Timo Stollenwerk

**Comment by tisto** [comment]
Note: Approved by the FWT: https://community.plone.org/t/fwt-meeting-minutes-2019-04-16/8387

**Comment by ale-rt** [comment]
@tisto I would consider this as done CC @plone/framework-team
