### ISSUE TITLE
CSS issue in add-ons controlpanel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2779]
See 
<img width="714" alt="screenshot 2019-02-28 09 33 32" src="https://user-images.githubusercontent.com/594239/53552642-118c6180-3b3c-11e9-88ed-6b829a7c0b75.png">
"Uninstall" button

**Comment by pbauer** [comment]
Same is true for actions:
<img width="272" alt="actions" src="https://user-images.githubusercontent.com/453208/53684553-2bca6900-3d0f-11e9-97a5-9a8b4cccfc4d.png">

It is broken by https://github.com/plone/plonetheme.barceloneta/pull/171. I'll revert that merge.

**Comment by pbauer** [comment]
I could not revert due to later changes in barceloneta.

**Comment by vincentfretin** [comment]
Anyone having experience on rebuilding barceloneta can please remove 
```
.pull-right{
       .standalone{    
               width:65px;
               } 
       .destructive{
               width:65px;
       }
}
```
from `plonetheme/barceloneta/theme/less/buttons.plone.less` and rebuild it?
Please @pbauer @ale-rt @agitator

**Comment by agitator** [comment]
https://github.com/plone/plonetheme.barceloneta/blob/master/HOWTO_DEVELOP.rst does this not work?

**Comment by vincentfretin** [comment]
Thanks I didn't saw this doc. It works great. I'll create a PR in a few minutes.
