### ISSUE TITLE
Export of registry.xml via portal_setup failed under Plone 5.2 Py3

### ISSUE THREAD

**Issue by 1letter** [plone/Products.CMFPlone#2782]
### What I did:

- Install [coredev buildout py2py3 via CoredevMultiPy](https://github.com/collective/coredev52multipy)
- add Plone Site
- got to ZMI -> plonesite -> portal_setup -> export -> check 'Export the configuration registry schemata
Exports records and settings' -> click 'Export Selected Steps'

### What I expect to happen:

- Download of a setup_tool-xxxx.tar.gz File

### What actually happened:

Traceback:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module Products.GenericSetup.tool, line 646, in manage_exportSelectedSteps
  Module Products.GenericSetup.tool, line 1298, in _doRunExportSteps
  Module plone.app.registry.exportimport.handler, line 94, in exportRegistry
  Module Products.GenericSetup.context, line 442, in writeDataFile
ValueError: Unicode text is not supported, even if it only contains ascii. Please encode your data. See GS 1.7.0 changes for more
```
But when i go to Plone Site -> portal_registry -> export and click the button 'Export Now', all is fine. i get a downloadfile registry.xml

### What version of Plone/ Addons I am using:

- Plain Buildout Coredev 5.2 with Py3

**It did not happen with the same procedure on Py2 Version of Plone 5.2**

**Comment by gforcada** [comment]
Fixed with https://github.com/plone/plone.app.registry/pull/35 right?
