### ISSUE TITLE
New 2-level navigation...sematics of arrow up/down?

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2787]
What is the purpose or the sematics of the arrow in the navigation...it just turns from arrow up to arrow down and back without any further UI feedback...makes no sense.

Plone 5.2RC1

https://nimb.ws/9DoSrR

**Comment by agitator** [comment]
In the mobile version it's the turning if the menu is opened, for the desktop version the arrow marks that there is a submenu.

If you click it, which is not needed as the menu already opens, it will change the state and turn.

At first I let it stay open based on the state, but didn't find that useful... for example if you resize the window from mobile to desktop size, the menu was in expanded which seemed weird.

But I'm open proposals for further improvement ;-)

**Comment by zopyx** [comment]
The behavior is ok on mobile but it should behave the same way on desktop as well. I don't see why the behavior should differ. If you click on the icon when the menu is open on desktop then it should close the menu in the same way.

**Comment by zopyx** [comment]
Well, the submenu opens automatically when you hover over the main menu item fine. So there
must be an indicator that there is a submenu. But for desktop there is no need to implement this arrow up/down game at all. Just leave the arrow down icon on desktop (when you can hover of the subitems) without any changing the icon state.

**Comment by zopyx** [comment]
The icons on mobile are too small. I have large fingers then it is very easy to click outside of the icons and load the view of the corresponding folder object.

**Comment by agitator** [comment]
The opener was already fixed but not released yet. I increased the size of the touch area on mobile

<img width="722" alt="screenshot 2019-03-06 at 15 23 08" src="https://user-images.githubusercontent.com/365761/53891750-50825180-402b-11e9-85b4-86cc4cec1a18.png">

fixed with https://github.com/plone/plonetheme.barceloneta/pull/181 can you test it?

**Comment by agitator** [comment]
fixed with https://github.com/plone/plonetheme.barceloneta/pull/181
