### ISSUE TITLE
Wrong default values for msgid label_email

### ISSUE THREAD

**Issue by erral** [plone/Products.CMFPlone#2790]
label_email msgid is used with a wrong default value:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/login/login.py#L106

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/login/login_help.py#L62

Plone is already using "E-mail" as default value elsewhere:

https://github.com/plone/plone.app.portlets/blob/master/plone/app/portlets/portlets/login.pt#L48

https://github.com/plone/plone.app.users/blob/master/plone/app/users/schema.py#L67

**Comment by vincentfretin** [comment]
I guess you saw the i18ndude warnings. :) Indeed Plone 5.2 currently gives
```
Warning: msgid 'label_email' in plone.app.users/plone/app/users/browser/membersearch.py:29 already exists with a different default (bad: E-mail, should be: Email)
The references for the existent value are:
Products.CMFPlone/Products/CMFPlone/browser/login/login_help.py:61
Products.CMFPlone/Products/CMFPlone/browser/login/login.py:109
Warning: msgid 'label_email' in plone.app.users/plone/app/users/schema.py:67 already exists with a different default (bad: E-mail, should be: Email)
The references for the existent value are:
Products.CMFPlone/Products/CMFPlone/browser/login/login_help.py:61
plone.app.users/plone/app/users/browser/membersearch.py:29
Products.CMFPlone/Products/CMFPlone/browser/login/login.py:109
Warning: msgid 'label_email' in plone.app.users/plone/app/users/schema.py:82 already exists with a different default (bad: E-mail, should be: Email)
The references for the existent value are:
Products.CMFPlone/Products/CMFPlone/browser/login/login_help.py:61
plone.app.users/plone/app/users/browser/membersearch.py:29
Products.CMFPlone/Products/CMFPlone/browser/login/login.py:109
plone.app.users/plone/app/users/schema.py:67
Warning: msgid 'label_email' in Products.CMFPlone/Products/CMFPlone/browser/login/login.py:109
Products.CMFPlone/Products/CMFPlone/browser/login/login_help.py:61
plone.app.users/plone/app/users/browser/membersearch.py:29
plone.app.users/plone/app/users/schema.py:67
plone.app.users/plone/app/users/schema.py:82 already exists with a different default (bad: Email, should be: E-mail)
The references for the existent value are:
plone.app.portlets/plone/app/portlets/portlets/login.pt:46
```

The message extracted is label_email, default="E-mail".

It would be great if the default message could be the same everywhere.
From the discussion on https://github.com/plone/Products.CMFPlone/pull/2791 with
@tkimnguyen @MatthewWilkes @jensens @thet 
it seems we're in favor for Email.
Feel free to create a PR for each package to change it.

**Comment by erral** [comment]
I created the PRs for plone.app.portlets and plone.app.users: https://github.com/plone/plone.app.users/pull/90 https://github.com/plone/plone.app.portlets/pull/134
