### ISSUE TITLE
http://dist.plone.org/release/5.2rc1-pending/versions.cfg flaky

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2794]
http://dist.plone.org/release/5.2rc1-pending/versions.cfg

extends an old Zope 2 versions.cfg rather than a decent Zope 4 versions.cfg

**Comment by petschki** [comment]
the whole versions.cfg is from Plone 5.1.5 ... wrong symlink? @esteele

**Comment by petschki** [comment]
https://community.plone.org/t/plone-5-2rc1-soft-released/8163/44
