### ISSUE TITLE
PAS group integration code pretty fragile (fails with with Dynamic Groups plugin)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2804]
Plone 5.2-latest

I configured a dynamic groups plugin with a simple group, predictate `python: 1` and activated the plugin. The groups control panel of Plone fails with:

```

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 142, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 295, in publish_module
  Module ZPublisher.WSGIPublisher, line 229, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupsoverview, line 35, in __call__
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupsoverview, line 58, in doSearch
AttributeError: 'NoneType' object has no attribute 'getProperty'

```

The PAS integration layer of Plone is in general notoriously fragile and weak. 

Errors should be catched and reported properly. It is impossible to spot from the error message where error occurs. Adding debugging information through `__traceback_info__` might help a bit. In general: the user/groups control panel  should remain functional or at least admin friendly. Robustness is king.

**Comment by jensens** [comment]
dup of #2773
