### ISSUE TITLE
PAS plugin management dysfunctional in Plone 5.2/WSGI?

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2807]
Plone 5.2rc1/Python 3

- add plugin (e.g. local role plugin) in PAS aka `acl_users`
- goto the plugins management screen (e.g. /acl_users/plugins/manage_plugins?plugin_type=IRolesPlugin)
- try to add one of the available plugins to the list of active plugins
- Error:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
TypeError: 'ReplaceableWrapper' object is not callable
```

Marked as blocker because the functionality of the PAS ZMI is essential.

`ReplaceableWrapper` is a functionality of Plone

**Comment by pbauer** [comment]
I cannot reproduce the issue following your steps with the current cordev.

**Comment by zopyx** [comment]
Tested on python3.plone-demo.info running 5.2RC1

**Comment by zopyx** [comment]
Seems to work with coredev. Will re-check with RC2.

**Comment by pbauer** [comment]
If you don't have a coredev use http://demo-latest-py3.plone.org for testing. It's a nightly build of the coredev.

**Comment by pbauer** [comment]
Works fine on http://demo-latest-py3.plone.org/acl_users/manage_main
