### ISSUE TITLE
Can not save website controlpanel when default page is empty.

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2813]
In some project I have an empty `default page` setting in my registry. 
```
  <records
      interface="Products.CMFPlone.interfaces.controlpanel.ISiteSchema"
      prefix="plone">
    <value key="default_page"></value>
...
```

After save of Website settings I got a validation error "required input is missing" (German: Erforderliche Eingabe fehlt.). But there was no field marked, its floats free between robots and roles field. With inspector I see there a hidden input:
```
<input id="form-widgets-default_page" name="form.widgets.default_page" value="" class="hidden-widget" type="hidden" data-_extension-text-contrast="bg">
```
The field is required but hidden with an empty value, so this is what it is causing the problem.

**Comment by petschki** [comment]
How to solve this? make `default_page` not required? In generall I think `plone.app.registry` should check if one tries to clear a required registry value... what do you think?

**Comment by jensens** [comment]
well, default page can be empty. IMO. It's OK to remove the required.
