### ISSUE TITLE
ParseError: Query contains only common words: u'\xa7*'

### ISSUE THREAD

**Issue by Gomez** [plone/Products.CMFPlone#2818]
### What I did:

Create a vanilla Plone 5.1 site with this content field:

```
from z3c.relationfield.schema import RelationChoice
from plone.app.vocabularies.catalog import CatalogSource

testfield = RelationChoice(
    title=u'Test',
    source=CatalogSource(portal_type=['Document', 'Folder']),
    required=False,
)
```
Search in this field for &, $ or other special character.

Traceback:
```
1548660778.930.314897364982 https://localhorst:8080/Plone/anct/++widget++form.widgets.origin/@@getSource
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.vocabulary, line 153, in __call__
  Module plone.app.vocabularies.catalog, line 708, in search_catalog
  Module Products.CMFPlone.CatalogTool, line 390, in searchResults
  Module Products.ZCatalog.ZCatalog, line 604, in searchResults
  Module Products.ZCatalog.Catalog, line 1072, in searchResults
  Module Products.ZCatalog.Catalog, line 551, in search
  Module Products.ZCTextIndex.ZCTextIndex, line 217, in _apply_index
  Module Products.ZCTextIndex.QueryParser, line 139, in parseQuery
ParseError: Query contains only common words: u'\xa7*'
```

### What I expect to happen:

No Traceback, search should happen.

### What actually happened:

Got a traceback, 

### What version of Plone/ Addons I am using:

Plone 5.1, no addons.

### Additional notes

Looks like escaping should happen in plone.app.vocabularies.catalog 

Related issues:
https://github.com/plone/Products.CMFPlone/issues/1537#issuecomment-214564093
https://github.com/zopefoundation/Products.ZCTextIndex/issues/2

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
