### ISSUE TITLE
Create tickets for each of the remaining scripts in plone_ecmascript

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#282]
this scripts need to be adapted to be mockup friendly and moved to another js package or resource directory

- [x] ~~cookie_functions~~
- [x] inline_validation - jcbrand
- [x] jquery.highlightsearchterms - giacomos
- [x] ~~js-standards~~
- [x] ~~kss-bbb~~
- [x] livesearch - ale-rt
- [x] login - jcbrand
- [x] mark_special_links - fulv
- [x] ~~popupforms~~ - jcbrand (*please see my comment below*)
- [x] table_sorter
- [x] unlockOnFormUnload

**Comment by gforcada** [comment]
Seems to me that all items on that list have been done? Can anyone confirm and close? :)
