### ISSUE TITLE
Profile with pic breaks on second save of user profile

### ISSUE THREAD

**Issue by pigeonflight** [plone/Products.CMFPlone#2845]
### What I did:

- Logged in as a user
- Under preferences I added a profile pic then saved
- I returned to my preferences and added a location (without changing the profile pic)

Here's a recorded session (I used the tryplone demo site):

![profile-pic-bug](https://user-images.githubusercontent.com/31827/56383357-408b8f00-61df-11e9-94ef-c81a1d3a7d2a.gif)

### What I expect to happen:
I expected that my profile would be updated with my location information.

### What actually happened:
I got the following:
```
We’re sorry, but there seems to be an error…
The error has been logged as entry number 1555611954.860.209339404861.

If you need to report this to the 
                    site administration, please include this entry number in your message.
```
Here's the traceback
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.users.browser.userdatapanel, line 94, in __call__
  Module z3c.form.form, line 233, in __call__
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 136, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module z3c.form.browser.text, line 36, in update
  Module z3c.form.browser.widget, line 171, in update
  Module Products.CMFPlone.patches.z3c_form, line 47, in _wrapped
  Module z3c.form.widget, line 88, in update
  Module plone.formwidget.namedfile.widget, line 273, in extract
  Module plone.namedfile.utils, line 42, in safe_basename
AttributeError: 'NoneType' object has no attribute 'rfind'
```
### What version of Plone/ Addons I am using:
I have been able to replicate this with the following versions:
Plone 5.2
Plone 5.1.5
Plone 5.1.4
Plone 5.1.2.1

(This bug does not seem to affect Plone 5.1.2 or less)

**Comment by pbauer** [comment]
@pigeonflight can you please check if this was fixed with https://github.com/plone/Products.CMFPlone/issues/2709? Seems like a duplicate.

**Comment by pigeonflight** [comment]
@pbauer yup that fixed the issue.
