### ISSUE TITLE
CSS issue with  new dropdown menu for 2nd level navigation in Plone 5.2

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2848]
Plone 5.2-latest

See screenshot 
![Screenshot_20190424_120108](https://user-images.githubusercontent.com/594239/56651251-f09e4380-6688-11e9-8fd7-994f57250991.png)

**Comment by pbauer** [comment]
I cannot reproduce the issue (FF and Chrome on Mac):
 
![Bildschirmfoto 2019-04-29 um 12 23 38](https://user-images.githubusercontent.com/453208/56890433-b8787580-6a79-11e9-9047-d826a405785d.png)
<img width="1441" alt="Bildschirmfoto 2019-04-29 um 12 23 56" src="https://user-images.githubusercontent.com/453208/56890435-b8787580-6a79-11e9-8862-7ecadf1a9f85.png">

**Comment by pbauer** [comment]
I was now able to recreate this and others issues with the dropdown-navigations-styles.

When I create a structure like this:

```
A Folder
├── Fooooooooooooooooooooooooooooooooooooooooooooooooooo
│   └── Foo foo foo foo foo bar bar bar
├── Foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo
│   └── Bar bar bar
├── Foo foo
├── Foo
    ├── Bar
    └── Baz
```

It will look like this:
<img width="1222" alt="broken nav" src="https://user-images.githubusercontent.com/453208/58543975-be8c7e00-8200-11e9-8058-76d59540676f.png">

Aparent issues:

1. No line-breaks in Long words
2. Some items cannot be selected (`Bar` is not clickable)
3. Subitems are hidden by nav-items with long words (You never see `Foo foo foo foo foo bar bar bar` which is in `Fooooooooooooooooooooooooooooooooooooooooooooooooooo`)
4. The Arrows that indicate that thjere are subitems are outside the blue area. They are aligned with the arrow in the the first item and thus invisible. You can see them when you change the background color of the page: 
   <img width="1126" alt="nav color" src="https://user-images.githubusercontent.com/453208/58544008-ca784000-8200-11e9-88a8-d5360ab36d6b.png">

5. The current item is not correctly selected (`Foo foo` and `Foo` are both highlighted)

The mobile navigation looks fine though!

Today I recreated that structure in http://demo-latest-py3.plone.org/en/a-folder (the site is reset each night so it might be gone by the time you look at it)

**Comment by pbauer** [comment]
https://github.com/plone/plonetheme.barceloneta/pull/182 fixes most issues mentioned above except for `5. The current item is not correctly selected (Foo foo and Foo are both highlighted)`. 

It now looks like this:
<img width="1305" alt="nav after1" src="https://user-images.githubusercontent.com/453208/58549542-0f55a400-820c-11e9-98b4-ed09639ab8fe.png">


But when I have the following simple structure (as in http://demo-latest-py3.plone.org/en/unsere-tollen-geschaftsprozesse):

```
Unsere tollen Geschäftsprozesse
├──  Arbeitsmedizinisch - Sicherheitstechnischer Dienst
└──  Prävention
```
It looks like this with and without the added `word-break: break-word;`:

<img width="1305" alt="navi after" src="https://user-images.githubusercontent.com/453208/58549481-e46b5000-820b-11e9-9abf-5f37c423c50c.png">

**Comment by agitator** [comment]
<img width="443" alt="Screenshot 2019-06-05 at 14 52 11" src="https://user-images.githubusercontent.com/365761/58957789-ac32b700-87a1-11e9-8abe-2ce6db72a758.png">

submenu length is fixed


the current item issue is not about a wrong marked current item but the inPath class... looking into it

**Comment by agitator** [comment]
https://github.com/plone/mockup/pull/906 is the fix for inPath selction
