### ISSUE TITLE
Mouse-Sensitivity when navigating in folder_contents is too high

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2851]
When trying to enter a folder in folder_contents it very frequently happens that the js thinks you instead want to drag&drop the folder to another position. You need to keep the mouse absolutely still to actually navigate into a folder.

Is it possible to decrease the sensitivity of the handler that listens to dragging? 

Editors encounter this issue in Plone 5.1 and 5.2.

**Comment by pnicolli** [comment]
Most of our customer experience the same issue, mainly (but not only) on Windows.
This issue has been there since Plone 5.0, now we found budget to dig deeper into this issue and are actively trying to solve it.
I'll keep in touch :)

**Comment by pnicolli** [comment]
We have a fix, PR coming soon to mockup and plone.staticresources :)
We are also willing to update mockup and CMFPlone for Plone 5.1.x.

**Comment by pnicolli** [comment]
Fixed with https://github.com/plone/mockup/pull/919 and compiled resources for Plone 5.2 in https://github.com/plone/plone.staticresources/pull/36.

5.1 backport coming soon™

**Comment by jensens** [comment]
staticresources need a recompile
