### ISSUE TITLE
Weird flicker noise with 2nd level dropdown navigation

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2853]
Plone 5.2rc2, Python 3.7

See video:

https://public.zopyx.com/flicker-navigation.mp4

**Comment by vincentfretin** [comment]
The video gives now a 404.
Which OS and which browser?
I have no issue on Chrome and Firefox Ubuntu 18.04 with 2nd level navigation.
I close for lack of informations. Please reopen with addition informations if you still reproduce the issue on Plone 5.2.2.
