### ISSUE TITLE
Should we pin plone.testing 5.0.0 and six 1.11.0 in http://dist.plone.org/release/4.3-latest/versions.cfg?

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#2867]
Since bobtemplates.plone adds this version of plone.testing in it's setup.py:

https://github.com/plone/bobtemplates.plone/commit/d57d364502cd9305eea5a1ba34f85bddca303de3

>Add minimum requirement for plone.testing to improve testing. http://do3.cc/blog/2016/04/92/better-test-isolation-in-plone/
> Add depedency on plone.testing 5.0.0. Despite the major version number, this change does not contain breaking changes.

For the six pin, it's because of a `jsonschema` dependency:

```
Getting required 'functools32'
  required by jsonschema 3.0.1.
We have the best distribution that satisfies 'functools32'.
Picked: functools32 = 3.2.3.post2
The constraint, 1.10.0, is not consistent with the requirement, 'six>=1.11.0'.
While:
  Updating instance.
Error: Bad constraint 1.10.0 six>=1.11.0
```
(Actually we can either pin `jsonschema` (2.6.0 works) or `six`)

Shouldn't we add this to 4.3 versions.cfg? So we can avoid dependency conflicts in new generated packages using bobtemplates.plone.

@esteele @mauritsvanrees @do3cc

**Comment by jensens** [comment]
AFAIK, since we have test isolation problems with Plone < 5.2, plone.testing 5.0 cant be used for running coredev tests.

**Comment by mauritsvanrees** [comment]
`plone.testing 5` is indeed impossible for Plone 4 in core. Even Plone 5.1 still uses an older version. (This surprised me, but apparently it is needed.)

And `six 1.11.0` was already pinned last year in [this coredev commit](https://github.com/plone/buildout.coredev/commit/37cc7c35d7), but that is not in an official 4.3 release yet. It will be included with the next one.
