### ISSUE TITLE
ZMI in RC3 and RC4-pending is broken when using VHM other than root

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#2868]
### What I did:
Access to ZMI in a site that is deployed in a path other than the root of a domain. When you access the ZMI, it's broken.

The reason is because the JS and CSS resources are hardcoded to / instead to take into account the VHM settings. Most probably a Zope problem, really hoping that this does not happen in Zope4.0 final...

### What I expect to happen:

The ZMI is not broken.

### What actually happened:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/486927/58006395-4d561800-7ae8-11e9-9339-5c3a898d77dd.png">

### What version of Plone/ Addons I am using:
Vainilla

**Comment by sneridagh** [comment]
@pbauer @mauritsvanrees @tisto Just wanted to make you notice about this, I guess it’s kind of big...

**Comment by pbauer** [comment]
I have not used VHM in ages. Can you provide a example-mapping that works in 5.1?

**Comment by sneridagh** [comment]
Sorry if I didn’t express myself correctly, VHM when using an standard Nginx configured as a reverse proxy, with a URL other than root (like example.com/api). I will provide an example when I can.

**Comment by sneridagh** [comment]
@pbauer I've setup this site to demo:
https://plonedemo.kitconcept.com/api/

go to ZMI: admin//admin

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/486927/59160412-f4b9df80-8ad5-11e9-9fbd-e44ba04107a5.png">

Using the usual Nginx config (works well with the Plone UI):

```
    location ~ /api($|/.*) {
      rewrite ^/api($|/.*) /VirtualHostBase/https/plonedemo.kitconcept.com:443/Plone/VirtualHostRoot/_vh_api$1 break;
      proxy_pass http://plonedemoapi;
    }
```

I will leave this online for some days.

As I said, it seems that someone was very optimistic about the JS/CSS resource location being in root always... The resources must match with the real deployment of the site, not server root.

Who took care of this?

/cc @mauritsvanrees @jensens

**Comment by sneridagh** [comment]
The problem can be seen also in: https://volto.kitconcept.com/api/manage

**Comment by pbauer** [comment]
Fixed with https://github.com/plone/buildout.coredev/pull/594
