### ISSUE TITLE
Collection date criteria with relative number of days not saved

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2879]
Plone 5.2RC3

Create a collection and select a date criteria with before/after relative date, enter # days, then save
and re-edit -> field with number of days is empty. The internal `query` also indicates that the value for days is not persisted properly

**Comment by zopyx** [comment]
The error is still open in 5.2.1

**Comment by zopyx** [comment]
The issue has some more dimensions:

1. a `query=[{'i': 'end', 'o': 'plone.app.querystring.operation.date.beforeRelativeDate', 'v': '222'}]` is being rendered with an empty input field for `v` - expected behavior: ìnput field should contain the value `222`
2. updating the value through the UI does not cause the value to be persisted.  Updating the value and other metadata value caused the value to be persisted. So there is something in Plone  which checking the object state (the metadata values) before and after. An object will only be saved with changed metadata..obviously this check does not include a check for the change value of the input field.

**Comment by petschki** [comment]
This is an issue in `pat-querystring` of mockup. See https://github.com/plone/mockup/pull/983 ... fix for `plone.staticresources` is on the way

**Comment by petschki** [comment]
https://github.com/plone/plone.staticresources/pull/78 was merged, which fixes this one. Can you confirm?

**Comment by zopyx** [comment]
No improvement with plone.staticresources@master. I see this error on the console:

```plone-editor-tools-compiled.min.js:1 Uncaught TypeError: Cannot read property 'widget' of undefined
    at createValue (plone-editor-tools-compiled.min.js:1)
    at createOperator (plone-editor-tools-compiled.min.js:1)
    at c.init (plone-editor-tools-compiled.min.js:1)
    at new c (plone-editor-tools-compiled.min.js:1)
    at e.createCriteria (plone-editor-tools-compiled.min.js:1)
    at Object.<anonymous> (plone-editor-tools-compiled.min.js:1)
    at Function.each (jquery.min.js:2)
    at e._init (plone-editor-tools-compiled.min.js:1)
    at Object.success (plone-editor-tools-compiled.min.js:1)
    at i (jquery.min.js:2)
```

**Comment by vincentfretin** [comment]
This is working properly on Plone 5.2.2rc1 for me.

**Comment by vincentfretin** [comment]
I'm closing it. Please reopen if you still see the issue on a newly created Plone.
