### ISSUE TITLE
Toolbar: unable to access all items of the display menu

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2880]
Major usability issues in Plone 5.2, see screenshot:

our list of available views is pretty long, a bunch of views are not selectable because there is no way to scroll down. In particular I can not reach the menu item for selecting a content item (last in  menu)

<img width="409" alt="Screenshot 2019-06-06 05 43 09" src="https://user-images.githubusercontent.com/594239/59005517-2e60c100-881e-11e9-88df-40ef3963f68b.png">

**Comment by vincentfretin** [comment]
Still an issue in Plone 5.2.2

**Comment by jensens** [comment]
The case in the screenshot work. If the menu is longer than the height of the visible area, it is still cut in 5.2.10, in 6.0.2 all works fine, menu is scrollable then. I do not think we need to keep this one open.
