### ISSUE TITLE
Highlighting of items in control panel visually broken

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2883]
Plone 5.2RC3

- the highlighted area does not cover all the text in some cases
- weird placement of the ">" character

See screenshots
<img width="196" alt="Screenshot 2019-06-10 07 09 48" src="https://user-images.githubusercontent.com/594239/59173800-e9ef6100-8b4e-11e9-9630-0770ad4d0f2b.png">

<img width="213" alt="Screenshot 2019-06-10 07 09 53" src="https://user-images.githubusercontent.com/594239/59173801-e9ef6100-8b4e-11e9-9aaa-9d5510bcff0f.png">

**Comment by vincentfretin** [comment]
I don't reproduce your first case.
For the second case there is this issue https://github.com/plone/plonetheme.barceloneta/issues/189
I'm closing this issue as duplicate.
