### ISSUE TITLE
Keywords broken

### ISSUE THREAD

**Issue by gogobd** [plone/Products.CMFPlone#2885]
### What I did:

1.) Created a vanilla Plone Site
2.) Added an Page, fill out Title and saved it
3.) Added one Keyword in Categorization and saved it
4.) Added another Keyword and try to save it

### What I expect to happen:

5.) The page should be saved with two keywords

### What actually happened:

6.) The field containing the Keywords shows a "wrong type" error indicator and the page won't save.

![Screen Shot 2019-06-13 at 09 25 37](https://user-images.githubusercontent.com/728976/59412409-aa7a7c00-8dbd-11e9-91c3-d7b85ebbd30e.png)

### What version of Plone/ Addons I am using:

https://github.com/collective/coredev52multipy as of June 12th/13th 2019
i.e. coredev master imho, and in 5.2 latest.

**Comment by jensens** [comment]
I tried this in 5.2-latest and 
- it works under Python 3.x
- **it is broken under Python 2.7**

**Comment by gogobd** [comment]
awesome!
