### ISSUE TITLE
Images in TinyMCE are lacking support for highpixeldensity scales

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#2889]
Images inserted with TinyMCE don't have image source set included when highpixeldensity_scales are activated.

### What I did:
Activated support for highpixeldensity_scales in controlpanel.
Inserted image into text area

### What I expect to happen:
An image with source set definition included in the image tag.

### What actually happened:
Default image tag is rendered.

**Comment by jensens** [comment]
fixed in plone 6
