### ISSUE TITLE
Pillow 6.0.0 dependency for 5.2RC3/final is very flaky

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2895]
The Pillow 6.0.0 has various issues. 

During the UGent site migration we encountered at least five different issues in Pillow that are already reported and fixes for the final Pillow 6.1.0 release (which is not released so far).

https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst

Also encountered two issues in the context of a Reportlab submodule running under 5.2RC3

It would be better to ship 5.2 with Pillow 5.4.1 update to Pillow 6.1.0 if available for the final release of 5.2

**Comment by pbauer** [comment]
Pillow 6.1.0 is out. I'll update the coredev pinn.

**Comment by zopyx** [comment]
Good news
