### ISSUE TITLE
Move permissions definitions from plone.app.controlpanel into Products.CMFPlone

### ISSUE THREAD

**Issue by khink** [plone/Products.CMFPlone#291]
For PLIP 10359 (https://dev.plone.org/ticket/10359) and cleanup (https://github.com/plone/Products.CMFPlone/issues/184), we want to move all controlpanel-related things to Products.CMFPlone.
Currenty the view permissions are defined in plone.app.controlpanel. These should be moved into Products.CMFPlone before we can get rid of p.a.controlpanel completely.

**Comment by gforcada** [comment]
Related to #358 ?

**Comment by khink** [comment]
I think so.

**Comment by jensens** [comment]
permissions are still in ``plone.app.controlpanel``!

``plone.app.controlpanel/plone/app/controlpanel/permissions.zcml`` needs move to ``Products.CMFPlone/Products/CMFPlone/controlpanel/permissions.zcml``

**Comment by Shriyanshagro** [comment]
@jensens can you be more specific to the requirement??
As I'm a newbie to Plone, so what all does it took to complete this task?

**Comment by jensens** [comment]
@Shriyanshagro thanks for offering your help. 

In past, we moved (or merged) the code we had in ``plone.app.controlpanel`` over to our main package Products.CMFPlone. ``plone.app.controlpanel`` is meant to only contain code for backward compatibility reasons.

1) Some bits were not moved, primary these are the permission definitions. 

It is just a zcml (XML) file, no python code involved. It needs to be removed in ``plone.app.controlpanel`` and added in ``Products.CMFPlone/Products/CMFPlone/controlpanel``. Also both directories ``configure.zcml`` includes must be changed accordingly. This should be all for the permissions if I have not overseen anything.

A second task in the same league is checking if the classes defined in ``interfaces.py`` are still used anywhere in Plone. 

If both is done, then Plone should be able to run without ``plone.app.controlpanel``.

**Comment by Shriyanshagro** [comment]
Then I'm on it. Let me put my hands into this, to migrate it.

**Comment by jensens** [comment]
Done
