### ISSUE TITLE
Webfont display problem with special characters aka german umlauts

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#2912]
Products.CMFPlone-5.2rc5-py3.7

Text with TinyMCE seems to have a problem
<img width="434" alt="Screenshot 2019-07-01 at 17 50 07" src="https://user-images.githubusercontent.com/365761/60450620-92fb1a00-9c2a-11e9-83c6-412b075229e5.png">

TinyMCE edit
<img width="602" alt="Screenshot 2019-07-01 at 17 55 17" src="https://user-images.githubusercontent.com/365761/60450716-b756f680-9c2a-11e9-8803-362d5bed736f.png">

TinyMCE source

<img width="645" alt="Screenshot 2019-07-01 at 17 55 30" src="https://user-images.githubusercontent.com/365761/60450719-baea7d80-9c2a-11e9-8ce1-0ee362a957e9.png">

After manual edit/override of those chars

<img width="608" alt="Screenshot 2019-07-01 at 18 06 40" src="https://user-images.githubusercontent.com/365761/60450826-fe44ec00-9c2a-11e9-88d5-b2d7174f811e.png">

Chars are displayed correctly
<img width="606" alt="Screenshot 2019-07-01 at 17 58 35" src="https://user-images.githubusercontent.com/365761/60450847-0c930800-9c2b-11e9-97c1-d19df0be56e0.png">

Default title and description are ok
<img width="450" alt="Screenshot 2019-07-01 at 17 49 41" src="https://user-images.githubusercontent.com/365761/60450886-22a0c880-9c2b-11e9-8dea-c31452511d72.png">

Terms from c.taxonomie have the same problem
<img width="406" alt="Screenshot 2019-07-01 at 18 08 40" src="https://user-images.githubusercontent.com/365761/60450987-4fed7680-9c2b-11e9-97a9-4bb2268f8d03.png">

Also downloads via relations 
<img width="241" alt="Screenshot 2019-07-01 at 18 09 47" src="https://user-images.githubusercontent.com/365761/60451050-76131680-9c2b-11e9-97fb-8687b3c962d8.png">

The webfont is included like this
```
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap" rel="stylesheet">

```

I found https://stackoverflow.com/questions/19704167/special-chars-issue-in-firefox-and-ie-using-webfonts-with-utf8 but cannot make much of it.

Anyone seen something like that?

Maybe @zopyx?

**Comment by zopyx** [comment]
No bells ringing

**Comment by agitator** [comment]
Stuff like that can happen for sure when copy and pasting snippets from other sources...
What I really wonder is why for example the taxonomy imported from a vdex/XML acts up like that or an uploaded file?

**Comment by iham** [comment]
i tried the file-part on plone5.2rc5-python2.7.
(@agitator sent me the exakt file)

the upload worked.
the display worked.
the download worked.
the binary worked.

to me this looks like a py3 problem.

**Comment by jensens** [comment]
Analyzing this in a hexeditor I can confirm it is not utf8:
![Screenshot at 2019-07-02 13-53-00](https://user-images.githubusercontent.com/157140/60510919-f50e5a80-9cd0-11e9-8dcd-4c64534b534b.png)

**Comment by jensens** [comment]
Unicode Character 'COMBINING DIAERESIS' (U+0308)
https://www.fileformat.info/info/unicode/char/0308/index.htm

**Comment by jensens** [comment]
The usual `ü` is a U+00FC
https://www.fileformat.info/info/unicode/char/00fc/index.htm
Which is also part of Roboto (as a Google webfont example) 
https://www.fileformat.info/info/unicode/font/roboto_light/grid.htm

So it seems the input itself was wrong and is no supported bu the used font. I can not believe that a conversion goes wrong here so far.

**Comment by agitator** [comment]
https://validator.w3.org says

Text run is not in Unicode Normalization Form C.
From line 142, column 261; to line 142, column 297
="level2">Bauleitung (ÖBA, Objektüberwachung)</span

**Comment by agitator** [comment]
probably something like https://stackoverflow.com/questions/16467479/normalizing-unicode#16467505 is needed... but where? on save? on output/display?

**Comment by jensens** [comment]
On save: IMO wrong. If its needed for correct output: as a transform-chain transform, at the end?

**Comment by agitator** [comment]
@ale-rt @loechel @MrTango @MatthewWilkes  opinions?

**Comment by agitator** [comment]
<img width="348" alt="Screenshot 2019-07-03 at 17 29 42" src="https://user-images.githubusercontent.com/365761/60604562-3d547800-9db8-11e9-80ec-2d9e86850908.png">

<img width="499" alt="Screenshot 2019-07-03 at 17 31 14" src="https://user-images.githubusercontent.com/365761/60604724-7ab90580-9db8-11e9-96dc-7db266704a8b.png">

**Comment by gforcada** [comment]
We hit that same problem at der Freitag, our font does not support the combining character.

I remember asking if there was a generic way to have an event handler/constraint/hook to be able to change a text field whenever it was added/modified, but there was none, so I roll out our own event handler on add/edit that goes through all the fields from the content type, and whichever is a text field it runs the normalization form C:

```
import unicodedata

unicodedata.normalize('NFC', text)
```

**Comment by agitator** [comment]
@gforcada did you encounter any problems or side effects with the normalization on save?

Tried a few webfonts and all show the same problem and also if it is a w3 recommendation, should this go into the core?

The more I think about it the more my opinion shifts to normalize on safe than doing it with an output filter or transform which could add render time.

**Comment by gforcada** [comment]
@agitator no, the only *problem* is that as you can not make a single generic adapter for all text field (at least I'm not aware of how to do it) you have to keep adding more and more event handlers ZCML registrations as you keep creating content types.

As usual, a good test suite that scans for that and breaks if not all content types are covered is enough as a safe guard.

Finally, after two search attempts I found my original question: https://stackoverflow.com/questions/20144712

**Comment by agitator** [comment]
https://www.w3.org/International/questions/qa-html-css-normalization

**Comment by petschki** [comment]
unicode diarrhea 😂

**Comment by gogobd** [comment]
This issue should be resolved (zope schema is normalizing unicode to NFC by default now)
