### ISSUE TITLE
PasswordResetView::getErrors function never called.

### ISSUE THREAD

**Issue by nazrulworld** [plone/Products.CMFPlone#2917]
### What I did:
I am trying to reset the password, using a normal Plone user and I made a PDB inside https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/login/password_reset.py#L159

URL: {site url}/passwordreset/e3127df738bc41e1976cc36cc9832132?userid=local_manager

### What I expect to happen:
I expected a call `RegistrationTool.testPasswordValidity(password, password2)
` as I have some business logic inside testPasswordValidity but I saw code never coming here

### What actually happened:
As I see inside ''getErrors''  method, there is a call to registration tool testPasswordValidity method but the ''getErrors'' never called.
### What version of Plone/ Addons I am using:
Plone 5.2.5rc

**Comment by benkummer** [comment]
Fix in password_reset which works for me 
https://github.com/plone/Products.CMFPlone/blob/bd98bd05a3eaf1c5b9579a7fb49da9c37f6721fd/Products/CMFPlone/browser/login/password_reset.py#L141

 ```
    errors = self.getErrors()
    if errors:
        self.status = errors
        return self.form()
```

**Comment by nazrulworld** [comment]
@benkummer did you make a pull request or just tried in your local.

**Comment by benkummer** [comment]
@nazrulworld I did try it local. Icannot do pull requests yet

**Comment by nazrulworld** [comment]
@benkummer thank you so much for your contribution.
