### ISSUE TITLE
Default effective date of front-page and Plone site

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2919]
The default effective date of a new Plone site and its front-page is epoch.

```
>>> app.Plone4.effective()
DateTime('1969/12/31 00:00:00 GMT+2')
>>> app.Plone4['front-page'].effective()
DateTime('1969/12/31 00:00:00 GMT+2')
```

Smart decision or nor - issue or not...
When you install collective.blog.portlets then the front-page (configured by default as blogish content-types) will appear under year 1969 inside the portlet....a bit weird...

Perhaps the effective date of a new Plone site and its default-page should set to the creation date and time

**Comment by jensens** [comment]
With Plone 6 Dexterity site root this should be fixed. I do not think we should change anything in Plone 5. Please reopen if you think I am wrong.
