### ISSUE TITLE
Remove Products.ResourceRegistries as Plone core dependency

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#292]
Products.ResourceRegistries should be removed in Plone5 as a core dependency. It's not used anymore and not even necessary for migration, because the new resource registry just reads the old `jsregistry.xml` and `cssregistry.xml` files and imports them into the new resource registry.

**Comment by vangheem** [comment]
No action on this in a while. Closing this until someone wants to work on it and writes a proper plip for it. Feel free to reopen.
