### ISSUE TITLE
"Settings"  for date/datetime fields inside schema editor is broken

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2930]
See https://github.com/collective/collective.easyform/issues/179 which also reproduces in Plone 5.2.0:

- create a new content type through the web
- add date or date time field
- click on "Settings" ->

```
2019-08-09 10:13:50,309 ERROR   [Zope.SiteErrorLog:251][waitress] 1565338430.3089490.9426224875882804 http://dev2.zopyx.de:20081/Plone4/dexterity-types/xxx/date/@@edit
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 136, in updateWidgets
  Module z3c.form.field, line 257, in update
  Module zope.component._api, line 97, in getMultiAdapter
zope.interface.interfaces.ComponentLookupError: ((<zope.schema._bootstrapfields.Field object at 0x7fe198df69b0>, <WSGIRequest, URL=http://dev2.zopyx.de:20081/Plone4/dexterity-types/xxx/date/@@edit>), <InterfaceClass z3c.form.interfaces.IFieldWidget>, '')

```

**Comment by batlock666** [comment]
The problem has something to do with the `min` and `max` fields from class `Orderable` (a superclass of both `Date` and `Datetime`). These fields have values of class `Field`, while they should be of class `Date`/`Datetime`.

I've tried the same with a field of class `Int`, which also has `Orderable` as superclass. In this case everything worked correctly.

**Comment by zopyx** [comment]
Marked as blocker because TTW editing of content types is a core functionality of Plone.

**Comment by ale-rt** [comment]
Looks like it is not an issue anymore.
Tested on Plone buildout.coredev 5.2

I added a content type:
![image](https://user-images.githubusercontent.com/1300763/86323229-c3f69c00-bc3c-11ea-8c37-3e453367f72c.png)
added a date field and clicked settings:
![image](https://user-images.githubusercontent.com/1300763/86323428-1932ad80-bc3d-11ea-9ddd-b5dbc4ae55f3.png)
I can set a min date and a max date.

Can you confirm it works for you as well, @zopyx?

**Comment by zopyx** [comment]
Seems to work in 5.2.2-pending
