### ISSUE TITLE
URL in Plone with problems?

### ISSUE THREAD

**Issue by claytonc** [plone/Products.CMFPlone#2944]
### What I did:

I created folders, subfolders and page in plone site:

- http://localhost:8080/plone/folder-1
  - http://localhost:8080/plone/folder-1/sub-folder-1
    - http://localhost:8080/plone/folder-1/sub-folder-1/page-1
- http://localhost:8080/plone/folder-2

### What I expect to happen:

When accessing as follows URLs always returns a page and not a 404, and when authenticated actions not show:

1. http://localhost:8080/plone/folder-1/sub-folder-1 - status 200 and show folder
2. http://localhost:8080/plone/folder-1/sub-folder-1/page-1 - status 200 and show page

3. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1 - status 404 and  not show page
4. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1/page-1 - status 404 and  not show page
5. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1/folder-2/page-1 - status 404 and  not show page

### What actually happened:

1. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1 - status 200 and show folder
2. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1/page-1 - status 200 and show page
3. http://localhost:8080/plone/folder-1/folder-2/sub-folder-1/folder-2/page-1 -status 200 and show page

Test in plone.org:

1. https://plone.org/news/2019/the-guardians-of-the-zope-and-plone-galaxy 
- https://plone.org/news/2019/news/the-guardians-of-the-zope-and-plone-galaxy

2. https://plone.org/foundation/contributors-agreement
- https://plone.org/foundation/news/contributors-agreement

3. https://plone.org/community/framework
- https://plone.org/community/foundation/framework
- https://plone.org/foundation/community/foundation/framework
- https://plone.org/foundation/community/foundation/news/framework

This behavior is normal or bug?

### What version of Plone/ Addons I am using:

Test in plone 4.3.x and 5.1.x and no addons extras

**Comment by erral** [comment]
This behaviour is normal dut to Zope's Acquisition mechanism, you can read more about Acquistion here: https://zope.readthedocs.io/en/latest/zopebook/Acquisition.html

You can check [collective.redirectacquired](https://github.com/collective/collective.redirectacquired) if you want to redirect to the proper folder when reaching that kind of URLs
