### ISSUE TITLE
"last modified" dates format: not the same in "View" and in "Contents" of a folder

### ISSUE THREAD

**Issue by dbitouze** [plone/Products.CMFPlone#2953]
### What I did:
I installed a fresh Plone 5.2 (python3) instance and started to create a new Plone site in French, with "last modified" dates displayed. Then I added content and looked at the content of a folder either from (one of) its view(s) or from its "Contents" (`/folder_contents`).

### What I expect to happen:
I expected the "last modified" dates format to be the same in the two cases, following the French rules (`dd/mm/yyyy hh:mm`).
### What actually happened:
The "last modified" dates format are:

- as expected in the view case (`dd/mm/yyyy hh:mm`),
- not as expected in the "Contents" case (`mm/dd/yyyy hh:mm AM/PM`),

hence not the same.

### What version of Plone/Addons I am using:

- Plone 5.2.0 (5207)
- CMF 2.4.0
- Zope 4.1.1
- Python 3.7.3 (default, Apr 4 2019, 08:55:10) [GCC 8.3.1 20190329]
- PIL 6.1.0 (Pillow)
- WSGI : On
- Serveur : waitress 1.3.0

**Comment by vincentfretin** [comment]
Can you please give us a screenshot?
I'm currently seeing "Par admin — Dernière modification 8 hours ago" in French (another issue)
![Capture d’écran de 2019-10-13 17-24-44](https://user-images.githubusercontent.com/112249/66717942-7bf9c580-edde-11e9-8428-4a542add9f2b.png)
![Capture d’écran de 2019-10-13 17-25-19](https://user-images.githubusercontent.com/112249/66717944-7f8d4c80-edde-11e9-9ab7-c7155910e457.png)

**Comment by dbitouze** [comment]
Cf.:

![image](https://user-images.githubusercontent.com/1032633/66718694-d860e300-ede6-11e9-80bb-f1033cd7a8aa.png)

versus:

![image](https://user-images.githubusercontent.com/1032633/66718709-0ba37200-ede7-11e9-8bed-6cad42c77f60.png)

(BTW, another issue in the translations "external", "internal", etc.)

**Comment by dbitouze** [comment]
Quite strange! Sometimes the "Contents" case is OK:


![image](https://user-images.githubusercontent.com/1032633/66721458-10c2ea00-ee04-11e9-941d-a43b18ab0304.png)

and sometimes not:

![image](https://user-images.githubusercontent.com/1032633/66721434-eec96780-ee03-11e9-95a4-b220c01ef53e.png)

AFAICS, it is OK if another view (other than the standard one) has been previously selected...

**Comment by vincentfretin** [comment]
For the date in the Last modified column, #2074 may be related.

**Comment by vincentfretin** [comment]
Ah this is actually a regression in Plone 5.2.0?
In the buildout.coredev 5.1 it actually works correctly.
![Capture d’écran de 2020-06-20 14-49-10](https://user-images.githubusercontent.com/112249/85202235-401be600-b305-11ea-885a-d36c4a5b99a1.png)

What changed?

**Comment by vincentfretin** [comment]
For the Last modified column, the regression is in plone-editor-tools bundle between mockup branch 2.7.x and master. (I tried to use mockup 2.7.x in Plone 5.2 and this fixed the issue)

For the "3 minutes ago" in toolbar and "by line", I don't know.

**Comment by dbitouze** [comment]
And what about" external", "internal", etc.?

**Comment by vincentfretin** [comment]
The review state not translated is still an issue. I made a long list of the issues here https://github.com/plone/Products.CMFPlone/issues/2188#issuecomment-646535054
See the list of known i18n issues here https://github.com/plone/Products.CMFPlone/issues/3123

**Comment by vincentfretin** [comment]
The "3 minutes ago" is using the pat-moment pattern from mockup, but switching mockup to 2.7.x doesn't resolve the issue, so the regression may be a change in an other package?

If someone want to dig in this regression, I switched mockup like this:
```
cd src/mockup
git checkout 2.7.x
make bootstrap
```
and put plone-editor-tools bundle in develop mode (see https://github.com/plone/mockup/pull/985)

To go back to master:
```
git checkout master
rm -rf node_modules
make bootstrap
```

**Comment by vincentfretin** [comment]
OMG no, this is not related to branch 2.7.x vs master at all. I'm on mockup master, if I put the plone-editor-tools js bundle in develop mode, the issue for the Last modified column is fixed. This is the same thing as #3124 . Is the bundle not up to date? How do we rebuild that for the next release?

**Comment by vincentfretin** [comment]
Compared to branch 2.7.x, mockup master now lazy load the moment locale, I put a console.log in moment pattern `mockup/patterns/moment/pattern.js`, I see it will do `require(['moment-url/fr']);`, but I still get the "3 minutes ago" in English, not in French.
@davilima6 you worked on this, do you know what's going on? Did it really work with non English locale at one point?

**Comment by vincentfretin** [comment]
The `require` is a requirejs thing. How and where it is supposed to load an additional javascript file? I see in `mockup/js/config.js` that moment-url is actually an alias to `node_modules/moment/locale`. I see in PR https://github.com/plone/plone.staticresources/pull/10 that the moment/locale folder was committed in plone/staticresources/static/components/moment/locale
@agitator can you help?

**Comment by vincentfretin** [comment]
Actually I can see in Chrome network tab that `http://0.0.0.0:8080/Plone/++plone++static/components/moment/locale/fr.js` is downloaded. But it's still not in French.

**Comment by vincentfretin** [comment]
@davilima6 This is an issue with requirejs and the require line it seems. If I put 'moment-url/fr' in the define, I see the French translation.

**Comment by vincentfretin** [comment]
@davilima6 I think the require is somewhat asynchrone and the moment date are rendered before the fr.js is fully loaded? When you first show folder contents, it downloads the fr.js but in the toolbar you see "20 hours ago" in English. Then if you click on folder contents to show 30 items per page, it will somewhat update the moment pattern in the toolbar and you can see in French "il y a 20 heures".

**Comment by davilima6** [comment]
Hi, @vincentfretin. Thanks for the investigation. I'll try to reproduce the issue and the path you took. Your last message might mean that we lack reloading the pattern after the require (possibly in a delayed manner). I think `pat-registry` has a scan function for that.

**Comment by vincentfretin** [comment]
Hi @davilima6 You seems to know better this stuff than me. I'll leave it to you. :pray: Thanks.

**Comment by vincentfretin** [comment]
@davilima6 I did the fix in https://github.com/plone/mockup/pull/987

**Comment by davilima6** [comment]
Looks good. Thanks!
