### ISSUE TITLE
Content Settings controlpanel saves changes without notice when changing content type selection

### ISSUE THREAD

**Issue by tmassman** [plone/Products.CMFPlone#2986]
### What I did:

- Go to @@content-controlpanel
- Select a content type from the `select` field
- Change some settings
- Select another content type without hitting the `Save` button

### What I expect to happen:

Settings for the first selected content type are not changed

### What actually happened:

Settings for the first content type are changed

### What version of Plone/ Addons I am using:

Plone 5.2.x, but applies to all 5.x versions, and 4.x as well.

**Comment by tmassman** [comment]
The bug was already fixed in 5.1.x, but the fix was not applied to the 5.2.x branch. The PR #2990  will take care of this.

**Comment by jensens** [comment]
master is missing, I forgot about Plone 6 ;)
