### ISSUE TITLE
Password Reset not validating password

### ISSUE THREAD

**Issue by ccedgordon** [plone/Products.CMFPlone#2987]
### What I expect to happen:
Password reset should not allow passwords that do not meet password validation requirements. No validation is occuring. 

### What actually happened:

After triggering the 'forgot password' email and following the link, I am able to reset my password to anything I want. For example, a password that does not meet the minimum length. I set my password to 'x'. 

### What version of Plone/ Addons I am using:

No addons, replicated in Plone 5.1.5 and Plone 5.2 

'Allow set own passwords' and 'email as login' both turned on. 
This only affects the password reset page that is emailed to users, not the password reset page once you are logged in. 

In Products.CMFPlone.browser.password_reset.py, in the function _reset_password, the function pw_tool.resetPassword(userid, randomstring, password) is called. But that function (in Products.CMFPlone.PasswordResetTool) has a note that reads " Note that this method will *not* check password validity: this must be done by the caller."

**Comment by agitator** [comment]
Just now I ran into the same problem... though I couldn't reproduce it within buildout.coredev 5.2 (didn't enable 'Allow set own passwords' and 'email as login') and had dx.membrane in suspicion which I'm using in that project.

**Comment by agitator** [comment]
@ale-rt @mauritsvanrees ping?

**Comment by agitator** [comment]
https://github.com/plone/Products.CMFPlone/pull/2982 should fix this

**Comment by agitator** [comment]
can confirm, works also for dx.membrane
