### ISSUE TITLE
Outdated Plone Site misses link to plone-upgrade

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2989]
I load a Plone 5.1.5 database under Plone 5.2.0. Usually, you would have a message on both the root Zope management page and at the top of the ZMI of the Plone Site, that the site is outdated, with a link to `@@plone-upgrade`. This is missing. Our patch probably no longer works on Zope 4.

When I manually visit `http://localhost:8080/Plone/@@plone-upgrade` I do see that I need to upgrade (from current active configuration 5115 to latest available configuration 5207).

**Comment by jensens** [comment]
Outdated?
If you think this is wrong please reopen the issue.
