### ISSUE TITLE
Standard folder listing with images needs extra padding

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3018]
See screenshot (Plone 5.2.1)

There is no visual padding and no visual separation between the thumbnails.
An image border or at least some extra margin-bottom would help .
![screenshot-dev2 zopyx de_20081-2020 01 20-10_08_24](https://user-images.githubusercontent.com/594239/72713258-09cb1680-3b6d-11ea-9d32-e699a4a6df0f.png)

**Comment by jensens** [comment]
From the screenshot I have no idea what you are talking about. After all in Plone 6 this was redesigned anyway. I close this one. If you think I am wrong, please reopen and provide more information.
