### ISSUE TITLE
plone.app.z3cform: a form-only macro?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#302]
*As I see that issues are not enabled on plone.app.z3cform...*

Right now, with plone.app.z3cform you can create manually your form template while reusing parts of the logic, so you get the best from both worlds, customization on the surroundings of the form and automatic form generation.

Unfortunately the only macros available are for:
- the whole form plus title and description: ``form``
- the whole form without title but with description: ``titlelessform``
- only the form fileds: ``fields``
- only the actions: ``actions``

So a new macro for the whole form (i.e. ``fields`` and ``actions`` and the ``<form>`` that wraps them) would be really convenient.

I can work on the pull request if others do find it as useful as I do.

**Comment by vangheem** [comment]
Any updates on this? I'd prefer to close old enhancement requests if no one is interested. Closing for now.
