### ISSUE TITLE
Plone 5.2 - Can't browse date indexes in portal_catalog

### ISSUE THREAD

**Issue by PatrickDowney** [plone/Products.CMFPlone#3020]
I have a Plone 5.2 site and through ZMI, I'm trying to view records of an index I had that was a DateIndex.  However, it was giving me an error that it couldn't parse the date.  I tried viewing other DateIndexes and was getting the same error.  I tried to make a new Plone Site without installing anything to see if there was an issue with one of the packages, but I was getting the same error.

### What I did:

In my buildout.cfg, I removed my packages I placed in the src directory from 'eggs' and 'develop'.  I deleted the existing data.fs files and then reran buildout.   I then started the instance and created a new Plone site.  Without installing anything or touching anything else, I went into 'portal_catalog' in the ZMI, clicked on 'Indexes', clicked on 'created' (an index whose type is 'DateIndex') and then clicked on Browse.

### What I expect to happen:
A list of records of the 'created' DateIndex.

### What actually happened:

I received a traceback that looks like it was trying to parse something but failed.

    Traceback (innermost last):
      Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
      Module ZPublisher.WSGIPublisher, line 337, in publish_module
      Module ZPublisher.WSGIPublisher, line 255, in publish
      Module ZPublisher.mapply, line 85, in mapply
      Module ZPublisher.WSGIPublisher, line 61, in call_object
      Module Shared.DC.Scripts.Bindings, line 335, in __call__
      Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
      Module App.special_dtml, line 214, in _exec
      Module DocumentTemplate._DocumentTemplate, line 145, in render_blocks
      Module DocumentTemplate._DocumentTemplate, line 246, in render_blocks_
      Module DocumentTemplate.DT_Let, line 85, in render
      Module DocumentTemplate._DocumentTemplate, line 145, in render_blocks
      Module DocumentTemplate._DocumentTemplate, line 246, in render_blocks_
      Module DocumentTemplate.DT_In, line 645, in renderwb
      Module DocumentTemplate._DocumentTemplate, line 145, in render_blocks
      Module DocumentTemplate._DocumentTemplate, line 228, in render_blocks_
      Module DocumentTemplate._DocumentTemplate, line 169, in render_blocks_
      Module DocumentTemplate.DT_Util, line 228, in eval
       - __traceback_info__: DateTime
      Module <string>, line 1, in <module>
      Module DateTime.DateTime, line 447, in __init__
    DateTime.interfaces.SyntaxError: Unable to parse (2020.0583650686976, 1.6681227598564874, 21.711805555503815, 17.08333333209157, 5, 0, 'UTC'), {}

Edit:  I think its the version of python I'm using.  I started a new buildout just using 2.7 and it worked.  When I pointed the unified installer to the default python 3 that came with the os (Xubuntu 18.04.3), I got the same error again.

### What version of Plone/ Addons I am using:

Edit:
Plone 5.2.1

python 3.6.9
OS being used: Xubuntu 18.04.3

**Comment by FarooqAlaulddin** [comment]
Any updates for this issue? python 3.8.12 + Plone5.2.8

**Comment by davisagli** [comment]
Not sure what's up here, but it looks strange that the year/month/day are floats rather than ints.

**Comment by frapell** [comment]
Yup, haven't been able to figure out where is that coming from...

**Comment by frapell** [comment]
@davisagli Indeed, that was it... replacing all of those with `//` does fix it

**Comment by jensens** [comment]
I close this here, upstream bug in ZCatalog.

**Comment by davisagli** [comment]
@frapell FYI, fixed and released in ZCatalog 7.0: https://github.com/zopefoundation/Products.ZCatalog/pull/145

**Comment by PatrickDowney** [comment]
Thanks for responses and fixing this.   Really appreciate it.
