### ISSUE TITLE
Integrate PloneHotfix20200121

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3021]
Main issue for tracking that the [January 2020 Hotfix](https://plone.org/security/hotfix/20200121) is applied everywhere.

We could copy this into separate issues per Plone version if we want. And/or create an issue per package that needs a fix. Let's see. I am happy for others to jump in.

## Privilege escalation when plone.restapi is installed

- https://plone.org/security/hotfix/20200121/privilege-escalation-when-plone-restapi-is-installed
- Plone 5.2, 6.0
- [x] Needs fix in `plone.restapi`. Fixed in 6.2.1.

## SQL injection in DTML or in connection objects

- https://plone.org/security/hotfix/20200121/sql-injection-in-dtml-or-in-connection-objects
- All Plone versions. All Zope versions.
- [x] Needs fix in `DocumentTemplate`, `Products.PythonScripts`,  `Products.ZSQLMethods` (for ` Shared.DC.ZRDB.Connection`) [Update: done, coredev PRs created. And `PythonScripts needed no fix.]
- [x] The hotfix may break when using Postgres (for example double quotes ending up twice in the database), so we might need a version 1.1 of the hotfix. The main fix is in DocumentTemplate, and that has a good version of the code.

## XSS in the title field on plone 5.0 and higher

- https://plone.org/security/hotfix/20200121/xss-in-the-title-field-on-plone-5-0-and-higher
- Plone 5 and 6
- Needs fix in `plone.app.content` and `plone.app.layout`
- [x] `plone.app.content` 3.5.x: https://github.com/plone/plone.app.content/pull/195
- [x] `plone.app.content` master: https://github.com/plone/plone.app.content/pull/193
- [x] `plone.app.layout` only master: https://github.com/plone/plone.app.layout/pull/232

## Privilege escalation for overwriting content

- https://plone.org/security/hotfix/20200121/privilege-escalation-for-overwriting-content
- All Plone versions
- Needs fix in `plone.app.contenttypes`
- [x] 1.1.x: https://github.com/plone/plone.app.contenttypes/pull/546
- [x] 1.4.x: https://github.com/plone/plone.app.contenttypes/pull/545
- [x] master: https://github.com/plone/plone.app.contenttypes/pull/543

## An open redirection on the login form and possibly other places

- https://plone.org/security/hotfix/20200121/an-open-redirection-on-the-login-form-and-possibly-other-places
- All Plone versions
- Needs fix in `Products.CMFPlone` (`isURLInPortal` function)
- [x] `Products.CMFPlone` 4.3. https://github.com/plone/Products.CMFPlone/pull/3024
- [x] `Products.CMFPlone` 5.1: https://github.com/plone/Products.CMFPlone/pull/3043
- [x] `Products.CMFPlone` 5.2: https://github.com/plone/Products.CMFPlone/pull/3044 
- [x] `Products.CMFPlone` 6.0: https://github.com/plone/Products.CMFPlone/pull/3045

## Password strength checks were not always checked

- https://plone.org/security/hotfix/20200121/password-strength-checks-were-not-always-checked
- All Plone versions. But it was already publicly reported in issue #2987 and on 5.2.1 it was already fixed in PR #2982. We need to check it though.
- Needs fix in `Products.CMFPlone`
- [x] `Products.CMFPlone` 4.3. https://github.com/plone/Products.CMFPlone/pull/3025
- [x] `Products.CMFPlone` 5.1: https://github.com/plone/Products.CMFPlone/pull/3043
- [x] `Products.CMFPlone` 5.2: https://github.com/plone/Products.CMFPlone/pull/3044 
- [x] `Products.CMFPlone` 6.0: https://github.com/plone/Products.CMFPlone/pull/3045

**Comment by tkimnguyen** [comment]
A note: I’ve included the hotfix in r2 of the 5.2.1 unified installer and could do the same for the other versions. What did we do for previous hotfixes?

**Comment by gotcha** [comment]
> But it was already publicly reported in issue #2987 and on 5.2.1 it was already fixed in PR #2982.
I do not understand what you mean hereabove. #2982 does not include any patch to `testPasswordValidity`.

**Comment by mauritsvanrees** [comment]
> > But it was already publicly reported in issue #2987 and on 5.2.1 it was already fixed in PR #2982.
> 
> @mauritsvanrees I do not understand what you mean hereabove. #2982 does not include any patch to `testPasswordValidity`.

That PR fixes the same problem in a different way. I think `testPasswordValidity` was easier to hotfix. At least we could fix it in one place for all Plone versions.
It might be that Plone 5.2 needs an extra fix that the original PR did not cover, and that is only covered by the hotfix.

**Comment by gotcha** [comment]
> That PR fixes the same problem in a different way. I think testPasswordValidity was easier to hotfix. At least we could fix it in one place for all Plone versions.
It might be that Plone 5.2 needs an extra fix that the original PR did not cover, and that is only covered by the hotfix.

I prefer your fix: as it is not restricted to the view, people relying on the API will get the fix as well.

**Comment by mauritsvanrees** [comment]
Yes, that would be better.

I wonder if the fix from #2982 currently in Plone 5.2.1 can and should be removed. Should be fine to keep it: the hotfix tests pass. But maybe in some cases the check is then done double. I haven't dived deeply into that.

**Comment by erral** [comment]
> A note: I’ve included the hotfix in r2 of the 5.2.1 unified installer and could do the same for the other versions. What did we do for previous hotfixes?

**Comment by mauritsvanrees** [comment]
All PRs done!

Now some releases are needed. Let me make a list of that as well, for good measure. Some have already been done.
We need CMFPlone releases as well, which take a bit longer.

- [x] plone.restapi: 6.2.1
- [x] DocumentTemplate 2.13.6
- [x] DocumentTemplate 3.2.2
- [ ] plone.app.content 3.5.x
- [ ] plone.app.content master
- [ ] plone.app.layout master
- [ ] plone.app.contenttypes 1.1.x
- [ ] plone.app.contenttypes 1.4.x
- [ ] plone.app.contenttypes master
- [ ] Products.CMFPlone 4.3.x
- [ ] Products.CMFPlone 5.1.x
- [ ] Products.CMFPlone 5.2.x
