### ISSUE TITLE
Style enhancements for toolbar

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#303]
Here are three small enhancements for the toolbar. I suck at less and do not know yet where the change should end up in. I you like these changes please link to the changeset here, so next time you'll get a pull-request.

No outline around links (remove the ugly dotted line when clicking):

    #edit-zone a {
    	outline: 0
    }

Less left-margin between icon and text in top expanded mode:

    #edit-zone.plone-toolbar-top.expanded  nav > ul a > span + span {
    	padding: 0 8px 0 0;
    }

Add a separator between tabs (also top expanded):

    #edit-zone.plone-toolbar-top.expanded  nav > ul > li {
    	border-right: 1px dotted #888;	
    }

**Comment by vangheem** [comment]
Is this still relevant? I know there have been some changes since this was reported to toolbar. Please close if this is no longer valid against master.

**Comment by vangheem** [comment]
Closing for now since no response. Please reopen if still relevant.

**Comment by pbauer** [comment]
Sorry, I missed the question. Yes it is stil relevant and I think the changes would improve usability.

**Comment by vangheem** [comment]
After the less file change is made, you then run: "./bin/plone-compile-resources --bundle=plone" to generate the built css(with a clean Plone instance).

**Comment by pbauer** [comment]
Thanks!
