### ISSUE TITLE
Make Barceloneta and Plone templates Bootstrap 4 compatible

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#3040]
part of PLIP: https://github.com/plone/Products.CMFPlone/issues/2967

# Barceloneta Theme
- [x] convert less to sass
- [x] update compile mechanism for sass
- [x] use standard Diazo replace/before/after rules to get content and portlet columns
- [x] define boostrap grid css classes in external xsl file which get's included in rule.xml

# Templates to update

- [ ] z3c/form/browser/submit_display.pt
- [x] z3c/form/browser/submit_input.pt
- [ ] ~~z3c/form/browser/button_input.pt ?~~
- [ ] most of the overrides from https://github.com/collective/plonetheme.tokyo/tree/master/src/plonetheme/tokyo/browser/overrides

List (work in progress) of Packages / Views / Templates to touch: https://docs.google.com/spreadsheets/d/15C0YOsW2cxafM1G8zyHHNsNSJF5hZto6jqpB7ymbE0U

## How we will update the templates

We will fix update the templates in all packages for Plone 6, because this will be breaking themes and maybe javascript. To make it possible to use it in Plone 5 already, we will provide overrides inside plonetheme.barceloneta via jbot. The overrides will be only applied for Plone < 6.
The overrides we will need at least for templates in CMFPlone like the controlpanels. Some packages might just get a majaor release and can be still used in Plone 5 but will not be used in Plone < 6 by default.

**Comment by agitator** [comment]
@MrTango could you compare with https://github.com/plone/plone.app.z3cform/tree/bootstrap4/plone/app/z3cform/templates and check what's still missing?
