### ISSUE TITLE
Groups with groups and users as members are not working

### ISSUE THREAD

**Issue by krissik** [plone/Products.CMFPlone#3048]
### What I did:

On demo.plone.org I created a group "testgroup" to which I have added "reviewer" group using `@@usergroup-groupmembership`. Now I want to add "editor-in-chief" user to that group and search for it. I select the checkbox and click "Add selected groups and users to this group"

### What I expect to happen:

That "editor-in-chief" is member of group "testgroup"

### What actually happened:
An error:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupmembership, line 77, in __call__
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupmembership, line 74, in update
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupmembership, line 87, in getMembers
TypeError: '<' not supported between instances of 'str' and 'bool'

```

If I check group memberschip of "editor-in-chief" it is added to test group. (@@usergroup-usermembership?userid=editorinchief Tab: Group Memberships) But if I check group members of "testgroup" "editor-in-chief" is not in this group.

### What version of Plone/ Addons I am using:
Plone 5.2.1 (5208)
CMF 2.4.2
Zope 4.1.3

**Comment by mauritsvanrees** [comment]
I can't reproduce this on Python 2.7, but I *can* on Python 3.7.
It goes wrong in [this line](https://github.com/plone/Products.CMFPlone/blob/5.2.1/Products/CMFPlone/controlpanel/browser/usergroups_groupmembership.py#L87-L88). We are sorting with a key that can return a string or a boolean. Apparently on Python 2 this works fine, but not on 3.

We can do the same for groups as is done a few lines later for users: if `x` (group or user) is None, use an empty string as value.
But really, we should make this a bit simpler, and avoid iterating over the list twice.
I will have a try.
