### ISSUE TITLE
Use Zope 5 in Plone 6

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3058]
## PLIP (Plone Improvement Proposal)

The development of Zope and its ecosystem is proceeding steadily.
Plone should keep the pace with it.

### Proposer: 

- Alessandro Pisa

### Seconder: 

- *Add yourself*

## Abstract

After the big effort of modernization done to deliver Plone 5.2, we now have the chance, with a limited effort, to keep the pace with the packages Plone is built on top.
Zope developers are demonstrating to be active by supporting in closing bugs and pushing hard to keep Zope up-to-date with the currently maintained Python versions.

## Motivation

We want Plone to be up-to-date and to support as well the latest Python versions.
We want to avoid to lag behind and to do an enormous migration effort like happened with the Plone 5.2 release.

## Assumptions

Using the latest Zope appears to most core developer obvious.

## Proposal & Implementation

Pull request https://github.com/plone/buildout.coredev/pull/680

This goes on pair with https://github.com/plone/Products.CMFPlone/issues/2812

## Deliverables

The jenkins jobs of buildout.coredev (6.0 branch) should be green for all the supported Python 3.x versions.

## Risks

Zope 5 has few breaking [changes](https://github.com/zopefoundation/Zope/blob/08fcf97e4a605a9b2f7fa80ae8aa17750c499f45/CHANGES.rst#backwards-incompatible-changes). 
The main point is to drop Python2.7, clean compatibility code (e.g. `six` and similar).

People which are still using ZServer and branches of it that support Python3, might be affected.

## Participants

- @jensens

**Comment by jensens** [comment]
The last two days @mauritsvanrees and I worked on it and now the 6.0 branch runs with the latest Zope 5 master. After release of Zope 5 final needs to be changed to use the release.
Lets keep the issue open until Zope 5 final is used.

**Comment by pbauer** [comment]
Great work! https://demo-latest-plone6.plone.org now uses it:
![zope5](https://user-images.githubusercontent.com/453208/94241837-7cb73900-ff15-11ea-81c3-419f039078b1.png)

**Comment by jensens** [comment]
done
