### ISSUE TITLE
ReplaceableWrapper does not work

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3059]
In Plone 5.2.1 or coredev as of today on Python 3.8 if for some reason the code runs into Plone Portal Root `index_html` method the WSGI publisher can not render the result and raises:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 84, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
TypeError: 'ReplaceableWrapper' object is not callable
```

This happens to me in a customized site where I had no view set on the root. For some reason its not a problem with Python 2.7 AFAICT.

**Comment by thet** [comment]
Closed by: https://github.com/plone/Products.CMFPlone/pull/3060
