### ISSUE TITLE
"Products.CMFPlone.browser.interfaces.IPlone" lacks definition for "patterns_settings"

### ISSUE THREAD

**Issue by d-maurer** [plone/Products.CMFPlone#3066]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)
BUG for Plone 5.2.1

This bug is currently hidden (for some unknown reason).
With https://github.com/zopefoundation/Zope/pull/807 it will let the "csrf.txt" test fail with the (understandable) exception `UnAuthorized: you are not allowed to access "pattern_settings"` for the expression `plone_view/patterns_settings` in `main_template`: the view `plone_view` allows interface `IPlone` and as this lacks a definition for `patterns_settings`, access is unauthorized.

**Comment by mauritsvanrees** [comment]
Directly fixed in the 5.2.x branch. I will do it on 6.0 too.
Thanks for the clear bug report!
