### ISSUE TITLE
Move plone.app.referenceablebehavior to plone.app.testing

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#308]
plone.app.referenceablebehavior imports: "from plone.app.dexterity.tests import layer as dexterity_layer":

https://github.com/plone/plone.app.referenceablebehavior/blob/master/plone/app/referenceablebehavior/tests/layer.py

This needs to be refactored to use the plone.app.dexterity testing test setup.

Afterwards we might be able to remove the PTC traces in p.a.dexterity:

https://github.com/plone/plone.app.dexterity/commit/a2809e18da90e507ac86808fb46e7d4cb66e768d

cc @tomgross @gforcada

**Comment by tomgross** [comment]
plone.app.referenceablebehavior is using plone.app.testing
