### ISSUE TITLE
Update markup of templates in Products.CMFPlone to Bootstrap 5

### ISSUE THREAD

**Issue by santonelli** [plone/Products.CMFPlone#3081]
Due to #2967 we have to update the markup of the templates in Products.CMFPlone.

- [ ] Products.CMFPlone.browser.templates.error_message.pt
- [ ] Products.CMFPlone.skins.plone_prefs.password_form.pt
- [ ] Products.CMFPlone.skins.plone_prefs.prefs_main_template.pt
- [ ] Products.CMFPlone.skins.plone_templates.recently_modified.pt
- [ ] Products.CMFPlone.skins.plone_templates.recently_published.pt
- [ ] Products.CMFPlone.skins.plone_templates.test_rendering.pt

Since we started our work on this before 5.2 come out, check if the template is still in use. Feel free to add missing templates here. See also #3061 for further details. Check overrides in [plonetheme.tokyo](https://github.com/collective/plonetheme.tokyo) for already existing updated templates.

**Comment by agitator** [comment]
todo: also convert skins templates to browser pages
