### ISSUE TITLE
Link integrity only works partially

### ISSUE THREAD

**Issue by iham** [plone/Products.CMFPlone#3095]
Link integrity is a bit to simple on parsing/remembering linked content

### What I did:

1. add a page; write some body text and add an image (via tiny mce upload); save. 
2. add a second page; copy the content (body text) from the page 1 **view**; save.
3. try to delete the linked image in page 1 and 2 - link integrity only warns about page 1; aboard.
4. edit page 1 and copy the content of tinymce; paste that to page 2 instead; save page 2 again
5. try to delete the linked image in page 1 and 2 - link integrity warns about both pages!

i am pretty sure it is about the transform. the **view** of page 1 shows no uids on linked images, so the link integrity parser on page 2 does not handle those transformed links as internal ones and doesn't add them to its catalog.

### What I expect to happen:
link integrity warns about internal images on every page it is linked to.

### What actually happened:
link integrity only warns about linked stuff with uids

### What version of Plone/ Addons I am using:
plone 5.2 (same happens in an old plone 3.6)

### Possible fix
add "internal links" recognition to the link integrity parser?

**Comment by iham** [comment]
as i can't tell if thats a regression (did that ever work in older plone versions), a bug (for users that is one) or a feature, please feel free to add correct labels if you know more about that topic.

**Comment by iham** [comment]
solutions:

1. turn off link transform for editors, so they don't c&p transformed links
2. add validation to tinymce to convert internal links to resolveuid stuff and linkintegrity gets those
3. let link-integrity parse internal links and store them as it does whith resolveuid stuff
4. teach users not to do things like c&p from other internal pages

other ideas/solutions?

**Comment by jensens** [comment]
this was fixed in Plone 6
