### ISSUE TITLE
Plone 5.1.x Enable image caption support

### ISSUE THREAD

**Issue by tuticapi** [plone/Products.CMFPlone#3098]
### What I did:
New plone installation with
Installer
https://plone.org/download/releases/5.1.6
http://dist.plone.org/release/5.1.6

### What I expect to happen:
In the editing section in TinyMCE when adding an image the dialog box must include the caption image field.

![image](https://user-images.githubusercontent.com/16021828/82612372-5577e600-9b88-11ea-8fd4-a860b6840049.png)

### What actually happened:
In the editing section in TinyMCE when you want to add an image, the dialog box does not include the caption image field.

![image](https://user-images.githubusercontent.com/16021828/82612350-4abd5100-9b88-11ea-89c6-9e29c996c0b0.png)

### What version of Plone/ Addons I am using:
-Visión Global de Versiones
-Plone 5.1.6 (5116)
-CMF 2.2.13
-Zope 2.13.29
-Python 2.7.17 (default, Nov 7 2019, 10:07:09) [GCC 7.4.0]
-PIL 5.2.0 (Pillow)

Ref:

https://github.com/plone/plone.outputfilters/issues/37
https://github.com/plone/plone.app.upgrade/issues/231
https://github.com/plone/mockup/issues/977

>I have implemented the solution that I use [here](https://github.com/plone/mockup/pull/911)
In a short time I will send the pull request.

**Comment by vincentfretin** [comment]
Image caption feature is available in Plone 5.2.2.
