### ISSUE TITLE
Saving portal_controlpanel/manage_editActionsForm results in insufficient privileges

### ISSUE THREAD

**Issue by mdvmh** [plone/Products.CMFPlone#3113]
### What I did:
Clicking on 'save' in plonesite/portal_controlpanel/manage_editActionsForm

### What I expect to happen:
Invoking plonesite/@@overview-controlpanel in browser results in displaying the configurations

### What actually happened:
Invoking plonesite/@@overview-controlpanel in browser results in plonesite/insufficient-privileges

### What version of Plone/ Addons I am using:
Plone 5.2.1 (5208)
CMF 2.4.2
Zope 4.1.3
Python 3.7.7 (default, Apr 23 2020, 15:15:03) [GCC 6.3.0 20170516]
PIL 6.2.2 (Pillow)
WSGI: On
Server: waitress 1.4.2

Plain Plone installations without addons is in use.

### Note
Seems to be similar to:
https://github.com/plone/Products.CMFPlone/issues/1376

**Comment by thet** [comment]
Cannot reproduce, at least as admin. A‌ site administrator does not have access to that form nor the "actions"‌ control panel in http://localhost:8080/Plone/@@actions-controlpanel
If a site admin should have access is another discussion.
Closing this issue.
