### ISSUE TITLE
Some translations don't get picked up in editor modals

### ISSUE THREAD

**Issue by djowett-ftw** [plone/Products.CMFPlone#3120]
### What I did:

Use demo.plone.org in German
Try to add a link or an image

### What I expect to happen:

Modals are **fully** translated in the selected language (German)

### What actually happened:

Some translations don't get picked up
<img width="1326" alt="Screenshot 2020-06-16 at 09 29 15" src="https://user-images.githubusercontent.com/54800639/84745907-885da000-afb5-11ea-9600-d39a56e9f77c.png">

<img width="1326" alt="Screenshot 2020-06-16 at 09 34 40" src="https://user-images.githubusercontent.com/54800639/84745928-8d225400-afb5-11ea-8736-30dc3717d3e3.png">

### What version of Plone/ Addons I am using:

5.2.1 on demo.plone.org (also the case in 5.1.6 where we are using it)

**Comment by vincentfretin** [comment]
I'm looking with current 5.2 branch (future 5.2.2)

For insert a link:
- for "External" tab, this seems fixed in branch 5.2
- in all tabs, "Target" field not translated
- in Anchor tab, "Select an anchor" not translated

For insert an image:
- in all tabs, "Show Image Caption from Image Description" and "Image Caption" not translated
- the second tab shows "[object Object]" in French.

In the richtext toolbar, the tooltip "Remove link(s)" is no translated.

**Comment by vincentfretin** [comment]
![tab_object_Object](https://user-images.githubusercontent.com/112249/85115703-62860480-b21c-11ea-8828-5f1a06493ec2.png)

**Comment by vincentfretin** [comment]
Is there an issue with "Format" menu in the toolbar too? In French it's the same "Format". In German shouldn't it be "Formate"?

**Comment by vincentfretin** [comment]
@djowett-ftw You added the messages "Select an anchor" and "Target" in
https://github.com/collective/plone.app.locales/commit/c860a23a5005b05f1aafed92c7b3e1fb17e74381#commitcomment-40030331
How did you add them? Manually?
This is properly translated for example in French in widgets.po but it doesn't translate in the interface.
I can see those two messages in
https://github.com/plone/mockup/blob/db7843e7f1cb418198e098d66e5bddcd42bca036/mockup/patterns/tinymce/templates/link.xml#L61
and
https://github.com/plone/mockup/blob/db7843e7f1cb418198e098d66e5bddcd42bca036/mockup/patterns/tinymce/templates/link.xml#L74
but I don't know if it's properly internationalized there. What template language is this?

**Comment by vincentfretin** [comment]
Yeah I don't think this is correctly internationalized, I think it should be variables there and you need to have the variable in the object https://github.com/plone/mockup/blob/3e64876363286d9f1dd8d7a97a18ed013479bbe3/mockup/patterns/tinymce/js/links.js#L463 returned by `generateModalHtml`
I see an example with captionFromDescription 
https://github.com/plone/mockup/commit/3e64876363286d9f1dd8d7a97a18ed013479bbe3#diff-ff3812f0a02826b2ef1ffcd5ccc5d579R154

**Comment by vincentfretin** [comment]
I resynced widgets.pot and kept manually your two messages for now. This added two messages related to image caption, so if you translate them, this should fixes the translation in the UI for those.
```
#: ./patterns/tinymce/pattern.js
msgid "Show Image Caption from Image Description"
msgstr ""

#: ./patterns/tinymce/pattern.js
msgid "Image Caption"
msgstr ""
```

**Comment by djowett-ftw** [comment]
@vincentfretin I did the internationalization work in https://github.com/plone/mockup/pull/930/files#diff-ae0bd47fbe86e225ca9bc31a278348eeL66.  It was a backport to begin with at least, but maybe it ended up with fixes that aren't in Plone 5.2 (e.g. making "Target" translatable and reverting "Remove Link(s)" to "Remove Link" - as there are no translations for the former.

**Comment by vincentfretin** [comment]
Ah! For Plone 5.1.x, we use mockup branch 2.7.x and for Plone 5.2.x we use mockup master.
So there is some of your changes that are only on branch 2.7.x apparently. Can you create a new PR against master to have your changes there? Maybe its as simple as cherry-picking your commit, maybe not.

**Comment by vincentfretin** [comment]
For the "object Object:" tab, it should be "Upload". This is working properly on buildout.coredev 5.1 / mockup 2.7.0. The regression is in mockup master.

**Comment by vincentfretin** [comment]
I did a fix for the Upload tab in TinyMCE Image showing [object Object]
https://github.com/plone/mockup/pull/986

**Comment by vincentfretin** [comment]
I updated my comment https://github.com/plone/Products.CMFPlone/issues/3120#issuecomment-646504435 to create a todo list of the remaining points.

**Comment by djowett-ftw** [comment]
Hi @vincentfretin, sorry I've not been granted time to work on this - I think I burned too much time on the original 5.1 patch (with the confusions you encountered) to get favour for any more :-(

**Comment by vincentfretin** [comment]
I fixed the remaining issues in https://github.com/plone/mockup/pull/986/commits/ad2773a4dd810b673cdf285af798b7f1e7817da1
it was just a matter of cherry-picking your commit and fix conflicts.
