### ISSUE TITLE
"Error" not internationalized in Document add form

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#3126]
### What I did:

With Plone in non-English language, create a Document, leave the required Title field empty, click on Save

### What I expect to happen:
The error message perfectly localized:
Erreur Il y a des erreurs.
![Capture d’écran de 2020-06-28 09-55-21](https://user-images.githubusercontent.com/112249/85941881-03b04180-b926-11ea-89cd-d994a49dad68.png)

### What actually happened:
Error Il y a des erreurs.

### What version of Plone/ Addons I am using:
Plone 5.2.2rc1

**Comment by vincentfretin** [comment]
Somebody know how this error message is rendered? I have no clue where to look.

We have the Info, Error and Warning in the po file.

**Comment by vincentfretin** [comment]
This error message is not rendered by `plone.app.layout/plone/app/layout/viewlets/globalstatusmessage.pt`
Probably rendered in javascript? Where? How?

**Comment by vincentfretin** [comment]
No it's not rendered in javascript, I see the full html structure in the html response when I save.

**Comment by vincentfretin** [comment]
I found it in `plone.app.z3cform/plone/app/z3cform/templates/macros.pt`
If a replace
```
<dt i18n:translate="">Error</dt>
```
by
```
<dt i18n:translate="" i18n:domain="plone">Error</dt>
```
this fixes it.
But it's weird because we have `i18n:domain="plone"` in the root tag, but it doesn't same to care... Chameleon issue?

**Comment by mauritsvanrees** [comment]
Maybe the root domain is not picked up because this is in a macro.

**Comment by vincentfretin** [comment]
Yes you're probably right. There may be another domain defined in the caller. I didn't investigated further.
