### ISSUE TITLE
Expose the human_readable_size helper in the @@plone view

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3146]
The [@@plone view](https://github.com/plone/Products.CMFPlone/blob/009f785e450430ee7b143624480aef9268491c0b/Products/CMFPlone/browser/ploneview.py#L19) has helper methods that can be used in templates.
It would be handy to add the [Products.CMFPlone.utils.human_readable_size](https://github.com/plone/Products.CMFPlone/blob/009f785e450430ee7b143624480aef9268491c0b/Products/CMFPlone/utils.py#L855-L876) function as a method of that view.

**Comment by ale-rt** [comment]
I do not think this addition should be a PLIP, what do you think?
CC @plone/framework-team

**Comment by rodfersou** [comment]
it is a [well tested method](https://github.com/plone/Products.CMFPlone/blob/009f785e450430ee7b143624480aef9268491c0b/Products/CMFPlone/tests/test_utils.py#L149-L190) and [@@plone view](https://github.com/plone/Products.CMFPlone/blob/009f785e450430ee7b143624480aef9268491c0b/Products/CMFPlone/browser/ploneview.py#L19) placement looks handy for templates.

+1 on the addition, not so complex use case to need a PLIP also in my opinion.

**Comment by vincentfretin** [comment]
FYI plone.app.content already use it in a template like this https://github.com/plone/plone.app.content/blob/61c3b9918d79451aeceed63969cde930c70e2cef/plone/app/content/browser/templates/content_status_history.pt#L126 and 
https://github.com/plone/plone.app.content/blob/61c3b9918d79451aeceed63969cde930c70e2cef/plone/app/content/browser/content_status_history.py#L157-L158
