### ISSUE TITLE
Add Bootstrap Icons

### ISSUE THREAD

**Issue by santonelli** [plone/Products.CMFPlone#3162]
# Abstract

This issue belongs to #2967 (Change Templates to Bootstrap 4). 

Since we have to touch a lot of icons anyway, we decided to use [Bootstrap Icons](https://icons.getbootstrap.com/) in the upcoming theme. Since the current icon handling is complex and icons are difficult to customize we come up with this proposal.

## TL;DR

Icons are referenced in Plone only by its semantic name. A resolver then builds an URL or tag for consumption in templates or icon expressions. It looks up the name in the Plone registry, where an resource URL is stored for each name. 

The bootstrap icon set is used by default. Other icon sets are provided as add-ons. Those or customization in projects are done by remapping the names to other resources. 

Inline SVG is the preferred icon format, for legacy PNG is possible too. Inlining SVG at all places is not scope of this proposal.

# Motivation

A full set of useful, clean and modern icons should be available in Plone by default. 

Icon names should reflect the semantics for what they are used, not what they show.

The current way to register icons is not simple. Definitions of icons are in code, LESS/CSS and configuration (icon expression). In future there should be one place to register icons (registry) and one way to use them.

# Assumptions

- Plone 6
- Bootstrap 4 based Theme

# Proposal & Implementation

## Semantic Icons

Icons should be provided by a name to be resolved to the actual icon. An icon should be accessed by name only, independent of the actual icon-set used. Thus it will be way easier to customize an icon theme or provide a new one.

Icons names are semantic, so an icon may be named: i.e. `plone-copy`, `plone-paste`, `plone-contenttype-image`,  and a resolver then delivers the configured icon. Icon mapping happens in the registry. The same icon will be registered under a more generic name, like `generic-image`.

## Icon Registry

Wherever icons are used they are referenced by semantic name. The name is then resolved either to the resource URL or the HTML-tag.

We use the `plone.registry` for resolving. This works similar as already used in other places. Using a prefix for each icons `plone-ICONNAME`.  The value is the resource URL.

Thus any icon can be customized by changing its Plone registry record: only the resource URL of the name need to be updated.

## Default Full Icon Set

By default we provide the [Bootstrap Icons](https://icons.getbootstrap.com/). The full set is registered using their bootstrap name. Those names usages is disallowed in Plone Core. They are meant to be used in customizations only.

All icons used in Plone are additional registered with a semantic name prefixed by `plone-`. `plone-` prefixed names must be used in Plone core. The semantic name should be a in weight between generic and special. The default icon set and its registration goes into ``plone.staticresources``

Optional icons (icons and their registration) go to independent PyPI packages like `collective.icons.PACKACKENAME`. The icons in there are registered with their name in the given icon set. the `plone-` names are overridden in the package, so after installation all icons are from the package.

Optional icons (icons and their registration) go to independent packages collective.icons.xxx

If an Plone add-on package (like `collective.easyform`) introduces own icons (like an `form` icon). it must get there an own semantic name like `easyform-form`. It should map this to am existing bootstrap icon from Plone or provide an own svg icon.

## Icon registration
in plone.staticresources a file `profiles/default/registry/icons.xml` contains records like so:
```
  ...
  <records interface="plone.staticresources.interfaces.IIcon"
           prefix="plone.staticresources.icon.plone-copy">
    <value key="resource">++plone++static/components/bootstrap-icons/icons/clipboard.svg</value>
  </records>
  ...
  <records interface="plone.staticresources.interfaces.IIcon"
           prefix="plone.staticresources.icon.clipboard">
    <value key="resource">++plone++static/components/bootstrap-icons/icons/clipboard.svg</value>
  </records>
  ...
```

## Icon usage

We can identify two different type of icon usage, as: 

1. icon expression returning a URL to the icon,
2. html snippet.

For both we need a central utility to lookup the URL or the snippet.

For SVG we want icons to be inline, not as `<img .. />` tag - this way the icons can be styled by CSS as SVG is just markup in DOM. For icon expressions this is not easily possible without changing the current logic, which will breaks add-ons. Something we want to avoid. However, inlining may be done by a transform for those cases. 

Given a HTML snippet is fetched, inlining SVG is simple.

Inlining via transform s out of scope of this proposal, but it should be easy to provide a transform later after this proposal was implemented.

## Introducing the Icon Resolver

We need a central utility for icon lookup. In Plone usually traversers or views are used, so we plan to do.

- The utility is a helper to resolve Icon by given name,
- No resolver chains are expected (redirect to resolve in chain).

The resolver provides two kinds of results: URL or HTML-tag-snippet (SVG/IMG).

This may work like so:

- resolve an URL: `++resolveiconurl++plone-contenttype-image` OR `@@resolveiconurl/plone-contenttype-image
- resolve TAG:   `++resolveicontag++plone-copy` OR `@@resolveicontag/plone-copy`

For tags parameters are translated to XML attributes. I.e. `++resolveicontag++plone.copy?class=fancycolor&height=100px&widths=120px` results in a tag i.e. `<svg class="fancycolor" height="100px" width="120px" ...>...</svg>" (same for `img`). Arbitary attributes can be applied. Note that existing attributes are replaced. If no parameters are given an SVG is returned as-is.

Security: all parameters passed must be checked for any CSRF attack vectors. 

Code should go into in `Products/CMFPlone/browser/iconresolver.py`.

## Control Panel

A control panel to import/export the registry XML and to edit the icons would be nice but not mandatory as the first step. So, import/export works using the registry control panel already.

Code should go into in `Products/CMFPlone/controlpanel`.

# Questions and Hints

Add hints and caveats here for discussion.

## Default Icon Story

- Bootstrap Icons are available as SVG (at the time of writing this BI Alpha 5 is out)
- People may expect icon fonts like Font Awesome available by class (<i class="fa fa-home"></i>) - but those are available as SVG as well.
- We should generate CSS/SASS to make SVGs available in classes as mentioned above
- Its not possible to style icons implemented as image tag, background image, etc. (as mentioned above)

**Comment by vincentfretin** [comment]
Please note that bootstrap-icons is already in plone.staticresources for Plone 5.2.2, @agitator added it in https://github.com/plone/plone.staticresources/commit/fe0ccda740959f5904ce8fba12773775d8ed53cb
and https://github.com/plone/plone.staticresources/commit/9c230465825f3b6fc788ca0158aeed7877f56672

**Comment by agitator** [comment]
@vincentfretin added it for that reason ;-)

**Comment by jensens** [comment]
Just a hint for writing a traverser, since this is poorly documented:

They follow the schema `++ADAPTERNAME++SOMESTRING/SUBPATH`.

The multi-adapter on context and request  has to implement `from zope.traversing.interfaces import ITraversable`.
It has to be registered with `name="ADAPTERNAME"` in zcml.

```
<adapter
      name="ADAPTERNAME"
      factory=".traverser.MyTraverser"
      />
```

Then some basic code skeleton looks like so:

```
@implementer(ITraversable)
@adapter(ISiteRoot, IMyLayer)
class MyTraverser(object):

    def __init__(self, context, request):
        self.context = context
        self.request = request

    def traverse(self, name, ignored):
        # do something with name which is SOMESTRING and look up whatever, return as needed
        # if nothing matches: error
        raise LocationError(self.context, name) 
```

**Comment by santonelli** [comment]
Update Bootstrap Icons to 1.0.0 and registration is done in https://github.com/plone/plone.staticresources/pull/101. There is also a script to generate bootstrap_icons.xml in profile/default/registry/ based on the files listed in the components folder.

**Comment by santonelli** [comment]
This is done with [c8e220f7](https://github.com/plone/plone.staticresources/commit/c8e220f78597f88a318bf8717ca0f28c8c8ac3c3). Current version is 1.3.0.
