### ISSUE TITLE
Undo deprecation warning for len(batch)

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3176]
In Plone 5.2 you get lots of deprecation warnings like this, in real-world use, and for easy of reproduction also when running for example this test (edited to filter out other warnings):

```
$ bin/test -s Products.CMFPlone -t pwreset_browser.rst
...
  Running:
    1/1 (100.0%)/Users/maurits/community/plone-coredev/py3/var/cache/f8b4063628323927100f9f247fe9c029.py:460: DeprecationWarning: Using len() is deprecated. Use the `length` attribute for the size of the current page, which is what we return now. Use the `sequence_length` attribute for the size of the entire sequence. 
  if __condition:
/Users/maurits/community/plone-coredev/py3/src/Zope/src/Products/PageTemplates/engine.py:74: DeprecationWarning: Using len() is deprecated. Use the `length` attribute for the size of the current page, which is what we return now. Use the `sequence_length` attribute for the size of the entire sequence. 
  iterable = list(iterable) if iterable is not None else ()
/Users/maurits/community/plone-coredev/py3/var/cache/0a229eac7e57a317bdd047ef739d4daf.py:137: DeprecationWarning: Using len() is deprecated. Use the `length` attribute for the size of the current page, which is what we return now. Use the `sequence_length` attribute for the size of the entire sequence. 
  if __condition:
...
/Users/maurits/community/plone-coredev/py3/src/Zope/src/Products/PageTemplates/Expressions.py:253: DeprecationWarning: Using len() is deprecated. Use the `length` attribute for the size of the current page, which is what we return now. Use the `sequence_length` attribute for the size of the entire sequence. 
  return bool(value)
/Users/maurits/shared-eggs/cp37m/zope.deprecation-4.4.0-py3.7.egg/zope/deprecation/deprecation.py:88: DeprecationWarning: isDefaultPage is deprecated. Import from Products.CMFPlone.defaultpage instead
  name)
/Users/maurits/community/plone-coredev/py3/var/cache/16a60114d1d42d8280752740f6a1c9e7.py:1871: DeprecationWarning: Using len() is deprecated. Use the `length` attribute for the size of the current page, which is what we return now. Use the `sequence_length` attribute for the size of the entire sequence. 
  if __condition:
```

Those are actually two different warnings. The second one is due to a missing `__bool__` and will be fixed with my PR #3175. The first one is from code in `Products.PageTemplates` that handle [iteration over a repeat](https://github.com/zopefoundation/Zope/blob/4.5.1/src/Products/PageTemplates/engine.py#L78-L80). If you have a batch and in a template you do `tal:repeat="item batch"`, then this code calls `len(batch)` to get the length of repeat. Actually, `list(batch)` already does this, when I look at the traceback.

The call to `len(batch)` is [deprecated in `CMFPlone`](https://github.com/plone/Products.CMFPlone/blob/5.2.2/Products/CMFPlone/PloneBatch.py#L22-L28). This was first done in 2011, for Plone 4.2, in commit 84bdce6682fe408a8c3e41a826e0d44337f4ce6e. It advocated using the `pagesize` attribute at first. In 2015, for Plone 5.0, in commit a66ed5462e701fe61726db6566d30afefd4326ea I changed this to recommend `length` or `sequence_length`, depending on what you wanted.

But as you can see, `Products.PageTemplates` happily calls `len(batch)`, and this happens everytime someone uses a batch in a template.  This makes the deprecation useless by now, I think: people cannot avoid this warning.

An option could be to change this in `Products.PageTemplates` (and possibly `chameleon` as well, but I don't want to think about that just now), something like:

```
if hasattr(iterable, "length"):
    length = iterable.length
    if callable(length):
        length = length()
else:
    length = len(iterable)
```

But I don't think it makes sense to have special code like this for `PloneBatch` in `Products.PageTemplates`.

So a proposal: let's undo this deprecation. In other words: remove [these lines](https://github.com/plone/Products.CMFPlone/blob/5.2.2/Products/CMFPlone/PloneBatch.py#L24-L28). (But keep them as a comment probably.) This would be for Plone 5.2.3.

@plone/framework-team Thoughts?

**Comment by ale-rt** [comment]
I agree with undoing the deprecation. It makes sense that the length of the batch is the number of batched element.
