### ISSUE TITLE
Windows: 5.2.2 Release broken, requirements.cfg does not reflect buildout.coredev

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3180]
https://dist.plone.org/release/5.2.2/requirements.txt is different from https://github.com/plone/buildout.coredev/blob/5.2/requirements.txt and so the latest fixes for Windows installation are not in the release!

**Comment by jensens** [comment]
cc @plone/release-team

**Comment by mauritsvanrees** [comment]
It is not in the coredev tag I made for 5.2.2:
https://github.com/plone/buildout.coredev/blob/5.2.2/requirements.txt

But you *did* make the changes before I created this tag. I didn't think to copy the requirements to the tag. Oops! Sorry.

Let me keep the tag the same, but I will copy the file to dist.plone.org.
Done.

But it is cached a while. With an extra parameter you can see it though:
https://dist.plone.org/release/5.2.2/requirements.txt?x=1

**Comment by jensens** [comment]
thx!
