### ISSUE TITLE
Third level navigation hover issue

### ISSUE THREAD

**Issue by cdw9** [plone/Products.CMFPlone#3181]
Seen on Plone 5.2.1 and 5.2.2, in Firefox

Steps to reproduce:
* Add a folder to the root of the site ('Demo' in image below)
* Add another folder (A Folder) inside the first, add a few items into it
* In the global navigation, hover over 'A Folder', so the next level of items flies out
* Move your cursor down beneath the menu, the flyout slides back, but goes under your cursor, causing it to fly back out

![menu](https://user-images.githubusercontent.com/447195/93800235-eb3e8300-fc05-11ea-8b1b-a39280ac9517.gif)

**Comment by jensens** [comment]
just tried in latest 5.2 demo and all fine now.
