### ISSUE TITLE
folder_contents view in Plone 5.0a3 does not play nice with browser forward back buttons

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#319]
- Create a Plone site and navigate to the folder_contens view
- click on a subfolder - the URL remains unchanged
- now click on the browser back button and you will land on the front-page and not the folder_contents
  of the Plone root

-> major usability fail

Not if if this is possible but the URL of the folder_contents view must change when you click through
the folder structure. Especially the toolbar must respect the URL of the current folder context.

**Comment by vangheem** [comment]
The history is implemented in folder contents here: https://github.com/plone/Products.CMFPlone/commit/e5909c2be0848f3fb7b4efa5a1287a8e83bb15e0

Still need a solution to reload the menu on folder change.
