### ISSUE TITLE
Usability @@resourceregistry-controlpanel in Plone 5.0

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#320]
The current implementation of @@resourceregistry-controlpanel is pretty unusable.

Click on a resource entry item at the bottom of the screen and nothing happens _visually_ 
unless you scroll back to the top.

At least click on a resource should scroll back to the top of the page.
There is of course a filter to search for a resource but it does not resolve the issues with the very long list of resources (which is very long by default).  At least a scrollbar for the  outer DIV with some reasonable max-height would help here a lot.

**Comment by vangheem** [comment]
Your suggestions are now implemented in mockup core.
