### ISSUE TITLE
PLIP: Remove plone.app.upgrade steps and code before "to521"

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3202]
## Abstract

In `plone.app.upgrade` master targeting Plone 6.0 remove all upgrade steps below Plone 5.2.0 

## Motivation

1. One must upgrade to 5.2.x before going further to 6.0 (Python 3 migration step)
2. `plone.app.upgrade` code gets complex and starts producing side effects like https://github.com/plone/plone.restapi/issues/1007
3. it reduces maintenance work and test complexity

## Proposal & Implementation

Remove all upgrade steps before (but not including) profile `to521`, including bbb-mocks and tests.

## Deliverables

`plone.app.upgrade` needs a branch for 5.x, master targets `6.0`

## Risks

Add-on packages depending on mocks in `plone.app.upgrade` may break.

## Participants

Jens Klein

**Comment by ale-rt** [comment]
I think in the past we already removed old upgrades, so I am not even sure this should be a PLIP :)
Anyway I am ok with that and I will add this to the agenda for the next meeting.

There might be some potential issues if we remove some code that provides aliases for objects stored in the ZODB.

**Comment by jensens** [comment]
>  think in the past we already removed old upgrades, so I am not even sure this should be a PLIP :)

Yes, I was not sure if it is needed as well - but for visibility a PLIP does not hurt.

> There might be some potential issues if we remove some code that provides aliases for objects stored in the ZODB.

There is at least the Quickinstaller Mock. I am not sure it is needed while migration (need to look into it, maybe @mauritsvanrees knows details?). I would propose to not enable those mocks globally, but only while migration code runs.

**Comment by mauritsvanrees** [comment]
In February I already opened https://github.com/plone/plone.app.upgrade/issues/227, saying more or less the same. But fine to have it more visible here.

I agree with removing everything up to but not including `to521`. So [this upgrade step](https://github.com/plone/plone.app.upgrade/blob/2.0.35/plone/app/upgrade/v52/configure.zcml#L128-L139) is the first one that should remain. This is the upgrade step from 5.2.0 (profile 5207) to 5.2.1 (5208), as you saw.
BTW, we should then update [this code](https://github.com/plone/plone.app.upgrade/pull/248/files#diff-bd90fb092a8f5c4ac8f1b6abcf9a81630e85d837b5aa6f830f3594983055a08cR49) that sets the start profile version in tests to 5200. That should become 5207. But maybe the test will still run fine with this.

The QuickInstaller mock must stay. I added it in the recently merged https://github.com/plone/plone.app.upgrade/pull/248, specifically so we can cleanly uninstall the QI in Plone 6. But maybe it can indeed be done differently, so it is only active when running the upgrades.

**Comment by ale-rt** [comment]
The PLIP was approved https://community.plone.org/t/fwt-meeting-minutes-2020-11-10/13086

**Comment by jensens** [comment]
This was resolved.

**Comment by gforcada** [comment]
@stevepiercy if it was completed, shouldn't be moved to the `Merged` column? :)

**Comment by stevepiercy** [comment]
@gforcada done, although I don't remember adding it to the PLIP board. Maybe I did a bulk action and caught this one by mistake.
