### ISSUE TITLE
Update Plone 5.2.X with latest TinyMCE 4.x release

### ISSUE THREAD

**Issue by fredvd** [plone/Products.CMFPlone#3207]
Plone 5.2 uses a 'builded' version of TinyMCE 4.x.  Including this version is a bit cumbersome and requires updates to multiple repo's, of which the 'builded' tinymce version is an external one. 

My perssonal motive: in some Plone 5.2 projects I'm seeing several issues with TinyMCE use in a pattern-modal where 'submodals' of TinyMCE its own menu's or popups are not visible or accessible anymore.  either these menu's disappear because of z-index issues or of scroll positioning. This happens for example with the template TinyMCE plugin. 

* Other Plone community members have made attempts at upgrading TinyMCE builded in the past, but these have not been merged into Plone 5.X. 
* This is not for Plone 6. TinyMCE 5 is a major rewrite.  Plone 6 master will get TinyMCE 5.5.X support through a an update of Mockup master where mockup will use ES6 modules and import syntax. 

Plone 5.2.2 and 5.2.3-pending are now using TinyMCE 'builded' 4.7.13, which line was changed the last time about three years ago.  The latest available 4.x series of TinyMC is 4.9.11.  I first couldn't find a changelog, tiny.cloud website starts documenting changes for 5.x and archive.tinymce.com stops at 4.3.3.  But there is a maintained changelog in the Tinymce github repo's 4.x branch: https://github.com/tinymce/tinymce/blob/4.x/changelog.txt

I'm not sure if using a 5.X version of tinymce in Plone 5.2 is feasible, considering the major changes. We are now using version 4.7.13 (2018-05-16),  TinyMCE version 4.9.11  is from (2020-07-13) and the changelog has around 98 changelog lines. 

I think it's worth it to update TinyMCE to at least 4.9.11 in the next minor Plone 5.2 update to include these fixes and solve potentional incompatibilities/regressions now.  It will also be beneficial that 'if' another emergency bugfix is required for a new found are already up to date. 

Maybe there's a more recent 'sweet spot' TinyMCE version between 5.0.X or the current 5.5.1 which we could update to, but since the 5.0.1 was never merged into mockup I think that's too big a wager. @frapell , you created the 5.0.1 branch in tinymce_builded. Did this sort of 'work' ?

**Comment by frapell** [comment]
@fredvd I tried to do so in https://github.com/plone/mockup/pull/901 however tests were failing. Then a discussion was started in that same ticket about why we were using the "builded" version instead of simply pulling the pkg using npm, and @thet mentioned it was because of translations and then attempted to upgrade to 5.5.1 in https://github.com/plone/mockup/pull/1024 pulling from npm, but seems there are some issues with the translations....

Personally, I would prefer trying to not get too far behind and trying to uprgade to the latest tinymce...

**Comment by thet** [comment]
@fredvd I'd focus on Plone 6 / Mockup ES6 which contains the latest TinyMCE 5 version.
If this is OK, please close the ticket. Otherwise someone needs to take over and update TinyMCE for Plone 4.

**Comment by fredvd** [comment]
@thet I had this almost working already, but made some mistakes with bundling last year.

In the meantime we have had some new bug reports from customer sites using Plone 5.2 in certain browsers (mainly Firefox). For example adding a link to an image is broken.

Not everybody can/will upgrade to Plone 6 classic and the latest TinyMCE 4 still contains some 80 fixes that are now not in Plone 5.2 .  And 5.2 will stille be around for a while…

I’ll keep it open, if I can/must work on it, it’s billable :-)

**Comment by pbauer** [comment]
Done

**Comment by pbauer** [comment]
Sorry, I thought that was for Plone 6. We could reopen that but with Plone 6 almost ready I guess nobody will put in the work to do that.

**Comment by fredvd** [comment]
As also noted by Johannes.  The site that gave me most inexplicable but occasional issues with TinyMCE 4 will move to Plone 6 shortly, so I won't have much motivation myself to look at this. But I'd like to keep this open for a while for others to find if they search for tinymce issues in Plone 5.2 frontend and find out our TinyMCE is rather long in the tooth and could be updated. to the latest 4.x.
