### ISSUE TITLE
Displayerror in Registration Form

### ISSUE THREAD

**Issue by 1letter** [plone/Products.CMFPlone#3217]
### What I did:

- Enable Self Registration with "use E-Mail" Option in Security Controlpanel
- Disable "Let users select their own passwords"

### What I expect to happen:

- a Form with Full Name and E-Mail Field

### What actually happened:

- a Form with Full Name and E-Mail Field
- and i see a Boolean Field in Readonly Mode with Option "Yes"

### What version of Plone/ Addons I am using:

- Plain  5.2.3 Plone without any Addons

Screen:
![Bildschirmfoto vom 2020-12-10 10-49-42](https://user-images.githubusercontent.com/11072000/101756639-8133cc80-3ad6-11eb-8c2f-c6139230ccef.png)

**Comment by jensens** [comment]
still an issue?
