### ISSUE TITLE
Please set up a Plip job for #3061

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3219]
If I go here:
- https://jenkins.plone.org/view/PLIPs/

I expect to see a PLIP job for #3061
This is not happening, can somebody please add one? 
Thanks a lot!

**Comment by ale-rt** [comment]
CC @plone/testing-team

**Comment by gforcada** [comment]
Sorry for the delay... how did you create the PLIP jobs? :thinking:

**Comment by gforcada** [comment]
I see no jobs, so I went ahead and created them:

https://jenkins.plone.org/view/PLIPs/job/plip-2967-barceloneta-lts-3.8/
https://jenkins.plone.org/view/PLIPs/job/plip-2967-barceloneta-lts-3.7/
https://jenkins.plone.org/view/PLIPs/job/plip-2967-barceloneta-lts-3.6/
https://jenkins.plone.org/view/PLIPs/job/plip-2967-barceloneta-lts-2.7/

**Comment by gforcada** [comment]
I see that for 2.7 it is failing due to expecting a version of setuptools that is only meant for python 3, is it expected to work with python 2.7 at all? :thinking:

**Comment by ale-rt** [comment]
I never did and probably I expressed myself very poorly, but I think you guessed what to do anyway :)
This is Py3/Plone6 only.
The PLIP cfg is here https://github.com/plone/buildout.coredev/blob/6.0/plips/plip-2967-barceloneta-lts.cfg

**Comment by ale-rt** [comment]
It seems to me the wrong cfg was picked:
- plips/plip-2967-barceloneta-lts-source-checkouts.cfg
The good one should be:
- plip-2967-barceloneta-lts.cfg

BTW I do not see any reason why we have two separate cfg for this plip.

**Comment by gforcada** [comment]
Finally I had some time: python 2.7 job removed and cfg updated. Sorry for the mistake :bow:

**Comment by mauritsvanrees** [comment]
Seems handled, closing.
