### ISSUE TITLE
Formatting of Systemmails is broken, if delivered via Exchange

### ISSUE THREAD

**Issue by 1letter** [plone/Products.CMFPlone#3221]
Plone 5.2.3 Plain
see https://github.com/zopefoundation/Products.MailHost/issues/35

Solution: use the rfc compatible policy
`message_from_string(messageText.strip(), policy=policy.SMTP)`

**Comment by mauritsvanrees** [comment]
In that issue, Dieter is [hoping that you will make a PR](https://github.com/zopefoundation/Products.MailHost/issues/35#issuecomment-743121605). Are you up for that?

**Comment by 1letter** [comment]
@mauritsvanrees  The changes are not only in the Products.Mailhost, also in here in CMFPlone. I will make the PR in both Package, i hope i do that  next week. I think the most work is on the tests, but i'm not sure. I will report and ask.

**Comment by jensens** [comment]
@1letter was this fixed?

**Comment by 1letter** [comment]
@jensens yes, i think it was fixed.
