### ISSUE TITLE
Old-style profile with JS/CSS imported but not reliably used within rendered pages after a while

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#323]
Situation: Plone 5.0a3 buildout with 

git@bitbucket.org:onkopedia/zopyx.existdb.git 

('dexterity' branch).

I created a new Plone site and added 'zopyx.existdb' as add-on.

As expected the JS/CSS resources show up in the resource registry control panels.

For debugging purposes I added an alert() to the local.js file of the package.

After the some operations in the control panel and some content management work in Plone UI the 
zopyx.existdb resources are no longer loaded - they do not longer show up in the HTML markup and of course the alert() is no longer trigger for each page load.

**Comment by bloodbare** [comment]
@zopyx I would recomend to create a bundle for your resources for plone 5, if you want to use the legacy support can you check at plone-legacy bundle if your resources are loaded there?

More information on : https://github.com/plone/documentation/blob/6ef432fa385f44d63ac0a2021541ffa381c03c47/adapt-and-extend/theming/resources.rst
