### ISSUE TITLE
Controlpanel for Relations

### ISSUE THREAD

**Issue by loechel** [plone/Products.CMFPlone#3231]
## Abstract

Provide two new controlpanels for admins and the helper-methods used by these forsm:

1. Rebuild all relations (``/@@relations_rebuild``)
   This form allows to rebuild all relations. It exports all valid relations from the relation-catalog, purges the relation-catalog (and optionally the intid-catalog) and restores all valid relations.
It also provied some statictics on existing relations and documentation on what it does and which relations are from where.

2. Inspect relations  (``/@@relations_inspect``)
   This controlpanel allows you to inspect specific relations:
   ![relations](https://user-images.githubusercontent.com/453208/109466325-d8a85f80-7a69-11eb-9d23-daf764b91060.png)

3. Helper methods 
    In `Products.CMFPlone.relationhelper` are the methods used by these forms. They are written in such a way that it is easy to use them separately, e.g. in upgrade-steps.
  
``rebuild_relations(context=None, flush_and_rebuild_intids=False)``

``get_relations_stats()``

``get_all_relations()``

``store_relations(context=None)``

``purge_relations(context=None):``

``restore_relations(context=None, all_relations=None)``

``get_intid(obj)``

``get_field_and_schema_for_fieldname(field_id, portal_type)``

``cleanup_intids(context=None)``

``flush_intids()``

``rebuild_intids()``

``add_to_intids(obj, path)``

## Motivation

Ease migrations and dealing with realtions.

## Assumptions

Everyone wants this.

## Proposal & Implementation

Helkpers 

## Deliverables

Controlpanels for relations
Helper-methods
Tests
Docuymentation

## Risks
None

**Comment by tisto** [comment]
@loechel @pbauer do you plan to implement this for Volto and/or Plone classic?

**Comment by pbauer** [comment]
So far the implementation only exists for Plone Classic but Volto should be done as well.

**Comment by pbauer** [comment]
@plone/framework-team The pull-request #3232 is ready for review.

At the relations-sprint we discussed the following:
* A controlpanel in Volto is nice to have but not a hard requirement since it is on the same admin-level as the controlpanels for portal_catalog in the ZMI
* Additional features (pagination/sorting/deleting/showing more infos on items) may be a nice addition but are not really required

**Comment by ale-rt** [comment]
Thanks for the awesome job!
I will have a look and write to the @plone/framework-team to discuss this one!

**Comment by MrTango** [comment]
Does this depend on other addon's like the on ein collective you guys worked on or is it independend?
A bit more detail would be nice in the description.
What does it do?

**Comment by pbauer** [comment]
I updated the description a little.

**Comment by ale-rt** [comment]
The @plone/framework-team approved this PLIP during the last meeting
