### ISSUE TITLE
Duplicate ID #portal-languageselector

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3233]
The ID `#portal-languageselector` is used twice in Plone 5.2.2.
IDs must be unique.

<img width="899" alt="Bildschirmfoto 2021-02-02 um 10 22 35" src="https://user-images.githubusercontent.com/594239/106579212-b7bf1e00-6540-11eb-9e33-3752d16fc6ce.png">

**Comment by jensens** [comment]
this is fixed in Plone 6 (checked on classicui demo site)
