### ISSUE TITLE
Toolbar: Wrong position of content

### ISSUE THREAD

**Issue by csenger** [plone/Products.CMFPlone#3236]
### What I did:

Have a Window that is not as high as the content of the contentmenu in the toolbar. E.g. the Add...-Menu with a lot of types in it.

### What I expect to happen:

The contentmenu has the full height of the window and a scrollbar and is fully visible

### What actually happened:

The contentmenu has a negative margin-top. Only the lower part is visible.

![image](https://user-images.githubusercontent.com/223032/106958065-249d0880-6739-11eb-9b1a-aba2f64ea9db.png)

The code in mockup should be limited to a minumum margin-top of 0:

https://github.com/plone/mockup/blob/5e71d149beacbebc97eef2cf8693b1a706431923/mockup/patterns/toolbar/pattern.js#L324-L331

### What version of Plone/ Addons I am using:

Plone CMFPlone 5.2.2., mockup 3.2.2, plone.staticresources 1.3.2

**Comment by jensens** [comment]
AFAICT it works fine in Plone 6. Please reopen if I am wrong.
