### ISSUE TITLE
Where is 5.2.3 ?

### ISSUE THREAD

**Issue by robertherzog** [plone/Products.CMFPlone#3238]
### What actually happened:
I am really surprised that, for several months now, the latest "release 5.2.3" is unavailable on the main Plone website, even if it mentions on a bright red background "Get Plone 5.2 (stable)", which links to 5.2.3 on Github. I know it is possible to find 5.2.2 but giving a link to an unexisting package is not very stimulating to get using Plone by newcomers.
I have been using Plone over the most of last decade, I run several sites on 5.1. I witnessed that the support for Plone has been steadingly vanishing.
This is sad.
Greetings from sunny, but icecold Belgium
Robert

**Comment by mauritsvanrees** [comment]
Hello Robert,

Unfortunately, for the past half year we are having problems creating a tested unified installer that works on Linux, Mac and Windows. A lot of work is under way to [get this fixed](https://github.com/plone/Installers-UnifiedInstaller/pull/110).
Meanwhile lots of people are using 5.2.3 by extending the versions from https://dist.plone.org/release/5.2.3/versions.cfg.

I am currently working on getting 5.2.4 released. For the installer it looks like we will choose to skip creating one for 5.2.3, and go to 5.2.4 instead.

Greetings from a Belgium that is warming up quite nicely this weekend. :-)
