### ISSUE TITLE
remove skins/plone_prefs/password_form?

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#3240]
There's still a password_form in skins/plone_prefs.
Is this covered by passwordpanel.py in plone.app.users or still needed?

**Comment by mauritsvanrees** [comment]
This form is indeed not needed anymore. I am removing it in the next two PRs that I am testing together:

- https://github.com/plone/Products.CMFPlone/pull/3462
- https://github.com/plone/plone.app.upgrade/pull/276
