### ISSUE TITLE
2021 News content not being indexed by Google

### ISSUE THREAD

**Issue by barbiebrega** [plone/Products.CMFPlone#3243]
I am using Plone 4.1.6 (4115)
I noticed the news content created in 2021 are not being indexed by Google.
I think theres is a ceiling problem/bug somewhere...
Because I was having this issue with date ceiling: https://github.com/plone/Products.Archetypes/issues/133
Already fixed it as reported in the issue above.
Although the content have the correct date now, they don't appear in Google searches anymore.
But they do return in Plone search

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
