### ISSUE TITLE
Add IMREALLYPLONE6 Python import marker

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#3257]

**Comment by thet** [comment]
Does this help? https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/meta.zcml#L21

You can ask for the feature with:
```<configure zcml:condition="have plone-60">...</configure>```

Don't know yet about python variables, but for those I'd follow what we're using in testing, like ``PLONE_60`` or so...

**Comment by mauritsvanrees** [comment]
@thet See also discussion in this PR: https://github.com/plone/Products.CMFPlone/pull/3258

**Comment by mauritsvanrees** [comment]
This is finished.

Plone 6.0 has:

```
PLONE52MARKER = True
PLONE60MARKER = True
```

and Plone 5.2 only has:

```
PLONE52MARKER = True
```
