### ISSUE TITLE
Reversed Order button on Collections does not save its value in Plone 6

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3263]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

When I edit a Collection in Plone 6 (e.g. https://demo-latest-plone6.plone.org/en/++add++Collection)
And I select "Reversed Order" on any sorting criteria the value (True) is not persisted. 

In Plone 5.2-latest (e.g. https://demo-latest-py3.plone.org/en/++add++Collection) it works.

**Comment by pbauer** [comment]
@petschki maybe you have a idea how to fix this?

**Comment by petschki** [comment]
Seems like pat-querystring has something to do with it ... if you deactivate JS and edit the collection the checkbox gets saved. I'll do some further investigations ...

**Comment by petschki** [comment]
@pbauer this should fix it https://github.com/plone/plone.staticresources/pull/133

**Comment by jensens** [comment]
This is done and can be closed, right? 
If you disagree please reopen and go on.
