### ISSUE TITLE
Streamline Default Contenttype Templates

### ISSUE THREAD

**Issue by santonelli** [plone/Products.CMFPlone#3265]
This issue is to keep track of work on templates for default contenttypes.

### Idea

* Unify templates of default contenttypes
* Add structure by adding sections for all elements (text, contributors, rights, tags, etc.)
* Add tag `section` with class `section section-xxx` for each section
* Add tag `header` with headline to each section
* Headline may be hidden by CSS for some sections (e.g. tags)
* Main action (e.g. call to action) is part of template (not part of document actions viewlet)

### Strucuture

* Title
* Description
* Main content (Image, File download, Event date, etc.)
* Additional information (Image metadata, Event details)
* Actions (Link to fullscreen for Images, download for files, iCal download for events, etc.)
* Text

### Download Demo Content

* https://classic.plone.de/download/demo.zexp

### Known Bugs

* Comments reply button is missing
* Comments reply feature is broken
* Related content styling broken du to Bootstrap upgrade (missing media)

### Work in Progress

* https://github.com/plone/plonetheme.barceloneta/tree/issue_3265_streamline_templates
* https://github.com/plone/plone.app.contenttypes/tree/issue_3265_streamline_templates

**Comment by santonelli** [comment]
@agitator @jensens Here we go...

**Comment by agitator** [comment]
https://github.com/plone/plone.app.event/pull/328
https://github.com/plone/plone.app.contenttypes/pull/598
https://github.com/plone/plonetheme.barceloneta/pull/236

**Comment by agitator** [comment]
done
