### ISSUE TITLE
Circular dependency between Products.CMFPlone and plone.app.testing

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#327]
Products.CMFPlone depends on plone.app.testing and vica versa.

**Comment by hvelarde** [comment]
the issue is the following: suppose I want to guarantee that some version of some package is used only with some version of Plone.

I will introduce a dependency on ``CMFPlone == x.y`` and that will bring a circular dependency.

how do you solve this without doing it?

**Comment by gforcada** [comment]
Probably still not fixed, as CMFPlone does not have `plone/meta` applied yet, but we can close this, as it is an integral part of applying `plone/meta` to it.
