### ISSUE TITLE
mr.roboto does not propose to run the jenkins jobs automatically for Plone 6

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3270]
### What I did:

I make a PR for a Plone 6 package

### What I expect to happen:

mr.roboto propose me to add the comment `@jenkins-plone-org please run jobs`

### What actually happened:

nothing

**Comment by ale-rt** [comment]
As far as I can see this can be solved by providing a plone_versions configuration:
- https://github.com/plone/mr.roboto/blob/825b18ee43f230dc65a86b3573dd8a3cef55fc80/src/mr.roboto/src/mr/roboto/views/home.py#L141

**Comment by ale-rt** [comment]
Maybe this one should be updated?

**Comment by gforcada** [comment]
No, one is independent of the other, after fixing/improving mr.roboto, one needs to deploy it to `jenkins.plone.org`. I'm trying my best on keeping jenkins.plone.org alive and secured updating it as a new LTS is released, but seems I'm out of energy to do the final bits of plone 6 support on mr.roboto 😖 deploying is a piece of cake (at the end is just a git checkout 🤷🏾 ).

I'm happy to review merge requests there, but I failed for 1-2-3 years to provide the pull request you ask for. Maybe my motivation would be higher if we do pair programming? Anyone willing for that? So we finally fix this before plone 6 is actually out? 😓

**Comment by ale-rt** [comment]
That will be absolutely amazing, @gforcada! Whenever it fits you :)

**Comment by mauritsvanrees** [comment]
@fredvd from the admins team also wants to try updating mr.roboto on the server. I think he knows from a previous meeting with Gil how that would work. But he would need to update, and then someone (maybe me) try out if things are improved, and nothing new broken, and Fred could revert if needed.

**Comment by gforcada** [comment]
@ale-rt @fredvd we could do a joint session one day? 🤔 Wednesday next week around/after 19:00?

**Comment by fredvd** [comment]
> @ale-rt @fredvd we could do a joint session one day? 🤔 Wednesday next week around/after 19:00?

Yes that would be great! Wednesday evening april 28th is fine for me.

**Comment by ale-rt** [comment]
I cannot make it on the 28th, I will move the scheduling to an email thread.

**Comment by ale-rt** [comment]
Followup issue on mr.roboto https://github.com/plone/mr.roboto/issues/80
