### ISSUE TITLE
Which product should I use to migrate sites to Plone 5.2?

### ISSUE THREAD

**Issue by wesleybl** [plone/Products.CMFPlone#3271]
If I want to migrate a site from Plone 4 to Plone 5.2, without using the traditional migration of Data.fs from Plone, or migrate from another CMS, which product is recommended to use?

[collective.transmogrifier](https://github.com/collective/collective.transmogrifier)?
[collective.exportimport](https://github.com/collective/collective.exportimport)?

I saw that there is documentation on how to migrate using collective.transmogrifier:

https://training.plone.org/5/transmogrifier/

But I also saw that an official release of `collective.transmogrifier` with Python 3 support has not yet been released. I even opened a PR with the Python 3 branch:

https://github.com/collective/collective.transmogrifier/pull/22

I saw that the `collective.exportimport` has a lot more activity.

So, which product should I use? Which one will be easier to use and will have more support?

@mauritsvanrees @pbauer @zopyx @cdw9?

**Comment by zopyx** [comment]
Please discuss this on community.plone.org - don't think that this is a bugtracker related issue

**Comment by pbauer** [comment]
You don't need a special account for community.plone.org. Simply use your github account to login.
I've already migrated several projects using collective.exportimport and are now working on the migrating a huge (>80GB) intranet. There are some challenges (currently I'm working to migrate comments) but so far it seems fine.

**Comment by mauritsvanrees** [comment]
Transmogrify is more mature. More people will have experience with it. I still want to use this in combination with `collective.jsonify` to migrate my personal site to Plone 5.2. It currently is Plone 2.5 so `collective.exportimport` is no option for the export. I might want to try it for the import actually.

At Zest we are using `collective.exportimport` to migrate one customer site from 4.3 to 5.2, and will likely use it more often, certainly for more sites of this customer. So far it is working fine, and me and colleague Fred have contributed to the package the last few weeks.

In my experience, transmogrify is hard to configure, you have to setup a pipeline with hooks from various packages, and probably write a few of your own. exportimport is newer and probably lacks some parts, but it builds on the solid foundation of plone.restapi. I would go with `collective.exportimport`.
