### ISSUE TITLE
we should remove the “Newsletter signup” link in the footer of Plone.org

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#3275]
That newsletter is no longer being produced

![image](https://user-images.githubusercontent.com/815418/119347418-1ed42000-bc61-11eb-88b0-9891b0b3f52c.png)

**Comment by rohnsha0** [comment]
Will fix this soon

**Comment by rohnsha0** [comment]
Unable to find the codebase :(

**Comment by rohnsha0** [comment]
This issue makes no sense here... Issue raised in `ploneorg.theme` repo... (Issue21 in PLoneorg.theme)
