### ISSUE TITLE
After catalog clear and rebuild, the portal_catalog is in the brains

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3295]
Plone coredev 5.2 with Python 3.

- Create a Plone Site
- Go to the portal_catalog.
- The standard expected brains are there.
- Do a clear and rebuild on the advanced tab.
- A extra brain is there, with path `/Plone/portal_catalog`. The brain feels like a combination of the Plone Site object and the catalog.

I don't directly notice anything that goes wrong after this, but this cannot be right.
No idea what causes this.

**Comment by jensens** [comment]
Still an issue?

**Comment by mauritsvanrees** [comment]
No, I can't reproduce it anymore.
