### ISSUE TITLE
Content versioning is partially broken

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#330]
How to reproduce
* Create a new Plone 5 site.
* edit the front-page
* In the "Content info" toolbar click onto "history"

First error (minor) there: whatever action you take, the CSRF protection ask for confirmation.
Second bug: if you choose a *diff* action you'll get a traceback:

    2014-12-14 23:21:28 ERROR Zope.SiteErrorLog 1418595688.030.0113286654089
    http://localhost:8080/Plone/front-page/@@history
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module Products.CMFEditions.browser.diff, line 61, in __call__
      Module Products.CMFDiffTool.CMFDiffTool, line 159, in createChangeSet
      Module Products.CMFDiffTool.ChangeSet, line 86, in computeDiff
      Module Products.CMFDiffTool.CMFDiffTool, line 144, in computeDiff
      Module Products.CMFDiffTool.dexteritydiff, line 73, in __init__
      Module Products.CMFDiffTool.dexteritydiff, line 94, in _diff
      Module Products.CMFDiffTool.dexteritydiff, line 107, in _diff_schema
      Module Products.CMFDiffTool.dexteritydiff, line 180, in _compute_fields_order
      Module plone.autoform.base, line 55, in updateFieldsFromSchemata
      Module plone.autoform.utils, line 211, in processFields
    AttributeError: 'AutoFields' object has no attribute 'context'

**Comment by vangheem** [comment]
Well, working is better than a hack. @keul would you mind putting together a fix pull fix or a pull request to review.

Additionally, the toolbar needs to provide access to the history view.

**Comment by keul** [comment]
Hope to find some time to package the PR.

About toolbar: dont' think I'm able to help on this, not entered in the toolbar world right now.

**Comment by vangheem** [comment]
The toolbar was a false alarm.

**Comment by keul** [comment]
Pull requests above are not fixing all of the issues, some CSRF warning are left: from the `@@historyview` if you click on "View" of an old revision you are redirected to the `version_history_form.pt` (old style CMF template from CMFEditions. `_authenticator` must be added also there, question is: how?

**Comment by gforcada** [comment]
@keul by first porting that old style CMF template to a BrowserView? Technical debt that we have to pay at some point...

**Comment by keul** [comment]
@gforcada naturally yes, but I meant: there's some technical general decision to take on CMFEditions? Or just let's transform it into a zope 3 view (with the same name)?

**Comment by gforcada** [comment]
@keul again plain dumb logic from me: let's do the porting first and get rid of old technologies and then we can decide what to do with it. So spending as little as possible on it would be the best.

**Comment by vangheem** [comment]
Also note, something on that view is doing a write on read. That is why the
csrf page is coming up.

**Comment by vangheem** [comment]
I'm looking into finishing this right now.
