### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [plone/Products.CMFPlone#3308]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by avoinea** [comment]
@zidingz https://plone.org/security/report

**Comment by mauritsvanrees** [comment]
When you create a new issue here, you are presented with three templates to choose from: a Bug Report, a Plone Improvement Proposal, or a Security Issue.

![Screenshot 2021-09-01 at 09 49 55](https://user-images.githubusercontent.com/210587/131633654-52c15264-4811-4d24-be0b-4625e8bc59ee.png)

When you click the last one, you get this text:

> Please do **NOT** create a public bug report if you think this may be a security issue.
> Instead, please contact the Plone Security Team via email: security@plone.org.
> See also https://plone.org/security/report
> 

You are right though. When someone clicks on the Security tab in this repository, it would be good if they see a security policy, which is what creating such a `SECURITY.md` file does. I will see about adding that.

Thanks for the tip!
And I look forward to seeing your security report.

**Comment by mauritsvanrees** [comment]
Done: https://github.com/plone/Products.CMFPlone/security/policy

**Comment by zidingz** [comment]
Thanks so much!

**Comment by MatthewWilkes** [comment]
@zidingz Why did you ask us to add this if you were going to ignore the information? Your startup does not have our permission to accept reports on our behalf, please stop accepting them. If you'd like to email the security team without requiring a third party intermediary then you're welcome to.
