### ISSUE TITLE
Why the ticket 13715 (on dev.plone.org trac) was closed as invalid?

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#331]
The bug [Plone 4.3.1 TinyMCE Strikethrough not working](https://dev.plone.org/ticket/13715) was closed by @smcmahon as invalid but the problem still happens. Why was it closed? Was it because the problem is in Products.Tinymce and not Products.CMFPlone itself? [Products.TinyMCE repository](https://github.com/plone/Products.TinyMCE) don't accept issues, where do I write a bug report? I know that the upgradeStep proposed by @pbauer works but I think this should be fixed on Products.TinyMCE.

**Comment by vangheem** [comment]
Probably just closed because @smcmahon thoughts someone applied the fix. This is a fine place to report issues. I'm going to close this one though because this isn't actually an issue here. Feel free to add a new issue that is relevant or re-open the trac issue.
