### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by B3EF** [plone/Products.CMFPlone#3310]
Reported 4 bugs at huntr.dev
https://huntr.dev/bounties/7d9c4136-cdaa-4135-9c97-cd93b828b6a9/
https://huntr.dev/bounties/c244709f-2d8e-4d1e-ac23-a0dc1e4902db/
https://huntr.dev/bounties/5d707e7b-c968-4f1c-bf57-c211ded2eac0/
https://huntr.dev/bounties/1f38221e-55a1-47fe-9856-b711d18c3e39/
please check and verify the reports.

**Comment by MatthewWilkes** [comment]
You have irresponsibly disclosed potential security issues to a third party against our policies. We will not engage with this platform, please contact the security team directly.

**Comment by JamieSlome** [comment]
@B3EF @MatthewWilkes - just jumping in here! 👋 

After speaking with the maintainers, they have requested that any security issues are disclosed directly to them. Whilst we would love to support disclosures through our platform, it is of course important that we respect their security processes as well! ❤️

**Comment by MatthewWilkes** [comment]
@B3EF Jamie has sorted out the platform issues, so let's draw a line under that. If you still want to report issues then please do follow the process in security.md and email the security team. We do not pay bounties, but we do assign CVEs as standard for all confirmed reports and credit the discoverer.
