### ISSUE TITLE
DX-Site-Root: ZMI Nav-Tree is no longer expandable

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#3323]
After migrating to dx-site-root, the navtree within the zmi is no longer expandable

![Screenshot 2021-09-20 at 09 10 52](https://user-images.githubusercontent.com/365761/133967168-6a1b8f88-b8ca-4252-9d60-91ca842a0e3e.png)

https://github.com/plone/Products.CMFPlone/issues/2454 @jaroel @ale-rt

**Comment by ale-rt** [comment]
I will have a look!

**Comment by petschki** [comment]
This is true for all dexterity.Container classes ... would be cool if the containers could expand in ZMI in general ...

**Comment by jensens** [comment]
What a rabbit hole! Wanna feel like Alice? Go here https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/menu.dtml and here https://github.com/zopefoundation/DocumentTemplate/blob/master/src/TreeDisplay/TreeTag.py
Need more mushrooms or tea....

**Comment by jaroel** [comment]
Before you enable this by default, please keep in mind that BTreeFolder2 objects may contain many many many items ;)

**Comment by jensens** [comment]
For the site root we want it expandable. I doubt anyone adds there N-many items. And if: IDK
