### ISSUE TITLE
Insufficient Privileges on some views, even for Manager

### ISSUE THREAD

**Issue by laulaz** [plone/Products.CMFPlone#3335]
A series of views fails to show in latest Plone 6 (displaying the Insufficient Privileges page instead), at least :
- `password_form`
- `prefs_error_log_form`
- `prefs_error_log_showEntry`

all skin based templates relying on `prefs_main_template`.

Debug message in console :
```
Unauthorized: The object is marked as private.
Access to 'tag' of (Products.Five.browser.metaconfigure.IconsView object at 0x11002fa90) denied.
```

The code that leads to this error is there :
https://github.com/plone/Products.CMFPlone/blob/75a45a2ca50df8900a4203c3bb9220dec1eb220f/Products/CMFPlone/controlpanel/browser/prefsmaintemplate.pt#L48

Icon resolver was introduced in #3194.

**Comment by jmevissen** [comment]
The Error Log Form  is fixed with #3372

**Comment by laulaz** [comment]
`password_form` will be removed in #3425

**Comment by laulaz** [comment]
Everything is fine now (tested on Plone 6.0.0a6) 👍
