### ISSUE TITLE
PLIP: replace z3c.autoinclude with autoinclude

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3339]
## Abstract

Plone 5.2 uses `z3c.autoinclude` to pull in zcml of add-on packages via an entry point, and let add-ons automatically include zcml of their dependencies.
In Plone 6.0 we should use the new `plone.autoinclude`, and not include the zcml of dependencies.

## Motivation

The main motivations are a few downsides from `z3c.autoinclude`:

- It does not fully [support pip](https://github.com/zopefoundation/z3c.autoinclude/issues/9). A [PR](https://github.com/zopefoundation/z3c.autoinclude/pull/2) from 2016 to that effect was never merged.
- It supports `includeDependencies` in zcml, which is discouraged by core Plone developers, and is disabled in tests.
- It has legacy code to support old, weirdly named or non-standard installed packages.
- It is slow: it takes extra time to start Plone.

## Assumptions

- We still want auto discovery of zcml: a package registers an entry point that signals that it wants Plone to load its own zcml.
- We don't want to support `includeDependencies`. Packages should explicitly load any zcml from other packages that they need.
- We want support for detecting the entry point in pip-installed packages.
- The current `z3c.autoinclude.plugin` entry points should work unchanged.
- We like having a modern autoinclude version, with support for Python 3.6-3.10 including PyPy, and unit and integration tests with pip, buildout2, and buildout3.

## Proposal & Implementation

Follow the steps outlined in the [`plone.autoinclude` readme](https://github.com/plone/plone.autoinclude#inclusion-in-core-plone).

Note that the readme also contains information on how to test it in a current Plone project, without any changes to Plone itself. I tried it in a customer project on Plone 5.2.6-pending and it worked.

## Deliverables

- `plone.autoinclude`. Version 1.0.0a2 is on PyPI.
- A few changes in `Products.CMFPlone`, as outlined in the link in the Proposal & Implementation above.
- Include `plone.autoinclude` in the coredev buildout and run its tests. Note that we should keep using GitHub Actions in the repository for running all the unit and integration tests on pip/buildout2/buildout3. The coredev buildout can run the unit tests.
- For a migration on docs.plone.org, some info from the readme can be copied.

## Risks

- Packages that use the already discouraged `includeDependencies` in their zcml may no longer work. In a lot of cases, the dependencies will have their own entry point so their zcml gets loaded anyway, but maybe not in the right order.

## Alternative

By setting an environment variable`Z3C_AUTOINCLUDE_DEPENDENCIES_DISABLED`, or calling `z3c.autoinclude.api.disable_dependencies`, you can disable/disarm the `includeDependencies` directive in zcml. This is both the biggest time sink, and the biggest reason that the pip support is not complete. Loading zcml based on the entry point itself seems to work fine and fast enough in pip.

## Participants

Current `plone.autoinclude` 1.0.0a2 was made by Maurits van Rees (@mauritsvanrees) and Thomas Schorr (@tschorr), with partial review by Jens Klein (@jensens).

I would like to include this in one of the Plone 6 alphas. Definitely *not* before the conference though. :-)

cc @plone/framework-team

**Comment by mauritsvanrees** [comment]
I have added a [PLIP config](https://github.com/plone/buildout.coredev/blob/6.0/plips/plip-3339-plone-autoinclude.cfg), which uses a branch from [`CMFPlone` PR 3340](https://github.com/plone/Products.CMFPlone/pull/3340). With that, I think the PLIP is ready for review.

@gforcada Could you create a PLIP job please? Is it documented anywhere how to do that?

**Comment by rodfersou** [comment]
> and not include the zcml of dependencies.

what is the impact of this part of the change?

**Comment by tisto** [comment]
+1 from me. I'd like to see proper documentation on this and a short how-to for add-on developers what they need to do.

**Comment by ale-rt** [comment]
This PLIP has been approved by the @plone/framework-team 

I will take care of reviewing it ASAP

**Comment by mauritsvanrees** [comment]
> > and not include the zcml of dependencies.
> 
> what is the impact of this part of the change?

This means that `includeDependencies` in `configure.zcml` no longer works. Instead, packages should **explicitly** load any zcml from other packages that they need.

**Comment by jensens** [comment]
> I'd like to see proper documentation on this and a short how-to for add-on developers what they need to do.

I just read through the README which is really comprehensive and explains it very well too. OTOH we could add a short howto to the new backend documentation (which is currently very empty) with a link to the README.

**Comment by ale-rt** [comment]
#3340 is merged!
