### ISSUE TITLE
Plone 6 File upload: ZODB.POSException.Unsupported: Storing Blobs in <ZODB.mvccadapter.MVCCAdapterInstance object at 0x112a40670> is not supported.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3345]
- Plone 6.0.0a1 installation with Python 3.9/pip
- Creating a `File` causes this error with an arbitrary file upload

```
Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 173, in transaction_pubevents
  Module transaction._manager, line 257, in commit
  Module transaction._manager, line 134, in commit
  Module transaction._transaction, line 282, in commit
  Module transaction._compat, line 49, in reraise
  Module transaction._transaction, line 273, in commit
  Module transaction._transaction, line 456, in _commitResources
  Module transaction._compat, line 49, in reraise
  Module transaction._transaction, line 430, in _commitResources
  Module ZODB.Connection, line 497, in commit
  Module ZODB.Connection, line 546, in _commit
  Module ZODB.Connection, line 584, in _store_objects
ZODB.POSException.Unsupported: Storing Blobs in <ZODB.mvccadapter.MVCCAdapterInstance object at 0x112a40670> is not supported.
```

**Comment by avoinea** [comment]
This issue is still there with Plone **6.0.0a3**. @mauritsvanrees Anyway to fix this with `mkwsgiinstance`?

**Comment by mauritsvanrees** [comment]
I tried https://github.com/bluedynamics/plone-kickstarter and it creates a proper `zope.conf` with blobstorage. Not sure where it gets this from though. Ah, the instance skeleton is created by [`cookiecutter-zope-instance`](https://github.com/bluedynamics/cookiecutter-zope-instance/blob/475308ab6718a54febfcd0737768fb455cecb3cc/%7B%7B%20cookiecutter.target%20%7D%7D/etc/zope.conf#L39) which is basically a replacement for `plone.recipe.zope2instance`.

**Comment by mauritsvanrees** [comment]
This works, if you follow the current [installation instructions](https://6.dev-docs.plone.org/install/index.html).

**Comment by FarooqAlaulddin** [comment]
Still having this issue after following [Plone-6-Multi-Clients-Zeo](https://community.plone.org/t/example-of-two-clients-and-a-zeo-server-with-a-pip-installation-of-plone-6/15518#example-how-to-create-a-zeo-cluster-with-plone-6-and-pip-1). Zeo is running and I am able to edit existing content-type with/without file type, but when I try to add any content-type with file I get the same error - any thoughts?

[cookiecutter-zope-instance](https://github.com/bluedynamics/cookiecutter-zope-instance/blob/475308ab6718a54febfcd0737768fb455cecb3cc/%7B%7B%20cookiecutter.target%20%7D%7D/etc/zope.conf#L39) Creates the following configs:



    # This file was generated by "cookiecutter-zope-instance"
    %define INSTANCEHOME /opt/projects/Plone/standards/backend/instance
    instancehome $INSTANCEHOME
    
    %define CLIENTHOME /opt/projects/Plone/standards/backend/zeo/var
    clienthome $CLIENTHOME
    
    debug-mode off
    security-policy-implementation C
    verbose-security off
    
    default-zpublisher-encoding utf-8
    <environment>
        CHAMELEON_CACHE /opt/projects/Plone/standards/backend/zeo/var/cache
        zope_i18n_compile_mo_files true
    
    </environment>
    # Database
    <zodb_db main>
        mount-point /
        cache-size 30000
        # ZEO storage
        <zeoclient>
            # blobs
            shared-blob-dir true
            blob-dir /opt/projects/Plone/standards/backend/zeo/var/blobs
            # general settings
            server localhost:8100
            name 1
            cache-size 128MB
            # Advanced options
            read-only-fallback true
            read-only true
            drop-cache-rather-verify False
        </zeoclient>
    </zodb_db>

With instance.ymal be:

    default_context:
    
        db_storage: 'zeo'
        db_zeo_server: 'localhost:8100'
        location_clienthome: '/opt/projects/Plone/standards/backend/zeo/var'
        db_blobs_location: '/opt/projects/Plone/standards/backend/zeo/var/blobs'
    
        # rest of configs...
