### ISSUE TITLE
Bylines are not consistent

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3350]
### What I did:

1. Go to https://6-classic.demo.plone.org/
2. Login as Manager
3. Browse to https://6-classic.demo.plone.org/en/demo/a-folder
4. Note that the byline viewlet for the folder displays just the date while the byline for the page inside a folder displays also the time
![image](https://user-images.githubusercontent.com/1300763/139528484-089a3a5c-8c9f-43f7-8865-eb8e3bee97e5.png)

### What I expect to happen:

The bylines should be consistent, probably both should display the time.

### What version of Plone/ Addons I am using:

Plone 6.0.0a2.dev0 (6001)
CMF 2.5.4
Zope 5.3.1.dev0
Python 3.8.3 (default, Jul 14 2020, 07:39:54) [GCC 7.5.0]
PIL 8.3.1 (Pillow)
WSGI: On
Server: waitress 2.0.0

**Comment by ale-rt** [comment]
There but not just there...
If you look the screenshot the byline after the page heading says "Oct 30, 2021", the byline in the listed page says "Oct 30, 2021 08:11 AM".

The pt you linked is responsible for the second one (see the `long_format=1`):
https://github.com/plone/plone.app.contenttypes/blob/08b6cea4e17a5588d2f5cdbe706ca280f528c481/plone/app/contenttypes/browser/templates/listing.pt#L97

The other date is probably generated in some viewlet contained in `plone.app.layout`.
I would change **both** of them to use `pat-display-time` like we have in the sidebar, see:
![image](https://user-images.githubusercontent.com/1300763/189388624-e4def67f-0b91-41d7-ba70-235f058c9381.png)

**Comment by pbauer** [comment]
fixed
