### ISSUE TITLE
Document author information not available to anonymous anymore?

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#337]
As part of moving the security controlpanel to z3cform (#216) I'm trying to write a robot test for the "Allow anyone to view 'about' information" setting.

It seems that document author information is now available only to logged-in users by viewing "Content info" in the edit bar.

Is there a plan to show this information also for anonymous users or should this setting be removed?

**Comment by jcerjak** [comment]
@bloodbare , @albertcasado , perhaps you have any input on this?

**Comment by bloodbare** [comment]
@jcerjak no plan on that subject, in case it should be maintained we should add another viewlet for it after content title

**Comment by thet** [comment]
@jcerjak there is a 'allowAnonymousViewAbout' setting in site_properties, which is used by the different folder views, including the ones in plone.app.contenttypes (which i'm refactoring at the moment). it would be great to have that setting in the site controlpanel instead.

**Comment by jcerjak** [comment]
@thet , @bloodbare , sorry my bad, the author info is still there, I just need to update the templates to use the setting from the registry (which is already there) instead of site properties. This will fix the folder listing and search templates, I need to check if others still have the author info, so I'll leave this ticket open for now.

**Comment by bloodbare** [comment]
Just take care that the Document By Line viewlet is disapearing (when we merge toolbar)
