### ISSUE TITLE
Update generator metadata literal in HEAD tag

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#3381]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Not a bug, a todo: The generator metadata literal in HEAD tag in Classic is:

`<meta name="generator" content="Plone - http://plone.com" />`

### What I expect to happen:

I suggest to update it with:

`<meta name="generator" content="Plone 6 - https://plone.org" />`

so we can track from now on the version numbers out there too.

PR in Volto: 

https://github.com/plone/volto/pull/2934

### What version of Plone/ Addons I am using:

Plone 6 Classic a2

**Comment by Dnouv** [comment]
Hello @sneridagh 
Is this issue still available to work? If it is, please let me know, I would like to work on this.
Looking forward to your reply.
Thank you!

**Comment by wesleybl** [comment]
@Dnouv to contribute to Plone, you must sign the Contributor Agreements. See:

https://docs.plone.org/develop/coredev/docs/agreement.html

**Comment by Dnouv** [comment]
Thank you for your prompt reply. I have a query regarding the Agreement. In the CA, there was a question.

> Which new files have you written so far and which files have you changed so far?

So to answer this question, shall I make the required changes as per this issue and then fill out the modified filename and cc the CA, or should I leave this question blank as of now and cc the CA before making the changes to any code file.
I would really appreciate it if you could help me out with this doubt. Thank you!

**Comment by wesleybl** [comment]
You can simply answer the question:

`None`

Then you can sign the CA and send. Then, you will be included in the plone organization, and from there, you can create Pull Requests to change the files.

If you find this question strange, you can open an issue in:

https://github.com/plone/Products.CMFPlone/issues

for it to be improved.

**Comment by heisenberg2208** [comment]
Can I work on this enhancement? still yet to be done?

**Comment by pavankalyan224847** [comment]
is this issue still available ? can i work on it ? I am a beginner to open source contribution so can you please guide me with this ? 
Thank you

**Comment by stevepiercy** [comment]
@pavankalyan224847 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), specifically [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

Regardless, this issue appears to have been resolved, at least as far as I can tell on the source code of https://classic.demo.plone.org/en, and in the [6.0.0b2 bug fixes](https://github.com/plone/Products.CMFPlone/blob/bccc107bb9c999f9883206943b01e37956ae6b6d/CHANGES.md#bug-fixes-18). Closing.
