### ISSUE TITLE
Link in "Powered by Plone & Python"

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#3382]
Question: Should we update the "Powered by Plone & Python" link in the footer? I'd say we only say "Powered by Plone". Also the link is outdated, it points out to `plone.com`

**Comment by ale-rt** [comment]
> Question: Should we update the "Powered by Plone & Python" link in the footer? I'd say we only say "Powered by Plone". 

+0 Maybe the @plone/marketing-communications team is more interested in that.

> Also the link is outdated, it points out to `plone.com`

+1 in fixing that!

**Comment by sneridagh** [comment]
Yeah, sure I wanted to put it here, so it's visible and start the discussion. Agreed, it is a question for the @plone/marketing-communications team to decide.

So for classic is clear, no change at all. The doubt was more geared towards Volto, since it's confusing for newbies after booting the frontend, and the footer says "Powered by Plone and Python" :/ . In that case, since Plone is made up a lot of things, I initially thought it might be better just say "Plone".

**Comment by asdali8888** [comment]
https://test.net

**Comment by rohnsha0** [comment]
@mtrebron Is there any change for this issue?
As the link is fixed in #3607!
Should we update anything with branding in the same PR? 
@ericof @stevepiercy @fredvd

**Comment by stevepiercy** [comment]
@rohnsha0 yes, please change "Powered by Plone & Python" to "Powered by Plone". We got a 👍 from a member of the @plone/marketing-communications team.

**Comment by rohnsha0** [comment]
@stevepiercy under #3607 or through an altogether new PR?

**Comment by stevepiercy** [comment]
Whatever is easier. We are not picky.

**Comment by stevepiercy** [comment]
Actually, now that #3607 was merged, a new PR is needed.
