### ISSUE TITLE
Automatically close stale issues and PRs?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3400]
The CMFPlone issue tracker usually has around 700 issues open, sometimes more, sometimes less. Some are really old, the oldest being issue #125 from 2013, or 8 years ago. (That one is actually still relevant, as it talks about possibly removing the `portal_properties` tool in Plone 6.)

Anyway, most issues of say at least one year old, are stale, not being worked on, not on anyone's radar. They clutter the issue tracker. Same for old pull requests.
I often go to a Plone package that I want to work on or report a problem for. I check the open issues and PRs to see if anyone else has seen my problem or has made a fix already. In a lot of cases there are just a few issues and PRs so I check them, and they are often years old.

We could close these issues and PRs automatically after some time. There is a GitHub action for that: [close stale issues](https://github.com/marketplace/actions/close-stale-issues#usage) which you can run in cron mode. The link is to the usage examples.
There are lots of options, including debugging and options to define labels or milestones that prevent an issue/PR from ever getting marked as stale.

Is this something we want?
We could try it out on a less used repository. Randomly chosen: [`plone.app.robotframework`](https://github.com/plone/plone.app.robotframework) with 11 issues and 2 PR, all from 2019 or earlier.

Note: I am not volunteering to do this for all plone repositories. :-)
We should probably have the same config for all repositories, except maybe a more elaborate one for CMFPlone.

**Comment by mauritsvanrees** [comment]
No reaction, so let's close.

**Comment by davisagli** [comment]
I would support spending time manually reviewing old issues (and I will try to contribute to that now that I am more focused on Plone work) but I'm -1 on closing old issues automatically. There are real problems that are old, there are tickets which have useful information about those problems, and closing them makes it harder to find the information.
