### ISSUE TITLE
error on rss feed on plone site search

### ISSUE THREAD

**Issue by yurj** [plone/Products.CMFPlone#3405]
on plone 6, if you do a search, you get an error clicking on the RSS feed link (`search_rss`):

```
  Module Products.PluginIndexes.unindex, line 404, in getRequestCacheKey
TypeError: unhashable type: 'record'

 - Expression: " python: [i for i in feed.items"
 - Filename:   ... cts/CMFPlone/browser/syndication/templates/search-rss.pt
 - Location:   (line 12: col 29)
 - Source:     objects python: [i for i in feed.items];">
 ```

Sometimes it works, I think when the query result has not been cached. When cached, you get an error in calculating the cachekey, I suppose.

**Comment by wesleybl** [comment]
This seems to be related to: #3007

**Comment by wesleybl** [comment]
@yurj I did the PR: https://github.com/zopefoundation/Products.ZCatalog/pull/129 in the ZCatalog which I think will fix this. See if with the ZCatalog master branch this is fixed.

**Comment by yurj** [comment]
> @yurj I did the PR: [zopefoundation/Products.ZCatalog#129](https://github.com/zopefoundation/Products.ZCatalog/pull/129) in the ZCatalog which I think will fix this. See if with the ZCatalog master branch this is fixed.

Yes, it is fixed! Nice work :+1:

**Comment by wesleybl** [comment]
I pinned version 6.2 of `Products.ZCatalog`, which fixes this issue: https://github.com/plone/buildout.coredev/pull/791
