### ISSUE TITLE
Time field broken in es6 branch

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3409]
After updating mockup to replace pickadate with pat-date-picker from patternslib there is no more support for time-fields:

```
    time_field = schema.Time(
        title="Time field",
        required=False,
    )
``` 

The obvious solution would be to register a widget (z3c.form does not have one) for time-fields that use native html input for time:

```
<input type="time" name="mytime">
```

**Comment by petschki** [comment]
fixed here https://github.com/plone/plone.app.z3cform/pull/134

**Comment by pbauer** [comment]
The field looks ok but the data is not stored or even passed to the request.

**Comment by iham** [comment]
first weird behavior i can spot:
the rendered input has no "name" and "value" attribute.

trying to figure out how to add those...

**Comment by pbauer** [comment]
@iham in most other templates it is the tal-attribute `name view/name;`

**Comment by petschki** [comment]
time widget doesn't have its own template but reuses InputWidget with overridden `type` see https://github.com/plone/plone.app.z3cform/blob/petschki-html-datetime-field/plone/app/z3cform/widget.py#L233 ... this is exactly what Date and DateTime field do and there it works ... seems that the rabbithole is a bit deeper ...

**Comment by iham** [comment]
looks fixed :)
