### ISSUE TITLE
PortalState.portal() uses memoize_contextless

### ISSUE THREAD

**Issue by reinhardt** [plone/Products.CMFPlone#341]
PortalState.portal() depends on self.context, yet it uses memoize_contextless, which caches without regard to the context.

I have just run into a situation where this masks an error. I think it boils down to portal() first being called normally, with the portal object being returned and cached, and then being called on an object without an Acquisition chain. This should throw an error because the portal cannot be found, but the cached value is used instead.

See https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/globals/portal.py#L27

**Comment by vangheem** [comment]
hhmm, it seems to me like it's still better to have the caching done contextless. It's unfortunate that it can mask other errors; however, I'm not sure there is a solution for this in core.

Closing. Please reopen if you disagree and have ideas.

**Comment by reinhardt** [comment]
Is it an option to use plone.api.portal.get()?

**Comment by vangheem** [comment]
It should still be memoized though in that view.

**Comment by reinhardt** [comment]
Sure, I mean call plone.api.portal.get() in that view instead of getToolByName(). Then it doesn't depend on self.context and it's consistent with using memoize_contextless.

**Comment by vangheem** [comment]
Ahh, I thought the issue was related to already memoized results.

This depends on plone.api being merged.

**Comment by reinhardt** [comment]
> Ahh, I thought the issue was related to already memoized results.

Yes, but there's two ways of fixing it: Don't use the contextless version of memoize, or don't use self.context. :-)

> This depends on plone.api being merged.

Not sure what exactly that means, but alternatively zope.component.hooks.getSite() could be used, which is what plone.api uses internally.

**Comment by reinhardt** [comment]
Any opinions on my last comment? Should I make a pull request?

**Comment by vangheem** [comment]
Making a PR to do it the way plone.api does it would be good.

I'm not opposed to using plone.api itself but I guess the stance of the framework team is that we aren't to use it in plone itself to prevent circular dependencies.
