### ISSUE TITLE
Toolbar issues with ES6 branch

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3414]
Some items we discussed today:

- [x] Cannot be positioned on top of the page
- [x] when collapsed, make whole bar clickable to open (maybe even on hover?)
- [x] Cannot be made smaller unless viewport is at breakpoint md
- [x] Cannot scoll to actions that are at the lower end when viewport is small and/or items are expanded
- [x] Name (last item) not visible when viewport is small and/or items are expanded
- [x] mobile support

**Comment by petschki** [comment]
I've refactored the toolbar and implemented the "collapsed/expanded" mode which already was implemented in `plone.app.layout.globals.layout` by toggling the body class `plone-toolbar-left-expanded` via cookie. 

Now there are the following states which should be discussed:

1. **Expanded mode**: this is the default state for screenwidth larger than `md` breakpoint
2. **Collapsed mode**: Either the user toggled this mode with the collapse item at the top or the screen width is smaller than `md` breakpoint
3. **Expanded in collapsed mode**: there you can collapse the menu or make it permanent expanded again (icon is only shown if screen is larger than `md` breakpoint)

see it in action:

<img width="572" alt="Bildschirmfoto 2022-01-27 um 09 49 20" src="https://user-images.githubusercontent.com/511761/151325048-c1ce3f47-1f08-4145-9439-526c1fb8f1c9.png">

Development note:

The toolbar changes affecting multiple packages:
- `plone.app.contentmenu`
- `plone.app.layout`
- `mockup`

make sure you've updated all of them and youe are running mockup with webpack ... `plone.staticresources` do not have the latest changes of mockup

**Comment by agitator** [comment]
Nice!

**Comment by yurj** [comment]
Very nice. Beware that the toolbar is not scrollable under md scree sizes.

**Comment by petschki** [comment]
I've enabled the offcanvas-backdrop when in collapsed mode -> this fixes scrolling and close on click outside

**Comment by iham** [comment]
@petschki really like what you did there!

especially the <-| is a good action indicator.

**Comment by 1letter** [comment]
@petschki looks good!

**Comment by petschki** [comment]
First draft of "topmode" is pushed ... updated packages:

- mockup
- plone.app.contentmenu
- plone.app.layout
- plonetheme.barceloneta

as mentioned, the toolbar scss has moved to [plonetheme.barceloneta/scss/_toolbar.scss](https://github.com/plone/plonetheme.barceloneta/blob/master/scss/_toolbar.scss) ... 

open issues with topmode:
- [ ] menu items wrap when browser window is between xl and lg
- [ ] dropdowns do not close, when clicking outside
- [ ] _add your issue here_

**Comment by petschki** [comment]
hovering on collapsed toolbar opens it now
