### ISSUE TITLE
@@login-help uses subform but validation is over all the fields

### ISSUE THREAD

**Issue by yurj** [plone/Products.CMFPlone#3422]
### What I did:

go to /@@login-help

I expect to be able to retrieve my username or a link to reset the password

Instead, validation kicks in for both inputs while they should be indipendent.

I'm using plone 6.0, in Plone 5.2.6 it works.

Note: the feature is implemented using subforms.

**Comment by petschki** [comment]
If using subforms and the validation is done on the server side, we should implement `<form novalidate />` to skip browsers html5 validation.
