### ISSUE TITLE
Upgrading an existing site from 5.0a2 to 5.0a3 leads to a broken site

### ISSUE THREAD

**Issue by cewing** [plone/Products.CMFPlone#343]
**The Error**

    KeyError('Interface `Products.CMFPlone.interfaces.controlpanel.ITinyMCESchema` defines
    a field `toolbar_anchor`, for which there is no record.',) (Also, the following error occurred 
    while attempting to render the standard error message, please see the event log for full 
    details: Interface `Products.CMFPlone.interfaces.controlpanel.ITinyMCESchema` defines a 
    field `toolbar_anchor`, for which there is no record.)

**Steps to Reproduce**

1.  Download and run the Plone 5.0a2 unified installer
2.  Create a new site
3.  Update `buildout.cfg` in the `zinstance` to use the 5.0a3 versions.cfg instead of `versions.cfg` and update `find-links` to add the 5.0a3 release directory on `dist.plone.org`
4.  Attempt to view the site, see the above error
5.  Run the upgrade as directed by the zope root view
6.  Repeat step 4 above

**Comment by tisto** [comment]
Seems like there is an upgrade step for the TinyMCE missing. As far as I know @robgietema added those settings. I guess we need an upgrade step to fix that.

@esteele Was 5.0a3 officially released? Do we have to add an upgrade step for 5.0a3 -> 5.0a4 or 5.0b1?

**Comment by cewing** [comment]
It looks like the problem is that the upgrade step for `to_alpha3` was released without the appropriate profile contents.  The 1.3.8 release of `p.a.upgrade` contains `rolemap.xml` but the first commit *after* the release removes that and adds `registry.xml` which contains the right registry records.  (see plone/plone.app.upgrade@fe70ffd1)

**Comment by cewing** [comment]
@tisto, @esteele there is no installer for 5.0a3.  There is a `versions.cfg` and a folder on dist.plone.org

**Comment by cewing** [comment]
I'd say this can be marked as 'fixed' since the upgrade step is there and will be in the next release of `p.a.upgrade`.  I'll go ahead and close it.  Feel free to re-open if more attention is needed.

**Comment by esteele** [comment]
a3 was scrapped because of a mockup issue.

**Comment by cewing** [comment]
ahhhh, good.  this whole thing can be ignored then.  Thanks @esteele, @tisto
