### ISSUE TITLE
Remove the treatment of the "created" parameter in the search view

### ISSUE THREAD

**Issue by wesleybl** [plone/Products.CMFPlone#3432]
To fix #3007, @frapell did PR #3012. However, the problem occurs with any parameter that uses record notation in the URL. So I made PRs https://github.com/zopefoundation/Products.ZCatalog/pull/129 and https://github.com/zopefoundation/Products.ZCatalog/pull/130 in `ZCatalog`, to handle any record parameter.

Therefore, we must remove the treatment of the `created` parameter:

https://github.com/plone/Products.CMFPlone/blob/954942a1ec95d9c9472ecf791d8d55ca096b33bb/Products/CMFPlone/browser/search.py#L121-L124

when Plone 6/Plone 5.2 uses a version of Zope that contains these PRs.

Probably when Plone 6 is using Zope > 5.4 and Plone 5.2 is using Zope > 4.7

**Comment by mauritsvanrees** [comment]
Pinning new `Products.ZCatalog` releases should be enough. I can't create releases for this package, but I can ask.
I will wait a bit, since Jenkins has problems now.
