### ISSUE TITLE
iconresolver: support for extended icon names as contenttype/news-item broken

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#3458]
## Extended names are currently not correctly supported:

This registration can't be found with the current publishtraverse implementation:
```
  <record name="plone.icon.contenttype/news-item">
    <field type="plone.registry.field.TextLine">
      <title>Plone News Item</title>
    </field>
    <value key="resource">++plone++bootstrap-icons/file-earmark-richtext.svg</value>
  </record>
```

please also document this in [https://github.com/plone/documentation/blob/6-dev/docs/classic-ui/icons.md](https://github.com/plone/documentation/blob/6-dev/docs/classic-ui/icons.md)

**Comment by petschki** [comment]
this is fixed with #3512 ... see https://demo-latest-plone6.plone.org/@@iconresolver/contenttype/document for example
