### ISSUE TITLE
Use latest z3c.form in Plone Classic UI

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#3459]
## Abstract

This PLIPs mission is to upgrade `z3c.form` to the latest available version in Plone Classic UI.

## Assumption

Right now `z3c.form` is pinned to the latest 3.x version because of the dependencies to the subform functionality provided by `z3c.form.object.SubformAdapter` and `z3c.form.object.ObjectSubForm`. This has been removed in z3c.form since 4.x

## Proposal & Implementation

To get the latest z3c.form we have to backport subform functionality to `plone.z3cform` and figure out which core packages needs to be refactored.

For addons we have to provide a deprecation message to the new `plone.z3cform` module

## Deliverables

- [x] https://github.com/plone/Products.CMFPlone/pull/3460
- [x] https://github.com/plone/plone.app.portlets/pull/161
- [x] https://github.com/plone/plone.app.z3cform/pull/146
- [x] https://github.com/plone/plone.autoform/pull/41
- [x] https://github.com/plone/plone.z3cform/pull/20

## Participants

- @petschki

**Comment by petschki** [comment]
I've created a branch with the updated z3c.form version and this what happened on jenkins ... https://github.com/plone/buildout.coredev/pull/782

**Comment by petschki** [comment]
plone.autoform and plone.app.portlets can safely be merged because there are only backwards compatible test fixes.  CMFPlone has a backward compatible update to login form and can be merged too.  The plone(.app).z3cform package Updates need z3c.form >= 4 and therefore an updated versions.cfg of buildout.coredev …

/cc @mauritsvanrees @jensens might wanna have a look?

**Comment by petschki** [comment]
PS: jenkins is down to 3 failing tests. I think I can them later today.

**Comment by ale-rt** [comment]
+1 with this PLIP and what with Timo says about not having a PLIP for this!
Thanks @petschki

**Comment by petschki** [comment]
Thanks for your comments. Indeed not really worth a PLIP ... I have merged the updates in plone.(app.)z3cform packages and bumped `z3c.form` version to `4.2` in cordev 6.0 today ... everything runs smooth.
