### ISSUE TITLE
Clicking samples or Home will jump to Confirm Action Pages. Can I skip this step

### ISSUE THREAD

**Issue by suklix** [plone/Products.CMFPlone#3461]
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/26037801/159504856-b7630ddd-c0d3-4518-b83f-f481f1454efe.png">

**Comment by mauritsvanrees** [comment]
I don't know what "samples" is. this sounds like something specific to your website.

But this page is from the automatic CSRF protection. You can find some information here: https://github.com/plone/plone.protect#automatic-csrf-protection

Plone sees that visiting this page will make a change in your database. A database change is fine when you fill in a form, for example the Edit form of a page. But in this case you are simply visiting a page. This can have two causes, which Plone tries to protect you from:

- You have some code that is making changes even when simply visiting a page via a GET request. In general this is bad behavior, but there might be good reasons for this. You should investigate and try to figure out what is causing this. Recently I took over maintenance of a website for a client, and all visits to the homepage resulting in a write to the database, making the site slower. This was a simple error and I fixed it. If it is not easily fixable in your case, or if you think it is fine, the link above shows some ways to prevent showing this confirmation page.
- It could be a hack attempt, where someone on a different website is tricking you into following a link to make changes on your website. From your small description, it does not look like this is the case.

**Comment by EliaoHame** [comment]
Ok, thanks for your reply
