### ISSUE TITLE
Allow TinyMCE to be used in inline-mode

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3465]
Inline-mode of TinyMCE (https://www.tiny.cloud/docs/demo/inline) is nice among other reasons because the edited text looks exactly the way as the saved result. 

To enable it you could simply set `{"inline": "true"}` as the value in the field "Other settings" of the TinyMCE controlpanel. That is enough to trigger it. 

But that fails with `Could not initialize inline editor on invalid inline target element` since the html-tag that renders the TinyMCE is a `<textarea>`. See https://www.tiny.cloud/blog/tinymce-inline-option-not-working for details about that constraint.

The `<textarea>` thing is defined in `plone.app.z3cform.widget.RichTextWidget` which has `TextareaWidget` as `_base`. In `render_input_mode` of the widget it is possible to conditionally render a different html element like `div` around the text. But then fallback to textarea no longer works and saving also fails and and and... 

So it seems that using inline-mode in not straightforward. The question is do we like that option enough to do the required work?

**Comment by thet** [comment]
For reference, in Plone 5 you can activate inline editing like so:

```
from plone.app.textfield import RichText
from plone.app.z3cform.widget import RichTextWidget
from plone.autoform.directives import widget

[...]

    # inline: True necessary for reordering rows, otherwise tinymce would not render correctly.
    # tiny config to reduce UI
    widget("description", RichTextWidget, pattern_options={
        "inline": True,
        "tiny": {
            "toolbar": "bold italic bullist unlink plonelink",
            "plugins": ["plonelink", "lists", ],
            "menubar": "",
        },
    })
    # RichText for TinyMCE
    # allowed_mime_types to not get the mimetype selector and for tinymce to actually work.
    # the mimetypeselector has a config for the textfield, but here we are cloning textfields and the mimetypeselector config isn't updated.
    description = RichText(title=u"Beschreibung", required=False, allowed_mime_types=["text/html"])

```

**Comment by pbauer** [comment]
This is fixed with:

* https://github.com/plone/Products.CMFPlone/pull/3501
* https://github.com/plone/plone.base/pull/7
* https://github.com/plone/plone.app.upgrade/pull/288

**Comment by pbauer** [comment]
Jenkins:
https://jenkins.plone.org/job/pull-request-6.0-3.7/1178/
https://jenkins.plone.org/job/pull-request-6.0-3.8/1169/
https://jenkins.plone.org/job/pull-request-6.0-3.9/1103/

**Comment by pbauer** [comment]
With the current solution you can globally enable or disable inline mode in the TinyMCE controlpanel and still disable or enable it by schema-field for specific types or behaviors using `pattern_options={"inline": True}` like the example from @thet

What I did not see earlier is that the tinymce-pattern actually uses this setting to replace the textarea with a div before instanciating tinymce. So no changes to RichTextWidget are required.

**Comment by pbauer** [comment]
Tests are green.

**Comment by mauritsvanrees** [comment]
Alles gemerget.
