### ISSUE TITLE
js used when editing events is missing 

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3469]
When adding a event (https://6-classic.demo.plone.org/de/++add++Event) in Plone 6 classic the js hat used to modify various aspects of the input-fields is no longer used.

Examples: When selecting "Whole Day" the end-field was hidden or when the date of start was set to the future the end-date was set to the same day.

The old js from `plone/app/event/browser/resources/event.js` is not yet included in the new plone bundle.

**Comment by mauritsvanrees** [comment]
See also https://github.com/plone/plone.app.event/issues/350

**Comment by pbauer** [comment]
Fixed with https://github.com/plone/plone.app.event/pull/353
