### ISSUE TITLE
Duplication of source when Installing old-way JavaScript with Generic Setup

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#347]
On Plone 5 if you install an add-on using old way portal_javascript Generic Setup registration it will load the JavaScript in the new Resource Registry on the plone-legacy bundle (ok).

If you reinstall the product, the JavaScript is added another time and it will continue to add other copy of the JavaScript until you reinstall it.

If you provide an uninstall step (that is triggered by reinstall) you'll get no effect.

See also https://community.plone.org/t/plone-5-add-ons-development-with-css-js-resources/451/2

**Comment by keul** [comment]
Not checked, but probably is the the same for CSS also

**Comment by fulv** [comment]
Yes, you need to add an uninstall/registry.xml step, as well as remove the
bundle, at least as a workaround:

def _removeBundleFromRegistry():
    logger.info('Removing bundle reference from registry')

    record = 'plone.bundles/plone-legacy.resources'
    resources = api.portal.get_registry_record(record)
    if u'resource-plonesocial-network-stylesheets' in resources:
        resources.remove(u'resource-plonesocial-network-stylesheets')

http://stackoverflow.com/questions/26874044/how-to-remove-an-element-from-a-list-type-resource-registry-record-using-generic/26962193#26962193

**Comment by keul** [comment]
@fulv yes I forgot that question on SO, thanks for pointing it out.

However (bug apart) the situation now is very confused IMHO: you can register a JS using Generic Setup (old way) but you can't unregister it in any way apart pure Python.
I'd like to find some time to look at this to get a more logical behavior.

**Comment by vangheem** [comment]
I'm going to close this issue. We should think about updating plone.app.registry's import/export to handle more cases and manipulate entries better.

**Comment by keul** [comment]
@vangheem but still, if a user try to use old-way generic setup he will see its resources registered twice, isn't it?

**Comment by vangheem** [comment]
I don't see this behavior. Why is it showing twice?
