### ISSUE TITLE
Plone 6: Custom css textarea is disabled when empty

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3471]
In a new Plone 6 site, go to Theme Settings and then Custom Styles. The custom css textarea is black and you cannot type in it.

When [reviewing ES6](https://github.com/plone/Products.CMFPlone/issues/3211#issuecomment-1075746689) I already saw this problem. Later I edited my comment to note that after merge it was fixed. But now I see the problem again, both on migrated and on fresh sites. See screen shot.

![Screenshot 2022-03-30 at 10 17 29](https://user-images.githubusercontent.com/210587/160785740-c9837f2f-09b6-41d4-8fa4-122ded282218.png)

Wait a minute. When I disable Javascript, it works. And then I can re-enable Javascript and it keeps working. So it only fails when it is empty. Updated the issue title accordingly.

**Comment by mauritsvanrees** [comment]
In `plone.app.theming` in `controlpanel.pt` as a test I can change `tal:content="custom_css"` to `tal:content="python:custom_css or 'p {}'"` and then it works, because it is no longer empty.

@MrTango Is this something that needs to be fixed in `pat-code-editor`, that it also loads when the current field content is empty?

**Comment by pbauer** [comment]
Looks similar to #3473
