### ISSUE TITLE
Modeleditor not working in Plone 6 classic

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3473]
The code-editor used in Dexterity (https://6-classic.demo.plone.org/dexterity-types/File/@@modeleditor) and in easyform 
(/@@fields/@@modeleditor) is not working at all in Plone 6 classic coredev.

**Comment by pbauer** [comment]
This is still broken, now there is a empty input-form, the current xml is not displayed but I can add new xml which then overwrited the default-schema.

Image (http://localhost:8080/Plone/dexterity-types/Image/@@modeleditor):
![image](https://user-images.githubusercontent.com/453208/161008713-9a6a081e-2233-4055-aefe-0a4dc8273e0c.png)

Easyform (http://localhost:8080/Plone/asd/@@fields/@@modeleditor)
![easyform](https://user-images.githubusercontent.com/453208/161008721-6a953b2b-a10b-48ed-9ba7-9c9757bb3a9d.png)

**Comment by mauritsvanrees** [comment]
It shows nothing when the `model_source` of the FTI is empty. I have a fix now in the modeleditor in plone.app.dexterity:
https://github.com/plone/plone.app.dexterity/pull/343

**Comment by mauritsvanrees** [comment]
To be clearer: the FTI in question has a `model_file` which has some perfectly fine XML. It should be shown when there is not `model_source` yet.
