### ISSUE TITLE
Barceloneta accessibility (color contrast) issue?

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#349]
Not officially checked, but I think that Barceloneta use a bad color contrast for field descriptions in forms.
I'm the only one that have problems reading help text?
![schermata 01-2457034 alle 21 52 53](https://cloud.githubusercontent.com/assets/284924/5696770/3b4d5e12-99dc-11e4-9d53-d26eeb6b906d.png)

BTW: how about enabling barceloneta theme's issue tracker?

**Comment by davisagli** [comment]
I made it a bit better in #293, but it might need a bigger change.

**Comment by keul** [comment]
I'll retry with latest master of barceloneta theme. Maybe you really fixed this already.
Thanks

**Comment by thet** [comment]
issue tracker is now enabled.
