### ISSUE TITLE
Upgrade to TinyMCE 6

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3502]
In Plone 6 we should use the recently released TinyMCE 6 (currently 6.0.1).

Upgrade-Guide: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
Changelog: https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-overview/

**Comment by jensens** [comment]
fixed https://github.com/plone/mockup/commit/1f3b7346d0f442d8aa7eaacd9b4323c04f803292
