### ISSUE TITLE
Calendars are broken in events Recurrence overlay

### ISSUE THREAD

**Issue by laulaz** [plone/Products.CMFPlone#3509]
### What I did:
On an event with "Event Recurrence" behavior activated, if you click on Recurrence "Add" button, its overlay has problems :
1.  calendars popups are not working when trying to choose a date (for "Until" and for "Add date" fields)
2. z-index is incorrect and the overlay is behind TinyMCE toolbar

<img width="773" alt="capture" src="https://user-images.githubusercontent.com/1101273/164225795-04fac42d-34e0-4624-9575-7629ea717ccb.png">

I don't know if this is the right repo for this issue, or if it should be in `plone.app.event`.

### What version of Plone/ Addons I am using:
Plone 6 dev

**Comment by petschki** [comment]
I startet fixing this at BSSP ... issue is here https://github.com/plone/mockup/issues/1171 ... PR follows
