### ISSUE TITLE
searching for phrases within quotes doesn't work

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#3517]
the `munge_search_term` method doesn't work when searching for quoted phrases.

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py

**Reproduce:**

- go to https://6-classic.demo.plone.org/en
- search for `"Welcome to Plone"`
- you get an empty search result

**Background**

the `munge_search_term` returns this for the phrase above:

`'Welcome AND to AND Plone*'`

**Solution**

keep phrases within quotes untouched.

**Comment by yurj** [comment]
"Welcome" -> 1 result
"Welcome " -> 0 results (a space after 'e')
