### ISSUE TITLE
Editing filesystem based Dexterity types through the Plone UI -> "Settings" link missing.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#353]
Dexterity implemented using Python on the filesystem appear within the Dexterity types control panel of Plone. 

Is it possible to add new fields through the web to such types - not sure if this is desirable - but not my point here.

After adding a new field, the field itself is no longer editable.

For types created directly through the web there is a link "Settings" for each field.

This link is not available for fields added to types as decribed above.

**Comment by vangheem** [comment]
Confirmed this is no longer an issue on plone 5 master

![screen shot 2015-07-17 at 10 40 05 am](https://cloud.githubusercontent.com/assets/524413/8743574/3be92e88-2c70-11e5-8e9a-bb2e73b35ae7.png)
