### ISSUE TITLE
Formatting of long strings in toolbar

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3546]
See screenshot...hyphenation should be enabled (or at least wrapping of text). Test with 6.0.0a4.
![Uploading b85a91f6-76b7-4648-8f14-58b170b7a9b6.png…]()

**Comment by pbauer** [comment]
@zopyx The screenshot is missing.

Also: Long names also are reaching into the content-area:
![grafik](https://user-images.githubusercontent.com/453208/171401588-ffba7ae7-a425-4079-84ee-e3be727e878b.png)

**Comment by zopyx** [comment]
![Uploading b85a91f6-76b7-4648-8f14-58b170b7a9b6.png…]()

**Comment by zopyx** [comment]
![b85a91f6-76b7-4648-8f14-58b170b7a9b6](https://user-images.githubusercontent.com/594239/171432907-87924392-e03d-4b58-9215-c5e9d2c732a0.png)

**Comment by petschki** [comment]
the latest toolbar updates switched back to `pull-right` menus as you see in @pbauer 's screenshot ... there the length of the type strings isn't an issue anymore ... the collapsibles menus were "experimentally" released in alpha4 ...

**Comment by jensens** [comment]
@zopyx does https://github.com/plone/plonetheme.barceloneta/pull/289 fix it for you? if so, please close the issue.

**Comment by zopyx** [comment]
Resolved
