### ISSUE TITLE
Infinite white scroll area below footer

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3547]
Plone 6.0.0a4

See video...you can scroll infinitely (can be tested on plone-demo.info)

https://user-images.githubusercontent.com/594239/171179566-de10fda3-5743-4518-b586-3791c6ad28fa.mp4

 across the footer...there is only a white area...

**Comment by agitator** [comment]
https://6-classic.demo.plone.org (coredev) doesn't seem to have that issue... or does it?

**Comment by MrTango** [comment]
With  beta1 and after i can't reproduce this, closing it for now.
