### ISSUE TITLE
Toolbar: redirect after selecting default page broken

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#3548]
### What I did:

toolbar -> `display` -> `select content item as default view` -> select an item & save

### What I expect to happen:

I get redirected to the selected item

### What actually happened:

The current folder view remains

### What version of Plone/ Addons I am using:

Plone 6.0-dev

**Comment by mauritsvanrees** [comment]
I cannot reproduce this on current coredev with a fresh Plone site.

- Create a folder.
- Create a page in it.
- Go back to the folder.
- Select the page as default page.
- I get redirected to the default page.

Tried in three browsers.

Ah, but in folder contents the experience is off. Do you mean that?

This works fine:

- Go to folder contents.
- Select a different view.
- You get redirected to this view.

But this not:

- Go to folder contents again.
- Select the page as default.
- You are stuck with a modal that says 'Info: View changed'. Twice.
- Close the model and you are still in folder contents.

Tested: your PR fixes it.
