### ISSUE TITLE
Pinning the Plone toolbar in 6.0.0a4+ does not work in the context of the portlet configuration option

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3557]
- pin the toolbar on a particular context option
-  choose a portlet configuration
-  there is no way for getting back to the pinned toolbar configuration
![Uploading Bildschirmfoto 2022-06-08 um 23.50.58.png…]()

**Comment by petschki** [comment]
same issue on demo.plone.org with Plone 5.2 ... maybe we should style the "return" and "go to parent" links as buttons like its was done in Plone 5.2 ...

<img width="1192" alt="Bildschirmfoto 2022-06-10 um 09 40 21" src="https://user-images.githubusercontent.com/511761/173015655-7eaaa7d2-997e-4e4a-b59f-8f9896fe492b.png">
 
/cc @agitator

**Comment by 1letter** [comment]
I have add an PR in [plone.app.portlets](https://github.com/plone/plone.app.portlets/pull/165) to solve the display of links as Buttons

**Comment by agitator** [comment]
I'd prefer not to use buttons and just add more margin/whitespace around those links, as we do it in some sub-controlpanel-views.

**Comment by 1letter** [comment]
i think that can be closed with this merge https://github.com/plone/plone.app.portlets/issues/164
