### ISSUE TITLE
Instantsearch input field completely minimized and unusable with cluttered portal tabs

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3559]
Plone 6.0.0a4: as you can see, the search input field is minimized and the user can enter some search text however the contents of the input field is not visible
<img width="1496" alt="Bildschirmfoto 2022-06-10 um 12 28 35" src="https://user-images.githubusercontent.com/594239/173047058-346c30a8-26c7-4769-9bb3-b4c6c5b50398.png">

**Comment by petschki** [comment]
Fixed here https://github.com/plone/plonetheme.barceloneta/commit/e4755ab0507f5387dc671f2dafb1389c0d3b72e9
