### ISSUE TITLE
Test isolation problem with plone.dexterity

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#356]
Adding plone.dexterity to the plone_app_testing alltests group in tests.cfg (buildout.coredev 5.0) leads to test failures:

http://jenkins.plone.org/job/plone-5.0-python-2.7/4009/console

Running just the plone.dexterity tests works fine though.

@thet could it be that some event-related mocks are responsible since all test failures have dates in it? Running plone.dexterity with plone.event and plone.app.event ("bin/test -s plone.event -s plone.app.event -s plone.dexterity") works fine though.

```
Running zope.testrunner.layer.UnitTests tests:
  Tear down plone.z3cform.tests.plone.z3cform:Functional in 0.000 seconds.
  Tear down plone.z3cform.tests.P3FLayer in 0.000 seconds.
  Tear down plone.testing.z2.Startup in 0.007 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.004 seconds.
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.


Failure in test test_item_dublincore (plone.dexterity.tests.test_content.TestContent)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
    result = test_method()
  File "/home/jenkins/workspace/plone-5.0-python-2.7/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 669, in test_item_dublincore
    self.assertEqual(i.CreationDate()[:19], i.creation_date.ISO()[:19])
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '2015-01-22T13:19:24' != '2015-01-22T22:19:24'



Failure in test test_item_dublincore_date (plone.dexterity.tests.test_content.TestContent)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
    result = test_method()
  File "/home/jenkins/workspace/plone-5.0-python-2.7/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 702, in test_item_dublincore_date
    self.assertEqual(i.CreationDate()[:19], i.creation_date.ISO()[:19])
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '2015-01-22T13:19:24' != '2015-01-22T22:19:24'



Failure in test test_item_dublincore_datetime (plone.dexterity.tests.test_content.TestContent)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
    result = test_method()
  File "/home/jenkins/workspace/plone-5.0-python-2.7/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 744, in test_item_dublincore_datetime
    self.assertEqual(i.CreationDate(), i.creation_date.ISO())
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '2015-01-22T13:19:24-08:00' != '2015-01-22T22:19:24-08:00'

  Ran 1395 tests with 3 failures, 0 errors and 0 skipped in 1 minutes 36.665 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Total: 4734 tests, 3 failures, 0 errors and 12 skipped in 21 minutes 39.123 seconds.
```

**Comment by tisto** [comment]
Strange, I'm unable to reproduce this on my local machine (OS X). Will try on Ubuntu later today...

**Comment by tisto** [comment]
Crap. I can't reproduce the test failures on Ubuntu 14.04 LTS either. Seems this test somehow relies on the local date/time settings. @thet Do we have any best practices to mock date/time libs in tests?

**Comment by thet** [comment]
On Fri, 2015-01-23 at 00:55 -0800, Timo Stollenwerk wrote:
> Crap. I can't reproduce the test failures on Ubuntu 14.04 LTS either.
> Seems this test somehow relies on the local date/time settings. @thet
> Do we have any best practices to mock date/time libs in tests?

I've done this in plone.app.event like so:

https://github.com/plone/plone.app.event/blob/master/plone/app/event/tests/base_setup.py#L18
https://github.com/plone/plone.app.event/blob/master/plone/app/event/tests/test_event_listing.py#L13

it patches this one:
https://github.com/plone/plone.app.event/blob/master/plone/app/event/base.py#L458

**Comment by thet** [comment]
here's my changeset as attempt to fix that problem - but it doesn't
work:


[thet@luft plone.dexterity]$ git diff
diff --git a/plone/dexterity/tests/test_content.py
b/plone/dexterity/tests/test_content.py
index 7a9851f..1820b8a 100644
--- a/plone/dexterity/tests/test_content.py
+++ b/plone/dexterity/tests/test_content.py
@@ -1,4 +1,5 @@
 # -*- coding: utf-8 -*-
+from DateTime import DateTime
 from Products.CMFPlone.interfaces import IConstrainTypes
 from datetime import date, datetime
 from plone.behavior.interfaces import IBehavior
@@ -22,9 +23,17 @@ from zope.interface import Interface
 from zope.interface import alsoProvides
 
 import unittest
+import mock
 import zope.schema
 
 
+def patched_DT(dt_string):
+    if dt_string:
+        return DateTime(dt_string)
+    else:
+        return DateTime('2015/01/23 10:00:00.000000 GMT+1')
+
+
 class TestContent(MockTestCase):
 
     def setUp(self):
@@ -627,8 +636,8 @@ class TestContent(MockTestCase):
         self.assertTrue(isinstance(i.id, str))
         self.assertTrue(isinstance(i.getId(), str))
 
+    @mock.patch('DateTime.DateTime', new=patched_DT)
     def test_item_dublincore(self):
-        from DateTime.DateTime import DateTime
 
         i = Item(
             title=u"Emperor Penguin",
@@ -666,6 +675,7 @@ class TestContent(MockTestCase):
         self.assertEqual(i.rights, 'CC')
         self.assertEqual(i.Rights(), 'CC')
         self.assertEqual(i.creation_date, i.created())
+        import pdb; pdb.set_trace()
         self.assertEqual(i.CreationDate()[:19],
i.creation_date.ISO()[:19])
         self.assertEqual(i.modification_date, i.creation_date)
         self.assertEqual(i.modification_date, i.modified())
@@ -675,7 +685,6 @@ class TestContent(MockTestCase):
         self.assertEqual(i.Identifier(), i.absolute_url())
 
     def test_item_dublincore_date(self):
-        from DateTime.DateTime import DateTime
 
         i = Item(
             title=u"Emperor Penguin",
@@ -707,7 +716,6 @@ class TestContent(MockTestCase):
         self.assertEqual(i.Date(), i.EffectiveDate())
 
     def test_item_dublincore_datetime(self):
-        from DateTime.DateTime import DateTime
 
         i = Item(
             title=u"Emperor Penguin",
@@ -782,7 +790,6 @@ class TestContent(MockTestCase):
         self.assertEqual(i.foo, "bar")
 
     def test_container_init_dublincore(self):
-        from DateTime.DateTime import DateTime
         c = Container(
             title=u"Test title",
             language="en",

**Comment by tisto** [comment]
My attempt to fix this: https://github.com/plone/plone.dexterity/commit/04013c60aeb7715704a0d3642e84b5be1b4db404

**Comment by thet** [comment]
nice

**Comment by tisto** [comment]
Ok. Seems to work. Will close the issue...
