### ISSUE TITLE
Text on Create Plone Site screen is incorrect

### ISSUE THREAD

**Issue by stevepiercy** [plone/Products.CMFPlone#3568]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Note that the text is not correct.

![Screen Shot 2022-06-29 at 5 20 08 AM](https://user-images.githubusercontent.com/102112/176435249-931da994-7dfc-42fe-a3db-0cea879570c7.png)

> For an introduction to Plone, success stories, demos, providers, visit [plone.com](http://plone.com/). For documentation, add-ons, support, community, visit [plone.org](http://plone.org/).

plone.com redirects to plone.org.

See https://github.com/plone/documentation/pull/1260#discussion_r909565281

### What I did:

Followed the instructions here:

https://deploy-preview-1260--6-dev-docs-plone-org.netlify.app/install/source-step-by-step.html#installation-steps

### What version of Plone/ Addons I am using:

6.0a6

**Comment by rohnsha0** [comment]
@stevepiercy Check if the issue persists!?

**Comment by stevepiercy** [comment]
Yes. Please see: https://github.com/plone/Products.CMFPlone/search?q=plone.com

**Comment by rohnsha0** [comment]
@stevepiercy But the link you gave doesn't reflect the issue!
Please provide a valid link...

**Comment by stevepiercy** [comment]
It shows all instances of `plone.com` in the code base. That site no longer exists. All references to it should be updated to `plone.org`.

**Comment by rohnsha0** [comment]
@stevepiercy This means all instances should be changed to plone.org!?

**Comment by rohnsha0** [comment]
I'll soon fix the all the known instances through a PR! @stevepiercy

**Comment by stevepiercy** [comment]
Indeed, after your other PR, I suspected that there were more instances of `plone.com` lurking in the code base, just waiting to pounce upon the unwary. Imagine the horror! 😱 So I did that query to reveal where they are hiding.

**Comment by rohnsha0** [comment]
hahahah! 
I'll try to fix them all by sometime after this front-end fix for your issue!

**Comment by rohnsha0** [comment]
@stevepiercy Just searched plone.com in the organization, It has as much as 423 times used! :( 
https://github.com/search?p=3&q=org%3Aplone+plone.com&type=Code

**Comment by stevepiercy** [comment]
One repo at a time. 😉 If the repo is in Plone Core and still active, then it would be worth updating. Many are not, such as [plone/plone.com-static](https://github.com/plone/plone.com-static), and should be ignored (or archived as read-only).

**Comment by rohnsha0** [comment]
yaa! I understand

**Comment by rohnsha0** [comment]
doing a PR now! kindly verify!
