### ISSUE TITLE
Toolbar: long list of addable types, some not reachable

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3569]
Plone 6.0.0a6

We have a long list of addable types...some types at the bottom of the list of types is not reachable through scrolling. 

<img width="793" alt="Bildschirmfoto 2022-06-29 um 16 35 31" src="https://user-images.githubusercontent.com/594239/176463930-16eeff14-3fb3-4fd8-a120-390116d7cfb9.png">

**Comment by petschki** [comment]
I recommend a custom CSS snippet for your implementation:

example 1: scrolling

```
#plone-contentmenu-factories .dropdown-menu {
    max-height:40rem;
    overflow-y:scroll;
}
```

example 2: columns

```
#plone-contentmenu-factories .dropdown-menu {
    columns:3;
}
```

**Comment by zopyx** [comment]
This must not be in the responsibility of the add-on developers. 
As user *without any Plone theme* should be able to install as much add-ons with as much content types it needs.
The Plone toolbar must support this use case out of the box.
