### ISSUE TITLE
Mark imports from plone.app.controlpanel as deprecated.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#358]
We kept the imports in plone.app.controlpanel for backwards compatibility, e.g.:

https://github.com/plone/plone.app.controlpanel/blob/master/plone/app/controlpanel/editing.py

It would be nice if a deprecation message would show up if people use those imports.

I think @jensens wanted to write down some best practice docs for deprecation messages.

cc @MrTango @khink

**Comment by jensens** [comment]
sounds like this one is for me, so i can take deprecation manual further

**Comment by gforcada** [comment]
@jensens then you maybe are also interested in https://github.com/plone/Products.CMFPlone/issues/120

**Comment by davisagli** [comment]
plone.app.controlpanel is no longer used and I'm not sure there's any value in doing this. I'll close the issue
