### ISSUE TITLE
Robot tests with modals sometimes fail

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3582]
We have some unstable robot tests. One class of failures is where a modal is not closed. For example this [`plone.schemaeditor` failure](https://jenkins.plone.org/job/pull-request-6.0-3.7/1674/testReport/junit/plone.schemaeditor.tests.test_robot/RobotTestCase/Add_a_fieldSet_and_move_a_field_into_this_fieldset/):

> Keyword 'Page should not contain element' failed after retrying for 8 seconds.
> The last error was: Page should not have contained element 'css=div.modal-wrapper'.

I thought I had mentioned this elsewhere, but cannot find it. Maybe it was not on GitHub.

**Comment by petschki** [comment]
This happens very often but not reproducable. While locally all tests are green my latest jenkins job today had this again: https://jenkins.plone.org/job/pull-request-6.0-3.9/1654/robot/report/robot_log.html

**Comment by mauritsvanrees** [comment]
I have the feeling it goes wrong more often on Jenkins on 3.7 and maybe 3.8 than on 3.9. Local testing seems to confirm this. Does not really help though. :-/

**Comment by mauritsvanrees** [comment]
This seems okay now.
