### ISSUE TITLE
Empty folder_contents showing "Page 1 of 0 shown"

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3591]
Plone 6.0.0b1
![IMG_2512](https://user-images.githubusercontent.com/594239/183736257-fe4f4351-aaf0-4d74-b3df-c76879f8b055.PNG)

**Comment by rohnsha0** [comment]
![image](https://user-images.githubusercontent.com/86848116/188299668-a2830088-21e3-4631-9dbf-a455e2ca7e03.png)
Seems to be inherited from Plone v/5.2.9

Technicals:-
```
Plone 5.2.9 (5217)
CMF 2.6.0
Zope 4.8.2
Python 3.8.3 (default, Jul 14 2020, 07:39:54) [GCC 7.5.0]
PIL 6.2.2 (Pillow)
```

**Comment by devdanzin** [comment]
This seems to come from mockup, here:

https://github.com/plone/mockup/blob/51e23105cb9ac799cf88914e202398eb12c576b0/src/pat/structure/templates/paging.xml#L46-L51

I think the fix should be here, checking that `response.total` is zero and setting `this.state.totalPages` to 1:

https://github.com/plone/mockup/blob/51e23105cb9ac799cf88914e202398eb12c576b0/src/pat/structure/js/collections/result.js#L70-L73

Does this make sense? Should I send a PR?

**Comment by rohnsha0** [comment]
Implement the changes locally, if it works then surely go for a PR
