### ISSUE TITLE
Buttons cluttered together in Theming control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3595]
The top 3 buttons have no paddings, the placement of the bottom buttons also needs some love.
<img width="607" alt="Bildschirmfoto 2022-08-09 um 20 52 57" src="https://user-images.githubusercontent.com/594239/183738822-b05b0ea4-9b6b-4893-a133-748e625cb6f0.png">

**Comment by rohnsha0** [comment]
Does the issue persist? @zopyx

**Comment by zopyx** [comment]
Your question makes no sense without a fix for the issue. Is there a fix?

**Comment by stevepiercy** [comment]
@zopyx on https://demo.plone.org/@@theming-controlpanel, here is what I see.

![Screen Shot 2022-08-16 at 9 15 06 PM](https://user-images.githubusercontent.com/102112/185033366-6e310f88-6212-480d-b2b0-4bfb6de1371c.png)

Technical Details:
```
Plone 5.2.9 (5217)
CMF 2.6.0
Zope 4.8.2
Python 3.8.3 (default, Jul 14 2020, 07:39:54) [GCC 7.5.0]
PIL 6.2.2 (Pillow)
```

What is different between your experience and mine?

**Comment by zopyx** [comment]
Talking about Plone 6..you are on 5.2.9.

See 

https://www.plone-demo.info/@@theming-controlpanel

admin/admin

**Comment by stevepiercy** [comment]
Got it.

Next question, where in the heck is the CSS located? We looked all over in CMFPlone, no luck.

I found this template:

https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/controlpanel.pt

Which mentions the CSS file:

https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/controlpanel.pt#L34

Which is located here:

https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/resources/controlpanel.css

So perhaps this issue should be moved to that repo to fix?

**Comment by agitator** [comment]
The active styles are from plonetheme.barceloneta - just add some utility classes from bootstrap https://getbootstrap.com/docs/5.2/utilities/spacing/#margin-and-padding

**Comment by rohnsha0** [comment]
> The active styles are from plonetheme.barceloneta - just add some utility classes from bootstrap https://getbootstrap.com/docs/5.2/utilities/spacing/#margin-and-padding

But these are some template-based errors naa?
Then changing the theme should fix the error?!
Correct me if I'm wrong...

**Comment by stevepiercy** [comment]
@agitator thanks for the reference to Bootstrap 5.2 CSS classes to use. Now where the heck should they be added? That's what we cannot figure out.

**Comment by agitator** [comment]
The css-file is just the bare minimum and seen as a fallback.
All the button styling is from Bootstrap, so adding bootstrap classes to the template should be the fix.

**Comment by rohnsha0** [comment]
> The css-file is just the bare minimum and seen as a fallback. All the button styling is from Bootstrap, so adding bootstrap classes to the template should be the fix.

Yaa... Got it

**Comment by stevepiercy** [comment]
> All the button styling is from Bootstrap, so adding bootstrap classes to the template should be the fix.

This one?

https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/controlpanel.pt

**Comment by rohnsha0** [comment]
But padding is there... This must be fixed using internal CSS...

**Comment by stevepiercy** [comment]
I would say identify was done in Plone 5.2 for the theming control panel's buttons, which I think was based on Bootstrap 3 or 4, or it could have some custom CSS mixed in. If it is Bootstrap based, then check Bootstrap 5's upgrade guide to see what needs to be changed and how for the Plone 6 theming control panel.

**Comment by stevepiercy** [comment]
Actually, looking at the HTML, this is a [button group](https://getbootstrap.com/docs/5.2/components/button-group/). Button groups are essentially a group of buttons smooshed together into a toolbar. That does not make sense in this context. They are just buttons.

I would change `<div class="btn-group">` to `<div class="m-1">`, based on the [Spacing utility](https://getbootstrap.com/docs/5.2/utilities/spacing/) that @agitator mentioned earlier, giving it some margin around all sides.

**Comment by rohnsha0** [comment]
@stevepiercy Yaa... This would make sense... but won't that break anything?

**Comment by rohnsha0** [comment]
Directly changing to `<div class="m-1">`

**Comment by stevepiercy** [comment]
I don't know. Only one way to find out! Run tests before committing changes and pushing them to GitHub to make a pull request. If a test breaks, fix the test to match the new HTML markup.

**Comment by rohnsha0** [comment]
Hahaha! That's the only possible way.... I think would work...

**Comment by stevepiercy** [comment]
I mean, @rohnsha0, if you have not yet done so, it is a Really Good Idea™ to read and follow the [Guidelines for contributing to Plone Core](https://docs.plone.org/develop/coredev/docs/guidelines.html) _before_ you contribute to Plone core.

**Comment by rohnsha0** [comment]
@stevepiercy But that I'm already aware of Plone Core contribution guidance... Sir...

**Comment by rohnsha0** [comment]
![image](https://user-images.githubusercontent.com/86848116/186069464-3482de63-5e1c-41f5-8b51-3554dc6c442a.png)


is this good?

**Comment by rohnsha0** [comment]
This issue is to be fixed in `plone/ploneapp.theming` repo...
Closing this issue here.... as issue raised the repo....

**Comment by wesleybl** [comment]
>This issue is to be fixed in plone/ploneapp.theming repo...
Closing this issue here.... as issue raised the repo....

@rohnsha0 It's okay to open an issue in Products.CMFPlone, even if the fix is in another package. This is a common practice in Plone.

**Comment by rohnsha0** [comment]
> > This issue is to be fixed in plone/ploneapp.theming repo...
> > Closing this issue here.... as issue raised the repo....
> 
> @rohnsha0 It's okay to open an issue in Products.CMFPlone, even if the fix is in another package. This is a common practice in Plone.

No issues... Let it remain opened... Until that's merged in that repo! Right?

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/plone.app.theming/issues/212
