### ISSUE TITLE
PlonePAS searchForMembers does not check for encoding, resulting in missing results

### ISSUE THREAD

**Issue by do3cc** [plone/Products.CMFPlone#360]
searchForMembers does allow to pass a REQUEST object. its values are then used for face value. The form input are encoded strings and methods lower in the foodchain handle them improperly. There won't be exceptions but people are just not found.
This is true in current Plone 4.3 and current development branch

**Comment by do3cc** [comment]
Note to self.
Products.CMFDefault.utils:decode() would be the universal answer.
But not today...

**Comment by do3cc** [comment]
This has been fixed in 5.0.1 and later Jensens improved the code to not have a dependency on CMFDefault

**Comment by do3cc** [comment]
Oh, in 4.1.x it is in master but without a release

**Comment by pbauer** [comment]
branch 4.1.x has seen two new releases (4.1.5 and 4.1.6) that include the fix (https://github.com/plone/Products.PlonePAS/commit/eb93b117702daf640b78dbc95495ba5ea2450bdd).
