### ISSUE TITLE
Inconsistent font sizes used for description in control panels

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3600]
All descriptions should use the same font/font-size

Plone 6.0.0b1

<img width="944" alt="Bildschirmfoto 2022-08-09 um 21 25 27" src="https://user-images.githubusercontent.com/594239/183744544-985dc590-01a4-4ea8-9131-5100e65ec1ea.png">
<img width="1265" alt="Bildschirmfoto 2022-08-09 um 21 25 22" src="https://user-images.githubusercontent.com/594239/183744551-c57246ca-63a3-4c4a-97db-0610313723af.png">

**Comment by rohnsha0** [comment]
@zopyx can you please elaborate the issue?
Unable to see any inconsistency in font sizing...

**Comment by zopyx** [comment]
Open 

https://www.plone-demo.info/@@usergroup-groupprefs
https://www.plone-demo.info/portal_registry

side by side and see the different font-sizes of the text below the H1 tag yourself.

Login: admin/admin

**Comment by rohnsha0** [comment]
@zopyx Can understand what's the issue is....
But can't figure out what's going wrong...

**Comment by zopyx** [comment]
> But can't figure out what's going wrong...

Huh??? The same functionality like description should be displayed in all contexts with the same font-size.

**Comment by rohnsha0** [comment]
What I was trying to say that how should this be fixed....
That I'm unable to figure out... 😑

**Comment by zopyx** [comment]
The templates use different markup/CSS for the related description..just look at the markup using the website inspector of your browser.

**Comment by rohnsha0** [comment]
> The templates use different markup/CSS for the related description..just look at the markup using the website inspector of your browser.

changing the class from `lead` to `text-muted m-2` will do the job regarding font sizing in the description

**Comment by rohnsha0** [comment]
In fact I think there's some inconsistency in page margins.... As `Configuration Registry` page has some bigger margin than the homepage
