### ISSUE TITLE
main_template references plone.com 

### ISSUE THREAD

**Issue by mtrebron** [plone/Products.CMFPlone#3605]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

The CMFPlone [main_template](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/main_template.pt#L42) includes this line:
`<meta name="generator" content="Plone - http://plone.com" />` 

See also: https://github.com/plone/Products.CMFPlone/issues/3568

### What I did:

Create a new Plone6 classic site.

### What I expect to happen:
render HTML that references plone.org

### What actually happened:
render HTML that references plone.com - this site no longer exists

### What version of Plone/ Addons I am using:
Version Overview

    Plone 6.0.0b1 (6006)
    CMF 2.6.0
    Zope 5.5.2
    Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
    PIL 9.1.1 (Pillow)
    WSGI: On
    Server: waitress 2.1.2

**Comment by rohnsha0** [comment]
Changing the link would work right?
