### ISSUE TITLE
Move RAMcache controlpanel into CMFPlone 

### ISSUE THREAD

**Issue by khink** [plone/Products.CMFPlone#361]
There's an controlpanel to reset RAMcache called ram.py in p.a.controlpanel.

We should:
1) move it into CMFPlone
2) make it z3c.form
3) wire it up in the plone_control_panel (currently it isn't)

**Comment by tisto** [comment]
I did not move the RAM control panel to CMFPlone by purpose. Why would we want to re-add it if it has been removed before or never been included in Plone 4? Can anybody shed some light into this? Maybe it was no longer needed when we moved to plone.app.caching?

**Comment by davisagli** [comment]
The plone.app.caching control panel has a tab to manage the RAM cache, so I agree this isn't necessary.
