### ISSUE TITLE
TinyMCE editor not translated anymore

### ISSUE THREAD

**Issue by laulaz** [plone/Products.CMFPlone#3619]
TinyMCE menus / buttons are not translated anymore on Plone 6.0.0b1, everything stays in English.

For example, in spanish on the demo site :
<img width="1471" alt="tinymce" src="https://user-images.githubusercontent.com/1101273/185973625-e249c95c-264c-4435-8a9e-7f6c40879fda.png">

I don't know in which release the regression occurred, but it was still correctly translated on Plone 6.0.0a3.

**Comment by davisagli** [comment]
Also see https://github.com/plone/mockup/issues/1209

**Comment by laulaz** [comment]
I close this one, since it has been fixed and release (mockup 5.0.0-alpha.22)
