### ISSUE TITLE
Site Creation Volto creates Folder-type content

### ISSUE THREAD

**Issue by wesleybl** [plone/Products.CMFPlone#3628]
### What I did:

I created a Volto Site.

### What I expect to happen:

That contents of the Folder type are not created, since the Folders were removed in Volto.

### What actually happened:

Initial contents, News, Events and Users are created as Folder.

When I navigate in Volto and click on one of these items in the menu, I get the error in javascript console:

```
GET https://localhost/++api++/Members/@types/Folder 401
```

This seems to be done in:

https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/setuphandlers.py

### What version of Plone/ Addons I am using:

Plone 6.0b1

**Comment by mauritsvanrees** [comment]
This sounds like the kind of thing we want to get right before a final release, so could be called a blocker.
I confirm it on https://6.demo.plone.org/Members but only for the Members folder, not for News or Events.
The site seems to work fine though. Can you tell me what goes wrong because of this?

**Comment by wesleybl** [comment]
It works, but I find it strange to keep giving an error when browsing the site.

I also find it strange for the installation to create a content type that can no longer be created.

Also note that the contents are not useful for anything. Inside the news and events folder, Collections are created. Collections are not used in Volto. You cannot create a Collection type in Volto. So you don't see the search, which is done in Classic Plone. The Members folder, in Classic, has a view that serves to search for users. This view does not work in the Volto.

I keep asking myself what content should be created in Volto. Perhaps none?

**Comment by wesleybl** [comment]
Well actually the Collection works. But if you try to edit it, nothing is shown.

**Comment by davisagli** [comment]
For Volto instead of collections we can create a page with a listing block that does the same queries that were previously done using collections. Or, we can just remove those pages if we don't think they are valuable as default content.
