### ISSUE TITLE
TinyMCE does not load in add modal of static text portlet

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3636]
### What I did:
Add a Static Text portlet.

### What I expect to happen:

In the modal opended I am able to edit RichText.

### What actually happened:

In the modal there is no TinyMCE loaded.

### What version of Plone/ Addons I am using:

Vanilla 6.0.0b2 Classic UI

### Workaround

Add one character, save and then edit - this does not open in modal and works.

**Comment by mauritsvanrees** [comment]
Works fine here, both in a 6.0.0b1 site and in current coredev. I tried a portlet in the site root on the left and in the footer. This is the add form:

![Screenshot 2022-09-07 at 13 48 52](https://user-images.githubusercontent.com/210587/188871698-6fc97e7a-b588-427f-b0c3-c31fc4062b42.png)

Tried on Mac in Firefox, Chrome, Safari.

**Comment by jensens** [comment]
very strange, at time of writing I tried it in the 6-classic demo and it did not load. Now it works,
