### ISSUE TITLE
Rich text behavior not assigned to Plone Site

### ISSUE THREAD

**Issue by lzdych** [plone/Products.CMFPlone#3657]
### What I did:

Created a new Plone Site.

### What I expect to happen:

I expected a rich-text field with the default welcome content in the Plone Site's edit form.

### What actually happened:

The default welcome content of the homepage is displayed (Classic UI) but no way to remove or modify it.

### What version of Plone/ Addons I am using:
Plone 6.0beta3

**Comment by pbauer** [comment]
When you click "Create a new Plone site" `plone.volto` will be installed which disables the behavior plone.richtext for certain types (including `Plone Site`). This is for Plone 6 with the Volto frontend. 
If you click "Create Classic Plone site" that add-on is not installed and richtext-behaviors are enabled. 
Maybe the form needs a better text to explain what the difference between the buttons is. 
Also: Clicking "Advanced" has `plone.volto` enabled, more specifically the profiles `Plone 6 Frontend (plone.volto)` and `Plone 6 Frontend (Default content on homepage)` are pre-selected.

**Comment by lzdych** [comment]
@pbauer that's where I got confused but now it's clear so not a bug but misunderstanding.
