### ISSUE TITLE
Not clear what to do after creating a Volto site in the backend

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3664]
You startup a fresh Plone 6 backend, click to create a new Plone site, and then you see the homepage, saying "Welcome to Volto!" and "The React powered content management system" and a bunch of text. When you click to edit, you can change the title and description, but there is no text.
In fact, when you create a new page, you can set a title and description, but no text. Save it, and you see the rich text from the front page, probably due to acquisition. This is very strange.
Of course what you *should* do, is startup a fresh frontend, connect it to the backend, and then everything works. I don't think this is clear for all new users, and I have seen a few questions about this.

This came up during the Plone 6 coordination meeting today. The idea we came up with:

- add a viewlet in `plone.volto`
- probably in the above content title viewlet manager, but I don't much care where exactly.
- Let this show a warning in the style of a portal status message.
- We did not talk about a text, but something like "This backend is not meant for editing. You should use the frontend."

A helpful link would be nice. Maybe one of these:

- https://6.dev-docs.plone.org/install/containers/index.html
- https://6.dev-docs.plone.org/volto/getting-started/install.html
- https://volto.plone.org

The dev docs link should be replaced with docs.plone.org at some point, but I hope we can arrange a redirect from the old to the new once this is needed.

Feel free to come up with a good, short text, or with a completely different implementation idea.

**Comment by pbauer** [comment]
https://github.com/plone/plone.volto/pull/94 now displays the following warning: 

This site is configured to use the Volto frontend. Your are accessing the backend.
For more information please read the [documentation](https://6.dev-docs.plone.org/volto/index.html)

**Comment by mauritsvanrees** [comment]
Excellent. Thanks!

**Comment by RobHerzog** [comment]
Looking for a solution to cure the "The backend is not responding..." issue on my installation

**Comment by mauritsvanrees** [comment]
About that last comment: I had contact with Robert privately.  His issue has now been resolved, it was a problem with the Apache configuration.
