### ISSUE TITLE
ATReferenceField -> allow_sorting=True broken

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#368]
See:

https://community.plone.org/t/referencefield-ignores-its-ordering/485/ 

Either an issue of the ReferenceField implementation or the archetypes.referencebrowserwidget implementation.

**Comment by mauritsvanrees** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 4.3 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
