### ISSUE TITLE
Control panel for Content Type > Behaviors short names not displayed to user

### ISSUE THREAD

**Issue by stevepiercy** [plone/Products.CMFPlone#3706]
When browsing a specific content type from the Content Type control panel, a list of behaviors is shown in the user interface with their Titles and Description. For each behavior, one may view the source code of the checkbox (its name attribute) to view their Short Names (Side note: is there a better name than "Short Names"?). For example, see the content type page's behaviors: https://classic.demo.plone.org/dexterity-types/Document/@@behaviors

![content-type-control-panel-page-behaviors](https://user-images.githubusercontent.com/102112/208317125-a0d23006-6b4d-4ce7-bbf3-ef3ace5482b4.png)

See https://github.com/plone/documentation/pull/1372#discussion_r1050794700

### What I did:

Visit https://classic.demo.plone.org/dexterity-types/Document/@@behaviors, and view page source.

### What I expect to happen:

It would be helpful to display the "short names" to the user for development purposes.

### What actually happened:

Short names only display in HTML source.

### What version of Plone/ Addons I am using:

```
Plone 6.0.0 (6011)
CMF 2.6.0
Zope 5.7
Python 3.11.1 (main, Dec 10 2022, 15:02:21) [GCC 7.5.0]
PIL 9.3.0 (Pillow)
```

If this is not the correct repo, please transfer the issue to the correct one. Thank you!

@ksuess @jensens

**Comment by ameybhavsar24** [comment]
Hey, I can take this up. What should be the design?

**Comment by stevepiercy** [comment]
I would suggest a [table](https://getbootstrap.com/docs/5.3/content/tables/), with the column headers in the order of `Title`, `Short Name`, `Description`. I like tables that have the Twitter Bootstrap attributes of:

- [Responsive tables](https://getbootstrap.com/docs/5.3/content/tables/#responsive-tables)
- [Table group dividers](https://getbootstrap.com/docs/5.3/content/tables/#table-group-dividers)
- [Small tables](https://getbootstrap.com/docs/5.3/content/tables/#small-tables)
- [Hoverable rows](https://getbootstrap.com/docs/5.3/content/tables/#hoverable-rows)

However, I would strongly recommend that you consult with the Classic UI team to get their opinion for an optimal layout. They are familiar with details of the design of control panel appearance, not I. If you don't get a response here, then next ask in the [Community Forum development/user-interface category](https://community.plone.org/tags/c/development/user-interface/14/none) or in Discord's [#classic-ui channel](https://discord.com/channels/786421998426521600/787254601656827924). Also this issue originated from an idea from @ksuess, who may have an opinion as well.

**Comment by jensens** [comment]
I like the idea of having a a table, this would make the page easier to read.

**Comment by mtrebron** [comment]
Re side note: it may be helpful to distinguish between short names and dotted names. e.g. such as is done here:
https://plonerestapi.readthedocs.io/en/latest/usage/customization.html?highlight=dotted

> For customizing a specific field instance, a named IFieldSerializer adapter can be registered. The name may either be the full dotted name of the field, such as plone.app.dexterity.behaviors.exclfromnav.IExcludeFromNavigation.exclude_from_nav, or the shortname of the field, such as exclude_from_nav.

**Comment by jensens** [comment]
@mtrebron dotted names are phased out - the only reason to display them is to point to code location. Do not use them as a name to reference a behavior.

**Comment by stevepiercy** [comment]
@mtrebron can you provide a specific example of what you refer to? Either a link, screenshot, or how to get there from https://6-classic.demo.plone.org/dexterity-types/Document/@@behaviors?

**Comment by mtrebron** [comment]
@stevepiercy for example: https://6-classic.demo.plone.org/portal_types/Event/manage_propertiesForm

**Comment by mtrebron** [comment]
The example of the zcml is from plone.app.event. The ZMI properties form gives a lot more information about the content type, beyond what is listed in the Behaviors field on that page.

**Comment by stevepiercy** [comment]
I do not follow what you are proposing.

Are you suggesting more than the 3 columns to display in the Behaviors Control Panel?

Or something else?

The original proposal is to take what has been documented at https://6.docs.plone.org/backend/behaviors.html#built-in-behaviors and putting it into the control panel. Here's a sample of the proposed layout for the first two items:

| Title | Short Name | Description |
|-|-|-|
| 🔲  Allow discussion | `plone.allowdiscussion` | Allow discussion on this item |
| 🔲  Basic metadata | `plone.basic` | Adds title and description fields. |

**Comment by ksuess** [comment]
For development purpose an information that points to the code location would be helpful. Maybe you can come up with an idea that avoids the dotted name? As @jensens said, or as I interpret him, the dotted name should not be used for enhancing a content type in /profiles/types/MyContentType.xml

**Comment by mtrebron** [comment]
Sorry for being unclear, I'll try again - using the Behavior "Exclude from Navigation".

The dotted name -now deprecated- includes the name of the package, presumably it was something like `plone.app.dexterity.behaviors.exclfromnav`
The name, as defined in the behavior's [zcml registration](https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/behaviors/configure.zcml#L85) is `plone.excludefromnavigation`, and as @ksuess correctly indicates, this should be used in the content type's profile XML.

In my opinion, the latter however is not a "Short Name" - since we already use this terminology when we talk about the ID of a content object. I would prefer simply using "Name" here, as this is how it is called in the zcml declaration.

Thanks for sharing the mockup of the proposal, looks fine to me. To answer my own question: would it be useful to include more info from the ZMI: this is probably overkill when the main function of this Control Panel page is simply to allow enabling and disabling behaviors. 

Sorry for the noise.

**Comment by jensens** [comment]
+1 for simply `Name` there. The term Short Name is historical and misleading today.

**Comment by pushkar707** [comment]
Hi Steve,

I would like to take up this issue. I can add a table that contains short names column in UI. Can you assign this issue to me?

**Comment by stevepiercy** [comment]
@mtrebron @ksuess @jensens now that we have @pushkar707 interested to work on this, let's summarize the foregoing discussion with a revised mockup. I have replaced "Short Name" with "Name".

| Title | Name | Description |
|-|-|-|
| 🔲  Allow discussion | `plone.allowdiscussion` | Allow discussion on this item |
| 🔲  Basic metadata | `plone.basic` | Adds title and description fields. |

Could I get an OK to proceed with this revised mockup, or additional suggestions for improvement?

Also who within the Classic UI team would be a good leader to review the PR for this week?

@pushkar707, before doing any work, please read and take appropriate action:

- https://plone.org/foundation/contributors-agreement
- https://docs.plone.org/develop/coredev/docs/index.html

Thank you!

**Comment by pushkar707** [comment]
@stevepiercy, thanks for letting me work over it, I am okay with the revised mockup. Though, I am facing problems in executing the code in my local environment.

 I couldn't find any guide about development in the readme of the project. Can you provide me with the instructions to setup the project locally, and then I can start working over it.

**Comment by stevepiercy** [comment]
@pushkar707 https://6.docs.plone.org/install/index.html

**Comment by ksuess** [comment]
> @mtrebron @ksuess @jensens now that we have @pushkar707 interested to work on this, let's summarize the foregoing discussion with a revised mockup. I have replaced "Short Name" with "Name".
> Title 	Name 	Description
> 🔲 Allow discussion 	`plone.allowdiscussion` 	Allow discussion on this item
> 🔲 Basic metadata 	`plone.basic` 	Adds title and description fields.
> 
> Could I get an OK to proceed with this revised mockup, or additional suggestions for improvement?
> 
> Also who within the Classic UI team would be a good leader to review the PR for this week?
> 
> @pushkar707, before doing any work, please read and take appropriate action:
> 
>     * https://plone.org/foundation/contributors-agreement
> 
>     * https://docs.plone.org/develop/coredev/docs/index.html
> 
> 
> Thank you!

I would like to see the package name where the behavior is defined.

**Comment by stevepiercy** [comment]
> I would like to see the package name where the behavior is defined.

Do you mean as a fourth column in the table mockup?

**Comment by stevepiercy** [comment]
Added! However I have no idea where or how to find the package names for all the behaviors. Where would I begin?

## Behaviors

| Title | Name | Description | Package Name |
|-|-|-|-|
| 🔲  Allow discussion | `plone.allowdiscussion` | Allow discussion on this item | unknown |
| 🔲  Basic metadata | `plone.basic` | Adds title and description fields. | unknown |

**Comment by pushkar707** [comment]
@ksuess I saw the following links linked by you:
https://plone.org/foundation/contributors-agreement
https://docs.plone.org/develop/coredev/docs/index.html

I am fine with whatever you guys decide, you can let me know what more columns will be added, and then I will add it

**Comment by ksuess** [comment]
> Added! However I have no idea where or how to find the package names for all the behaviors. Where would I begin?
> ## Behaviors
> Title 	Name 	Description 	Package Name
> 🔲 Allow discussion 	`plone.allowdiscussion` 	Allow discussion on this item 	unknown
> 🔲 Basic metadata 	`plone.basic` 	Adds title and description fields. 	unknown

The page /@@behaviors is nourished here: https://github.com/plone/plone.app.dexterity/blob/1044ed22b00221e1c5fa8fc8ea4069a4ae2a30c4/plone/app/dexterity/browser/behaviors.py#L83-L118

The behavior registry entry `reg` has information about where to find the code.

**Comment by ksuess** [comment]
> @ksuess I saw the following links linked by you: https://plone.org/foundation/contributors-agreement https://docs.plone.org/develop/coredev/docs/index.html
> 
> I am fine with whatever you guys decide, you can let me know what more columns will be added, and then I will add it

@pushkar707 Am I right, that you asked two days before, how to install Plone? 
And now you want to contribute? I recommend to have a look at and take some time reading and experimenting with https://training.plone.org/ and https://6.docs.plone.org/. Get familiar with Plone and then feel free to ask questions about Plone in our forum https://community.plone.org/. Enjoy!

**Comment by pushkar707** [comment]
@ksuess I was just trying to install Plone right now, after following all the steps given in the documentation, I am encountering following error:

Frontend codebase:
 - Installing @plone/generator-volto@6.2.0
 - Generate frontend application with @plone/volto 16.5.0
Traceback (most recent call last):
  File "C:\Users\bansa\AppData\Local\Temp\tmpovifvz5q.py", line 167, in <module>
    main()
  File "C:\Users\bansa\AppData\Local\Temp\tmpovifvz5q.py", line 144, in main
    prepare_frontend(
  File "C:\Users\bansa\AppData\Local\Temp\tmpovifvz5q.py", line 113, in prepare_frontend
    os.rename(src, dst)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:\\Open source\\Plone\\my_project\\project-title\\frontend\\Makefile.default' -> 'E:\\Open source\\Plone\\my_project\\project-title\\frontend\\Makefile'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

**Comment by ksuess** [comment]
@pushkar707 This is an issue. 
For questions to Plone in general, please visit  https://community.plone.org/.

**Comment by stevepiercy** [comment]
> The page /@@behaviors is nourished here: https://github.com/plone/plone.app.dexterity/blob/1044ed22b00221e1c5fa8fc8ea4069a4ae2a30c4/plone/app/dexterity/browser/behaviors.py#L83-L118
> 
> The behavior registry entry `reg` has information about where to find the code.

I followed that to https://github.com/plone/plone.behavior/blob/master/plone/behavior/registration.py#L74, but I still don't see the package names. This appears to be more about how to register a package name, not what are the package names or where to find them.

**Comment by ksuess** [comment]
![image](https://user-images.githubusercontent.com/1144737/229519374-89f98473-0315-413c-897e-a2abc885422f.png)
This is a generated form. It is generated from schema build by https://github.com/plone/plone.app.dexterity/blob/1044ed22b00221e1c5fa8fc8ea4069a4ae2a30c4/plone/app/dexterity/browser/behaviors.py#L107

The description of the boolean field can be modified by adding the schema, which is received from `reg`.
Just inspect https://github.com/plone/plone.app.dexterity/blob/1044ed22b00221e1c5fa8fc8ea4069a4ae2a30c4/plone/app/dexterity/browser/behaviors.py#L83-L118 to see that each behavior is regitered with the following information ( example behavior 'volto.preview_image')

```
<BehaviorRegistration volto.preview_image at 4612948704
  schema: plone.volto.behaviors.preview.IPreview
  marker: plone.volto.behaviors.preview.IPreview
  factory: None
  title: Preview Image
  Preview image for listings
>
```

Which tells the developer, that he/she can find the code in package `plone.volto`

**Comment by ksuess** [comment]
And yes, that will not give you a table.

**Comment by stevepiercy** [comment]
I'm sorry, I still do not see where the package names exist in any of the code you cited. Do I have to run a debugger, logger, or something else to find the package names?

**Comment by pushkar707** [comment]
@ksuess, I will get back once I can install run plone in my local environment and understand its code structure.

**Comment by ksuess** [comment]
> I'm sorry, I still do not see where the package names exist in any of the code you cited. Do I have to run a debugger, logger, or something else to find the package names?

No, sorry, my poor explanation skills.
Please see https://github.com/plone/plone.app.dexterity/pull/363 can't better explain this. Feel free to modify according your gusto.

**Comment by stevepiercy** [comment]
@ksuess I think it has finally penetrated my thick skull. Please correct me if I am wrong.

By using this method, we can inspect each boolean field's registered behavior for the attributes we need to build a row of values in the table. Using the example registered object:

```
<BehaviorRegistration volto.preview_image at 4612948704
  schema: plone.volto.behaviors.preview.IPreview
  marker: plone.volto.behaviors.preview.IPreview
  factory: None
  title: Preview Image
  Preview image for listings
>
```

We get values for this behavior as follows.

- Title = `title` (Preview Image)
- Name = `BehaviorRegistration` object name (`volto.preview_image`)
- Description = Value after `title` (Preview image for listings). What is its key?
- Package Name = `schema` (`plone.volto`), obtained by splitting on `.behaviors` and getting the first value in the resulting list.

**Comment by ksuess** [comment]
> @ksuess I think it has finally penetrated my thick skull. Please correct me if I am wrong.
> 
> By using this method, we can inspect each boolean field's registered behavior for the attributes we need to build a row of values in the table. Using the example registered object:
> 
> ```
> <BehaviorRegistration volto.preview_image at 4612948704
>   schema: plone.volto.behaviors.preview.IPreview
>   marker: plone.volto.behaviors.preview.IPreview
>   factory: None
>   title: Preview Image
>   Preview image for listings
> >
> ```
> 
> We get values for this behavior as follows.
> 
>     * Title = `title` (Preview Image)
>     * Name = `BehaviorRegistration` object name (`volto.preview_image`)
>     * Description = Value after `title` (Preview image for listings). What is its key?
>     * Package Name = `schema` (`plone.volto`), obtained by splitting on `.behaviors` and getting the first value in the resulting list.

I aggree, that a table would be pretty solution. But this would mean to invest a lot of time. The view /@@behaviors is a form. A form is generated from it's schema. The schema (definition of fields, fieldsets, methods) is generated in this case by looping over all behaviors. The loop adds a boolean field per behavior.
If you insist in a table, then you would need to replace the default view of a form. That's possible, but needs a big effort. So I propose to take the PR like it is and maybe do some polishing, like replacing round brackets by square brackets or adding "package:". In my opinion the dotted name (like "plone.volto.behaviors.preview.IPreview") is absolutly fine. It does describe the path to the schema interface. That's what a devoloper needs to find the code.

**Comment by stevepiercy** [comment]
I had not considered that, but you're right. The HTML markup appears to come from https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/checkbox_input.pt

If we want to use a table, we would need significant changes, not just for a single row, but also for start and end of tables and a table header. Changes here would affect other places where this widget is used. That would be a huge waste of time, when all we really need is a display of the data.

How about this instead. Here's the generated markup of the 

```html
<div class="mb-3 field">
  <div class="widget">
    <div class="form-check" id="form-widgets-volto-preview_image">
      <input class="form-check-input single-checkbox-widget bool-field" id="form-widgets-volto-preview_image-0" name="form.widgets.volto.preview_image:list" type="checkbox" value="selected">
      <label class="form-check-label" for="form-widgets-volto-preview_image-0">
        <span class="label">Preview Image</span>
      </label>
    </div>
    <input name="form.widgets.volto.preview_image-empty-marker" type="hidden" value="1">
    <div class="form-text">Preview image for listings</div>
  </div>
</div>
```

Let's just change this:

```html
    <div class="form-text">Preview image for listings</div>
```

to this:

```html
    <div class="form-text">Preview image for listings. Name: volto.preview_image. Package: plone.volto.behaviors.preview.IPreview</div>
```

...which renders like this:

![Screen Shot 2023-04-04 at 3 14 23 AM](https://user-images.githubusercontent.com/102112/229761150-82d6802f-79cd-4527-a977-3051300d2bf9.png)

...and call it good.

**Comment by ksuess** [comment]
Designing the layout to be a table  does not need the amount of effort as I thought, as the behavior view has its own view template.
I drafted a solution in https://github.com/plone/plone.app.dexterity/pull/365.
Despite thinking this is a nice, satisfiying AND quick solution, and local tests are OK, CI tests fail with an error that is not comprehensible, at least for me.
It's a pitty…
![Page_—_Site](https://user-images.githubusercontent.com/1144737/233044885-2bc177c7-496c-4b97-a4f7-e03dd8c89fc8.png)
This would help developers to look up the name of the behavior to be applied and even help to find the behavior code.
