### ISSUE TITLE
Missing data-bundle attributes on javascript and styles resources.

### ISSUE THREAD

**Issue by aormazabal** [plone/Products.CMFPlone#3707]
## Abstract

Javascript and Styles Resources Plone 6 missing data-bundle attribute. 

## Motivation

Is useful to have these attributes in resources to filter them through Diazo rules. 
Sometimes you need to remove or show this resources, for styling motivations.

## Assumptions

It could be possible with the last change in webresource library. Webresource v.1.2

## Proposal & Implementation

Add attribute on Resource declaration

                PloneStyleResource(
                   ...,
                    **{'data-bundle': name}
                )

## Risks

Not found

**Comment by mauritsvanrees** [comment]
This is a minor improvement and does not need a PLIP in my opinion.
You have made a PR for this: https://github.com/plone/Products.CMFPlone/pull/3708
Should be green soon now, and then can be merged.

**Comment by aormazabal** [comment]
> This is a minor improvement and does not need a PLIP in my opinion. You have made a PR for this: #3708 Should be green soon now, and then can be merged.

Ok, thanks, so can I close this PLIP? Sorry, I'm newby contributing...

**Comment by mauritsvanrees** [comment]
No problem. Let's keep this open until your PR is merged.
