### ISSUE TITLE
Drop-downs in "Create a Plone site" cut part of the text

### ISSUE THREAD

**Issue by frapell** [plone/Products.CMFPlone#372]
![add-new](https://cloud.githubusercontent.com/assets/851006/6097529/c9cad5f6-af9f-11e4-8272-76558d445fce.png)

This is fixed If I replace in ++resource++plone-admin-ui.css
```
select {
    height: 40px;
    width: 200px;
}
```
With
```
select {
    height: auto;
    width: auto;
}
```

But I think this could break stuff somewhere else ?

**Comment by vangheem** [comment]
You should be fine changing that. plone-admin-ui.css is only used on pages like site creation, upgrade.

If you're worried, add a selector to it and make the change.

**Comment by vangheem** [comment]
fixed with: https://github.com/plone/Products.CMFPlone/commit/4ba47ba9e026f8bfe67928c1e8a3f6eaef276914
