### ISSUE TITLE
fs-contextInfo: TypeError: Missing.Value is not JSON serializable

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#374]
buildout.coredev as of 2015-02-09 with xmldirector.plonecore 0.3.6 installed.
I created a TTW content-type with a "XML Text" field. The folder contents view of object instance gives me:

@@plone_view/getIcon as been deprecated, you should use @@plone_layout/getIcon
2015-02-09 09:16:38 ERROR Zope.SiteErrorLog 1423469798.510.464006884293 http://demo.xml-director.info:8080/Plone/hello-w/@@fc-contextInfo
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.folder, line 568, in __call__
  Module json, line 243, in dumps
  Module json.encoder, line 207, in encode
  Module json.encoder, line 270, in iterencode
  Module json.encoder, line 184, in default
TypeError: Missing.Value is not JSON serializable

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone.app.content/commit/65d32843fa66e723afaab91e44d3faf9d7661568
