### ISSUE TITLE
JS error in plone-legacy bundle related to plone.app.discussion

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#375]
buildout.coredev as of 2015-02-09, I am receiving a JS error in the plone-legacy bundle (related to p.a.discussion?):

![out](https://cloud.githubusercontent.com/assets/594239/6103744/98c8f7fa-b047-11e4-85c4-b16761ef6787.png)
![out2](https://cloud.githubusercontent.com/assets/594239/6103745/98cc2b50-b047-11e4-9a5c-3a9fecbb28d5.png)

        /**********************************************************************
         * Edit a comment
         **********************************************************************/
	$("form[name='edit']").prepOverlay({
                cssclass: 'overlay-edit-comment',
                width: '60%',
		subtype: 'ajax',
		filter: '#content>*'
		})

**Comment by vangheem** [comment]
I think this is related to an ordering bug in the legacy import handler that hasn't been tackled yet. In this case, a js file gets included before the require legacy overlay helper js file--I think. https://github.com/plone/Products.CMFPlone/issues/275

I've confirmed this behavior.

**Comment by vangheem** [comment]
This should be fixed.

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.discussion/commit/ad3953f7942129e79cefbe792cfdc3fc4eca0d08
