### ISSUE TITLE
PluggableAuthService enumerates over all authentication plugins, even if user was already found

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#376]
actually, this issue should be filed for `Products.PluggableAuthService`, but it's not github and we are users of it, so i file it for CMFPlone.

when trying to authenticate credentials, all authentication plugins are queried for the user credentials. the docs say, it stops when the first user is found: https://github.com/do3cc/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/doc/framework_overview.stx#L85

but it's implemented differently: https://github.com/do3cc/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/PluggableAuthService.py#L595 - here the userinfo is added to a userids list, enumerating all activated authentication plugins.

with a admin user defined in in acl_user's source_users authentication plugin but also having a LDAP authentication plugin ordered after source_users, it would be convenient to not having to deal with LDAP connection timeouts, but being authenticated right away.

what's the purpose of having a list of user credentials to be authenticated anyways?

**Comment by gforcada** [comment]
:+1: we are having the same problem with a custom SSO integration that we have.

**Comment by rnixx** [comment]
This looks like an implementation flaw. It makes no sence to authenticate against a different user source if there's already a successful authentication. It makes sence for other PAS interfaces to union the results, i.e. user properties, but for authentication, first winning plugin should rule (and stop processing).

Anyways i fear that something will break if this behavior gets changed (it should be changed though)

**Comment by thet** [comment]
@saily @jensens @datakurre any thoughts from your side?

**Comment by bogdangi** [comment]
:-1: I try to be short to explain why I don't agree.

If user does email login and we have an another plugin like SSO plugin then:

SSO plugin authenticates user but if there are two or more users with same email:
- which user folder is going to be chooses?
- should we choose first one or any of them?
- if there is only one folder is this folder belongs to that user?

When there are two plugins SSO plugin only returns SSO user related data and emaillogin plugin returns plone user id and we can get user folder and user permissions and both of them are logged in.

**Comment by datakurre** [comment]
I agree with the others. It's hard to come up with any sane requirement for the current behavior. Yet, it would be nice to get the reasoning for that implementation from the original author.

**Comment by thet** [comment]
@bogdangi i dont fully understand. why should there be more users with the same email and how can they login using the same credentials? in my understanding, there should be exactly one user associated with a email, especially if it's used for logging in.
but probably i'm missing something about login workflows with SSO plugins.

regarding the annotation of the user object with permissions., groups and other data: for those PAS plugins, all of them should (or have to) iterated through.

**Comment by bogdangi** [comment]
@thet , imagine that you have emaillogin plugin and SSO email plugin.

```python
sso_user = {'email': 'user@email.com'}
plone_user = {'email': 'user@email.com', 'user_id': 'user'}
```

**in new implementation**:
you mapped users by emails,
it means:
- if SSO auth successful plugin **should** return user_id of exist user with the same email and **stops**
- if SSO auth unsuccessful it calls emaillogin plugin and so on … 

Then if externally (on SSO service) email was changed to 'some@email.com' and we have another user with the same email 'user@email.com' registered on SSO service, then this user is able to login and have the user permissions that is not expected to be given to her.

but **in old implementation**:

you didn't map users by emails,
it means:
- if SSO auth successful plugin returns SSO sessions id and **continue**
- if emaillogin auth successful it returns user_is and user folder and **continue** …

**Comment by jensens** [comment]
I close this here, if it is still a problem, please create an issue at https://github.com/zopefoundation/Products.PluggableAuthService
