### ISSUE TITLE
TinyMCE inserting image inline into text, makes text disappear 

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#3768]
### What I did:

insert an image inline into a text paragraph.

### What I expect to happen:

The text is split by the image.

### What actually happened:

The text is replaced by the image.

### What version of Plone/ Addons I am using:

Plone 6.0.3
It does not happen in 5.2

**Comment by pbauer** [comment]
I can confirm this. Also happens with images: When you add a image next to another image the original image-tag is removed.
