### ISSUE TITLE
We need to remove the plone.app.multilingual dependency

### ISSUE THREAD

**Issue by folix-01** [plone/Products.CMFPlone#3779]
The plone.app.multilingual dependency should be removed

**Comment by mauritsvanrees** [comment]
It looks like three things are needed:
- [x] Load it conditionally in `Products.CMFPlone`. https://github.com/plone/Products.CMFPlone/pull/3780
- [ ] Add it to the `install_requires` of the `Plone` egg.  Only needed on Plone 6.1, but I see no problem in doing that on the current master branch used on both 6.0 and 6.1.  We could branch away though.
- [ ] `plone.restapi` has a hard dependency on plone.app.multilingual and does not yet declare it.  This was no problem until now.
    - [ ] Quickest solution is to add `plone.app.multilingual` to the `install_requires` of `plone.restapi`, that would be fine as a start.
    - [ ] Better solution would be to make `plone.restapi` use `plone.app.multilingual` only conditionally: only import it and load zcml when the package is available.

**Comment by mauritsvanrees** [comment]
As far as I see, all is done.
