### ISSUE TITLE
WebDAV integration problems

### ISSUE THREAD

**Issue by d-maurer** [plone/Products.CMFPlone#378]
[Bad charset handing in PROPPATCH](https://github.com/zopefoundation/Zope/issues/21)

[PROPFIND violates XML-namespace](https://github.com/zopefoundation/Zope/issues/20)

PROPPATCH fails to call "index_object" (thus, the catalog is not updated after property changes via WebDAV).

**Comment by jensens** [comment]
since theres no plan to support webdav for know in py3 I close this.
