### ISSUE TITLE
Plone 5 i18n issues

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#379]
I need help to fix the following errors, or I won't be able to extract messages for translations.
https://docs.google.com/document/d/1duXEAsoCXp4u0Tp-KYmBjEtLWb_zi3xgKQVTobdCoyU/edit

**Comment by vincentfretin** [comment]
The errors from the google doc are fixed with some others. I have to check if the 394 removed messages are really removed or if there are templates with missing i18:domain="plone" like it was the case for plone.app.themeing controlpanel.pt.

See comments on https://github.com/plone/Products.CMFPlone/commit/72446991256ca9ed1f2df47edcc5a9e8e6bb6657 for the issue I have with i18ndude not recognizing the new Chameleon functionality for tal:attributes.

**Comment by vincentfretin** [comment]
Ok! We now have up to date po files in plone.app.locales master for Plone 5! Go translators!
For Plone 4.x, we now have a 4.3.x branch.

If you find any i18n issue, please create a new issue in the right package or in Products.CMFPlone if you don't know. Please add a cc @vincentfretin so I don't miss it.

**Comment by vangheem** [comment]
We also need to think about ways to detect translations in javascript...

**Comment by vangheem** [comment]
https://github.com/plone/mockup/blob/master/mockup/patterns/structure/pattern.js#L70

**Comment by vincentfretin** [comment]
How do the translate javascript library works. Is there a documentation somewhere?

**Comment by vincentfretin** [comment]
@vangheem You need a way to create a widgets.pot file in plone.app.locales master in the locales directory. I'll add the widgets domain in buildout coredev experimental/i18n.cfg to take care of the resynchronization of the po files.

**Comment by vincentfretin** [comment]
The i18n.js module in mockup try to call a plonejsi18n view on the server (or another name depending of the data-i18ncatalogurl attr on the body). I couldn't find this view. So I guess we have to implement it? It takes a domain and language parameters and have to return json.

**Comment by vangheem** [comment]
Here's a start for the widgets pot: https://github.com/collective/plone.app.locales/commit/7ab2218f65063d482e03d1266daecb16a6155ec8

plonejsi18n view is defined in plone.app.content

**Comment by vincentfretin** [comment]
I created the widgets.po files are in plone.app.locales
I tried to translate the "Cut" button in folder_contents. I translated the message in fr/LC_MESSAGES/widgets.po, restarted the instance and reloaded folder_contents. With Chromium, F12, Resources, Local storage, I have widgets-fr key and the translations in the value. Cool. But The button is not translated in the interface.

**Comment by vangheem** [comment]
Ahh, those are passed in directly. I'll remove the translation from widgets since those are passed in:

https://github.com/plone/plone.app.content/commit/1cae12f7f679af72291404bfb237a43a2e79fa76

**Comment by vincentfretin** [comment]
Hum, I resynced widgets and plone domains, removed the localstorage. I still see Cut instead of Couper in French.

**Comment by vincentfretin** [comment]
I found the problem, I'm fixing it.

**Comment by pbauer** [comment]
The plonejsi18n-view at ``plone.app.content.browser.i18n.i18njs._gettext_catalog`` gets the tranlation-catalogs and always uses the first one. Therefore you cannot override widget.po like all other po-files by putting a file of the same name with your overrides in your package.

**Comment by pbauer** [comment]
A todo would be to update the documentation on how to translate.
