### ISSUE TITLE
Error trying to create a control panel connected to content type

### ISSUE THREAD

**Issue by rileydog** [plone/Products.CMFPlone#3795]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)
Traceback:
Wayne Glover
Docent IMS

    [Home](http://184.168.30.89:8080/docentims)
    [News](http://184.168.30.89:8080/docentims/news)
    [Events](http://184.168.30.89:8080/docentims/events)
    [Users](http://184.168.30.89:8080/docentims/Members)
    [PMP Breakdown](http://184.168.30.89:8080/docentims/pmp-breakdown)

Search Site
[Advanced Search…](http://184.168.30.89:8080/docentims/@@search)

    [Home](http://184.168.30.89:8080/docentims)

We’re sorry, but there seems to be an error…

Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 390, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module zope.browserpage.simpleviewclass, line 44, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 58, in __call__
  Module zope.pagetemplate.pagetemplate, line 134, in pt_render
  Module Products.PageTemplates.engine, line 365, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 298, in render
  Module chameleon.template, line 214, in render
  Module chameleon.utils, line 20, in raise_with_traceback
  Module chameleon.template, line 190, in render
  Module 163f7c730b9774ad1e638ee38cb39e87, line 303, in render
  Module 4b33ef6a96f757276913c10b3dd4b720, line 921, in render_master
  Module 4b33ef6a96f757276913c10b3dd4b720, line 1581, in render_content
  Module 163f7c730b9774ad1e638ee38cb39e87, line 145, in __fill_main
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 221, in _eval
  Module Products.PageTemplates.Expressions, line 152, in render
  Module plone.app.portlets.browser.manage, line 303, in portal_type_icon
AttributeError: 'LayoutPolicy' object has no attribute 'getIcon'

 - Expression: "context/main_template/macros/master"
 - Filename:   ... ne/app/portlets/browser/templates/manage-content-type.pt
 - Location:   (line 5: col 23)
 - Source:     ... etal:use-macro="context/main_template/macros/master"
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7fe0b8975c90>
               options: {}
               args: ()
               nothing: None
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7fe0bcc82d50>
               request: <WSGIRequest, URL=http://184.168.30.89:8080/docentims/@@manage-content-type-portlets>
               view: <Products.Five.browser.metaconfigure.SimpleViewClass from /app/lib/python3.11/site-packages/plone/app/portlets/browser/templates/manage-content-type.pt object at 0x7fe0b4f0c150>
               context: <PloneSite at /docentims>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7fe0affcc6d0>
               here: <PloneSite at /docentims>
               container: <PloneSite at /docentims>
               root: <Application at >
               traverse_subpath: []
               user: <PloneUser 'wglover@docentims.com'>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7fe0b4a04aa0>
               loop: {}
               target_language: None
               translate: <function BaseTemplate.render.<locals>.translate at 0x7fe0af73cb80>
               macroname: 'master'
               attrs: {}

### What I Did:

1. from control panel, select "Content Settings"
2. Half way down, see "[Manage portlets assigned to this content type]"
3. select this

### What I expect to happen:
1. I would expect it to take me to the list of portlets

### What actually happened:
1. get the error shown in trace back.
2.  Note: tried for several content types including standard plone CTs and Dexterity types i created

**Comment by davisagli** [comment]
@rileydog Thanks for the bug report. I was able to reproduce the problem and submitted a fix in https://github.com/plone/plone.app.portlets/pull/177
