### ISSUE TITLE
Registering and logging in looses current page

### ISSUE THREAD

**Issue by adrigen** [plone/Products.CMFPlone#380]
While logging in using the login form returns the user to the page they were on, if the user registeres and then uses the login (immediately) button, they are taken to the home page of the site.

**Comment by gforcada** [comment]
Thanks for reporting, which version of Plone are you using? 4.2.6? 4.3.4? 5.x? Python version? Any relevant add-ons that my be of interest regarding this bug?

**Comment by adrigen** [comment]
4.3.3, Python 2.7

**Comment by jensens** [comment]
With plone.login merge in 5.2 here a lot changed, also behavior wise. So this is outdated here.
