### ISSUE TITLE
bug: contributing guidelines page not found

### ISSUE THREAD

**Issue by ydv-ankit** [plone/Products.CMFPlone#3802]
### What I did:
clicking on "Developer Guidelines" redirect to link https://6.docs.plone.org/develop/coredev/docs/guidelines.html which shows page not found.

1. On repo, open [contributing.md](https://github.com/plone/Products.CMFPlone/blob/master/CONTRIBUTING.md) file
2. click on "Developer Guidelines"
3. shows "page not found" as this bug reports

### What I expect to happen:
Link should redirect where contribution guidelines are present

### What actually happened:
redirects to link that shows "page not found"

### What version of Plone/ Addons I am using:
master (latest) branch

**Comment by mauritsvanrees** [comment]
Those docs need to be moved, this is part of https://github.com/plone/documentation/issues/1486

Workaround is to add `5.` in front of the url:
https://5.docs.plone.org/develop/coredev/docs/guidelines.html

**Comment by ydv-ankit** [comment]
so should we use `5` instead of `6` in url

**Comment by mauritsvanrees** [comment]
I have changed the link to 5.docs.plone.org.  A temporary solution, as this document should live in the new docs as well, but at least the url then works.
Done in packages `Plone` and `Products.CMFPlone`, branches 6.0.x and master.
Thanks for your report!
