### ISSUE TITLE
profile metadata.xml from 6.0.x branch and master out of sync?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3809]
@mauritsvanrees might it be that the tests failures on [Jenkins PR jobs for Plone 6.1](https://jenkins.plone.org/job/pull-request-6.1-3.11/128) are related to `Products.CMFPlone`'s `metadata.xml` being at version `6017` while `plone.app.upgrade`'s `metadata.xml` being at version `6018`?

Note that for `Products.CMFPlone`s branch `6.0.x` `metadata.xml` is at `6018`.

😵‍💫

**Comment by mauritsvanrees** [comment]
Ah, yes, that should be updated as well.

Okay, the metadata on 6.1 should be 6100, but that only makes sense once we have real differences, and there is a `v61` directory in `plone.app.upgrade`.
So for now using the same metadata version is fine.
