### ISSUE TITLE
Circular dependency between p.a.z3cform and p.a.vocabularies

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3816]
Seems that we have still a few dependency cycles around :-/

According to @petschki we have one between `plone.app.vocabularies` and `plone.app.z3cform`

**Comment by petschki** [comment]
Details: if I add `plone.app.vocabularies` as `install_requires` to p.a.z3cform, this is the circle:

```
found edge plone.app.vocabularies -> plone.namedfile
found edge plone.namedfile -> plone.schemaeditor
found edge plone.schemaeditor -> plone.app.z3cform
```

I've found the following imports:

- `plone.app.z3cform.widgets.singlecheckbox` -> `from plone.app.vocabularies.terms import TermWithDescription`
- `plone.app.vocabularies.images` ->`from plone.namedfile.interfaces import IAvailableSizes`
- `plone.namedfile.editor` -> `from plone.schemaeditor.fields import FieldFactory`
- `plone.schemaeditor` -> `from plone.app.z3cform.interfaces import IDateField, IDatetimeField`

The last line could IMHO safely be changed to `from zope.schema.interfaces import IDate, IDatetime` which would untangle this circle ... I'll give it a try...

**Comment by gforcada** [comment]
@mauritsvanrees not too pressuring, but I would very much like to have a way to update https://dist.plone.org/release/6.0-dev/constraints.txt somehow so when these fixes happen, we can see them _soon_ on other packages that rely on that 🚀 

Automating these processes would be great 🍀

**Comment by mauritsvanrees** [comment]
@gforcada If you know what you are doing (which is usually the case ;-)) this would be the way:

```
$ ssh dist.plone.org
$ cd /var/www/dist.plone.org/release/6.0-dev/
# edit constraints.txt and versions.cfg
```

Or grab a copy, edit them locally, and scp them of course.

But you would need access to the dist.plone.org server.  If @fredvd is still around, you should be able to give you access, or point you to someone else from the A/I team who can.
I am happy for someone to grant you access.

Okay, this is not "automating these processes". ;-)
But it may help get something unstuck if a release manager decides to go on vacation for a week, for example me tomorrow. :-D
In a pinch, you can also ask Eric Steele to update a version pin there.

(If you get ssh access from someone and still can't get on the server, ask them which port you should use.)

**Comment by petschki** [comment]
This is fixed
