### ISSUE TITLE
Cancel Adding page without title, not "possible" anymore (Classic)

### ISSUE THREAD

**Issue by espenmn** [plone/Products.CMFPlone#3819]
**Regression**
 
Somewhere from 6.0 to 6.0.5, Adding a new page can not be cancelled anymore, unless you add a title (or move the cursor to another field).

### What I did:

- added new page and clicked on cancel.

### What I expect to happen:
- Creation of page should be cancelled, and 'user returned to former URI)

### What actually happened:
- Cancel is prevented due to validation of Title.
- Since the 'Cancel' button is at the bottom of the screen, error message will not be visible to the user, and they might not understand 'why they cant cancel'. 

### What version of Plone/ Addons I am using:
Plone 6.0.5, No add-ons, problem might come from Barceloneta theme.

**Comment by petschki** [comment]
This is fixed ... see the `plone.staticresources` versions here https://github.com/plone/mockup/issues/1259 or upgrade to Plone 6.0.6
