### ISSUE TITLE
ATContentTypes/plone.app.collection install problem on Plone 5.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#382]
ATContentTypes is already an optional dependency in Plone 5. plone.app.collection should be optional as well.

I also suspect that some of the test isolation problems are related to plone.app.collection.

https://github.com/plone/buildout.coredev/commit/019cef11f34d00ff3adce357a7f92a3da89f7121

**Comment by tisto** [comment]
Ok. I think I got that one wrong. plone.app.collection is already optional. Though, installing plone.app.collection or ATContentTypes in Plone 5 ( buildout.coredev ) leads to the following traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 196, in __call__
  Module Products.GenericSetup.tool, line 365, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plone.app.collection:default
  Module Products.GenericSetup.tool, line 1119, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1030, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 225, in importTypesTool
  Module Products.GenericSetup.utils, line 838, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 834, in importObjects
   - __traceback_info__: types/Collection
  Module Products.GenericSetup.utils, line 509, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 60, in _importNode
  Module Products.GenericSetup.utils, line 730, in _initProperties
ValueError: undefined property 'content_meta_type'
```

**Comment by tisto** [comment]
It seems this error occurs when we a Collection is already registered (e.g. from plone.app.contenttypes) and we try to override that type with the AT-based Collection type. Since we are not going to support the use case to install a fresh Plone 5 and then install ATContentTypes, we can just ignore it. We should also hide ATContentTypes and plone.app.collection from the quickinstaller in Plone 5.

**Comment by vangheem** [comment]
Here is the PR for hiding ATContentTypes: https://github.com/plone/Products.CMFPlone/pull/671

**Comment by vangheem** [comment]
Decided to change Products.ATContentTypes instead: https://github.com/plone/Products.ATContentTypes/pull/22

**Comment by gnafou** [comment]
( from #635 ) 
So if i understand right, i should be able to upgrade a 4.x site with AT types to plone 5., but unable to create a new 5. site with AT ??

**Comment by vangheem** [comment]
correct.

**Comment by vangheem** [comment]
You can create a new site and make it so Archetypes based content types work; however, you can not replace the shipped plone.app.contenttypes with ATContentTypes.

**Comment by gnafou** [comment]
okok ... is there an easy way to migrate thousands of AT documents to Dexterity ?  these documents are fairly simple contents

**Comment by vangheem** [comment]
https://pypi.python.org/pypi/plone.app.contenttypes check out the migration section.

**Comment by pbauer** [comment]
That issue should be fixed in https://github.com/plone/plone.app.contenttypes/commit/34916e59ce691a388ab67de95f6eb18e521342d4

**Comment by mauritsvanrees** [comment]
Related: https://github.com/plone/plone.app.collection/pull/29
