### ISSUE TITLE
Best practices to update registry records?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3827]
At work whenever we have change our `profiles/default/*.xml` we create a corresponding upgrade step to update those files on the Plone site.

Mostly it boils down to this function:

```python
def update_gs_profile(profile_id=PROFILE_ID, tool=None):
    """Imports the given tool Generic Setup step from the given profile."""
    if tool is None:
        logger.critical('Needs a tool to run!')

    setup = api.portal.get_tool('portal_setup')
    setup.runImportStepFromProfile(profile_id, tool)
```

i.e. given a GS profile and a tool to update, it updates the configuration for that profile.

For `registry.xml` we have:

```python
def update_gs_registry(profile_id=PROFILE_ID):
    """Imports registry.xml setup step."""
    update_gs_profile(profile_id=profile_id, tool='plone.app.registry')
```

What I found interesting is that given such a `registry.xml` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<registry>
  <records interface="freitag.one.interfaces.ISomeSettings" />
  <records interface="freitag.one.interfaces.ISomeMoreSettings" />
  <record name="freitag.one.a-url">
    <field type="plone.registry.field.URI">
      <title>A URL</title>
    </field>
    <value>https://example.org</value>
  </record>
</registry>
```

Running the `update_gs_registry` function mentioned above installs the new registry record `freitag.one.a-url` with the expected value.

I can now, happily go to the registry control panel and update the setting, all good and nice ✨ 

__Now, comes the bug:__ 🐞 

If I re-run the upgrade step (i.e. call again `update_gs_registry`) the value is reset to the one coming from `registry.xml`, my manual changes are lost!

Ok, looking at `plone.app.registry` documentation I can _fix_ that by adding a `purge="false"` attribute on `value`, i.e. `<value purge="false"></value>`.

Still not, it gets overwritten again 🐞 

So, __what are the best practices when having this sort of registries?__ Never to call `runImportStepFromProfile` on it? 🤔 

Interestingly enough, for the interfaces `freitag.one.interfaces.ISomeSettings` that define some records, they are not overwritten...

__At least that feels inconsistent to me.__

I was expecting that if a registry already exists is left alone, or that at least, you can hint GenericSetup to _ignore_ the new value (by providing this `purge` as mentioned on the documentation)...

**Comment by ale-rt** [comment]
Maybe related https://github.com/plone/Products.CMFPlone/issues/1375

**Comment by ale-rt** [comment]
I have very little time, but AFAIK the solution in many case is to set the value through Python code

**Comment by mauritsvanrees** [comment]
I agree with what David said.

> Perhaps it could also be used for the purpose you have in mind, to control whether an existing value should be overwritten. But I think it would be less confusing if that was a new setting with a new name, maybe overwrite_existing="false".

Years ago, when the configuration registry was still being developed, I had hoped that something like this would be done, but it never happened, except that you can register an interface without overwriting anything.

BTW, I would write the upgrade in zcml like this:

```
  <genericsetup:upgradeDepends
    source="1000"
    destination="1001"
    profile="your.package:default"
    title="Update registry"
    import_steps="plone.app.registry"
    />
```

**Comment by gforcada** [comment]
Thanks! now I see that there was indeed some misunderstanding from my side 😊
