### ISSUE TITLE
Check if deletion by acquisition is still a problem.

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#383]
Original Ticket:
https://dev.plone.org/ticket/13603

copied here:
If a user "deletes" the same item twice (ex.: having two different tabs open and not realising it's already been deleted) any higher level item with the same short name will be deleted without trace. 

Steps to reproduce on a default Plone4.1 site:
 * create a folder 'test' on the root
 * crate another item 'test' somewhere else deeper in the site
 * open '''folder_contents''' with the item 'test' in two different tabs/browsers
   * fixed in in https://github.com/plone/Products.CMFPlone/commit/6d6710728b35b97e2f328c454c8688346612b1e1
 * or open the item 'test' in two different tabs/browsers and delete via '''Actions - Delete'''
 * select and delete 'test' consequently from both tabs
 * 'test' folder on root will be gone.

Undo logs would look as if the same item has been deleted twice:

    /Plone/folder_delete Deleted test (/Plone/f1/f2/test) by admin 2013-05-27 14:30:07
    /Plone/folder_delete Deleted test (/Plone/f1/f2/test) by admin 2013-05-27 14:29:55
    /Plone/portal_factory Edited ATDocument test at http://xxx:8080/Plone/f1/f2/test by admin 2013-05-27 14:29:18
    /Plone/portal_factory Edited ATFolder f2 at http://xxx:8080/Plone/f1/f2 by admin 2013-05-27 14:29:03
    /Plone/portal_factory Edited ATFolder f1 at http://xxx:8080/Plone/f1 by admin 2013-05-27 14:28:55
    /Plone/portal_factory Edited ATFolder test at http://xxx:8080/Plone/test by admin 2013-05-27 14:28:42

There have been a problem in 4.x fixed with #198, but since the script was turned into a browserview with #84 its not clear if the problem resists in 5.0

Todos:

- [x] tests added in 80b687fa must be rewritten for 5.0
- [x] if the problem still exists fix it in 5.0

**Comment by cewing** [comment]
I can verify that this is in fact a problem.  Here are the actions I took to reproduce it:

1.  Created a brand-new vanilla Plone site from the 5.0 branch of buildout.coredev
2.  Created a page with the id `test` at the site root
3.  Created a folder `container-one` at the site root
4.  Created a folder `container-two` inside the `container-one` folder
5.  Created a page with the id `test` inside the `container-two` folder
6.  Opened two browser tabs on the `/container-one/container-two/test` page
7.  Deleted the page using the actions menu in the first tab
8.  Deleted the page using the actions menu in the second tab as well.
9.  Observed that the `test` page at the site root was deleted instead.

**Comment by cewing** [comment]
I can also confirm that for the folder view delete this is *not* a problem.  I will add a test to demonstrate this as well, to help protect against possible regressions.

**Comment by cewing** [comment]
@jensens, I've written tests to demonstrate the working and failing scenarios and committed a fix for the scenario that was failing.  Hope that will help to close this issue

**Comment by jensens** [comment]
merged plone/plone.app.content#28 which fixes this issue, thx @cewing!
