### ISSUE TITLE
404-page pretends that user is not authenticated

### ISSUE THREAD

**Issue by umlaeute** [plone/Products.CMFPlone#385]
When i log in my site (e.g. http://myplone.org), I get a visual feedback that I _am_ logged in (e.g. links to personal items, no more <kbd>log in</kbd> link.

However, when I then go to a non-existing page on my site (e.g. http://myplone.org/blabla) and get a `404` page (as expected), all clues that i am still logged in are gone: suddenly there is even a <kbd>log in</kbd> button again!

this seems to affect all versions of plone that i know. tested with:
- CMFPlone 1.0.4
- Plone 2.1.3 (and 2.1.4)
- Plone 2.5.3-final
- Plone 4 (i have been told and could not confirm myself)
- Plone 5.0b1.dev0 (5004)

what is the reasoning behind this behaviour, and would you consider changing it?

**Comment by frisi** [comment]
never noticed that and tried out on plone 4.3.4 - same probleme there

**Comment by jensens** [comment]
i think this is by intend. an error page should be as simple as possible. but it depends on the error code: for a 404 e.g. in an intranet  the current behavior is probably not what we want.

**Comment by davisagli** [comment]
I don't think this is intentional. It's just a side effect of the fact that NotFound is usually raised during traversal, before authentication has taken place.

**Comment by jensens** [comment]
I dont think its worth to fix this.
