### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3852]
Officially support Python 3.12 in Plone 6.1

- [x] Update versions in coredev (https://github.com/plone/buildout.coredev/pull/890)
- [x] Create a jenkins job for 3.12
- Fix failing tests in plone.restapi and plone.api
  - [x] https://github.com/plone/plone.api/pull/514
  - [x] https://github.com/plone/plone.restapi/pull/1719
- [x] update mr.roboto mapping to trigger the 3.12 jobs for PRs targeting Plone 6.0 and 6.1
- [x] Update setup.py
- [ ] Update Documentation
- [x] Update matrix-settings
- [ ] Update mr.bob for 3.12 (https://github.com/collective/mr.bob/pull/98)
- [ ] Update plone.reload for 3.12 (https://github.com/plone/plone.reload/pull/18)

**Comment by gforcada** [comment]
I updated the python ansible role to add python 3.12 on it and, _live_, our jenkins nodes are getting it installed as the search panel at the plone conference is happening :)

**Comment by gforcada** [comment]
Jobs are created for Plone 6.0 and 6.1:

- https://jenkins.plone.org/view/All/job/plone-6.0-python-3.12/
- https://jenkins.plone.org/view/All/job/plone-6.0-python-3.12-robot-chrome/
- https://jenkins.plone.org/view/All/job/pull-request-6.0-3.12/

- https://jenkins.plone.org/view/All/job/plone-6.1-python-3.12/
- https://jenkins.plone.org/view/All/job/plone-6.1-python-3.12-robot-chrome/
- https://jenkins.plone.org/view/All/job/pull-request-6.1-3.12/

I did not add them to the main tab, as they are probably not stable 🍀

**Comment by gforcada** [comment]
@mauritsvanrees do we want to officially support Python 3.12 on 6.0, or that's only for 6.1? 🤔 I guess both, but asking just in case 🍀

**Comment by gforcada** [comment]
Support on `buildout.coredev` for branch `6.0` is already merged 🎉  we need to port those version pins to `6.1` branch as well though.

What about Jenkins and mr.roboto? should we already enforce 3.12 support for any new PR once the `buildout.coredev` version pins are added? 🤔

**Comment by mauritsvanrees** [comment]
Zope is not officially supporting 3.12 yet.  Biggest blocker is review of `RestrictedPython`.  I think we should only declare preliminary support in Plone until that is resolved.

I would say on 6.0 we keep testing everything on Python 3.8 and 3.11.  3.12 can be another weekly job.
For 6.1 we could test on 3.8 and 3.12 all the time, and have 3.11 as one of the weekly jobs.

**Comment by gforcada** [comment]
@mauritsvanrees I adjusted Jenkins jobs accordingly and updated `mr.roboto` to set the hooks on new PRs.

Hopefully I stitched everything correctly 😅

**Comment by mauritsvanrees** [comment]
Thanks!

**Comment by gforcada** [comment]
Seems that not, I forgot the 6.1 on 3.8 on jenkins, but not on mr.roboto, so fortunately, I realized it while trying to fix https://github.com/plone/plone.app.content/pull/262 😄
