### ISSUE TITLE
Circular dependency between p.a.content and plone.app.dexterity

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3858]
That's an interesting one 😄 

## plone.app.dexterity

It uses the following from `plone.app.content`:

```
plone/app/dexterity/behaviors/configure.zcml:67:      provides="plone.app.content.interfaces.INameFromTitle"
plone/app/dexterity/behaviors/filename.py:1:from plone.app.content.interfaces import INameFromTitle

plone/app/dexterity/tests/namefromtitle.txt:15:plone.app.content (normally this would be done via Generic Setup)::
plone/app/dexterity/tests/namefromtitle.txt:17:  >>> fti.behaviors = ('plone.app.content.interfaces.INameFromTitle',
plone/app/dexterity/tests/test_constrains.py:1:from plone.app.content.browser.constraintypes import IConstrainForm
plone/app/dexterity/tests/test_permissions.py:1:from plone.app.content.browser.vocabulary import VocabularyView
```

i.e. basically __a single interface__ (`INameFromTitle`) and on tests, where is _fair game_ IMHO.

## plone.app.content

It uses the following from `plone.app.dexterity`:

```
plone/app/content/browser/contents/properties.py:4:from plone.app.dexterity.behaviors.metadata import ICategorization
plone/app/content/browser/file.py:3:from plone.app.dexterity.interfaces import IDXFileFactory

plone/app/content/tests/test_contents.py:39:            "plone.app.dexterity.behaviors.metadata.IBasic",
plone/app/content/tests/test_contents.py:82:            "plone.app.dexterity.behaviors.metadata.IBasic",
plone/app/content/tests/test_contents.py:165:            "plone.app.dexterity.behaviors.metadata.IBasic",
plone/app/content/tests/test_contents.py:266:            "plone.app.dexterity.behaviors.metadata.IBasic",
plone/app/content/tests/test_contents.py:349:        type1_fti.behaviors = ("plone.app.dexterity.behaviors.metadata.IBasic",)
plone/app/content/tests/test_contents.py:358:        type2_fti.behaviors = ("plone.app.dexterity.behaviors.metadata.IBasic",)
plone/app/content/tests/test_widgets.py:683:        # the next calls plone.app.dexterity.factories and does a
plone/app/content/tests/test_widgets.py:700:        # the next calls plone.app.dexterity.factories and does a
```

So, two imports mainly: `ICategorization` and `IDXFileFactory`, and again, some tests...

## Proposal

`plone.app.content` is meant to be _on top_ of `plone.app.dexterity`, thus a solution can be:

- [x] https://github.com/plone/plone.base/pull/51: move `INameFromTitle` interface from `plone.app.content` to `plone.base`
- move tests from `plone.app.dexterity` that import `plone.app.content` to `plone.app.content` itself (the tests are actually testing functionality from `plone.app.content`)
  - [x] https://github.com/plone/plone.app.content/pull/270
  - [x] https://github.com/plone/plone.app.dexterity/pull/378
- rename the `INameFromTitle` imports on both `plone.app.content` and `plone.app.dexterity` to use `plone.base`, and add a deprecation warning in `plone.app.content`
  - [ ] https://github.com/plone/plone.app.dexterity/pull/379
  - [ ] https://github.com/plone/plone.app.content/pull/271

**Comment by davisagli** [comment]
In my opinion plone.app.content belongs above plone.app.dexterity. plone.app.dexterity is the core content type framework, while plone.app.content is mostly the Classic UI folder contents view. This can probably be resolved by moving INameFromTitle to plone.base, and any other frontend-agnostic functionality from plone.app.content to either plone.app.dexterity or Products.CMFPlone.

**Comment by gforcada** [comment]
Oh, thanks, yes, that makes more sense indeed.

Other than `INameFromTitle` the other imports on `plone.app.dexterity` are on tests that actually could be moved directly on `plone.app.content` itself, as they are testing the functionality of `plone.app.content` 🤔 

https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/tests/test_permissions.py

https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/tests/test_constrains.py

**Comment by gforcada** [comment]
@davisagli @jensens @mauritsvanrees how does the `Proposal` section above in the first comment look like? On my head it makes all sense, and it can be done in small PRs that should not break Jenkins at any point 🍀

**Comment by mauritsvanrees** [comment]
Sounds good to me.
