### ISSUE TITLE
List of portal types in content-type filter unsupported

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3860]
Plone 6.0.7

The list of available portal types in the filter should/must be sorted alphabetically.

Talking of sorting: the standard `sort()` or `sorted()` method should not be applied because they do not deal corr

ectly with unicode strings in the context of the configured locale using `pyuca`:

https://github.com/jtauber/pyuca

![d0f18fc9-40a1-465b-a7db-d5b68cdfb8a8](https://github.com/plone/Products.CMFPlone/assets/594239/42b4b802-0f91-42a9-8d58-812bdb36496b)

**Comment by Tushar-kalsi** [comment]
Hi @zopyx  Can i get the opportunity to implement Pyuca for Filters mentioned above ??

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone.app.vocabularies/pull/93
