### ISSUE TITLE
Remove Products.CMFCalendar.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#387]
@thet Products.CMFCalendar should be removed in Plone 5, right?

**Comment by thet** [comment]
Right. I thougt it aready is removed? CMFPlone doesn't depend on it anymore, but a quick grep in my buildout.coredev directory gave me these results:
```
src/Products.PloneTestCase/Products/PloneTestCase/setup.py:27:    ZopeTestCase.installProduct('CMFCalendar', quiet=1)
tests.cfg:198:    Products.CMFCalendar
```
is the "from PloneTestCase to plone.app.testing" migration already finished, so that PloneTestCase can be removed?

**Comment by tisto** [comment]
@tomgross I lost a bit track of the plone.app.testing migration (sorry). Did I merge all your work? Can you give us a quick heads up?

**Comment by tomgross** [comment]
Actually I am unsure about the state myself. I think most branches were
merged at some point but some were reverted. CMFCalendar can be removed
after Archetypes branch is merged. It is a dependency of CMFTestCase.
Timo Stollenwerk <notifications@github.com> schrieb am Di., 3. März 2015 um
09:23:

**Comment by tisto** [comment]
@tomgross looking at https://raw.githubusercontent.com/plone/buildout.coredev/tomgross-noptc2/sources.cfg I just see branch=master. No ptc removal branches. Do you we have a list of all pkg that you worked on somewhere, so we can check if everything has been merged?

**Comment by tisto** [comment]
Ok. I will look into the Archetypes pull request and try to merge it: https://github.com/plone/Products.Archetypes/pull/42

**Comment by tisto** [comment]
CMFCalendar is gone as far as I can tell. Will close the issue.
