### ISSUE TITLE
Keywords with "&" not possible

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#3874]
in Classic-UI its not possible to use keywords (tags) containing "&". See screencast:

https://github.com/plone/Products.CMFPlone/assets/511761/b8bbd098-ea79-487a-9893-937779eea354

**Comment by MrDurvesh11** [comment]
Hi Sir,
I've looked into the issue, and I believe I have a solution. Can I resolve this issue.
Thanks,

**Comment by stevepiercy** [comment]
@MrDurvesh11 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by petschki** [comment]
fixed here https://github.com/plone/plone.app.content/pull/273
