### ISSUE TITLE
ptc to plone.app.testing

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#388]
@tisto  The following products need some love in migrating to plone.app.testing:

Products.PloneLanguageTool (still a CMFTestCase dependency :( )
~~plone.app.blob~~
~~plone.app.folder~~
Products.ATContentTypes
~~plone.openid~~
Products.ResourceRegistries
plone.app.controlpanel
~~plone.outputfilters~~
~~plone.app.upgrade~~

All of these were ready (except ATContentTypes) at some point but some diverged meanwhile. Even some of my branches were deleted. This is frustrating ...

**Comment by thet** [comment]
if the branches were deleted via the github delete branch button after a merge, it should be able to restore it again...

**Comment by gforcada** [comment]
I should take part of the blame on this... I reverted 4 or 5 branches when everything was merged to bring back jenkins to a green build.

Could we follow a PLIP route and create a cfg on buildout.coredev plips folder so that we can keep track of the progress in a sane way? I can understand how frustrating it is, but you can also understand that having a broken build and weird things going on (having just half of the tests running, etc) is not a desirable situation...

**Comment by tisto** [comment]
Hey @tomgross, I understand your frustration. Sorry! I think there were quite a few things that went wrong. As @gforcada wrote, we really have to be more careful if we are dealing with pull requests that are that complex.

I created a PLIP job:

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/

I will add all the branches you mentioned above and make sure we restore those who have been deleted. My main concern right now is the alltests problem I described here https://github.com/plone/Products.Archetypes/pull/42.

**Comment by tisto** [comment]
The PLIP job is green (because we did not add any packages yet):

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/

I would propose to go step by step, adding one package at a time (low hanging fruits first).

**Comment by tisto** [comment]
Adding plone.openid works: http://jenkins.plone.org/view/PLIPs/job/plip-ptc/4/

**Comment by tisto** [comment]
I was wrong. Forgot to add plone.openid to auto-checkout. plone.openid and plone.app.openid run in full test isolation now. plone.app.openid still has test failures (related to the plone.openid changes):

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/8/console

```
#### Running tests for plone.app.openid ####
Running plone.app.openid.testing.PloneAppCollectionLayer:Integration tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.288 seconds.
  Set up plone.app.testing.layers.PloneFixture /home/jenkins/.buildout/eggs/setuptools-5.8-py2.7.egg/pkg_resources.py:1032: UserWarning: /home/jenkins/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
in 11.505 seconds.
  Set up plone.app.openid.testing.PloneAppOpenidLayer Could not install product plone.app.openid
in 0.114 seconds.
  Set up plone.app.openid.testing.PloneAppCollectionLayer:Integration in 0.000 seconds.


Error in test testOnlyOpenIdInstalled (plone.app.openid.tests.test_view.TestOpenIdView)
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/tests/test_view.py", line 42, in testOnlyOpenIdInstalled
    'profile-plone.app.openid:default')
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 365, in runAllImportStepsFromProfile
    blacklisted_steps=blacklisted_steps)
   - __traceback_info__: profile-plone.app.openid:default
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1119, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1030, in _doRunImportStep
    return handler(context)
   - __traceback_info__: ploneopenid-various
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/setuphandlers.py", line 58, in importVarious
    createOpenIdPlugin(site, out)
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/setuphandlers.py", line 19, in createOpenIdPlugin
    acl.manage_addProduct["plone.openid"].addOpenIdPlugin(
AttributeError: addOpenIdPlugin



Error in test test_OpenIdInstalled (plone.app.openid.tests.test_view.TestOpenIdView)
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/tests/test_view.py", line 31, in test_OpenIdInstalled
    'profile-plone.app.openid:default')
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 365, in runAllImportStepsFromProfile
    blacklisted_steps=blacklisted_steps)
   - __traceback_info__: profile-plone.app.openid:default
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1119, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1030, in _doRunImportStep
    return handler(context)
   - __traceback_info__: ploneopenid-various
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/setuphandlers.py", line 58, in importVarious
    createOpenIdPlugin(site, out)
  File "/home/jenkins/workspace/plip-ptc/src/plone.app.openid/plone/app/openid/setuphandlers.py", line 19, in createOpenIdPlugin
    acl.manage_addProduct["plone.openid"].addOpenIdPlugin(
AttributeError: addOpenIdPlugin

  Ran 3 tests with 0 failures, 2 errors and 0 skipped in 0.511 seconds.
Tearing down left over layers:
  Tear down plone.app.openid.testing.PloneAppCollectionLayer:Integration in 0.000 seconds.
  Tear down plone.app.openid.testing.PloneAppOpenidLayer in 0.003 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.098 seconds.
  Tear down plone.testing.z2.Startup in 0.007 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.
#### Finished tests for plone.app.openid ####

#### Running tests for plone.openid ####
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 13 tests with 0 failures, 0 errors and 4 skipped in 0.106 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
#### Finished tests for plone.openid ####
```

**Comment by tisto** [comment]
I fixed the plone.app.folder tests: http://jenkins.plone.org/view/PLIPs/job/plip-ptc/10/.

**Comment by tisto** [comment]
Merged packages:

- plone.app.blob: https://github.com/plone/plone.app.blob/commit/8d749a774137ca7ead779544db114ff01afc811d
- plone.app.folder: https://github.com/plone/plone.app.folder/commit/581739db2ab8a82d68d6a89df3e2e6bfbfd8651d
- plone.app.upgrade: https://github.com/plone/plone.app.upgrade/commit/3663cd3ec4f4163619b982ce38e5d7b08b6a3de4

No pull request:

- Products.ATContentTypes: https://github.com/plone/Products.ATContentTypes/tree/tomgross-ptc

Pull request with test failures:

- Products.Archetypes causes test failures: https://github.com/plone/Products.Archetypes/pull/42
- plone.openid causes test failures: https://github.com/plone/plone.openid/pull/7

Pull requests that require pending changes:

- plone.outputfilters requires changes in plone.namedfile: https://github.com/plone/plone.outputfilters/pull/10

Packages that won't be part of Plone 5:

- Products.ResourceRegistries
- Products.PloneLanguageTool
- plone.app.controlpanel

**Comment by gforcada** [comment]
What about this other one: https://github.com/plone/Products.CMFDynamicViewFTI/pull/3 ?

**Comment by davisagli** [comment]
plone.outputfilters is now merged

**Comment by tisto** [comment]
plone.openid and plone.app.openid have been merged.

**Comment by tisto** [comment]
That's a good one. When I add plone.app.openid and plone.openid to the AT_plone_app_testing alltests group (https://github.com/plone/buildout.coredev/commit/72433b81e7bf65bb6e218f07d181b79107ad686b) I see a test failure in Products.contentmigration (that is run in full test isolation by alltests):

```
#### Running tests for Products.contentmigration ####
Running Products.contentmigration.tests.layer.PloneContentMigrationTestCase:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.182 seconds.
  Set up plone.app.testing.layers.PloneFixture /home/jenkins/.buildout/eggs/setuptools-5.8-py2.7.egg/pkg_resources.py:1032: UserWarning: /home/jenkins/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
in 10.240 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 2.258 seconds.
  Set up Products.contentmigration.tests.layer.PloneTestCaseFixture in 1.457 seconds.
  Set up Products.contentmigration.tests.layer.PloneContentMigrationTestCase:Functional in 0.000 seconds.


Failure in test /home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.contentmigration/Products/contentmigration/tests/../archetypes.txt
Failed doctest test for archetypes.txt
  File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.contentmigration/Products/contentmigration/tests/../archetypes.txt", line 0

----------------------------------------------------------------------
File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.contentmigration/Products/contentmigration/tests/../archetypes.txt", line 85, in archetypes.txt
Failed example:
    ff_migrator.migrate()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest archetypes.txt[47]>", line 1, in <module>
        ff_migrator.migrate()
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.contentmigration/Products/contentmigration/basemigrator/migrator.py", line 220, in migrate
        method()
       - __traceback_info__: (<Products.contentmigration.archetypes.ATFolderMigrator object at 0x7fb57ea12fd0>, <bound method ATFolderMigrator.migrate_extension_fields of <Products.contentmigration.archetypes.ATFolderMigrator object at 0x7fb57ea12fd0>>, <ATFolder at /plone/fold1_MIGRATION_>, 'fold1')
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.contentmigration/Products/contentmigration/archetypes.py", line 203, in migrate_extension_fields
        self.new.update(**kwargs)
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.Archetypes/Products/Archetypes/BaseObject.py", line 449, in update
        self.Schema().updateAll(self, **kwargs)
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.Archetypes/Products/Archetypes/Schema/__init__.py", line 528, in updateAll
        method(kwargs[name])
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.Archetypes/Products/Archetypes/BaseObject.py", line 216, in setId
        parent.manage_renameObject(self.id, value)
      File "/home/jenkins/workspace/plone-5.0-python-2.7-at/src/Products.CMFPlone/Products/CMFPlone/PloneFolder.py", line 84, in manage_renameObject
        result = method(self, id, new_id, REQUEST)
      File "/home/jenkins/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/CopySupport.py", line 348, in manage_renameObject
        action ='manage_main'))
    CopyError: 
    <HTML>
    <HEAD>
    <TITLE>Invalid Id</TITLE>
    </HEAD>
    <BODY BGCOLOR="#FFFFFF">
    <FORM ACTION="manage_main" METHOD="GET" >
    <TABLE BORDER="0" WIDTH="100%" CELLPADDING="10">
    <TR>
      <TD VALIGN="TOP">
      <BR>
      <CENTER><B><FONT SIZE="+6" COLOR="#77003B">!</FONT></B></CENTER>
      </TD>
      <TD VALIGN="TOP">
      <BR><BR>
      <CENTER>
      The id "fold1_MIGRATION_" is invalid - it is already in use.
      </CENTER>
      </TD>
    </TR>
    <TR>
      <TD VALIGN="TOP">
      </TD>
      <TD VALIGN="TOP">
      <CENTER>
      <INPUT TYPE="SUBMIT" VALUE="   Ok   ">
      </CENTER>
      </TD>
    </TR>
    </TABLE>
    </FORM>
    </BODY></HTML>

  Ran 14 tests with 1 failures, 0 errors and 0 skipped in 4.728 seconds.
Tearing down left over layers:
  Tear down Products.contentmigration.tests.layer.PloneContentMigrationTestCase:Functional in 0.000 seconds.
  Tear down Products.contentmigration.tests.layer.PloneTestCaseFixture in 0.011 seconds.
  Tear down plone.app.testing.bbb.PloneTestCaseFixture in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.088 seconds.
  Tear down plone.testing.z2.Startup in 0.006 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.
#### Finished tests for Products.contentmigration ####
```

I'd say this is impossible (if that would be the first time that something like this happens)...anyways...will revert my commit.

**Comment by tisto** [comment]
FYI: the plip-ptc jenkins job now checks out Products.Archetypes: 

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/18/console

The strange failure in the "Archetypes" alltests group persists. Products.Archetypes tests all pass though.

@jensens btw: you did not really believe me, when I said that we have to be extremely careful with merging those pull requests, right? That's the fun stuff I have been struggling with for more than a year. ;) Still can't believe those things really happen...

**Comment by tisto** [comment]
@tomgross when I run each package in the Archetypes allltests group in full isolation we get just a single test failure in PortalTransforms: http://jenkins.plone.org/view/PLIPs/job/plip-ptc/20/console

```
#### Running tests for Products.PortalTransforms ####

/home/jenkins/.buildout/eggs/setuptools-5.8-py2.7.egg/pkg_resources.py:1032: UserWarning: /home/jenkins/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).

Running Products.Archetypes.tests.attestcase.Archetypes:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.230 seconds.

  Set up plone.app.testing.layers.PloneFixture in 10.218 seconds.

  Set up plone.app.testing.bbb.PloneTestCaseFixture in 2.360 seconds.
  Set up Products.Archetypes.tests.attestcase.ATTestCaseFixture in 0.263 seconds.

  Set up Products.Archetypes.tests.attestcase.Archetypes:Functional in 0.000 seconds.


Error in test testCacheWithVHost (Products.PortalTransforms.tests.test_engine.TestEngine)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/tests/test_engine.py", line 262, in testCacheWithVHost
    self.engine.manage_addPolicy(mt, required)
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/TransformEngine.py", line 534, in manage_addPolicy
    raise TransformException(msg)
TransformException: A policy for output text/x-html-safe is yet defined



Error in test testPolicy (Products.PortalTransforms.tests.test_engine.TestEngine)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/tests/test_engine.py", line 212, in testPolicy
    self.engine.manage_addPolicy(mt, required)
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/TransformEngine.py", line 534, in manage_addPolicy
    raise TransformException(msg)
TransformException: A policy for output text/x-html-safe is yet defined

  Ran 121 tests with 0 failures, 2 errors and 0 skipped in 7.650 seconds.
Running zope.testrunner.layer.UnitTests tests:
  Tear down Products.Archetypes.tests.attestcase.Archetypes:Functional in 0.000 seconds.
  Tear down Products.Archetypes.tests.attestcase.ATTestCaseFixture in 0.010 seconds.
  Tear down plone.app.testing.bbb.PloneTestCaseFixture in 0.005 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.081 seconds.
  Tear down plone.testing.z2.Startup in 0.006 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 5 tests with 0 failures, 0 errors and 0 skipped in 0.032 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Total: 126 tests, 0 failures, 2 errors and 0 skipped in 21.544 seconds.

#### Finished tests for Products.PortalTransforms ####
```

Taking into considerations that those packages are legacy code, I could live with running them in full isolation. Therefore, if we fix the PortalTransforms failure, I'd say we can merge Archetypes as well.

**Comment by tisto** [comment]
PortalTransforms test failures are fixed.

**Comment by tisto** [comment]
@tomgross I tried hard to fix the plip-ptc job with Products.Archetypes, but there seems to be a non-trivial dependency between Archetypes, P.PortalTransforms and P.contentmigration. Test failures even seem to occur when tests are run in full isolation (shouldn't be possible). Some test failures could not be reproduced locally, some tests failed randomly. I just could not manage to fix the failing tests for both Plone 5.0 and Plone 4.3. This almost drove me insane...

My recommendation would be to get rid of P.contentmigration for Plone 5, to simplify the problem. It does not make sense to put too much effort into this in my opinion. Maybe we can fix some things for P.PortalTransforms as part of your PLIP.

**Comment by davisagli** [comment]
Products.contentmigration is kind of important for anyone migrating a Plone 4 site using ATContentTypes

**Comment by tisto** [comment]
@davisagli you mean to migrate a Plone 4 site with AT to Plone 5 (with AT)?

**Comment by davisagli** [comment]
No, to plone.app.contenttypes.

**Comment by tisto** [comment]
So what if we would refactor plone.app.contenttypes not to depend on P.contentmigration? Would that work?

**Comment by davisagli** [comment]
That would require inventing a new content migration system, which sounds like more work than fixing some tests.

**Comment by tisto** [comment]
ic. I thought P.contentmigration would be an AT-only thing and p.a.contenttypes just included some helper methods from there. Never really looked into it.

As said before, I already spend quite some time on trying to make things work and I failed. We could of course run those two tests that cause trouble conditionally. Though, the test isolation issues really worry me...not sure what to do here...

**Comment by davisagli** [comment]
Well, more heads are better than one when it comes to figuring out test isolation problems. Can you point us to the failures?

**Comment by tisto** [comment]
Well, it is hard to explain because things are so unpredictable. With the P.Archetypes tests moved to plone.app.testing we get two test failures in P.PortalTransforms:

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/39/#showFailuresLink

```
#### Running tests for Products.PortalTransforms ####
/home/jenkins/.buildout/eggs/setuptools-5.8-py2.7.egg/pkg_resources.py:1032: UserWarning: /home/jenkins/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Running Products.Archetypes.tests.attestcase.Archetypes:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.246 seconds.
  Set up plone.app.testing.layers.PloneFixture in 10.005 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 2.289 seconds.
  Set up Products.Archetypes.tests.attestcase.ATTestCaseFixture in 0.247 seconds.
  Set up Products.Archetypes.tests.attestcase.Archetypes:Functional in 0.000 seconds.


Failure in test testCacheWithVHost (Products.PortalTransforms.tests.test_engine.TestEngine)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/tests/test_engine.py", line 273, in testCacheWithVHost
    out.getData())
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: <a href="http://nohost/plone/Members/test_user_1_/qux">vhost link</a>



Failure in test testPolicy (Products.PortalTransforms.tests.test_engine.TestEngine)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-ptc/src/Products.PortalTransforms/Products/PortalTransforms/tests/test_engine.py", line 216, in testPolicy
    self.assertEqual(self.engine.listPolicies(), expected_policy)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 744, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python2.7/unittest/case.py", line 726, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [('text/x-html-safe', ('html_t... != [('text/x-html-safe', ('dummy_...

First differing element 0:
('text/x-html-safe', ('html_to_plone_outputfilters_html',))
('text/x-html-safe', ('dummy_html_filter1', 'dummy_html_filter2'))

- [('text/x-html-safe', ('html_to_plone_outputfilters_html',))]
+ [('text/x-html-safe', ('dummy_html_filter1', 'dummy_html_filter2'))]

  Ran 121 tests with 2 failures, 0 errors and 0 skipped in 7.685 seconds.
Running zope.testrunner.layer.UnitTests tests:
  Tear down Products.Archetypes.tests.attestcase.Archetypes:Functional in 0.000 seconds.
  Tear down Products.Archetypes.tests.attestcase.ATTestCaseFixture in 0.010 seconds.
  Tear down plone.app.testing.bbb.PloneTestCaseFixture in 0.005 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.080 seconds.
  Tear down plone.testing.z2.Startup in 0.007 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 5 tests with 2 failures, 0 errors and 0 skipped in 0.030 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Total: 126 tests, 2 failures, 0 errors and 0 skipped in 21.277 seconds.
#### Finished tests for Products.PortalTransforms ####
```
The problem seems to be that this line fails because there is already another policy present:

self.engine.manage_addPolicy(mt, required)

Therefore I fixed those tests by removing the policy before adding one or checking first. When I do this I can fix the PortalTransforms tests. Though, then the Archetypes alltests group just stopps right in the middle and no further tests are executed. See this trace for an example:

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/35/console

**Comment by davisagli** [comment]
That last error is the one that happens if one of the alltests groups lists a package that is not present in the python environment.

**Comment by tisto** [comment]
That would mean that this error shouldn't occur with an empty Archtypes alltests group, right? I think I tried that already. Though, I will re-apply my fix, then we can give it another try. Thx for the hint!

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/40/

**Comment by tisto** [comment]
I tried this locally with an empty Archetypes alltests group. Same error as on Jenkins.

**Comment by tisto** [comment]
The error does not occur when running:

bin/alltests-at --group=Archetypes

Though, when running:

bin/alltests-at

the problem occurs.

**Comment by davisagli** [comment]
Well, it's clearly failing due to plone.recipe.alltests not getting input it expects. I'd suggest putting in a pdb where it's failing and figure out where that unexpected None is coming from.

**Comment by tisto** [comment]
I amended p.r.alltests to ignore package path lookup errors:

https://github.com/plone/plone.recipe.alltests/pull/4

This way the specific pkg test will fail with an import error rather than just failing without any clue what might have gone wrong.

With this fix in place the CMF alltests group fails because CMFCalendar is missing:

```
#### Running tests for group CMF ####
...
ImportError: No module named CMFCalendar
#### Finished tests for group CMF ####
```

Will try to remove CMFCalendar.

**Comment by tisto** [comment]
Products.Archetypes and Products.CMFDynamicView are ready to merge, all tests pass:

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/46/

Thx for the alltests hint @davisagli!

**Comment by tisto** [comment]
@tomgross P.Archetypes and P.CMFDynamicView have been merged. Though, if I checkout CMFDynamicView in Plone 4.3 -> boom:

http://jenkins.plone.org/job/plone-4.3-python-2.7/73/consoleFull

**Comment by tisto** [comment]
@tomgross I fixed the 4.3 issue. Some bbb code was missing. All green now! 

So what's the status with ATContentTypes? What needs to be done? Do you want me to add it to auto-checkout in our Jenkins job? 

All other remaining packages will not be part of Plone 5, so it is not worth to put more effort into those I guess.

**Comment by tomgross** [comment]
:clap: Wow @tisto Thanks for fixing all the testing issues!
ATContentTypes is done about 70% I think. The porting is done but there are tests failining. I started to fix these but could not finish it. It is probably easier now once P.Archetyes is merged. I can look into it but I can't promise this will be any time soon. So if anyone wants to take over my work is here: https://github.com/plone/Products.ATContentTypes/tree/tomgross-ptc

**Comment by tisto** [comment]
@tomgross I got the Jenkins job basically running. All "bin/alltests" tests pass. As expected we have a couple of ATContentTypes test failures:

http://jenkins.plone.org/view/PLIPs/job/plip-ptc/52/

**Comment by tisto** [comment]
Products.PloneTestCase is gone! Thanks so much @tomgross! Great work!

**Comment by pbauer** [comment]
:beers:

**Comment by jensens** [comment]
this is good news!

**Comment by jcerjak** [comment]
Great success!
