### ISSUE TITLE
meta viewport in Plone 4 prevents zooming in beyond 100%, starts zoomed out

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#389]
This is in plonetheme.sunburst's main_template.pt:

`<meta name="viewport" content="width=device-width, initial-scale=0.6666, maximum-scale=1.0, minimum-scale=0.6666" />`

This is bad for two reasons:
- it starts the screen zoomed out and 
- it prevents zooming in beyond 100% 

max-zoom:1 is considered an accessibility problem.  What was the thinking behind this?

The current theme in Plone 5 uses:  `width=device-width, initial-scale=1.0`, so I'm only wondering if there is any risk in changing it in plonetheme.sunburst, for any further releases of Plone 4.

**Comment by fulv** [comment]
Credit: @mrwweb

**Comment by mrwweb** [comment]
Background: http://a11yproject.com/posts/never-use-maximum-scale/

**Comment by agitator** [comment]
never had a project where ^ this was sane ... 

+1 for 
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by polyester** [comment]
good point. I used that one in https://github.com/plone/Products.CMFPlone/issues/407 for consistency, but there is indeed no sane reason for maximum scale.

**Comment by jensens** [comment]
For those still using sunburst: This is still true https://github.com/plone/plonetheme.sunburst/blob/master/plonetheme/sunburst/skins/sunburst_templates/main_template.pt
