### ISSUE TITLE
font-weight on the toolbar

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#390]
the font on the toolbar looks too thin, almost not readable for people without an "eagle eye"
![screen shot 2015-03-04 at 17 49 07](https://cloud.githubusercontent.com/assets/365761/6488427/c0da552e-c297-11e4-9bcd-53dd63a2b9d7.png)
![screen shot 2015-03-04 at 17 57 36](https://cloud.githubusercontent.com/assets/365761/6488470/0f340756-c298-11e4-9908-95786d9d3d56.png)

**Comment by bloodbare** [comment]
Duplicated on #426 so lets close it
