### ISSUE TITLE
TinyMCE: Some inline_style icons are broken

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3905]
Tested in https://classic.demo.plone.org, Plone 6.0.9-coredev and 6.1-coredev.

The icons for the inline-styles `strikethrough` and `code` are broken and show bombs instead of the expected svg.

Screenshot from 6.1 coredev:
![inline_style_61](https://github.com/plone/Products.CMFPlone/assets/453208/5cb57770-df28-416d-b8f4-17a927dd834a)

I could not track down what code is responsible for turning the config-setting into the svg.

**Comment by pbauer** [comment]
@thet or @petschki might know how that happens

**Comment by petschki** [comment]
<img width="488" alt="Bildschirmfoto 2024-02-21 um 10 22 32" src="https://github.com/plone/Products.CMFPlone/assets/511761/96ff6c27-4737-4019-8a50-aa9e660dd8aa">

according to the tiny icon list here https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/ the icon names are "strike-through" and "sourcecode" ... we need to update this in the default registry.
