### ISSUE TITLE
Editing a images alignment in TinyMCE duplicates the image

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3910]
Tested in 6.0.9, 6.0 coredev and 6.1 coredev. 
For me it only happens in Firefox, not in Chrome

To reproduce:

* Add a image to a page in TinyMCE and select Align Left
* Edit the same image (select it with a click and click "Insert Image")
* Change Align to Right 
* Save 
* You now have two images (one right, one left)

![duplicate](https://github.com/plone/Products.CMFPlone/assets/453208/a40f4df9-164c-4ef9-9425-44a9ee0f7c4a)

**Comment by pbauer** [comment]
Same issue: Selecting the image via click and pressing "delete" does not remove the image.

Both problems do not happen when selecting the img-tag in status bar before deleting or changing something:
![tag](https://github.com/plone/Products.CMFPlone/assets/453208/b92c647c-b767-4541-8c60-1a407c0fa1ab)

My guess is that the mage-plugin somehow does not select the correct element upon click.

**Comment by pbauer** [comment]
@petschki maybe this is also up your alley :)

**Comment by petschki** [comment]
I remember this behavior some time ago. I think @mauritsvanrees had some similary issues. Thought we fixed that meanwhile. I try to figure out whats going on.

**Comment by petschki** [comment]
I fixed an issue here https://github.com/plone/mockup/commit/856b519c8f598aa93d629d1b786984c7b08e7db3 but this was there for some reason ;)

**Comment by petschki** [comment]
Fixed in 
```
plone.staticresources==2.1.12 (Plone 6.0)
plone.staticresources==2.2.0a5 (Plone 6.1)
```

**Comment by mauritsvanrees** [comment]
My earlier report with the same problem was issue #3800.
I confirm this is fixed with the new version.  Thanks!
I will include the new version in Plone 6.0.10 today.
