### ISSUE TITLE
PLIP: drop Python 3.8 and 3.9 in Plone 6.1

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3926]
## Abstract

As agreed in the Plone Steering on 2024-03-07, let's drop Python 3.8 and 3.9 support in Plone 6.1.  See [community announcement](https://community.plone.org/t/python-6-1-will-drop-support-for-python-3-8-and-3-9/19128/1) that I just made.

It has already been decided.  But in a discussion during the German Plone Tagung last week, we saw value in having a PLIP for all such major changes, even when it is a PLIP after the fact.

## Motivation

Until now, the alpha releases of Plone 6.1 supported five Python versions: 3.8 through 3.12. In the next alpha we will drop 3.8 and 3.9.  So 6.1 will support 3.10, 3.11, and 3.12. This was agreed during the meeting of the Plone Steering Circle last week. This is a meeting of Plone team leaders.

This means less burden on maintainers within the Plone community, like the release team and A/I team (including testing), and opens up the possibility for Plone core developers to use some more recent features. For inspiration, here is the Python document explaining what is new in each Python version:
https://docs.python.org/3/whatsnew/index.html

See what's new in [3.9](https://docs.python.org/3/whatsnew/3.9.html) and [3.10](https://docs.python.org/3/whatsnew/3.10.html) for what we can now use in 6.1 that was not possible earlier, for example the `zoneinfo` module and structural pattern matching (`match/case`).

## Assumptions

If you must use an older Python version, you can stay on Plone 6.0, which will support each Python version until it runs out of security support from the Python community. For Python 3.8 this is October 2024, for Python 3.9 this is October 2025. See [https://www.python.org/downloads/](https://www.python.org/downloads/).

## Proposal & Implementation

The only thing we really must do is announce it, and make it clear in the release notes and update the release schedule.

## Deliverables

- [x] Announce it: https://community.plone.org/t/python-6-1-will-drop-support-for-python-3-8-and-3-9/19128?u=mauritsvanrees
- [x] Update release schedule: https://plone.org/download/release-schedule
- [x] Update Jenkins to no longer run 3.8 and 3.9 jobs for 6.1: https://github.com/plone/jenkins.plone.org/issues/353
- [x] Update `mr.roboto` as well probably.
- [ ] Drop 3.8 and 3.9 classifiers from packages that are for 6.1 only.
- [x] Add `python_requires>=3.10` to at least `Plone` and `Products.CMFPlone`.  We could also wait until there is a change that really *requires* a newer Python version.
- [x] Add this to the upgrade guide for 6.1. https://github.com/plone/documentation/pull/1655
- [x] https://github.com/plone/documentation/issues/1674

Perhaps:

- [ ] Check if changes in `plone/meta` are needed for packages that only run on 6.1.

## Risks

This will break for users that currently have a 6.1 alpha site on 3.8 or 3.9.  But that seems unlikely: I expect all 6.1 users to use at least 3.11.

## Participants

* Maurits van Rees

**Comment by tisto** [comment]
I approve this PLIP. cc @plone/framework-team @plone/release-team

**Comment by MrTango** [comment]
I approve this PLIP. sorry for the delay

**Comment by stevepiercy** [comment]
I'd like to amend the documentation issue with this checklist:

https://github.com/plone/documentation/issues/1721

**Comment by stevepiercy** [comment]
I approve this PLIP, and any other documentation issues that may arise as we discover them.

**Comment by stevepiercy** [comment]
Since we're [testing and passing on Python 3.13](https://jenkins.plone.org/job/plone-6.1-python-3.13/), should this PLIP be amended to include support for it?

I move to amend this PLIP accordingly. Can I get a second?

**Comment by mauritsvanrees** [comment]
Let's not amend this PLIP: it is finished.  Well, I just did the last change needed, in commit eba6e73108541efac28eef47c7be61c658684db9.

We can still "Drop 3.8 and 3.9 classifiers from packages that are for 6.1 only" as one of the tasks says, but that is an ongoing effort as there keep coming more packages that for one reason or another drop Plone 6.0 support.

Supporting Python 3.13 does not need a PLIP.
