### ISSUE TITLE
Workflow transition on defaultPage is propagated to its container

### ISSUE THREAD

**Issue by sauzher** [plone/Products.CMFPlone#3932]
### What I did:

Step to reproduce on a vanilla plone4, plone5.2 or plone6 classic:

1. create a folder BAR
2. create a page BAZ inside BAR
3. Publish both BAR and BAZ
4. set BAZ as default page of BAR
5. Retract publication on page BAZ

### What I expect to happen:

- changed the page BAZ state only

### What actually happened:

-   changed folder BAR state also

  The same happens if page BAZ and foler BAR are private and you publish the page BAZ. You'll get BAR published also.
  The same happens despite the workflow associated on the contents. 
  It seems that the matters is the ID of the applied transaction.

### What version of Plone/ Addons I am using:

-  plone4, plone5.2 or plone6 classic

**Comment by yurj** [comment]
https://classic.demo.plone.org/en/bar/content_status_modify?workflow_action=retract&_authenticator=xyz
this is the link, the bug is in https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/toolbar*

But the link does not explain why the page itself change status...

**Comment by sauzher** [comment]
@stevepiercy The issues raises only when the page is set as `defaultPage` of its container. Only one page at time can be the default.

@yurj the toolbar link is 404. Alas, the plone demo site is automatically reset often to be useful as reference here.

**Comment by stevepiercy** [comment]
I think it's a feature, too. It does not make sense to publish an empty container. If you retract the default view of a container, then the container itself should also be retracted. If you want to have the container remain published, then set another page as the default view.

**Comment by sauzher** [comment]
There's a incipit of the issue here: https://community.plone.org/t/workflow-transition-on-defaultpage-is-propagated-to-its-container/19318

**Comment by petschki** [comment]
I would also say this is the expected behavior for defaultPages. Otherwise you would could change the folder state only via folder_contents or we have to implement an extra action in the toolbar for the "defaultPageContainerState" which adds extra complexity to the already complex "default page" thinking ...

**Comment by mauritsvanrees** [comment]
I would also say this is expected behavior.
It may have surprised you, but not doing it this way would be more surprising.
