### ISSUE TITLE
TinyMCE 5 is EOL, 7 recommended

### ISSUE THREAD

**Issue by stevepiercy** [plone/Products.CMFPlone#3936]
From https://www.tiny.cloud/docs/tinymce/5/:

> TinyMCE 5 reached End of Support in April 2023. No more bug fixes, security updates, or new features will be introduced to TinyMCE 5. We recommend you upgrade to [TinyMCE 7](https://www.tiny.cloud/docs/tinymce/7/upgrading/) or consider [TinyMCE 5 Long Term Support (LTS)](https://www.tiny.cloud/long-term-support/) if you need more time.

**Comment by petschki** [comment]
Oh wow. I'll give Tiny 7 a try in `plone/mockup`.

**Comment by jensens** [comment]
PR was merged PLIP closed, close this one too?

**Comment by stevepiercy** [comment]
This needs to stay open. We might not go to TinyMCE 7 because they moved several plugins to their paid version, including templates. There's a discussion in Discord, but no final decision yet.

**Comment by petschki** [comment]
We have backported the missing `template` plugin from TinyMCE 6 into mockup here https://github.com/plone/mockup/pull/1384 ... I'll close this.
