### ISSUE TITLE
Broken or missing JavaScript leads to unusable resource registry.

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#3942]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

The resource registry has all it's bundles collpapsed in an bootstrap accordion element.

When JavaScript cannot be loaded (e.g. by providing it via webpack dev server or if it is broken), then the resource registry has all it's resource tabs are closed and cannot be opened and thus are not interactable.

See:

![grafik](https://github.com/plone/Products.CMFPlone/assets/170891/db95591b-8d99-4edf-874e-1544a3b23e7c)

### What I did:

- Remove the plone bundle by deleting the entry or disabling it.

### What I expect to happen:

In http://localhost:8080/Plone/@@resourceregistry-controlpanel I'd expect all the resource bundle entries to be un-collapsed and the form fields being shown.

### What actually happened:

All the resource entries are collapsed and the resource registry is not interactable.

### What version of Plone/ Addons I am using:

    Plone 6.1.0a3.dev0 (6102)
    CMF 3.3
    Zope 5.9
    Python 3.12.2 (main, Mar 17 2024, 12:06:58) [GCC 13.2.0]
    PIL 10.2.0 (Pillow)
    WSGI: On
    Server: waitress 2.1.2

## Proposal to fix this

The HTML element `details` is widely available and provides content collapsing without JavaScript being necessary.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by petschki** [comment]
If you deactivate JS in your browser the collapsibles will be open ... but this could be solved better definitely.
