### ISSUE TITLE
TypeError thrown when during groups lookup

### ISSUE THREAD

**Issue by alecpm** [plone/Products.CMFPlone#3952]
The offending code is [here](https://github.com/plone/Products.CMFPlone/blob/308aa4d03ee6c0ce9d8119ce4c37955153f0bc6f/Products/CMFPlone/controlpanel/browser/usergroups_usermembership.py#L66). The traceback looks like this:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 280, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFPlone.controlpanel.browser.usergroups_usermembership, line 57, in __call__
  Module Products.CMFPlone.controlpanel.browser.usergroups_usermembership, line 54, in update
  Module Products.CMFPlone.controlpanel.browser.usergroups_usermembership, line 63, in getGroups
TypeError: '<' not supported between instances of 'bool' and 'str'
```

The issue is that when there's a `None` value in the `groupResults` (which is anticipated in the sort code) the lambda returns `False` which fails to compare against the group title/name strings under Python 3. The list comprehension that defines `groupResults` should probably just filter out `None` values to avoid this issue. I'm not entirely sure what circumstances result in a `None` group value, but I am seeing it occur in a real world use case.

**Comment by davisagli** [comment]
FWIW we fixed a similar bug in plone.restapi recently: https://github.com/plone/plone.restapi/pull/1775

I think it can happen if a group is enumerated by a PAS plugin but it can't actually be fetched by id for some reason.

In your case maybe there is something wrong with what the dexterity.membrane PAS plugins are returning?
