### ISSUE TITLE
PLIP: make plone.app.discussion a core add-on [6.1]

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3958]
## Responsible Persons

* Proposer: Jens Klein (@jensens)
* Seconder: Maurits van Rees (@mauritsvanrees)

## Abstract

Move `plone.app.discussion` above `Products.CMFPlone` in the dependency chain.

## Motivation

Most Plone sites do not need discussion/comment support.

## Proposal & Implementation

* Remove `plone.app.discussion` from the `install_requires` of `Products.CMFPlone`.
* Add it to the dependencies of `Plone`.
* Have a maintenance branch of `plone.app.discussion` for Plone 6.0.

## Deliverables

- [ ] `plone.app.discussion` branch for 6.0, and let master depend on `Products.CMFPlone.
- [ ] Add to dependencies of `Plone`, remove it from `Products.CMFPlone`
- [ ] Add to [main documentation upgrade guide](https://github.com/plone/documentation/pull/1666)
- [ ] Add snippet as specified in https://github.com/plone/plone.restapi/pull/1781#discussion_r1602282129 to both the [`@comment` endpoint docs](https://6.docs.plone.org/plone.restapi/docs/source/endpoints/comments.html) and [`plone.restapi` upgrade guide](https://6.docs.plone.org/plone.restapi/docs/source/upgrade-guide.html)

## Status:

WIP, see https://github.com/plone/plone.app.discussion/pull/211

## Contributors:

- Steve Piercy (@stevepiercy)

**Comment by stevepiercy** [comment]
I updated the original PLIP regarding the docs from a single item to two items, and created a pull request to address one of them in https://github.com/plone/documentation/pull/1666

**Comment by tisto** [comment]
For what it is worth, I approve this PLIP and moved it to "approved" column in the PLIP overview:

https://github.com/orgs/plone/projects/47/views/1

@plone/framework-team @plone/release-team feel free to chime in.

@mauritsvanrees @jensens what's the status of this PLIP? Isn't this merged already?

**Comment by jensens** [comment]
Last (manual) tests and fixes addressing updates from Plone 5.2/6.0 are open. 
see  https://github.com/plone/plone.app.discussion/pull/211#issuecomment-2167385971 and below.

**Comment by mauritsvanrees** [comment]
I have added an upgrade step in https://github.com/plone/plone.app.upgrade/pull/330.  See testing hints there.  I have merged main/master in the PR branches of the other packages.  This seems ready now.

**Comment by jensens** [comment]
Please merge if everything is ready!

**Comment by mauritsvanrees** [comment]
Last call for reviews.  Without further comments I intend to merge this at the end of this week or beginning of next week.

**Comment by mauritsvanrees** [comment]
All is merged.  Jenkins may take some time getting green again, but should be fine after all merges have really landed.

There was some documentation already, but could be extended for clarity.  I will have a go at that.

**Comment by mauritsvanrees** [comment]
Documentation PR: https://github.com/plone/documentation/pull/1696

And I thought of one more change that would be good.  Since in 6.1 you need to explicitly activate the add-on, I think it makes sense to let this globally enable comments.  This also helps Volto, which has no Discussion control panel where you can enable comments.
I made a small PR: https://github.com/plone/plone.app.discussion/pull/244

After this, it would be good to have another 6.1 alpha with all the needed changes.

**Comment by jensens** [comment]
this is done now, close?

**Comment by mauritsvanrees** [comment]
Yes. Thanks all!
