### ISSUE TITLE
Problem with TAB navigation in login form (Plone Classic)

### ISSUE THREAD

**Issue by verena-rh** [plone/Products.CMFPlone#3969]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Normally you can use TAB in the login window to jump from the username to the password. If you have already entered the password incorrectly once and the login window contains an error message, you can no longer jump further using the TAB key. This also means that the autotype function of a password manager no longer works.

### What I did:

After a failed login attempt, make another attempt.

### What I expect to happen:

Can jump from username to password field with TAB key

### What actually happened:

The Cursor remains in the username field when the TAB key is pressed

### What version of Plone/ Addons I am using:

6.0.11.1

**Comment by rohnsha0** [comment]
@verena-rh I wasn't able to reproduce the error tho!
