### ISSUE TITLE
Contributing to `Products.CMFPlone` is broken

### ISSUE THREAD

**Issue by stevepiercy** [plone/Products.CMFPlone#3973]
As a new to Plone core contributor, you would start by going to our documentation:

https://6.docs.plone.org/contributing/index.html#specific-contribution-policies-of-projects

Which takes you to the repository:

https://github.com/plone/Products.CMFPlone/

And if you happen to know the pattern of checking a repo's `CONTRIBUTING.md`, you would go there:

https://github.com/plone/Products.CMFPlone/blob/master/CONTRIBUTING.md

Which takes you to outdated documentation.

https://5.docs.plone.org/develop/coredev/docs/guidelines.html

Which rambles on and on about irrelevant topics, until you finally find testing.

https://5.docs.plone.org/develop/coredev/docs/intro.html#testing-locally

And if you have not used buildout, it won't work.

The fallback is to just push a commit, submit a pull request, and tell Jenkins to run tests against your PR. This is slow and wasteful, but there is no other way for new contributors to contribute.

We have clear instructions for documentation, Volto, plone.restapi, and plone.api. I've also [ported docs from reStructuredText in version 5.2 to MyST for 6.0](https://github.com/plone/documentation/blob/6.0/coredev/getting-started-with-development.md), but I've begged and pleaded for anyone, _anyone_, to help to no avail. I have no clue myself, else I would update the docs.

References: https://github.com/plone/documentation/issues/1278

**Comment by rohnsha0** [comment]
@stevepiercy so in short we need to update the documentation? in this repo?!

**Comment by stevepiercy** [comment]
@rohnsha0 yes.

In plone/documentation. As I said:

> I've also [ported docs from reStructuredText in version 5.2 to MyST for 6.0](https://github.com/plone/documentation/blob/6.0/coredev/getting-started-with-development.md)

That is a mere conversion from one syntax to another with only a few grammar, spelling, or syntax fixes. The content itself is still outdated and incorrect for Plone 6.
