### ISSUE TITLE
Refactor esteele.manager into plone.releaser.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#398]
- Refactor
- Add to github.com/plone
- Include in buildout.coredev
- Write documentation (release process, versioning, manifest.in, ...)

**Comment by tisto** [comment]
https://github.com/plone/plone.releaser

**Comment by gforcada** [comment]
:+1:

**Comment by tisto** [comment]
done: https://pypi.python.org/pypi/plone.releaser
