### ISSUE TITLE
site logo - remove width and height attributes

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#399]
i ran into a problem, where the width and height attributes on the portal logo are problematic for responsive sites. e.g., we have a sticky horizontal menu. when scrolling down the page, the menu shrinks, and so does the logo. but since, it has a fixed width, setting the height to something smaller makes the logo look like stretched.

i propose to simply remove the width and height attributes.
see: https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L203

cc/ @sneridagh @albertcasado

**Comment by vangheem** [comment]
definitely. width and height should never be fixed like that. IMO, make the change right away.
