### ISSUE TITLE
Twitter link should be changed to x links

### ISSUE THREAD

**Issue by SarthakPaandey** [plone/Products.CMFPlone#3994]
In `setup.py`'s `project_urls` metadata, change Twitter link from `https://twitter.com/plone` to `https://x.com/plone`.

**Comment by davisagli** [comment]
This change is fine, but please only update user-facing text and not internal variable names (which make backwards-compatibility more difficult).

**Comment by rohnsha0** [comment]
> This change is fine, but please only update user-facing text and not internal variable names (which make backwards-compatibility more difficult).

Agreed

**Comment by SarthakPaandey** [comment]
> This change is fine, but please only update user-facing text and not internal variable names (which make backwards-compatibility more difficult).
Sure.

**Comment by SarthakPaandey** [comment]
> This change is fine, but please only update user-facing text and not internal variable names (which make backwards-compatibility more difficult).

Sure.

**Comment by stevepiercy** [comment]
This is definitely not a [Plone Improvement Proposal (PLIP)](https://6.docs.plone.org/contributing/core/plips.html). The related PR is a mere one-line internal fix of metadata in `setup.py`, not anywhere near the scope implied in the issue description. The original description inflated its importance and was very misleading, as other maintainers responded accordingly. @SarthakPaandey doing that is very disrespectful of the Plone community and its volunteers' freely given time and attention. I corrected the description to reflect reality.

@SarthakPaandey please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do) and Item 2 in [Work with GitHub issues](https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contribute to Plone 6 core](https://6.docs.plone.org/contributing/core/index.html).

We cannot even review, much less merge, your pull request until you satisfy contributor requirements.

**Comment by davisagli** [comment]
@stevepiercy I agree it didn't need to be a PLIP, since it wasn't a controversial change, but you've gone overboard in the other direction. There are other references to Twitter that need to be updated, such as in the social media control panel (https://demo.plone.org/controlpanel/socialmedia)

**Comment by stevepiercy** [comment]
@davisagli see #3995.

**Comment by SarthakPaandey** [comment]
I am sorry @stevepiercy. I will follow what you have mentioned. Thanks for the guidance!
