### ISSUE TITLE
CMFPlone is not initialised when using editable pip install

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#4002]
You can try this out with https://github.com/plone/buildout.coredev/pull/945.  Checkout the branch of that PR, run `make install` and `make zope-start` and try to create a Plone instance.  This will fail with `KeyError: 'Unicode Whitespace splitter'` because the [`initialize` function](https://github.com/plone/Products.CMFPlone/blob/6.1.0a4/Products/CMFPlone/__init__.py#L46) is not called.

So what is going on?

* During Zope startup, `OFS.Application` [installs products](https://github.com/zopefoundation/Zope/blob/5.10/src/OFS/Application.py#L377).
* It gets a list of products by calling [`get_products`](https://github.com/zopefoundation/Zope/blob/5.10/src/OFS/Application.py#L413).
* This basically does `import Products` and then checks which Python packages are in the directory of that module.
* That directory is for example `.venv/lib/python3.12/site-packages/Products`.
* In each package found in that directory, [`install_product`](https://github.com/zopefoundation/Zope/blob/5.10/src/OFS/Application.py#L468) gets called, which results in calling the `initialize` function in `__init__.py` if it exists.
* When you have pip installed `Products.CMFPlone` normally, `CMFPlone` will be in that directory, so all is well.
* When you are instead using an editable install (`pip install -e src/Products.CMFPlone`), it will *not* be in this list.  So the `initialize` function will not get called, and all kinds of stuff won't be registered.  Creating a Plone Site or visiting an existing Plone site fails.
* The way to handle this, is to use [`five.registerPackage`](https://github.com/zopefoundation/Zope/blob/1b21489db28ffe25c1ce103ea273c09fc4dfd9c0/src/OFS/metaconfigure.py#L107).
* This adds the package to a list of [packages to initialize](https://github.com/zopefoundation/Zope/blob/1b21489db28ffe25c1ce103ea273c09fc4dfd9c0/src/OFS/Application.py#L392-L394) in much the same way as happens with packages in the special `Products` namespace.

So we should add `five:registerPackage` to the `configure.zcml` of `Products.CMFPlone`.  Then it works.
I will do that in 6.0 and 6.1.

**Comment by mauritsvanrees** [comment]
And if, like me, you are wondering how this actually works with Buildout, this is the pretty print of `Products.__path__` in that case (Plone 6.1):

```
['/Users/maurits/community/plone-coredev/6.1/src/Products.CMFPlone/Products',
 '/Users/maurits/shared-eggs/cp312/Products.isurlinportal-3.0.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.PortalTransforms-4.1.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Zope-5.10-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFPlacefulWorkflow-3.0.4-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.statusmessages-5.0.6-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.SiteErrorLog-6.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.PlonePAS-8.0.4-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.MimetypesRegistry-3.0.1-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.ExtendedPathIndex-4.0.1-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.DCWorkflow-3.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFEditions-4.0.3-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.GenericSetup-3.0.2-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFCore-3.5-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.ZCatalog-7.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFDynamicViewFTI-7.0.2-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.PluggableAuthService-3.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.BTreeFolder2-5.1-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.PythonScripts-5.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.ExternalMethod-5.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.ZopeVersionControl-4.1-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFUid-4.2-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.CMFDiffTool-4.0.4-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.MailHost-5.2-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.StandardCacheManagers-5.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.DateRecurringIndex-3.0.1-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.Sessions-5.0-py3.12.egg/Products',
 '/Users/maurits/shared-eggs/cp312/Products.PluginRegistry-2.0-py3.12.egg/Products']
```

So there the Products path is not one directory, but multiple.

Meanwhile I have PRs ready for Plone 6.0 and 6.1.

**Comment by thet** [comment]
Super explanation on the Products initialization phase!
