### ISSUE TITLE
PLIP 13091: Multilingual

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#401]
There is a plip configuration : 
https://github.com/plone/buildout.coredev/blob/5.0/plips/plip13091-multilingual.cfg

There is a jk job : 
http://jenkins.plone.org/view/PLIPs/job/plip-13091-multilingual/

It works but it needs to make tests pass.

**Comment by bloodbare** [comment]
Its related to #145

**Comment by tisto** [comment]
List of pull requests:

https://github.com/plone/plone.app.controlpanel/pull/25
https://github.com/plone/plone.app.multilingual/pull/159
https://github.com/plone/archetypes.multilingual/pull/11
https://github.com/plone/plone.i18n (no pr needed)
https://github.com/plone/plone.app.upgrade/pull/29
https://github.com/plone/plone.app.contenttypes/pull/218
https://github.com/plone/plone.app.testing/pull/12
https://github.com/plone/Products.ATContentTypes/pull/16
https://github.com/plone/plone.theme/pull/2
https://github.com/plone/plone.app.i18n/pull/3
https://github.com/plone/plonetheme.barceloneta/pull/7
https://github.com/plone/plone.theme/pull/2

**Comment by tisto** [comment]
plone.theme: http://jenkins.plone.org/view/PLIPs/job/plip-13091-multilingual/97/

**Comment by tisto** [comment]
plonetheme.barceloneta: http://jenkins.plone.org/view/PLIPs/job/plip-13091-multilingual/98/

**Comment by tisto** [comment]
plone.app.i18n (not necessary)

**Comment by tisto** [comment]
plone.app.controlpanel: http://jenkins.plone.org/view/PLIPs/job/plip-13091-multilingual/99/

**Comment by tisto** [comment]
Products.CMFPlone: http://jenkins.plone.org/view/PLIPs/job/plip-13091-multilingual/100/

**Comment by tisto** [comment]
Multilingual has been merged.

**Comment by gforcada** [comment]
:tada:
