### ISSUE TITLE
Remove Portal_css Portal_javascript

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#402]
Its needed an upgrade step to remove portal_css portal_javascript on plone 5, also remove the PloneResourceRegistry

**Comment by bloodbare** [comment]
As removing Plone Resource Registry would mean that jsregistry.xml import would not work we pospone this removal to plone 5.1

**Comment by pbauer** [comment]
Duplicate of https://github.com/plone/Products.CMFPlone/issues/1742
