### ISSUE TITLE
`email.utils.getaddresses` was changed to "strict-parsing" in Python 3.11.10 and 3.12.6

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#4020]
when running the tests we've encountered the following error in `testvalidateSingleEmailAddress`

```
AssertionError: True is not false : user@example.org
Bcc: user@example.org should fail
```

this is because `email.utils.getaddresses` has changed its strategy to "strict parsing" in the newest Python 3.11 and 3.12 versions. (see https://docs.python.org/3.12/whatsnew/3.12.html#id11 and https://docs.python.org/3.11/whatsnew/3.11.html#email)

### proposed solution:

~~add the parameter `strict=False` to get the old behavior back and test with `getattr(email.utils, 'supports_strict_parsing', False)` if this parameter is available~~

new approach: respect the new output from strict parsing.

**Comment by mauritsvanrees** [comment]
Fix got merged. Thanks!
