### ISSUE TITLE
Move all controlpanel permissions to permissions file

### ISSUE THREAD

**Issue by jackahl** [plone/Products.CMFPlone#4028]
## Suggestion to move controlpanel permission declaration to unified location

While working on the aliases controlpanel I noticed, that there are multiple controlpanel permission definitions located in another file than the others at https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/permissions.zcml:

- Imaging: https://github.com/plone/Products.CMFPlone/blob/ad248d7e0c5ea2b7a0649575abb6c79e891e620c/Products/CMFPlone/controlpanel/browser/configure.zcml#L8
- TinyMCE: https://github.com/plone/Products.CMFPlone/blob/ad248d7e0c5ea2b7a0649575abb6c79e891e620c/Products/CMFPlone/controlpanel/browser/configure.zcml#L13
- ManagePortalAliases: https://github.com/plone/Products.CMFPlone/blob/ad248d7e0c5ea2b7a0649575abb6c79e891e620c/Products/CMFPlone/controlpanel/browser/configure.zcml#L329
- ManageContextAliases: https://github.com/plone/Products.CMFPlone/blob/ad248d7e0c5ea2b7a0649575abb6c79e891e620c/Products/CMFPlone/controlpanel/browser/configure.zcml#L334

At a glance I don't see any reason, why they are declared there and not in the main permissions file for controlpanels. 

Could someone from @plone/classicui-team check whether my train of thought here is correct?

**Comment by jensens** [comment]
Ack, any controlpanel permission under `...CMFPlone/controlpanel/*` should go in the `...CMFPlone/controlpanel/permissions.zcml`.

**Comment by rohnsha0** [comment]
already completed in #4030
