### ISSUE TITLE
TinyMCE ignores the HTML filter settings

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#405]
The TinyMCE pattern does not read the HTML filter settings. See skipped filter control panel robot tests for details:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_controlpanel_filter.robot

I created a new issue after the discussion took place here:

https://github.com/plone/Products.CMFPlone/issues/213

**Comment by vangheem** [comment]
@bloodbare and I agree that we'd prefer not to implement this in TinyMCE. It's always been painful having 2 levels of filtering going on. There was always something about it that wouldn't work and cause very hard to debug problems--not knowing where the filtering was happening.

**Comment by vangheem** [comment]
Please reopen if you disagree...
