### ISSUE TITLE
Permission plone.ModifyConstrainTypes (Modify constrain types) no longer managed

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#4072]
The permission `plone.ModifyConstrainTypes` (Modify constrain types) used to be assigned to 'Manager', 'Site Administrator', 'Owner' by Products.ATContentTypes. This assignment has not been moved anywhere so that is only held by Manager now.

**Comment by pbauer** [comment]
Adding this to `rolemap.xml` of CMFPlone does the trick. 

```xml
    <permission name="Modify constrain types" acquire="True">
      <role name="Manager"/>
      <role name="Site Administrator"/>
      <role name="Owner"/>
    </permission>
```

`plone.app.content` that defines the permission has no (and imho should not have a) profile.

**Comment by pbauer** [comment]
We could add a upgrade-step for that but it might unexpectedly change permissions that were set differently in a project. 
All sites since 5.1 or 5.2 with Archetypes (duh!) will either have only Manager or custom stuff.

**Comment by davisagli** [comment]
@pbauer I could see an argument for either adding the upgrade step or not. The important thing is that we say clearly in the release notes which one we did.
