### ISSUE TITLE
Sorting Timezones while creating site

### ISSUE THREAD

**Issue by rohnsha0** [plone/Products.CMFPlone#4075]
### What I did:
Tried creating a website and selecting timezones

### What I expect to happen:
The timezones should come sorted alphabetically for easier access

### What actually happened:
![image](https://github.com/user-attachments/assets/9b130623-7e8d-4a0c-84da-03594e985205)

The timezones were jumbled up
### What version of Plone/ Addons I am using:

- Plone 6.1.0b2.dev0 (6106)
- CMF 3.6
- Zope 5.11
- Python 3.11.9 (main, Dec 5 2024, 04:13:12) [GCC 14.2.1 20240910]
- PIL 11.0.0 (Pillow)
- WSGI: On
- Server: waitress 3.0.1

**Comment by davisagli** [comment]
They appear to already be sorted alphabetically by the full name in parentheses.

**Comment by rohnsha0** [comment]
so is it sorted by the zone?
