### ISSUE TITLE
Creating a link is broken in TinyMCE inline mode in Plone 6.1.0b2

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#4083]
Steps to reproduce:

- Enable tinymce inline mode (`plone.inline`)
- Edit a page
- Try to add a link
- Nothing happend

JS traceback in console:

```
Uncaught TypeError: document.getElementById(...)['pattern-tinymce'] is undefined
    T links.js:326
    onAction links.js:360
    buttonBehaviours theme.js:17595
    p_ theme.js:12004
    buttonBehaviours theme.js:17593
links.js:326:32
    T links.js:326
    onAction links.js:360
    buttonBehaviours theme.js:17595
    p_ theme.js:12004
    buttonBehaviours theme.js:17593
```

Probably related to new contentbrowser pattern.

### What version of Plone I am using:
Plone 6.1.0b2

**Comment by petschki** [comment]
You can check this PR https://github.com/plone/plone.staticresources/pull/364 for fixing this (without running mockup webpack devel server)
