### ISSUE TITLE
Inline portal_javascripts break 404 page

### ISSUE THREAD

**Issue by code-po8** [plone/Products.CMFPlone#409]
If an entry in portal_javascripts is marked to render inline, the 404 page of the plone site sends the JavaScript's MIME type instead of text/html as would be expected.  This causes browsers to display the HTML of the error page instead of rendering it.

Steps to recreate:
1. Create a trivial JavaScript file.
2. Add an entry for it in portal_javascripts with inline rendering checked.
3. Enter a bad URL into browser to make plone's 404 page appear.

**Comment by jensens** [comment]
outdated
