### ISSUE TITLE
adding site with default language 'de-at' breaks

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#411]
With current Plone 5 beta 1 and the merged language control panel, adding a site with a language like 'de-at' breaks and gives the following traceback:

```
2015-04-01 20:25:30 ERROR Zope.SiteErrorLog 1427912730.490.962488456232 http://localhost:8888/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 232, in __call__
  Module Products.CMFPlone.factory, line 95, in addPloneSite
  Module plone.registry.registry, line 47, in __setitem__
  Module plone.registry.record, line 83, in _set_value
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 389, in _validate
ConstraintNotSatisfied: de-at
```

Please note, 'de-at' is selected by default, as reported by my browser.

- ``Products.CMFPlone.browser.admin.AddPloneSite.languages`` uses ``plone.i18n.locales.interfaces.IContentLanguageAvailability`` and constructs a list of languages with combined language codes, if the default language as reported by the browser contains a "-".
- ``Products.CMFPlone.interfaces.controlpanel.ILanguageSchema.use_combined_language_codes`` as a default value of False.
- ``plone.app.vocabularies.language.AvailableContentLanguageVocabulary`` constructs it's language list via ``plone.i18n.utility.LanguageUtility.getAvailableLanguages`` according to the setting ``use_combined_language_codes``, which is False by default.

I guess, we have to set ``use_combined_language_codes`` to True in CMFPlone/factory, if CMFPlone/admin/AddPloneSite decides to use combined language codes...

**Comment by thet** [comment]
^^^ @bloodbare @tisto

**Comment by thet** [comment]
workaround for a successful install: choose 'de' or anything else as long it is not a combined language when adding a site.

**Comment by hvelarde** [comment]
confirmed over here

**Comment by Martronic-SA** [comment]
The problem is still there in the 5.0b2 (fr-ch)

**Comment by jaroel** [comment]
Currently we don't have an option to select a combined language. Not sure why yet.

**Comment by jaroel** [comment]
Right, it only shows when your browser says it's language is something with a '-' in it.

@thet 
Would it be acceptable to only allow 'DE' in plone-addsite, and use plone_control_panel to select a specific locale?

**Comment by davilima6** [comment]
IMO 5.0 should definitely allow specific locales but for a post-sprint 5.0b3 it's very acceptable :)

**Comment by thet** [comment]
@jaroel i'm not sure if i like to remove the ability to use combined language codes (even if your pull https://github.com/plone/Products.CMFPlone/pull/684 simplifies the code :) )

IIRC, it would be enough to let the ``use_combined_language_codes`` setting in ``Products.CMFPlone.interfaces.controlpanel`` default to ``True``.

**Comment by jaroel** [comment]
Do we see a good reason not to show the whole list by default?
The browser language is already selected.

**Comment by bloodbare** [comment]
It can be tricky for most of the sites to need to choose between different english flavous.

**Comment by jaroel** [comment]
I've reworked the language selection in https://github.com/plone/Products.CMFPlone/pull/693 .
It groups all country specific languages.
