### ISSUE TITLE
No Mail Settings are stored on MailHost

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#412]
On the new mail control panel.

Mailhost does not get the values from the Configuration Registry so it does not know the mail settings and can't send emails

@MrTango @tisto

**Comment by MrTango** [comment]
Thats right, you should not use the properties in the mailhost, but instead take them from registry directly. The MailHost is a CMF package, so that we decide to not change that.
In Plone we should simple not use the properties in MailHost anymore.

**Comment by djay** [comment]
This is getting stupid. Now we are just breaking things for the sake of it. Why not? MailHost has a well documented api. Are you going to put all of PAS in the registry too? Stupid.

**Comment by MrTango** [comment]
djay, you can still use the methods in MailHost, but not the properties, because the configuration is now in the registry like it is the case for all Plone settings now. And the best way to get the mail settings is to get it from the registry.

**Comment by djay** [comment]
Not all settings. It will never be all settings. PAS for example. It was really meant for just portal properties and few obvious ones.

**Comment by MrTango** [comment]
maybe, but i'm not the right person in charge for that.
This is all defined in a PLIP and most of that is done for Plone 5.
In the special case of mail control panel, the settings are now in Plone registry like for most control panels. I'm not into the PAS stuff, so you should discuss that on Plone dev mailing list.

**Comment by tisto** [comment]
@bloodbare can you be a bit more specific where the settings are not picked up? We replaced all portal properties lookups in core code.

@djay the settings used to be looked up in portal properties. They are now looked up on the new registry. This is needed if we want to get rid of the old tools. We did not change the mailhost api at all. 

Before you call things stupid you might want to take a minute to check how things actually work:

https://github.com/plone/Products.CMFPlone/pull/328/files

You did not care to spend a minute on thinking about something that took quite a few peoples months to implement. The PLIP was written 5 years ago by Hanno (https://dev.plone.org/ticket/10359). That might give you an idea how much effort we had to put into that, just to hear you complain about it. 

This is how you motivate people to spend more of their free time to work on cleanup tasks...

**Comment by bloodbare** [comment]
@tisto is it solved ?

**Comment by tkimnguyen** [comment]
I am running into this problem in the 5.0b1 installer.

**Comment by vangheem** [comment]
Is it fixed on master? Looks like there is a changelog for the fix. @tkimnguyen can you test please? Thanks.

**Comment by tkimnguyen** [comment]
I just tried this with the coredev buildout. It sends mail out but I think the Site From Name field is being treated somehow as an email address: if I just put in my name "T. Kim Nguyen", I get this error

``
Error Unable to send test e-mail {'kim@bla.com': (553, '5.5.4 <kim@bla.com>... Domain name required for sender address T.')}.
``
but if I put in that field the email address again, it sends out ok.

**Comment by tkimnguyen** [comment]
(sorry, inadvertently closed this issue because of my commit message wording)

**Comment by tisto** [comment]
I think I fixed the issue. I need to find time to do some more testing and make sure this is covered by robot test. If @tkimnguyen could give master a try that would help.

**Comment by tkimnguyen** [comment]
@tisto did you change something since I made the change above alter the "from email address"? If you didn't change anything since, I think it works well now (I tested a number of different ways sending out the test email message). I just wasn't sure of the protocol for closing issues.

**Comment by tisto** [comment]
No. I don't think so. I guess there were actually two bugs. I fixed the first one and you just fixed the second one. :)

**Comment by tkimnguyen** [comment]
yay :)
