### ISSUE TITLE
Select list with field elements unsupported

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#413]
The list (see screenshot) should be sorted by localized field names (tested against 5.0b1)
![screenshot 2015-04-07 14 25 22] (https://cloud.githubusercontent.com/assets/594239/7023039/2ccda7c2-dd32-11e4-86ac-c46481c54dd3.png)

**Comment by davisagli** [comment]
This can be fixed here: https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/fields.py#L54

Would you be willing to make a pull request?

**Comment by zopyx** [comment]
https://github.com/plone/plone.schemaeditor/pull/22

2015-04-08 8:06 GMT-04:00 David Glick <notifications@github.com>:

**Comment by vangheem** [comment]
This was merged, closing.
