### ISSUE TITLE
Adding a new Dexterity 'xml' gives an error in @@add-type

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#417]
Plone 5.0b1:

I tried to create a Dexterity content type TTW called 'xml'.

This gives the following JS error:

![screenshot 2015-04-08 09 58 37](https://cloud.githubusercontent.com/assets/594239/7041057/155b4e9c-ddd6-11e4-82ca-e4654c15b131.png)

**Comment by zopyx** [comment]
As expect: this is the error from the backend...the form should provide some more reasonable error messages:

2015-04-08 09:59:46 ERROR Zope.SiteErrorLog 1428479986.30.278133076263 http://localhost:8080/xml/dexterity-types/@@add-type
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module z3c.form.form, line 213, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module z3c.form.form, line 242, in handleAdd
  Module z3c.form.form, line 250, in createAndAdd
  Module plone.app.dexterity.browser.add_type, line 46, in add
  Module OFS.ObjectManager, line 326, in _setObject
  Module OFS.ObjectManager, line 120, in checkValidId
BadRequest: The id "xml" is reserved.

**Comment by davisagli** [comment]
This comes from the modal pattern in mockup: https://github.com/plone/mockup/blob/master/mockup/patterns/modal/pattern.js#L266

I agree it should report the error in a more useful way.

**Comment by vangheem** [comment]
fixed here: https://github.com/plone/mockup/commit/ccec87028bc22e082d6d9a95874d8a961f91b707
