### ISSUE TITLE
Packages with broken or missing dependencies are no longer visible in the add-ons form

### ISSUE THREAD

**Issue by cewing** [plone/Products.CMFPlone#419]
If you have an add-on with metadata dependencies on other packages, any of which is missing or broken, then the add-on is not displayed in the add-on management form.  The data is available from the [QuickInstaller tool](https://github.com/plone/Products.CMFQuickInstallerTool/blob/master/Products/CMFQuickInstallerTool/QuickInstallerTool.py#L155) but is not used in the new Products.CMFPlone/controlpanel/browser/quickinstaller.py view.

**Comment by thet** [comment]
Isn't that a more like a feature? IMO, the dependencies in a package should be well defined.

**Comment by davisagli** [comment]
Unless you're developing the package and haven't defined them well yet. In Plone 4 it showed warnings in this situation. Fortunately @cewing is almost done with pull request to restore that functionality.

**Comment by cewing** [comment]
It's also helpful if you're a site manager and you add an add-on and it did not properly declare package dependencies in its `setup.py`.  I'm generally of the opinion that more information is better than less when it comes to "why isn't that thing I just created/downloaded showing up to be installed"

**Comment by thet** [comment]
+1. listing broken packages in an extra section is of course much better than just ignoring it.
