### ISSUE TITLE
Translate folder_add_more on Plone 5

### ISSUE THREAD

**Issue by skleinfeldt** [plone/Products.CMFPlone#421]
Plone 5 folder contents view "Add" button shows the untranslated string "folder_add_more" for folder content type configuration.
![folder_add_more](https://cloud.githubusercontent.com/assets/1198463/7056763/e2fd8cf2-de1c-11e4-8b0c-01336b04d07b.png)

**Comment by gforcada** [comment]
Someone needs to update the English translation on [plone.app.locales](https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/en/LC_MESSAGES/plone.po#L6316:L6319)

**Comment by davisagli** [comment]
@gforcada no, actually the problem is that we need to explicitly translate message strings after https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/folder.py#L533 because the response is served as JSON rather than passed through a template.

**Comment by gforcada** [comment]
Aha, sorry for the noise then.
