### ISSUE TITLE
Fix speedup for tests?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#425]
I just stumbled upon this line: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patches/speed.py#L5

As we moved to `plone.app.testing` do we need to change that to something else? Does that still make sense?

/cc @tisto

**Comment by tisto** [comment]
No idea.

**Comment by davisagli** [comment]
I don't know. It could be that this is still in the environment and the p.a.testing tests still depend on it. Do they break without it?

**Comment by jensens** [comment]
At least in zope4 factorydispatcher is cached and as soon zope4 is used this patch can be removed.

**Comment by jensens** [comment]
seems like we need to clean this up now
