### ISSUE TITLE
Font type, weight, size could use some tweaking on toolbar

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#426]
The readability of the toolbar text really sucks. See screenshot taken on my Macbook air. At least the font-weight must be higher. Right now the text appears very thin and some pixel are apparently missing or the dithering hurts the readability

![screenshot 2015-04-09 07 28 25](https://cloud.githubusercontent.com/assets/594239/7065852/221a937c-de8a-11e4-8416-25d9a9fe2a6d.png)

**Comment by frisi** [comment]
just a guess and might be completely unrelated: maybe  font-smoothing is to blame here?
i recently read an article that points out a very similar issue: http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

**Comment by zopyx** [comment]
Perhaps this is the issue but it is an issue that can not be solved by client-side changes

**Comment by agitator** [comment]
https://github.com/plone/Products.CMFPlone/issues/390

**Comment by bloodbare** [comment]
@albertcasado can you take care of this issue ?

**Comment by agitator** [comment]
these things look fine on a retina-like display, but this is by far not the standard.
there are other areas where font-weight "light" makes it almost unreadable.
i think the "lightest" default font-weight has to be "normal" for any style in plone.

**Comment by tisto** [comment]
@zopyx First of all thanks for reporting bugs. This helps us a lot improving Plone 5. Your input is important and highly appreciated.

Though, would you be willing to fix a bug that was reported with "XXX sucks"? Would you be willing to spend your free time fixing things for people that say your work sucks? Please continue to report bugs, but if you do, think for a second about the people that will fix those bugs (for your and others).

@albertcasado did a great job with the theme in his free time, without being payed by a company (his regular job does not even include any Plone work at all). We should all be very thankful for this and the least we can do is report bugs in a professional manner.

**Comment by zopyx** [comment]
Sorry for inappropriate wording, no intention for offending anyone here.
Just need to make the issue clear.

2015-04-26 10:18 GMT+02:00 Timo Stollenwerk <notifications@github.com>:

**Comment by agitator** [comment]
changed font-weight to 700, should be good now
