### ISSUE TITLE
Toolbar contrast poor

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#427]
Related to https://github.com/plone/Products.CMFPlone/issues/426:

the contrast of the text (grey on blackground) sucks horribly. Sorry but this hurts my eyes.
In addition the opacity of the background is not helpful for reading the next....poor usability.
![screenshot 2015-04-09 19 41 53](https://cloud.githubusercontent.com/assets/594239/7079320/bd25d1e0-def0-11e4-9d12-1a6d15bd6176.png)

**Comment by bloodbare** [comment]
@albertcasado

**Comment by vangheem** [comment]
Fixed with another commit.
