### ISSUE TITLE
addPloneSite() does not work nicely with the Plone legacy bundle/resources not added to the legacy bundle automatically

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#428]
I have a setup script for installing a Plone 4/5 instance running XML Director

The adjust code for create a Plone 5 site uses addPloneSite() which installed the xmldirector.demo:default profile 

https://github.com/xml-director/xmldirector.demo/blob/master/democontent/setup-plone.py#L43

with has xmldirector.plone core as a depedency:

https://github.com/xml-director/xmldirector.demo/blob/master/xmldirector/demo/profiles/default/metadata.xml

addPloneSite() works fine and installs the xmldirector.plonecore package with the exception that the resources of the xmldirector.plonecore does not appear in the Plone legacy bundle. I have to re-install the package through the Plone site setup in order to re-add the resources to the legacy bundle.

**Comment by zopyx** [comment]
uninstalling and re-installing the xmldirector.plonecore add-on programmatically does not make a difference. So there must be something within the TTW installer of add-ons doing something special related to the legacy bundle.

**Comment by vangheem** [comment]
huh, it looks like it's done the same way: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/factory.py#L114 and https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/browser/quickinstaller.py#L218

I'll try to make time to test later.

**Comment by zopyx** [comment]
git clone https://github.com/xml-director/xmldirector.plonecore.git
make build-demo5
bin/instance run src/xmldirector.demo/democontent/setup-plone-428.py

Start Plone and goto 

localhost:12020/xml-director/@@resourceregistry-controlpanel

The legacy bundle does not contain the JS/CSS files of xmldirector.plonecore

**Comment by vangheem** [comment]
Thanks, installing right now.

**Comment by vangheem** [comment]
Your problem has to deal with how addPloneSite handles errors. On error of extension_ids, the site is still created. So your plone 5 version of the addPloneSite call does not work.

If you change:
```
try:
    addPloneSite(app, 'xml-director', create_userfolder=True, extension_ids=['plonetheme.sunburst:default', 'xmldirector.demo:default', 'pp.client.plone:default'])
except:
    addPloneSite(app, 'xml-director', extension_ids=['plonetheme.barceloneta:default', 'xmldirector.plonecore:default', 'xmldirector.demo:default', 'pp.client.plone:default'])
```
to:
```
try:
    import plonetheme.sunburst
    addPloneSite(app, 'xml-director', create_userfolder=True, extension_ids=['plonetheme.sunburst:default', 'xmldirector.demo:default', 'pp.client.plone:default'])
except:
    addPloneSite(app, 'xml-director', extension_ids=['plonetheme.barceloneta:default', 'xmldirector.plonecore:default', 'xmldirector.demo:default', 'pp.client.plone:default'])
```

The site is created properly and the resources are imported.

I am going to close this issue. Please re-open if I mis-understood.

**Comment by zopyx** [comment]
...means Plone is swallowing errors....bad behavior

**Comment by vangheem** [comment]
actually, I think your code was swallowing the error. When I ran the code manually, it'd throw an exception. The real problem is that creating a site should probably be in a savepoint which can be rolled back if errored.

**Comment by zopyx** [comment]
The Plone 4.x code within the try clause causes an exception:

-> addPloneSite(app, 'xml-director', create_userfolder=True,
extension_ids=['plonetheme.sunburst:default', 'xmldirector.demo:default',
'pp.client.plone:default'])
(Pdb++) n
TypeError: "addPloneSite() got an unexpected keyword argument
'create_userfolder'"

and then the 5.0 setup code is being executed:

-> addPloneSite(app, 'xml-director',
extension_ids=['plonetheme.barceloneta:default',
'xmldirector.plonecore:default', 'xmldirector.demo:default',
'pp.client.plone:default'])

So there is no difference in the code execution path...but I need to
recheck that later in detail.

2015-05-02 9:15 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

**Comment by zopyx** [comment]
The change 

https://github.com/xml-director/xmldirector.demo/commit/f1bf8756429c0d305c37e922cf82fcb05375cd85#diff-802d2e15b8f3d86fe942af5fe9041c27

does not has any impact on the original problem.

**Comment by vangheem** [comment]
When I run:

```
bin/instance run src/xmldirector.demo/democontent/setup-plone-428.py
```

now, it gives me this error:

```
Traceback (most recent call last):
  File "/Users/nathan/code/sandbox/xmldirector.plonecore/parts/instance/bin/interpreter", line 328, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "src/xmldirector.demo/democontent/setup-plone-428.py", line 26, in <module>
    newSecurityManager(None, user.__of__(uf))
AttributeError: 'NoneType' object has no attribute '__of__'
```

No idea what is going on but maybe you have other issues.

When I tested before, I had it worked with the addPloneSite not getting run twice.

**Comment by vangheem** [comment]
okay, re-ran build. Worked for me: https://www.dropbox.com/s/eu7ppgicyqs16ml/addPloneSite.mov?dl=0

**Comment by zopyx** [comment]
Is this with the lastest patch in CMFCore or official Plone 5.0b1 code?

**Comment by zopyx** [comment]
Here is my screencast showing that it is still not working for me:

https://www.dropbox.com/s/f50talmmbdrpzl5/ScreenFlow.mp4?dl=0

2015-05-02 16:01 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

**Comment by zopyx** [comment]
Works now with 

https://github.com/plone/Products.CMFPlone/commit/e37000a60551f94695f2510966754d7d73efed92 

applied.
