### ISSUE TITLE
@@overview-controlpanel - width of list items/Plone 5.0b1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#429]
The control panel items should not span the whole width of the page...
![plone site](https://cloud.githubusercontent.com/assets/594239/7086717/25352356-df52-11e4-8775-ba1635684f3a.png)

**Comment by bloodbare** [comment]
@albertcasado

**Comment by tisto** [comment]
This is somehow related to the p.a.controlpanel refactoring. What do we want here? The old way of displaying those items? Or just less width? I also think this is a duplicate.

**Comment by davisagli** [comment]
I thought the old appearance with columns was nice and compact. It could probably be implemented with CSS columns these days (as long as there are fewer columns depending on the responsive breakpoints).

**Comment by gforcada** [comment]
from the designs I understood that the single column was meant to be fixed across all control panels so you get an easy navigation or scroll memory on where to get options. Thus we either create a fancy first page explaining what can you do on the control panel or we could also redirect directly to on of the control panels (site for example?)

**Comment by jaroel** [comment]
@sneridagh You are working on this, right?

**Comment by sneridagh** [comment]
@jaroel Yeah! And making progress!

**Comment by jaroel** [comment]
Nice :dancers:

**Comment by vangheem** [comment]
Done and in toolbar-fixup branch.
