### ISSUE TITLE
two quickinstaller views, can we delete one?

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#430]
Is it normal we have both CMFPlone/controlpanel/browser/quickinstaller.pt / quickinstaller.py and plone.app.controlpanel/plone/app/controlpanel/qi.pt / qi.py ?
The two views seem almost identical. A bad refactoring maybe?

**Comment by vangheem** [comment]
hhmmm, i thought plone.app.controlpanel was getting all merged into Products.CMFPlone

**Comment by gforcada** [comment]
I think the idea is to ship it but only for BBB.

/cc @tisto @bloodbare

**Comment by vincentfretin** [comment]
I don't think it was for BBB reason, I think it's a merge/refactoring error. plone.app.controlpanel/plone/app/controlpanel/qi.py didn't exist on Plone 4.
The prefs_install_products_form page actually uses Products/CMFPlone/controlpanel/browser/quickinstaller.pt, not plone.app.controlpanel/plone/app/controlpanel/qi.pt

**Comment by vincentfretin** [comment]
I removed plone/app/controlpanel/qi.pt and qi.py
The view wasn't declared in zcml.
