### ISSUE TITLE
404 when clicking on a flag (switchLanguage missing)

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#431]
Plone 5b1
In language control panel, select two languages (English and French for example), check Show language flags, and Always show language selector.
Click Save.
You have now flags at the top.
When you click on one of them, you get a Page not found.
It doesn't find a switchLanguage view.

**Comment by jaroel** [comment]
Fixed in https://github.com/plone/plone.app.i18n/commit/634300e64602ac1c0f46dbefbd31c124df18a22e
