### ISSUE TITLE
Issue with input and search button

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#435]
In Plone 5b1
The search button is misaligned with the input.
The label of the button is cut in French "Rechercher". see screenshot attached.
![search](https://cloud.githubusercontent.com/assets/112249/7100756/e3ec84e2-e033-11e4-9cda-1b4570e110b1.png)

**Comment by vincentfretin** [comment]
Previous image was with iceweasel (firefox).
It's worse with chromium
![search](https://cloud.githubusercontent.com/assets/112249/7100760/379ad0e4-e034-11e4-98a3-5a2fcad2b6d9.png)

**Comment by vangheem** [comment]
This was fixed.
