### ISSUE TITLE
Star icon for required field

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#437]
In Plone 5b1
Am I the only one that found that the star icon is a bit weird for the required fields?
![star](https://cloud.githubusercontent.com/assets/112249/7100774/0f86745e-e035-11e4-87fa-cb61696f9e66.png)

You generally found a red square or an asterisk here, not a star like that.

**Comment by vincentfretin** [comment]
Generally a star represents a favorite functionality.

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plonetheme.barceloneta/commit/72806ef0494ba0234b3af03dfbfbf9ba332094dd
