### ISSUE TITLE
Dexterity in-out widget visual issue.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#439]
The padding of the left/right buttons is inconsistent (Plone 5.0b1)

http://www.awesomescreenshot.com/image/70270/de73d525e3291044f538e2f3b7fd5aec

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plonetheme.barceloneta/commit/73216bf8ba186410f9f89b2ea25c2e5f8319a15d
