### ISSUE TITLE
TinyMCE internal images/links not working after enabling multilingual (Plone 5.0b1)

### ISSUE THREAD

**Issue by nightmarebadger** [plone/Products.CMFPlone#440]
In Plone5.0b1 if you install plone.app.multilingual and enable two languages, TinyMCE internal images and links stop working. 

The error seems to come from the relatedfields pattern calling

    /Plone/en/@@getVocabulary?name=plone.app.vocabularies.Catalog

instead of

    /Plone/@@getVocabulary?name=plone.app.vocabularies.Catalog

which leads to an error ("Vocabulary lookup not allowed"). 

Widgets outside TinyMCE don't seem to be affected by this. For instance, Page -> Categorization -> Related items works ok, but searches through all items (I would expect to only see items from the language I am currently on).

**Comment by allusa** [comment]
Now the the navigation root is checked correctly. Solved on Plone 5.0b2.
