### ISSUE TITLE
[Website] [Plone.org] Links or content leading to trackers for website issues are driving crazy

### ISSUE THREAD

**Issue by acsr** [plone/Products.CMFPlone#445]
I tried to file in an issue with the plone.org content 

(Name of Sjoerd van Efferen is missing last name in the members of Plone Foundation listing at https://plone.org/foundation/members)

I discovered the following hurdles whe trying to file in a ticket:

1. Link in footer of plone.org is not working today (points to https://dev.plone.org/newticket?field_component=Website)

    * The server at https://dev.plone.org is not responding for me

2. I looked over Plone.org to figure out a working link in the content.

    * There is a way to start to look at from the tab "Contribute" 

        * you will be pointed just to link for developers ending up in the collective on github. 
          http://collective.github.io this is not helpful to followup.
 
    * If you start at tab "Support" and then the key visual "Develop" you will eventually visit https://plone.org/documentation/faq/i-think-ive-found-a-bug-in-plone.-where-should-i-report-it

        * There is a text at the end that is not matching what you find on github if you visit the location. The text is confusing even if it mentiones that this section needs cleanup.

Finally I decided to put this here so hopefully someone can redirect it to the right place later.

**Comment by vangheem** [comment]
Okay, I fixed all the issues you brought up. The link issues are just waiting for a site update: https://github.com/plone/plonetheme.ploneorg/issues/2

https://github.com/plone/plonetheme.ploneorg/commit/e1128154d3a4bf710297af51d89bd7147ed0516c

plone.org is not very well maintained right now--waiting for new site to get finished up.
