### ISSUE TITLE
plone.app.multilingual and archetypes.multilingual have test isolation issues

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#447]
Adding either plone.app.multilingual or archetypes.multilingual to the AT_plone_app_testing alltests group in buildout.coredev (tests.cfg) leads to multiple test isolation issues. Both packages seem to have test isolation problems that need to be fixed.

cc @bloodbare

**Comment by bloodbare** [comment]
Which JK job I can check for that ?

**Comment by tisto** [comment]
We do not have a Jenkins job. I just tried that locally on my machine. I guess we could create a plip job. Not sure if that's worth the effort though.

**Comment by tisto** [comment]
btw: here is the traceback for archetypes.multilingual: https://github.com/plone/archetypes.multilingual/issues/12#issuecomment-94654457

**Comment by gforcada** [comment]
@tisto I'm just looking at https://github.com/plone/buildout.coredev/blob/5.0/tests.cfg and given my not so depth knowledge about buildout, can we actually just override some groups on another cfg file?

My idea given @bloodbare questions would be to create a jenkins job for some test isolation problems, so anyone can work on them, see the errors that are happening and just update the cfg file with their pull request branches, test those branches via jenkins and merge on the build is green.

**Comment by gforcada** [comment]
@tisto @bloodbare it seems you can actually do it:

```
[buildout]
extends =
    ../core.cfg

[test-groups]
AT_plone_app_testing =
    plone.app.collection
    Products.contentmigration
    Products.CMFDynamicViewFTI
    plone.app.multilingual
```

@tisto all test isolation problems are documented on test.cfg?

**Comment by do3cc** [comment]
https://github.com/plone/plone.testing/pull/19
More test isolation packages

**Comment by jensens** [comment]
meanwhile with python3 migration test isolation problems were fixed
