### ISSUE TITLE
Plone 5 Upgrade Guide

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#450]
http://docs.plone.org/manage/upgrading/index.html
https://github.com/plone/documentation/tree/master/manage/upgrading

Topics:
- Control panels
- Mailhost
- PloneTestCase removal
- Portal tools removal
- plone.app.contenttypes/plone.app.event
- Resource registry
- plone.app.widgets/mockup/patternslib
- New theme

**Comment by tisto** [comment]
PloneTestCase: http://stackoverflow.com/questions/29660234/importerror-no-module-named-plonetestcase#comment47503559_29660234

**Comment by tisto** [comment]
Control panels: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/README.rst

**Comment by tisto** [comment]
https://github.com/plone/documentation/pull/227

**Comment by pbauer** [comment]
https://github.com/plone/documentation/compare/do3cc-upgrade-z3cform

**Comment by jensens** [comment]
are open tasks left here?
