### ISSUE TITLE
add * to @@search query

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#451]
the "default" results on @@search page should be the same as in live search results
if I add a * to the end of the search term, the result are the same again

we're even updating the live search input field from the "big" input field in the search form, so there should be no difference

**Comment by vangheem** [comment]
Agreed. All queries should be wrapped like "*" + term + "*" right?

This has already been discussed elsewhere. Feel free to update.

**Comment by agitator** [comment]
don't know about the query in detail, but " + term + " would be even better.
important is that we keep the way how these two search tools work identical.

yes, there was a similar issue - didn't find it

**Comment by tomgross** [comment]
Is it possible to specify query syntax in the search field? If so adding a "*" at the end would lead to unwanted behaviour: like this: dog AND cat -> dog AND cat*

**Comment by vangheem** [comment]
FYI, plone 4's live search had this special logic::

```
# for now we just do a full search to prove a point, this is not the
# way to do this in the future, we'd use a in-memory probability based
# result set.
# convert queries to zctextindex

# XXX really if it contains + * ? or -
# it will not be right since the catalog ignores all non-word
# characters equally like
# so we don't even attept to make that right.
# But we strip these and these so that the catalog does
# not interpret them as metachars
# See http://dev.plone.org/plone/ticket/9422 for an explanation of '\u3000'
multispace = u'\u3000'.encode('utf-8')
for char in ('?', '-', '+', '*', multispace):
    q = q.replace(char, ' ')
r = q.split()
r = " AND ".join(r)
r = quote_bad_chars(r) + '*'
searchterms = url_quote_plus(r)
```

This logic was lost with the plain use of SearchableText index in the search form.

Are there objections to re-introducing logic like this to help with search results?

**Comment by vangheem** [comment]
I implemented this the way I think most people want it to behave. Please re-open if there are still problems. Thanks.
