### ISSUE TITLE
Error deleting a Plone 5 site

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#452]
I ignored this problem the first time I got it, but today it happened again so I think there's something wrong.

Sometimes (unluckily I don't have a way to reproduce this) deleting I Plone 5 site raise an error:

    2015-04-23 16:55:52 ERROR Zope.SiteErrorLog 1429800952.280.307771923778 http://localhost:8080/manage_delObjects
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.app.linkintegrity.monkey2, line 19, in manage_delObjects
      Module OFS.ObjectManager, line 540, in manage_delObjects
      Module OFS.ObjectManager, line 408, in _delObject
      Module zope.event, line 31, in notify
      Module zope.component.event, line 24, in dispatch
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module zope.component.event, line 32, in objectEventNotify
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module OFS.subscribers, line 113, in dispatchObjectMovedEvent
      Module zope.container.contained, line 153, in dispatchToSublocations
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module OFS.subscribers, line 113, in dispatchObjectMovedEvent
      Module zope.container.contained, line 153, in dispatchToSublocations
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module plone.app.linkintegrity.handlers, line 224, in referencedObjectRemoved
      Module plone.app.linkintegrity.info, line 40, in integrityCheckingEnabled
      Module zope.component._api, line 169, in getUtility
    ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, ''

Sites I'm talking about are little, quite empty, test sites, with no additional add-ons inside.

**Comment by vangheem** [comment]
I wasn't able to reproduce this. I've been deleting an re-creating sites no problem. Any updates?

**Comment by keul** [comment]
Hints: I think you must install something in the registry first. Sorry, I've the test environment at home, can't test this right now

**Comment by vangheem** [comment]
I still can not reproduce this. Is there anything unique you're doing? This on coredev?

**Comment by davisagli** [comment]
Probably depends on the order in which the portal's subobjects get deleted. It would only happen if an object that's referenced is deleted after portal_registry.

This is a bit weird though...I don't think we really need to bother doing linkintegrity checks if the user's deleting the entire portal! I wonder if there's some way we can prevent dispatching the event to subobjects.

**Comment by vangheem** [comment]
Going to close this for now. Please re-open if it is still probably on master. If you have more specific steps to reproduce this, that'd be great. Thank you.
