### ISSUE TITLE
(Plone 5.0b1) Catalog returns all languages by default

### ISSUE THREAD

**Issue by nightmarebadger** [plone/Products.CMFPlone#453]
A catalog query used to only return items in the current language and if you wanted to get all languages you had to explicitly specify it with something like:

    catalog(query, Language='all')

or

    catalog(query, Language='')

This seems to no longer be the case, if you do not specify a language you get items from all languages and using `Language='all'` returns an empty list.

**Comment by jensens** [comment]
did you enable plone.app.multilingual?

**Comment by nightmarebadger** [comment]
Yeah, plone.app.multilingual is enabled, we have two languages ('en' and 'sl').

**Comment by vangheem** [comment]
Yes, the catalog is no longer hacked/monkey patched to do this magic for you. As far as I understand, this is by design and you need to specify the language in the queries manually. Core will not have a patch on the catalog to do this for you.
