### ISSUE TITLE
(Plone 5.0b1) Navigation controlpanel 'Displayed content types' are not taken into account

### ISSUE THREAD

**Issue by nightmarebadger** [plone/Products.CMFPlone#454]
If you go to the Navigation control panel (`@@navigation-controlpanel`) and change the `Displayed content types` it doesn't seem to be taken into account (other settings worked fine though). 

Going to ZMI -> portal_properties -> navtree_properties and changing `metaTypesNotToList` worked and allowed me to add/remove types from the navigation/sitemap.

**Comment by tisto** [comment]
@nightmarebadger thanks for reporting. I will look into it.

**Comment by tisto** [comment]
@nightmarebadger Can you be a bit more specific about "doesn't seem to be taken into account". I tried it manually and we have a robot test that passes:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_controlpanel_navigation.robot#L30

Please add a list of steps that are necessary to reproduce the bug.

**Comment by tisto** [comment]
Fix: https://github.com/plone/Products.CMFPlone/pull/485

**Comment by tisto** [comment]
PR Test: jenkins.plone.org/job/pull-request/108

**Comment by tisto** [comment]
Another fix: https://github.com/plone/plone.app.contentlisting/pull/7

**Comment by tisto** [comment]
Fixes have been merged:

https://github.com/plone/Products.CMFPlone/pull/485
https://github.com/plone/plone.app.contentlisting/pull/7
