### ISSUE TITLE
Refactor theming control panel to not depend on p.a.controlpanel.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#457]
The theming control panel in plone.app.theming imports the skins control panel from p.a.controlpanel:

https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/controlpanel.py#L31

Since plone.app.controlpanel is deprecated and will be removed in Plone 5.1, we have to remove that dependency.

We can either refactor the entire plone.app.theming control panel to use plone.app.registry (better), or just move the code from p.a.controlpanel to p.a.controlpanel (easier).

**Comment by vangheem** [comment]
This was fixed with https://github.com/plone/plone.app.theming/commit/dcf8be121d5ae330020f76162b4e63e1a39bb2f7
