### ISSUE TITLE
Custom Theming - Bugs

### ISSUE THREAD

**Issue by birdwell** [plone/Products.CMFPlone#458]
When you copy Barceloneta Theme (active), you can't make the copied theme the active one. It continues to make the Barceloneta Theme the active one. 

When modifying the custom theme, all of the buttons when you hover over them disappear or move away from your mouse. 

![screenshot 2015-04-24 16 08 57](https://cloud.githubusercontent.com/assets/3323856/7356598/dfe52ba2-ecee-11e4-801b-8b900e2634f1.png)
![screenshot 2015-04-24 17 03 56](https://cloud.githubusercontent.com/assets/3323856/7356599/dfe589b2-ecee-11e4-8bfc-f116116f738b.png)
![screenshot 2015-04-27 15 04 15](https://cloud.githubusercontent.com/assets/3323856/7356597/dfe53520-ecee-11e4-82ec-35106a682337.png)

**Comment by vangheem** [comment]
I'm pretty sure this was a known issue issue fixed in master(CMFPlone and
plone.app.theming). I don't have a commit to prove or right now though...
