### ISSUE TITLE
Not obvious to use sharing and workflow together for complex workflows

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#462]
## Problem

For example, a site admin wants to create a workflow whereby content is viewed by several different organisation roles such as "Communications Team" or "HR Manager". So they feel like they need to create new Plone roles to achieve this because of the word "Role" and sometimes end up doing so via the ZMI. Instead they are normally better off using groups to represent their organisation roles, and use the sharing tab to change the capabilities of those groups in a given state. (originally from https://trello.com/c/lelTU7hK/7-not-obvious-to-use-sharing-and-workflow-together-for-complex-workflows)

This is made worse by inconsistent naming between the sharing tab and the users/groups control panel. Sharing uses the word "Permissions" and relabels "Editor" to "Can Edit". (from https://trello.com/c/jrrl7tyH/5-confusion-between-names-of-roles-in-sharing-vs-users-configlet)

It's not obvious when browsing in folder contents or in toolbar when a private content might be visible to others. You can only see that by clicking sharing. (https://trello.com/c/c2NRztVZ/22-not-obvious-private-items-might-be-shared)

[![Vote](http://voting-badge.herokuapp.com/img?url=https://github.com/plone/Products.CMFPlone/issues/462)](http://voting-badge.herokuapp.com/vote?url=https://github.com/plone/Products.CMFPlone/issues/462)
## Internal

If there are no longer global plone roles via the control panel then there is a performance difference if the root sharing tab is used instead. There could be optimisations used to solve this.
## Options
1. Remove word Roles from the UI. Replace it with "capabilities" or "permissions" or "permission set".
   - same in both "users and groups" and "sharing"
2. The Roles matrix could be removed from the user and groups control panels and instead a link to root sharing form. 
   1. admin adds new user Fred. After in Users and groups there is a link "Edit Global sharing" next to Freds name. Admin clicks it
   2. Switches to Sharing tab on the root with Freds name already in the list.
   3. pro: user and groups takes up less space and less code.
   4. con: less efficient?
3. Some kind of display of how state affects capabilities on the sharing tab and/or workflow dialog. e.g. if submitted state removes edit permission from the Can Edit capability we should make that visible somehow. 
   - Combining sharing and state into one form could help show the relationship between what is possible in a certain state and if its possible, who can do it. 
     - pro: decreases the number of toolbar items #482 
4. Summarize sharing in the toolbar. For instance show how many users can view or edit a private content item
5. ??

An example of what combining sharing and state togeather might look like

![2-sharing](https://cloud.githubusercontent.com/assets/41700/8741105/2b3e7c38-2c7e-11e5-952b-5717c71a28b4.png)

A summary of sharing in the toolbar might look like
![1-home](https://cloud.githubusercontent.com/assets/41700/8741602/c2990f4c-2c85-11e5-8d5c-59932be81351.png)

**Comment by vangheem** [comment]
1. We can't mixed in permissions to replace the "role" label. I don't know what is best here.
2. This is interesting! Would we need to add more to the Sharing tab to make this reasonable to do(I mean more "roles")?
3. This would be cool. I'm not sure how that would be done right now but something to think about.

Additionally, the work on the plone intranet improvement indexing performance of permission changes should solve any performance issues.

**Comment by vangheem** [comment]
I would also target Plone 5.1 with this.

**Comment by jensens** [comment]
@djay, do you still plan to implement this? If yes I'd propose to make this an addon first and then plip it for integration.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Comment by djay** [comment]
This an issue in 6
