### ISSUE TITLE
too easy to use use images that are slow to download

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#463]
## User Problem

from @jonstahl 

One of the biggest problems I've had with users who don't understand image optimization for the web (i.e. most folks) is that they don't understand how to rescale and appropriately optimize images for the web. Plone's automated image scaling helps somewhat, but there are several problems with it:

- Default jpeg quality setting of 88 is not very aggressive, and scaled images are often still much larger than they need to be. 
- There is no way to detect when a user is uploading an inappropriately large image (esp. a carousel image) for unscaled use or to offer a way to correct it.

(from https://trello.com/c/sazsMhmK/42-need-additional-affordances-for-automatic-image-optimization-to-prevent-performance-problems)

## Internal

As of Plone 4.3.1/plone.app.imaging 1.0.8 this is finally made jpeg quality TTW configurable, but the current defaults still result in pretty large images.

## Options

1. Need additional affordances for automatic image optimization to prevent performance problems??
2. Some kind of indication of download time/size inside tinymce?
3. Some way to automatically suggest or change the image scale if you manually resize the image?
4. ??

**Comment by vangheem** [comment]
Yes, we have the *same* problem.

What is a good default? I'm okay just leaving the quality configurable.

2. Good idea.
3. This would be *really* nice.
4. Change the default image size to the large scale instead of the original in tinymce.

**Comment by frisi** [comment]
it would also be good to be able to configure a maximum image size in pixels.
this would not help a lot in terms of website performance, but could dramatically reduce the size of the blobstorage

this used to be possible for archetypes image fields before plone.app.image was introduced.
```
[atcontenttypes-conf]
recipe = plone.recipe.atcontenttypes
zope-instance-location =
    ${instance1:location}
    ${instance2:location}
max-image-dimension =
    ATImage:2048,2048
    ATNewsItem:2048,2048
```

**Comment by vangheem** [comment]
Ah yes, bringing back max size constraints would be nice. Should that be configurable TTW?

**Comment by tkimnguyen** [comment]
Yes!

**Comment by hvelarde** [comment]
this is handled with client size resizing in the [jQuery File Upload](http://blueimp.github.io/jQuery-File-Upload/] plugin used in [collective.upload](https://github.com/collective/collective.upload).

it would be nice to port that feature into Plone but I don't know what are the implications.

I don't know neither how did you implemented the folder contents features but there are many other nice feature on that plugin that could be very useful.

**Comment by djowett** [comment]
Not wanting to teach Grandma how to suck eggs*, but if this is any help, this is gist showing [an Image Dimension Validator for Plone 4+ that works with (the Dexterity based) plone.app.contenttypes](https://gist.github.com/djowett/3470ec60f1e0f1c7d486)

* I never got this analogy - no-one ever told me how to suck eggs ... or indeed why you would want to

**Comment by jaroel** [comment]
Make the UI select the largest non-original size by default.

**Comment by jaroel** [comment]
This has been resolved by selecting the largest scale that isn't 'original'.
See https://github.com/plone/mockup/commit/791cde54ce03c72f5a105879e4dc76576692d6af
