### ISSUE TITLE
update what appears in default front-page for all new Plone sites

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#466]
This content should be reviewed & updated, especially for Plone 5:
 Products.CMFPlone/Products/CMFPlone/browser/templates/plone-frontpage.pt

**Comment by jaroel** [comment]
@tkimnguyen Could you do this/find someone to do this on short term? Where "short term" is before shipping Plone 5?

**Comment by tkimnguyen** [comment]
Yup, will get a draft done this week

**Comment by jaroel** [comment]
Awesome!
