### ISSUE TITLE
Not easy to move content between sites

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#468]
## User problem
Such has moving content from a staging site to a production. In particular this supports a use case where you need two replicated sites where you use one to stage large complex changes of content across a site which can be reviewed and then committed/published in a single transaction.

Currently you can do zexp export but you need FS access to import.

see [provide-a-solution-to-permit-asynchronous-replicat](http://plone.uservoice.com/forums/20503-plone-improvement-ideas/suggestions/735858-provide-a-solution-to-permit-asynchronous-replicat)
and https://trello.com/c/e4BCKA8I/35-not-easy-to-move-content-between-sites

## Internal

I think part of the problem here is security concerns. If you move zexp's around like the zsyncer plugin did you are moving pickles and potentially bypassing security checks,

Asko as been working on support for GS inside a Diazo theme zip which could provide a TTW way to move content between sites. You could freeze some content into GS inside a theme, download it as a zip and then upload it to another site. see https://github.com/collective/collective.themesitesetup

## Options

1. Include a way to export parts of the content tree inside a theme and use themes to transport content between sites. As the added bonus that enable public themes to come with sample content. see collective.themesitesetup.

2. Something like https://pypi.python.org/pypi/Products.ZSyncer but perhaps not as such a lower level such that there are security concerns. This is a nicer UI if you regularlly sync parts of your content to another site. 

3. ??

**Comment by pigeonflight** [comment]
Could we borrow ideas from Products.QuickImporter? The user experience is
not the nicest but it has worked for me. It might be worth looking at.

**Comment by thet** [comment]
There is also collective.jsonify, which can be used to export individual objects and whole sites to the JSON format. For importing, you'd need a transmogrifier pipeline, which doesn't exactly fullfill the "easy" requirement.

**Comment by djay** [comment]
duplicate of #1373. Will close and merge this one.
