### ISSUE TITLE
no out of the box way to include dynamic or rich content into the text of a page

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#469]
## User Problem

An editor would like to have page with a listing of a particular folder embedded inside the middle of the text or of a table cell, for example. They also might like to insert an embedded video player.

Plone provides only portlets and diazo out of the box.
## Options
1. You can use a combination of portlets and something like the PortletPage plugin. A listing portlet comes built into Plone. PortletPage provides limited layout and portlets are opinionated about borders and structure so this approach is only really good for "rows of boxes" type layouts.
2. Diazo can be used by defining a style which can be applied to a link or image or other text and then using rules to transform this into more complex html. For example you can use a style on a link to turn it into an embedded video player. You can use a custom style on a list of images to turn it into a carousel. With some like HTMLFragments you could possibly use a custom style applied to a relative to a folder or collection into a folder listing. This approach is kind of clumsy and not obvious. It doesn't provide an UI for selecting more parameters.
3. Shortcodes. CMS's like Wordpress provide a way to include dynamic content via codes entered into the visual editor. The result is not WYSIWYG but an UI could be used to aid in editing shortcode parameters. This approach could be combined with the tile/mosaic approach. See http://plone.293351.n2.nabble.com/VIDEO-Simplifying-Plone-with-tiles-and-shortcodes-td7570629.html
4. Mosaic/collective.cover. Dynamic content can't be inserted into text but the page can be divided into smaller areas of text laid out in a grid. Tiles can be added and configured by the user. It's not clear what control the themer has over where and when the tiles can be used but they should be able to style the resulting HTML. 
5. ??

**Comment by frisi** [comment]
option 3 is implemented in: https://pypi.python.org/pypi/collective.easytemplate/

**Comment by vangheem** [comment]
I think plone.app.mosaic is our answer here.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
