### ISSUE TITLE
UnicodeDecodeError on catalog queries with a unicode value for Subject field

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#470]
Catalog queries break with a `UnicodeDecodeError` when querying the Subject field with a unicode value, but only if there is a subject value indexed with characters out of the ASCII character set.
It looks like only the `Subject` field is affected by this bug. In a project, another `KeywordIndex` works fine when queried with unicode values!

Here some steps to reproduce, given a plain Plone 5 or Plone 4 site:

```
>>> doc = app.Plone['front-page']
>>> doc.Subject()
()
>>> doc.subject
()

Querying works fine:
>>> context.portal_catalog(**{u'Subject': u'ähnü€'})
[]

Now, add some Keywords:
>>> doc.subject = (u'test', u'ähnü€')
>>> doc.reindexObject()
>>> doc.Subject()
('test', '\xc3\xa4hn\xc3\xbc\xe2\x82\xac')
>>> doc.subject
(u'test', u'\xe4hn\xfc\u20ac')

Now, querying:
>>> app.Plone.portal_catalog(Subject=u'test')
Traceback (most recent call last):
...
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
>>> app.Plone.portal_catalog(Subject=u'ähnü€')
Traceback (most recent call last):
...
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

Encoding works:
>>> app.Plone.portal_catalog(Subject=u'test'.encode('utf-8'))
[<Products.ZCatalog.Catalog.mybrains object at ...>]
>>> app.Plone.portal_catalog(Subject=u'ähnü€'.encode('utf-8'))
[<Products.ZCatalog.Catalog.mybrains object at ...>]
```

**Comment by ida** [comment]
FWIW, I had the same prob in an addon, fixed by first replacing funny asciis with html-entities:

    string.encode('ascii', 'xmlcharrefreplace')

And then using genious F. Lundhberg's `unescape`-method to reconvert to utf-8-chars:

    string = unescape(string)

You can find it on:
http://effbot.org/zone/re-sub.htm#unescape-html

**Comment by thet** [comment]
I didn't come across any unicode decode errors on the subject field in recent years.
#closingissues
