### ISSUE TITLE
`edit-bar` still shown on public page when default theme is deactivated.

### ISSUE THREAD

**Issue by ivanteoh** [plone/Products.CMFPlone#471]
When I deactivate the default theme in Plone 5.0a3, The `edit-bar` still there on the public front page. I believe it shouldn't be there.
![ubuntu_64_1204 running - oracle vm virtualbox_482](https://cloud.githubusercontent.com/assets/900434/7426682/c9fdc844-f00e-11e4-8fff-07db0a079bd0.png)

**Comment by vangheem** [comment]
What version? What do you mean by "When I deactivate the default Plone"? I can't reproduce this.

**Comment by ivanteoh** [comment]
Typo on my comment. Added screen shot and Plone version.

**Comment by vangheem** [comment]
Still doesn't make sense. What do you mean by "When I deactivate the default theme"?

**Comment by ivanteoh** [comment]
When I go to `theming-controlpanel` and deactivate `Barceloneta Theme`. 
![ubuntu_64_1204 running - oracle vm virtualbox_483](https://cloud.githubusercontent.com/assets/900434/7426770/e104b0c8-f010-11e4-865f-4c827f812d69.png)

**Comment by vangheem** [comment]
Ah I see. Not sure what you are trying to accomplish by disabling a theme though.

**Comment by ivanteoh** [comment]
I was playing around the new theme and accidentally found. :)
