### ISSUE TITLE
_authenticator querystring param continue to be used on every page

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#473]
Is OK that the ``_authenticator`` querystring is used everywhere also for normal site navigation when authenticated?

**Comment by vangheem** [comment]
It's not used everywhere, just in places where it will need it--when plone writes on read requests. It is not used in navigation. Main place it's used is for the edit bar stuff.

It's not great that it's in the urls but it's the best solution we have until zope/plone take care of all the write on read problems.

**Comment by keul** [comment]
@vangheem sorry but I see a different behavior (master buildout updated 1 ours ago): I simply go to http://localhost:8080/Plone then if I click on "View" button in toolbar the link became http://localhost:8080/Plone/front-page?_authenticator=42b49a388557daa779425bccf853e17b1c708f4a

Apart of that: not a big issue, just an ugly URL

**Comment by vangheem** [comment]
Right, "View" is part of the edit bar. 

Maybe we should update portal_actions to be able to opt-out of adding in the _authenticator. Right now it's a catch-all thought for dealing with archetypes write on read for a few different portal actions.

**Comment by keul** [comment]
@vangheem thanks, get it

**Comment by davilima6** [comment]
Can we reopen this to pass `_authenticator` as a POST parameter? GET would then be a fallback for JS-disabled devices.

As commented in: https://github.com/plone/Products.CMFPlone/issues/668#issuecomment-122291194
