### ISSUE TITLE
_authenticator querystring param is not added on links for adding new types

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#474]
I'm trying on Plone 5 and old-style product (not DX based). I installed Archetypes so I can rely on the old `createObject` script, but when I click I finish in the CSRF confirmation page as the generated link is "http://localhost:8080/Plone/test-tema-nl/createObject?type_name=...".

Manually adding the `_authenticator` in the link will fix the issue. Can this be added to all elements of the factory menu? Or at least to all non-dexterity ones?

**Comment by vangheem** [comment]
Yes, it should be getting added.
