### ISSUE TITLE
Visual overlay problem with toolbar

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#476]
Opened the toolbar over a form using ACEditor does not look that good.
(Latest Safari on Mac)

![screenshot 2015-05-02 17 58 18](https://cloud.githubusercontent.com/assets/594239/7441718/dabb93a0-f0f4-11e4-94e9-317cc7165115.png)

**Comment by vangheem** [comment]
Since that is not a plone core reproducible problem, can you provide the
necessary z-index to fix this(or other rules)

**Comment by zopyx** [comment]
.plone-toolbar-left {

z-index: 5;
}

or a higher z-index solves the problem.

Since Plone uses ACeditor itself for Diazo there is the chance that it
affects Plone core as well. Since the overlay is supposed
to overlay all Plone elements I suggest that it should have a higher
z-index by default.


2015-05-02 21:00 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

> Since that is not a plone core reproducible problem, can you provide the
> necessary z-index to fix this(or other rules)
