### ISSUE TITLE
Add-on control panel wonky. Not listing all installed products.

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#478]

**Comment by tomgross** [comment]
Is this related to https://github.com/plone/Products.CMFPlone/issues/478?

**Comment by vangheem** [comment]
#478 is this issue :)

**Comment by tomgross** [comment]
https://github.com/plone/Products.CMFPlone/issues/527

**Comment by jaroel** [comment]
Superseded by #527

**Comment by jaroel** [comment]
My bad.

**Comment by jaroel** [comment]
Got an example?

**Comment by vangheem** [comment]
Closing this. I have no example right now. It might have been related to the other issue.
