### ISSUE TITLE
Toolbar: Actions not accessible when in horizontal mode

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#481]
Actions (Cut, Copy, Delete, ...) are not accessible, because there is no vertical scrollbar:
![horizontal-toolbar-actions](https://cloud.githubusercontent.com/assets/191024/7444754/ed842698-f192-11e4-8646-40784d8e1045.jpg)

**Comment by vangheem** [comment]
Closing as duplicate of https://github.com/plone/Products.CMFPlone/issues/482

**Comment by vangheem** [comment]
Close as duplicate of https://github.com/plone/Products.CMFPlone/issues/482 and https://github.com/plone/Products.CMFPlone/issues/529
