### ISSUE TITLE
Toolbar: commonly used menu items to hard to get to or not where you expect

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#482]
# User Problem

1. The current layout of the toolbar makes some common options hard to get at (#177)
  - actions (cut, copy, delete, rename, ...) 
  - last modified and "content type" should be visible on toolbar without an extra click
  - its not clear we have the most commonly used items at the top
  - the content buttons needs to be shown at all times
2. In addition the way "more options" works is that all these menus are open which means "more options is far too long causing scrolling, or in horizontal mode with default view prevents you from being able to select all choices at all: #481
3. The u-turn mouse movement to back up to the top of "more options" is not nice (#663)
3. Some percentage of editors will be trying to do content editing on mobile
   - its not clear if this is realistic or what the most common actions for this group are
   -  fix liquidness: #528
   -  buttons are too wide and do not fit well as screen narrows. 
4. The user group "plugin developers" need a clearly defined way add UI for their plugins.
  - Currently we have
    - portal_actions/document_actions (rss, print, full_screen, extedit)
       - full_screen and extedit are backend and rss and print are front end. Do plugins use this?
    - portal_actions/object (Contents, Syndication, Rules, Sharing)
      - Lots of plugins use this e.g. plomino (Properties, About, ACL, Replication,Design, Using)
    - plone.app.contentmenu - [how to add](http://stackoverflow.com/questions/6272578/how-to-override-plones-display-menu-for-special-case-content). plugins add to this but which?
    - portlets - some are meant for edit/backend only such as the review portlet, quickupload, plominos quick add portlet. These really make sense being in the toolbar somewhere.
5. Both vertical and horizontal modes are supported. Both need to work equally well for editors otherwise we are better off just having one.
  - if both needs to be configurable
  - both need to not ensure they don't cover important elements of the themed page making it hard the user to use their site while logged in.

![toolbar-actions](https://cloud.githubusercontent.com/assets/191024/7444814/f197b418-f195-11e4-9c94-983e64c4ec41.jpg)  ![plonetoolbar](https://cloud.githubusercontent.com/assets/6492010/8478909/a417d600-20d4-11e5-831f-80d5b8cdb868.jpg)

# Options (tick to eliminate)
1. [x] move actions, display and portlets to the top level
2. [ ] Change the style of toolbar flyout menus in vertical mode
  - [ ] accordion menus that are sticky - ie can be set to remain open. ie go below the item
     - con: requires scrolling toolbar
  - [ ] horizontal flyout. would need to thick so its easy to hit
     - con: only really works for short menus like actions or personal tools. 
  - [ ] fat horizontal flyout - ie horizontal flyout that wraps if its too long
  - [x] drop down that starts to the right of the item
     - con: can go off the bottom of the screen on short screens
  - [ ] use a modal popup for long menus like "add new" or "display".
3. [ ] you can rearrange the menus yourself.
  - or maybe create shortcuts easily to menu items you use a lot
4. Reduce the items in toolbar so we can get rid of "more options". see [mockup](https://gomockingbird.com/projects/qh6s0uy/4gXVnC)
  - [ ] get rid of "view". Replace it with a close icon inside the UI for each backend UI page.
  - [ ] move display into edit form
     - pro: people don’t understand it and click on it by mistake often screwing up their landing pages. inside edit could give more context. #704
     - pro: could give more space to explain default pages - see #519
  -  [ ] move state into edit form
     - pro: you can save and publish in one action which takes two now
     - pro: makes publishing a post request
     - pro: you can fast publish in contents anyway. It’s two clicks the same as more options.
     - con: takes two clicks to publish something
     - con: you lose the ability to see what the current state of the item is
   - [ ] merge sharing and state into one form
     - conceptually this are related and work together. State determines which riles are "active" and sharing determines who has those roles. For example a "extranet" hidden folder is achieved by using state: private and adding users to the viewer role. By bringing these together we are showing that relationship
     - pro: could help explain how sharing and workflow work together #462
     - pro: will help to change state of folder of a default page (#461)
     - con: extra click and load to change state.
       - is this offset by it being so quick to change state in "contents"?
    - [ ] move sharing into the state dropdown. (and probably rename it sharing)
6. work out how to handle an arbitrary items in the toolbar (added by plugins)
    - [x] scrolling toolbar - autoscroll when you get to the bottom. swipe on mobile
    - [ ] wrap it
    - [ ] have an optional "more..." only when screen isn’t long enough
    - [ ] any plugins that add to object tabs goes into "extra options" but content menus go at the top level.
    - [ ] vertically just make the page longer and use normal page scroll. Make personal tools stick to the bottom
    - [ ] horizontally 
7. [x] Put last modified (and user) into main toolbar and combine rest of the content info into the history page.
8. [ ] Edit button could be menu when a default page
   - pro: make it easier to edit a folder when its has a default page #461
9. [ ] "Add new" should be a form rather than a menu
   - the menu can be too long
   - pro: gives us a place to explain what the types are. Maybe show previews
   - pro: gives us a place to let you select where the object should go. see #464
   - con: its an extra click.
     - but then you are going to load the edit form after anyway so does the user care?
   - con: can't see whats addable in the current context without the extra click. does the user care?
10. [ ] Put dashboard portlets into the toolbar perhaps as extra popout bar. 
   - pro: provides natural place for plugins to provide UI elements which are backend (e.g. plomino, review portlet etc).
   - pro: is configurable by the user to put in shortcuts

**Comment by thet** [comment]
Agree. The display menu is also essential, for me even more than the actions menu (I prefer cut, paste, etc to do in the folder contents view).
IMO, the content info is not important and could be moved into the "more" menu.

**Comment by vangheem** [comment]
I think I agree. We need a better discussion on everything on the toolbar--not just actions.

**Comment by 3dogMcNeill** [comment]
I keep expecting to see the "Display" options under the "View" icon/menu.

**Comment by tomgross** [comment]
@3dogMcNeill me too!

**Comment by djay** [comment]
Hope you don't mind @jcerjak but I updated your issue to make it more problem centric and to encompass the bigger underlying issue with "more options".
Anyone feel free to add any options I've missed.

I've also made a mockup of what the toolbar could look like if we implemented these and some other ideas.
https://gomockingbird.com/projects/qh6s0uy/4gXVnC

**Comment by jcerjak** [comment]
@djay :thumbsup:

**Comment by vangheem** [comment]
@plone/ux-team please review @djay changes to this ticket.

**Comment by bloodbare** [comment]
So we wrote down the specific scope for toolbar on Arnhem Sprint

* Document by line integrated on the toolbar (remove the suboptions, add timeago on the toolbar and the time of the last edition, link to the history modal and style it)

* All the options (remove the more options option and expand them with a portlets/display/actions). In vertical and horizontal make them scrollable.

* Move suboptions to the place where is the parent. When choosing a toolbar point of the menu move the suboptions to the place where is the option.

* No changing side option. Toolbar left/top should be defined on the configuration of the site (no cookie)

* Option to change the icon. Adding an option to change the icon of the toolbar.

**Comment by djay** [comment]
Also decided that all the ideas around reducing the number menu options such as display inside edit, no view button, combining sharing and workflow etc, are too risky for plone 5.0 and will have to be done as extensions or a 5.1 release.

**Comment by djay** [comment]
in terms of getting rid of the view menu option to make space, how hard do you think it would be to
- have a viewlet  that put a close button on any view that wasn't the "view"?
- put a body tag on any view that wasn't the "view" so the themer can style their back end separate from the front if they want without having to use URLs
- have a way for a plugin developer to 
register  their view as either frontend or back end - ie  wouldn't have body tag or close button if frontend. but also not the default view of an object. eg @@search or sitemap
maybe I'll try and have a look at this @bloodbare @vangheem.

**Comment by djay** [comment]
Some feedback on testing. Generally looking very slick. 

[ ] scrolling. scrolling past the end of the toolbar scrolls the content panel works great. But on mobile swiping the the content panel also seems to scroll the toolbar which isn't desirable.
[ ] not sure how you scroll without a scroll wheel on a desktop. maybe the scrolling of the main page and toolbar should be tightly linked in that case so you can use the main scrollbar?
[ ] need some indicator to show when some menu items are hidden
[ ] would be good to swipe right to close the menu on mobile
[ ] on each page load on android chrome it seems to open the toolbar and then close it again
[ ] drop downs seem to fly down from above
[ ] "contents" should be always visible. on first login nothing the toolbar is empty. probably "add new" should always be visible too. Actually everything should be in there. If you are adding a new Page, you are still in the context of the folder so shouldn't the toolbar reflect that?
[ ] content info, sharing and "view" should be lower. I don't think you actually need to click on "view" that often.
[ ] not sure we need to highlight "view" in the toolbar
[ ] show the context content type under "edit"
[ ] could fit last modified by on the content info button
[ ] could fit the currently selected display view on the display button
[ ] login link is partially hidden behind search when not logged in. (not toolbar related I know)
[ ] previously you could click on contents to publish a folder with a default view. Now you can't.

**Comment by djay** [comment]
would be good to get some more feedback from the rest of the @plone/ux-team.

**Comment by djay** [comment]
<img width="395" alt="screen shot 2015-07-16 at 12 18 35 am" src="https://cloud.githubusercontent.com/assets/41700/8704972/b0475dca-2b50-11e5-93b2-8edce97a45c8.png"> 
Here is the current state of the toolbar now for those who don't a working dev buildout

**Comment by vangheem** [comment]
sorting placement of the items is hard and we don't have as much control over it as we'd like...

**Comment by djay** [comment]
@vangheem yeah I can understand the p.a.contentmenu vs object tabs infrastructure underneath makes that hard.
However the big problem is when plugins add object tabs. If the way the toolbar works now is [object tabs] + [content menus] then its going to unworkable once you get plugins like plomino that will push the contentmenus off the page. Just adding in redirection tool and placeful workflow adds two more items to the toolbar.

**Comment by vangheem** [comment]
They are mostly edge cases. Most screens for editors of a CMS, using vertical mode, will fit at least 14 items in there.

**Comment by djay** [comment]
Not so sure about that. Going to be really annoying on mobile if you have to scroll every time to use "add new".

BTW, @vangheem There is a simple version of merging the state and sharing menus that we can do easily now. Move sharing into the state menu. Then you reduce the items by one.
I really do think sharing and workflow are tightly related ... we just have training ourselves not to think that way. 
and probably that menu is better called sharing than state. Sharing private, sharing published.

**Comment by vangheem** [comment]
It's going to be really annoying to use any CMS on mobile. We aren't optimizing for mobile--just making it useful.

**Comment by vangheem** [comment]
@djay I agree with merging state and sharing; however, even at the sprint it's not convincing to everyone. I don't think we'll get it this time around.

**Comment by djay** [comment]
@vangheem what if sharing was put into the state menu the same way workflow policy was. Simple enough to do now and everyone can try it for the next week and see how they like it. Easy enough to reverse. 
Most people will admit sharing is not an option that gets used very often so it makes sense it shouldn't be taking up room.

**Comment by davilima6** [comment]
I'm -1 for merging Sharing and State, especially for 5.0. We just changed theme and lots of interfaces so we could balance that by maintaining some information architecture in place, if it's not broken (too much of a change just to save space). If you commit to that Sharing link should remain outside of Workflow dropdown.

I agree that in many Plone installations it's very rarely used but not on Intranets and other permission oriented websites for sections and documents. Also I think it's good for marketing to just have Sharing there, just to rapidly reveal how powerful the CMS is.

**Comment by djay** [comment]
Its not just about saving space. Sharing and state are conceptually linked
but in a way that's not obvious to first time users. Sharing determines
what a person can do and state determines when they can do it. I haven't
met any user who I haven't had to specifically train to for example  create
a restricted area ie  by telling them you set to private and then add
people to "can view". Bringing sharing and state closer together is just
the first step in a series of changes I'd like to make to this power much
clearer to users. Having sharing separate currently undersells the power
you want to advertise IMO.

**Comment by davilima6** [comment]
I completely agree they are linked and liked your explanation of Who, What and When. Maybe those are terms that can be used or at least guide a future interface merging - it'd be nice to run usability tests on that.

**Comment by djay** [comment]
Thought i'd upload video of the cool work being done by the sprinters at Arnhem (@vangheem @bloodbare @agitator and others) on the toolbar in case anyone else in @plone/ux-team has any additional early feedback. Other than a few glitches in mobile (RHS) mode it seems to be working well.

![toolbarsprint](https://cloud.githubusercontent.com/assets/41700/8715357/6eb637dc-2baa-11e5-9dc8-084a2e7b9982.gif)

For anyone wanting to test it out themselves for remote testing like me, it's the coredev buildout, 5.0 branch and then $ bin/buildout -c plips/plip-toolbar.cfg

**Comment by djay** [comment]
whats the rational behind the toolbar moving to the right on mobiles?
Wouldn't it be better to be consistent?

**Comment by bloodbare** [comment]
Its on the right because most people are right handed!

**Comment by vangheem** [comment]
Closing this issue as the PLIP was merged. @djay Can you create a new issue that will specifically be for Plone 5.1 so we can continue iterating and improving the editing experience? Thanks.

**Comment by djay** [comment]
@vangheem yeah I'll split it out so all the major left over ideas will get looked at.

**Comment by djay** [comment]
@vangheem I think I covered all the important ideas and issues. Not sure about the idea of an automatic "more..." button. We only need that if the scrolling idea fails to work in testing.

**Comment by vangheem** [comment]
Agreed. Thank you.

**Comment by djay** [comment]
@bloodbare what if the site isn't mobile responsive? do you have to scroll right to get to the menu after each page load?

**Comment by vangheem** [comment]
If the site isn't mobile responsive, aren't pixels shown at different amounts so our responsive toolbar settings won't take affect?
