### ISSUE TITLE
Remove navtree_properties.idsNotToList?

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#486]
I just stumbled across another portal property that is not included in the control panels. I guess this attribute allows you to list ids that are excluded from the navigation.

We should either remove the setting entirely, or implement it properly (adding it to the control panel, adding tests, etc.). I would recommend to remove it, since it seems nobody ever cared about that feature after all.

I'd be willing to remove it. If we want to keep it, somebody else needs to step up to do the work.

**Comment by vangheem** [comment]
+1 on removing it. It's good to remove some of the old technical debt when possible. There is already a hide from nav setting for content.

**Comment by fulv** [comment]
-1, I think it's useful, and it's not hurting anyone.  What's the downside
of leaving it in place, until it's properly added to the control panel,
tested, etc?

**Comment by thet** [comment]
+1 for removing also from my side. the navtree portlet's implementation is way too complex. the setting does not add much on top of it, but it does at least a little.

**Comment by vangheem** [comment]
If it's untested, the downside is that every knob adds complexity to project.

**Comment by tisto** [comment]
@fulv downside is that we have to keep old code when refactoring and cleaning up. We also have to put efforts into amending tests, etc. As I said. If someone is willing to do that, fine. Personally I will not put effort into supporting features that were never fully implemented, tested or documented.

**Comment by fulv** [comment]
@tisto > _supporting features that were never fully implemented, tested or documented._
Following that logic to its extreme conclusion, there would be very little left to support.
Don't get me wrong, I don't disagree with you at all, and I certainly have no room to talk, given that I can't volunteer to do that work right now.  Just trying to keep some perspective.

**Comment by fulv** [comment]
I can explain my -1 further:  every time some TTW functionality is removed, I think we lose a lot more than we gain by just removing complexity.

**Comment by tisto** [comment]
@fulv I'm not saying we should remove all features that are not fully tested or documented. We are talking about a feature here that most likely never really worked and was never really used by anybody. 

We should just decide if we really want a feature (and then put effort into doing it right) or get rid of it (if nobody finds it useful enough to put some effort into it). Therefore feel free to step up for working on it, if you find this feature useful. If nobody steps up, I don't think it is fair to expect somebody else to do the work.

**Comment by fulv** [comment]
@tisto I, for one, have used it.  I'm not expecting somebody else to do the work.  All I'm saying is that removing it is work, too.  If not removing it is an option, then it should be considered.  I understand that for some refactoring this might not be an option, and I'll make my peace with it.

**Comment by tisto** [comment]
At some point we will have to get rid of portal properties. If we want that feature in the future, we have to move it to plone.app.registry. Removing it right now is less work than keeping it, this is the only reason why I want to get rid of it now, otherwise I would just leave it as it is.

**Comment by thet** [comment]
I grep'd for ``idsNotToList``, and it looks like it's properly implemented, well tested and used not only in the navigation portlet, but also for contentlistings and probably the sitemap. See the grep results below. It was always possible to set ``idsNotToList`` via properties.xml.

I think the decission on removing this setting should be discussed in the FWT and needs a (simple) PLIP. A PLIP, pointing to this discussion here should be enough.

```
Products.CMFPlone/Products/CMFPlone/browser/navtree.py:119:        for id in navtree_properties.getProperty('idsNotToList', ()):
Products.CMFPlone/Products/CMFPlone/browser/navigation.py:218:        idsNotToList = self.navtree_properties.getProperty('idsNotToList', ())
Products.CMFPlone/Products/CMFPlone/browser/navigation.py:220:            if not (item.getId in idsNotToList or item.exclude_from_nav):
Products.CMFPlone/Products/CMFPlone/profiles/default/propertiestool.xml:16:  <property name="idsNotToList" type="lines"/>
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:81:        # Make sure that items whose ids are in the idsNotToList navTree
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:97:    def testNavTreeExcludesItemsInIdsNotToList(self):
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:98:        # Make sure that items whose ids are in the idsNotToList navTree
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:101:        ntp.manage_changeProperties(idsNotToList=['folder2'])
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:109:    def testShowAllParentsOverridesNavTreeExcludesItemsInIdsNotToList(self):
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:110:        # Make sure that items whose ids are in the idsNotToList navTree
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:113:        ntp.manage_changeProperties(idsNotToList=['folder2'],
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:136:        # Make sure that items whose ids are in the idsNotToList navTree
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:635:    def testTabsExcludeItemsInIdsNotToList(self):
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:636:        # Make sure that items whose ids are in the idsNotToList navTree
Products.CMFPlone/Products/CMFPlone/tests/testNavigationView.py:642:        ntp.manage_changeProperties(idsNotToList=['folder2'])
Products.CMFPlone/docs/HISTORY.txt:9682:  news.pt).  Added support for the property 'idsNotToList' from
plone.app.contentlisting/plone/app/contentlisting/tests/integration.rst:231:    >>> navtree_properties.idsNotToList = [news.id]
plone.app.contentlisting/plone/app/contentlisting/tests/integration.rst:238:    >>> navtree_properties.idsNotToList = []
plone.app.contentlisting/plone/app/contentlisting/contentlisting.py:140:        if self.id in list(navtree_properties.idsNotToList):
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:163:        # Make sure that items whose ids are in the idsNotToList navTree
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:179:    def testNavTreeExcludesItemsInIdsNotToList(self):
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:180:        # Make sure that items whose ids are in the idsNotToList navTree
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:183:        ntp.manage_changeProperties(idsNotToList=['folder2'])
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:191:    def testShowAllParentsOverridesNavTreeExcludesItemsInIdsNotToList(self):
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:192:        # Make sure that items whose ids are in the idsNotToList navTree
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:195:        ntp.manage_changeProperties(idsNotToList=['folder2'], showAllParents=True)
plone.app.portlets/plone/app/portlets/tests/test_navigation_portlet.py:217:        # Make sure that items whose ids are in the idsNotToList navTree
```

**Comment by fulv** [comment]
@thet +1 for the PLIP

**Comment by jensens** [comment]
+1 for PLIP 
-1 (based on my current knowledge) for removal)

**Comment by fulv** [comment]
To add one more (shaky) data point, maybe someone can confirm this:  I
vaguely recall reading about this in one of those old books about Plone
that were published years ago.  I don't have them around anymore, so I
don't know for sure.  While possible, I think it's unlikely that I would
have stumbled on this setting while poking around the ZMI.

**Comment by tisto** [comment]
Ok. I will stop working on that. I was hoping to quickly clean that up things before beta2. I wasted enough time going through broken, untested and undocumented code that nobody ever seems to have used, when working on the control panels (lots of things are still broken there btw. and have been broken since quite some time without anyone ever noticing). We will just do another 80% job adding new stuff without removing the old cruft.

Things that would be needed if we want to keep that setting:

1) Confirm that this setting is actually used by people
2) Research why this setting hasn't been added (or has been removed) from the control panel. There might be a good reason why it's not there.
3) Document that feature
4) Make sure we have proper integration tests for it
5) Write robot tests to make sure the setting works, that's also important for documentation
6) Move from portal properties to plone.app.registry and add it to the navigation control panel 

It seems we are neither willing to give up functionality nor willing to put any effort into fixing things. That is not going to work. Feel free to re-open if anybody is actually willing to do something.

**Comment by djay** [comment]
I think big issue is we haven't thought of a good way to research what
features are used.
Tryibf to think if there is some clever low impact way to find out.
Maybe some js bookmarklet that can survey or grab selected settings and
upload them. Then we work hard to get a list of people willing to run it on
their sites? If they only have to login and click one button maybe we can
get a lot of data about non sensitive settings very quickly?

**Comment by thet** [comment]
@tisto - if it was really broken, the removal might not even have to be discussed. but since it is properly unit-tested, properly implemented and NOT broken, a removal must go with a formal decision of the FWT - IMO.

if this feature is holding us back for getting rid of portal_properties entirely, i think the decision could easily go towards removal. also, i can't think of a good use case, why hiding navigation items based in their ID is a good thing. can anyone provide some use cases, please? @fulv ?

@tisto are we getting rid of portal_properties entirely for Plone 5.0? it would be GREAT, but i don't have this impression.

**Comment by jensens** [comment]
Looking deeper into it i ask myself why we have _global_ navtree properties at all? Navtree is a portlet, a portlet has its settings stored on its own. 

Then: ``plone.app.contentlisting/plone/app/contentlisting/contentlisting.py`` uses a navtree setting here? Totally wrong and confusing.

Also to consider: Sitemap - we need to check how far this affects it.

So these settings are more or less default values for all portlets plus some places outside navtree. 
I think we have a conceptional problem here - ghosts from the past left from times before Plone 3.

**Comment by fulv** [comment]
To answer @thet's question, re: use cases:  IIRC, on one site the client wanted the ability to provide some simple custom styles per section or subsection TTW;  I modified the main template to load a stylesheet with a specific id, say `mycustomstyle.css`;  then the client could upload a css file anywhere they wanted, give it that id, and through acquisition they would get the most spcecific css file available, with a fallback at the site root where there was an empty one.  Adding just the id `mycustomstyle.css` to `idsNotToList` would avoid having to remember to "exclude from navigation" every one of those specific files.
