### ISSUE TITLE
Remove old discussion infrastructure

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#488]
At least in Archetypes is old discussion code which is stated to be removed in Plone 5. I guess we should remove it now or it will sit there forever ;-)

@tisto as author of plone.app.discussion what do you think? Do you know other spots?

**Comment by jensens** [comment]
+1

@tomgross iirc you already removed parts of it in AT? I cant find the PR atm.

**Comment by tomgross** [comment]
I reverted the changes I did when removing CMFDefault. This should be seperate.

**Comment by tisto** [comment]
@tomgross yeah. We should remove that code. I think we removed the old discussion code from all other packages already.

**Comment by davisagli** [comment]
Archetypes is no longer supported in Plone 6
