### ISSUE TITLE
Remove CMFDefault from Plone 5

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#489]
The following tasks are pending for complete CMFDefault removal in Plone 5:

 - [x] Port imaging control panel to z3cform https://github.com/plone/plone.app.imaging/issues/12
 - [x] Fix failing tests in https://github.com/plone/Products.PortalTransforms/tree/tomgross-nocmfdefault
 - [x] Remove dependency in Products/CMFDynamicViewFTI/content_for_tests.py
 - [x] Merge https://github.com/plone/plone.app.testing/pull/13
 - [x] Merge https://github.com/plone/plone.app.content/pull/29

**Comment by tomgross** [comment]
Any takers for Task 1?

**Comment by vangheem** [comment]
I'll give task 1 a try.

**Comment by vangheem** [comment]
pull requests are made for #1 -- should be able to merge at any time.

**Comment by vangheem** [comment]
imaging changes are merged.

**Comment by tomgross** [comment]
@vangheem Thanks!

**Comment by tisto** [comment]
@vangheem awesome!

**Comment by tisto** [comment]
I guess CMFDefault is really gone now: http://jenkins.plone.org/view/Dependencies/job/plone-package-dependencies-cmf/lastSuccessfulBuild/artifact/deps/Products.CMFDefault.txt

Thanks @tomgross (and @vangheem for the image control panel work)! Fantastic work!!!

**Comment by tomgross** [comment]
:+1: I guess we can merge https://github.com/plone/buildout.coredev/pull/79 then and close this issue
