### ISSUE TITLE
barceloneta less file still appear even barceloneta theme is uninstalled.

### ISSUE THREAD

**Issue by ivanteoh** [plone/Products.CMFPlone#491]
When you uninstall or deactivate barceloneta theme, less file from this theme still appear on the site.

![screenshot](https://cloud.githubusercontent.com/assets/900434/7487962/9f7ba1ea-f405-11e4-974e-74fa9862736d.png)

**Comment by vangheem** [comment]
Tested on master and I can not reproduce this issue. What version of plone are you on?

If you can reproduce this on master or when beta2 is released, please re-open.
