### ISSUE TITLE
Can't include custom styles menu items in a theme 

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#492]
## User Problem

If a themer creates a theme to be uploaded as a zip file and includes custom tinymce styles then these won't automatically appear in the tinymce style menu for the editors to use. 
The same applies to portlet styles if you use the portlet styles plugin. Also to styles in tiles with plone.app.mosaic.

## Internal

Currently the UI is in the tinymce control panel where most options are for the site admin rather than the themer. The settings are now stored in the registry in plone 5.

## Options

1. The theme could come with manual instructions on how to configure the menu items after the theme is activated and how to remove them after the theme is deactivated

1. Squarespace has a nice solution. Special comments in the LESS files. see http://developers.squarespace.com/style-editor/

2. Could put it in the manifest.cfg

3. [collective.themesitesetup](https://github.com/collective/collective.themesitesetup) installs GS on theme activation (or maybe manually). However it needs to install and uninstall when theme is deactivated. If the theme is deactivted then the menu items shouldn't remain as they won't do anything without the css.

4. Some kind of way of merging registry entries inside portal_resources similar to how lineage subregistries work. Possibly from a registry XML or yaml file. Nice in that it allows more than just styles to included in a theme but could be too technical for users. You have to know the internal registry names.

5. ??

**Comment by vangheem** [comment]
We've done this for tinymce on plone 5. The value in the manifest is: tinymce_content_css

**Comment by vangheem** [comment]
fwiw, latest tinymce provides an "importcss" plugin that'll automatically detect styles from a css file. Plone 5 integrates with this pulling in styles from the content_css theme setting. I think this solves this use case.

**Comment by djay** [comment]
How does this work? Is there documentation?
So we are getting rid of the tinymce styles control panel to prevent
confusion ?

**Comment by vangheem** [comment]
You provide a css file and tiny scans it and automatically uses styles found. It does not replace providing other styles. Styles in tinymce 4 are in groupings(headers, blocks, inline, alignment). It's not all in one big bucket like tinymce 3 was.

Right now, if you activate the plugin, it'll just use whatever you define for content_css--it's not very useful that way actually though because it includes too much. I suppose it might be useful to allow providing a tinymce-styles property in the theme manifest so you can have a smaller set of styles.

**Comment by vangheem** [comment]
Alright, here is how it works(notice discreet, pullout and portalMessage):

![screen shot 2015-05-09 at 1 13 28 am](https://cloud.githubusercontent.com/assets/524413/7548974/a96f8a60-f5e8-11e4-809b-186748267511.png)

And here is the css file that generates those three rules:

![screen shot 2015-05-09 at 1 14 51 am](https://cloud.githubusercontent.com/assets/524413/7548977/d4e22856-f5e8-11e4-8561-60a2fb087ea4.png)


Then, in your theme manifest, you can provide a value for tinymce-styles-css to customize these styles.

**Comment by djay** [comment]
cool. looks good. So has to be in a specially named .css file or has to be in the manifest to appear?
I've raised a documentation ticket to get it put into the manual. 
It would be good if this was less tinymce specific. For instance if we could use the same mechanism for include tile styles in a theme or other kinds of styles (like portlet styles which we use a lot)

**Comment by davilima6** [comment]
Seems to have been fixed in: https://github.com/plone/Products.CMFPlone/commit/03e1483dd73a23ad13f3c7f05d88ad62cde20c32

**Comment by davilima6** [comment]
What if my project doesn't include a theme? How else can I provide a value for tinymce-styles-css?

**Comment by djay** [comment]
@davilima6 we need an easy way to have a empty theme. Just need an empty html file and rules file that says to take everything from the content. Except perhaps injecting a single js and css file? Perhaps we need a shortcut button or preinstalled theme for this?

**Comment by davilima6** [comment]
Well, if my project doesn't need a theme, I'd rather not to have theme code in it. So -1 for empty theme just to inject css/js.

**Comment by hvelarde** [comment]
a theme is _a preset package containing graphical appearance details_ ([1](https://en.wikipedia.org/wiki/Theme_(computing))); including styles for TinyMCE must never be under the responsibility of a theme.

**Comment by djay** [comment]
Honestly I don't care about pedentry or wherever you dragged up a
definition to suit your ideas. Rename it to designers integration package
then because thats what a theme is in plone world. Its very rarely
predefined and almost always where the frontend developer determines what
the interaction between the content and the design and styles. Styles live
there.

**Comment by hvelarde** [comment]
no; a Plone theme is just a theme, not a "designers integration package"; that's only a definition you dragged up to suit your ideas.

the Diazo concept has been clear from day one: http://docs.plone.org/external/diazo/docs/index.html
