### ISSUE TITLE
Locking does not work in Plone 5 beta

### ISSUE THREAD

**Issue by juh2** [plone/Products.CMFPlone#497]
I don't get a locking warning in Plone 5 beta, when I edit a page, which is edited by someone else.

**Comment by vangheem** [comment]
Seems like locking support needs to be added for each type you want it for. I'll at it to the default types definition unless anyone disagrees?

**Comment by vangheem** [comment]
ref: https://github.com/plone/plone.app.contenttypes/pull/227
