### ISSUE TITLE
Site creation error: issues with language selection

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#503]
See https://dev.plone.org/ticket/20256#comment:3

Is plone.app.multilingual supposed to be installed by default?

The issues stems from  https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/language.py#L49 requiring plone.app.multilingual to be installed to return a vocabulary and having default_language use it as a vocab:  https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L124

Then, site creation uses this vocab:  https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/admin.py#L188 which isn't not what the value is validated against.

Right now, selecting anything other than english throws an error.

**Comment by vangheem** [comment]
cc @bloodbare

**Comment by vangheem** [comment]
Also, @ebrehault

**Comment by bloodbare** [comment]
Multilingual should not be installed by default. portal_languages tool is in plone.i18n https://github.com/plone/plone.i18n/blob/master/plone/i18n/utility.py#L128

I would say that gives this error because you need to set first the available languages and then the default language. The default language needs to be in the available languages, is it possible that is this error ?

**Comment by vangheem** [comment]
The vocabulary uses the portal_languages tool from plone.app.multilingual. Looks like it needs to be switched to what is used in plone.i18n. I'm looking into it right now.

**Comment by vangheem** [comment]
hhmm, I'm rather confused at how this ever worked....

**Comment by vangheem** [comment]
FYI, the problem was actually really subtle. The plone.app.upgrade branch that was used in the plip was not updated with master and Products.PloneLanguageTool was still specified in the setup.py. This caused the tool registration in plone.i18n to be overridden by Products.PloneLanguageTool.

**Comment by bloodbare** [comment]
Ouch !
