### ISSUE TITLE
Building resource bundle TTW may use outdated resources from browser cache

### ISSUE THREAD

**Issue by datakurre** [plone/Products.CMFPlone#504]
While creating a TTW resource bundles on a Plone 5b1 site in production mode:

1. Create TTW resources into portal_resources
2. Configure resource and bundle
3. Build bundle
4. Edit resource in portal_resources
5. Re-build bundle

Re-build may have used the initial version of custom TTW resources, not the latest versions. A temporary "fix" is to use force reload that particular resource using its direct url in browser or open a new private browsing window.

Clearly somehwere URLs should be postfixed with ?timestamps, but I'm not sure where and how hard would that be (because the build is done by less or requirejs).

**Comment by vangheem** [comment]
Thanks for reporting this. Fixing this issue might require patching r.js. Yes, this is a problem though.

**Comment by vangheem** [comment]
js fixed here: https://github.com/plone/Products.CMFPlone/commit/2d3865805efc6b72dce236eb68e502d8c57717b6

**Comment by vangheem** [comment]
Less fixed here: https://github.com/plone/Products.CMFPlone/commit/bd1f9ba99d1ad40bb7fe1c00eaa32b8884aae5e2
