### ISSUE TITLE
plone.schemaeditor reordering

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#506]
(this issue is connected to https://github.com/plone/buildout.coredev/blob/b0f0d74bb6b96b0293883bf9aff95805f19c8533/plips/reviews/plip13350-review-frapell.rst, we list it here so it appears in the Plone 5 milestone issues https://github.com/plone/Products.CMFPlone/milestones/Plone%205)

When trying to change field order, I get "plone.protect Error checking for CSRF." in my terminal, and the new order is not saved.

**Comment by ebrehault** [comment]
@frapell I cannot reproduce this issue (I add several fields to my schema, then I can reorder them the way I want).
Could you provide more details?

**Comment by frapell** [comment]
@ebrehault I removed all packages from src/ directory and re-ran buildout from scratch. Tried to create a brand new site, and ended up with this:

http://pastie.org/private/egffh8e9624zym7yhtuvsq

**Comment by ebrehault** [comment]
Oh right, makes sense, URI field types are not in the list.
Fixed (and I have also added datetime, as you asked)

**Comment by frapell** [comment]
This is what I see when trying to change field order by drag&dropping

(Javascript error in my chrome developer tools)

![drag_drop_error](https://cloud.githubusercontent.com/assets/851006/7613925/05c800ba-f96a-11e4-8a51-8b36fd9d1b6e.png)

This is on a fresh site on a fresh buildout run...

**Comment by ebrehault** [comment]
I have run `bin/plone-compile-resources` and I get the error too now.
So that's a new mockup regression I guess.

**Comment by frapell** [comment]
As long as the PLIP changes are not provoking this, I think we can close this and report it wherever relevant...

**Comment by vangheem** [comment]
Yes, I imagine this has nothing to do with this plip. That schemaeditor drag/drop code needs updating.

**Comment by ebrehault** [comment]
yes, schemaeditor js should be turn into a pattern.

Regarding the bug, the only (related) change I found is the upgrade from jQuery 1.11.1 to 1.11.2 8 days ago...

**Comment by vangheem** [comment]
I imagine it's not new. I'm sure this has been around since Plone 5 and just never noticed/fixed.

**Comment by ebrehault** [comment]
Oh no, that's new, it was working fine with Plone 5.0b1.

By the way @frapell, I think we should keep this issue open, even if it is not related to this PLIP, it is still an annoying bug for Plone 5.0 milestone (as it also impacts the Dexterity types control panel).

**Comment by vangheem** [comment]
I've fixed this with: https://github.com/plone/plone.schemaeditor/commit/7b7aae13f1c6188b8b3252374a44740354730a48

Regarding drag and drop... Since we're only supporting IE9+ anyways, we need to get rid of our jquery.event.(drag|drop) dependency and just use built-in browser stuff or something more lightweight. That js dependency has given us more trouble than what it's worth and AFAIK, the purpose is really only for support for older browsers.
