### ISSUE TITLE
CSRF warning when removing a field in user schema

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#508]
(this issue is connected to https://github.com/plone/buildout.coredev/blob/b0f0d74bb6b96b0293883bf9aff95805f19c8533/plips/reviews/plip13350-review-frapell.rst, we list it here so it appears in the Plone 5 milestone issues https://github.com/plone/Products.CMFPlone/milestones/Plone%205)

When deleting a field, I get "WARNING plone.protect error parsing dom, failure to add csrf token to response for url" in my terminal, however, the field is removed fine.

**Comment by ebrehault** [comment]
Strange, the token is properly append to the delete url:
https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/browser/schema/listing.py#L80

@vangheem any idea why we get this warning?

**Comment by vangheem** [comment]
that warning is from plone.protect detecting the response html and attempting to automatically include csrf tokens in POST forms on the site.

It's possible the response instead html when it thinks it should be? Maybe plone.protect needs to do some better pre-checks before it attempts to parse the dom?

**Comment by ebrehault** [comment]
@vangheem ok so that's because the `delete` method (which is not supposed to return HTML) set its content-type to `text/html`:
https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/browser/field/order.py#L56

To me there is no reason for that, I guess I will replace it with `application/json`.

**Comment by ebrehault** [comment]
Fixed with https://github.com/plone/plone.schemaeditor/commit/d886441140e10ce0cf224a9498c36a4e5f3d0595
