### ISSUE TITLE
Do not allow rich text field in user schema editor

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#512]
(this issue is connected to https://github.com/plone/buildout.coredev/blob/b0f0d74bb6b96b0293883bf9aff95805f19c8533/plips/reviews/plip13350-review-frapell.rst, we list it here so it appears in the Plone 5 milestone issues https://github.com/plone/Products.CMFPlone/milestones/Plone%205)

When adding a "Rich Text" field, the TinyMCE editor is not visible for anonymous when registering.
Short-term solution: remove richtext field from the allowed field type list.

**Comment by ebrehault** [comment]
Fixed https://github.com/plone/plone.app.users/commit/b1755e396de4fd0328e032bff5970a0dafa05847

**Comment by frapell** [comment]
@ebrehault would it be possible to instead of remove the field altogether, to limit it so it can only be added to the profile form? (and not the registration).

This field is very useful, for example, for bio field

**Comment by ebrehault** [comment]
I am pretty sure it is possible, but I do not know how to do that kind of things with `plone.schemaeditor`, so I prefer to remove the field type, that's a temporary solution, my immediate objective is to get a stable solution as soon as possible.
