### ISSUE TITLE
Re-upload to file with caching can cause confusion

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#518]
## User Problem

If a user uploads a file then publishes it, often the file will be heavily cached, in browsers and CDNs and in many cases can't be purged. The user then becomes frustrated that they thought they uploaded a new version but they or others are still getting the old version
## Options
1. Training. Users can be instructed to rename after they upload to ensure its not cached. External links will be redirected and internal links will be fixed by resolveUID.
2. Auto rename to the file name as a site policy. Perhaps via a content rule?
3. Display a message after upload warning its wise to rename and perhaps providing a link to auto rename to the new filename (or maybe append a timestamp).

**Comment by agitator** [comment]
ran into this as well...solved it by reregistering the cache purge view for content editors in the user menu (an other way/workaround would be to display a "purge cache" button in that context)

imho this should be solved in plone.app.caching (making sure the cache purge works)
the user shouldn't have to care about it

**Comment by vangheem** [comment]
Yes, plone.app.caching is the easiest solution here. @agitator do you have a plone.app.caching config you can share that we can integrate into default core configs?

**Comment by pbauer** [comment]
@agitator can you please document your solution in this https://github.com/plone/documentation and then close the ticket?

**Comment by thet** [comment]
The default settings for plone.app.caching with a purgable caching proxy uses for "Content files and images" a "Moderate caching" operation. This should not cache the content in the browser at all and should purge the file/image from the caching proxy as soon as it gets updated. 
Doesn't it work with these settings?

**Comment by fredvd** [comment]
I had issues with this before in Plone 4 with the p.a.contenttypes add'on there. it's not only the the purging but also the construction of the purge url for the download link on the view template for the file CT which has issues (if that hasn't been refactored in p.a.contenttypes master. 

See https://github.com/plone/plone.app.contenttypes/issues/265

**Comment by davisagli** [comment]
In Plone 6 this seems to be resolved for actually rendering the image due to using new scale URLs that are based on a hash generated when the image is changed. But the full size image is still cached too much.

**Comment by fredvd** [comment]
@davisagli   Is it the backend that is caching or is it the browser? 

@mauritsvanrees I remember you patched/fixed some of the caching headers for the full size image 1 or 2 years ago for our 'draw' custom contenttype where we hadd issues when the image field was updated but the browser requested an old copy.  That was Plone 4 but iirc you also fixed something related in 5.X that showed the same behavior. Or?

**Comment by jensens** [comment]
In Plone 6 with picture variants the zoomed image is now a scale. I think this solves it. Reopen if I am wrong.
