### ISSUE TITLE
the idea of default pages in not obvious

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#519]
# User problem

If an editor has a page and then wants subpages then in plone they need to both understand the idea of default pages and the actions of creating a new folder with the same name, then move the page into it and finally setting the folders view to use the original page as a default page.
# Internal

Lots of internal stuff around efficiency and backwards compatibility if folderish content is chosen.
# Options
## Mosaic replaces Page, Collection & Folder

All content is folderish with tiles. Pages, collections and folders merge. Discussed in this [Daft PLIP: Remove default pages via tiles](https://docs.google.com/document/d/1jJ7765rW-CpdOhKR6o4hFaOzQk6xmuePFZd-zTzxwFE/edit) and https://dev.plone.org/ticket/9210 (and probably a bunch more places)
- some issues include
  - Need a way to have navigation titles and descriptions be separate from the page title and description (like https://github.com/collective/collective.navigationtitle). probably a navigation viewlet/tile that uses an adapter to get the title and description to be used in menus, and a DX behviour to allow these to be set as different from the normal title and description.
  - Need a way for portlets to exist at just the page level (probably solved by mosaic sitelayouts).
  - Need a way for sharing to be set at just the page level. 
    - (would likely need to be solved together with a mosaic fine grained permission model, e.g. I want to let Marketing edit part of the page but not add subpages. I want to let Anonymous view the page but not any subitems)
  - requires tiles or similar (mosaic or tinymcetiles) to replace the folderviews.

Demo using mosaics - https://youtu.be/qSQGMnvW3k8
Demo using tinymcetiles - https://www.youtube.com/watch?v=HuxLoXlchc4
## Mosaic-less Page/Collection/Folder combo type.

As proposed by [Rob Gietema in this post](http://plone.293351.n2.nabble.com/Folderish-Page-Proposal-td7568149.html) and also analysed in [Daft PLIP: Remove default pages via tiles](https://docs.google.com/document/d/1jJ7765rW-CpdOhKR6o4hFaOzQk6xmuePFZd-zTzxwFE/edit)
- same issues as above + not as flexible
## Shortcuts

e.g. 
-  A "turn into a folder with a default page" action on a Page to automate the steps. 
- Enable "add > page" on a Page type. Which then creates a folder, sets a default page and adds the new page inside the new folder.

**Comment by jaroel** [comment]
@djay could you find someone/take lead in this?

**Comment by djay** [comment]
@jaroel this is a UX team issue that will be worked on by UX team. All the ones labeled UX and enhancement are hard problems that doesn't have an obvious solution yet.

**Comment by djay** [comment]
This video from @datakurre shows what option 1 could look like https://youtu.be/qSQGMnvW3k8

**Comment by datakurre** [comment]
Maybe this could be developed as an optional profile to avoid the outcry for two big changes.

Sharing issue sounds like the only real blocker. And it's hard to solve robustly, because permission and role acquisition is the default.

**Comment by datakurre** [comment]
So, it should be possible to assign non-inheriting local roles. Even there might be technical challenges, it's probably mainly UX problem.

**Comment by djay** [comment]
cleaned it up and put in more details

**Comment by tkimnguyen** [comment]
Apologies in advance... Castle has done away with default pages for folders. Folders by default get a content listing tile that shows the contained items; you can change the settings of that tile, and you can of course add more tiles on the page, e.g. a rich text tile that replaces the Plone default page concept.

Castle does not, however, address the question of converting a page into a folder.

![screen shot 2017-05-08 at may 8 9 14 54 am](https://cloud.githubusercontent.com/assets/815418/25808185/e263750e-33ce-11e7-872b-e9527bf33452.jpg)

**Comment by djay** [comment]
@tkimnguyen How many people have you trained on castle? Is there any kind of stats or anecdotal evidence shows this is much easier to teach and understand?

Also, above implies there is still a difference in castle between a page and a folder, so it hasn't gone the full folderless idea where everything is a container then?

**Comment by tkimnguyen** [comment]
People seem to understand the concept of folders just fine. 

That's right: Castle still has folders and pages, and it does not do the "everything is folderish" thing.

**Comment by djay** [comment]
@tkimnguyen so do you guys recommend Plone implements this?

**Comment by djay** [comment]
@tkimnguyen btw I was asking about the concept of having no default pages, rather than folders

**Comment by tkimnguyen** [comment]
Well, we do think this is an improvement because default pages confuse a lot of people (saw this at the uni too). 

If other Plone folks agree that default pages are a problem, this would be a good way to avoid the problem without wholesale changes to Plone. But we can't be the ones advocating for this feature being moved into Plone...

**Comment by jensens** [comment]
In Volto this is solved - no default pages! I doubt we will touch this in ClassicUI. So I close this one.
