### ISSUE TITLE
Building plone-logged-in bundle TTW fails with "too much recursion" error

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#521]
My version is https://github.com/plone/Products.CMFPlone/commit/e88469c6bccae216f5e32d87b0cbab61419f175f
```
less compilation error on file http://localhost:8080/Plone/++plone++static/plone-logged-in.less: Error: too much recursion
less compilation error on file http://localhost:8080/Plone/++plone++static/plone-logged-in.less: Error: too much recursion
less compilation error on file http://localhost:8080/Plone/++plone++static/plone-logged-in.less: Error: too much recursion
less compilation error on file http://localhost:8080/Plone/++plone++static/plone-logged-in.less: Error: too much recursion
```

**Comment by vangheem** [comment]
Does compiling with `./bin/plone-compile-resources --bundle=plone-logged-in` still work?

**Comment by vangheem** [comment]
Maybe it has something to do with this: https://github.com/less/less.js/issues/1222

However, I just tested on a fresh plone site and it is working properly.

Did you make a change?

**Comment by tomgross** [comment]
No I didn't make any changes. It's a plain buildout.coredev clone. Maybe a JS library conflict? Are all JS libraries pinned to KGS?

**Comment by tomgross** [comment]
My nodejs is Version 0.10.31 from the system package of openSuSE 13.2 and my npm is 1.4.23 if that helps.

**Comment by vangheem** [comment]
It's a less error. If you're building TTW, the only thing that matters is the less.js file that runs the compilation in the browser. No other dependencies for building less.

What browser and version?

**Comment by tomgross** [comment]
Firefox 38.0.1

**Comment by vangheem** [comment]
I just tested on Firefox 37 and 38. I can not reproduce this.

Where does the error show?

**Comment by tomgross** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/339384/7706346/36b036e0-fe4a-11e4-82b4-f51bda8f35c6.png)

**Comment by vangheem** [comment]
I still can not reproduce this. @tomgross is this still happening for you? Can you close this ticket if it is no longer happening?

**Comment by tomgross** [comment]
I have not seen this for a while.
