### ISSUE TITLE
Plone 4.3: pin latest compatible versions for plone.app.contentypes

### ISSUE THREAD

**Issue by simahawk** [plone/Products.CMFPlone#522]
[p.a.contentypes README](https://pypi.python.org/pypi/plone.app.contenttypes) says:

`Version 1.1b3 is tested with Plone 4.3.x. The versions of branch 1.1.x will stay compatible with Plone 4.3.x.`
and
`The 1.1.x-branch supports Plone 4.3.x. From this 1.1.x-releases will be cut.`

BUT from 1.2a4 changelog you see 

`Restore Plone 4.3 compatibility by depending on plone.app.event >= 2.0a4. The previous release of p.a.c got an implicit Plone 5 dependency through a previous version of plone.app.event. [thet]`

Can we:

* update that README ( @thet ? @pbauer ?)
* pin these packages (and all related pkgs if needed) into 4.3.x/versions.cfg ( @esteele  ?)

This will fix "what the hell should I use in my plone"-question once for all :)

**Comment by simahawk** [comment]
@pbauer just released p.a.c 1.1b4 that requires p.a.event 1.1.4. I pinned these versions in my buildout and did the upgrade steps: everything seems to work fine.

@esteele can we baptize these versions for versions.cfg? :)

**Comment by tisto** [comment]
If we choose to include those version pins we should make a final p.a.contenttypes release.

+1 for including those pins. Version conflicts with p.a.c/p.a.e are a major pain.
