### ISSUE TITLE
Not obvious how to open contents in folder_contents

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#524]
A client pointed me to a problem in wildcard.foldercontents, which also applies to the new ``folder_contents`` in Plone 5:

When navigating through the site hierachy, it was not obvious how to open a content he just navigated to.
I had to check myself: you have to click on the gear-symbol on the right side the content item in the list and select "Open" or "Edit".
Opening or editing should be offered without having to open a dropdown menu. Open and Edit icons would be enough, I guess.

Ideally, window.location and the toolbar's urls would change after navigating somewhere else in folder_contents. But that would break other UI concepts, I guess - as the rest of the site cannot be updated without doing a full page reload.

**Comment by vangheem** [comment]
On Plone 5, folder contents does actually change the url bar. Additionally, it reloads the toolbar.

If we want to reload other elements on the page, we could do something tricky where we re-requested the base view and replaced other elements in the layout that change depending on context.

Having folder contents manipulate the url path is important though to let people be able to link to it.

**Comment by vangheem** [comment]
As for not being able to view an item easily--I agree. Could we change the item title to something like: "Title of view (view)" where "view" would be a link to access the item.
