### ISSUE TITLE
table of contents should be a tile or portlet or part of navigation

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#525]
## user problem

Some style of sites treat the page as long with subpages as anchors. Need a nicer way to switch to this style. It's a little weird that how a TOC is a switch but navigation is a portlet. Would be more consistent if they were dealt with the same way. I suspect TOC mode hardly gets used.
## Options
1. TOC portlet. same markup as navigation portlet.
2. enhance navigation portlet to allow heading anchors up to a certain depth.
3. ??

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
