### ISSUE TITLE
TypeError: $.fieldValue is not a function

### ISSUE THREAD

**Issue by datakurre** [plone/Products.CMFPlone#526]
On locally run Plone 5.0b1, on the latest Firefox, every now and then, I get error a javascript error 

    TypeError: $.fieldValue is not a function

when trying to perform an action an an overlay / modal form, e.g. adding a new user or confirming content deletion.

Reload always fixes the issue.

Could there still be javascript loading related issues? $.fieldValue is a function set by jquery.form.

**Comment by vangheem** [comment]
Can you share the stacktrace? Does this happen in b2 or master?

**Comment by datakurre** [comment]
I'll report back, when I see that on b2.

**Comment by datakurre** [comment]
Now seen on b2, but I don't know how to get proper stack trace dump with Firefox.

![nayttokuva 2015-05-29 kello 23 24 48](https://cloud.githubusercontent.com/assets/160447/7892018/fde8e506-0659-11e5-8d2b-bd450823039b.png)
![nayttokuva 2015-05-29 kello 23 24 28](https://cloud.githubusercontent.com/assets/160447/7892019/fdf2d2fa-0659-11e5-88ac-8e625a973a09.png)

**Comment by vangheem** [comment]
hhmm, I don't think we're using jquerytools.form.js for anything anymore. We should probably remove that. Seem looks a bit mysterious.

I that this seems to happen with plone.app.mosiac then? So this isn't vanilla plone 5.

**Comment by datakurre** [comment]
@vangheem So, could it be that jquerytools.form somehow conflicts with jquery.form used by modal pattern?

Yes, it's not vanilla (I use Plone 5 mainly with Mosaic), but I've seen this issue randomly with any mockup modal form in Plone (and don't know, how Mosaic's JS bundle could cause this).

**Comment by datakurre** [comment]
But there is no jquerytools.form. There's only jquery.form.

**Comment by datakurre** [comment]
But jquery.form is both in legacy bundle and plone bundle.

**Comment by datakurre** [comment]
I think, I've only seen that with the very first modal after starting the site. And reload fixes the issue. So, it could be some kind of racing condition. Annoying to reproduce and debug.

**Comment by vangheem** [comment]
can you test removing jquery.form from the legacy bundle? Is that pulled in by plone.app.mosiac?

**Comment by datakurre** [comment]
I'll try this...

Mosaic does not depend on legacy bundle, and the issue appears, when Mosaic uses modal provided by plone-bundle.

And now, when you said, I'm not sure, if legacy bundle even was active in that request. Need to check that and wait for another occurrence.

**Comment by vangheem** [comment]
The legacy bundle is always active. In plone 5, the legacy bundle just means any js that was imported from jsregistry.xml--it's included sequentially.

It is in fact jquerytools.form. Look at the traceback js.

It's pulled in by https://github.com/plone/plone.app.jquerytools/blob/master/plone/app/jquerytools/profiles/default/jsregistry.xml#L21

Please try removing jquerytools.form from the legacy bundle and see if the problem persists. Go to Resource Registries -> "plone-legacy"

**Comment by datakurre** [comment]
@vangheem Thanks. I'll do that and see, if I see the issue again.

**Comment by vangheem** [comment]
I think we need to change plone.app.jquerytools or, if possible, remove the package in plone 5.

**Comment by vangheem** [comment]
alright, master plone 5 no longer uses plone.app.jquerytools so this problem shouldn't happen anymore.

**Comment by datakurre** [comment]
Just confirm that removing p.a.jquerytools.from from legacy bundle fixed this for me also in 5.0b2.
