### ISSUE TITLE
Products with no configure.zcml are not shown in Addon controlpanel

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#527]
With Plone 5.0b2 products with no configure.zcml are not shown in Addon controlpanel list as available products. They are shown in the quickinstaller of the ZMI. This should be fixed or documented.

example: https://pypi.python.org/pypi/Products.AutoUserMakerPASPlugin/1.1

**Comment by jaroel** [comment]
The Addon controlpanel only show addons with a GS profile.

**Comment by bloodbare** [comment]
can we close this ticket ?

**Comment by jaroel** [comment]
Non-GS addons are no longer support, so I'd say yes.
Please open this ticket if you disagreee.

**Comment by tomgross** [comment]
@jaroel Where is this documented?

**Comment by jaroel** [comment]
I think @datakurre fixed this, right?

**Comment by datakurre** [comment]
@jaroel I recall only fixing install to still use quick installer (to support products with old install hooks). I may not have touched the vocabulary.

**Comment by jaroel** [comment]
I'm checking what, why.
