### ISSUE TITLE
Default theme not liquid

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#528]
when I use the vertical toolbar I'm getting an horizontal scrollbar:

![selection_001](https://cloud.githubusercontent.com/assets/341393/7801732/e668e0be-02ff-11e5-8a22-3eb80c9eb0a7.png)

this behavior is worst if the horizontal toolbar is expanded:

![selection_002](https://cloud.githubusercontent.com/assets/341393/7801733/ea5b8cc6-02ff-11e5-9c61-094d91dd5fd5.png)

**Comment by vangheem** [comment]
To clarify how to reproduce this issue for whoever works on it, it is very specific widths that this happens. It seems like between widths of 990 and 1100px.

At least, that's how it is for me.

**Comment by bloodbare** [comment]
Addressed on #482
