### ISSUE TITLE
Toolbar Issues

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#529]
- [ ] commonly used menu items to hard to get to or not where you expect - https://github.com/plone/Products.CMFPlone/issues/482 
   - https://github.com/plone/Products.CMFPlone/issues/177
   - https://github.com/plone/Products.CMFPlone/issues/481
   - [ ] would be nice if last modified info were visible on toolbar without an extra click?
- [ ] fix liquidness: https://github.com/plone/Products.CMFPlone/issues/528
- [ ] decide if we want to support both vertical and horizontal positioning
- [ ] if we are supporting different toolbar display types, it should be configurable in a control panel
- [ ] buttons are too wide and do not fit well as screen narrows. Can we stack icon on top of text and make taller? Or potentially hide icons?
- [ ] need to decide if folder contents button should show at all times
- [ ] font and font weight: https://github.com/plone/Products.CMFPlone/issues/426

**Comment by jcerjak** [comment]
My two pennies regarding the vertical/horizontal positioning: I was skeptical at first about the vertical bar, but now I prefer using it, imho it looks better and it's easy to use. If it's not a huge amount of work to support both options, I'd prefer to have this configurable.

**Comment by hvelarde** [comment]
why don't we just leave the document byline viewlet where it is right now? the information should be hidden via control panel configlet if that's a security concern and we can get rid of one button in the toolbar.

**Comment by vangheem** [comment]
@hvelarde that would help. But say you hide it or the diazo theme doesn't pull it in. Now how do you get access to that information and the history?

**Comment by hvelarde** [comment]
currently, the viewlet is inside the ``IBelowContentTitle`` so if you make your Diazo theme to include everything inside that it would be there.

![selection_001](https://cloud.githubusercontent.com/assets/341393/7813038/e26c5552-038d-11e5-86c5-14ebc4fd3ed3.png)

we probably need some basic guidelines for newbies.

**Comment by agitator** [comment]
I like the vertical toolbar for it's compactness and see that as the default as it is right now.
The horizontal version is more explanatory especially with the expanded labels (and more of a known PC menu approach), which can make it easier to get used to how things work in Plone - imho the horizontal version has less ui issues anyway.
I vote for keeping both vertical and horizontal positioning - no real reason for removing this option.

**Comment by vangheem** [comment]
The reason for removing one of them is so we can focus on doing one well. I'd prefer not to have to support 2 positions. However, if we do keep both, we need options in the control panel to flip the settings. Or have it a user setting.

Right now, horizontal expanded menu has the same explanatory value as vertical expanded.

**Comment by agitator** [comment]
we can still focus on the default ;-)

**Comment by djay** [comment]
I think I've merge all the issues from here to https://github.com/plone/Products.CMFPlone/issues/482 I'll close this now
