### ISSUE TITLE
upgrade to 4.3.5 breaks use of OrderedSelectWidget

### ISSUE THREAD

**Issue by petri** [plone/Products.CMFPlone#530]
I have a z3c.form with a field defined thus:
    
    extra_products = schema.List(title=u"Choose products", required=False,
                        description=u"Chosen products will be added to each order row.",
                        value_type=schema.Choice(source=ProductSourceBinder()))

As per docs, the default widget for this is the ```z3c.form.browser.orderedselect.OrderedSelectWidget```. This was working fine before upgrade. After upgrading, the widget only shows up & down arrows, but nothing else - nothing to select from, either.

I tried switching back to 4.3.4 and also (on 4.3.5) instead of ```schema.List``` switching to ```schema.Set``` to change the default widget to regular multi select, and both such "downgraded" cases work fine.

**Comment by petri** [comment]
I can confirm this also breaks for example ftw.globalstatusmessage.

**Comment by vangheem** [comment]
Try downgrading to z3c.form 3.2.1.

The only difference, it seems, from 3.2.1 to 3.2.3 is that some inline javascript was moved into a file.

Can you see if the orderedselect_input.js is getting included in your rendered page? Can you check if there are javascript errors related to it?

**Comment by petri** [comment]
orderedselect_input.js is included, yes - no JS errors on Safari on OS X

**Comment by petri** [comment]
Downgrading to z3c.form 3.2.1 helps - no problem there.

**Comment by vangheem** [comment]
@pbauer any idea what might be going on? You did the change.

**Comment by vangheem** [comment]
@pbauer ping on this
