### ISSUE TITLE
Register plone.ngo and plone.ong domain names, if appropriate

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#533]
1. All organizations must be social good organizations and are reviewed as part of the registration process. An .ngo domain isn't available to just anyone but communicates something about the owner of the site.
2. All owners of .ngo domains receive a profile page as part of the new OnGood network. This is a directory of international nonprofits, and your new profile will be among them.
3. The OnGood network includes a built-in online donation tool that's especially well-suited for international donations

**Comment by fulv** [comment]
https://www.ongood.ngo/portal/

http://globalngo.org/discover/eligibility/

**Comment by vangheem** [comment]
@plone/launch-team @polyester any thoughts?

**Comment by polyester** [comment]
I'm sceptical, as is most of the non-profit communities that I frequent.

**Comment by vangheem** [comment]
I'm closing then. Anyone who is interested and has more opinions on it can reopen. Thanks.
