### ISSUE TITLE
plone.app.openid 2.1.x not compat with 4.3

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#534]
Latest Plone 4.3.5 requires plone.app.openid 2.1.0. 2.1.0 changed to get it's use_email_as_login setting from the configuration registry. This is breaking sites it seems as reported on IRC.

The commit that caused this seems to be https://github.com/plone/plone.app.openid/commit/fbbfe1ef6756a607e489f456f3586b601556b729

Can we update the code to work both with plone 5 and plone 4 and can we get an updated release? Thanks.

@tisto @jcerjak @esteele

**Comment by vangheem** [comment]
@obct537 is going to fix it.

This, along with the plone.app.blob issue. Could we quickly get out another 4.3 release?

**Comment by esteele** [comment]
Absolutely.

**Comment by vangheem** [comment]
@obct537 is this close? Do you need help?

**Comment by tisto** [comment]
I will work on a fix.

**Comment by tisto** [comment]
Ok. There is a problem. login_form.cpt is a skins folder template. We can not just add a switch with a fallback to a template, we need Python code for that. I would say we should rather cut another branch and make two new releases for Plone 4.3 and 5.0.

**Comment by vangheem** [comment]
Ahh, I thought it was just that one line that was the problem. Yes, let's
do different branches. We also need to downgrade 4.3 version.

**Comment by tisto** [comment]
plone.app.openid 2.1.x should have never make it into Plone 4.3. There was already a branch and a release.
