### ISSUE TITLE
Sporadic AttributeError: 'FileResource' object has no attribute 'PROPFIND' errors

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#536]
We are receiving very sporadic errors (once or twice a day) on one particular browser resource image.
No idea where this issue is coming from. There are various other browser resource images used on this Plone 4.3 site and we never see any issues with them.

1432730924.430.0142972126906 https://www.onkopedia.com/de/onkopedia/guidelines/++resource++onkopedia.policy/images/back-to-toc.png
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 473, in traverse
  Module zope.browserresource.file, line 94, in browserDefault
AttributeError: 'FileResource' object has no attribute 'PROPFIND'

**Comment by vangheem** [comment]
Isn't PROPFIND related to webdav?

line 94 is:

    return getattr(self, request.method), ()

so it's just erroring because that resource does not support PROPFIND

**Comment by zopyx** [comment]
PROPFIND is related to WebDAV...but there is no WebDAV involved in our system. The URL is called TTW only.

**Comment by vangheem** [comment]
I have no idea how to replicate this issue. I haven't seen it. Are you still seeing these errors in your log? Can you correlate them to web server logs and see the request method used? Perhaps you're not blocking webdav attempts at your server?

I'm closing for until further notice. Feel free to reopen if I'm wrong.
