### ISSUE TITLE
Get rid of plone.app.form

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#537]
Since formlib is no longer used for the controlpanel, plone.app.form seems obsolete too. There are only two packages using it in core:

plone.app.contentrules -> should be ported to z3c.form too for the sake of consitency
plone.app.controlpanel -> all necessary code from plone.app.form could go there until this is removed.

mr.cleanup strikes again ;-)

**Comment by vangheem** [comment]
Can't we just remove plone.app.controlpanel by now? I can try taking a look at plone.app.contentrules

**Comment by tomgross** [comment]
Thanks @vangheem!

I'm +1 removing plone.app.controlpanel. We change a major version. This may break things.

**Comment by vangheem** [comment]
also, five.formlib. Is that used anywhere else or could we also get rid of that?

**Comment by vangheem** [comment]
aannnnd zope.formlib?

**Comment by tomgross** [comment]
There are more of these: plone.fieldsets and zope.app.form
Nathan Van Gheem <notifications@github.com> schrieb am Fr., 29. Mai 2015 um
22:50:

**Comment by tisto** [comment]
We could remove plone.app.controlpanel. Though, we kept it for backwards compatibility and made sure the old import locations still work. I'm pretty sure we can just remove the plone.app.form parts.

**Comment by gforcada** [comment]
@vangheem @tomgross then you may be interested in this jenkins job: http://jenkins.plone.org/view/Dependencies/job/plone-package-dependencies-formlib/

**Comment by vangheem** [comment]
@tomgross

plone.app.contentrules is ready: https://github.com/plone/plone.app.contentrules/pull/14

Tests are passing locally. I'm running full test suite for this pull request here: http://jenkins.plone.org/job/pull-request/179/

Night time here now so I'm going to bed. Feel free to merge if everything passes.

**Comment by tomgross** [comment]
@tisto I'm in favour of removing plone.app.controlpanel, if we don't use it in Plone core 5.0 at all. People can still use it as an addon, if they depend on it, right?
Removing it is the cleaner approach IMO.

**Comment by tomgross** [comment]
@vangheem cool thanks! :clap:

**Comment by thet** [comment]
@tisto I agree with @tomgross for removing p.a.controlpanel. if packages declare their dependencies in setup.py properly, removing shouldn't be an issue (but often packages don't declare their dependencies...)

**Comment by tisto** [comment]
Most packages do not declare their dependencies properly and we still have packages depending on plone.app.controlpanel code and imports:

https://github.com/plone/plone.app.controlpanel/pull/50

Before we can even discuss removing the package, we have to make sure we do not have code depending on it.

@thet Maybe I should just stop working on cleanup tasks. I either hear complains about removing too much code (https://github.com/plone/Products.CMFPlone/issues/486) or not enough (here).

**Comment by thet** [comment]
@tisto, don't take these comments personally! i'm a kind of guy who wants to hear good arguments. it's just an discussion, and with your last argument about the dependency declaration problem, which i'm aware of, i'm ok for keeping p.a.controlpanels. as soon someone solved the issue of imports/dependency declarations, this discussion has a different standpoint. as long no one solves it (while you @tisto aren't in charge to solve it) we have to stick with what we have.

besides of that: three random people discussing issues on github cannot come to a formal decission. that would bypass official teams. they can provide arguments for an official team (e.g. FWT) to make formal decissions. we should keep this in mind and submit important discussions to official Plone-teams. maybe not this one, but this is a problem with discussions on github in general.

**Comment by gforcada** [comment]
@thet well that's why @jensens was writing some deprecation guidelines, so let's help him finish that writeup and just stick to the rules defined there regarding distribution deprecation :)

**Comment by jensens** [comment]
indeed, I played around now a bit more with ``zope.deprecation`` and ``zope.deferredimport`` which are both - besides the usal python stdlib ``warnings.deprecation`` the packages to use.

I'll invest 2h hours today into that document in order to have a working draft at least and come back then.

**Comment by tisto** [comment]
plone.app.controlpanel is now formlib-free.

**Comment by thet** [comment]
:beers:

**Comment by jensens** [comment]
:+1:

**Comment by gforcada** [comment]
:+1:

**Comment by tomgross** [comment]
https://github.com/plone/plone.portlet.collection/pull/6
https://github.com/plone/plone.app.collection/pull/24

**Comment by tomgross** [comment]
All occurences removed. Together with zope.app.form and five.formlib
