### ISSUE TITLE
Update the control panel icons

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#538]
Let's get some more modern icons to use in the control panel listing at @@overview-controlpanel.
![screen shot 2015-05-29 at 3 18 35 pm](https://cloud.githubusercontent.com/assets/483999/7890774/08e77358-0616-11e5-92be-e924b43cf99e.png)

See also #104.

**Comment by vangheem** [comment]
+1 those icons have to be near 10 years old :)

**Comment by vangheem** [comment]
Done in toolbar-fixup plip branches.
