### ISSUE TITLE
Content Rules control panel: checkboxes are shown as required

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#542]
In the "Add rule" form of @@rules-controlpanel, the three checkboxes at the end of the form are designated as "required", which makes no sense for a checkbox element.

![screen shot 2015-05-29 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/483999/7891172/f22aa3c6-0618-11e5-8bb9-2591326d3880.png)

**Comment by vangheem** [comment]
already fixed in latest.
