### ISSUE TITLE
Navigation settings control panel: improve display of workflow state filters

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#554]
* Reduce spacing between the "filter" checkbox and the workflow states beneath. 
* Display workflow states one-per-line

![screen shot 2015-05-29 at 4 08 10 pm](https://cloud.githubusercontent.com/assets/483999/7891751/253f20d0-061d-11e5-9ee3-4b47d2144bd9.png)

**Comment by vangheem** [comment]
already fixed in latest.
