### ISSUE TITLE
TinyMCE Settings: Standardize label casing

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#564]
Don't use title casing on labels:

* Editor Plugins (Also capitalize the 'tinyme' in the description)
* Custom Plugins
* Custom Buttons
* AtD Ignore strings
* AtD Error types to show
* AtD Service URL
* Contains Objects
* Image Objects

**Comment by sneridagh** [comment]
Done, toolbar-fixup branch.
