### ISSUE TITLE
Type Settings: Content type menu text is faded

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#565]
The text of the content type selector at the top of @@types-controlpanel is lighter/greyer/different than the other select elements on the page. The select element also appears to be underlined or have a bottom border. 

![screen shot 2015-05-29 at 4 47 21 pm](https://cloud.githubusercontent.com/assets/483999/7894403/0788eafc-0637-11e5-93f0-672d49ae580a.png)

**Comment by davisagli** [comment]
Is that the right screenshot? I can't tell what part of the page you're talking about.

**Comment by esteele** [comment]
@davisagli: Fixed.

**Comment by agitator** [comment]
fixed
