### ISSUE TITLE
Standardize the "Site setup" link across all control panels

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#570]
At the top of each site control panel page, we either have a link with the text "Site Setup ›", "Site Setup" or no link at all. We need to choose one and stick with it.

**Comment by tisto** [comment]
This should go into the plone.app.registry control panel base class/template.

**Comment by tisto** [comment]
Actually the link is already in p.a.registry: 

https://github.com/plone/plone.app.registry/blob/master/plone/app/registry/browser/controlpanel_layout.pt#L17

I guess this is just a matter of cleaning up things then...

**Comment by thet** [comment]
Why should the base control panel template be in plone.app.registry and not in Products.CMFPlone/controlpanels, where we moved all other control panel stuff?

**Comment by tisto** [comment]
@thet because it has been there before we started to move the control panels to p.a.registry and we do not gain anything from moving stuff around. I'm not opposed to move that code (plus documentation and tests of course), I just don't see what we could gain but instead just work and possible problems.

**Comment by thet** [comment]
I favor clear package structures instead of related code spread all over Plone.  It makes it easier to understand code and to develop. I see fixing that as part of our code cleanup effort.For a particular bad example look at the navigation portlet.

**Comment by tisto** [comment]
@thet ok. I will refactor that code if you do the same for p.a.event/p.a.contenttypes. deal? :)

**Comment by thet** [comment]
Deal! :) 
although I need more time for that refactoring

**Comment by tisto** [comment]
Fair enough... :)

**Comment by jaroel** [comment]
Looks like the link can be removed, because it is already in the menu directly next or below to the content.
Pages that don't have the navigation, should have it instead of the 'Site Setup' link?
