### ISSUE TITLE
Colophon text "Powered by Plone and Python" formatting differers from neighboring elements

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#572]
"Powered by Plone and Python" is displayed in the footer on the same line as Site Map/Accessibility/Contact, but is given an uppercase transform.

**Comment by gforcada** [comment]
plonetheme.barceloneta needs to be added on checkouts.cfg

**Comment by bloodbare** [comment]
Solved on toolbar-fixup branch
