### ISSUE TITLE
"Content info" menubar item displays a "linked translations" section with no further information

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#576]
Don't display the heading if there's no information to display.

![screen shot 2015-05-29 at 6 20 18 pm](https://cloud.githubusercontent.com/assets/483999/7893797/6a460fd8-062f-11e5-9c24-25dc3970aed2.png)

**Comment by vangheem** [comment]
merged into https://github.com/plone/Products.CMFPlone/issues/482
