### ISSUE TITLE
Standardize display of menubar headings (links vs text)?

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#578]
We have two cases for headings in the menu bar:
![screen shot 2015-05-29 at 6 26 19 pm](https://cloud.githubusercontent.com/assets/483999/7893891/6e680548-0630-11e5-9b32-425e598c0f72.png)
and 
![screen shot 2015-05-29 at 6 26 40 pm](https://cloud.githubusercontent.com/assets/483999/7893892/72ffdd2e-0630-11e5-8a01-e8dea33d4759.png)

where the former contains links and the latter doesn't. First, do we need these links? Second, should these be styled in a manner similar to the other menus?

**Comment by vangheem** [comment]
Merged into https://github.com/plone/Products.CMFPlone/issues/482
