### ISSUE TITLE
folder_constraintypes_form requires __everything__

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#583]
* Don't require checkboxes. 
* I'm not sure it makes sense to require any of these fields here.

![screen shot 2015-05-29 at 7 01 08 pm](https://cloud.githubusercontent.com/assets/483999/7894262/1c9f0c3e-0635-11e5-80f2-e68faf2b5841.png)

**Comment by davisagli** [comment]
Individual checkbox issue fixed in plone/plonetheme.barceloneta@9bdb7ef5b8ec9ca57bd1c7fbddf55005fff87e66

**Comment by jensens** [comment]
fixed by merging plone/plone.app.content#32
