### ISSUE TITLE
Remove the "required" label on edit form's "Exclude from navigation" checkbox

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#585]
![screen shot 2015-05-29 at 7 08 56 pm](https://cloud.githubusercontent.com/assets/483999/7894339/33293ea6-0636-11e5-99d2-34aa5a1e8fb6.png)

**Comment by davisagli** [comment]
Fixed in plone/plonetheme.barceloneta@9bdb7ef5b8ec9ca57bd1c7fbddf55005fff87e66
