### ISSUE TITLE
Generate a style guide for Plone core

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#589]
Based on some of the inconsistencies I've been noticing while going through Plone 5, I think we should set up a style guide for the core UI. 

What I've run across so far:
- Casing in page titles. There is a mix of sentence and title casing. I'd vote for the latter. 
- Casing in field labels. Also a mix of sentence and title casing. Sentence casing seems the more common. 
- Save buttons. Currently a mix of "save" and "apply changes". Should have the primary styling applied, ("context" in Plone's CSS)
- cancel buttons. Should these exist everywhere there's a save button? They should not have the button-primary styling applied. 

@bledwell , @vangheem: I'd appreciate your thoughts about what might belong here.

**Comment by davilima6** [comment]
+1

**Comment by davisagli** [comment]
This still sounds like a good idea, but it doesn't seem like the existence of this issue has helped it happen. Should I keep it open?

**Comment by esteele** [comment]
Let’s just close it.
