### ISSUE TITLE
Refactor control panel base view/template from plone.app.registry into P.CMFPlone

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#590]
See https://github.com/plone/Products.CMFPlone/issues/570#issuecomment-107142282 for discussion.

**Comment by vangheem** [comment]
Are we still bothering doing this for 5.0? Should we move this to 5.1 task?

**Comment by vangheem** [comment]
No action on this in a while. Closing this until someone wants to work on it and writes a proper plip for it. Feel free to reopen.
