### ISSUE TITLE
@@resourceregistry-controlpanel not visible from navigation when plone updated

### ISSUE THREAD

**Issue by birdwell** [plone/Products.CMFPlone#595]
When I update a Plone site say from Plone 5a3 to 5b2, the @@resourceregistry-controlpanel is missing from the site setup navigation bar. However, you can visit it by entering in the url. 
![screenshot 2015-06-01 12 08 09](https://cloud.githubusercontent.com/assets/3323856/7965119/152e9398-09e1-11e5-8bf7-86ef2eb193ac.png)

**Comment by vangheem** [comment]
Upgrade step fixed. Next upgrade should address this.
