### ISSUE TITLE
New Resource Registry Reset Option?

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#597]
I'm stuck in the following situation: I introduced a JavaScript error in one of my JS bundles I use in my Plone site. Since the new resource registry is also a mockup pattern written in JS it is not accessible any more. I guess the two options are now:
 - Recreate the default JS from mockup on the command line
 - Delete Plone egg and let it fetch again
It would be good to have a reset to default option in the resource registry to prevent JS users to shot themselves in the foot (or at least recover from it easily :wink: ).

**Comment by vangheem** [comment]
I'll look into potential ways to make this better.

**Comment by vangheem** [comment]
So I'm still thinking of better ways but it will now fall back and let you delete built bundles if the resource registry fails to load.

One other idea I had was to see if it were possible to test executing the built js file in an iframe before saving and see if it errors. Not sure that's possible though.

**Comment by djay** [comment]
would one way be to seperate the control panel and themed site and target your bundles to go to one or the other? That way working on a theme bundle won't affect that back end.
It's really not that hard to do @vangheem.  prototype at https://github.com/collective/plonetheme.cmsui
