### ISSUE TITLE
XSS check is triggered in ZMI

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#598]
In some (all?) ZMI operations the XSS check of Plone is triggered.

http://localhost:8000/Plone2/acl_users/source_users/manage_workspace ->
http://localhost:8000/Plone2/@@confirm-action?original_url=http%3A%2F%2Flocalhost%3A8000%2FPlone2%2Facl_users%2Fsource_users%2Fmanage_users

This anoying and frightening additional click should be eliminated.
Plone 5b2

**Comment by vangheem** [comment]
Need to fix write on read. Can't remove XSS warnings--it's protecting plone.

**Comment by tomgross** [comment]
Security over usability. Closing this.
