### ISSUE TITLE
Renaming and importing a LanguageRootFolder fails

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#600]
Renaming a LRF or importing it via zexp fails with:
```
2015-06-05T11:38:09 ERROR Zope.SiteErrorLog 1433497089.050.0849822399551 http://localhost:8080/Plone/manage_importObject
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module OFS.ObjectManager, line 627, in manage_importObject
  Module OFS.ObjectManager, line 646, in _importObjectFromFile
  Module Products.CMFCore.PortalFolder, line 421, in _verifyObjectPaste
ValueError: Disallowed subobject type: LRF
```

Plone 5.0b2

**Comment by pbauer** [comment]
I don't know how we should fix this sanely. LRF and LIF should not be made implicitly addable. And adding exceptions to paste and import seems insane. The best strategy I see is simply documenting that you need to make them implicitly addable (in http://localhost:8080/Plone/portal_types/LIF/manage_propertiesForm) before renaming and/or importing them and switching that off again after you are done.
