### ISSUE TITLE
Link to sitemap in robots.txt has wrong format

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#604]
According to http://www.sitemaps.org/protocol.html#submit_robots (and google webmastertools) specifying ``/sitemap.xml.gz`` is not ok. It has to be a complete URL like``http://www.mysite.com/sitemap.xml.gz``.

So far robots.txt is only a txt-file in the skins-folder and not overrideable with a browser-view. It can be overridden using skins, z3c.jbot or at the webserver-level. How about a pull-request that removes robots.txt and adds a browser-view ``robots.txt`` that returns the same but with the actual portal-url.

**Comment by vangheem** [comment]
You could only make that change for Plone 5 since it would break existing Plone 4 setups potentially.

Perhaps we move robots to a simple template that can easily be edited in the site control panel.

It could have 1 replacement variable %(portal_url)s. I doesn't necessarily have to be editable in the site control panel but it'd be nice to be able to set the value in the configuration registry I think.

**Comment by pbauer** [comment]
@vangheem will this be enough? 
```
<records interface="Products.CMFPlone.interfaces.ISiteSchema"
         prefix="plone" />
```

**Comment by pbauer** [comment]
For those who want a quick fix for the same problem in Plone 4 here is a workaround:

Im the ZMI add a python-script wih the name ``robots.txt`` in the Plone-root:

```python
portal_state = context.restrictedTraverse('@@plone_portal_state')
portal_url = portal_state.portal_url() 

ROBOTS_TXT = u"""Sitemap: {portal_url}/sitemap.xml.gz
# Define access-restrictions for robots/spiders
# http://www.robotstxt.org/wc/norobots.html

# By default we allow robots to access all areas of our site
# already accessible to anonymous users

User-agent: *
Disallow:

# Add Googlebot-specific syntax extension to exclude forms
# that are repeated for each piece of content in the site
# the wildcard is only supported by Googlebot
# http://www.google.com/support/webmasters/bin/answer.py?answer=40367&ctx=sibling

User-Agent: Googlebot
Disallow: /*sendto_form$
Disallow: /*folder_factories$
"""
return ROBOTS_TXT.format(portal_url=portal_url)
```
When overriding robots.txt with z3c.jbot or skins you would only get a text-file and could not add a dynamic url.
