### ISSUE TITLE
Sometimes http://dist.plone.org/release/4.3-latest/versions.cfg is downloaded as gzip

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#606]
You can close this if it's not a actually a problem in Plone infrastructure.

Sometimes when downloading http://dist.plone.org/release/4.3-latest/versions.cfg from buildout we receive a gzipped file. I don't know if this is a corporate proxy network problem or a problem in Plone Servers (or both: like a proxy cached the gzipped version when was wrong on Plone Infrastructure in a specific moment), so I'm opening this issue. A similar problem for [Plone 4.3.1 happened in the past](http://plone.293351.n2.nabble.com/Error-getting-4-3-1-versions-cfg-with-buildout-td7566149.html).

Has anyone had this problem before? When we tested it we did a simple ```wget http://dist.plone.org/release/4.3-latest/versions.cfg```.

An issue was open [in buildout issue tracker](https://github.com/buildout/buildout/issues/245) to ask if it can show friendlier messages when this happens.

**Comment by vangheem** [comment]
This more looks like the compression encoding used by the web server isn't being interpreted properly from the python that downloads and reads the version files.

This would be a zc.buildout problem or maybe related to python. I really have no other ideas what is going on.

I'm am going to close the ticket and suggest you continue your open issue on zc.buildout repo. You might want to poke them about it.

**Comment by jaroel** [comment]
@svx any ideas?
Maybe we should just disable gzip. The packages are already zips, and the gain on the .cfg files might be not that much?

**Comment by vangheem** [comment]
it's probably just default nginx config. Fine to disable though of course.

On Mon, Jul 13, 2015 at 11:33 AM, Roel Bruggink <notifications@github.com>
wrote:

> @svx <https://github.com/svx> any ideas?
> Maybe we should just disable gzip. The packages are already zips, and the
> gain on the .cfg files might be not that much?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/606#issuecomment-120870651>
> .
>



-- 
Nathan Van Gheem
Solutions Architect
Wildcard Corp

**Comment by idgserpro** [comment]
This problem still occurs sporadically. Any news about it? It seems to be some configuration on the server hosting the versions.cfg file. @vangheem you can reopen it?
