### ISSUE TITLE
Folder contents: Hide open dialog when another is opened

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#608]
For instance, clicking "properties" and then "tags", you'll wind up with two open dialogs.
![screen shot 2015-06-14 at 12 09 30 pm](https://cloud.githubusercontent.com/assets/483999/8146903/6867d708-128e-11e5-9066-d10cd5b85209.png)

**Comment by vangheem** [comment]
fixed here: https://github.com/plone/mockup/commit/5d2b4bb6d68965e925a759bdfb563e221d5029fd
