### ISSUE TITLE
Folder contents: When dragging an item, don't show the actions menu items

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#614]
When dragging items in the folder contents view, the ghosted version of the item includes the menu items from the action menu (cut, copy, paste, etc).

![plone_site](https://cloud.githubusercontent.com/assets/483999/8146945/91d17822-1290-11e5-9a29-4313e24d1e8d.png)

**Comment by vangheem** [comment]
fixed in latest.
