### ISSUE TITLE
Unable to hide the toolbar on smaller screens

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#615]
When using a mobile device (or thinner screen) the toolbar (moved to the right side) cannot be closed/hidden by clicking on the Plone icon.

**Comment by esteele** [comment]
Correction. When loading the page, this works as expected. When resizing the browser, I'm unable to show/hide the toolbar or open menu items.

**Comment by vangheem** [comment]
Closing. Need to reload when you resize your browser like a mobile device as there is js that binds differently depending screen size.
