### ISSUE TITLE
Review and update default front page content

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#624]
the information on the default front page of new Plone sites needs to be updated (eg for links, Plone.com, Plone 5 and other recent changes in the community and software)

**Comment by tkimnguyen** [comment]
[Plone Launch Team]

**Comment by djay** [comment]
The explaining of plone "the community" as the first thing you see is somewhat confusing. 
I personally think that the we would be better off creating a dummy site that have content that reflected a simple typical site. Including things like a extranet/private shared area. Lots more content that acted as a tour of plone.
How to get help and about plone could be put under a "about us" section or something.

**Comment by esteele** [comment]
See also #573, #574, #575

**Comment by tkimnguyen** [comment]
I'll draft up a revision and send around for comments [braces hisself]. @djay that's a nice idea! if it's shown as an option...otherwise too heavy if all you want to do is create a new site and have to strip out all this auto content.

**Comment by esteele** [comment]
We already have the basic content creation living in its own generic setup profile, and can be skipped when using the advanced mode of the site creation form. So there's no reason we couldn't do the same with another if we wanted to.

**Comment by tkimnguyen** [comment]
- [x] https://github.com/plone/Products.CMFPlone/issues/573
- [x] https://github.com/plone/Products.CMFPlone/issues/574
- [x] https://github.com/plone/Products.CMFPlone/issues/575
- [x] https://github.com/plone/Products.CMFPlone/issues/466

All these have been closed. Creating more complex demo content should be moved to its own issue.
