### ISSUE TITLE
manage-viewlets screen not functional (csrf protection?)

### ISSUE THREAD

**Issue by polyester** [plone/Products.CMFPlone#625]
On Plone5b2, the @@manage-viewlets screen does not work:

- reordering
- hide/show
- once clicked, the screen interacts in weird ways with the toolbar.

One clue: bin/instance fg gives out 
2015-06-14 15:51:35 INFO plone.protect aborting transaction due to no CSRF protection on url http://localhost:8080/Plone/@@manage-viewlets

**Comment by tomgross** [comment]
Already registered: https://github.com/plone/plonetheme.barceloneta/issues/16

**Comment by polyester** [comment]
Sorry, it came up in our accessibility testing here in Tokyo.
