### ISSUE TITLE
Archetypes and CMFDefault dependency

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#626]
Due to recent changes in Plone 5 about CMFDefault (removed dependency! :+1: ) this package is excluded also when Archetypes is included.

What about adding an explicit dependency from Archetypes to CMFDefault?

PS: anybody can activate Archetypes issue tracker?

**Comment by tomgross** [comment]
Why? There are no CMFDefault dependencies in AT or ATCT.

**Comment by keul** [comment]
My fault, Archetypes source was not updated
