### ISSUE TITLE
Generated absolute urls with domains in plone resource bundle.

### ISSUE THREAD

**Issue by jkubaile** [plone/Products.CMFPlone#629]
We just "deployed" a Plone 5.02b based portal as a local intranet solution. The instance was set up via url http://host:8080/Plone. 

After deployment we want to change the url and added a rewrite on a apache instance so the portal is accessable via http://anotherhost/intranet. This results in missing icons on the edit bar, after login. Looking deeper shows browser messages, complaining about cross-domain access for ressources. In detail the included bootstrap fonts.

Re-building the "plone" bundle (via the resourceregistry-control panel) via the new anotherhost url fixes the icons. But now, the old page has the broken icons cause of the missing font.

This is also relevant for mixed http/https setups and probably will also avoid to serve a portal under different domain names.

**Comment by vangheem** [comment]
Yikes. Rewriting all urls defined in css to be relative should fix the problem.
