### ISSUE TITLE
4.3.6  - DX content types deletion lead to uncatalog error log

### ISSUE THREAD

**Issue by simahawk** [plone/Products.CMFPlone#636]
I'm experiencing this error on a bare 4.3.6 instance. If you use AT types it works fine. If you use DX objects and you delete them you get:
```
2015-06-17 12:23:32 ERROR Zope.ZCatalog uncatalogObject unsuccessfully attempted to uncatalog an object with a uid of /DX/test. 
```
whereas "test" is DX folder o or a  DX page.

Judging from the catalog ZMI interface catalog/uncatalog operations are working, so I wonder what this error line means.

The version of ZCatalog is: Products.ZCatalog-2.13.27

**Comment by simahawk** [comment]
side note: the only reference I found for that msg is into PDBDebugMode [here](https://github.com/collective/Products.PDBDebugMode/blob/master/Products/PDBDebugMode/pdblogging.py#L19)

where it says that there's a "known issue" to ignore :)

Where this is "known".... I don't know :)

**Comment by simahawk** [comment]
I think we might have an issue w/ zope events here, because I placed a pdb into "uncatalogObject" and this is called BEFORE confirm the deletion of the object (!!!) and this leads to uncataloguing the object before real deletion.
That's the reason why every next time the method is called you get the error: because it has been already uncatalogued.

**Comment by thet** [comment]
Do you have transmogrifier installed? IIRC, I got this error with transmogrifier in place, but not without.

**Comment by thet** [comment]
However, a clear understanding of this error would help a lot.
Here is some useful information: http://old.zope.org/Members/rmore/unsuccessfulUncatalog
It's not online now, so here is the archive.org'd version: https://web.archive.org/web/20060425014916/http://www.zope.org/Members/rmore/unsuccessfulUncatalog

**Comment by simahawk** [comment]
yes I have transmogrifier egg loaded since I need to do a migration.
So, you mean that transmogrifier modify the way deletion event is handled?
I'll try without it...

**Comment by simahawk** [comment]
Seems you are right... after removing the conf for the migration it looks like the error is gone :)
I guess we should consider this issue closed?

**Comment by thet** [comment]
i was happy when i found out this solution :)
even i don't understand it.
i had several transmogrifier packages installed, do you know, which one caused the error?

another transmogrifier package gave me an VirtualHostMonster error, which is why i had to patch it like so (only when migration is active, of course):
```
from Products.SiteAccess import VirtualHostMonster as vhm
from zExceptions import BadRequest
import logging

logger = logging.getLogger(name='amKumma migration')
orig_VirtualHostMonster = vhm.VirtualHostMonster


class VirtualHostMonster(orig_VirtualHostMonster):
    def manage_afterAdd(self, item, container):
        try:
            super(VirtualHostMonster, self).manage_afterAdd(item, container)
        except BadRequest:
            logger.warn('ignored: "BadRequest: This container already has a Virtual Host Monster"')  # noqa
            return
vhm.VirtualHostMonster = VirtualHostMonster
```

**Comment by thet** [comment]
and yes, for CMFPlone, we can close this issue. it's related to transmogrifier, however.
