### ISSUE TITLE
plone.batching fails if b_start is too high

### ISSUE THREAD

**Issue by gbastien** [plone/Products.CMFPlone#639]
Hi @do3cc @tomgross, I saw you worked on plone.batching

Let's say I have a page using batching, 20 elements by page, 41 elements so 3 pages

I send a link to the last page to someone by mail.  Then I remove one element making my batch only having 2 pages now.

If I try to access http://mypage/...&b_start=40, it fails with a :

Module plone.batching.batch, line 231, in previous_pages
ValueError: 3 is not in list

I would like to update code so if the b_start is too high, it falls back to last page, does that seem right?

Thank you!

Gauthier

**Comment by gforcada** [comment]
I'm not them, but yes, a pull request to get the last existing page would be a good fallback. Way better than an error :+1:

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone.batching/pull/8
