### ISSUE TITLE
Products.CMFPlacefulWorkflow version in metadata.xml is old

### ISSUE THREAD

**Issue by yuseitahara** [plone/Products.CMFPlone#640]
Hi,
I found that Products.CMFPlacefulWorkflow version in two files below is still 1.4.1
although the true version of that product is 1.5.10 in Plone 4.3.6.

Products/CMFPlacefulWorkflow/profiles/base/metadata.xml
Products/CMFPlacefulWorkflow/profiles/default/metadata.xml

And due to that, Plone's add-ons page shows a wrong warning message.

**Comment by vangheem** [comment]
Why does a warning message show? metadata.xml files do not need to mirror actual product versions. If fact, packages should be using metadata versioning like this: https://github.com/collective/wildcard.media/blob/master/wildcard/media/profiles/default/metadata.xml#L3

Then, warnings should only show if there is a profile upgrade step that needs to be run.

I'm closing for now. Please feel free to re-open with more information.
