### ISSUE TITLE
PLIP Enhance Contentlisting

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#646]
Proposer: Johannes Raggam
Seconder:

Motivation
----------

The package ``plone.app.contentlisting`` defines a ``@@folderListing`` view,
which can be used to iterate over the contents of a folder with optional filter
criteria. The items of the list are wrapper around the contents, returning it's
attributes from the content brain or the content object, if needed.

Until up to 1.2, ``plone.app.contentlisting`` did only work for folders, but
not collection results. Since 1.2, there is a new view, ``@@contentlisting``,
which works on folder contents and collection results. The new name was due to
the term ``@@folderListing`` (note the uppercase "L") would not work
semantically for collections. In favor of a simpler API without unnecessary
duplication of functionality, I propose to deprecate the ``@@folderListing`` in
favor of the enhanced ``@@contentlisting`` view and to remove the
``@@folderListing`` for a upcoming version.

Proposal & Implementation
-------------------------

The functionality was implemented in this pull request and is already merged:
https://github.com/plone/plone.app.contentlisting/pull/6

The packages' documentation is already updated.

All references of @@folderListing in core packages and documentation should be
updated.

The new functionality should be documented in docs.plone.org.

An upgrade notice should be written.

Implications
------------

The current Implementation of ``@@contentlisting`` does only work with
Dexterity collections. It's tested only with plone.app.contenttypes' collection
behavior.

Risks
-----

Until ``@@folderListing`` is removed, there are no risks. Code depending on
``@@folderListing`` will still work, while the new ``@@contentlisting`` can be
used.

Once removed, legacy code depending on ``@@folderListing`` will break.

Participants
------------

Johannes Raggam

Progress
--------

 [X] Implementation.
 [X] Package documentation.
 [ ] References to ``@@folderListing`` in core code.
 [ ] References to ``@@folderListing`` in core documentation.
 [ ] Core documentation of new functionality.
 [ ] Upgrade notice.

**Comment by tisto** [comment]
@thet following our FWT discussion from yesterday I would consider this to be a clean up task that does not require an additional PLIP. There have been PLIPs for the collection/p.a.contentlisting already and this should have happened as part of those PLIPs. If I understand the code correctly, we are not removing the old @@folderListing. We just have to make sure that we do not break ATContentTypes support when working on that. I would recommend to keep the pull request merged and continue to work on the issues mentioned above. Thanks for your work!

**Comment by tomgross** [comment]
What I'd love to see is a deprecation / removal process in Plone. Like
 1. Introduce a new feature
 2. Deprecate an existing feature incl. a date / version when it will be removed
 3. Adjust documentation
 4. Create an issue for removing it
 5. Remove it to the communicated date / version
 6. Adjust documentation and tests

Now we have comments and conditions in our codebase saying: Remove this when on Python 2.4!

**Comment by tisto** [comment]
@tomgross Absolutely! @jensens started to work on this. Though, unfortunately it seems things are a bit more complex than we initially thought.

**Comment by jensens** [comment]
it's on-hold at the moment, too many other tasks. but I'll definitely will continue on this in the next weeks.
