### ISSUE TITLE
PLIP 13350: Define extra member properties TTW

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#649]
See https://dev.plone.org/ticket/13350 for details. I added this PLIP here in order to track our progress on working on the remaining issues that are necessary to merge this pull request.

ToDo:

[ ] Fix plone.app.users test isolation issues
[ ] Write second PLIP review
[ ] Merge PLIP

**Comment by tisto** [comment]
I suspect that the test isolation problem is somehow caused by the BaseTestCase in base.py. This base class uses the functional test layer even though it is used for functional and integration tests.

**Comment by tisto** [comment]
I just removed all test code except testing.py and test_schema_types.py that fails due to a missing "Home Page" field on the login form. 

https://github.com/plone/plone.app.users/tree/plip13350-tisto-minimal-test-setup

Running "bin/test -s plone.app.users -s plone.app.customerize" still fails. I guess this is because the userschema.xml is not properly loaded. I refactored the test setup to follow our best practice and that did not solve our test isolation problems. Therefore I think the key to solving our problem is to figure out why userschema.xml is not properly loaded.

**Comment by tisto** [comment]
I also investigated the second test failure: 

flexible_user_registration.rst: "LookupError: name 'form.widgets.IUserFormSelection.forms:list'"

The plone.schemaeditor form is missing the field_extender "Where should this field be shown?". This is just a field extender that is registered in the configure.zcml. I really don't get why the extender is not present in the test setup.

**Comment by ebrehault** [comment]
I am not sure the problem comes from `userschema.xml` not being loaded. The underlying problem is about the `configure.zcml` not being loaded.

**Comment by bloodbare** [comment]
Can we merge ?

**Comment by ebrehault** [comment]
@bloodbare: as you asked I tried LDAP, but it is currently globally broken for Plone 5 (see https://github.com/plone/plone.app.ldap/pull/21#issuecomment-120119103 ), so I guess it makes it a separated issue.

So I think we can merge it (do you know if there have been any progress regarding the test isolation issue during the sprint ?)

**Comment by vangheem** [comment]
How many packages does this cause test isolation issues with? Can we just add plone.app.users to the test isolation section?

**Comment by ebrehault** [comment]
@vangheem yes we can do that, but @tisto thinks it is not a long term solution, and I agree with that. We need to fix this problem or we will end up with all our packages in the test isolation group.

Regarding conflicts, I have identified at least one package: plone.app.customerize.
You can see the error by running:
```
bin/test -s plone.app.users -s plone.app.customerize
```
But @tisto removed plone.app.customerize from the tests and we still had issues when running `bin/alltests`, so there are other conflicting packages here, but I do not know which ones.
