### ISSUE TITLE
Encoding problems with Mockup Select2 widget

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#650]
With plone.app.widgets under Plone 4.3 or the standard Plone 5 installation, the following problem occurs when choosing a value with non-ASCII characters from the vocabulary result presented by the Select 2 widget:

- Edit a content item, go to the categorization tag, save a new category with non-ASCII data in it (e.g. "Nåøï"). Click Save.
- Open the Edit view again. Go to the categorization tab. No surprises until now.
- Delete the item from the Select2 widget and select the item from the list again. Or any other item with non-ASCII characters in it. Click Save.

The Subject tag is presented with binary encoded data. That's because the vocabularies token attribute saves it with the ``binascii.b2a_qp`` function, while value and title are just stored as unicode values.
The ``@@getVocabulary`` from ``plone.app.widgets.browser.vocabularies``, resp Plone 5, ``plone.app.content.browser.vocabularies`` uses the token instead of the value.

Two pull requests fixing it are underway.

**Comment by thet** [comment]
Closed via https://github.com/plone/plone.app.content/pull/34

**Comment by davisagli** [comment]
I don't think that fix is correct. It's appropriate for forms to deal with tokens. It sounds like maybe we're missing a widget converter to turn the token back into the corresponding value on the backend when the form is submitted.

**Comment by thet** [comment]
Hope this fixes it: https://github.com/plone/plone.app.z3cform/pull/34

**Comment by thet** [comment]
:collision:
but makes sense, what you suggest.

i always avoided to get into the concept of vocabularies, because i always thought simple lists or dictionaries would be all we need.  :hammer:
