### ISSUE TITLE
Archetypes are not functional (without ATContentTypes) in Plone 5

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#651]
Some of the AT functionality of CMFPlone moved to ATContentTypes (like the createObject script, portal_factory). This code really should live in Archetypes. Otherwise it is not possible to use pure AT content without ATContentTypes in Plone 5.

[ ] Analyze dependencies
[ ] Write a test for it
[ ] Make AT without ATContentTypes work

**Comment by tomgross** [comment]
Related to https://github.com/plone/Products.CMFPlone/issues/124 and https://github.com/plone/Products.CMFPlone/issues/635

**Comment by ebrehault** [comment]
ATContentTypes provides a "Archetypes-tools without content-types" profile for Plone 5 which installs all those needed elements without the content types themselves.
So, we just need to add this profile in our `metadata.xml` for our old AT products, and it just work.

So it is not actually a bug, but yes we could save an extra dependency if we move that stuff into Archetypes.

**Comment by tomgross** [comment]
So Archetypes depends on ATContentTypes (another circular dependency). That sounds rather strange to me.

**Comment by ebrehault** [comment]
No, there is no circular dependency here, Archetypes does not depend on ATContentTypes, but AT-based products must depend on ATContentTypes and Archetypes.
So clearly that's not ideal, but I do not think we must mark it as a bug for Plone 5 (implying we cannot release Plone 5 until it is fixed).

**Comment by tomgross** [comment]
I see 2 solutions to this:
1 - refactor AT and ATContentTypes so AT is self contained. This is
probably to late now, since we are in a beta. in the long run this would be
the cleaner approach. it would allow us to ship Plone with AT but without
ATContentTypes sometime later
2 - Add a *createObject* script to AT skins. This would asure minimal
compatibiliy with too much changes to the current products.
I see pros and cons to both solutions but since we are in a beta and AT is
a dying horse, 2 is my favorit.
Eric BREHAULT <notifications@github.com> schrieb am Do., 25. Juni 2015 um
21:00:

**Comment by tomgross** [comment]
Here is an implementation of 2:

 - [ ] https://github.com/plone/Products.Archetypes/pull/47
 - [ ] https://github.com/plone/Products.ATContentTypes/pull/21

**Comment by vangheem** [comment]
I also prefer #2 and am fine with this change. Anyone object to merging?

**Comment by pbauer** [comment]
Merged
