### ISSUE TITLE
Folder restrictions don't seem to work in Plone 5

### ISSUE THREAD

**Issue by frapell** [plone/Products.CMFPlone#653]
I have just found this, not sure right now which component is to blame, but basically, if you add a restriction to a folder in a brand new Plone 5 site, you still can add content to it. This is on latest pull from buildout.coredev ( plone/buildout.coredev@afed1814335f083d190e721eec81f8241f4f5eaf )

Steps to reproduce:

1) Create site from scratch
2) Add a folder ( http://localhost:8080/Plone/++add++Folder )
3) Name it whatever (Test Folder)
4) Go to folder restrictions ( http://localhost:8080/Plone/test-folder/folder_constraintypes_form )
5) Select manually and uncheck all of them, and save

At this point, the "Add new" no longer lists content to add, however, if you know the URL you can still add them.

http://localhost:8080/Plone/test-folder/++add++Collection
http://localhost:8080/Plone/test-folder/++add++Event
http://localhost:8080/Plone/test-folder/++add++File
http://localhost:8080/Plone/test-folder/++add++Folder
http://localhost:8080/Plone/test-folder/++add++Image
http://localhost:8080/Plone/test-folder/++add++Link
http://localhost:8080/Plone/test-folder/++add++News%20Item
http://localhost:8080/Plone/test-folder/++add++Document

Expected result:

Disallowed objects should not be allowed to be added

**Comment by vangheem** [comment]
Maybe this was never enforced in dexterity?

**Comment by vangheem** [comment]
I've made a PR to address this: https://github.com/plone/plone.dexterity/pull/31

**Comment by vangheem** [comment]
@frapell would you mind reviewing and merging if tests pass and you think this is fine. Thanks.

**Comment by gforcada** [comment]
The pull request got merged, so closing this...
