### ISSUE TITLE
Inconsistent visual for required fields

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#654]
See screenshot. Placement and visual for required fields differs in z3c.form controlpanel
![1435307687096screensave](https://cloud.githubusercontent.com/assets/594239/8373670/207ebeb0-1bef-11e5-850e-b04da87fb517.png)

**Comment by davisagli** [comment]
The indicator next to the checkboxes was already removed https://github.com/plone/plonetheme.barceloneta/commit/9bdb7ef5b8ec9ca57bd1c7fbddf55005fff87e66
