### ISSUE TITLE
Event Recurrence "Repeats" field is wider than the form

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#655]
In the form that pops ups after clicking on the "add" link, the "Repeats" field isn't constrained to the form width. Perhaps "add" should be a button? Wasn't clear to me that "add" and "Does not repeat" were sub items of "Recurrence" because they have the same visual heirarchy (same size font, bold).  
![screen shot 2015-06-29 at 11 26 03 am](https://cloud.githubusercontent.com/assets/7101218/8411528/5c07f612-1e52-11e5-9a88-6c8d3a93b693.png)

**Comment by agitator** [comment]
changed font-weight and added margin to action links
