### ISSUE TITLE
Relabel in Events "Repeat" Pop-Up Box

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#656]
Correct: "Repeat on," "Selected Dates," and form fills for "Until" and "Add date."
![screen shot 2015-06-29 at 11 34 43 am](https://cloud.githubusercontent.com/assets/7101218/8411675/3e75a364-1e53-11e5-8974-5f9715349ba6.png)

**Comment by ltakens** [comment]
Looks sane to me. Running on master.
![schermafbeelding 2015-07-13 om 15 05 17](https://cloud.githubusercontent.com/assets/12794611/8650142/e5b2b496-2970-11e5-8d98-9b64ba32256a.png)
