### ISSUE TITLE
Related Items: "select" link not needed

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#658]
Clicking on the item listed (ex, "News") should take the user to the folder/page. The user shouldn't have to click on a list item then click again on "select."

![screen shot 2015-06-29 at 11 50 06 am](https://cloud.githubusercontent.com/assets/7101218/8412030/2b828a40-1e55-11e5-8c8e-3ceb23adc0db.png)

**Comment by vangheem** [comment]
I think it works with a double click. The reason it's like this is because when you have nested folders, single click allows you to navigate through them.

**Comment by vangheem** [comment]
Perhaps there should be a select button on each item so you can still navigation to sub-folders.

**Comment by 3dogMcNeill** [comment]
I see what you mean (re: subfolders)...what if it functioned more like how it is now (v4.3.2) where folders are links to subitems? 
![screen shot 2015-06-29 at 2 01 00 pm](https://cloud.githubusercontent.com/assets/7101218/8414679/ac683df0-1e67-11e5-883b-0db1b904a7ff.png)

**Comment by vangheem** [comment]
@3dogMcNeill it is working that way now. I've updated the widget to be more consistent look and feel with the main selection.

![screen shot 2015-07-02 at 1 16 27 pm](https://cloud.githubusercontent.com/assets/524413/8484307/965b9988-20bc-11e5-9c19-72523c79e575.png)

**Comment by vangheem** [comment]
so now, single click loads folder items, arrow button and double click starts searching related items in that folder.
