### ISSUE TITLE
email_from_address registry setting not being used everywhere yet

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#661]
Latest culprit is PasswordResetTool, sending reset requests.

Do we need to override <portal object>.getProperty so we can get the email_from_address property from the registry instead or is that a little too magical?

**Comment by tisto** [comment]
I would prefer to replace the getProperty lookups with p.a.registry lookups. This is what we did for all other packages.

**Comment by vangheem** [comment]
fixed with https://github.com/plone/Products.PasswordResetTool/pull/9
