### ISSUE TITLE
Keywords links

### ISSUE THREAD

**Issue by Martronic-SA** [plone/Products.CMFPlone#664]
I've read somewhere (but I can't remember where...) that it was better in a searchengine point of view, to have keyword links point to http://www.plone.org/@@search/documents instead of http://www.plone.org/@@search?Subject=documents

I've already done modifications in order to achieve that.

Is someone aware of that?

**Comment by jaroel** [comment]
This would be correct if you do content listings, for example products in a webshop.
You should not do ```/products?category=football&subcategory=shirts&color=red``` but ```/products/football/shirts/?color=red```.

For pages that need to filter the output based on user input it is more than ok to use ```/search?keyword=red football shirts```.
Search engines will index a lot a duplicate content if you do not do this. Google will actually penalize you for that :)
