### ISSUE TITLE
delete_confirmation deletes before confirmation

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#666]
When using the "delete" action, which calls ``OBJECT/delete_confirmation``, a cpy script in ``skins/plone_form_scripts/delete_confirmation.cpy`` in Products.CMFPlone, the following events are thrown (note, i put ``print`` statements into zope.event and transaction):

```
<ZPublisher.pubevents.PubStart object at 0x7f396e3b4410>
<zope.traversing.interfaces.BeforeTraverseEvent object at 0x7f397038f150>
<ZPublisher.pubevents.PubAfterTraversal object at 0x7f3970531e90>
TRANSACTION SAVEPOINT
<OFS.event.ObjectWillBeRemovedEvent object at 0x7f396e472750>
TRANSACTION JOIN
<zope.lifecycleevent.ObjectRemovedEvent object at 0x7f396e472750>
<zope.container.contained.ContainerModifiedEvent object at 0x7f396e472750>
<ZPublisher.pubevents.PubBeforeCommit object at 0x7f396ec62810>
TRANSACTION COMMIT
<ZPublisher.pubevents.PubSuccess object at 0x7f396e305490>
<zope.publisher.interfaces.EndRequestEvent object at 0x7f39700c2b90>
TRANSACTION ABORT
```

After that, the delete_confirmation page is show. Pressing "Cancel" does not emit any more events nor a TRANSACTION JOIN, but pressing "Delete" repeats the events from before, resulting in a deleted object.

This makes it quite hard to hook into the event machinery to run some code AFTER a object was really deleted. Due to a comment in ``delete_confirmation.cpy`` I suspect this whole weirdness has something to do with the link integrity feature.

**Comment by thet** [comment]
This happens, when delete_confirmation is confirmed with the "Delete" action:
```
<ZPublisher.pubevents.PubStart object at 0x7f3970685b90>
<zope.traversing.interfaces.BeforeTraverseEvent object at 0x7f39705c4650>
<ZPublisher.pubevents.PubAfterTraversal object at 0x7f396e7cb3d0>
TRANSACTION SAVEPOINT
<OFS.event.ObjectWillBeRemovedEvent object at 0x7f396e7d5250>
TRANSACTION JOIN
<zope.lifecycleevent.ObjectRemovedEvent object at 0x7f396e7d5250>
<zope.container.contained.ContainerModifiedEvent object at 0x7f396e7d5250>
<OFS.event.ObjectWillBeRemovedEvent object at 0x7f397d1d9850>
TRANSACTION JOIN
<zope.lifecycleevent.ObjectRemovedEvent object at 0x7f397d1d9850>
<zope.container.contained.ContainerModifiedEvent object at 0x7f397d1d9850>
<ZPublisher.pubevents.PubBeforeCommit object at 0x7f396e16c950>
TRANSACTION COMMIT
<ZPublisher.pubevents.PubSuccess object at 0x7f396e16c950>
<zope.publisher.interfaces.EndRequestEvent object at 0x7f396e16c950>
TRANSACTION ABORT
```

**Comment by thet** [comment]
Note, in Plone 5 the delete_confirmation story was refactored and IObjectRemovedEvent is thrown only once, after the confirmation.

**Comment by idgserpro** [comment]
Maybe https://github.com/plone/plone.app.linkintegrity/blob/master/plone/app/linkintegrity/NOTES.txt#L165 can give you a hint.

**Comment by vangheem** [comment]
Isn't this broken because of this
https://github.com/plone/Products.CMFPlone/issues/255

**Comment by thet** [comment]
@vangheem the issue i was describing only occurs in Plone 4.3. It might not get resolved, because as described in the document @idgserpro referenced, it was intentional.
But we shouldn't accept this weired behavior in Plone 5. There should be a better way doing it. The ObjectRemovedEvent should really only fired once in a request and only if the object was deleted successfully. Otherwise, the event doesn't help much.
On the other hand, there might still be a conceptional problem: When the ObjectRemvoedEvent is fired after a transaction join, the transaction can still be aborted or not commited successfully.

**Comment by jensens** [comment]
since this is a upt-to 4.3 thing i'd keep it there as is and not chnage it. usually its not a problem. in 5 its fixed. so i close here
