### ISSUE TITLE
Toolbar: display Add item, Workflow and More options icons in the Folder contents view

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#685]
I think there's no reason to hide those icons from the toolbar on that view. I know we have a dedicated `Add` button in the folder content's navbar but that shouldn't be enough to break the expectability that is present in all but the management or accessory (sharing, select_default_page, sitemap, contact-info) views.

Related to: https://github.com/plone/Products.CMFPlone/commit/c14ffd203ac8ed132085b315056fdc3b640101eb#commitcomment-12184434

**Comment by djay** [comment]
also see https://github.com/plone/Products.CMFPlone/issues/482

**Comment by davilima6** [comment]
I saw it but since it's more specific to the Contents view I thought I should create a separate issue. Are you +1 on this? Should I include it in #482?

**Comment by vangheem** [comment]
I'm not sure. When you are in folder contents, you should be using it, not the toolbar.

**Comment by davilima6** [comment]
I think it's best if we look at it from the "it's all Plone, one part of it is missing" perspective instead of enforcing the user what he should or shouldn't do in each view (unless it breaks sth).

I mean, even from configuration screens you can always `Write` a new message in Gmail, in the same manner `Post` is always available in mobile Facebook and GooglePlus, so why should our `Add` button  be missing from time to time?

**Comment by vangheem** [comment]
It's good to prevent the user from doing things they don't expect. There is already an add button in folder contents. Changing context with folder contents...

**Comment by davilima6** [comment]
I didn't understand your last sentence... What would be the unexpected situation we could avoid?

Re: add button IMHO if I had to choose I'd leave it where it belongs most of the time (the toolbar) but since we also have an Upload button (and mostly because of that) I think there's no problem keeping them both. I think global controls shouldn't be made out of hand because of local replacements unless they conflict or are superseded somehow.

**Comment by djay** [comment]
I think later we can make "add new" totally global by including a field to pick where content goes (like #464). 
I think there are two things going on. 
- Some root views like site-map, logged in etc have no toolbar at all. They should probably have the same toolbar as root.
- There is a bug I think where views on content objects such as sharing, restrictions etc are missing the contentmenu dropdowns ie actions, display and add new.

**Comment by djay** [comment]
@vangheem There is a simple version of merging the state and sharing menus that we can do easily now. Move sharing into the state menu. Then you reduce the items by one.
I really do think sharing and workflow are tightly related and probably that menu is better called sharing than state. Sharing private, sharing published.

**Comment by davilima6** [comment]
I really like Plone's paradigm of acting in context so I see some risk in option 5 from #464: loosing this mental model too much. Although it might be a harmless and really nice shortcut, I'm not sure if for Plone 5.0 since community feedback would be important for such a change.

Re: 1) I do have see toolbar in the mentioned views, even simpler: only Content Info and User Actions and of course no Contents, View and Sharing icons.

Re: 2) I confirm that behavior but I understand why it can be seen as a feature. Being on those views means you are already in the proccess of configuring the content object so Plone can give you less buttons to worry about. Not the same as in Folder Contents, which is the main content manipulation screen.

**Comment by vangheem** [comment]
This is done.

**Comment by djay** [comment]
The following views still don't have toolbar items
- sitemap
- search
- accessibility

Also not sure about the contents being in an overlay. Without being able to use the toolbar then I think we lose the ability for object tabs to be applied to the folder in a default page... unless they have the info message saying you are editing the default view, click here to edit the folder. All thats there for the builtin stuff but I'm not sure it works for plugins.

Also, all this overlay stuff means we have zero chance of theming the backend separate from the frontend I think. I think it means that your front end theme doesn't just have to include a small amount of js for the toolbar but the entire plone UI right?

**Comment by vangheem** [comment]
The contents being in an overlay was actually a bug that is fixed. Those buttons were set in portal_actions to have modals but the integration was broken. I fixed that integration and changed those buttons to not show in a modal. Upgrade step is in place also but there is no upgrade when testing from master--try creating a new site.
