### ISSUE TITLE
Contents:  "workflow" wording should be consistent with the toolbar (ie "state")

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#686]
The word workflow hasn't been used much in plone UI. The toolbar uses "state". Previous versions used "changed state" in folder contents. I think being consistent and using the word "state" is best. @plone/ux-team ?

**Comment by vangheem** [comment]
closed https://github.com/plone/plone.app.content/commit/c80c127c42bb90b516f1867ca6ba4143bf88ecbc
