### ISSUE TITLE
No way to search if themer removes search (search in toolbar/contents)

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#687]
# User problem
The themer may decide they don't want a site search in their public theme. This then leaves them with limited options to allow the editor/admin to be able to manage their content.
A themer might also decide they want to disable live search for the viewers but want to keep it for editors.
Even if the themer decided to keep search, having it in the toolbar or contents provides a consistent user experience for the editor.

# Options
1. Search inside Contents
  - con: mixing up the mental model. Contents currently is only about the current folder.
  - pro: actions can be performed on searched content
  1. Depth control on Search box in Contents (ie radio of "folder", "subtree", "whole site")
  1. separate search field or search button inside contents
2. have a search built into the toolbar.
  - quick search popout that loads the contents view for results.
3. other ideas @plone/ux-team ?

**Comment by davilima6** [comment]
+1 for keeping it where it is. It seems you want to put entire Plone in the Toolbar. I understand the spirit but I think Toolbar's fit for logged-in users only. I'm +1 that every functionality that's interesting to Anonymous - such as portal message, site-wide search and byline - should remain in themed area.

**Comment by djay** [comment]
@davilima6 you misunderstand. I never said remove it from the themed area. I'm suggesting all useful to an editor should also be available outside of the themed area.

**Comment by djay** [comment]
and things not useful the non-editors should not be in themed area.

**Comment by davilima6** [comment]
Sorry, I thought you wanted to move it.

So to be clear: +1 for having it along with traditional search if it's really discrete ie do not compete with the viewlet. When duplicated it's a convenience. When themer removes it (minority of times imo), editors still keep search always available (instead of going to /search).

**Comment by hvelarde** [comment]
isn't just easier to use the `userrole-anonymous` class on the body tag to drop the search bar using Diazo?

**Comment by davilima6** [comment]
Question is: does the usecase "Themer drops search viewlet; Authenticated must have fallback" need to be supported ootb? If not we could go for documentation here, providing Diazo snippet to move search viewlet into toolbar css:if-not-content=". userrole-anonymous" or just insert new markup and styles.

**Comment by hvelarde** [comment]
IMO, this is not a use case for the Plone core.

**Comment by jensens** [comment]
dont we have a search portlet that could be enabled for a group or such if this is needed? I dont think this is a real problem - and so no use case.
