### ISSUE TITLE
can't see the current content type you are viewing

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#703]
# user problem

The user can get confused what they are viewing. Currently the only ways to know what they are viewing is to click edit.
# options
1. in the toolbar change "Edit" button to "Edit Folder" or "Edit Page" so the content type of the current context is visible. comes from #482 
2. ??

**Comment by vangheem** [comment]
No easy way to do this with current framework we use for rendering buttons. No way to make dynamic button titles for the "Edit" button. This will have to wait until Plone 5.1 when we plan up updating the framework around toolbar buttons.

**Comment by tkimnguyen** [comment]
(almost a year later) Has the toolbar button framework been changed to support this?

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
