### ISSUE TITLE
expect to see "upload" under "add new" dropdown.

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#707]
# user problem

Some other CMS's have upload at the same place you can add content. Users might not think to look under contents to upload multiple items at once. (from #482)
# options
1. Add "upload" as the last item in the "add new" drop down.
   - same overlay as in upload contents
   - probably should go to the contents view after upload

**Comment by jensens** [comment]
Probably a thing to be adressed in Volto. I dont think this will happen in classic Plone.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
