### ISSUE TITLE
ability to customise the toolbar

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#708]
# user problem
- Different styles of sites might make more use of some features which are obscured in the toolbar. themer or admin should be able to influence this
- Individual users might like to customise the toolbar.
- Some sites workflow might require extra quick links or notifications like review list etc.
- some plugins might install too many items making it hard to get to the ones you do use.

from #482
# Options
1. give an edit toolbar option to set a custom layout. rearrange or remove items.
2. registry settings by admin or themer
3. portlets in the toolbar
   - either a version of the dashboard or a new portlet manager
   - either in the main toolbar or as an extra popout

**Comment by jensens** [comment]
Toolbar is a viewlet manager, one can override those viewlets. I don't think we will support more soon,.
I close this request for now. If you plan to work further on this please reopen and go on.
