### ISSUE TITLE
mobile: icon to open toolbar might could obscure

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#710]
# user problem

Can't predict the layout of a theme but something important like a menu might be under the top right.
# options
1. themer can style it to be in a different place
2. allow the user to drag it where they want
   - when the toolbar is open it moves to the top
   - when closed it returns to where the user last left it

**Comment by vangheem** [comment]
I think we just have to rely on option 1 don't we?

**Comment by jensens** [comment]
1 is how it works
