### ISSUE TITLE
"view" takes up extra space on the toolbar

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#711]
# user problem
- With plugins the toolbar can get crowded very quickly. esp on mobile you will have scroll (see #482)
- "View" doesn't serve much purpose. It is mainly there to get you back from all the other "backend" views. However most have "cancel" or close buttons which do the same.
# options
1. remove the "view" toolbar item
2. ensure all the backend views have a consistent close in the top right corner
   - e.g. contents

**Comment by jensens** [comment]
I think time showed the value of ``view``. Since its an action its easy to remove in customer setups, even TTW. This can be closed.
