### ISSUE TITLE
Clipboard cleared after paste

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#718]
In all former Plone versions you could copy an object and paste it multiple time within the folder_contents view. This is no longer possible in Plone 5. It seems that the clipboard information is deleted directly after paste...not sure why this is the case. The semantics of copy&paste on all most all IT systems are basically as in older Plone versions: you can paste as often as you want.

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.content/pull/44
