### ISSUE TITLE
plone.app.users upgrade step does not disappear

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#719]
overview-controlpanel displays this upgrade step all the time...it does not go away...

![Uploading screenshot-dev1.veit-schiele.de 8080 2015-07-18 13-24-18.png…]()

**Comment by mauritsvanrees** [comment]
Fixed in https://github.com/plone/plone.app.users/commit/b25c39c2dcf7cae76e05f3dae92eb1b47d111f86
Available in Plone 5.0b4.
