### ISSUE TITLE
folder_contents...three ways to open a content object

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#720]
The new folder_contents provides three way to open a content object:

- you click on the title
- you click on the icon within the same table cell
- you click on 'open' from the content object's dropdown menu on the right.

It does not make sense to have three redundant way to do the same thing.
At least remove "open" from the object's dropdown menu and add an 'edit' icon beside the 'view' icon. Being able to edit a document quickly with *one* click is more important than opening a document in three different. ways.

**Comment by vangheem** [comment]
The view icon is for because you can not get to folders otherwise. Having it on all objects is there to make it consistent.

I think the "Open" button needs to be removed.

**Comment by zopyx** [comment]
An additional edit icon would be super useful. I have many usecase and
customers where the extra click and additional page load for the standard
view could be omitted (being more productive).

2015-07-18 20:51 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

**Comment by davilima6** [comment]
+1 for adding `edit` and removing `open` button

**Comment by vangheem** [comment]
This was already discussed here: https://github.com/plone/mockup/pull/520

There is differing opinions and no obvious best way.

This ticket is just because we now have redundant ways to "open" content--just need to remove it in the pull down.
