### ISSUE TITLE
sorting in control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#721]
The items of the control panel are completely unsorted (should be sorted in alphabetical order (depending on the current language in Plone).
![screenshot-dev1 veit-schiele de 8080 2015-07-18 13-35-44](https://cloud.githubusercontent.com/assets/594239/8761438/07d76bf4-2d52-11e5-8540-82fd53932690.png)

**Comment by vangheem** [comment]
At the sprint it was discussed that it should always be sorted by English titles.

I wonder if that is due to integrators using Plone in multiple languages though and that most users would just prefer it sorted in their own language.

**Comment by djay** [comment]
If we could get the research I'd much prefer it was sorted based on most used. I would think that themeing and addons would come first. but for sure they should he sorted consistently despite language.

**Comment by zopyx** [comment]
Sorting on English titles is completely nonsense and does not make any
sense at all.
Sorting based on "frequently used" or "most important" might be an argument
but not EN titles only.
So why are other lists sorted by the current UI language?

2015-07-19 5:36 GMT+02:00 Dylan Jay <notifications@github.com>:

**Comment by polyester** [comment]
Points that came up in the discussion:

- sorting on localized language is very annoying for people having/using sites in more than 1 language, because the ordering changes all the time. People are creatures of habit.
- there is precedent for this: look f.i. to controlpanel settings on OS X (or Ubuntu or Windows), they are not sorted by local language.
- the best would be to sort according to 'semantic logic'. A start is already that there are groups now, which makes the sorting within those groups less of an issue. Also the icons make it already easier.
- but we need some real discussion and not just a few person's opinion, to decide what that order is.

**Comment by davilima6** [comment]
+1 for sticking with alphasort until more research/discussion is done.

I think we need to be careful not to make the classical Plone for Plonistas mistake here. I can also feel the pain of having items changing places but EN-ordering is a solution that only works for a specific group of long-time users. If we aim for first timers around the globe most people won't be supported by any logic when looking for items.

**Comment by pigeonflight** [comment]
I tend to remember the location of items in a control panel based on spatial and visual clues (icons). I am much less likely to remember the name (which would be needed for me to search alphabetically). 

I don't know if I represent the majority of users.

I think is more important that items are available in a consistent and predictable location, than how they are sorted.

As long as the locations remain consistent and predictable. Either of the approaches shown in the screenshots below are fine with me.

Alphabetical sorting in Ubuntu
![image](https://cloud.githubusercontent.com/assets/31827/9010811/e49efd10-376e-11e5-96bf-f0f08e62ee4f.png)

Not Alphabetically sorted in OS X
![image](https://cloud.githubusercontent.com/assets/31827/9010733/5f974b7c-376e-11e5-9eef-1a8fba721745.png)

**Comment by jcerjak** [comment]
> What's missing for Plone is a spotlight type search for the control panel.

+1

**Comment by jensens** [comment]
sorting semantically and sane grouping is fine. -1 for sorting by title in any language

**Comment by sarvesh211999** [comment]
I think sorting should be done on language basis 
As a new user I first started searching alphabetically It is very difficult
