### ISSUE TITLE
text wrapping in toolbar

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#723]
See screenshot. The wrapping of the text within the toolbar is completely unacceptable. Either you adjust the width of the toolbar according to the length of the texts or you use hyphenation.
- CSS hyphenation is supported by some browsers (Firefox, Webkit/Safari) but unsupported by Chrome and even latest IE (afaik)
- use a JS based approach (hyphenator.hs) for only this part of Plone...new module, new dependency...
- put the translated terms used within the toolbar into the .po files using soft hyphens.

![screenshot-dev1 veit-schiele de 8080 2015-07-18 13-40-02](https://cloud.githubusercontent.com/assets/594239/8761458/99104550-2d52-11e5-9212-20dc3673e4a8.png)

**Comment by vangheem** [comment]
This is difficult. I'm sure other languages have even longer variants for these words.

# Options

1. Make the toolbar extra wide and hope it will work with all languages
2. Use javascript to dynamically detect this happening and for buttons it is happening on, decrease the font size to make it fit.

I'm in favor of #2.

**Comment by davilima6** [comment]
Option 3: truncate big words and test that title always informs full description, maybe adopting tooltips as progressive enhancement for higher visibility

**Comment by agitator** [comment]
would it somehow be possible to allow the user to pull out the toolbar as far as he needs it and truncate the rest?

**Comment by zopyx** [comment]
This issue is still open..unlikely that you want to release Plone 5 final with a half-broken UI.

**Comment by pbauer** [comment]
This changed to clipping (like Microsoft Phone and Metro). 
There might still be room for improvement but we need ideas fist.

**Comment by zopyx** [comment]
At least for the horizontal toolbar:
Throw away all icons and turn the toolbar into a decent dropdown menu.

Sent from a mobile device

**Comment by zopyx** [comment]
Prototype hyphenation support in Plone 5:

https://pypi.python.org/pypi/zopyx.plone.hyphenator

**Comment by thet** [comment]
this PR adresses this problem in another way - making the toolbar wider: https://github.com/plone/Products.CMFPlone/pull/1733

**Comment by zopyx** [comment]
All modern browsern -including Webkit  - implement meanwhile hpyhenation. So a single

```
hyphens: auto
```
to the CSS of the toolbar would solve most of the pain.

**Comment by zopyx** [comment]
<img width="1438" alt="bildschirmfoto 2017-10-31 um 11 32 05" src="https://user-images.githubusercontent.com/594239/32220061-8fad24b2-be30-11e7-85e9-3882b00c5776.png">

**Comment by zopyx** [comment]
I wonder why this bugfix does not show up in Plone 5.1.0?

**Comment by tmassman** [comment]
Added backport to Plone 5.1.x in PR https://github.com/plone/Products.CMFPlone/pull/2539.

**Comment by tmassman** [comment]
Merged into 5.1.x.
