### ISSUE TITLE
text wrapping in toolbar , Part II

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#726]
Related to #723:

when you minimize the toolbar then the explanatory texts will be displayed upon hovering with the mouse. Longer (German) texts appear truncated and unreadable -> visual and usability fail

**Comment by tisto** [comment]
@zopyx fyi: thanks for reporting bugs. No need to use a "Plone 5" prefix, there is a "Plone 5" milestone.

**Comment by zopyx** [comment]
There is no way to mark a bug a P5-only related.

2015-07-18 16:03 GMT+02:00 Timo Stollenwerk <notifications@github.com>:

**Comment by vangheem** [comment]
I wonder if we just get rid of the on-hover description fail. They can be quite long and it's difficult to show them nicely.

Perhaps switch in some sort of tooltip to the right instead.

**Comment by davilima6** [comment]
I think current animation looks really nice so if truncating words ([as suggested here](https://github.com/plone/Products.CMFPlone/issues/723#issuecomment-122905977)) isn't acceptable,  I'm +1 on switching to tooltips. We have to consider that custom wf states will often have bigger titles and that is also the case for most non-English localizations (it's difficult to get shorter than "Add new").

**Comment by agitator** [comment]
also leaning torwards tooltips

still the problematic with labels visible, shall we make the toolbar even wider in that case?

**Comment by rnixx** [comment]
+1 on switching to tooltips.

i'm also +1 on the idea of @agitator about resizable toolbar in #723.

further it would be nice if expanding the toolbar not changes the page with, but overlay it.

**Comment by jensens** [comment]
seems fixed.
