### ISSUE TITLE
Portlets management can be confusing

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#728]
# Problems

- [x] Clicking on one of the inherited portlets (e.g. "footer") inside the overlay causes a second overlay with the footer portlet to appear for a second and then the page reloads automatically with the footer portlet configuration screen displayed as normal page...
- [x] clicking on "Cancel" here returns to footer portlets configuration screen displayed as normal page and no longer as overlay...
- [x] Clicking "Cancel" while adding a new portlet gives a success messages "Portlet added"
- [x] overlays end up being stacked.
- [x] opacity on overlays makes it difficult to read.
- [x] poor contrast of portlet listing

See http://public.zopyx.com/portlets.mp4

# History

- at some point the mange portlets was implement into an overlay.
- @vangheem tried to make it all work within the overlay so there wasn't weird context switch after the initial overlay load. However, trying to make a lot of forms all work within an overlay is difficult and problematic.

# Solutions

- [x] Remove initial overlay. Only use overlays for specific, single-use actions within the portlet management(add portlet, edit portlet)
- [x] update styles to have been contrast for readability.

**Comment by vangheem** [comment]
Okay, @zopyx we get there are issues with portlet management. You don't need to create 3 issues that could just be 1 issue--it just makes it harder to follow the problem. 

I'm going to merge the issues into this ticket.

**Comment by vangheem** [comment]
See https://github.com/plone/plone.app.contentmenu/pull/11
and
https://github.com/plone/plonetheme.barceloneta/commit/d3a32c48d9a39c98f30c6ee345846f13b47e97b6
