### ISSUE TITLE
Poor contrast of portlet management

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#730]
The readability of the portlets management is hard...at least the used font should be bolder...nice design but hard to read at all.
![1437314808785screensave](https://cloud.githubusercontent.com/assets/594239/8766249/42621920-2e30-11e5-86d3-98ed8818730f.png)

**Comment by vangheem** [comment]
Duplicate of https://github.com/plone/Products.CMFPlone/issues/728
