### ISSUE TITLE
Visual artifacts while rendering the toolbar (xx days ago vs. ISO datetime string)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#732]
The toolbar displays the "xx days ago" information during the loading of a page as ISO date time string and then turns it into "xx days ago" after the complete loading of the HTML. This is an visual artifact and confuses the eye especially when the page is loaded over a slow line or takes some time for rendering. The toolbar should only display "xx days ago" and not the ISO string at all. Perhaps the toolbar or this particular toolbar items should be hidden by default and made visible after moment.js(?) made its work here.

**Comment by vangheem** [comment]
+1 to hiding and then showing after the javascript loads it.

**Comment by ichim-david** [comment]
@vangheem  I was looking at the moment pattern and I can't see any events being triggered:
https://github.com/plone/mockup/blob/af3a58aacf55f29af21888cff79a3a88477526e0/mockup/patterns/moment/pattern.js

I wanted to fix this issue but there is no indication to me when the change is applied.

I have the following in mind as a potential fix:
1. hide .pat-moment within some css ex: .pat-moment { display: none;}
2. after $el.html() is set add $el.class('pat-transformed') or a generic class like ("pat-loaded") that indicates it is done
3. .pat-moment.pat-transformed { display: block;}

I would prefer a generic eventing solution where each pattern would trigger a before and after pattern is completed and to have a class added on the element which could be easily styled but I think it would be too late for such a change now.

If you have a better or easier idea in mind I would be willing to take a crack at it and send a pull request either with my proposed solution or something else.

**Comment by vangheem** [comment]
I like the idea of having a class applied after a pattern is successfully applied

What do you think @jcbrand ?

@ichim-david We use patternslib: https://github.com/Patternslib/Patterns/blob/master/src/core/registry.js#L89

**Comment by ichim-david** [comment]
@jcbrand @vangheem Another idea would be to set it as a data attribute
data-pat-loaded, this way avoiding adding any classes
.pat-moment[data-pat-loaded='true']  { display: block; }
This could be added if a flag if provided either globally or per pattern although again it could be too complicated to do so at this stage.

Going for the class approach I was thinking of this coming from angular with ng-cloak functionality where the framework provides the functionality and not the pattern itself
https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by davisagli** [comment]
Looks like this was fixed in Plone 6
