### ISSUE TITLE
Folder contents lacks a display option to view all content pieces without pagination.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#735]
The "Show all" option of all older Plone versions is missing. There is no way to display all content items on one screen. Although this can be a dangerous option for large folders, people are used to display all items on one screen and then searching for something particular using the browser search functionality.
At least there should be an option to display the folder content in larger batches other than 50.

**Comment by vangheem** [comment]
I thought about adding a 100 paging option. Wasn't sure if that was excessive or not. I thought the query functionality would be enough to satisfy this use-case though.

**Comment by davilima6** [comment]
+1 for 100 batches, and I think we should provide results per page in a select box so to reduce visual clutter for a functionality that's not going to be used that often. And when you do use it there's no need to see all the options at the same time. It's not like you have to compare items, just increase or decrease them.

+1 also for a Show all link, if possible with a warning prompt in case folder has more than 1000 items.

**Comment by vangheem** [comment]
PR welcome.

**Comment by vangheem** [comment]
I disagree with being able to show all content. IMO, it is an abusable use-case that users should be advised to use filtering for instead.

**Comment by davilima6** [comment]
I see your point but maybe that could be handled with a warning if Plone detects more than a thousand items? I believe most Plone installations try to keep below that and a warning would avoid losing that functionality due to a minority of news items (or other populous but not numerous) containers.

**Comment by zopyx** [comment]
There are case when u want this functionality. Don't treat users like idiots dictating them how to work. 

Sent from a mobile device

**Comment by vangheem** [comment]
Users will abuse things if they can. It's a good idea to provide better patterns of use.

Just because something has been a certain way, does not mean it needs to be that way forever in a product. The "show all" functionality was necessary before because you didn't have search. Now that there is built-in filtering, there is no need for the potential pitfall behavior.

**Comment by hvelarde** [comment]
I agree with @zopyx: listing all contents  is useful and has to stay; there are use cases that filtering wont cover and the result would be having to filter many times.

+1 also on @davilima6; we can warn users if the result query is big.

**Comment by vangheem** [comment]
What is this use-case where filtering won't work?

**Comment by vangheem** [comment]
@hvelarde @davilima6 have you tried the new folder contents?

**Comment by hvelarde** [comment]
@vangheem it won't work when you want to see all items :-)

and yes, I've tried it in Plone 4 using [wildcard.foldercontents](https://pypi.python.org/pypi/wildcard.foldercontents).

**Comment by vangheem** [comment]
Not the same. Even the 2.x is much different at this point.

**Comment by davilima6** [comment]
I did try filtering in P5 and I understand it's very powerful and also ajax-based so there's no need to see all items to find something that isn't on current page.

However sometimes you're not actually searching for a specific content; instead you just want a full listing of items available, sometimes to take action on them, sometimes for audit or analysis only, even printing. Maybe you just want to be able to detect some pattern. In one word: control.

**Comment by 3dogMcNeill** [comment]
Relevant read: [Preventing User Errors: Avoiding Conscious Mistakes](http://www.nngroup.com/articles/user-mistakes/)

**Comment by tomgross** [comment]
@vangheem One Usecase is documented in #1265 As an editor I want to reoder all items of a folder.

**Comment by fgrcon** [comment]
@tomgross @vangheem  :+1:  for show all

**Comment by tomgross** [comment]
Any news on that?

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
