### ISSUE TITLE
TypeError: prepOverlay is not a function

### ISSUE THREAD

**Issue by gyst** [plone/Products.CMFPlone#738]
Reproduced on Products.CMFPlone 2b9e0c0f8a492cd26bf1d70b5f7e3341959504e1
- Create a new Plone site
- View welcome page

![prepoverlay](https://cloud.githubusercontent.com/assets/122351/8778621/3c949f7a-2eff-11e5-8fb0-c8e945def293.png)

**Comment by vangheem** [comment]
This should have been fixed in plone.app.discussion a long time ago.

Are you using coredev buildout? Are you using a customized build of plone-logged-in js? might you need to rebuild the js?

**Comment by gyst** [comment]
This was on a ploneintranet buildout that extends
http://dist.plone.org/release/5.0b2/versions.cfg

Pinning plone.app.discussion to 2.4.4. fixed the issue indeed, thanks a lot!
