### ISSUE TITLE
@@historyview publicly visible 

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#739]
This view is only protected by the "View" permission so if the object is visible then so is its history. The history itself doesn't seem visible but I don't see a reason the view itself shouldn't be protected too.

Also ./content_status_history (state>advanced) is also only protected by the ```View``` permission.

Helpful to try and work out what is a frontend and backend screen #465

**Comment by vangheem** [comment]
content_status_history seems to use content_status_modify which ends up checking permissions there. In the end, the user require modify portal content. I see no problem in adding that permission to the view.

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.content/pull/45

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.content/pull/45
