### ISSUE TITLE
Should be easy to create have a byline

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#741]
## User problem

Some sites show some combination of
- last updated date
- last published date
- creators name
- last editors name

The person in charge of deciding _what_ information is shown on the page (information architect/content team leader/site admin/themer) should be able to include this information in the page easily and flexibly being able to pick which of the above they want to show. Showing at least the publication date is a common feature of blog posts and news items in other CMS's
## History

The byline was a feature used both by internal editors and reused to show to the public (with reduced functionality, ie no history). Currently for 5.0 it is hidden by default because there is last updated date is shown in the toolbar and the history view provides the other info at a single click.

replaces https://github.com/plone/Products.CMFPlone/issues/668 and https://github.com/plone/Products.CMFPlone/issues/714
## Options
1. Have a tickbox to turn the byline on
   - Fix the current tickboxes in security and site which previously determine if the byline is visible to the public and if it should show last published date. This would turn it on for everyone or off for everyone.
     - should probably move somewhere more sensible like theming.
     - improve them to give more options about showing date without author #668
     - pro: backwards compatible setting. 
     - con: makes it harder for themers to cope with visual elements that can be turn on thus breaking the theme (but we already have that with things like TOC)
2. Have the viewlet hidden but easily enabled by switching on the viewlet ttw. Document how to use diazo to hide parts you don't want.
3. ~~Always have the byline turned on. Document how to use diazo to hide parts you don't want or all of it~~
4. ~~Document how to use diazo to create your own byline using parameter expression like `modified = context/modified` and a diazo rule like `<insert-after css:theme="#content h1"><p>Last modified {$modified}</p></insert-after>`~~
   ~~\- pro: teaches them more flexible approach. code is small and easy to copy
   ~~- con: means that have to modify an out of the box theme.~~
5. solve "way to include dynamic or rich content into the text of a page" #469, ie by mosaic or similar. byline would be a tile. or by htmlfragments (requires coding)
6. ~~have something like collective.listingviews built into plone which enables admins to add portlets with common metadata without coding which can then be styled using diazo.~~

**Comment by davilima6** [comment]
It seems you forgot to mention original thread's most voted suggestion: byline stays exactly as it is but hidden. When Mosaic comes out, byline gets available as a configurable tile and then we delete old settings. As a bonus we avoid changing twice the recommended way of having a byline in Plone.

I find it also important to reaffirm in this issue the research made by @hvelarde: even though Barceloneta aims for minimal, byline is nothing short of  [an expected native CMS feature](https://twitter.com/hvelarde/status/622045162542383104).

**Comment by keul** [comment]
Probably it's too late for Plone 5, but I think it's time to make the byline a little more configurable.

We really enjoy the works we did with [rt.lastmodifier](https://github.com/RedTurtle/rt.lastmodifier), where there's a specific permission for every piece of the byline (that's is *not* related to theme but is a security configuration). The global check "show/hide byline to anonymous" is not enough in lot of use cases.

**Comment by davilima6** [comment]
Nice! I hope it's not hard porting those features into the byline tile.

**Comment by hvelarde** [comment]
@djay I really appreciate the work you have done trying to resume the conversation we have the other day, but we need to agree on one basic concept before continue working on this issue: the byline is content, not presentation. so, is not the "themer" who decides if that content is there, but the publisher of the site.

it has to be easy to change the settings and it has to be done independently of the theme; I don't see the need of having Diazo involved on this.

what @keul showed here probably the way we need to go.

**Comment by hvelarde** [comment]
@vangheem why did you closed it? we haven't even starting talking about it :-)

**Comment by mauritsvanrees** [comment]
@hvelarde He closed it automatically by merging a pull request that actually fixes it. Seems legit. :-)

**Comment by hvelarde** [comment]
@mauritsvanrees no, it doesn't fix it; we're talking about different things here

**Comment by davilima6** [comment]
@hvelarde is right, only the #714 part of this issue has been closed by plone/plone.app.layout#59 - and even then not completely cause now we have bad redundancy with toolbar. If we are keeping history in the latter we must hide the viewlet by default. Also I should file a bug in which the viewlet doesn't respect the settings in @@site-controlpanel.

After that we still have to discuss how to implement the controls suggested in #668. I think those should go on Mosaic only (option 5) for the sake of avoiding both coredev rewrites and integrators pain in the near future.

**Comment by rodfersou** [comment]
This issue https://github.com/plone/Products.CMFPlone/issues/1037 closes the part to respect @@site-controlpanel

/cc @davilima6 @hvelarde

**Comment by hvelarde** [comment]
I removed the "_strange to have some aspects of theme determined by a tickbox and others_" line from the "**Have a tickbox to turn the byline on**" option; as we discussed before, metadata is content, not theme.

**Comment by fredvd** [comment]
Now with the latest released Plone 5.0.6 there's a Security setting in the control panel: 
"Allow anyone to view 'about' information" which doesn't do anything for the byline for anonymous vistors because by default the byline viewlet is hidden.

**Comment by hvelarde** [comment]
@fredvd I fixed that for Plone 5.1

**Comment by thet** [comment]
Closing this, because following the discussion and linked PR/issues it looks like this issue being fixed.
Reopen if not.

**Comment by hvelarde** [comment]
it's not, but I'll create a new one later explaining what's missing; then we can close this one.

**Comment by hvelarde** [comment]
superseded by #1908.
