### ISSUE TITLE
allow themer to allow editors to pick a portlet style/class

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#742]
# User problem

It's very useful to have different styles of portlets and to let the user to choose which of those styles they want. Currently a theme can be delivered in plone 5.0 with custom tinymce styles which the editor can pick. It would equally be useful if a theme can be delivered with portlet styles which can be picked and the themer can use diazo to turn that into whatever they need.
# History

Several existing plugins already attempt to do this but all have to hack plone
- 5.0 PLIP https://dev.plone.org/ticket/12266
- https://plone.org/products/rer.portlet.advanced_static
- https://github.com/hexagonit/hexagonit.portletstyle
-  https://github.com/collective/collective.portletmetadata
- https://github.com/shuttlethread/collective.portletclass
# Options

Introduce assigning a portlet style in the portlet manager. No portlet implementation should have to change, only portlet managers.
1. Store the style in a special stylesheet mentioned in the manifest similar to tinymce styles (see #492)
2. Store styles definitations in the registry
   - con: themers will have to install them when they install their theme.
# Risks
1. Wasted effort (low)
   - portlets may be replaced by mosaic
   - but this change doesn't remove anything so its not really hurting
2. Provide less motivation to upgrade to mosaic

**Comment by davilima6** [comment]
+1. This should be easy to implement and the outcomes are huge.

**Comment by hvelarde** [comment]
-1 on this; portlets are about to die in future Plone versions; including in the core a feature that is already available via third party add-ons is not a good idea in this case, IMO.

**Comment by davilima6** [comment]
"About to die" is a bit over optimistic, don't you think? Please separate disliking portlets from honest observation of Plone's development pace: it took 5 years to go from 4.0 to 5.0 and I wouldn't bet on 6.0 being out in less than a couple years. (would you?) Even then portlets won't be completely off since there'll be thousands of sites that don't need or can't afford major version upgrades and will take good advantage if those classes are manageable by editors and siteadmins.

Point being: just because portlets suck we shouldn't turn our backs to them. IINM This is a very low hanging fruit, so if you do see any objective risks (e.g. hard time on migrations) please add to the debate.

**Comment by hvelarde** [comment]
@davilima6 this is not about personal choices or development pace, but medium and long term vision: I have nothing against portlets; the main issue is that, if we really want to get rid of them, we must stop adding portlet managers (like the new in the footer) and portlet features (like the one proposed here).

again, there are already add-ons to do what is proposed here; adding this feature to the core is a waste of time and effort, IMO.

**Comment by djay** [comment]
@hvelarde waste of whos time? no one asked you to implement it. Perhaps you could rephrase your complain as a risk?
In terms of plugins, they have to use monkey patches to achieve what they need. Any plugin that uses monkey patches is normally very hard to maintain and a good reason move at least part of the functionality into the core if its very useful.

**Comment by hvelarde** [comment]
@djay I'm not complaining, just giving my opinion: whatever delays the removal of portlets in Plone 5 is a bad decision in the long run.

**Comment by djay** [comment]
@hvelarde I think the only thing delaying mosaic is not enough people using
it and discovering some of the missing functionalities and risks associated
with it. Esp those familiar with cover. It just doesn't feel like its been
used in production enough.

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
