### ISSUE TITLE
Toolbar when visiting "@@personal-preferences" view

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#746]
In latest master Plone 0.5b4.dev0, logged in as "admin" and going to http://localhost:8080/Plone/@@personal-preferences I see the toolbar as in this image:

![schermata 2015-07-22 a 15 22 03](https://cloud.githubusercontent.com/assets/284924/8826259/7080cdf4-3085-11e5-9bb4-37f9d3f84390.png)

I'm not sure of many of the items I see there in that view (probably toolbar should be empty there), however the strange ones is the link to @@historyview, that call the view on the site root, with make no sense to me.

**Comment by vangheem** [comment]
@djay this is already getting confusing for users. Are we sure we want full toolbar to show on most pages?

\cc @plone/ux-team

**Comment by davilima6** [comment]
I think toolbar has to be minimal in all management and [accessory pages](https://github.com/plone/Products.CMFPlone/issues/685#issue-95244614).

**Comment by agitator** [comment]
I would say toolbar actions visible where it's useful -> context of content.
Not very useful for settings pages

**Comment by vangheem** [comment]
So back to original behavior. You'll have a mostly empty toolbar on all settings pages because you still need logout action.

Perhaps we have the "Contents" button everywhere though?

**Comment by davilima6** [comment]
Yeah. And please also full toolbar on folder contents.

**Comment by pbauer** [comment]
The toolbar is empty when ``disable_border`` is set in the request, e.g.:
```xml
<metal:block fill-slot="top_slot"
             tal:define="dummy python:request.set('disable_border',1)" />
```

**Comment by djay** [comment]
What about the view when initially logged in or contact form? Only contents
too?

**Comment by agitator** [comment]
login and contact form are within a modal windows, so not a real issue there

**Comment by vangheem** [comment]
@djay is more concerned with the initial view after you're logged in.

**Comment by vangheem** [comment]
http://jenkins.plone.org/job/pull-request-5.0/148/

**Comment by davilima6** [comment]
I believe it's a nice convenience to display Folder Contents icon in logged-in view and for the same reasons probably "Add new" as well. Everything else doesn't make sense and shouldn't be available: Content Info (byline) and all other content menu (layout, workflow, more options) and content view icons (view, edit, sharing).

BTW Content info icon should be removed from all views that don't relate to content such as sitemap and contact-info. Currently users are served with metadata from next parent in traversal.

Re: original issue, Sharing should be omitted from @@personal-preferences.
