### ISSUE TITLE
@@resourceregistry-controlpanel editing bundle causes error

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#748]
Within the resource registry control panel:

- I enabled dev mode
- clicked on "develop CSS" for plone-legacy
- edit list of CSS item from the legacy bundle
- clicked on "Save"

....spinning wheel and spinning...nothing is happening.

Plone 5.0b4.dev0 (5006)
CMF 2.2.8
Zope 2.13.22
Python 2.7.8 (default, Oct 13 2014, 12:40:26) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
PIL 2.7.0 (Pillow)

**Comment by pbauer** [comment]
Try it in Chrome. If it does not work there there might be a "real" problem.

**Comment by zopyx** [comment]
Always working with Chrome...

2015-07-23 12:03 GMT+02:00 Philip Bauer <notifications@github.com>:

**Comment by pbauer** [comment]
Does that mean it always works in Chrome or that you always work with Chrome?

**Comment by thet** [comment]
i remember i had a simmilar issue with firefox, where the build step wasn't working. it was a browser incompatibility, @vangheem  fixed it: https://github.com/plone/Products.CMFPlone/issues/351

@zopyx which version of chrome are you using?

**Comment by vangheem** [comment]
This is a bug and is unrelated to other tickets or the browser. I have reproduced.

I modified the ticket slightly to make it more clear how @zopyx is doing it.

**Comment by vangheem** [comment]
![screen shot 2015-07-23 at 8 37 37 am](https://cloud.githubusercontent.com/assets/524413/8851597/1f3a7c7e-3116-11e5-8d06-a1ad743afe8c.png)

**Comment by zopyx** [comment]
Using Chrome 43/44.

2015-07-23 15:38 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

**Comment by zopyx** [comment]
The error still exists in Plone 5.0b4.

**Comment by vangheem** [comment]
Sorry, this was fixed in the js code but a new bundle was never generated and pushed.
