### ISSUE TITLE
Font to thin in control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#752]
See screenshot (Firefox latest, Linux)
![plone site 2015-07-24 12-01-49](https://cloud.githubusercontent.com/assets/594239/8872280/d7c53e60-31fb-11e5-89ed-8275e842ad1d.png)

**Comment by pigeonflight** [comment]
For the sake of a newbie that might be working on this bug, the screen above can be navigated to from:
Admin > Site Setup > Advanced: Resource Registries (the url /@@resourceregistry-controlpanel)

The bug relates to the barceloneta css, specifically styles for .portlet .portletHeader

It can be observed on any portlet see screenshot below:
![image](https://cloud.githubusercontent.com/assets/31827/8893652/1558d6ce-335f-11e5-93bd-057977fb414d.png)

The current font weight is 100 (which, based on my experience, on a windows machine will look horrendous).
 I would recommend a font weight of 400.

**Comment by pigeonflight** [comment]
Tracked this down to the plonetheme.barceloneta
https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/portlets.plone.less#L12

It currently uses the less variable:  @plone-font-weight-light
the variables.plone.less file https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/variables.plone.less#L61
It should use @plone-font-weight-regular instead (with a font weight of 300)

**Comment by pigeonflight** [comment]
To fix this bug you'll need to configure grunt etc... see: https://github.com/plone/plonetheme.barceloneta/blob/master/HOWTO_DEVELOP.txt

**Comment by pigeonflight** [comment]
I think it looks much better bold so I've changed the variable used to @plone-font-weight-bold: 
![screenshot 2015-07-26 at 7 33 09 am](https://cloud.githubusercontent.com/assets/31827/8893898/a21f085e-3368-11e5-8d6f-098e229d3931.png)

And here it is in a normal portlet
![screenshot 2015-07-26 at 7 34 03 am](https://cloud.githubusercontent.com/assets/31827/8893906/bdc0cf34-3368-11e5-8b7b-09b283fc3b7c.png)

**Comment by pigeonflight** [comment]
The fixed has been pushed and commited

**Comment by agitator** [comment]
nice, thanx!
