### ISSUE TITLE
Visual issues in portal_registry

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#753]
- the second SELECT element moves to the second line when the iface name becomes too long..behaves weird...perhaps leave the second SELECT always on the next line
- some description texts contain html entities (structure: forgotten?)
-  table overflow into the portlet slot

![screenshot 2015-07-24 12 18 37](https://cloud.githubusercontent.com/assets/594239/8872534/337ee90c-31fe-11e5-8a80-1d649a96cf70.png)
![screenshot 2015-07-24 12 17 55](https://cloud.githubusercontent.com/assets/594239/8872535/339a11c8-31fe-11e5-9177-0f827f249b4b.png)
![screenshot 2015-07-24 12 17 41](https://cloud.githubusercontent.com/assets/594239/8872536/33a84d38-31fe-11e5-84c5-069e5d0a737d.png)

**Comment by pigeonflight** [comment]
I can confirm that adding structure to the description field fixes the html entities issue.
![screenshot 2015-07-26 at 12 27 14 pm](https://cloud.githubusercontent.com/assets/31827/8895044/ae339e9c-3391-11e5-8d19-c786cca214dd.png)

**Comment by vangheem** [comment]
The html entities and search field issues are fixed. Someone with better CSS skill needs to help fix the right portlet overflow issue.

**Comment by ichim-david** [comment]
With the latest change I can't get the portlet overflow issue anymore. Tried with recent version of Chrome and Firefox so do tell if possible what browser and version still has the portlet overflow.

**Comment by sneridagh** [comment]
I've just tried it and it seems fine. However, I've fixed some minor alignment issues with buttons.
Anyone still having issues? If not, we can just close this.

**Comment by pigeonflight** [comment]
Can this bug be closed?
