### ISSUE TITLE
ConstraintNotSatisfied: en_US

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#754]
Somehow I could get a plain Plone 5 site into a weird state where 'edit' for none of the
default content objects did not work anymore.

We’re sorry, but there seems to be an error…

Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 66, in \__call__
Module plone.z3cform.layout, line 50, in update
Module plone.dexterity.browser.edit, line 65, in update
Module plone.z3cform.fieldsets.extensible, line 59, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 141, in update
Module z3c.form.group, line 52, in update
Module z3c.form.group, line 48, in updateWidgets
Module z3c.form.field, line 277, in update
Module z3c.form.browser.select, line 51, in update
Module z3c.form.browser.widget, line 171, in update
Module z3c.form.widget, line 221, in update
Module z3c.form.widget, line 114, in update
Module zope.schema._bootstrapfields, line 78, in __get__
Module zope.schema._bootstrapfields, line 182, in validate
Module zope.schema._field, line 389, in _validate
ConstraintNotSatisfied: en_US

**Comment by tkimnguyen** [comment]
I got this same error stack trying to add a new Event in the /events folder.

**Comment by enzus** [comment]
I got the same error trying to add a news item on: http://dev.brianledwell.com:8081/Plone/news/++add++News%20Item

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 127, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module z3c.form.browser.select, line 51, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 221, in update
  Module z3c.form.widget, line 114, in update
  Module zope.schema._bootstrapfields, line 78, in __get__
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 389, in _validate
ConstraintNotSatisfied: en_US

**Comment by agitator** [comment]
same here...
ConstraintNotSatisfied: de_CH

only happens within example content folders

**Comment by vangheem** [comment]
PR to fix this: https://github.com/plone/plone.app.contenttypes/pull/264
