### ISSUE TITLE
No default table styles when using TinyMCE

### ISSUE THREAD

**Issue by danielhz** [plone/Products.CMFPlone#755]
I added a table in a document using the TinyMCE in a site build with Plone 5.0b3. However, the UI have no default style alternatives via CSS classes as in Plone 4. Thus, after creating the table it is difficult to put data inside the cells, because no borders are visible and no padding is added. Furthermore, if I want to add style, the UI only allows me to edit specific properties or attach the CSS attributes directly in the table. Thus, currently I cannot have and define reusable table classes.

**Comment by vangheem** [comment]
Thanks for the report. I have provided basic styles in this PR: https://github.com/plone/plonetheme.barceloneta/pull/31

It'd be great if you could test it out and give your feedback.

**Comment by danielhz** [comment]
Great! I will test it.

**Comment by danielhz** [comment]
I added the line below to my buildout.cfg. However, I do not see where can I select the classes that are available for tables.

    [sources]
    plonetheme.barceloneta = git https://github.com/plone/plonetheme.barceloneta.git

**Comment by ichim-david** [comment]
@danielhz https://github.com/plone/plonetheme.barceloneta/commit/0cc656e543cbdaa1841a4adf0d7ed5595e3bcceb  if you look at the css this styles table tag directly.
There are no classes to be added for the tables. 

You should just normally add a table and check out the css with a developer inspector such as from Chrome or Firefox.

**Comment by ichim-david** [comment]
@danielhz  furthermore you should use the correct branch to check out the changes which is:
[sources]
plonetheme.barceloneta = git https://github.com/plone/plonetheme.barceloneta.git branch=table-styles

branch=table-styles is important otherwise you are checking only what is done on master or after it was checked out you can do from the terminal:
<pre>git checkout table-styles</pre>
and then see if you get the table styles

**Comment by danielhz** [comment]
That I see is that now the default table style have a dotted border in cells as default so I can see where the cells are. This is much better :-). However, in Plone 4.3.6 I see options as "subdued grid", "fancy listing" or "invisible grid" when creating or editing tables. Maybe I'm wrong, but I have not seen this feature in Plone 5 beta. Furthermore, I think that this second feature may be not related to an specific theme but to the component that manage TinyMCE.

**Comment by vangheem** [comment]
See https://github.com/plone/Products.CMFPlone/pull/1082 for table styles implementation

**Comment by danielhz** [comment]
Thanks! I am not sure if it is enough adding the following in `buildout.cfg` to test it:

    [sources]
    products.CMFPlone = git https://github.com/plone/Products.CMFPlone.git

Otherwise, I will wait for the release of 5.0rc4.
