### ISSUE TITLE
Migrate plone_ecmascript to resources

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#76]
https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/skins/plone_ecmascript

Look around to make sure these aren't being implicitly called anywhere. Some of these might actually be able to be deprecated long term but a straight translation will work for now.

**Comment by gforcada** [comment]
There's just one left... anyone feeling like a hero? :)

**Comment by davisagli** [comment]
and there's another ticket for that (#284) so I'm going to close this one
