### ISSUE TITLE
re-add default events portlet to right column 

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#760]
I looked through the issue tracker here but could not find any related discussion. Is there a reason why the events portlet is no longer included in a Plone site's right column out of the box?

**Comment by jensens** [comment]
iirc there was a problem when upgrading from old style events (ATCT) to p.a.event. Maybe @thet knows more?

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.event/commit/eca821558fbb29a7bc3a4141c874c3a142b4bc27
The styles still needs some love (see https://github.com/plone/Products.CMFPlone/issues/775)

**Comment by thet** [comment]
Can't remember, must have been 5 years ago. Maybe it was something like, that I don't want to get them re-assigned every time I import the plone.app.event profile?

**Comment by pbauer** [comment]
That should no longer be an issue in the future with https://github.com/zopefoundation/Products.GenericSetup/pull/16

**Comment by tkimnguyen** [comment]
thx @pbauer - no trout slap for you today :)
