### ISSUE TITLE
adding or editing an events portlet: no workflow state seems chosen but one is ("Published")

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#761]
An events portlet correctly shows published events, even though no state is chosen in the  Workflow State widget

![screen shot 2015-07-29 at jul 29 12 39 16 am](https://cloud.githubusercontent.com/assets/815418/8950673/463d0bde-358a-11e5-8af4-ebbbad35a893.jpg)

**Comment by pbauer** [comment]
I don't consider that a bug. If no state is selected it means that events should not be filtered by state at all. That is much simpler than selecting all states.

**Comment by davilima6** [comment]
@pbauer I agree with you: this field should really be optional - just like the `Search base` below it. However I'd suggest changing the form help to sth like:

"Filter items to show by workflow state. If empty, all items with states visible by user will be listed."
