### ISSUE TITLE
TinyMCE Insert Image dialog on mobile device needs tweaking

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#762]
The following is on an iPhone 6 Plus:
- [ ] When you click the Insert Image toolbar icon, the dialog at first doesn't show up; it appears to be a black screen until you scroll to the top of the screen.
- [x] In "Drag and drop files from your desktop" could we change "desktop" to "device" or "computer"?
- [ ] The "Drop files here" area and the "Browse" and "Upload" buttons are cropped
- [x] Change "Just drag N drop" -> "Drag and drop"
- [x] "browse" should be capitalized in 'press the "browse" button'
- [ ] The error "You are not authorized to add content to this folder" is cropped and isn't very obvious visually. It's also not clear what I can do about it (do I cancel out and give up editing this item?).
- [ ] It's not clear what to do after you Browsed and selected an image... I figured out I had to scroll down to click the "Upload" button
- [ ] Once I'm done uploading the image, there should be a hint that I have to click the Insert button at the very bottom
- [ ] The Insert button isn't clickable in portrait orientation (the Cancel button is, however). Both buttons work in landscape orientation. 

@plone/ux-team

![img_9571](https://cloud.githubusercontent.com/assets/815418/8951292/e564cd80-3591-11e5-88f2-c30b07d59823.PNG)

**Comment by enzus** [comment]
Hi, I believe the same issue applies to many if not all the modals. So far, on my iPhone 5s, I've noticed that the login form and the upload form in the contents view are not responsive but I bet there are others in the same situation. Should we open a separate ticket for each modal or this one can do as generic placeholder?

![photo 29-07-2015 15 21 59](https://cloud.githubusercontent.com/assets/868825/8972395/006ad16a-365a-11e5-872c-7d6f9d6b6a07.png)

![photo 30-07-2015 01 24 20](https://cloud.githubusercontent.com/assets/868825/8972396/007305ba-365a-11e5-8ace-8d6d41dc4b23.png)

**Comment by tkimnguyen** [comment]
@enzus maybe we edit the original issue description with checkboxes for the dialogs we identify and check the boxes as we fix them?

**Comment by tkimnguyen** [comment]
@enzus on second thought, let's open another issue to fix modal dialogs because I'm finding other problems with this one (the Insert Image one).

**Comment by jensens** [comment]
just tried this in 5.2 and it looks fine afaict.
