### ISSUE TITLE
Styles for plone.app.discussion need some love

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#764]
Comments (plone.app.discussion) in Plone 5 don't look great yet 
![comments](https://cloud.githubusercontent.com/assets/453208/8957154/a4e186e8-35fc-11e5-88c6-a53fd5499c0a.png)

**Comment by pbauer** [comment]
There are two files for these styles: ``plone.app.discussion/plone/app/discussion/browser/stylesheets/discussion.css`` and ``plonetheme.barceloneta/plonetheme/barceloneta/theme/less/discussion.plone.less``. IMHO everything should move into ``discussion.plone.less`` and be cleaned up.

**Comment by tisto** [comment]
I agree that p.a.discussion styles should go into one file. Normally I
would prefer to keep the p.a.discussion code as separate as possible
from the core. Though, since the styles are more bound to barceloneta I
agree to use discussion.plone.less.

Am 07.09.2015 um 10:27 schrieb Philip Bauer:

**Comment by pbauer** [comment]
I tried my hand at that and failed miserably. Can a less-savy person please fix that?

**Comment by ichim-david** [comment]
This is what I have so far
![discussion-fixes](https://cloud.githubusercontent.com/assets/152852/9861911/16628ba8-5b3e-11e5-8c32-0b7206a5aede.png)
More fixes can be done tomorrow

**Comment by pbauer** [comment]
@ichim-david Much better than before! Please move all styles into ```plonetheme.barceloneta/plonetheme/barceloneta/theme/less/discussion.plone.less```. The links/buttons should also look the same. And I think the image should be round all the way.

**Comment by ichim-david** [comment]
@pbauer finally getting the time at 10pm to work on this, I will finish today.

@tisto  the reply button is never visible, I see that it expects to be set visible by javascript
and it never is.
Let me know if there is a ticket for this issue, if not we should add one.

**Comment by ichim-david** [comment]
@tisto @pbauer  @vangheem do we want links or buttons for the discussion actions?
![links](https://cloud.githubusercontent.com/assets/152852/9888148/10a4fc6e-5bfc-11e5-96b7-89b3c32e4378.png)
vs
![standardbuttons](https://cloud.githubusercontent.com/assets/152852/9888147/10a39f18-5bfc-11e5-8326-d6b526b45a11.png)

My opinion ... Github has buttons and icons :) for this issue form, although our buttons might be a tad heavy on the coloring and padding.

**Comment by ichim-david** [comment]
@tisto I've merged any styles that were useful (which were 4 rules ;) ) into plonetheme.barceloneta here
https://github.com/plone/plonetheme.barceloneta/commit/ddd67c6b679e6963efd418862c1da89d5430ef50

As such we could remove discussion.css for good from plone.app.discussion with an upgrade step.

@pbauer I went ahead and transformed the links into buttons as I find them easier to use especially in the context of a mobile users where the bigger touch area is a plus to have.

**Comment by davilima6** [comment]
+1 for buttons but also for making them lighter, more discreet.

My suggestion: multiple comments require too many identical buttons at once on screen so it's not unusual to have actions available on hover only. Besides I think that fits Barceloneta minimalism.

I see the risk of imposing this behavior on integrators so it should be easy to be turned off, either by a) customizing the discussion template and removing a single pattern-class, or b) toggling a switch in @@discussion-controlpanel. What do you think?

**Comment by tisto** [comment]
+1 for buttons and removing discussion.css with an upgrade step. Great work @ichim-david!

**Comment by pbauer** [comment]
:+1: for buttons. You can also have grey buttons to distinguish them more (probably best for edit). I'd either keep the default size or make them much smaller to keep some theme consistency. 
Lovely! I can help with the upgrade step if that is not your thing.

**Comment by pbauer** [comment]
done with https://github.com/plone/plonetheme.barceloneta/commit/ddd67c6b679e6963efd418862c1da89d5430ef50, https://github.com/plone/plone.app.upgrade/commit/fc8126e019c62ec64d663a41f6cdc43bc3c4fd9c and https://github.com/plone/plone.app.discussion/commit/35e6ab2677e89aaf87405f8c290b25930c8741bd
