### ISSUE TITLE
Drag & drop accidentally activated when scrolling up/down on the contents view on touch devices 

### ISSUE THREAD

**Issue by enzus** [plone/Products.CMFPlone#766]
On contents view I've noticed that the sorting of items through drag & drop can be inadvertently activated while simply scrolling up and down the page on touch devices (experienced myself on iPhone 5s).

This could lead to a continuous and more or less unconscious change of order of the listed content elements.
Ideally the drag & drop sorting should happen only after the user voluntarily switched on some sort of 'edit' mode. This switch should possibly be visible on touch devices only.

Enzo
@plone/ux-team 

![photo 29-07-2015 11 20 26](https://cloud.githubusercontent.com/assets/868825/8978359/c9dff7ea-36a1-11e5-85a8-dfc804104a8c.png)

**Comment by djay** [comment]
Maybe a 1s hold before drag mode is activated?

**Comment by davilima6** [comment]
+1 for 1st hold then drag on touch devices only

**Comment by enzus** [comment]
+1 too for 1s hold before drag works on touch devices. wonder if 1s is long enough or 1.5s would be better?

**Comment by enzus** [comment]
The only issue I can see is with the menu with various options (open, open in new tab, add to reading list, copy) that appear when you hold a link in general (Safari on iOS but probably also Chrome). We need to define what triggers the drag & drop and what the contextual menu or can they coexist?

**Comment by vangheem** [comment]
I'd recommend just disabling drag drop reordering for mobile.

I don't think there is any easy way with the library we're using for drag and drop to delay.

**Comment by vangheem** [comment]
Maybe have up/down buttons in the item cog menu for mobile.

**Comment by vangheem** [comment]
I mean, drag isn't even supposed to work on mobile right? Because drag always means scroll really.

**Comment by enzus** [comment]
+1 then on disabling drag & drop on touch devices (tablets included) and having instead up/down buttons

**Comment by davilima6** [comment]
Also +1 on replacing drag & drop with up/down arrows on touch however in the same place as in all previous Plone versions, to the left of each item checkbox. I don need to change it.

**Comment by hvelarde** [comment]
the handler is also a nice solution but it should work; right now is kind of broken, IIRC.

**Comment by davilima6** [comment]
It's not broken, is it? It had a small bug persisting some positions but I believe those have been solved for a while now.

**Comment by jensens** [comment]
I tried this in 6.0 - scrolling works at the left/right border while in the middle it reorders. I think this is fine.
