### ISSUE TITLE
event portlet formatting needs more padding

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#775]
The date, time, and location info in the event portlet need more padding

![screen shot 2015-07-31 at 1 48 31 pm](https://cloud.githubusercontent.com/assets/815418/9014909/f4d207ce-378a-11e5-84ee-0233dedd7b18.png)

**Comment by sneridagh** [comment]
Fixed!

**Comment by tkimnguyen** [comment]
Beautiful! thx @sneridagh
