### ISSUE TITLE
Disable HTML Filtering Will Crash portal_transforms in ZMI

### ISSUE THREAD

**Issue by l34marr** [plone/Products.CMFPlone#778]
Tested with buildout.coredev 5.0 branch from github (Products.CMFPlone 5.0b4.dev0)

Please see http://www.youtube.com/watch?v=G0mF3m92ACI for reference.

Maybe this is a side effect of #211 , which is not critical, but hopefully brings us better usability.

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/Products.PortalTransforms/commit/810f6fd37354bd82d114d07ea49252efde9e5edc
