### ISSUE TITLE
No autofocus on first form field

### ISSUE THREAD

**Issue by timitos** [plone/Products.CMFPlone#779]
On Login Form, Add Form, Search Forms, ... the first input field should get autofocus.

**Comment by timitos** [comment]
First plone/mockup#564 must be fixed

**Comment by timitos** [comment]
#1193 will make autofocus work again on those templates where it has been defined

**Comment by timitos** [comment]
#1205 New pull request because of problem with branch name and CI

**Comment by tomgross** [comment]
Any activity on this? It is still an issue for me on Plone 5.0.4.

**Comment by tomgross** [comment]
All the relevant PR requests have been mergen but this still does not work for a new Document in Plone 5.0.6.

**Comment by davisagli** [comment]
This is working in general in Plone 6. It is still not working on the login form but there is a separate issue for that.
