### ISSUE TITLE
Unable to uninstall products after upgrading to 5.0b3

### ISSUE THREAD

**Issue by ericof** [plone/Products.CMFPlone#780]
Steps to reproduce the problem:
* Create a Plone site with Plone 5.0b2
* Install an add on (i.e.: Open ID support)
* Upgrade to Plone 5.0b3
* Go to Control Panel / Add Ons
* Try to uninstall the same add on (i.e. Open ID Support)

Error message in the control panel:
<img width="1058" alt="add-on-control-panel-error" src="https://cloud.githubusercontent.com/assets/306014/9037258/d0b6616c-39e9-11e5-8588-09d2587adaba.png">

Error message in the terminal:
<img width="906" alt="terminal" src="https://cloud.githubusercontent.com/assets/306014/9037259/d0b99efe-39e9-11e5-936e-21d2f5ce6037.png">

**Comment by ericof** [comment]
Also, when compared to a newly created site (on Plone 5.0b3), the Control Panel categories does not look the same -- it seems some itens where not properly moved to their new categories

**Comment by hvelarde** [comment]
seems to be related with #443

**Comment by ericof** [comment]
It doesn't seem to be the case. The bug is related to the itens in control panel registration, not on the code of the add on itself.

**Comment by ericof** [comment]
Another info, if you create a new site in Plone 5.0b3, the install/uninstall works like charm

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.upgrade/commit/8de45a82dcfb42f4dab472aed9510ea68caa67ec (see also #814)
