### ISSUE TITLE
restore undo_form in Plone 5

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#783]
The /undo_form has been one of the amazing features of Plone for users and site managers. Users can see and usually undo their own changes, and site managers can undo a lot of inadvertent changes by anyone on the site. 

Undo has saved my bacon and that of many power content editors and site owners. I understand that a new browser view needs to be written for undo_form. It would also be nice to include instructions on the form to explain what might be undoable and what might not, and allow site owners to make this feature visible to end users or editors.

I'd be happy to give it a shot... if you care to risk the consequences ;)

**Comment by hvelarde** [comment]
big +1 on this

**Comment by jcerjak** [comment]
Related discussion: #102

Undo has actually worked quite well for me a lot of times, though in more complex cases it did break... Can we make it more solid?

**Comment by agitator** [comment]
+1

The only problem I came across was when user tried to pick one undo step.
Maybe some JS that selects all later steps when selecting one would help.

**Comment by djay** [comment]
There is a way to restore from history for content versioning objects.

The things making ZODB not easy to understand are:
- they currently don't tell you which objects are affected. Just what the url was that caused the change.
- you can't preview a restore
- you can't undo something that has changed the same object subsequently. So the only way you can undo is to undo both together. Again you can't preview so its not clear what the combined undo might result in.
- permissions. it bypasses all controls on who can alter what.
- it changes the history for content versioning.

I think to reenable it you would have to solve most of those.

**Comment by jensens** [comment]
Please to take into account
- undo may fail (several reasons)
- undo may be not available (example: RelStorage, history free)
- check if by default only available for Managers or Site Administrators (harmful feature)

Remark from FWT pov: This is a PLIP

**Comment by vangheem** [comment]
Also, you could potentially undo someone else's work.

**Comment by tkimnguyen** [comment]
I just want to restore the functionality that was there, despite its limitations. Despite its limitations, it was still very useful.

**Comment by jensens** [comment]
Afaik it was not in Plone 4.3, it was only available in ZMI (or hidden by default or so).

**Comment by davisagli** [comment]
> I just want to restore the functionality that was there, despite its limitations. Despite its limitations, it was still very useful.

Maybe it'd be better as an add-on?

**Comment by jensens** [comment]
I'am even not sure if it was available through Plone UI in the 3.x series. 
Anyway: PLIP it and we can discuss it on a broader base.
To keep core clean I also like the idea of an addon.

**Comment by tkimnguyen** [comment]
OK, PLIP it is... FYI it was in Plone 3 but the portal_action was left not visible.

**Comment by 3dogMcNeill** [comment]
+1

**Comment by davilima6** [comment]
+1 on restoring at least URL access to Undo. Don't forget it's an unique __killer__ feature that all other CMS lack and that most power users find unbelievably useful.

+1 on adding permission fixes and a JS to check all previous steps (which I always do with jquerify), but that could easily go on Plone 5.1. And if previews, versioning or RelStorage detecting are too hard, just keep Undo "hidden" in ZMI.

**Comment by hvelarde** [comment]
@jensens this is another feature that was removed by someone probably by mistake; we don't want to keep the core clean of useful features, aren't we?

**Comment by djay** [comment]
Read the original issue and the discussion hector. It was removed for some
very specific user issues and it was removed a long time ago in 4.

**Comment by hvelarde** [comment]
@djay thanks for pointing that! now it's clear to me that it was not removed by mistake: it's just another example of a feature removed without broader discussion, just because one of the core developers though it was useless.

**Comment by tkimnguyen** [comment]
I'm going to close this issue now and will instead create a PLIP for it. Please, let's keep in mind that core devs are doing their best to get P5 out the door. We can and will continue to improve on P5 following its release!
