### ISSUE TITLE
clarify that TinyMCE Insert Image dialog lets you upload just one image

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#784]
- [x] instructions could clarify a bit where the dialog is (the drop target)
- [ ] possible to use a UI hint to prevent multiple image drops? 
- [ ] and/or mention this in the instructions

**Comment by tkimnguyen** [comment]
@vangheem discussed changing the Insert Image behaviour so that after uploading the first (ie. only) image, the user is immediately switched back to the Image tab and the uploaded image is already selected (ready for user to click the Insert button).

**Comment by vangheem** [comment]
https://github.com/plone/mockup/pull/547 should finish this off.
