### ISSUE TITLE
Better quality Plone logo for portal-logo

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#786]
Is blurry and has noise around the edges—just needs to be replaced with a higher quality image.

**Comment by jensens** [comment]
SVG?

**Comment by 3dogMcNeill** [comment]
is this one of the images from the official Plone logo pack? There aren't any in the pack with the same dimensions—it looks like either a copy of a copy or a resized file. https://plone.org/foundation/logo

**Comment by jensens** [comment]
#767 states, svg are not supported.
