### ISSUE TITLE
Action button styling for "Insert Image" box

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#788]
When uploading an external image, both the "Browse" and "Upload" buttons turn blue on hover, but "Insert" doesn't and should. 

![insertbutton jpg](https://cloud.githubusercontent.com/assets/7101218/9046940/57ef0b7c-39fc-11e5-8f19-93dee7661f42.png)

**Comment by vangheem** [comment]
closed with https://github.com/plone/mockup/commit/6f1019def174c5cbeef79d7e19fafd6f68f1ecf2
