### ISSUE TITLE
Request to reorder actions on folder contents view 

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#791]
As both content contributor and site admin, would really like to see "open" and "edit" (used most) moved to top of the list and "cut" and "copy" (used the least and I prefer people to not really use) moved to the bottom. (this is on the former wildcard.foldercontents view)

![screen shot 2015-08-04 at 2 07 45 pm](https://cloud.githubusercontent.com/assets/7101218/9068711/0bab2e64-3ab3-11e5-864e-a084f7fe8bd3.png)

**Comment by agitator** [comment]
+1

**Comment by jensens** [comment]
can be closed, open and edit was now moved out to own icons.
