### ISSUE TITLE
Adding extra TinyMCE styles from a Plone add-on

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#793]
If we want to add new styles in our TinyMCE config, we have to declare them in our profile's `registry.xml` and provide the path to the related CSS in our theme's `manifest.xml`. That's fine when we create a Plone theme.

But how to do that if we are just creating an add-on?
We can still declare our styles in `registry.xml`, but there is no way to give the path to our CSS as we do not have a Diazo theme into our module.

**Comment by vangheem** [comment]
Do you mean CSS used in the editor or the styles drop down?

**Comment by vangheem** [comment]
Can you look at the tinymce configuration panel? @@tinymce-controlpanel

A lot is configurable with the registry and does not require a theme. More is configurable with registry than there is with the theme.

**Comment by ebrehault** [comment]
I need both:
- I want to user to be able to choose one of my add-on specific styles in the TinyMCE menu (this does work by declaring the needed stuff in `registry.xml`)
- I also want the choosen style to render specifically in the editor, and that's what I cannot do.

I have noticed the "Choose the CSS used in WYSIWYG Editor Area" parameter in @@tinymce-controlpanel, but apparently it is not loaded by the editor at the moment, and anyway, I would probably need it to be a list, not single value, as I do not want my add-on to replace the existing CSS.

**Comment by vangheem** [comment]
Right, as with current tinymce on plone 4, it seems like the single content css value line carried over. It's a comma separated value.

**Comment by vangheem** [comment]
The content css value to be a list so it can easily be configured with registry.xml. Then the pattern config can just convert that into a comma-separated value for tinymce.

**Comment by ebrehault** [comment]
OK, so I guess we just need to parse the registry value here and append the resulting URLs to the existing list here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patterns/__init__.py#L32

Right?

**Comment by vangheem** [comment]
It's already doing that.

I think we should change https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L400 to be a list.

**Comment by ebrehault** [comment]
Yes we need to change the schema, but I do not see any mention of the `content_css` attributes in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patterns/__init__.py#L32 at moment.
And if you inspect your TinyMCE iframe at the moment, you won't find `++plone++static/components/tinymce-builded/js/tinymce/skins/lightgray/content.min.css`  which is the `content_css` default value, so I think the `get_content_css` is wrong.

**Comment by vangheem** [comment]
ah hah! I was reading: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patterns/__init__.py#L38 wrong. Yes, you are correct. I apologize.

**Comment by ebrehault** [comment]
no problem
I am on it.

**Comment by ebrehault** [comment]
Fixed by https://github.com/plone/Products.CMFPlone/pull/794
