### ISSUE TITLE
FolderContents- Configure Display - Shows extra "Title"

### ISSUE THREAD

**Issue by bledwell** [plone/Products.CMFPlone#795]
When in folder contents and trying to show or hide columns you have an option "Title" it adds another column with "Title". Should this be duplicated since "Title" is already shown and cannot be removed?
![igaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/4641090/9077375/f185ade4-3af2-11e5-8db6-136d38ea9647.png)

**Comment by vangheem** [comment]
fixed here: https://github.com/plone/mockup/commit/6f1019def174c5cbeef79d7e19fafd6f68f1ecf2
