### ISSUE TITLE
Body padding issue with toolbar when screen is resized

### ISSUE THREAD

**Issue by chrismilway** [plone/Products.CMFPlone#797]
For a logged-in user, when the screen is resized from below 768 to above the padding on the left hand edge of the body element is incorrectly applied if the toolbar is in it's narrow configuration. The padding is 120px rather than 60px.

![padding-issue-1](https://cloud.githubusercontent.com/assets/4137130/9081659/4e610708-3b56-11e5-988d-38e6da06acb1.png)

There is also some strange behaviour with the flyout menus, which after the same resize will render at the top of the window rtaher than next to their menu entry. This also causes a negative left-margin to render the body under the toolbar and off the left edge of the window.

![padding-issue-2](https://cloud.githubusercontent.com/assets/4137130/9081660/4e75768e-3b56-11e5-9853-51785a4e4c9a.png)

Tested in FF 39 and Chrome 44 on Mac.

**Comment by jensens** [comment]
No problem in Plone 5.1 latest any more
