### ISSUE TITLE
Move archetype views to Products.ATContentTypes

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#80]
https://github.com/plone/Products.ATContentTypes

This would be the following views and their metadata files: https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/skins/plone_content: 

 * document_view.pt
 * event_view.pt
 * file_view.pt (don't forget the weird redirect cases)
 * image_view.pt
 * image_view_fullscreen.pt
 * link_redirect_view.py (again, weird case so be careful)
 * link_view.pt
 * newsitem_view.pt

In addition, let's make sure that the plone.app.contenttypes version of these views is implemented first and then migrate:

 * folder_full_view.pt
 * folder_full_view_item.pt
 * folder_summary_view.pt
 * folder_tabular_view.pt 

I *think* that these migrate as well and that there is another plip which is basically redoing these listings but it needs to be confirmed:

 * folder_listing.pt

I think this also means that having ATContentTypes will require also having CMF plone unless these get migrated to views as they move over. I encourage they do but realize this is a lot of work, and maybe its just easier requiring CMF. Also for customization reasons - people in the past did a lot TTW with this. It's up to whomever closes this to be the arbitrator of how nice they want to be.

In addition, we need to migrate the edits and what not that go with them. This includes the following in https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/skins/plone_form_scripts:

 * document_edit.cpy
 * document_edit.cpy.metadata
 * event_edit.cpy	
 * event_edit.cpy.metadata
 * file_edit.cpy
 * file_edit.cpy.metadata
 * image_edit.cpy
 * image_edit.cpy.metadata	Plone 
 * link_edit.cpy
 * link_edit.cpy.metadata
 * newsitem_edit.cpy
 * newsitem_edit.cpy.metadata
 * validate_event_edit.vpy
 * validate_file_edit.vpy
 * validate_image_edit.vpy
 * validate_link_edit.vpy
 * validate_newsitem_edit.vpy

**Comment by pbauer** [comment]
This was fixed in https://github.com/plone/Products.ATContentTypes/commit/31a934b0
