### ISSUE TITLE
Tiny MCE Setting - Editor Plugins not on by default not toggling on

### ISSUE THREAD

**Issue by bledwell** [plone/Products.CMFPlone#806]
When I go to "Site Setup > TinyMCE Settings > Plugins and Toolbar (tab)", any of the options that are not on by default do not turn on when I select them. For example selecting the "Preview" checkbox should result in 

![screen shot 2015-08-05 at 7 56 54 pm](https://cloud.githubusercontent.com/assets/4641090/9101467/f42ea4be-3bac-11e5-8005-691dc57d0ab1.png)

But for me results in this

![screen shot 2015-08-05 at 8 03 13 pm](https://cloud.githubusercontent.com/assets/4641090/9101473/14494b96-3bad-11e5-974e-cfe3b6def621.png)

Can someone confirm that Im correct this isn't working?

**Comment by vangheem** [comment]
Did you also add a button for this? Activating the plugin does not place a toolbar button anywhere. It's another setting. Look at the menu and toolbar settings

![screen shot 2015-08-05 at 8 25 32 pm](https://cloud.githubusercontent.com/assets/524413/9101742/328695f2-3bb0-11e5-9aca-72cf858aee34.png)

**Comment by bledwell** [comment]
Your absolutely correct! I change this

    "view": {
        "items": "visualaid", 
        "title": "View"
    }

to this

    "view": {
        "items": "visualaid | preview", 
        "title": "View"
    }

And it worked as expected. Thanks! I assumed by checking the box it would activate it. Is there a reason why all those options aren't already there in that Menu box? Would'nt the expectation be that checking the box would turn the option on without having to add to the menu? When I uncheck the box now for "preview" that option goes away like a toggle.

**Comment by vangheem** [comment]
So maybe we provide best guess default placement of all the plugins so when they're activated they show up somewhere and people can customize the placement if they want?

As long as providing buttons for non-activated plugins doesn't cause any errors.

**Comment by bledwell** [comment]
I think it would make things easier. If the admin wants to move the placement they can. But out of the box it would be easier to have them all checkboxable (if that can be a word) :)

**Comment by bledwell** [comment]
For placement we could use what the default placement is here? Keep from having to think too much http://www.tinymce.com/

**Comment by jkubaile** [comment]
+1 for this, I also run in this issue...
