### ISSUE TITLE
Toggle for expanded/collapsed toolbar is not obvious

### ISSUE THREAD

**Issue by enzus** [plone/Products.CMFPlone#807]
I found out by chance that clicking on the Plone logo in the toolbar toggles between an expanded version (icon + label) and a collapsed view (icon + label on hover). I'm not sure we have icons clear enough to suffice alone, hence I'm not sure about the value of the collapsed version but we should at least try to make the toggle more obvious... unless we want to keep it as a sort of easter egg?

**Comment by davilima6** [comment]
I don't think we need an easter egg here (although Plone probably lacks some) but I do believe there's value in having both collapsed and expanded versions. So +1 for adding a discreet arrow that animates changing direction when clicked in order to hint on the sliding behavior.

Maybe we could move the current arrow-down below toolbar logo to the right (over content). Sorry if I missed something but I don't see much meaning as it is.

**Comment by enzus** [comment]
OK for keeping the two versions but I struggle to see an elegant way to communicate it. I like the idea of keeping clear the area around Plone logo in the toolbar. Could you please sketch something up to help us visualise it?

**Comment by davilima6** [comment]
Something like this:

![toolbar-contracted](https://cloud.githubusercontent.com/assets/422130/9114733/bcedb668-3c31-11e5-8893-a292f2b5e0c2.png)

![toolbar-expanded](https://cloud.githubusercontent.com/assets/422130/9114732/bced26f8-3c31-11e5-9c1f-6ba207ec3966.png)

Without the buggy padding _(which should be better fixed when [submenu arrows are dropped in favor of hover behavior](https://github.com/plone/Products.CMFPlone/issues/802#issuecomment-128407651))_.

**Comment by enzus** [comment]
Mmhhh I'm not convinced as the arrows this way seems more related to the body on the right than the toolbar underneath. I know it would probably be ugly but for the sake of clarity we should probably just add a text underneath the Plone logo which alternatively says "expand/collapse toolbar" or "show/hide toolbar labels" and keep the little arrow down.

**Comment by davilima6** [comment]
-1 on texts below logo but we could go for a tooltip on the toggler. "Expand/collapse" or "Expand/collapse toolbar" is enough since it's less expensive for a user to test and get acquainted with the behavior than it is to be forever exposed to a not so critical contextual helper.

Apart from that I really don't see why there is an arrow below logo right now.

**Comment by enzus** [comment]
OK a tooltip sounds like a good compromise! I guess the reason of the little arrow is to create some correlation with the elements of the toolbar. Imagine the toolbar in a themed website context: that arrows seems to say "hey this is a Plone websites and these are the tools".

**Comment by davilima6** [comment]
I see but I don't think that's necessary because sidebars are an already established design pattern and our toolbar is fixed and stands out by itself in relation to the rest of the website. Besides only logged-in users see it so they don't need extra help to figure out those are the CMS tools.

**Comment by enzus** [comment]
Didn't say it's right to have, I just guessed why is there :)

**Comment by davilima6** [comment]
Np, just making my point. Thanks for bringing this issue up!

**Comment by jkubaile** [comment]
How about moving the expand icon inside the bar like it is done for the other menus like adding?

**Comment by davilima6** [comment]
Not bad, but still not sure which I prefer (specially if the other menu arrows are dropped).

![toolbar-contracted-arrow-inside](https://cloud.githubusercontent.com/assets/422130/9122139/4b201cc0-3c5d-11e5-88d3-a25b5b9098b4.png)

**Comment by enzus** [comment]
Guys the more I look at it the more I think we should get rid of the arrows altogether. I know it's a legacy pattern and I usually prefer being explicit to being implicit but in this case I'm sure it's clear enough and with the mouse over discover what's behind each menu will be a matter of ms.

**Comment by pigeonflight** [comment]
I think a sidebar strip is more inline with common visual vocabulary.
Then it would be okay to leave the logo as a easter egg for those who know.

![expandable-sidebar](https://cloud.githubusercontent.com/assets/31827/9152028/b65f9e20-3dde-11e5-9e0c-02db11df56c6.png)

**Comment by hvelarde** [comment]
The option off using the toolbar expanded or collapsed should be on the personal preferences form and not where it's now:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9823313/f178c090-589b-11e5-9ada-d59549b5ac5a.png)

**Comment by vangheem** [comment]
Agreed. Trying to nestle something in the UI seems wrong...

**Comment by davilima6** [comment]
For consistency I think we should have both site-wide and personal settings, just like for the other 3 items.

**Comment by djay** [comment]
im really confused by what the sugessted options are from reading the comments. can someone who understands edit the original issue and list them?
we aren't suggesting removing ability to expand and contract to just via the personal preferences are we? its really useful to switch quickly between both.

**Comment by davilima6** [comment]
This issue is about adding an ever visible visual toggle to give a visual handler to the expand/contract toolbar behavior. I suggest @hvelarde opens a new issue regarding the location of the persistent setting: @@personal-preferences, @@site-controlpanel or both (my vote).

**Comment by hvelarde** [comment]
I opened another issue that I think is more relevant: Do we really need 4 versions of the toolbar? #1001

**Comment by enzus** [comment]
Sorry guys, just seen this as I still missing any sort of notification from github so have to go around exploring tickets!

I think the solution by @pigeonflight is very elegant, correct and effective pointing the arrow from the logo down the toolbar and reducing all the other arrows to one in a sidebar strip.

I'm not sure I understood what you want to be a personal preference? Would the user activate the possibility to have this easter egg working or would decide once and for all for the collapsed or the expanded mode?

**Comment by davilima6** [comment]
This is not (and shouldn't be) an easter egg, that was a joke regarding the lack of visual pointers for the expand/contract behavior.

The personal preferences we're talking about is the @@personal-preferences view on which you can override site-wide/all-users defaults like wysiwyg editor, language and timezone. Now it has been suggested (and I agree) to add toolbar's position, which currently lives only in @@site-controlpanel.

**Comment by hvelarde** [comment]
I think we are missing some serious analysis on how users use the toolbar: do they really change from expand to collapse to expand so often that the options needs to be in place all the time, or is just find to leave it in the personal toolbar?

I agree with @davilima6 that the vertical/horizontal option should be in the personal preferences also.

**Comment by enzus** [comment]
OK, I now get it and, yes, I agree as well that the vertical/horizontal option should be in the personal preferences, basically to state which default way (expanded or collapsed) the user would prefer to see the toolbar.

I honestly don't think this mechanism is essential but it could come handy in certain circumstances. The analysis can be done but Plone covers so many different situations that I'm not sure we can identify patterns of usage here.

**Comment by jensens** [comment]
nice to have which stood in here for too long, I think the solution as we have it in 5.2 now works fine.
