### ISSUE TITLE
Reader view on Safari mobile can't be activated

### ISSUE THREAD

**Issue by enzus** [plone/Products.CMFPlone#810]
## User problem

The "reader view" on Safari mobile can't be activated on any Plone page. The icon, usually visible on the left side in the address bar, doesn't appear. I guess it depends on how the page has been marked up in Plone. It's nevertheless a shame not having it working in the Barceloneta theme as it does improve the readability of long texts on mobile screens, enlarging the font size, increasing the contrast and deactivating the background.

Anybody knows how to fix this?

**Comment by tomgross** [comment]
https://mathiasbynens.be/notes/safari-reader

**Comment by enzus** [comment]
Thanks @tomgross, a fascinating mystery! Although I hoped for a more straightforward answer :)
