### ISSUE TITLE
Upgrade Plone 4.1 to 4.3: TinyMCE, CMFEditions and sunburst are not upgraded

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#812]
The same is true for Plone 4.2, except that CMFEditions does not need to be upgraded there because it had no changes.

Take this simple buildout:

```
[buildout]
extends = https://dist.plone.org/release/4.1.6/versions.cfg
# extends = https://dist.plone.org/release/4.2.7/versions.cfg
# extends = https://dist.plone.org/release/4.3.6/versions.cfg
parts = instance

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs = Plone
```

Create a standard Plone Site. Nothing more.
Now change the extends line to version 4.3.6 (or coredev 4.3), run the buildout, start the instance and run the Plone upgrade.
If you then go to the Upgrades tab in portal_setup, you will notice that:
- TinyMCE has upgrade steps available from profile version 3 to 7.
- CMFEditions has upgrade steps available from profile version 3 to 4 (unless you started with Plone 4.2, where CMFEditions starts out at version 4).
- sunburst has upgrade steps available from profile version 2 to 3.
Most noticeable is that the TinyMCE editor fails to load: you just get a plain textarea.
Running the upgrade steps fixes this.

I am working on a solution for this in plone.app.upgrade.

**Comment by hvelarde** [comment]
@rodfersou I think we have seen this before

**Comment by mauritsvanrees** [comment]
For TinyMCE, the upgrades are not applied. I've got that fixed locally an a p.a.upgrade branch.

For sunburst, and maybe CMFEditions, the upgrade method is run, but the profile version is not updated.

I am looking if it makes sense to update the upgradeProduct method in the QuickInstaller tool in CMFPlone to support a 'dest' argument, so you can upgrade to a specific profile version. Not really needed in this case. But could be useful in case there is a need to first upgrade profile A to version 3, then profile B to the latest, then profile A to the latest.

**Comment by hvelarde** [comment]
why don't we implement that in plone.api?

**Comment by mauritsvanrees** [comment]
Because there is a method in CMFPlone that already does that and which can be improved.

Sure, plone.api could grow a function to call that method.

**Comment by mauritsvanrees** [comment]
Actually, might be more something to put in GenericSetup.

**Comment by mauritsvanrees** [comment]
GenericSetup pull request added: https://github.com/zopefoundation/Products.GenericSetup/pull/15

It is not needed for this issue, but it would make the code easier to write.

**Comment by mauritsvanrees** [comment]
Pull request for GenericSetup is accepted. The fresh 1.7.7 has it.

More fun. Create a Plone 4.2 site. Install all standard add-ons, except kupu. Upgrade to 4.3.

- plone.app.jquery: upgrade steps are not applied. I am about to handle that. Also, its first upgrade step has an error, which I have now fixed in plone.app.jquery itself.
- plone.app.jquerytools: upgrade steps are not applied. But at least this is offered in the Plone UI: 1.2b4 to 3. portal_setup offers upgrade from 2 to 3, reluctantly because the current version is 1.2b4 so there is a mismatch.
- Marshall: Plone UI offers to update from 2.1.2 to 2.1.4. No profile, just old-style Extensions method.
- plone.app.discussion: upgrade steps are not applied. Plone UI says nothing. portal_setup offers to update from 100 to 101. It looks like p.a.discussion is robust enough to handle missing reigstry items. p.a.upgrade does create the new anonymous_email_enabled field. It does not add the new edit_comment_enabled field, but that seems to be implicitly added.

**Comment by mauritsvanrees** [comment]
Checking Plone 4.1 with all add-ons except kupu installed, upgrading to 4.3:
- plone.app.jquery is fine
- plone.app.jquerytools: stays at 1.2b4 instead of 3. QI lists it as not installed, but installable.
- Marshall: same as Plone 4.2, QI offers old-style upgrade.
- plone.app.discussion is fine
(This is with a few fixes already applied in plone.app.upgrade.)
