### ISSUE TITLE
Mobile devices: Toolbar icon appears off screen when viewing wide image

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#813]
It's not a very wide image but on iPhone 6 Plus the toolbar icon appears off screen if you are in portrait orientation. You have to move the screen to the right or zoom out or switch it to landscape orientation to see it. Here's the example image. 

http://dev.brianledwell.com:8081/Plone/image.jpg/view

Normal portrait view:

![image](https://cloud.githubusercontent.com/assets/815418/9152371/0fbc37c4-3deb-11e5-9645-aee068c2d8a5.jpg)

If you zoom out you can see the toolbar icon:

![image](https://cloud.githubusercontent.com/assets/815418/9152397/d7b7351c-3deb-11e5-9587-189f542ea289.jpg)

**Comment by jensens** [comment]
meanwhile this was fixes in 5.2
