### ISSUE TITLE
HTML filtering requires a "re save" on each page for the settings to take effect. 

### ISSUE THREAD

**Issue by bledwell** [plone/Products.CMFPlone#817]
Using:  Plone 5.0b4.dev0 (5007)

Been testing the HTML filtering settings using iFrame video. 
When I add an "iframe" video the saved page does not show the video (as expected). But when I toggle ON the "Disable HTML Filtering" checkbox the video still does not display on the page (even after emptying cache). If I edit the video page and immediately "Save" (making no edits) the video displays as expected. The reverse is also true. If I have video correctly displaying on the page (with html filtering disabled) and uncheck "Disable HTML Filtering" checkbox in the HTML Filtering panel, go back to the video page and reload the video still displays. If I edit the page and immediately save the page the video properly does not display. Is this the expected behavior?

In addition. If I add "iFrame" to the "Custom tags" dialogue box I cannot get the video to display with "Disable HTML Filtering" checkbox OFF. Even if I do the "Edit" and "Save" trick from above.

**Comment by davisagli** [comment]
portal_transforms has its own cache (on a volatile attribute) of the body text transformed to text/x-html-safe, which lasts for an hour and doesn't get cleared unless you re-save the item or restart Zope. That's probably what's preventing you from seeing a change here.

**Comment by bledwell** [comment]
If I understand correctly. If I were to wait.. say an hour (or what ever the number is). The videos would show then? or not show depending on the html filtering settings?

**Comment by bledwell** [comment]
BTW thanks for responding, Im trying to get my head around the filtering setting and testing to see if they work as expected.  :)

**Comment by davisagli** [comment]
Presumably any changes to the filtering settings would work after an hour, but you should probably confirm that.

**Comment by bledwell** [comment]
Thankyou! Ill do that. If everything turns out copasetic how would you suggest I proceed? Id think there should be some text added in the HTML panel like "Please note that changes to this panel will take about an hour to take effect" something along those lines. Would this be a PLIP request.. it just seem so .. minor to be a plip.

**Comment by tkimnguyen** [comment]
Would anyone object to some help text being added to this effect?

**Comment by jcerjak** [comment]
Looks like this was fixed in https://github.com/plone/Products.CMFPlone/commit/1e441aed21a31fd6adfab9a03ec83f7e81c85f8c by @vangheem . Though the text might be more visible to users if we (also) mention this in the flash message, instead of only "Changes saved."?

**Comment by vangheem** [comment]
Converting this to a flash message would be great I think. This trips up users ALL the time.

**Comment by jcerjak** [comment]
Ok, I'll convert it to a flash message.

**Comment by tkimnguyen** [comment]
Thanks @jcerjak
