### ISSUE TITLE
Incomplete mapping of language names in control panel

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#824]
![screen shot 2015-08-13 at 09 31 08](https://cloud.githubusercontent.com/assets/365761/9244723/3acf5ba6-419e-11e5-9a7c-5e2c053673b4.png)

for example de-at maps to "Deutsch (Österreich)", de-ch is not mapped to a label
where does the "magic" happen here?

**Comment by jensens** [comment]
still an issue

**Comment by davisagli** [comment]
Still valid in Plone 6

**Comment by mauritsvanrees** [comment]
`plone/i18n/locales/languages.py` has the language definitions. `de-ch` is missing a native name for the language:

```
    "de-at": {
        "name": "German (Austria)",
        "native": "Deutsch (Österreich)",
        "flag": "countryflag/at",
    },
    "de-ch": {
        "name": "German (Switzerland)",
        "flag": "countryflag/ch",
    },
```

So to fix it, you edit `de-ch` to have `"native": "Deutsch (Gruezibuezi)"` ;-)

I suppose it is logical that the English name is **not** used as fallback: if the user does not understand English, then she may not recognise the English name. "German" and "Deutsch" do not even begin with the same character.

I will add a few for German and Dutch.

**Comment by davisagli** [comment]
@mauritsvanrees I could imagine a fancy fallback that looks for a translation of the non-country-specific variation name of the language, then adds the 2-char country code in parentheses. But it is probably easier to just add the native names manually.

**Comment by davisagli** [comment]
Not really complete; that PR only fixed it for German and Dutch

**Comment by jensens** [comment]
wtf, automatic close ...

**Comment by davisagli** [comment]
@jensens yeah I know, no worries

**Comment by erral** [comment]
the [AvailableContentLanguageVocabulary in plone.app.vocabularies uses the native name and if there is no native the language code to build the vocabulary](https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/language.py#L50). 

In our [language list in plone.i18n](https://github.com/plone/plone.i18n/blob/master/plone/i18n/locales/languages.py#L61) we have native names only for language names and [not for language-country variants (except some of them)](https://github.com/plone/plone.i18n/blob/master/plone/i18n/locales/languages.py#L1432).

I added a PR fixing this in plone.i18n for many languages (mainly the big ones like `fr`, `es` and `en`), but there are still some missing, like `ar`

**Comment by mauritsvanrees** [comment]
Thanks @erral! I think this can be closed now. Doing so.
