### ISSUE TITLE
History view / document by line

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#828]
There is a problem on permissions as the history / document by line browser page depends on having review permission on the document, that produces a permission error on people who are editors and should be able to see the workflow on the document. 

It's not the standard behavior to see the history nevermind if you have review permissions ?

@agitator

**Comment by pbauer** [comment]
related to #739?

**Comment by bloodbare** [comment]
My opinion is that history view should have view permission and render some information or another depending on the permissions it has. In case has modify content, it should be able to revert, in case it has review it should have the option to compare with older versions, but the history may be tied to view permissions. This ticket is intented to define if everybody sees this is the natural behavior.

**Comment by agitator** [comment]
sounds sensible to me

are wf transitions in the history as well? 
then we should include those type of changes and only those for "revert" as well

**Comment by bloodbare** [comment]
Right now users without review permission can't press history button on the toolbar so it should be fixed before 5 release.

**Comment by mauritsvanrees** [comment]
People with only View permission should not be able to see the history I think. Otherwise they can see what has been changed when a page was still private. This may contain sensitive information. You know: plans to take over the world. Or version comments: "removed rant about stupid customer".

**Comment by bloodbare** [comment]
Good point @mauritsvanrees so we will need to change @historyview page to show only the document by line and check if there is a review permission to show the changelog/diff and the modify permission to revert. Is it ok ?

**Comment by mauritsvanrees** [comment]
Yes.
Well, the HistoryByLineView already has a `show` method with `return not self.anonymous or settings.allow_anon_views_about` and a `show_history` method that checks for the `CMFEditions: Access previous versions` permission. So that looks okay already.

**Comment by vangheem** [comment]
What is the status of this.

https://github.com/plone/Products.CMFPlone/issues/739
https://github.com/plone/plone.app.content/pull/45

seem related.

We should close these tickets.

**Comment by hvelarde** [comment]
@rodfersou FYI
