### ISSUE TITLE
Copy/cut an image triggers the fullscreen view

### ISSUE THREAD

**Issue by enzus** [plone/Products.CMFPlone#829]
Just tested on http://dev.brianledwell.com:8081/Plone/image.jpg/view

If I click on Cut or Copy I'm redirected to the fullscreen view of the image (the one without any view template applied) although the action has been performed correctly.

**Comment by pbauer** [comment]
@enzus thanks for reporting. Keep the tickets coming :smiley:

**Comment by pbauer** [comment]
The same is true for rename
