### ISSUE TITLE
Support for JS code loaded in javascript_head_slot (in 5.0)?

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#837]
I am loading the JS module "DataTables.net" within one particular view (of XML Director):

https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/browser/connector_view.pt#L15-L19

The related DataTables initialization code

https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/browser/resources/local.js#L190

fails with 

    Uncaught TypeError: $(...).DataTable is not a function

The DataTables JS and CSS is actually loaded...is there anything else that is needed here in order to initialized third-party JS modules loaded directly through the javascript_head_slot (without using the jsregistry.xml (only needed for one particular view of the add-on)) or is this a pending bug?

Tested against Plone 5.0b4.

**Comment by vangheem** [comment]
Has to be something with the order of include. Look at https://github.com/plone/plone.app.registry/blob/master/plone/app/registry/browser/records.pt#L102 for examples of js being included. There are also some examples in plone.app.dexterity.

I'd have to see what is going on with the order that diazo is transforming the output.

**Comment by zopyx** [comment]
So the recommended way to include third party JS code in a Plone 4.3 + 5.0
compatible way is to place it at the end of the template instead of using
the JS head slot, right?



2015-09-07 23:57 GMT+02:00 Nathan Van Gheem <notifications@github.com>:

**Comment by davisagli** [comment]
I had the same problem with DataTables. It turn out that if require.js is loaded, then DataTables will register itself as an AMD module instead of loading globally.

I worked around the problem by adding this in my template right before I include the DataTables js, so that it doesn't detect that require.js is present:

      <script type="text/javascript">define = undefined; // make sure datatables doesn't register itself with requirejs</script>

**Comment by davisagli** [comment]
I guess a less hacky fix would be to do your datatables initialization inside a require() block.

**Comment by vangheem** [comment]
or put it in the legacy bundle since this commit: https://github.com/plone/Products.CMFPlone/pull/870/files

**Comment by frisi** [comment]
just an idea:
you might as well add your 3rd party script and css as a resource (IResourceRegistry)
and include it in your special view using `Products.CMFPlone.resources.add_resource_on_request`
see [resource registry docs section Adding or removing bundles from a request](https://github.com/plone/documentation/blob/5.0/adapt-and-extend/theming/resourceregistry.rst#id9)

**Comment by thet** [comment]
IMO, adding your javascript to the plone-legacy bundle should fix your problem. Here is some updated information about the resource registry, which might help clear up troubles: https://github.com/plone/documentation/blob/5.0/adapt-and-extend/theming/resourceregistry.rst
If not, reopen this issue or come over to get some help at the ploneconf sprint!
