### ISSUE TITLE
Convert "Delete Confirmation" to a browser view

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#84]
This pertains to the following files:

 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_forms/delete_confirmation_page.cpt
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_forms/delete_confirmation_page.cpt.metadata
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_form_scripts/delete_confirmation.cpy
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_form_scripts/delete_confirmation.cpy.metadata

**Comment by jensens** [comment]
so we can close this one
