### ISSUE TITLE
Portlet Management with weird artifacts

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#844]
Just installed Plone 5.0b4 and decided to add several portlets to the left slot of the front page...
the edit screen ended up like this:

![screenshot-dev1 veit-schiele de 7080 2015-08-28 15-32-48](https://cloud.githubusercontent.com/assets/594239/9547371/3e09b520-4d9a-11e5-9d64-687bca974344.png)

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.portlets/pull/54 should address this.
