### ISSUE TITLE
Still compatibility issues with legacy bundles, require.js (collective.elasticindex on Plone 5.0b4)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#845]
Testing our implementation of collective.elasticindex with Plone 5.0b4

https://bitbucket.org/dasgehirn/collective.elasticindex/src

After installing collective.elasticindex in Plone 5 (bin/buildout -c buildout-50.cfg) 
I see the following error on the JS console:

Uncaught Error: Mismatched anonymous define() module: function (){return Mark;}
http://requirejs.org/docs/errors.html#mismatchmakeError @ require.js:166intakeDefines @ require.js:1239(anonymous function) @ require.js:1427

**Comment by vangheem** [comment]
Master should have a workaround for these situations. Please try again when a new beta is out and reopen is you still see problems. Thank you.

**Comment by vangheem** [comment]
For reference: https://github.com/plone/Products.CMFPlone/pull/870
