### ISSUE TITLE
Visual issue in portlet management 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#846]
Screen screenshot
![screenshot-dev1 veit-schiele de 7080 2015-08-28 15-45-34](https://cloud.githubusercontent.com/assets/594239/9547638/eee5579a-4d9b-11e5-80d8-d79fb868be23.png)

**Comment by vangheem** [comment]
The old @@manage-portlets is no longer exposed in the UI is it? 

I'm inclined to say "won't fix" because this is harder to get all these styling cases fixed in tight column column spacing.

**Comment by vangheem** [comment]
Closing as @@manage-portlets is hidden in Plone 5 UI. Let me know if this is not the case. We are moving away from managing portlets like that.

**Comment by hvelarde** [comment]
how do you manage portlets in Plone 5 then?

**Comment by vangheem** [comment]
It's a drop down and you select the portlet manager you want to edit. You should try plone 5 :)

**Comment by hvelarde** [comment]
I will, on Friday :-)
