### ISSUE TITLE
JS error in Plone add view

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#847]
Escaping problem; see screenshot

**Comment by zopyx** [comment]
![out](https://cloud.githubusercontent.com/assets/594239/9547684/48be01ae-4d9c-11e5-8aed-982d872a9a1c.png)

**Comment by jaroel** [comment]
Probably should have a fallback, for when the client's timezone cannot be determined, or when a javascript error occurs, like this.

Proposed fallback: the server's timezone selected, on error or no client timezone.

**Comment by thet** [comment]
Why does this error occur? In the template there is no html encoded character: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/plone-addsite.pt#L32
can Diazo be the cause and changing a ``<`` into a ``&lt;``?

**Comment by vangheem** [comment]
Yes, it's diazo.

**Comment by jaroel** [comment]
This happens when you already have a Plone site installed (with Diazo).

**Comment by sneridagh** [comment]
I couldn't reproduce it. However, if it's Diazo to blame for, it would be enough to create a static resource for it?

**Comment by thet** [comment]
@sneridagh yes, that would solve it.
