### ISSUE TITLE
Query input field badly place in folder contents view

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#849]
![screenshot-dev1 veit-schiele de 7080 2015-08-28 15-56-04](https://cloud.githubusercontent.com/assets/594239/9547849/6553b416-4d9d-11e5-89cd-7c225e471235.png)

Depending on the width of the screen, the query input field is either placed
- left aligned
- right aligned with the button row above
- placed right aligned under the button row...completely random and inconsistent

**Comment by vincentfretin** [comment]
In Plone 5.2.2, I think this is fine:
![Capture d’écran de 2020-07-08 13-29-53](https://user-images.githubusercontent.com/112249/86913706-4f7d9a80-c11f-11ea-9dd0-ca3db22e6539.png)
![Capture d’écran de 2020-07-08 13-30-03](https://user-images.githubusercontent.com/112249/86913713-50163100-c11f-11ea-9466-ade0f0394be2.png)
![Capture d’écran de 2020-07-08 13-30-27](https://user-images.githubusercontent.com/112249/86913716-50aec780-c11f-11ea-8b7e-1802394d7c49.png)

Please reopen with a proposed solution if you disagree.
