### ISSUE TITLE
"Properties" dialog of folder contents, locale issues

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#850]
See screenshots:
- button placement wrong
- UI language is set to German but the date dialog use YEAR-MONTH instead of MONTH-YEAR
- time dropdown uses AM/PM (which is not used in Germany)

![screenshot-dev1 veit-schiele de 7080 2015-08-28 16-00-04](https://cloud.githubusercontent.com/assets/594239/9547976/0c1c9cd6-4d9e-11e5-9491-3f4b43dd1ee0.png)
![screenshot-dev1 veit-schiele de 7080 2015-08-28 16-00-31](https://cloud.githubusercontent.com/assets/594239/9547975/0c14a1e8-4d9e-11e5-8e5e-aed5915492b2.png)

**Comment by jensens** [comment]
still a problem, only few parts solved

**Comment by erral** [comment]
This one is really tricky. I traced it down to here: https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/templates/properties.pt#L5

There both effective and expiration form values are rendered and both have the pat-pickadate class with which the widget is rendered. The first try has been to add the pickadate configuration there (`data-pat-pickadate` attribute) but that does not work for some reason.

I don't understand how the widget is rendered correctly *but* the pickadate options are not taken. I keep investigating.

**Comment by vincentfretin** [comment]
You're on the right track. :-)
When I looked for the pickadate localization for the the add/edit form of a content type in https://github.com/plone/Products.CMFPlone/issues/3134#issuecomment-651204931
I saw indeed that we have `data-pat-pickadate="{&quot;date&quot;: {&quot;selectYears&quot;: 200}, &quot;time&quot;: {&quot;interval&quot;: 5 } }"` on the body tag and that for each date field `data-pat-pickadate="{&quot;date&quot;: {&quot;format&quot;: &quot;d mmmm yyyy&quot;, &quot;selectYears&quot;: 200, &quot;min&quot;: [1920, 1, 1], &quot;monthsFull&quot;: [&quot;janvier&quot;, &quot;f\u00e9vrier&quot;, &quot;mars&quot;, &quot;avril&quot;, &quot;mai&quot;, &quot;juin&quot;, &quot;juillet&quot;, &quot;ao\u00fbt&quot;, &quot;septembre&quot;, &quot;octobre&quot;, &quot;novembre&quot;, &quot;d\u00e9cembre&quot;], &quot;weekdaysShort&quot;: [&quot;dim.&quot;, &quot;lun.&quot;, &quot;mar.&quot;, &quot;mer.&quot;, &quot;jeu.&quot;, &quot;ven.&quot;, &quot;sam.&quot;], &quot;weekdaysFull&quot;: [&quot;dimanche&quot;, &quot;lundi&quot;, &quot;mardi&quot;, &quot;mercredi&quot;, &quot;jeudi&quot;, &quot;vendredi&quot;, &quot;samedi&quot;], &quot;firstDay&quot;: 0, &quot;max&quot;: [2040, 1, 1], &quot;placeholder&quot;: &quot;Entrer la date\u2026&quot;, &quot;monthsShort&quot;: [&quot;janv.&quot;, &quot;f\u00e9vr.&quot;, &quot;mars&quot;, &quot;avr.&quot;, &quot;mai&quot;, &quot;juin&quot;, &quot;juil.&quot;, &quot;ao\u00fbt&quot;, &quot;sept.&quot;, &quot;oct.&quot;, &quot;nov.&quot;, &quot;d\u00e9c.&quot;]}, &quot;clear&quot;: &quot;Effacer&quot;, &quot;today&quot;: &quot;Aujourd'hui&quot;, &quot;time&quot;: {&quot;placeholder&quot;: &quot;Entrer l'heure\u2026&quot;, &quot;format&quot;: &quot;HH:i&quot;}}"`

**Comment by erral** [comment]
Ah, my change was OK, formatting of JSON options was the problem. I got his one in https://github.com/plone/plone.app.content/pull/206
