### ISSUE TITLE
Date widget shows up with unnecessary scrollbars

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#851]
![screenshot-dev1 veit-schiele de 7080 2015-08-28 16-06-04](https://cloud.githubusercontent.com/assets/594239/9548104/c4f28ce8-4d9e-11e5-8539-3102e2a39249.png)

**Comment by polyester** [comment]
closing, as duplicated (with more error reports in various languages) in https://github.com/plone/Products.CMFPlone/issues/891

that provides a more complete error description
