### ISSUE TITLE
Plone 5: file id when title is provided

### ISSUE THREAD

**Issue by keul** [plone/Products.CMFPlone#855]
Tested now on Plone 5 master branch.

When you create a file (test.pdf) with a title ("Important document") the id of the file is "test.pdf" and not "important-document".

This is the old behavior we had on Plone 3.3, disappeared after plone.app.blob. I also created a ticket about it years ago (see https://dev.plone.org/ticket/9902) but it was closed as this new behavior was the intentional.

We changed idea again or is this a bug?

**Comment by pbauer** [comment]
I think that behavior is intentional. See https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/behaviors/filename.py and https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/tests/filename.txt. 
Personaly I'd prefer the title being used if it is provided and the filename only when there is no title.

**Comment by mauritsvanrees** [comment]
There is also the INameFromTitle behavior from plone.app.content. If I enable this, then the filename behavior gets ignored: a pdb in there never gets called. So enabling both behaviors is useless.

I notice that, regardless of which behaviors are activated or not, when I do not set a title myself, the context title automatically gets set to the filename. The filename behavior tries to do this too, but it has actually already been done by other code. I guess when there is a primary file field, some other code takes care of taking the title from this field.

So there are two options:

1. Use the current filename behavior:
  - If no explicit title is set, the title is set to the filename.
  - The id is taken from the filename.

2. Use the 'name from title' behavior:
  - If no explicit title is set, the title is set to the filename.
  - The id is taken from the title. So without an explicit title it is taken from the filename.

The second one seems Philip's preference. And mine too.

**Comment by keul** [comment]
Is my preference too, is not handy to say to customers that used Plone 3 then migrate to Plone 4 that the CMS changed this behavior. Again :smile:

**Comment by jensens** [comment]
outdated - wont fix
