### ISSUE TITLE
i18n/multilinguality not working

### ISSUE THREAD

**Issue by ida** [plone/Products.CMFPlone#856]
Since Plone-4.3.5, choosing another language than English for the site doesn't work (tested with P-4.3.5 and P-4.3.6). Except for workflow-states, strings remain to be English. Likely they are the default-strs (=not of English po-file).

**Comment by mauritsvanrees** [comment]
I have not noticed this.

You need to include some environment variables with the wanted supported languages in your buildout config.  Did you do that? See for example:
https://github.com/mauritsvanrees/maurits.i18ntalk/blob/master/talk.rst#buildoutcfg

**Comment by ida** [comment]
Thanks for quick response, no I didn't use the env-vars, I have very minimal builds for quick testing, each buildout.cfg is the same, just Plone-vs differs, sharing same eggs-cache. Interestingly, it works with the P-4.3.4-build, not with higher versions. But thanks, so for a production-env it's safe to use P > 4.3.4, when including the env-vars. Taking the chance, to leave a big thank you here, for the i18n-docs (amongst other helpful articles) you shared! E.g. I would have probably never figured out by myself, which profile-xml's need the plone-domain and which can use another.

**Comment by ida** [comment]
Closing, as it's no issue, when including the env-vars.
