### ISSUE TITLE
Bump to lxml 3.x

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#857]
I'd like to see us move to lxml 3.x (currently 3.4.4) before we cut the Plone 5 release. We're currently stuck on a version from 2011.

See [this thread from plone-developers](http://sourceforge.net/p/plone/mailman/plone-developers/thread/loom.20131029T170619-278%40post.gmane.org/#msg31576153) for some background.

At the time, the largest issue was the lack of Windows binaries. Unofficial builds are [available](http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml), and since we're not doing Windows installers at the moment, this is mostly moot.

**Comment by esteele** [comment]
[cssselect](https://github.com/SimonSapin/cssselect/) has now been split out of lxml proper and Plone won't run without that installed. 

Looking at it, I *think* two of the fixes in experimental.cssselect are now also in csseelect:
* [Make ``:contains()`` case sensitive for simplicity and speed](https://github.com/lrowe/experimental.cssselect/commit/df96e2b69e28a34b17f6cc2e0fc394c7fa02e149) looks to be [fixed here](https://github.com/SimonSapin/cssselect/blob/master/cssselect/parser.py#L373)
* [Fix bug with ignorable spaces between css selector groups.](https://github.com/lrowe/experimental.cssselect/commit/fe1d1347bae9fe1e9177a6e4ada5ce9bafdbd39d) looks to be [fixed here](https://github.com/SimonSapin/cssselect/commit/549177557a127be26f59edec696a0a8dc2e30e43)

So the remaining one would be ["use the xpath 'A//B' (short for  'A/descendant-or-self::node()/B') instead of 'A/descendant::B' for the css descendant selector ('A B')."](https://github.com/lrowe/experimental.cssselect/commit/c8b229ceddc0fc8db52cc11a29aae49b9252d2d8), which I haven't been able to find (and TBH, don't completely understand).

**Comment by esteele** [comment]
For that last one, running 
```_unicode _unicode(GenericTranslator().css_to_xpath('A B', prefix=''))``` through cssselector results in ```u'A/descendant-or-self::*/B'```

**Comment by esteele** [comment]
See https://github.com/plone/diazo/commit/62befdd5b1145d0689d95f07c948dc59bb0fd63a

**Comment by tisto** [comment]
+1 Let me know if you need a jenkins job to test this...

**Comment by esteele** [comment]
@tisto: Yes, please. That'd be great.

**Comment by tisto** [comment]
@esteele done: 

http://jenkins.plone.org/view/PLIPs/job/plip-lxml3
https://github.com/plone/buildout.coredev/blob/801b3bee543ea338a04efbcdc9229565c19ba3fa/plips/plip-lxml3.cfg
