### ISSUE TITLE
Profile listing on site creation has alignment issues

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#862]
When using the advanced version of the plone-addsite view (/@@plone-addsite?advanced=1), the list of profiles has some alignment issues:

![screen shot 2015-09-04 at 6 06 31 pm](https://cloud.githubusercontent.com/assets/483999/9695429/b7ed898a-532f-11e5-8c40-210a7c76f622.png)

**Comment by ichim-david** [comment]
@esteele  I've added a pull request for this issue being an easy fix
https://github.com/plone/Products.CMFPlone/pull/906
