### ISSUE TITLE
Move password_reset info into password reset tool

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#87]
This may be started in a branch of ProductsPasswordResetTool. Check at https://github.com/plone/Products.PasswordResetTool/tree/plip-13260-cpy-removal and make sure the below files are there. Make sure this build points to this branch... then delete!

Files affected: 
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_form_scripts/plone_change_password.py
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_prefs/password_form.pt
 * https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_prefs/password_form.pt.metadata

I am nervous about the integration of this and the member_prefs stuff, which is at #88 . I'm pretty sure PasswordReset is the right package but I could be wrong here.

**Comment by vangheem** [comment]
Closing. This should be part of the plone.login package for plone 5.1.
