### ISSUE TITLE
Migrate Archetypes specific portal_properties to ATCT

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#872]
These items in portal_properties/site_properties are no longer used in core. They should get moved into ATCT as part of the portal_properties deprecation.
*  calendar_starting_year
*  calendar_future_years_available
*  ellipsis
*  search_results_description_length
*  allowRolesToAddKeywords

plone_scripts/date_components_support can be moved as well since it's only used by ATCT and references the two calendar_* items above.

**Comment by pbauer** [comment]
``search_results_description_length`` and ``ellipsis`` could be used in ``Products.CMFPlone.browser.search.AjaxSearch.__call__`` with ``Products.CMFPlone.browser.ploneview.Plone.cropText`` to fix #902. And also in ``plone.app.contentlisting.catalog.CatalogContentListingObject.CroppedDescription`` (which is not used in the live-search but the "normal" search). Should we these properties to the registry?

**Comment by vangheem** [comment]
Those settings should be pattern options that can be overridden I think.

**Comment by pbauer** [comment]
The code to crop text already exists in python and would also be used in placed without a pattern (the normal search-results). I see no need to duplicate the same logic in javascript.
See a basic implementation here https://github.com/plone/Products.CMFPlone/commit/b7c2c41156beac7357223ffb83c5a8fc2e7bf9a8.

**Comment by vangheem** [comment]
Okay, that's fine. Thank you.

**Comment by esteele** [comment]
I'm curious, what's the use case for the ellipsis property? Is that a localization thing or someone that people commonly customize?

**Comment by pbauer** [comment]
No idea, I guessed a similar thing (what I found is this weird discussion: http://legendsoflocalization.com/qa-japanese-ellipsis-usage-and-english-translation). What do the i18n-experts say?

**Comment by esteele** [comment]
@vincentfretin: Do you know of any i18n/l10n reason for the ellipsis property?

**Comment by vincentfretin** [comment]
@esteele I didn't know about this ellipsis property. Maybe it's useful for some language. Maybe @terapyon can answer that.

**Comment by esteele** [comment]
I'm inclined to drop it and see if anyone complains. If it is a localization thing, it might be better off in a translation string.

**Comment by pbauer** [comment]
yes, drop it

**Comment by vincentfretin** [comment]
fine by me

**Comment by esteele** [comment]
One other notable part of this ticket. These portal types were previously values in 'types_not_searched', but had to be removed because they weren't valid in sites without Archetypes (prevented by the vocabulary tied to the field). 

* ATBooleanCriterion
* ATDateCriteria
* ATDateRangeCriterion
* ATListCriterion
* ATPortalTypeCriterion
* ATReferenceCriterion
* ATSelectionCriterion
* ATSimpleIntCriterion
* ATSimpleStringCriterion
* ATSortCriterion
* ChangeSet
* ATCurrentAuthorCriterion
* ATPathCriterion
* ATRelativePathCriterion

**Comment by pbauer** [comment]
The criteria were moved in https://github.com/plone/Products.ATContentTypes/commit/f7359a3660a1061189876d06508bb6db940bbced

**Comment by pbauer** [comment]
calendar_starting_year and calendar_future_years_available were moved to registry and Products.Archetypes in https://github.com/plone/Products.Archetypes/commit/986f14764be678f9534187f8a8ccd2f7c0a419aa https://github.com/plone/plone.app.upgrade/commit/71728d250eb978aa8c0cc362b958b40df1f2ef02 and https://github.com/plone/Products.CMFPlone/commit/978d43503c1545515a2f9d0afec45cbb7db7d737

**Comment by pbauer** [comment]
The criteria-move broke the build and was reverted. Will try again.

**Comment by pbauer** [comment]
Done \o/
