### ISSUE TITLE
Plone 4.3: Checked out content (via iterate) and the versions_history_form 

### ISSUE THREAD

**Issue by neilferreira** [plone/Products.CMFPlone#874]
Hello

I've been using plone.app.iterate for a while and never really paid much attention to the "History" form (versions_history_form) - it appears that the Baseline lists all of the historical changes made to it but once you make a checkout then the checkout itself is not aware of any of the History, it just comes up empty.

Is this by design? Or am I running into a bug?

**Comment by vangheem** [comment]
I'm not sure it's by design but I'm also not sure it's a bug.

**Comment by davilima6** [comment]
I see this as a bug cause checking out is a normal content operation, which can be done several times a day or week (eg: a frontpage or a cover) without the intention of creating a brand new item.

**Comment by vangheem** [comment]
It doesn't remove history from the baseline item, it just doesn't copy it over to the working copy.

**Comment by mauritsvanrees** [comment]
I would not call it a bug. A checkout is meant to be temporary. Once you check it in, those changes will be added to the history.

It seems unneeded to me to copy over the history to the checkout item. Also, the code would probably get confusing, at least to me. :-)

**Comment by neilferreira** [comment]
That is fine, I looked into it further and understand a bit more about it.  The history is stored under 'portal_revisions' and it makes sense that this history would not be copied across.
