### ISSUE TITLE
bundled twitter bootstrap theme is incomplete

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#877]
It doesn't work with the toolbar or editing.

It would be nice to update it to use #465.

**Comment by esteele** [comment]
@djay Can you elaborate a bit more? What does the successful completion of this ticket look like for you?

**Comment by djay** [comment]
Should be a complete theme that includes portlets etc, and an editing interface. I don't think it really does its job of showing another way to do a diazo theme. Using it to show off #465 and fixing it so it mostly works as a theme would help.

**Comment by djay** [comment]
Also has a problem when you try to use the toolbar since both are absolutely positioned.

**Comment by jcerjak** [comment]
Here is how the bootstrap theme looks for logged-in users - it's a bit broken and you cannot actually click on the links in the main navigation.

![plone-bootstrap-theme](https://cloud.githubusercontent.com/assets/191024/9836595/bf929512-5a1f-11e5-9d19-6bfe11414276.jpg)

**Comment by thet** [comment]
IMO, if we can't fix it until release date, we should remove the bootstrap theme.

**Comment by vangheem** [comment]
I agree. Since we ship with a diazo theme anyways, perhaps maintaining this theme isn't necessary.

**Comment by esteele** [comment]
Maintaining two themes has not worked well for us in the past.

**Comment by pbauer** [comment]
I'll rip it out
