### ISSUE TITLE
User and Groups controlpanel unusable when using more roles

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#879]
![bildschirmfoto 2015-09-08 um 14 45 00](https://cloud.githubusercontent.com/assets/453208/9735120/b7760412-5638-11e5-9f2a-6ed8c004f116.png)

**Comment by sneridagh** [comment]
Fixed by: https://github.com/plone/plonetheme.barceloneta/commit/d006020a5e77fb7151ea4f754f4932546aa0ea52
