### ISSUE TITLE
NewsML implemented in Plone 4 but never ported to Plone 5

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#880]
@jpgimenez think you could port that to Plone 5?

**Comment by hvelarde** [comment]
@vangheem we'll take care of this before the final release

**Comment by pbauer** [comment]
There is a new pr with these changes and failing tests: https://github.com/plone/Products.CMFPlone/pull/971

**Comment by rodfersou** [comment]
PR merged, closing issue
