### ISSUE TITLE
@@plone-addsite missing link to advanced page

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#883]
The @@plone-addsite has no link to the advanced page.
It is a common usecase to install add-ons while creating the Plone site. 

Adding &advanced=1 to the URL is not very integrator-friendly.

**Comment by pbauer** [comment]
The advanced-link is there on http://localhost:8080/: 
![bildschirmfoto 2015-09-13 um 11 16 07](https://cloud.githubusercontent.com/assets/453208/9836027/e0d92ac2-5a08-11e5-8df3-489b30d9d605.png)
On http://localhost:8080/manage_mainis is not there.
I added it in https://github.com/plone/Products.CMFPlone/commit/208ada8330dc7817fb7a4686b1e0f7e747d8257f
