### ISSUE TITLE
Products.TextIndexNG==3.4.10.2 does not appear as installable add-on

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#885]
Products.TextIndexNG==3.4.10.2
 
is shown within the portal_quickinstaller but does not show up in site setup.

I can install the add-on through portal_quickinstaller without issue.

The auto-include slug is configured properly

https://github.com/zopyx/Products.TextIndexNG3/blob/master/setup.py#L60-L61

So what is the additional magic needed for installing add-ons (with 'Products' namespace) properly in Plone 5?

**Comment by mauritsvanrees** [comment]
The additional magic is that you must have a GenericSetup profile.  And you have it, but it is registered with a condition that is false in default Plone 5:

```
      zcml:condition="installed Products.CMFDefault"
```

When I remove this condition, it shows up fine.

For further discussion see issue #527.

**Comment by zopyx** [comment]
oopppsss..good catch
