### ISSUE TITLE
UI element overlap in resource registry control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#886]
See screenshot. There is an overlap of two UI elements.

![screenshot-dev1 veit-schiele de 8081 2015-09-09 07-34-37](https://cloud.githubusercontent.com/assets/594239/9754055/550e0206-56c5-11e5-89a1-fb0eb733e723.png)

**Comment by rodfersou** [comment]
I think the best way to fix it is just at first tab ("Registry") the buttons go down (change the top: -42px; to top: 1rem;)

In the other tabs there are some elements in this space that will overlap, and at other tabs there are few buttons so, there is no problem to be near the tabs.

**Comment by rodfersou** [comment]
@pbauer @zopyx what do you think?

**Comment by rodfersou** [comment]
@vangheem too fast.. there is another pull request updating the css

**Comment by rodfersou** [comment]
https://github.com/plone/Products.CMFPlone/pull/1031
