### ISSUE TITLE
Folder contents column selector 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#889]
The default ordering of the columns within the folder contents columns selector does not represent the actual state (the default column ordering) of the folder contents view.

**Comment by zopyx** [comment]
![screenshot-dev1 veit-schiele de 8081 2015-09-09 07-51-10](https://cloud.githubusercontent.com/assets/594239/9754283/c6672b42-56c7-11e5-9a7f-ab421c35773e.png)

**Comment by jensens** [comment]
tried this and it now matches the order in the list. can be closed.
