### ISSUE TITLE
"Stichworte" vs. "Stichwörter", German translation for "Subject(s)"

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#890]
The Plone 5 UI mixes "Stichworte" vs. "Stichwörter" in various places in an inconsistent way.
![screenshot-dev1 veit-schiele de 8081 2015-09-09 07-55-39](https://cloud.githubusercontent.com/assets/594239/9754326/3b0a212a-56c8-11e5-9d1f-a7ef54dab180.png)

**Comment by jensens** [comment]
Eigentlich meinen wir ja auch Schlagworte https://www.duden.de/rechtschreibung/Schlagwort#Bedeutung2 
und nicht Stichwörter https://www.duden.de/rechtschreibung/Stichwort#Bedeutung1a 
oder Stichworte https://www.duden.de/rechtschreibung/Stichwort#Bedeutung3

**Comment by icemac** [comment]
@jensens Leider muss ich dir widersprechen: Wenn es um Verschlagwortung geht ist „Schlagwörter“ der korrekte Plural von „Schlagwort“, _nicht_ „Schlagworte“. So steht es auch in dem Duden-Link, den du referenziert hast: https://www.duden.de/rechtschreibung/Schlagwort#Bedeutung2

**Comment by jensens** [comment]
@icemac, oh, ja, ich hab mich da wohl verwirren lassen, danke für den Hinweis. Ich korrigiere das. Aber Grundsätzlich passt Schlagwort schon besser?

**Comment by icemac** [comment]
@jensens Ja, Schlagwort passt besser als Stichwort, da es ja um Verschlagwortung geht. Schlagwort halte ich für eine gute Übersetzung von `tag` bzw. `keyword`.
