### ISSUE TITLE
Model editor in dexterity control panel: Only a small cutout is shown in the edit field

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#895]
![modeleditor](https://cloud.githubusercontent.com/assets/918640/9759749/ba4362d6-56ef-11e5-9f47-5075b1425765.png)

But you can scroll it.

**Comment by pbauer** [comment]
Some js is not found:
```
"NetworkError: 404 Not Found - http://localhost:8080/Plone/++resource++plone.resourceeditor/ace/ace.js"
"NetworkError: 404 Not Found - http://localhost:8080/Plone/++resource++plone.resourceeditor/ace/mode-xml.js"
```
See also https://github.com/plone/Products.CMFPlone/issues/826

**Comment by pbauer** [comment]
@vangheem can you have another look at this please?

**Comment by rodfersou** [comment]
Still need to fix ace-editor style to fill all the height 
![ace-size-error](https://cloud.githubusercontent.com/assets/131209/9959069/cedba5a2-5de6-11e5-9ac6-a414ca7a21b1.png)

**Comment by rodfersou** [comment]
I changed the theme to the only disponible theme (monokai) and the height grows
![ace-size-error2](https://cloud.githubusercontent.com/assets/131209/9959505/fa656ccc-5dea-11e5-8eb1-4300da834fda.png)
