### ISSUE TITLE
Visual overlap in TinyMCE image upload

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#898]
![screenshot 2015-09-09 17 02 31](https://cloud.githubusercontent.com/assets/594239/9765473/a0c19bfa-5714-11e5-811c-7a8afdf94f0a.png)

**Comment by jensens** [comment]
wow, this one is still true

**Comment by vincentfretin** [comment]
duplicate of https://github.com/plone/Products.CMFPlone/issues/2533 which I fixed
