### ISSUE TITLE
Out-of-the-box user story for embedding videos broken

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#899]
TinyMCE has a menu to insert multimedia embedding code. So far so good. However iframes are being filtered out of the box which provides an inconsistent user experience since the user needs to modify the html filtering settings. 

Consistency is king. Either the multimedia support is working out of the box or it should not be available out of the box. If you disable it by default then there could be an easy "enable multimedia embedding" button within the HTML filtering settings control panel that would adjust the html filtering settings and the enable the option in TinyMCE.

Since embedding/iframes may affect security, this feature must be seen with the new configurable security level of Plone.

**Comment by djay** [comment]
+1

**Comment by vangheem** [comment]
+1, IMO, OOTB plone should just ship with iframe/object enabled. Rarely do people not want this and it's a huge annoyance.

**Comment by hvelarde** [comment]
+1

**Comment by vangheem** [comment]
Closed with https://github.com/plone/Products.PortalTransforms/commit/f1f2b6a40682a8073765c7a29116fea700ed2852
