### ISSUE TITLE
Too much console.log noise...

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#901]
Too many messages on the console..including deprecation warnings..

![screenshot 2015-09-09 17 17 49](https://cloud.githubusercontent.com/assets/594239/9765918/caff52ca-5716-11e5-9aba-baaec2d1cfa5.png)

**Comment by vangheem** [comment]
should be fixed with https://github.com/plone/Products.CMFPlone/commit/64bc88d14b108de0c1f7d409218318387018abf6
