### ISSUE TITLE
Descriptions shown in the live search result window should be truncated

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#902]
Overlong descriptions should be truncated after N chars in order to keep the result list usable.
![screenshot 2015-09-09 17 20 03](https://cloud.githubusercontent.com/assets/594239/9765994/21153f08-5717-11e5-99bc-aea4d5dc847b.png)

**Comment by pbauer** [comment]
Please look at https://github.com/plone/Products.CMFPlone/commit/b7c2c41156beac7357223ffb83c5a8fc2e7bf9a8
If that approach is generaly ok. I'll add a upgrade-step to move search_results_description_length to registry and add it to plone.app.constentlisting as well.

**Comment by vangheem** [comment]
This issue can be closed now right?

**Comment by pbauer** [comment]
There are actually 3 open pr's to fix this:
- https://github.com/plone/Products.CMFPlone/pull/909
- https://github.com/plone/plone.app.upgrade/pull/48
- https://github.com/plone/plone.app.contentlisting/pull/9

**Comment by pbauer** [comment]
I merged all three pull-requests (in the right order). I hope jenkins will not barf.

**Comment by pbauer** [comment]
Jenkins is happy.
