### ISSUE TITLE
Hide AtD settings in TinyMCE control panel when not selected

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#904]
AtD fields should be hidden when it isn't selected as the spellchecker type.

**Comment by zopyx** [comment]
AtD seems to stand for "After the deadline" spellchecker...AtD related options should be hidden if AtD is not chosen. It should be explained that there are obviously two different spellcheckers.  The UI does not explain what AtD is and what the advantages over the default spellchecker are.

**Comment by vangheem** [comment]
This is exactly the same wording that has been used in Plone 4 for a long time.

**Comment by hvelarde** [comment]
yes, but we must fix it at some point :-)

**Comment by vangheem** [comment]
It says right in the description "After the Deadline".

So you're ticket is that we should write integration code to conditionally hide AtD fields.

While I think it should be pretty self-evident that AtD settings won't be used if not using AtD for the spell-checker, I'll update the ticket and mark it as a feature request.
