### ISSUE TITLE
Document social media integration feature

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#905]
It is unclear where and how the Twitter/FB account names are exactly used and how social media integration actually works. Adding Twitter and FB does not seem to have any visual impact e.g. on rendering the Plone default front page

**Comment by hvelarde** [comment]
check the metadata: IIRC, integration inserts Open Graph and Twitter Cards; see [PLIP 20256](https://dev.plone.org/ticket/20256) for more information

**Comment by polyester** [comment]
Now documented in the (beta) plone5 docs. http://docs.plone.org/5/en/adapt-and-extend/config/socialmedia.html
