### ISSUE TITLE
Upgrade-Steps of Products.CMFPlone do not appear in manage_upgrades

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#908]
In http://localhost:8080/Plone/portal_setup/manage_upgrades you were able to run arbitrary upgrade-steps (very useful for debugging). The steps of CMFPlone doe nppear there any more.

**Comment by pbauer** [comment]
@mauritsvanrees maybe you have an diea since you worked on upgrade-steps recently.

**Comment by mauritsvanrees** [comment]
I see them just fine. Maybe you are looking for `Products.CMFPlone:default`? It is `Products.CMFPlone:plone` instead. Screen shots from current Plone 5 coredev, fresh site (same for older site):

![schermafbeelding 2015-09-10 om 14 14 26](https://cloud.githubusercontent.com/assets/210587/9787844/5d2b31be-57c6-11e5-9d49-4fb7c696d00e.png)

![schermafbeelding 2015-09-10 om 14 14 40](https://cloud.githubusercontent.com/assets/210587/9787846/63e80888-57c6-11e5-889e-fab429e03518.png)


![schermafbeelding 2015-09-10 om 14 12 35](https://cloud.githubusercontent.com/assets/210587/9787817/131d366c-57c6-11e5-8cef-d58fe91b78eb.png)

**Comment by pbauer** [comment]
Sorry, my bad. I obviously had some local experimens in my GenericSetup-egg. After deleting my local egg the upgrade-steps are there. Phew! Thanks for checking!
