### ISSUE TITLE
Wide screens have wasted horizontal space

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#912]
Plone one wide display (1900px width) looks like this. Too much space on the left and right side are wasted...why? Thought the the same would be responsive...the theme right now looks more like an old fix-width layout than a modern responsive theme...why can't the complete horizontal space be used? This looks strange and not helpful for application that need to display large amounts of data horizontally e.g. wide tables. 

![out](https://cloud.githubusercontent.com/assets/594239/9790691/b6467cac-57d7-11e5-9cc9-2fd09a5f311b.png)

**Comment by vangheem** [comment]
Please use reasonable issue title. "Half baked and more cumbersome than helpful." Seriously @zopyx You just sound like a troll.

I think the theme is fine. Many sites define max width as content looks funny often if it's stretched very wide. It was a design decision.

More important is how it looks mobile not on wide screens.

I'll change the ticket to sound more reasonable.

**Comment by vangheem** [comment]
@plone/ux-team do you have thoughts on horizontal space?

**Comment by davilima6** [comment]
Theme is fine. Screens can grow indefinitely larger but our eyes won't. Dropping max-width makes for bad readability of text (good pattern is 50-75 characters per line). Besides, having items too widespread makes pointing and clicking harder. Also, people with larger monitors often use multiple narrower windows, browsers included, in response to the issues above. Also see: http://visionpointmarketing.com/blog/entry/maximum-page-width-in-fluid-responsive-design

**Comment by zopyx** [comment]
Is there any official or easy way to get rid of these constraints? If not
then it is not fine. We have at least two sites with extra wide tables
where we need all extra space.

2015-09-10 18:52 GMT+02:00 Davi Lima <notifications@github.com>:

**Comment by davilima6** [comment]
Just change here: https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/variables.plone.less#L130

**Comment by zopyx** [comment]
excellent

2015-09-10 19:25 GMT+02:00 Davi Lima <notifications@github.com>:

**Comment by polyester** [comment]
Closing as
- it is a reasonable default (also default unlimited width would have a11y issues with dyslexic readers)
- it is easily changed TTW in the exposed less variables, should sides want to go extra-wide. Therefore in the hands of the site admin / themer, where it should be.

I'll try to note it down in the theming-docs; help welcome if anybody wants to start a 'useful LESS variables to tweak' document in the docs.
