### ISSUE TITLE
 Menu bar text invisible when State: Pending Review (yellow color)

### ISSUE THREAD

**Issue by petersta** [plone/Products.CMFPlone#913]
When object is in State: Pending Review (yellow color) then the state text in the toolbar is invisible. It becomes visible when hovering cursor over toolbar state entry/icon.

Version Overview:
UBUNTU 14.04 LTS
Firefox 40.0.3
Plone 5.0rc1 (5008)
CMF 2.2.8
Zope 2.13.22
Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
PIL 2.9.0 (Pillow)

**Comment by pabo3000** [comment]
Please check https://github.com/plone/Products.CMFPlone/pull/991. I am not quite sure how to modify less files. I used bin/plone-compile-resources and that changed 12 files.

**Comment by rodfersou** [comment]
@pabo3000 at plonetheme.barceloneta there is a [way to compile less easily](https://github.com/plone/plonetheme.barceloneta/blob/master/HOWTO_DEVELOP.rst) but for Products.CMFPlone I didn't find a configuration like this

**Comment by rodfersou** [comment]
@hvelarde why did you close it?
