### ISSUE TITLE
Live Searching Error: TypeError: Missing.Value is not JSON serializable

### ISSUE THREAD

**Issue by petersta** [plone/Products.CMFPlone#915]
Installed plain Plone site (no advanced options used).
Created Folder Pictures and uploaded via mass Upload about 25 pictures (of birds)
Live searching with criteria like "blonde"  to find "blonde tapuit.jpg" results in:
Found 1 results and Error There was an error searching.

The error is listed below:
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.search, line 216, in __call__
  Module json, line 243, in dumps
  Module json.encoder, line 207, in encode
  Module json.encoder, line 270, in iterencode
  Module json.encoder, line 184, in default
TypeError: Missing.Value is not JSON serializable

Version Overview:
UBUNTU 14.04 LTS
Firefox 40.0.3
Plone 5.0rc1 (5008)
CMF 2.2.8
Zope 2.13.22
Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
PIL 2.9.0 (Pillow)

**Comment by petersta** [comment]
Additional to posting above: the form search with  @@search? finds the document, so that work works.

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/Products.CMFPlone/commit/849bee9ed82856b4e0a1af497012ff8a253e78b9 (the commit-msg is wrong but the changelog is ok)
