### ISSUE TITLE
Url with @@manage-viewlets shows a corrupted layout of the Menu bar

### ISSUE THREAD

**Issue by petersta** [plone/Products.CMFPlone#916]
Using /Plone/@@manage-viewlets shows a corrupted layout of the Menu bar.

Version Overview:
UBUNTU 14.04 LTS
Firefox 40.0.3
Plone 5.0rc1 (5008)
CMF 2.2.8
Zope 2.13.22
Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
PIL 2.9.0 (Pillow)

**Comment by pbauer** [comment]
The reason ist that the toolbar is also a viewletmanager (plone.toolbar, ``plone.app.layout.viewlets.interfaces.IToolbar``) and gets the manage-viewlet-styles applied to it. I don't think it is a real problem. Using the toolbar in @@manage-viewlets makes no sense anyway, If you really want, you could hide the toolbar's content this way. 
![bildschirmfoto 2015-09-10 um 21 30 58](https://cloud.githubusercontent.com/assets/453208/9798742/45b7a94e-5803-11e5-8a2f-036b8b688165.png)

**Comment by sneridagh** [comment]
Now it looks better somehow. It's not useful for people to let it here as a reference and to make it clear that the toolbar components are viewlets. They currently show what they should show and as long it looks acceptable...

<img width="1225" alt="screen shot 2015-09-18 at 14 52 58" src="https://cloud.githubusercontent.com/assets/486927/9959560/394dead4-5e15-11e5-84c7-9cfc0b63472d.png">
