### ISSUE TITLE
TinyMCE -> Insert table -> very small table grid

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#920]
Inserting a 4x4 table through TinyMCE results in a very small table grid...completely unusable.

![screenshot 2015-09-11 09 26 23](https://cloud.githubusercontent.com/assets/594239/9809296/3bba76ba-5867-11e5-9f74-d4cf705e1480.png)

**Comment by davisagli** [comment]
Could maybe be fixed by adding a min-width for tables in the stylesheet.

**Comment by pbauer** [comment]
Duplicate of #755
