### ISSUE TITLE
Date/Time widgets on mobile

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#922]
The handling of the date and time widget on mobile is pretty clumsy. Using the HTML5 input fields would provide a better user experience.

**Comment by thet** [comment]
we cannot use html5 input fields ATM - the browser support is very weak. see: http://caniuse.com/#feat=input-datetime
http://amsul.ca/pickadate.js/ - which we are using - claims to be mobile friendly. looking at a current Plone 5 installation and resizing the browser window, it looks like we have to improve the styles to better support small screens. and make it look better also on normal screens.

**Comment by davisagli** [comment]
Plone 6 classic is now using the HTML5 date inputs.
