### ISSUE TITLE
Toolbar jumps up on iPad when opening a select element

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#923]
See screenshot. The toolbar move a significant part up when you click on a select element within the portlet management (iPad)

![img_0080](https://cloud.githubusercontent.com/assets/594239/9809530/629c2376-5869-11e5-9ef7-8d67a00e8d30.jpg)

**Comment by jensens** [comment]
tried it and it seems to be fixed meanwhile.
