### ISSUE TITLE
Sharing screen: some extra padding needed

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#924]
See screenshot...there should be some extra vertical space between "you can control"
and the following input field.

![screenshot 2015-09-11 09 39 34](https://cloud.githubusercontent.com/assets/594239/9809555/9eef7e40-5869-11e5-9ae3-dbb74dc1e536.png)

**Comment by sneridagh** [comment]
Fixed. Now it looks like:
<img width="883" alt="screen shot 2015-09-18 at 14 46 45" src="https://cloud.githubusercontent.com/assets/486927/9959427/49729492-5e14-11e5-8886-53ad993d49f1.png">
