### ISSUE TITLE
Recursion error in difflib, @@history view

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#929]
Somehow I could mess up the @@history view with some edit operations...

This error seems to occur after copy & pasting look content (50-10k or so) in to the description
and body text fields :-)

Dies ist die vollständige Fehlermeldung:

Zeige Fehlerbericht als Text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFEditions.browser.diff, line 62, in **call**
Module Products.Five.browser.pagetemplatefile, line 125, in **call**
Module Products.Five.browser.pagetemplatefile, line 59, in **call**
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 93, in **call**
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 258, in render
Module chameleon.template, line 191, in render
Module chameleon.template, line 171, in render
Module 92a6ad5c7519bb1cff79d37fe5b71ce4.py, line 1709, in render
Module 6a55c9d329578fcb6268f384673c74bf.py, line 1223, in render_master
Module 6a55c9d329578fcb6268f384673c74bf.py, line 458, in render_content
Module 92a6ad5c7519bb1cff79d37fe5b71ce4.py, line 1124, in __fill_main
Module Products.CMFDiffTool.TextDiff, line 54, in html_diff
Module difflib, line 1980, in make_table
Module difflib, line 1848, in _collect_lines
Module difflib, line 1825, in _line_wrapper
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
Module difflib, line 1809, in _split_line
RuntimeError: maximum recursion depth exceeded in cmp - Expression: "python:diff.html_diff(wrapcolumn=80) if exists_html_diff else ''" - Filename: ... ns-2.2.14-py2.7.egg/Products/CMFEditions/browser/diff.pt - Location: (line 127: col 42) - Source: ... python:diff.html_diff(wrapcolumn=80) if exists_html_diff else '' ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) template: <ViewPageTemplateFile - at 0x7fb084f76e10> views: <ViewMapper - at 0x7fb08285cf90> modules: <instance - at 0x7fb08c737200> args: <tuple - at 0x7fb09d6bb050> here: <ImplicitAcquisitionWrapper -1 at 0x7fb086c773c0> user: <ImplicitAcquisitionWrapper - at 0x7fb086c77820> loop: {...} (2) nothing: <NoneType - at 0x784160> container: <ImplicitAcquisitionWrapper -1 at 0x7fb086c773c0> request: <instance - at 0x7fb082cc0ab8> wrapped_repeat: <SafeMapping - at 0x7fb082da7ec0> traverse_subpath: <list - at 0x7fb082cc56c8> default: <object - at 0x7fb09d691bc0> context: <ImplicitAcquisitionWrapper -1 at 0x7fb086c773c0> view: <DiffView history at 0x7fb08285c910> translate: <function translate at 0x7fb08300a9b0> root: <ImplicitAcquisitionWrapper Zope at 0x7fb086740af0> options: {...} (0) target_language: <NoneType - at 0x784160>

**Comment by jensens** [comment]
@zopyx is this still an issue in 5.2?

**Comment by zopyx** [comment]
No idea how to reproduce after four years

**Comment by jensens** [comment]
so this issue has no value to be kept open anyway
