### ISSUE TITLE
UnicodeWarning in @@sharing view

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#930]
Searching for a user with accented chars e.g.

'üöä'

causes the following message on the console (however no error within the UI).

/home/ajung/.buildout/eggs/plone.app.workflow-2.2.3-py2.7.egg/plone/app/workflow/browser/sharing.py:364: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if not search_term or search_term == translated_message:

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.workflow/commit/24d47b45e8a80b670796d35e9b07dd3c5780bcf4
