### ISSUE TITLE
Missing CSRF protection in group administration

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#934]
I am on the URL

../Plone2/@@manage-group-dashboard?key=None

and click on the tab "Group Portlets"

This redirects to 

/Plone2/@@confirm-action?key=None&original_url=http%3A%2F%2Fdev1.veit-schiele.de%3A8080%2FPlone2%2F%40%40manage-group-portlets

with an form with "Confirm action" button...looks as if some CSRF protection is missing here...

**Comment by ichim-david** [comment]
Not exactly the same thing but I found a bug regarding CSRF protection when editing a record from the registry.
Attempting to save gave an error, attempting to hit cancel gave an error from the overlay.
Luckily hitting escape closes the overlay.
I think overlays should be tested more for potential CSRF protection errors on form  submits.

**Comment by jensens** [comment]
tried this from the groups settings form and all worsk w/o problems in 5.2
