### ISSUE TITLE
prefs_error_log_form does not validate #entries 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#936]
@@prefs_error_log_form

a non numeric value for "Number of exceptions to keep" causes this

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFCore.FSPythonScript, line 127, in **call**
Module Shared.DC.Scripts.Bindings, line 322, in **call**
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.PythonScripts.PythonScript, line 344, in _exec
Module script, line 5, in prefs_error_log_setProperties
<FSPythonScript at /Plone2/prefs_error_log_setProperties>
Line 5
Module Products.SiteErrorLog.SiteErrorLog, line 254, in setProperties
ValueError: invalid literal for int() with base 10: '\xc3\xbc\xc3\xb6\xc3\xa4'

Likely the form should validate the values as supposed in all other forms of the site setup.

**Comment by jensens** [comment]
is this still an issue?

**Comment by zopyx** [comment]
Working in 5.2
