### ISSUE TITLE
Syndication control panel issues

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#938]
It is possible to enter a negative number of "Maximum items".
After saving the setting Plone redirects to @@overview-controlpanel instead to the same page (as it happens with all other control panel forms).

**Comment by pbauer** [comment]
Why would anyone enter a negative value here and expect a result? 
The redirect is fixed in https://github.com/plone/Products.CMFPlone/commit/41307684e90b745eaf35c59bade9b3265ea16e09

**Comment by zopyx** [comment]
Why should it be allowed?
That's why we have validator?

Sent from a mobile device

**Comment by hvelarde** [comment]
@esteele I think @zopyx has a point, form validation is easy and is basic stuff; you should not close this ticket until addressed.

**Comment by vangheem** [comment]
PR https://github.com/plone/Products.CMFPlone/pull/977

**Comment by vangheem** [comment]
Discussion: https://community.plone.org/t/why-do-we-validate-form-fields/948
