### ISSUE TITLE
Time widget is far from optimal

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#945]
Displaying time options as a two-column list makes difficult to select quickly the time; for instance, if I want to set a time near midnight I have to scroll all the way down; same happens if I just want to clear the time:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9816508/cfd4e180-5873-11e5-8df9-d491c6673560.png)

**Comment by davilima6** [comment]
Plone 4 widget was way simpler (also lighter/native). We can learn with it: left column for hours and right one for minutes.

**Comment by davisagli** [comment]
In Plone 6 we use the browser datetime widget (`<input type="datetime-local">`)
