### ISSUE TITLE
Personal tools overflow when using horizontal toolbar

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#946]
the options on the menu are out of the viewable screen:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9816949/737c4678-5876-11e5-9f82-1b12ad4198f2.png)

**Comment by davilima6** [comment]
I confirm this. Probably ain't broken only in English, cause words are so short.

Solution would be setting popover [data-placement](http://getbootstrap.com/javascript/#popovers-examples) to `left` or `auto`.

**Comment by ichim-david** [comment]
I was playing into solving this with css by setting right: 0.
At least for a media-query of max 1200 it would be best to have this. 
If it goes over 1200 then it will stick to the edge.

A better fix would probably be to give instructions where to place it but 
this might be solvable with css as well

**Comment by hvelarde** [comment]
@ichim-david I think this can be solved using a different alignment here; see http://www.redebrasilatual.com.br/ as an example (the red menu item).

**Comment by hvelarde** [comment]
Plone 5.0.4 and this is still happening.

**Comment by davisagli** [comment]
Plone 6 no longer provides a horizontal variation of the toolbar.
