### ISSUE TITLE
Sorting in control panel menu lists

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#947]
List sorting inside the categories should be done in alphabetical order as it's way easier to find stuff there.

This is related with #721 but not the same issue.

![selection_005](https://cloud.githubusercontent.com/assets/341393/9817165/9e0a277e-5877-11e5-9de9-cf5578d7d7b3.png)

**Comment by davilima6** [comment]
Couldn't agree more, it's simply English-centric the way it is. Besides I think these lists are an additional reason not to have items sorted by visual clues/icons (we don't want ordering to be different).

I can feel the pain of people dealing with multiple languages, but maybe that could be solved alternatively? E.g. adding a quick switch for most used/alpha sorting (which would reflect in the sidelists).

**Comment by vangheem** [comment]
Duplicate of https://github.com/plone/Products.CMFPlone/issues/721

**Comment by hvelarde** [comment]
Is not duplicated, is another issue.

**Comment by pbauer** [comment]
I don't get it, how is this a different issue?

**Comment by hvelarde** [comment]
@pbauer because #721 is about the icons showed on the control panel page and this one is about the list displayed at the right side of every configlet.

**Comment by polyester** [comment]
It is the same issue, these two are sorted exactly the same. And as noted in https://github.com/plone/Products.CMFPlone/issues/721, it is currently not sorted by English either. 

The actual sorting decision should be made based later, and on some more research. Sorting the right-hand list differently than the icon list is not good from usability perspective. It could be that the most 'advanced' options, which are now purposefully at the end, would end up first.

**Comment by hvelarde** [comment]
I don't agree; the control panel list has icons and that's what makes it different from the list on the configlets right side; a list must be sorted alphabetically almost all the time; with icons, is different.

also, I don't agree on having issues reporting more than one bug or features request: most of the time what happens is that the issue is closed leaving behind things unsolved.

**Comment by polyester** [comment]
We indeed disagree. For a11y and ux reasons, it is much easier to know that "users and groups" can always be found as the first link in the "Users" grouping, rather than as the sometimes-17th, sometimes-23th link in a long list, depending on how many add-ons were installed. That would force users to tab through all of them repeatedly, because you will never know where they are.

Long lists should be divided up *semantically*; we can argue about the semantics. But alphabetically is definitely not always the best option.

**Comment by jensens** [comment]
this listing should use the icons and follow the same sorting as in the panel view.

**Comment by hvelarde** [comment]
marking it as duplicate then.
