### ISSUE TITLE
Fields related with anonymous users should be side by side

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#948]
This is related to the discussion control panel configlet.

IMO, fields that are related should be better organized if they are side by side:

![selection_006](https://cloud.githubusercontent.com/assets/341393/9817294/5926e600-5878-11e5-81da-07e1d27dc9e5.png)

**Comment by davilima6** [comment]
+1. Email for anonymous field should be moved up.

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.discussion/commit/b7f81fc3fe595ea0ec727c6c121598e6f4e86b6b
