### ISSUE TITLE
Missing language related resources

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#949]
This 404 status codes are returned when creating a new News Item on a site in Brazilian Portuguese language:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9817476/81fce632-5879-11e5-8fb9-f58e0693b40e.png)

**Comment by claytonc** [comment]
Is not properly translating into Portuguese Brazil.

* 404 when or returns null:
    - http://localhost:8080/Plone/plonejsi18n?domain=widgets&language=pt-br

* But when 200 returns:
    - http://localhost:8080/Plone/plonejsi18n?domain=widgets&language=pt_BR

* In the image above there request 404 also occurs to me.
    - http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/pt-br.js
    - http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/pt-br_PT-BR.js

* In folder "https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/static/components/tinymce-builded/js/tinymce/langs". 
    - there are no files "pt-br.js" or "pt-br_PT-BR.js".
    - but when you add the above files the tinyMCE is translated.

**Comment by claytonc** [comment]
In "self.request ['LANGUAGE']" always behind "pt-br" for java scripts

**Comment by claytonc** [comment]
The problem of translation in the TinyMCE editor in this file "mockup/patterns/tinymce/pattern.js".

I did some modifications but do not know if it's the ultimate solution.

The javascript "pattern.js" always looking for translations with "en-bt" and the file is "en_US".

An error was found when invoked "self.options.tiny.language" the value is undefined.

[pattern.js.diff.txt](https://github.com/plone/Products.CMFPlone/files/11005/pattern.js.diff.txt)

**Comment by claytonc** [comment]
And in "/mockup/js/i18n.js"

Widgets (Upload) in folder_contents translated.

@@ -64,6 +64,9 @@ define([
     };
 
     self.getUrl = function(domain, language) {
+      if (language.split('-').length > 1) {
+        language = language.split('-')[0] + '_' + language.split('-')[1].toUpperCase();
+      }
       return self.baseUrl + '?domain=' + domain + '&language=' + language;
     };

![image-tiny](https://cloud.githubusercontent.com/assets/1719539/10404251/c362e61e-6ea7-11e5-8856-fb01ee82ff57.png)
![imagem-folder_contents](https://cloud.githubusercontent.com/assets/1719539/10404250/c35d2152-6ea7-11e5-9bc9-3d9de7285777.png)

**Comment by claytonc** [comment]
No more 404 in languages.

**Comment by jensens** [comment]
is this still an issue?

**Comment by hvelarde** [comment]
we need to check again when 5.0.5 is out.

**Comment by davilima6** [comment]
It is in 5.1a2-pending.

**Comment by malthe** [comment]
This is still relevant.

It's looking for things like `en_EN.js` and `sv_SV.js` (the latter should be `sv_SE.js`).

**Comment by agitator** [comment]
same here with ch_DE, although it's "only" the users selected lang, the site itself runs und plain de

**Comment by lyralemos** [comment]
This is still a problem even in 5.1rc1.

I tried changing "/mockup/js/i18n.js" like @claytonc said, but it made no difference. Several parts of the UI still in English.

It's been 3 years since the original post, does anyone have an idea on how to solve this?

**Comment by lyralemos** [comment]
Just installed 5.1.0.1 and this is still a issue.

**Comment by thet** [comment]
@malthe checked against your sv_SE comment - in plone.app.locales there is no sv_SE variant - only ``sv``.
