### ISSUE TITLE
Wrong og:site_name generated markup

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#951]
I added a news item to a site and looked at the social markup included on it; there's issues with the `og:site_name` tag:

```xml
<meta content="Extra! Extra! Read all about it &amp;mdash; Site" property="og:site_name" />
```

According to the specification, that value should be the name of the site and not the title of the object.

*og:site_name - If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb".*

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.layout/commit/c71658832dfcf934d6e7369c806174864bd009b1
