### ISSUE TITLE
Short name (id) present on edit form even when explicitly requested not to be shown

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#958]
On the edit settings we have not selected to show the short name:

![selection_006](https://cloud.githubusercontent.com/assets/341393/9821751/b430f472-5892-11e5-90c9-4c77523014ae.png)

But it's present when editing an item:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9821752/b450432c-5892-11e5-8d7d-a9d61daf1519.png)

**Comment by vangheem** [comment]
Did this get moved to behaviors per type? Does dexterity care about this settings? Has it ever?

**Comment by hvelarde** [comment]
now that you mentioned it, there is a behavior for this, but it should obey the global settings:

![selection_010](https://cloud.githubusercontent.com/assets/341393/9823124/c7987000-589a-11e5-9e65-3a449b1dfade.png)

**Comment by djay** [comment]
I'd be in favour of removing the global option to simplify things. I know
it creates another backwards incompatibility but behaviours is a more
obvious place to look for it.

**Comment by vangheem** [comment]
deprecated settings are better than settings no one is going to fix...

**Comment by vangheem** [comment]
https://github.com/plone/Products.CMFPlone/pull/968 is ready for whenever we have some consensus.

**Comment by pbauer** [comment]
:+1: for dropping the global option

**Comment by pbauer** [comment]
merged
