### ISSUE TITLE
Broken link on manage content type portlets

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#959]
On Content Settings configlet, select any content type and then select Manage Portlets:

![selection_007](https://cloud.githubusercontent.com/assets/341393/9821908/d4f5da28-5893-11e5-96c1-831f15f33744.png)

Select Return:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9821907/d4a10c32-5893-11e5-9cdf-f13f84f6a258.png)

You'll get an 404 error page:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9821909/d5007726-5893-11e5-8380-c9ef85559c07.png)

**Comment by davilima6** [comment]
Btw this reminds @@manage-portlets is not completely hidden from UI (refs #846).

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/plone.app.portlets/commit/e018dee0e0e98082dc0c6ae2407eab12be2474b9
