### ISSUE TITLE
Remove SecureMailHost

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#965]
Products.SecureMailHost host not really been used since Plone 4.0

There are three places that still mention it:
- https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patches/securemailhost.py says at the top: "This module provides backwards compatiblity for products using the
  SecureMailHost API.  It should be removed entirely for Plone 5.0."
- https://github.com/plone/plone.app.testing/blob/master/plone/app/testing/layers.py#L62 loads its zcml.
- https://github.com/plone/plone.app.upgrade/blob/master/setup.py#L75 has in its `install_requires`:         `'Products.SecureMailHost', # For migration only, when can we remove this?`

Note that there were already some tries to get rid of this, but this failed, perhaps because too many patches were removed at once. See issue #109. So it may be more tricky than it sounds.

Note also that I have just move SecureMailHost out of the plone subversion collective into github, in case anyone needs it: https://github.com/collective/Products.SecureMailHost

**Comment by thet** [comment]
+1 for removing this package. as i see, this
1) needs help,
2) needs an plone.app.upgrade story plan,
3) needs a fix for #1208 too and
4) is a PLIP as it changes the API, even if there was an agreement on that some time ago.

**Comment by tkimnguyen** [comment]
@thet item 3 above has been fixed (#1208)

**Comment by thet** [comment]
Great! PLIP not needed - i just saw in the cmfplone patch that there was already a deprecation warning. Not sure about the upgrade thing - if the product didn't install some persistent tool, we can just remove all the securemailhost references.

**Comment by jensens** [comment]
can we close this one?

**Comment by thet** [comment]
First, we need a PR which removes what @mauritsvanrees mentioned, not?

**Comment by mauritsvanrees** [comment]
plone.app.dexterity uses `secureSend` in documentation a few times. I have removed that: https://github.com/plone/plone.app.dexterity/commit/48da045a46846f9c3c33d8cb7a67b4b97ff7d0c5

**Comment by mauritsvanrees** [comment]
I grepped through code in community packages that I have locally, and only found plone.app.dexterity (fixed) and collective.contentrule.mailtorole (issue created) that used secureSend.
Well, a few more that use secureSend as fallback when they see it is needed, like an [older version of collective.watcherlist](https://github.com/collective/collective.watcherlist/blob/1.2/collective/watcherlist/mailer.py#L13) and collective.confirmableforms.

In Plone 4.0 alpha we [replace old secure mailhosts with a standard one](https://github.com/plone/plone.app.upgrade/blob/1.3.27/plone/app/upgrade/v40/alphas.py#L427) so old instances should be no problem.

Products.PloneTestCase installs Products.SecureMailHost, but we can probably ignore that. plone.app.testing tries to import it, and when that succeeds it loads the zcml. We can do the same in PloneTestCase.

collective.contentrules.mailtorole and collective.confirmableforms would need to stop importing SecureMailHost, if only in tests. No problem.

**Comment by mauritsvanrees** [comment]
Okay, I have created pull request #1777 for this.

If that gets merged, then SecureMailHost is still being pulled in, but only by plone.app.upgrade, which does that to be able to migrate SecureMailHost objects to standard MailHost objects in v40 alpha. So basically we can only remove this dependency when we no longer support upgrading from Plone 3 to Plone 5.1 in one step. That is something for a different issue.

**Comment by mauritsvanrees** [comment]
All uses of SecureMailHost have been removed from Plone 5.1.
Let's leave the patch in place in 5.0: it doesn't seem a good idea to suddenly remove it in 5.0.7.
