### ISSUE TITLE
Change of default view of folder works only for logged in user

### ISSUE THREAD

**Issue by vincero** [plone/Products.CMFPlone#969]
On a Plone 5rc1 site I created a folder as admin and published it. Then put some content (images) into this folder. Then changed the default view e.g. to album view. OK for logged in user. For anonymous the view does not change to the new one.

**Comment by vangheem** [comment]
Can you give details on how to reproduce this? I can not reproduce.

**Comment by vincero** [comment]
We created yesterday a new Plone Demo Site with Plone 5rc1:
http://demo.plone.de

Create there a new folder as admin,
publish that folder,
put e.g. a JPG-file into the folder,
change the default display for the folder e.g. to album view

Then for a logged in user everything works correct.

A user who is not logged in to the site will not see the album view for 
that folder, but the default view with which the folder has been created.


Am 12.09.2015 um 15:12 schrieb Nathan Van Gheem:
>
> Can you give details on how to reproduce this? I can not reproduce.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/Products.CMFPlone/issues/969#issuecomment-139767438>.
>


-- 
MAX JAKOB                               Tel: ++49-89-2180-9301
Ludwig-Maximilians-Universitaet         Fax: ++49-89-2180-9338
Institut fuer Informatik                Oettingenstr. 67
                                         D-80538 Muenchen

**Comment by polyester** [comment]
@vincero, could you double-check if caching is not the issue here?

I've tried re-creating the issue as well, writing some robot-tests in the proceedings, and also cannot reproduce.

**Comment by vincero** [comment]
I noticed that the problem only appears when plone.app.caching is enabled (in RC2):

- create a folder, put some content into the folder
- change the folder view e.g. to album view
     --> OK
- change the folder view again to another view
     --> Now an anonymous user does not get the new view

In the latest coredev buildout this error does not occur anymore. So it seems to be solved.
