### ISSUE TITLE
Migrate Rename/Copy/Cut/Paste/Delete

### ISSUE THREAD

**Issue by eleddy** [plone/Products.CMFPlone#97]
I'm not sure if this is addressed in the new folder listing plip or not. Please coordinate with them to see if its already re-implemented. If not, move to a utility or something. I swear @vangheem has this code already... somewhere...

Note that this is referenced from folder_contents, and that will need to be updated to reflect the new paths.

Files Rename: 

 * Products/CMFPlone/skins/plone_scripts/folder_rename.cpy
 * Products/CMFPlone/skins/plone_scripts/object_rename.py
 * Products/CMFPlone/skins/plone_scripts/folder_rename.cpy.metadata
 * Products/CMFPlone/skins/plone_forms/folder_rename_form.cpt
 * Products/CMFPlone/skins/plone_forms/folder_rename_form.cpt.metadata
 * Products/CMFPlone/skins/plone_form_scripts/validate_folder_rename.vpy

Files Copy:

* Products/CMFPlone/skins/plone_scripts/folder_copy.cpy
* Products/CMFPlone/skins/plone_scripts/folder_copy.cpy.metadata
* Products/CMFPlone/skins/plone_scripts/object_copy.cpy
* Products/CMFPlone/skins/plone_scripts/object_copy.cpy.metadata

Files Cut:

* Products/CMFPlone/skins/plone_scripts/folder_cut.cpy
* Products/CMFPlone/skins/plone_scripts/folder_cut.cpy.metadata
* Products/CMFPlone/skins/plone_scripts/object_cut.cpy
* Products/CMFPlone/skins/plone_scripts/object_cut.cpy.metadata

Files Paste:

* Products/CMFPlone/skins/plone_scripts/folder_paste.cpy
* Products/CMFPlone/skins/plone_scripts/folder_paste.cpy.metadata
* Products/CMFPlone/skins/plone_scripts/object_paste.cpy
* Products/CMFPlone/skins/plone_scripts/object_paste.cpy.metadata

Files Delete:

* Products/CMFPlone/skins/plone_scripts/folder_delete.cpy
* Products/CMFPlone/skins/plone_scripts/folder_delete.cpy.metadata
* Products/CMFPlone/skins/plone_scripts/object_delete.cpy.metadata
* Products/CMFPlone/skins/plone_scripts/object_delete.cpy

**Comment by pbauer** [comment]
https://github.com/plone/plone.app.dexterity/issues/73 is fixed in https://github.com/plone/plone.app.content/commit/498634. The same still has to be done with regards to the new folder_contents
