### ISSUE TITLE
"Filter results" popup needs some CSS love

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#982]
Some padding between fields and labels is needed..
![screenshot 2015-09-14 18 48 28](https://cloud.githubusercontent.com/assets/594239/9855921/a4949088-5b11-11e5-9b01-3a0e5005ae00.png)

**Comment by rodfersou** [comment]
@zopyx here at Chromium and Firefox it looks fine

**Comment by rodfersou** [comment]
@zopyx I added a little space to make sure it will look fine on any browser
