### ISSUE TITLE
The Plone logo on left sidebar is doing nothing

### ISSUE THREAD

**Issue by prakharjoshi** [plone/Products.CMFPlone#988]
When we visit some page on Plone say ``http://0.0.0.0:8080/pjoshi/@@personal-preferences`` we see this as a side bar 
![bug1](https://cloud.githubusercontent.com/assets/6854139/9903790/d3d51792-5c96-11e5-8d22-8c54a2128a42.png)

And when we click on the plone logo on the top of side bar it should take us back to home page, right ?

But it just expands the sidebar like this 
![bug2](https://cloud.githubusercontent.com/assets/6854139/9903814/f509d786-5c96-11e5-956b-e3be91f497d7.png)

As this logo on front page is use to show the names of the logos on the side bar but what if there are no logo's in the sidebar as the above mentioned case here I don't think there is a need of expansion of sidebar ?

**Comment by pbauer** [comment]
The logo expands and contracts the sidebar. If there are no items in the sidebar except the personalbar that looks weird but is ok (the loginname appears which is cool). I would not change the bahavior.

**Comment by hvelarde** [comment]
that's why we need to move the option to expand/collapse the toolbar out of there (#807); the Plone logo makes absolutely no sense on the toolbar and can be removed, IMO.

**Comment by sneridagh** [comment]
-1 for that, this setting should be user related, not global.
For the usage of the logo, I found it appropiate because with it we add some distinctive branding to a Plone based site (which ideally won't have another Plone logo at its side).

**Comment by prakharjoshi** [comment]
Ok got it. @pbauer  Yeah its okay if it shows the username on expansion :)

**Comment by hvelarde** [comment]
@sneridagh and what was what I said in #807? that should be on the personal preferences form.

guys, please follow all the related issues, otherwise you're having a partial view of the whole picture and you tend to give partial solutions to the problems; yes, it takes time, but we need to do it.

**Comment by bloodbare** [comment]
I personally like that its there in order to have live switching, we have some plone 5 sites in production, and they love to be able to switch when they want.

**Comment by hvelarde** [comment]
@bloodbare that some people love that doesn't mean that's a good idea :-)

**Comment by fulv** [comment]
I like it, too.  Especially the fact that it gives a consistent Plone
personality to all sites regardless of theme (unless a themer customizes
the toolbar).

**Comment by davilima6** [comment]
+1 for keeping the switching functionality but I also agree with @hvelarde it's design unwise to have repeated logo when all that is needed is a handler or universally recognizable icon for expanding/contracting (arrows?).

**Comment by davisagli** [comment]
The logo won't be repeated in any site that has customized the logo for the site itself (i.e. almost any real world deployment). In that case it's good to have the Plone logo in the toolbar to promote the Plone brand.

**Comment by fulv** [comment]
No custom theme is going to keep the Plone logo in the page header, so it's
not really repeated in actual use cases.

**Comment by davilima6** [comment]
Imo the ootb experience is also important. Think http://demo.plone.de/ or any conference talk, recorded screencast or Plone training. Most times we'll be showcasing Plone, Vanilla is what we'll have and what we will show. Logo will be repeated in all pages.

Regarding Plone branding, it's an interesting take but a new strategy afaik. Plone used to have a more permissive approach about its logo being always visible (eg: colophon), so my question is, do you think it's worth to sustain the repetition for usecases like the above (ootb xp)?

**Comment by djay** [comment]
There is no repeated logo. No one is going to keep the theme plone logo.
Its going to get themed.
I agree its not intuitive but I also agree its a nice touch keeping the
plone logo in the toolbar. I think some kind of indication might help but
at the same time everything works without it expanded. People will discover
it eventually. Could be nice if click on the toolbar background also
expanded it to make it more discoverable.

**Comment by hvelarde** [comment]
using a Plone logo to toggle the toolbar is a bad design decision because is an inconsistent user interface; is an Easter egg, as @davilima6 said before.

on a Plone site, if I select a Plone logo I would expect one of two things: going to the home page, or going to the Plone site.
