### ISSUE TITLE
Bundle builder modal needs vertical scrollbars

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#994]
The modal is way too large; probably we can get rid of the horizontal toolbar also if w make the modal a little bit wider:

![imagem da pagina 2015-09-16 - 12 24 35](https://cloud.githubusercontent.com/assets/341393/9909399/6c64783c-5c6e-11e5-8981-91a98cd3b17d.png)

**Comment by davilima6** [comment]
Build results could be displayed retracted with an arrow for expanding/contracting full results.

**Comment by davisagli** [comment]
Through-the-web compilation of bundles has been removed in Plone 6
