### ISSUE TITLE
Extra useless options on Site Settings configlet

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#996]
The `Empty` option on both fields here makes no sense:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9909638/6d2ecbf4-5c6f-11e5-8439-400115d75207.png)

![selection_004](https://cloud.githubusercontent.com/assets/341393/9909525/feee21b2-5c6e-11e5-84c0-65b69234d12f.png)

**Comment by hvelarde** [comment]
I think this happens because the fields are not marked as `required` in the form.

**Comment by davilima6** [comment]
Isn't this the same? https://github.com/plone/Products.CMFPlone/issues/944#issuecomment-139573744

**Comment by hvelarde** [comment]
no, that one is on the Discussion configlet.
